
# Hand-coded solution reachability: train exactly two models

This notebook answers one precise question:

> The PROCESS and OUTCOME hand-coded Transformers already achieve 100% accuracy.  
> If we keep **each exact hand-coded architecture**, randomize its weights, and train it with its natural supervision, does gradient descent recover a 100%-accurate solution?

We train exactly **two models**:

| Trainable model | Architecture | Training target |
|---|---|---|
| `process_random_base` | exact `HandcodedProcessTransformer` layout | PROCESS / trace continuation |
| `outcome_random_base` | exact `HandcodedOutcomeTransformer` layout | OUTCOME-only continuation |

The two fixed hand-coded models are **references only** and are never optimized.

So the experiment is

\[
\boxed{
\text{2 fixed 100\% references}
+
\text{2 randomly initialized trainable models}
}
\]

with only the latter two undergoing gradient updates.

This is a **reachability experiment**, not yet an architecture-matched causal comparison between PROCESS and OUTCOME.


## 1. Imports and configuration

This notebook uses `handcoded_utils.py`, which contains the exact circuit generator, tokenizer, hand-coded architectures, training loop, and free-running evaluator.

In [1]:

import copy
import importlib
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

import handcoded_utils
importlib.reload(handcoded_utils)

from handcoded_utils import (
    BATCH_SIZE,
    BATCH_SEED,
    DATA_SEED,
    DEPTH,
    LR,
    MODEL_SEED,
    TEST_SEED,
    TEST_SIZE,
    TRAIN_SIZE,
    HandcodedOutcomeTransformer,
    HandcodedProcessTransformer,
    encode_dataset,
    free_run_metrics,
    generate,
    language_model_loss,
    make_batch_schedule,
    make_checkpoints,
    make_circuit_prompts,
    make_circuits,
    make_generation_evaluation,
    make_random_trainable_copy,
    make_tokenizer,
    train_one_model,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Main experiment settings.
N_TRAIN = TRAIN_SIZE
N_TEST = TEST_SIZE
STEPS = 2_000
LOSS_EVAL_SIZE = 64
CHECKPOINTS = make_checkpoints(STEPS, animation_checkpoints=40)

print("device:", DEVICE)
print("depth:", DEPTH)
print("train examples:", N_TRAIN)
print("test examples:", N_TEST)
print("steps:", STEPS)
print("loss eval examples:", LOSS_EVAL_SIZE)

device: cuda
depth: 4
train examples: 20000
test examples: 1000
steps: 2000
loss eval examples: 64

/home/hariguru/aayus/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# injected by run_seeds.py -- vary model init only
MODEL_SEED = 46
_OUT_JSON = '/home/hariguru/aayus/trace/results/reachability_seeds/seed_46.json'
print('MODEL_SEED =', MODEL_SEED)

MODEL_SEED = 46


## 2. Build the same dataset for both models

A circuit is

$$
s_t=\Phi(s_{t-1},g_t),\qquad t=1,\ldots,D.
$$

Both models receive the same prompt

```text
S0 g1 g2 ... gD <SEP>
```

but their supervised continuations differ.

PROCESS:

```text
g1 S1 g2 S2 ... gD SD <COLON> SD <EOS>
```

OUTCOME:

```text
<COLON> SD <EOS>
```

The underlying circuits, train/test split, and minibatch schedule are shared.

In [3]:

tokenizer = make_tokenizer()

train_circuits = make_circuits(N_TRAIN, DATA_SEED, DEPTH)
test_circuits = make_circuits(N_TEST, TEST_SEED, DEPTH)
example = test_circuits[0]

training_data = {
    mode: encode_dataset(train_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

# Held-out teacher-forced loss uses the test split. The training helper samples
# a deterministic prefix of this batch at checkpoints for speed.
test_loss_data = {
    mode: encode_dataset(test_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

batch_schedule = make_batch_schedule(
    N_TRAIN, STEPS, BATCH_SIZE, BATCH_SEED
)

train_eval = make_generation_evaluation(
    train_circuits[:min(300, len(train_circuits))],
    tokenizer,
    DEVICE,
)

test_eval = make_generation_evaluation(
    test_circuits,
    tokenizer,
    DEVICE,
)

circuit_prompts = make_circuit_prompts(
    example.gates,
    tokenizer,
    DEVICE,
)

print("Prompt :", tokenizer.decode(tokenizer.prompt(example)))
print("PROCESS:", tokenizer.decode(tokenizer.continuation(example, "process")))
print("OUTCOME:", tokenizer.decode(tokenizer.continuation(example, "outcome")))

Prompt : S1011 s02 c31 c31 t302 <SEP>
PROCESS: s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>
OUTCOME: <COLON> S1001 <EOS>


## 3. Fixed hand-coded references

These two models encode perfect algorithms directly in their weights.

### PROCESS reference

`HandcodedProcessTransformer`

- one causal attention/MLP block,
- four fixed attention heads,
- one ReLU unit for each `(state, gate)` pair,
- autoregressive reuse of the same block to emit intermediate states.

### OUTCOME reference

`HandcodedOutcomeTransformer`

- one causal attention/MLP block per circuit step,
- two attention heads per block,
- intermediate states remain internal to the residual stream,
- only the final answer is emitted.

They are not trained below. They establish that a 100% solution exists in each architecture class.

In [4]:

process_reference = HandcodedProcessTransformer(
    tokenizer, DEPTH
).to(DEVICE)

outcome_reference = HandcodedOutcomeTransformer(
    tokenizer, DEPTH
).to(DEVICE)

reference_rows = []

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    reference_rows.append({
        "model": name,
        "mode": mode,
        "answer_accuracy": metrics["final_answer"],
        "exact_continuation": metrics["exact_continuation"],
    })

pd.DataFrame(reference_rows)

           model     mode  answer_accuracy  exact_continuation
0  Fixed PROCESS  process              1.0                 1.0
1  Fixed OUTCOME  outcome              1.0                 1.0


Expected result:

$$
\operatorname{Acc}(\theta^\star_{\rm P})
=
\operatorname{Acc}(\theta^\star_{\rm O})
=
100\%.
$$

That is the realizability baseline.


## 4. Turn each exact hand-coded architecture into a random trainable model

This is the crucial correction.

We do **not** call `build_random_learned_model()`. That would create an unrelated ordinary one-layer Transformer.

Instead, `make_random_trainable_copy()`:

1. deep-copies the exact hand-coded model,
2. converts its stored weight buffers into `nn.Parameter`s,
3. randomly initializes those tensors.

Therefore the computational graph and tensor layout are inherited directly from the corresponding constructive model.

In [5]:

process_random_base = make_random_trainable_copy(
    process_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

outcome_random_base = make_random_trainable_copy(
    outcome_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

def trainable_params(model):
    return sum(p.numel() for p in model.parameters())

def stored_scalars(model):
    return sum(t.numel() for t in model.state_dict().values())

summary = pd.DataFrame([
    {
        "model": "Fixed PROCESS reference",
        "trainable_parameters": trainable_params(process_reference),
        "stored_scalars": stored_scalars(process_reference),
        "max_length": process_reference.max_length,
    },
    {
        "model": "Random trainable PROCESS architecture",
        "trainable_parameters": trainable_params(process_random_base),
        "stored_scalars": stored_scalars(process_random_base),
        "max_length": process_random_base.max_length,
    },
    {
        "model": "Fixed OUTCOME reference",
        "trainable_parameters": trainable_params(outcome_reference),
        "stored_scalars": stored_scalars(outcome_reference),
        "max_length": outcome_reference.max_length,
    },
    {
        "model": "Random trainable OUTCOME architecture",
        "trainable_parameters": trainable_params(outcome_random_base),
        "stored_scalars": stored_scalars(outcome_random_base),
        "max_length": outcome_random_base.max_length,
    },
])

summary

,model,trainable_parameters,stored_scalars,max_length
0,Fixed PROCESS reference,0,441664,16
1,Random trainable PROCESS architecture,441664,441664,16
2,Fixed OUTCOME reference,0,3588000,8
3,Random trainable OUTCOME architecture,3588000,3588000,8


A fixed reference reports zero **trainable** parameters because its constructed weights are registered as buffers. That does not mean it has zero weights. `stored_scalars` is the more relevant size diagnostic for the fixed models.


## 5. Sanity check: the trainable parameterization really contains the oracle

A useful stronger check is to convert the fixed buffers into trainable parameters **without changing their values**.

If the resulting model produces exactly the same logits as the fixed model, then the hand-coded optimum literally lies inside the trainable parameterization.

In [6]:

def make_trainable_oracle_copy(model, device):
    trainable = copy.deepcopy(model).cpu()

    def convert(module):
        for name, buffer in list(module._buffers.items()):
            if buffer is None:
                continue
            value = buffer.detach().clone()
            del module._buffers[name]
            module.register_parameter(name, torch.nn.Parameter(value))
        for child in module.children():
            convert(child)

    convert(trainable)
    return trainable.to(device)


process_oracle_trainable = make_trainable_oracle_copy(
    process_reference, DEVICE
)
outcome_oracle_trainable = make_trainable_oracle_copy(
    outcome_reference, DEVICE
)

prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

with torch.no_grad():
    process_error = (
        process_reference(prompt) - process_oracle_trainable(prompt)
    ).abs().max().item()

    outcome_error = (
        outcome_reference(prompt) - outcome_oracle_trainable(prompt)
    ).abs().max().item()

print("PROCESS max logit difference:", process_error)
print("OUTCOME max logit difference:", outcome_error)

assert process_error == 0.0
assert outcome_error == 0.0

PROCESS max logit difference: 0.0
OUTCOME max logit difference: 0.0


This gives the precise existence statement:

\[
\exists\,\theta^\star_{\rm P}\in\Theta_{\rm P},
\qquad
\exists\,\theta^\star_{\rm O}\in\Theta_{\rm O},
\]

with both achieving perfect execution.

The training experiment now asks whether random initialization reaches either solution class.


## 6. Train exactly two models

There is no `run_experiment(base, modes=("outcome","process"))` here.

That function would train two copies of the **same base architecture**.

Instead we make two explicit calls:

\[
\boxed{
\text{PROCESS architecture}+\text{PROCESS supervision}
}
\]

and

\[
\boxed{
\text{OUTCOME architecture}+\text{OUTCOME supervision}.
}
\]

So exactly two optimization runs occur.

In [7]:

trained_process, process_history = train_one_model(
    process_random_base,
    "process",
    training_data["process"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="process_architecture",
    test_loss_data=test_loss_data["process"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

trained_outcome, outcome_history = train_one_model(
    outcome_random_base,
    "outcome",
    training_data["outcome"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="outcome_architecture",
    test_loss_data=test_loss_data["outcome"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

history = pd.concat(
    [process_history, outcome_history],
    ignore_index=True,
)

display(
    history.drop(columns=["circuit_matrix"], errors="ignore")
)

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.260, train=0.0%, train_loss=4.260]

process_architecture/process:   0%|          | 1/2000 [00:00<05:04,  6.56it/s, test=0.0%, test_loss=4.260, train=0.0%, train_loss=4.260]

process_architecture/process:   0%|          | 1/2000 [00:00<05:04,  6.56it/s, test=0.0%, test_loss=4.235, train=0.0%, train_loss=4.236]

process_architecture/process:   0%|          | 1/2000 [00:00<05:04,  6.56it/s, test=0.0%, test_loss=3.903, train=0.0%, train_loss=3.919]

process_architecture/process:   0%|          | 1/2000 [00:00<05:04,  6.56it/s, test=0.0%, test_loss=3.660, train=0.0%, train_loss=3.685]

process_architecture/process:   0%|          | 10/2000 [00:00<00:43, 46.16it/s, test=0.0%, test_loss=3.660, train=0.0%, train_loss=3.685]

process_architecture/process:   0%|          | 10/2000 [00:00<00:43, 46.16it/s, test=5.2%, test_loss=3.025, train=7.3%, train_loss=3.021]

process_architecture/process:   1%|          | 20/2000 [00:00<00:29, 66.23it/s, test=5.2%, test_loss=3.025, train=7.3%, train_loss=3.021]

process_architecture/process:   1%|          | 20/2000 [00:00<00:29, 66.23it/s, test=6.4%, test_loss=2.804, train=5.0%, train_loss=2.810]

process_architecture/process:   1%|▏         | 29/2000 [00:00<00:26, 74.53it/s, test=6.4%, test_loss=2.804, train=5.0%, train_loss=2.810]

process_architecture/process:   2%|▏         | 48/2000 [00:00<00:17, 112.51it/s, test=6.4%, test_loss=2.804, train=5.0%, train_loss=2.810]

process_architecture/process:   2%|▏         | 48/2000 [00:00<00:17, 112.51it/s, test=6.3%, test_loss=2.603, train=5.0%, train_loss=2.648]

process_architecture/process:   3%|▎         | 60/2000 [00:00<00:17, 108.34it/s, test=6.3%, test_loss=2.603, train=5.0%, train_loss=2.648]

process_architecture/process:   3%|▎         | 60/2000 [00:00<00:17, 108.34it/s, test=9.8%, test_loss=2.376, train=7.0%, train_loss=2.413]

process_architecture/process:   4%|▍         | 75/2000 [00:00<00:17, 109.48it/s, test=9.8%, test_loss=2.376, train=7.0%, train_loss=2.413]

process_architecture/process:   5%|▍         | 95/2000 [00:00<00:14, 133.30it/s, test=9.8%, test_loss=2.376, train=7.0%, train_loss=2.413]

process_architecture/process:   5%|▍         | 95/2000 [00:01<00:14, 133.30it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   5%|▌         | 109/2000 [00:01<00:15, 125.06it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   6%|▋         | 128/2000 [00:01<00:13, 142.45it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   7%|▋         | 147/2000 [00:01<00:11, 155.19it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   7%|▋         | 147/2000 [00:01<00:11, 155.19it/s, test=13.3%, test_loss=1.988, train=10.7%, train_loss=2.019]

process_architecture/process:   8%|▊         | 163/2000 [00:01<00:13, 140.32it/s, test=13.3%, test_loss=1.988, train=10.7%, train_loss=2.019]

process_architecture/process:   9%|▉         | 182/2000 [00:01<00:11, 153.54it/s, test=13.3%, test_loss=1.988, train=10.7%, train_loss=2.019]

process_architecture/process:   9%|▉         | 182/2000 [00:01<00:11, 153.54it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  10%|█         | 200/2000 [00:01<00:12, 142.35it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  11%|█         | 219/2000 [00:01<00:11, 154.01it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  12%|█▏        | 239/2000 [00:01<00:10, 164.25it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  12%|█▏        | 239/2000 [00:01<00:10, 164.25it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  13%|█▎        | 256/2000 [00:01<00:11, 148.22it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  14%|█▍        | 276/2000 [00:02<00:10, 159.80it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  15%|█▍        | 295/2000 [00:02<00:10, 167.21it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  15%|█▍        | 295/2000 [00:02<00:10, 167.21it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  16%|█▌        | 313/2000 [00:02<00:11, 150.16it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  17%|█▋        | 333/2000 [00:02<00:10, 161.00it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  17%|█▋        | 333/2000 [00:02<00:10, 161.00it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  18%|█▊        | 350/2000 [00:02<00:11, 147.05it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  18%|█▊        | 369/2000 [00:02<00:10, 158.01it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  19%|█▉        | 388/2000 [00:02<00:09, 166.11it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  19%|█▉        | 388/2000 [00:02<00:09, 166.11it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  20%|██        | 406/2000 [00:02<00:10, 150.08it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  21%|██▏       | 425/2000 [00:03<00:09, 160.04it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  22%|██▏       | 444/2000 [00:03<00:09, 167.91it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  22%|██▏       | 444/2000 [00:03<00:09, 167.91it/s, test=99.8%, test_loss=0.005, train=100.0%, train_loss=0.005]

process_architecture/process:  23%|██▎       | 462/2000 [00:03<00:10, 151.03it/s, test=99.8%, test_loss=0.005, train=100.0%, train_loss=0.005]

process_architecture/process:  24%|██▍       | 481/2000 [00:03<00:09, 160.03it/s, test=99.8%, test_loss=0.005, train=100.0%, train_loss=0.005]

process_architecture/process:  24%|██▍       | 481/2000 [00:03<00:09, 160.03it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  25%|██▌       | 500/2000 [00:03<00:10, 146.96it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  26%|██▌       | 519/2000 [00:03<00:09, 157.63it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 538/2000 [00:03<00:08, 166.09it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 538/2000 [00:03<00:08, 166.09it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  28%|██▊       | 556/2000 [00:03<00:09, 150.13it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 576/2000 [00:04<00:08, 160.86it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|██▉       | 596/2000 [00:04<00:08, 169.27it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|██▉       | 596/2000 [00:04<00:08, 169.27it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  31%|███       | 614/2000 [00:04<00:09, 151.83it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 634/2000 [00:04<00:08, 162.13it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 634/2000 [00:04<00:08, 162.13it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  33%|███▎      | 651/2000 [00:04<00:09, 148.14it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▎      | 670/2000 [00:04<00:08, 158.35it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 689/2000 [00:04<00:07, 166.68it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 689/2000 [00:04<00:07, 166.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▌      | 707/2000 [00:04<00:08, 149.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▋      | 726/2000 [00:04<00:07, 160.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 745/2000 [00:05<00:07, 168.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 745/2000 [00:05<00:07, 168.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 763/2000 [00:05<00:08, 150.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 782/2000 [00:05<00:07, 159.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 782/2000 [00:05<00:07, 159.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|████      | 800/2000 [00:05<00:08, 146.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 819/2000 [00:05<00:07, 156.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 839/2000 [00:05<00:06, 166.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 839/2000 [00:05<00:06, 166.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  43%|████▎     | 857/2000 [00:05<00:07, 150.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 877/2000 [00:05<00:06, 161.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 897/2000 [00:06<00:06, 169.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 897/2000 [00:06<00:06, 169.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 915/2000 [00:06<00:07, 152.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 935/2000 [00:06<00:06, 163.02it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 935/2000 [00:06<00:06, 163.02it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 952/2000 [00:06<00:07, 148.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▊     | 972/2000 [00:06<00:06, 159.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|████▉     | 992/2000 [00:06<00:05, 168.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|████▉     | 992/2000 [00:06<00:05, 168.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1010/2000 [00:06<00:06, 150.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1030/2000 [00:06<00:06, 161.02it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1049/2000 [00:06<00:05, 167.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1049/2000 [00:07<00:05, 167.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1067/2000 [00:07<00:06, 151.19it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1087/2000 [00:07<00:05, 162.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1087/2000 [00:07<00:05, 162.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1104/2000 [00:07<00:06, 147.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1124/2000 [00:07<00:05, 159.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1143/2000 [00:07<00:05, 167.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1143/2000 [00:07<00:05, 167.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1161/2000 [00:07<00:05, 151.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1180/2000 [00:07<00:05, 160.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1180/2000 [00:07<00:05, 160.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1200/2000 [00:07<00:05, 148.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1219/2000 [00:08<00:04, 158.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1239/2000 [00:08<00:04, 167.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1239/2000 [00:08<00:04, 167.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1257/2000 [00:08<00:04, 150.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1276/2000 [00:08<00:04, 160.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1295/2000 [00:08<00:04, 167.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1295/2000 [00:08<00:04, 167.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1313/2000 [00:08<00:04, 150.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1331/2000 [00:08<00:04, 156.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1331/2000 [00:08<00:04, 156.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1350/2000 [00:08<00:04, 140.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1367/2000 [00:09<00:04, 145.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1386/2000 [00:09<00:03, 156.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1386/2000 [00:09<00:03, 156.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1403/2000 [00:09<00:04, 141.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████   | 1423/2000 [00:09<00:03, 154.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1443/2000 [00:09<00:03, 164.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1443/2000 [00:09<00:03, 164.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1461/2000 [00:09<00:03, 146.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1481/2000 [00:09<00:03, 158.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1481/2000 [00:09<00:03, 158.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1500/2000 [00:09<00:03, 146.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1518/2000 [00:10<00:03, 154.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1537/2000 [00:10<00:02, 163.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1537/2000 [00:10<00:02, 163.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1554/2000 [00:10<00:03, 146.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▊  | 1572/2000 [00:10<00:02, 155.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1592/2000 [00:10<00:02, 165.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1592/2000 [00:10<00:02, 165.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1610/2000 [00:10<00:02, 147.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1630/2000 [00:10<00:02, 159.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1630/2000 [00:10<00:02, 159.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▎ | 1650/2000 [00:10<00:02, 147.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1668/2000 [00:11<00:02, 154.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1687/2000 [00:11<00:01, 163.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1687/2000 [00:11<00:01, 163.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▌ | 1704/2000 [00:11<00:02, 146.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1724/2000 [00:11<00:01, 159.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1744/2000 [00:11<00:01, 168.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1744/2000 [00:11<00:01, 168.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1762/2000 [00:11<00:01, 151.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1782/2000 [00:11<00:01, 162.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1782/2000 [00:11<00:01, 162.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|█████████ | 1800/2000 [00:11<00:01, 148.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1819/2000 [00:11<00:01, 156.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1839/2000 [00:12<00:00, 166.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1839/2000 [00:12<00:00, 166.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1857/2000 [00:12<00:00, 150.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1877/2000 [00:12<00:00, 160.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1897/2000 [00:12<00:00, 169.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1897/2000 [00:12<00:00, 169.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1915/2000 [00:12<00:00, 151.81it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1934/2000 [00:12<00:00, 159.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1934/2000 [00:12<00:00, 159.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1951/2000 [00:12<00:00, 143.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1970/2000 [00:12<00:00, 154.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1989/2000 [00:13<00:00, 163.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1989/2000 [00:13<00:00, 163.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:13<00:00, 152.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.500, train=0.0%, train_loss=3.503]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=13.882, train=0.0%, train_loss=13.722]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.612, train=0.0%, train_loss=3.615]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:54, 36.58it/s, test=0.0%, test_loss=3.612, train=0.0%, train_loss=3.615]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:54, 36.58it/s, test=0.0%, test_loss=1.082, train=0.0%, train_loss=1.081]

outcome_architecture/outcome:   1%|          | 12/2000 [00:00<00:38, 51.31it/s, test=0.0%, test_loss=1.082, train=0.0%, train_loss=1.081]

outcome_architecture/outcome:   1%|          | 12/2000 [00:00<00:38, 51.31it/s, test=0.0%, test_loss=8.616, train=0.0%, train_loss=8.464]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 60.51it/s, test=0.0%, test_loss=8.616, train=0.0%, train_loss=8.464]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 60.51it/s, test=6.1%, test_loss=1.565, train=7.0%, train_loss=1.557]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:31, 62.31it/s, test=6.1%, test_loss=1.565, train=7.0%, train_loss=1.557]

outcome_architecture/outcome:   2%|▏         | 37/2000 [00:00<00:26, 74.44it/s, test=6.1%, test_loss=1.565, train=7.0%, train_loss=1.557]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:23, 82.28it/s, test=6.1%, test_loss=1.565, train=7.0%, train_loss=1.557]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:23, 82.28it/s, test=6.6%, test_loss=0.940, train=4.0%, train_loss=0.973]

outcome_architecture/outcome:   3%|▎         | 56/2000 [00:00<00:24, 78.22it/s, test=6.6%, test_loss=0.940, train=4.0%, train_loss=0.973]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:00<00:22, 84.44it/s, test=6.6%, test_loss=0.940, train=4.0%, train_loss=0.973]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:01<00:22, 84.44it/s, test=6.5%, test_loss=0.943, train=6.7%, train_loss=0.956]

outcome_architecture/outcome:   4%|▍         | 75/2000 [00:01<00:24, 79.87it/s, test=6.5%, test_loss=0.943, train=6.7%, train_loss=0.956]

outcome_architecture/outcome:   4%|▍         | 85/2000 [00:01<00:22, 85.36it/s, test=6.5%, test_loss=0.943, train=6.7%, train_loss=0.956]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 89.13it/s, test=6.5%, test_loss=0.943, train=6.7%, train_loss=0.956]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 89.13it/s, test=10.0%, test_loss=0.931, train=10.0%, train_loss=0.944]

outcome_architecture/outcome:   5%|▌         | 105/2000 [00:01<00:22, 83.33it/s, test=10.0%, test_loss=0.931, train=10.0%, train_loss=0.944]

outcome_architecture/outcome:   6%|▌         | 115/2000 [00:01<00:21, 87.40it/s, test=10.0%, test_loss=0.931, train=10.0%, train_loss=0.944]

outcome_architecture/outcome:   6%|▋         | 125/2000 [00:01<00:20, 90.62it/s, test=10.0%, test_loss=0.931, train=10.0%, train_loss=0.944]

outcome_architecture/outcome:   7%|▋         | 135/2000 [00:01<00:20, 93.00it/s, test=10.0%, test_loss=0.931, train=10.0%, train_loss=0.944]

outcome_architecture/outcome:   7%|▋         | 145/2000 [00:01<00:19, 94.87it/s, test=10.0%, test_loss=0.931, train=10.0%, train_loss=0.944]

outcome_architecture/outcome:   7%|▋         | 145/2000 [00:01<00:19, 94.87it/s, test=13.0%, test_loss=0.915, train=9.7%, train_loss=0.914]

outcome_architecture/outcome:   8%|▊         | 155/2000 [00:01<00:21, 86.69it/s, test=13.0%, test_loss=0.915, train=9.7%, train_loss=0.914]

outcome_architecture/outcome:   8%|▊         | 165/2000 [00:02<00:20, 89.70it/s, test=13.0%, test_loss=0.915, train=9.7%, train_loss=0.914]

outcome_architecture/outcome:   9%|▉         | 175/2000 [00:02<00:20, 90.98it/s, test=13.0%, test_loss=0.915, train=9.7%, train_loss=0.914]

outcome_architecture/outcome:   9%|▉         | 185/2000 [00:02<00:20, 90.68it/s, test=13.0%, test_loss=0.915, train=9.7%, train_loss=0.914]

outcome_architecture/outcome:  10%|▉         | 195/2000 [00:02<00:19, 92.80it/s, test=13.0%, test_loss=0.915, train=9.7%, train_loss=0.914]

outcome_architecture/outcome:  10%|▉         | 195/2000 [00:02<00:19, 92.80it/s, test=11.3%, test_loss=0.897, train=10.0%, train_loss=0.898]

outcome_architecture/outcome:  10%|█         | 205/2000 [00:02<00:20, 86.01it/s, test=11.3%, test_loss=0.897, train=10.0%, train_loss=0.898]

outcome_architecture/outcome:  11%|█         | 215/2000 [00:02<00:20, 87.69it/s, test=11.3%, test_loss=0.897, train=10.0%, train_loss=0.898]

outcome_architecture/outcome:  11%|█▏        | 225/2000 [00:02<00:19, 90.59it/s, test=11.3%, test_loss=0.897, train=10.0%, train_loss=0.898]

outcome_architecture/outcome:  12%|█▏        | 236/2000 [00:02<00:18, 93.42it/s, test=11.3%, test_loss=0.897, train=10.0%, train_loss=0.898]

outcome_architecture/outcome:  12%|█▏        | 246/2000 [00:02<00:18, 92.41it/s, test=11.3%, test_loss=0.897, train=10.0%, train_loss=0.898]

outcome_architecture/outcome:  12%|█▏        | 246/2000 [00:02<00:18, 92.41it/s, test=11.7%, test_loss=0.911, train=9.0%, train_loss=0.921]

outcome_architecture/outcome:  13%|█▎        | 256/2000 [00:03<00:20, 85.57it/s, test=11.7%, test_loss=0.911, train=9.0%, train_loss=0.921]

outcome_architecture/outcome:  13%|█▎        | 266/2000 [00:03<00:19, 88.99it/s, test=11.7%, test_loss=0.911, train=9.0%, train_loss=0.921]

outcome_architecture/outcome:  14%|█▍        | 276/2000 [00:03<00:18, 91.42it/s, test=11.7%, test_loss=0.911, train=9.0%, train_loss=0.921]

outcome_architecture/outcome:  14%|█▍        | 287/2000 [00:03<00:18, 94.03it/s, test=11.7%, test_loss=0.911, train=9.0%, train_loss=0.921]

outcome_architecture/outcome:  15%|█▍        | 297/2000 [00:03<00:17, 95.48it/s, test=11.7%, test_loss=0.911, train=9.0%, train_loss=0.921]

outcome_architecture/outcome:  15%|█▍        | 297/2000 [00:03<00:17, 95.48it/s, test=13.3%, test_loss=0.905, train=9.0%, train_loss=0.909]

outcome_architecture/outcome:  15%|█▌        | 307/2000 [00:03<00:19, 87.82it/s, test=13.3%, test_loss=0.905, train=9.0%, train_loss=0.909]

outcome_architecture/outcome:  16%|█▌        | 317/2000 [00:03<00:18, 91.10it/s, test=13.3%, test_loss=0.905, train=9.0%, train_loss=0.909]

outcome_architecture/outcome:  16%|█▋        | 327/2000 [00:03<00:17, 93.17it/s, test=13.3%, test_loss=0.905, train=9.0%, train_loss=0.909]

outcome_architecture/outcome:  17%|█▋        | 337/2000 [00:03<00:17, 94.74it/s, test=13.3%, test_loss=0.905, train=9.0%, train_loss=0.909]

outcome_architecture/outcome:  17%|█▋        | 347/2000 [00:03<00:17, 95.88it/s, test=13.3%, test_loss=0.905, train=9.0%, train_loss=0.909]

outcome_architecture/outcome:  17%|█▋        | 347/2000 [00:04<00:17, 95.88it/s, test=12.3%, test_loss=0.900, train=10.3%, train_loss=0.917]

outcome_architecture/outcome:  18%|█▊        | 357/2000 [00:04<00:18, 87.42it/s, test=12.3%, test_loss=0.900, train=10.3%, train_loss=0.917]

outcome_architecture/outcome:  18%|█▊        | 367/2000 [00:04<00:17, 90.83it/s, test=12.3%, test_loss=0.900, train=10.3%, train_loss=0.917]

outcome_architecture/outcome:  19%|█▉        | 377/2000 [00:04<00:17, 93.34it/s, test=12.3%, test_loss=0.900, train=10.3%, train_loss=0.917]

outcome_architecture/outcome:  19%|█▉        | 387/2000 [00:04<00:16, 95.04it/s, test=12.3%, test_loss=0.900, train=10.3%, train_loss=0.917]

outcome_architecture/outcome:  20%|█▉        | 398/2000 [00:04<00:16, 96.73it/s, test=12.3%, test_loss=0.900, train=10.3%, train_loss=0.917]

outcome_architecture/outcome:  20%|█▉        | 398/2000 [00:04<00:16, 96.73it/s, test=10.8%, test_loss=0.895, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  20%|██        | 408/2000 [00:04<00:18, 87.98it/s, test=10.8%, test_loss=0.895, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  21%|██        | 418/2000 [00:04<00:17, 90.90it/s, test=10.8%, test_loss=0.895, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  21%|██▏       | 428/2000 [00:04<00:16, 92.99it/s, test=10.8%, test_loss=0.895, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  22%|██▏       | 438/2000 [00:04<00:16, 94.79it/s, test=10.8%, test_loss=0.895, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  22%|██▏       | 448/2000 [00:05<00:16, 96.25it/s, test=10.8%, test_loss=0.895, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  22%|██▏       | 448/2000 [00:05<00:16, 96.25it/s, test=12.0%, test_loss=0.901, train=13.7%, train_loss=0.886]

outcome_architecture/outcome:  23%|██▎       | 458/2000 [00:05<00:17, 88.17it/s, test=12.0%, test_loss=0.901, train=13.7%, train_loss=0.886]

outcome_architecture/outcome:  23%|██▎       | 468/2000 [00:05<00:16, 91.23it/s, test=12.0%, test_loss=0.901, train=13.7%, train_loss=0.886]

outcome_architecture/outcome:  24%|██▍       | 478/2000 [00:05<00:16, 92.99it/s, test=12.0%, test_loss=0.901, train=13.7%, train_loss=0.886]

outcome_architecture/outcome:  24%|██▍       | 488/2000 [00:05<00:15, 94.98it/s, test=12.0%, test_loss=0.901, train=13.7%, train_loss=0.886]

outcome_architecture/outcome:  25%|██▍       | 499/2000 [00:05<00:15, 96.73it/s, test=12.0%, test_loss=0.901, train=13.7%, train_loss=0.886]

outcome_architecture/outcome:  25%|██▍       | 499/2000 [00:05<00:15, 96.73it/s, test=11.7%, test_loss=0.901, train=11.7%, train_loss=0.903]

outcome_architecture/outcome:  25%|██▌       | 509/2000 [00:05<00:16, 88.33it/s, test=11.7%, test_loss=0.901, train=11.7%, train_loss=0.903]

outcome_architecture/outcome:  26%|██▌       | 519/2000 [00:05<00:16, 91.47it/s, test=11.7%, test_loss=0.901, train=11.7%, train_loss=0.903]

outcome_architecture/outcome:  26%|██▋       | 529/2000 [00:05<00:15, 92.46it/s, test=11.7%, test_loss=0.901, train=11.7%, train_loss=0.903]

outcome_architecture/outcome:  27%|██▋       | 539/2000 [00:06<00:15, 93.46it/s, test=11.7%, test_loss=0.901, train=11.7%, train_loss=0.903]

outcome_architecture/outcome:  27%|██▋       | 549/2000 [00:06<00:15, 93.57it/s, test=11.7%, test_loss=0.901, train=11.7%, train_loss=0.903]

outcome_architecture/outcome:  27%|██▋       | 549/2000 [00:06<00:15, 93.57it/s, test=14.7%, test_loss=0.890, train=14.7%, train_loss=0.864]

outcome_architecture/outcome:  28%|██▊       | 559/2000 [00:06<00:16, 86.52it/s, test=14.7%, test_loss=0.890, train=14.7%, train_loss=0.864]

outcome_architecture/outcome:  28%|██▊       | 569/2000 [00:06<00:15, 89.82it/s, test=14.7%, test_loss=0.890, train=14.7%, train_loss=0.864]

outcome_architecture/outcome:  29%|██▉       | 580/2000 [00:06<00:15, 92.97it/s, test=14.7%, test_loss=0.890, train=14.7%, train_loss=0.864]

outcome_architecture/outcome:  30%|██▉       | 590/2000 [00:06<00:14, 94.49it/s, test=14.7%, test_loss=0.890, train=14.7%, train_loss=0.864]

outcome_architecture/outcome:  30%|██▉       | 590/2000 [00:06<00:14, 94.49it/s, test=13.5%, test_loss=0.888, train=13.0%, train_loss=0.897]

outcome_architecture/outcome:  30%|███       | 600/2000 [00:06<00:16, 84.87it/s, test=13.5%, test_loss=0.888, train=13.0%, train_loss=0.897]

outcome_architecture/outcome:  30%|███       | 610/2000 [00:06<00:15, 88.60it/s, test=13.5%, test_loss=0.888, train=13.0%, train_loss=0.897]

outcome_architecture/outcome:  31%|███       | 620/2000 [00:06<00:15, 91.51it/s, test=13.5%, test_loss=0.888, train=13.0%, train_loss=0.897]

outcome_architecture/outcome:  32%|███▏      | 631/2000 [00:07<00:14, 94.08it/s, test=13.5%, test_loss=0.888, train=13.0%, train_loss=0.897]

outcome_architecture/outcome:  32%|███▏      | 642/2000 [00:07<00:14, 96.00it/s, test=13.5%, test_loss=0.888, train=13.0%, train_loss=0.897]

outcome_architecture/outcome:  32%|███▏      | 642/2000 [00:07<00:14, 96.00it/s, test=15.8%, test_loss=0.875, train=16.3%, train_loss=0.853]

outcome_architecture/outcome:  33%|███▎      | 652/2000 [00:07<00:15, 87.86it/s, test=15.8%, test_loss=0.875, train=16.3%, train_loss=0.853]

outcome_architecture/outcome:  33%|███▎      | 661/2000 [00:07<00:15, 88.20it/s, test=15.8%, test_loss=0.875, train=16.3%, train_loss=0.853]

outcome_architecture/outcome:  34%|███▎      | 671/2000 [00:07<00:14, 91.20it/s, test=15.8%, test_loss=0.875, train=16.3%, train_loss=0.853]

outcome_architecture/outcome:  34%|███▍      | 681/2000 [00:07<00:14, 93.25it/s, test=15.8%, test_loss=0.875, train=16.3%, train_loss=0.853]

outcome_architecture/outcome:  35%|███▍      | 691/2000 [00:07<00:13, 94.85it/s, test=15.8%, test_loss=0.875, train=16.3%, train_loss=0.853]

outcome_architecture/outcome:  35%|███▍      | 691/2000 [00:07<00:13, 94.85it/s, test=12.1%, test_loss=0.919, train=10.7%, train_loss=0.939]

outcome_architecture/outcome:  35%|███▌      | 701/2000 [00:07<00:14, 87.13it/s, test=12.1%, test_loss=0.919, train=10.7%, train_loss=0.939]

outcome_architecture/outcome:  36%|███▌      | 711/2000 [00:07<00:14, 90.29it/s, test=12.1%, test_loss=0.919, train=10.7%, train_loss=0.939]

outcome_architecture/outcome:  36%|███▌      | 721/2000 [00:08<00:14, 89.81it/s, test=12.1%, test_loss=0.919, train=10.7%, train_loss=0.939]

outcome_architecture/outcome:  37%|███▋      | 731/2000 [00:08<00:13, 92.64it/s, test=12.1%, test_loss=0.919, train=10.7%, train_loss=0.939]

outcome_architecture/outcome:  37%|███▋      | 741/2000 [00:08<00:13, 94.57it/s, test=12.1%, test_loss=0.919, train=10.7%, train_loss=0.939]

outcome_architecture/outcome:  37%|███▋      | 741/2000 [00:08<00:13, 94.57it/s, test=0.9%, test_loss=362996320.000, train=2.7%, train_loss=340160288.000]

outcome_architecture/outcome:  38%|███▊      | 751/2000 [00:08<00:14, 87.33it/s, test=0.9%, test_loss=362996320.000, train=2.7%, train_loss=340160288.000]

outcome_architecture/outcome:  38%|███▊      | 762/2000 [00:08<00:13, 91.07it/s, test=0.9%, test_loss=362996320.000, train=2.7%, train_loss=340160288.000]

outcome_architecture/outcome:  39%|███▊      | 772/2000 [00:08<00:13, 90.90it/s, test=0.9%, test_loss=362996320.000, train=2.7%, train_loss=340160288.000]

outcome_architecture/outcome:  39%|███▉      | 782/2000 [00:08<00:13, 91.88it/s, test=0.9%, test_loss=362996320.000, train=2.7%, train_loss=340160288.000]

outcome_architecture/outcome:  40%|███▉      | 792/2000 [00:08<00:12, 93.57it/s, test=0.9%, test_loss=362996320.000, train=2.7%, train_loss=340160288.000]

outcome_architecture/outcome:  40%|███▉      | 792/2000 [00:08<00:12, 93.57it/s, test=0.0%, test_loss=13615973.000, train=0.0%, train_loss=21358598.000]

outcome_architecture/outcome:  40%|████      | 802/2000 [00:08<00:13, 86.58it/s, test=0.0%, test_loss=13615973.000, train=0.0%, train_loss=21358598.000]

outcome_architecture/outcome:  41%|████      | 812/2000 [00:09<00:13, 90.19it/s, test=0.0%, test_loss=13615973.000, train=0.0%, train_loss=21358598.000]

outcome_architecture/outcome:  41%|████      | 822/2000 [00:09<00:12, 92.61it/s, test=0.0%, test_loss=13615973.000, train=0.0%, train_loss=21358598.000]

outcome_architecture/outcome:  42%|████▏     | 832/2000 [00:09<00:12, 91.66it/s, test=0.0%, test_loss=13615973.000, train=0.0%, train_loss=21358598.000]

outcome_architecture/outcome:  42%|████▏     | 842/2000 [00:09<00:12, 93.88it/s, test=0.0%, test_loss=13615973.000, train=0.0%, train_loss=21358598.000]

outcome_architecture/outcome:  42%|████▏     | 842/2000 [00:09<00:12, 93.88it/s, test=0.2%, test_loss=1847190.125, train=0.0%, train_loss=1729876.625]

outcome_architecture/outcome:  43%|████▎     | 852/2000 [00:09<00:13, 85.34it/s, test=0.2%, test_loss=1847190.125, train=0.0%, train_loss=1729876.625]

outcome_architecture/outcome:  43%|████▎     | 862/2000 [00:09<00:12, 88.60it/s, test=0.2%, test_loss=1847190.125, train=0.0%, train_loss=1729876.625]

outcome_architecture/outcome:  44%|████▎     | 872/2000 [00:09<00:12, 91.36it/s, test=0.2%, test_loss=1847190.125, train=0.0%, train_loss=1729876.625]

outcome_architecture/outcome:  44%|████▍     | 882/2000 [00:09<00:11, 93.76it/s, test=0.2%, test_loss=1847190.125, train=0.0%, train_loss=1729876.625]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:12, 92.23it/s, test=0.2%, test_loss=1847190.125, train=0.0%, train_loss=1729876.625]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:10<00:12, 92.23it/s, test=0.2%, test_loss=577274.312, train=0.0%, train_loss=513677.969]

outcome_architecture/outcome:  45%|████▌     | 902/2000 [00:10<00:12, 85.11it/s, test=0.2%, test_loss=577274.312, train=0.0%, train_loss=513677.969]

outcome_architecture/outcome:  46%|████▌     | 912/2000 [00:10<00:12, 85.46it/s, test=0.2%, test_loss=577274.312, train=0.0%, train_loss=513677.969]

outcome_architecture/outcome:  46%|████▌     | 922/2000 [00:10<00:12, 87.14it/s, test=0.2%, test_loss=577274.312, train=0.0%, train_loss=513677.969]

outcome_architecture/outcome:  47%|████▋     | 932/2000 [00:10<00:11, 90.29it/s, test=0.2%, test_loss=577274.312, train=0.0%, train_loss=513677.969]

outcome_architecture/outcome:  47%|████▋     | 942/2000 [00:10<00:11, 92.99it/s, test=0.2%, test_loss=577274.312, train=0.0%, train_loss=513677.969]

outcome_architecture/outcome:  47%|████▋     | 942/2000 [00:10<00:11, 92.99it/s, test=0.7%, test_loss=237753.203, train=1.0%, train_loss=248968.953]

outcome_architecture/outcome:  48%|████▊     | 952/2000 [00:10<00:12, 85.44it/s, test=0.7%, test_loss=237753.203, train=1.0%, train_loss=248968.953]

outcome_architecture/outcome:  48%|████▊     | 962/2000 [00:10<00:11, 89.23it/s, test=0.7%, test_loss=237753.203, train=1.0%, train_loss=248968.953]

outcome_architecture/outcome:  49%|████▊     | 972/2000 [00:10<00:11, 92.19it/s, test=0.7%, test_loss=237753.203, train=1.0%, train_loss=248968.953]

outcome_architecture/outcome:  49%|████▉     | 982/2000 [00:10<00:10, 94.27it/s, test=0.7%, test_loss=237753.203, train=1.0%, train_loss=248968.953]

outcome_architecture/outcome:  50%|████▉     | 992/2000 [00:11<00:10, 95.88it/s, test=0.7%, test_loss=237753.203, train=1.0%, train_loss=248968.953]

outcome_architecture/outcome:  50%|████▉     | 992/2000 [00:11<00:10, 95.88it/s, test=0.5%, test_loss=176891.641, train=1.0%, train_loss=177213.516]

outcome_architecture/outcome:  50%|█████     | 1002/2000 [00:11<00:11, 87.78it/s, test=0.5%, test_loss=176891.641, train=1.0%, train_loss=177213.516]

outcome_architecture/outcome:  51%|█████     | 1012/2000 [00:11<00:10, 90.25it/s, test=0.5%, test_loss=176891.641, train=1.0%, train_loss=177213.516]

outcome_architecture/outcome:  51%|█████     | 1022/2000 [00:11<00:10, 91.88it/s, test=0.5%, test_loss=176891.641, train=1.0%, train_loss=177213.516]

outcome_architecture/outcome:  52%|█████▏    | 1032/2000 [00:11<00:10, 93.79it/s, test=0.5%, test_loss=176891.641, train=1.0%, train_loss=177213.516]

outcome_architecture/outcome:  52%|█████▏    | 1042/2000 [00:11<00:10, 95.10it/s, test=0.5%, test_loss=176891.641, train=1.0%, train_loss=177213.516]

outcome_architecture/outcome:  52%|█████▏    | 1042/2000 [00:11<00:10, 95.10it/s, test=0.1%, test_loss=216108.547, train=0.0%, train_loss=188559.750]

outcome_architecture/outcome:  53%|█████▎    | 1052/2000 [00:11<00:10, 87.22it/s, test=0.1%, test_loss=216108.547, train=0.0%, train_loss=188559.750]

outcome_architecture/outcome:  53%|█████▎    | 1062/2000 [00:11<00:10, 90.00it/s, test=0.1%, test_loss=216108.547, train=0.0%, train_loss=188559.750]

outcome_architecture/outcome:  54%|█████▎    | 1072/2000 [00:11<00:10, 92.20it/s, test=0.1%, test_loss=216108.547, train=0.0%, train_loss=188559.750]

outcome_architecture/outcome:  54%|█████▍    | 1082/2000 [00:12<00:09, 94.37it/s, test=0.1%, test_loss=216108.547, train=0.0%, train_loss=188559.750]

outcome_architecture/outcome:  55%|█████▍    | 1092/2000 [00:12<00:09, 95.88it/s, test=0.1%, test_loss=216108.547, train=0.0%, train_loss=188559.750]

outcome_architecture/outcome:  55%|█████▍    | 1092/2000 [00:12<00:09, 95.88it/s, test=0.4%, test_loss=138107.562, train=0.7%, train_loss=140850.297]

outcome_architecture/outcome:  55%|█████▌    | 1102/2000 [00:12<00:10, 87.70it/s, test=0.4%, test_loss=138107.562, train=0.7%, train_loss=140850.297]

outcome_architecture/outcome:  56%|█████▌    | 1112/2000 [00:12<00:09, 90.66it/s, test=0.4%, test_loss=138107.562, train=0.7%, train_loss=140850.297]

outcome_architecture/outcome:  56%|█████▌    | 1123/2000 [00:12<00:09, 93.52it/s, test=0.4%, test_loss=138107.562, train=0.7%, train_loss=140850.297]

outcome_architecture/outcome:  57%|█████▋    | 1133/2000 [00:12<00:09, 94.86it/s, test=0.4%, test_loss=138107.562, train=0.7%, train_loss=140850.297]

outcome_architecture/outcome:  57%|█████▋    | 1143/2000 [00:12<00:08, 95.66it/s, test=0.4%, test_loss=138107.562, train=0.7%, train_loss=140850.297]

outcome_architecture/outcome:  57%|█████▋    | 1143/2000 [00:12<00:08, 95.66it/s, test=0.3%, test_loss=59840.824, train=0.3%, train_loss=72224.789]

outcome_architecture/outcome:  58%|█████▊    | 1153/2000 [00:12<00:09, 88.04it/s, test=0.3%, test_loss=59840.824, train=0.3%, train_loss=72224.789]

outcome_architecture/outcome:  58%|█████▊    | 1163/2000 [00:12<00:09, 90.83it/s, test=0.3%, test_loss=59840.824, train=0.3%, train_loss=72224.789]

outcome_architecture/outcome:  59%|█████▊    | 1173/2000 [00:13<00:08, 92.87it/s, test=0.3%, test_loss=59840.824, train=0.3%, train_loss=72224.789]

outcome_architecture/outcome:  59%|█████▉    | 1183/2000 [00:13<00:08, 94.23it/s, test=0.3%, test_loss=59840.824, train=0.3%, train_loss=72224.789]

outcome_architecture/outcome:  60%|█████▉    | 1193/2000 [00:13<00:08, 95.57it/s, test=0.3%, test_loss=59840.824, train=0.3%, train_loss=72224.789]

outcome_architecture/outcome:  60%|█████▉    | 1193/2000 [00:13<00:08, 95.57it/s, test=0.2%, test_loss=60314.355, train=0.3%, train_loss=67535.633]

outcome_architecture/outcome:  60%|██████    | 1203/2000 [00:13<00:09, 87.93it/s, test=0.2%, test_loss=60314.355, train=0.3%, train_loss=67535.633]

outcome_architecture/outcome:  61%|██████    | 1213/2000 [00:13<00:08, 91.17it/s, test=0.2%, test_loss=60314.355, train=0.3%, train_loss=67535.633]

outcome_architecture/outcome:  61%|██████    | 1223/2000 [00:13<00:08, 92.94it/s, test=0.2%, test_loss=60314.355, train=0.3%, train_loss=67535.633]

outcome_architecture/outcome:  62%|██████▏   | 1233/2000 [00:13<00:08, 94.14it/s, test=0.2%, test_loss=60314.355, train=0.3%, train_loss=67535.633]

outcome_architecture/outcome:  62%|██████▏   | 1243/2000 [00:13<00:07, 95.05it/s, test=0.2%, test_loss=60314.355, train=0.3%, train_loss=67535.633]

outcome_architecture/outcome:  62%|██████▏   | 1243/2000 [00:13<00:07, 95.05it/s, test=0.0%, test_loss=73839.969, train=0.0%, train_loss=80822.227]

outcome_architecture/outcome:  63%|██████▎   | 1253/2000 [00:13<00:08, 87.31it/s, test=0.0%, test_loss=73839.969, train=0.0%, train_loss=80822.227]

outcome_architecture/outcome:  63%|██████▎   | 1263/2000 [00:14<00:08, 90.38it/s, test=0.0%, test_loss=73839.969, train=0.0%, train_loss=80822.227]

outcome_architecture/outcome:  64%|██████▎   | 1273/2000 [00:14<00:07, 92.49it/s, test=0.0%, test_loss=73839.969, train=0.0%, train_loss=80822.227]

outcome_architecture/outcome:  64%|██████▍   | 1283/2000 [00:14<00:07, 94.13it/s, test=0.0%, test_loss=73839.969, train=0.0%, train_loss=80822.227]

outcome_architecture/outcome:  65%|██████▍   | 1293/2000 [00:14<00:07, 95.04it/s, test=0.0%, test_loss=73839.969, train=0.0%, train_loss=80822.227]

outcome_architecture/outcome:  65%|██████▍   | 1293/2000 [00:14<00:07, 95.04it/s, test=0.1%, test_loss=59293.051, train=0.3%, train_loss=60352.855]

outcome_architecture/outcome:  65%|██████▌   | 1303/2000 [00:14<00:07, 87.26it/s, test=0.1%, test_loss=59293.051, train=0.3%, train_loss=60352.855]

outcome_architecture/outcome:  66%|██████▌   | 1313/2000 [00:14<00:07, 90.14it/s, test=0.1%, test_loss=59293.051, train=0.3%, train_loss=60352.855]

outcome_architecture/outcome:  66%|██████▌   | 1323/2000 [00:14<00:07, 92.78it/s, test=0.1%, test_loss=59293.051, train=0.3%, train_loss=60352.855]

outcome_architecture/outcome:  67%|██████▋   | 1333/2000 [00:14<00:07, 94.48it/s, test=0.1%, test_loss=59293.051, train=0.3%, train_loss=60352.855]

outcome_architecture/outcome:  67%|██████▋   | 1343/2000 [00:14<00:06, 95.43it/s, test=0.1%, test_loss=59293.051, train=0.3%, train_loss=60352.855]

outcome_architecture/outcome:  67%|██████▋   | 1343/2000 [00:14<00:06, 95.43it/s, test=0.0%, test_loss=129865992.000, train=0.0%, train_loss=148836416.000]

outcome_architecture/outcome:  68%|██████▊   | 1353/2000 [00:15<00:07, 87.35it/s, test=0.0%, test_loss=129865992.000, train=0.0%, train_loss=148836416.000]

outcome_architecture/outcome:  68%|██████▊   | 1363/2000 [00:15<00:07, 90.17it/s, test=0.0%, test_loss=129865992.000, train=0.0%, train_loss=148836416.000]

outcome_architecture/outcome:  69%|██████▊   | 1373/2000 [00:15<00:06, 92.23it/s, test=0.0%, test_loss=129865992.000, train=0.0%, train_loss=148836416.000]

outcome_architecture/outcome:  69%|██████▉   | 1383/2000 [00:15<00:06, 93.44it/s, test=0.0%, test_loss=129865992.000, train=0.0%, train_loss=148836416.000]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:15<00:06, 94.59it/s, test=0.0%, test_loss=129865992.000, train=0.0%, train_loss=148836416.000]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:15<00:06, 94.59it/s, test=0.1%, test_loss=2725851.250, train=0.3%, train_loss=3657856.250]

outcome_architecture/outcome:  70%|███████   | 1403/2000 [00:15<00:06, 87.10it/s, test=0.1%, test_loss=2725851.250, train=0.3%, train_loss=3657856.250]

outcome_architecture/outcome:  71%|███████   | 1413/2000 [00:15<00:06, 90.47it/s, test=0.1%, test_loss=2725851.250, train=0.3%, train_loss=3657856.250]

outcome_architecture/outcome:  71%|███████   | 1423/2000 [00:15<00:06, 92.13it/s, test=0.1%, test_loss=2725851.250, train=0.3%, train_loss=3657856.250]

outcome_architecture/outcome:  72%|███████▏  | 1433/2000 [00:15<00:06, 93.94it/s, test=0.1%, test_loss=2725851.250, train=0.3%, train_loss=3657856.250]

outcome_architecture/outcome:  72%|███████▏  | 1443/2000 [00:15<00:05, 95.62it/s, test=0.1%, test_loss=2725851.250, train=0.3%, train_loss=3657856.250]

outcome_architecture/outcome:  72%|███████▏  | 1443/2000 [00:16<00:05, 95.62it/s, test=0.6%, test_loss=735445.250, train=0.3%, train_loss=917448.750]

outcome_architecture/outcome:  73%|███████▎  | 1453/2000 [00:16<00:06, 87.42it/s, test=0.6%, test_loss=735445.250, train=0.3%, train_loss=917448.750]

outcome_architecture/outcome:  73%|███████▎  | 1463/2000 [00:16<00:05, 89.51it/s, test=0.6%, test_loss=735445.250, train=0.3%, train_loss=917448.750]

outcome_architecture/outcome:  74%|███████▎  | 1473/2000 [00:16<00:05, 91.70it/s, test=0.6%, test_loss=735445.250, train=0.3%, train_loss=917448.750]

outcome_architecture/outcome:  74%|███████▍  | 1483/2000 [00:16<00:05, 92.95it/s, test=0.6%, test_loss=735445.250, train=0.3%, train_loss=917448.750]

outcome_architecture/outcome:  75%|███████▍  | 1494/2000 [00:16<00:05, 96.39it/s, test=0.6%, test_loss=735445.250, train=0.3%, train_loss=917448.750]

outcome_architecture/outcome:  75%|███████▍  | 1494/2000 [00:16<00:05, 96.39it/s, test=0.3%, test_loss=574245.938, train=0.3%, train_loss=750499.312]

outcome_architecture/outcome:  75%|███████▌  | 1504/2000 [00:16<00:05, 89.82it/s, test=0.3%, test_loss=574245.938, train=0.3%, train_loss=750499.312]

outcome_architecture/outcome:  76%|███████▌  | 1515/2000 [00:16<00:05, 94.55it/s, test=0.3%, test_loss=574245.938, train=0.3%, train_loss=750499.312]

outcome_architecture/outcome:  76%|███████▋  | 1526/2000 [00:16<00:04, 97.71it/s, test=0.3%, test_loss=574245.938, train=0.3%, train_loss=750499.312]

outcome_architecture/outcome:  77%|███████▋  | 1537/2000 [00:16<00:04, 99.95it/s, test=0.3%, test_loss=574245.938, train=0.3%, train_loss=750499.312]

outcome_architecture/outcome:  77%|███████▋  | 1548/2000 [00:17<00:04, 101.56it/s, test=0.3%, test_loss=574245.938, train=0.3%, train_loss=750499.312]

outcome_architecture/outcome:  77%|███████▋  | 1548/2000 [00:17<00:04, 101.56it/s, test=0.5%, test_loss=521824.594, train=0.0%, train_loss=594000.312]

outcome_architecture/outcome:  78%|███████▊  | 1559/2000 [00:17<00:04, 93.51it/s, test=0.5%, test_loss=521824.594, train=0.0%, train_loss=594000.312]

outcome_architecture/outcome:  78%|███████▊  | 1570/2000 [00:17<00:04, 96.96it/s, test=0.5%, test_loss=521824.594, train=0.0%, train_loss=594000.312]

outcome_architecture/outcome:  79%|███████▉  | 1581/2000 [00:17<00:04, 98.49it/s, test=0.5%, test_loss=521824.594, train=0.0%, train_loss=594000.312]

outcome_architecture/outcome:  80%|███████▉  | 1592/2000 [00:17<00:04, 100.44it/s, test=0.5%, test_loss=521824.594, train=0.0%, train_loss=594000.312]

outcome_architecture/outcome:  80%|███████▉  | 1592/2000 [00:17<00:04, 100.44it/s, test=0.0%, test_loss=553036.062, train=0.0%, train_loss=637807.062]

outcome_architecture/outcome:  80%|████████  | 1603/2000 [00:17<00:04, 92.98it/s, test=0.0%, test_loss=553036.062, train=0.0%, train_loss=637807.062]

outcome_architecture/outcome:  81%|████████  | 1614/2000 [00:17<00:04, 95.67it/s, test=0.0%, test_loss=553036.062, train=0.0%, train_loss=637807.062]

outcome_architecture/outcome:  81%|████████▏ | 1625/2000 [00:17<00:03, 98.24it/s, test=0.0%, test_loss=553036.062, train=0.0%, train_loss=637807.062]

outcome_architecture/outcome:  82%|████████▏ | 1636/2000 [00:17<00:03, 100.18it/s, test=0.0%, test_loss=553036.062, train=0.0%, train_loss=637807.062]

outcome_architecture/outcome:  82%|████████▏ | 1647/2000 [00:18<00:03, 101.52it/s, test=0.0%, test_loss=553036.062, train=0.0%, train_loss=637807.062]

outcome_architecture/outcome:  82%|████████▏ | 1647/2000 [00:18<00:03, 101.52it/s, test=0.1%, test_loss=294580.750, train=0.0%, train_loss=308479.438]

outcome_architecture/outcome:  83%|████████▎ | 1658/2000 [00:18<00:03, 92.77it/s, test=0.1%, test_loss=294580.750, train=0.0%, train_loss=308479.438]

outcome_architecture/outcome:  83%|████████▎ | 1669/2000 [00:18<00:03, 95.89it/s, test=0.1%, test_loss=294580.750, train=0.0%, train_loss=308479.438]

outcome_architecture/outcome:  84%|████████▍ | 1680/2000 [00:18<00:03, 98.42it/s, test=0.1%, test_loss=294580.750, train=0.0%, train_loss=308479.438]

outcome_architecture/outcome:  85%|████████▍ | 1691/2000 [00:18<00:03, 99.61it/s, test=0.1%, test_loss=294580.750, train=0.0%, train_loss=308479.438]

outcome_architecture/outcome:  85%|████████▍ | 1691/2000 [00:18<00:03, 99.61it/s, test=0.2%, test_loss=399009.750, train=0.3%, train_loss=569530.312]

outcome_architecture/outcome:  85%|████████▌ | 1702/2000 [00:18<00:03, 90.39it/s, test=0.2%, test_loss=399009.750, train=0.3%, train_loss=569530.312]

outcome_architecture/outcome:  86%|████████▌ | 1712/2000 [00:18<00:03, 89.81it/s, test=0.2%, test_loss=399009.750, train=0.3%, train_loss=569530.312]

outcome_architecture/outcome:  86%|████████▌ | 1723/2000 [00:18<00:02, 93.99it/s, test=0.2%, test_loss=399009.750, train=0.3%, train_loss=569530.312]

outcome_architecture/outcome:  87%|████████▋ | 1734/2000 [00:19<00:02, 97.22it/s, test=0.2%, test_loss=399009.750, train=0.3%, train_loss=569530.312]

outcome_architecture/outcome:  87%|████████▋ | 1745/2000 [00:19<00:02, 98.94it/s, test=0.2%, test_loss=399009.750, train=0.3%, train_loss=569530.312]

outcome_architecture/outcome:  87%|████████▋ | 1745/2000 [00:19<00:02, 98.94it/s, test=0.1%, test_loss=299945.906, train=0.0%, train_loss=330921.906]

outcome_architecture/outcome:  88%|████████▊ | 1755/2000 [00:19<00:02, 91.27it/s, test=0.1%, test_loss=299945.906, train=0.0%, train_loss=330921.906]

outcome_architecture/outcome:  88%|████████▊ | 1765/2000 [00:19<00:02, 93.30it/s, test=0.1%, test_loss=299945.906, train=0.0%, train_loss=330921.906]

outcome_architecture/outcome:  89%|████████▉ | 1776/2000 [00:19<00:02, 95.72it/s, test=0.1%, test_loss=299945.906, train=0.0%, train_loss=330921.906]

outcome_architecture/outcome:  89%|████████▉ | 1787/2000 [00:19<00:02, 97.72it/s, test=0.1%, test_loss=299945.906, train=0.0%, train_loss=330921.906]

outcome_architecture/outcome:  90%|████████▉ | 1798/2000 [00:19<00:02, 99.44it/s, test=0.1%, test_loss=299945.906, train=0.0%, train_loss=330921.906]

outcome_architecture/outcome:  90%|████████▉ | 1798/2000 [00:19<00:02, 99.44it/s, test=0.3%, test_loss=230567.875, train=0.3%, train_loss=276950.875]

outcome_architecture/outcome:  90%|█████████ | 1808/2000 [00:19<00:02, 82.98it/s, test=0.3%, test_loss=230567.875, train=0.3%, train_loss=276950.875]

outcome_architecture/outcome:  91%|█████████ | 1819/2000 [00:19<00:02, 89.20it/s, test=0.3%, test_loss=230567.875, train=0.3%, train_loss=276950.875]

outcome_architecture/outcome:  92%|█████████▏| 1830/2000 [00:20<00:01, 93.69it/s, test=0.3%, test_loss=230567.875, train=0.3%, train_loss=276950.875]

outcome_architecture/outcome:  92%|█████████▏| 1841/2000 [00:20<00:01, 97.37it/s, test=0.3%, test_loss=230567.875, train=0.3%, train_loss=276950.875]

outcome_architecture/outcome:  92%|█████████▏| 1841/2000 [00:20<00:01, 97.37it/s, test=0.0%, test_loss=368546.594, train=0.3%, train_loss=466262.781]

outcome_architecture/outcome:  93%|█████████▎| 1852/2000 [00:20<00:01, 91.11it/s, test=0.0%, test_loss=368546.594, train=0.3%, train_loss=466262.781]

outcome_architecture/outcome:  93%|█████████▎| 1863/2000 [00:20<00:01, 95.50it/s, test=0.0%, test_loss=368546.594, train=0.3%, train_loss=466262.781]

outcome_architecture/outcome:  94%|█████████▎| 1874/2000 [00:20<00:01, 98.61it/s, test=0.0%, test_loss=368546.594, train=0.3%, train_loss=466262.781]

outcome_architecture/outcome:  94%|█████████▍| 1885/2000 [00:20<00:01, 98.83it/s, test=0.0%, test_loss=368546.594, train=0.3%, train_loss=466262.781]

outcome_architecture/outcome:  95%|█████████▍| 1896/2000 [00:20<00:01, 100.86it/s, test=0.0%, test_loss=368546.594, train=0.3%, train_loss=466262.781]

outcome_architecture/outcome:  95%|█████████▍| 1896/2000 [00:20<00:01, 100.86it/s, test=0.1%, test_loss=223754.078, train=0.3%, train_loss=303718.656]

outcome_architecture/outcome:  95%|█████████▌| 1907/2000 [00:20<00:00, 93.41it/s, test=0.1%, test_loss=223754.078, train=0.3%, train_loss=303718.656]

outcome_architecture/outcome:  96%|█████████▌| 1918/2000 [00:20<00:00, 96.96it/s, test=0.1%, test_loss=223754.078, train=0.3%, train_loss=303718.656]

outcome_architecture/outcome:  96%|█████████▋| 1929/2000 [00:21<00:00, 99.61it/s, test=0.1%, test_loss=223754.078, train=0.3%, train_loss=303718.656]

outcome_architecture/outcome:  97%|█████████▋| 1940/2000 [00:21<00:00, 100.52it/s, test=0.1%, test_loss=223754.078, train=0.3%, train_loss=303718.656]

outcome_architecture/outcome:  97%|█████████▋| 1940/2000 [00:21<00:00, 100.52it/s, test=0.4%, test_loss=179637.812, train=0.3%, train_loss=206136.875]

outcome_architecture/outcome:  98%|█████████▊| 1951/2000 [00:21<00:00, 92.26it/s, test=0.4%, test_loss=179637.812, train=0.3%, train_loss=206136.875]

outcome_architecture/outcome:  98%|█████████▊| 1962/2000 [00:21<00:00, 96.11it/s, test=0.4%, test_loss=179637.812, train=0.3%, train_loss=206136.875]

outcome_architecture/outcome:  99%|█████████▊| 1973/2000 [00:21<00:00, 98.80it/s, test=0.4%, test_loss=179637.812, train=0.3%, train_loss=206136.875]

outcome_architecture/outcome:  99%|█████████▉| 1984/2000 [00:21<00:00, 100.94it/s, test=0.4%, test_loss=179637.812, train=0.3%, train_loss=206136.875]

outcome_architecture/outcome: 100%|█████████▉| 1995/2000 [00:21<00:00, 102.58it/s, test=0.4%, test_loss=179637.812, train=0.3%, train_loss=206136.875]

outcome_architecture/outcome: 100%|█████████▉| 1995/2000 [00:21<00:00, 102.58it/s, test=0.1%, test_loss=188521.391, train=0.0%, train_loss=261824.688]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 91.71it/s, test=0.1%, test_loss=188521.391, train=0.0%, train_loss=261824.688]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,process,4.276747,0.000000,0.000,0.0,4.276700
1,1,process_architecture,process,4.260411,0.000000,0.000,0.0,4.260053
2,2,process_architecture,process,4.235844,0.000000,0.000,0.0,4.234654
3,5,process_architecture,process,3.919410,0.000000,0.000,0.0,3.902919
4,10,process_architecture,process,3.684902,0.000000,0.000,0.0,3.660361
...,...,...,...,...,...,...,...,...
91,1800,outcome_architecture,outcome,276950.875000,0.003333,0.003,0.0,230567.875000
92,1850,outcome_architecture,outcome,466262.781250,0.003333,0.000,0.0,368546.593750
93,1900,outcome_architecture,outcome,303718.656250,0.003333,0.001,0.0,223754.078125
94,1950,outcome_architecture,outcome,206136.875000,0.003333,0.004,0.0,179637.812500
95,2000,outcome_architecture,outcome,261824.687500,0.000000,0.001,0.0,188521.390625


## 7. Final behavioral comparison

The four displayed rows are:

- two fixed references,
- two trained models.

But only the latter two were optimized.

In [8]:

rows = []

for name, model, mode, trained in [
    ("Fixed PROCESS reference", process_reference, "process", False),
    ("Trained PROCESS architecture", trained_process, "process", True),
    ("Fixed OUTCOME reference", outcome_reference, "outcome", False),
    ("Trained OUTCOME architecture", trained_outcome, "outcome", True),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    rows.append({
        "model": name,
        "optimized": trained,
        "mode": mode,
        "test_answer_accuracy": metrics["final_answer"],
        "test_exact_continuation": metrics["exact_continuation"],
    })

final_results = pd.DataFrame(rows)
final_results

,model,optimized,mode,test_answer_accuracy,test_exact_continuation
0,Fixed PROCESS reference,False,process,1.000,1.0
1,Trained PROCESS architecture,True,process,1.000,1.0
2,Fixed OUTCOME reference,False,outcome,1.000,1.0
3,Trained OUTCOME architecture,True,outcome,0.001,0.0

## 8. Learning curves

The first plot tracks free-running answer accuracy. The second plot tracks teacher-forced training and held-out test loss at the same checkpoints.

In [9]:

fig, ax = plt.subplots(figsize=(8, 4.5))

for (architecture, mode), frame in history.groupby(["architecture", "mode"]):
    ax.plot(
        frame["step"],
        frame["test_answer_accuracy"],
        marker="o",
        label=f"{architecture} / {mode}",
    )

ax.axhline(1.0, linestyle="--", label="constructive solution = 100%")
ax.axhline(1 / tokenizer.n_states, linestyle=":", label="chance")
ax.set_xlabel("optimization step")
ax.set_ylabel("free-running test answer accuracy")
ax.set_ylim(-0.02, 1.03)
ax.legend()
plt.show()

In [10]:
def plot_train_test_loss(history, *, steps=STEPS):
    required = {"architecture", "mode", "step", "train_loss", "test_loss"}
    missing = required.difference(history.columns)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"history is missing required columns: {missing_text}")

    fig, ax = plt.subplots(figsize=(9, 5))
    styles = {
        ("process_architecture", "process"): {
            "color": "#2ca02c",
            "label": "PROCESS architecture / process",
        },
        ("outcome_architecture", "outcome"): {
            "color": "#d62728",
            "label": "OUTCOME architecture / outcome",
        },
    }

    for key, frame in history.sort_values("step").groupby(["architecture", "mode"]):
        style = styles.get(key, {"color": None, "label": " / ".join(map(str, key))})
        ax.plot(
            frame["step"],
            frame["train_loss"],
            color=style["color"],
            linewidth=2.2,
            label=f"{style['label']} train",
        )
        ax.plot(
            frame["step"],
            frame["test_loss"],
            color=style["color"],
            linestyle="--",
            linewidth=2.2,
            label=f"{style['label']} test",
        )

    ax.set_xlabel("Iteration", fontsize=13)
    ax.set_ylabel("Teacher-forced loss", fontsize=13)
    ax.set_xlim(0, steps)
    ax.grid(True, alpha=0.35)
    ax.legend(frameon=True, fontsize=10)
    fig.tight_layout()
    return fig, ax

plot_train_test_loss(history)
plt.show()


## 9. Inspect one free-running example

No gold continuation is fed to the model during this evaluation.

In [11]:

example_prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Trained PROCESS", trained_process, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
    ("Trained OUTCOME", trained_outcome, "outcome"),
]:
    budget = 3 if mode == "outcome" else 2 * DEPTH + 3
    generated = generate(
        model,
        example_prompt,
        budget,
        tokenizer.eos,
    )
    continuation = generated[0, example_prompt.shape[1]:]
    print(f"\n{name}")
    print(tokenizer.decode(continuation))

Fixed PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Trained PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Fixed OUTCOME
<COLON> S1001 <EOS>

Trained OUTCOME
S0001 S0001 S0001


## 10. How to interpret the result

There are four broad possibilities.

### Both trained models reach 100%

The two constructive solution classes are readily reachable from this initialization and optimizer.

### PROCESS reaches 100%, OUTCOME does not

Then

\[
\exists\theta^\star_{\rm O}:\operatorname{Err}(\theta^\star_{\rm O})=0
\]

but the tested terminal-supervision optimization trajectory does not discover it.

That is evidence for a **trainability / accessibility gap**, not an expressivity gap.

### OUTCOME reaches 100%, PROCESS does not

Then the existence of an explicit local process circuit does not by itself guarantee that ordinary trace training discovers it.

### Neither reaches 100%

Then constructive realizability and optimization reachability are substantially different for both architectures.

---

Do not infer an impossibility theorem from a failed run. Multiple seeds, learning-rate controls, and optimizer-stability diagnostics are needed before making a strong optimization claim.


# Optional appendix: full $2\times2$ architecture × supervision experiment

The primary notebook above trains exactly **two** models.

A separate, stronger control can cross:

\[
\{\text{PROCESS architecture},\text{OUTCOME architecture}\}
\times
\{\text{PROCESS supervision},\text{OUTCOME supervision}\}.
\]

That experiment trains **four** models and should be reported separately.

It requires the OUTCOME architecture to use the longer PROCESS position budget, so it is intentionally not the exact diagonal reachability experiment above.

In [12]:
RUN_OPTIONAL_2X2 = True

if RUN_OPTIONAL_2X2:
    from handcoded_utils import (
        build_random_trainable_outcome_architecture,
        build_random_trainable_process_architecture,
        run_architecture_experiment,
    )

    bases = {
        "process_architecture": build_random_trainable_process_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
        "outcome_architecture": build_random_trainable_outcome_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
    }

    models_2x2, history_2x2 = run_architecture_experiment(
        bases,
        training_data,
        batch_schedule,
        LR,
        CHECKPOINTS,
        train_eval,
        test_eval,
        tokenizer,
        circuit_prompts,
        test_loss_data=test_loss_data,
        loss_eval_size=LOSS_EVAL_SIZE,
    )

    display(history_2x2.drop(columns=["circuit_matrix"], errors="ignore"))
else:
    print("Skipping optional 2x2 experiment. Set RUN_OPTIONAL_2X2 = True to run it.")

architecture/mode:   0%|          | 0/4 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.212, train=0.0%, train_loss=4.212]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.124, train=0.0%, train_loss=4.124]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:04, 10.86it/s, test=0.0%, test_loss=4.124, train=0.0%, train_loss=4.124]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:04, 10.86it/s, test=0.0%, test_loss=2.992, train=0.0%, train_loss=2.995]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:04, 10.86it/s, test=0.0%, test_loss=1.748, train=0.0%, train_loss=1.764]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:31, 62.38it/s, test=0.0%, test_loss=1.748, train=0.0%, train_loss=1.764]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:31, 62.38it/s, test=0.0%, test_loss=1.130, train=0.0%, train_loss=1.123]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:31, 62.38it/s, test=0.6%, test_loss=1.095, train=0.0%, train_loss=1.092]

process_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:23, 83.69it/s, test=0.6%, test_loss=1.095, train=0.0%, train_loss=1.092]

process_architecture/outcome:   2%|▏         | 46/2000 [00:00<00:16, 120.02it/s, test=0.6%, test_loss=1.095, train=0.0%, train_loss=1.092]

process_architecture/outcome:   2%|▏         | 46/2000 [00:00<00:16, 120.02it/s, test=7.5%, test_loss=0.924, train=7.0%, train_loss=0.940]

process_architecture/outcome:   3%|▎         | 62/2000 [00:00<00:14, 130.73it/s, test=7.5%, test_loss=0.924, train=7.0%, train_loss=0.940]

process_architecture/outcome:   3%|▎         | 62/2000 [00:00<00:14, 130.73it/s, test=10.8%, test_loss=0.925, train=8.7%, train_loss=0.937]

process_architecture/outcome:   4%|▍         | 78/2000 [00:00<00:13, 138.48it/s, test=10.8%, test_loss=0.925, train=8.7%, train_loss=0.937]

process_architecture/outcome:   5%|▍         | 97/2000 [00:00<00:12, 153.36it/s, test=10.8%, test_loss=0.925, train=8.7%, train_loss=0.937]

process_architecture/outcome:   5%|▍         | 97/2000 [00:00<00:12, 153.36it/s, test=9.7%, test_loss=0.920, train=11.0%, train_loss=0.917]

process_architecture/outcome:   6%|▌         | 113/2000 [00:00<00:12, 150.80it/s, test=9.7%, test_loss=0.920, train=11.0%, train_loss=0.917]

process_architecture/outcome:   7%|▋         | 131/2000 [00:01<00:11, 158.62it/s, test=9.7%, test_loss=0.920, train=11.0%, train_loss=0.917]

process_architecture/outcome:   7%|▋         | 149/2000 [00:01<00:11, 163.45it/s, test=9.7%, test_loss=0.920, train=11.0%, train_loss=0.917]

process_architecture/outcome:   7%|▋         | 149/2000 [00:01<00:11, 163.45it/s, test=11.7%, test_loss=0.904, train=7.7%, train_loss=0.908]

process_architecture/outcome:   8%|▊         | 166/2000 [00:01<00:11, 156.62it/s, test=11.7%, test_loss=0.904, train=7.7%, train_loss=0.908]

process_architecture/outcome:   9%|▉         | 186/2000 [00:01<00:10, 168.79it/s, test=11.7%, test_loss=0.904, train=7.7%, train_loss=0.908]

process_architecture/outcome:   9%|▉         | 186/2000 [00:01<00:10, 168.79it/s, test=11.7%, test_loss=0.902, train=10.7%, train_loss=0.899]

process_architecture/outcome:  10%|█         | 204/2000 [00:01<00:10, 168.46it/s, test=11.7%, test_loss=0.902, train=10.7%, train_loss=0.899]

process_architecture/outcome:  11%|█         | 222/2000 [00:01<00:10, 171.51it/s, test=11.7%, test_loss=0.902, train=10.7%, train_loss=0.899]

process_architecture/outcome:  12%|█▏        | 241/2000 [00:01<00:10, 175.33it/s, test=11.7%, test_loss=0.902, train=10.7%, train_loss=0.899]

process_architecture/outcome:  12%|█▏        | 241/2000 [00:01<00:10, 175.33it/s, test=9.5%, test_loss=0.888, train=7.7%, train_loss=0.880]

process_architecture/outcome:  13%|█▎        | 259/2000 [00:01<00:10, 173.53it/s, test=9.5%, test_loss=0.888, train=7.7%, train_loss=0.880]

process_architecture/outcome:  14%|█▍        | 279/2000 [00:01<00:09, 181.08it/s, test=9.5%, test_loss=0.888, train=7.7%, train_loss=0.880]

process_architecture/outcome:  14%|█▍        | 279/2000 [00:01<00:09, 181.08it/s, test=9.7%, test_loss=0.882, train=9.3%, train_loss=0.876]

process_architecture/outcome:  15%|█▌        | 300/2000 [00:01<00:09, 178.86it/s, test=9.7%, test_loss=0.882, train=9.3%, train_loss=0.876]

process_architecture/outcome:  16%|█▌        | 320/2000 [00:02<00:09, 184.22it/s, test=9.7%, test_loss=0.882, train=9.3%, train_loss=0.876]

process_architecture/outcome:  17%|█▋        | 340/2000 [00:02<00:08, 188.23it/s, test=9.7%, test_loss=0.882, train=9.3%, train_loss=0.876]

process_architecture/outcome:  17%|█▋        | 340/2000 [00:02<00:08, 188.23it/s, test=11.5%, test_loss=0.870, train=12.0%, train_loss=0.884]

process_architecture/outcome:  18%|█▊        | 359/2000 [00:02<00:09, 182.01it/s, test=11.5%, test_loss=0.870, train=12.0%, train_loss=0.884]

process_architecture/outcome:  19%|█▉        | 380/2000 [00:02<00:08, 187.52it/s, test=11.5%, test_loss=0.870, train=12.0%, train_loss=0.884]

process_architecture/outcome:  19%|█▉        | 380/2000 [00:02<00:08, 187.52it/s, test=12.9%, test_loss=0.866, train=12.0%, train_loss=0.879]

process_architecture/outcome:  20%|██        | 400/2000 [00:02<00:08, 182.12it/s, test=12.9%, test_loss=0.866, train=12.0%, train_loss=0.879]

process_architecture/outcome:  21%|██        | 420/2000 [00:02<00:08, 186.57it/s, test=12.9%, test_loss=0.866, train=12.0%, train_loss=0.879]

process_architecture/outcome:  22%|██▏       | 440/2000 [00:02<00:08, 190.05it/s, test=12.9%, test_loss=0.866, train=12.0%, train_loss=0.879]

process_architecture/outcome:  22%|██▏       | 440/2000 [00:02<00:08, 190.05it/s, test=12.6%, test_loss=0.857, train=11.3%, train_loss=0.848]

process_architecture/outcome:  23%|██▎       | 460/2000 [00:02<00:08, 183.51it/s, test=12.6%, test_loss=0.857, train=11.3%, train_loss=0.848]

process_architecture/outcome:  24%|██▍       | 481/2000 [00:02<00:08, 188.55it/s, test=12.6%, test_loss=0.857, train=11.3%, train_loss=0.848]

process_architecture/outcome:  24%|██▍       | 481/2000 [00:03<00:08, 188.55it/s, test=14.2%, test_loss=0.855, train=12.7%, train_loss=0.850]

process_architecture/outcome:  25%|██▌       | 500/2000 [00:03<00:08, 182.20it/s, test=14.2%, test_loss=0.855, train=12.7%, train_loss=0.850]

process_architecture/outcome:  26%|██▌       | 520/2000 [00:03<00:07, 187.10it/s, test=14.2%, test_loss=0.855, train=12.7%, train_loss=0.850]

process_architecture/outcome:  27%|██▋       | 540/2000 [00:03<00:07, 190.54it/s, test=14.2%, test_loss=0.855, train=12.7%, train_loss=0.850]

process_architecture/outcome:  27%|██▋       | 540/2000 [00:03<00:07, 190.54it/s, test=12.7%, test_loss=0.865, train=11.7%, train_loss=0.837]

process_architecture/outcome:  28%|██▊       | 560/2000 [00:03<00:07, 184.48it/s, test=12.7%, test_loss=0.865, train=11.7%, train_loss=0.837]

process_architecture/outcome:  29%|██▉       | 581/2000 [00:03<00:07, 189.15it/s, test=12.7%, test_loss=0.865, train=11.7%, train_loss=0.837]

process_architecture/outcome:  29%|██▉       | 581/2000 [00:03<00:07, 189.15it/s, test=13.4%, test_loss=0.858, train=12.0%, train_loss=0.843]

process_architecture/outcome:  30%|███       | 600/2000 [00:03<00:07, 182.67it/s, test=13.4%, test_loss=0.858, train=12.0%, train_loss=0.843]

process_architecture/outcome:  31%|███       | 620/2000 [00:03<00:07, 186.78it/s, test=13.4%, test_loss=0.858, train=12.0%, train_loss=0.843]

process_architecture/outcome:  32%|███▏      | 640/2000 [00:03<00:07, 190.49it/s, test=13.4%, test_loss=0.858, train=12.0%, train_loss=0.843]

process_architecture/outcome:  32%|███▏      | 640/2000 [00:03<00:07, 190.49it/s, test=12.4%, test_loss=0.852, train=12.0%, train_loss=0.845]

process_architecture/outcome:  33%|███▎      | 660/2000 [00:03<00:07, 184.11it/s, test=12.4%, test_loss=0.852, train=12.0%, train_loss=0.845]

process_architecture/outcome:  34%|███▍      | 681/2000 [00:04<00:06, 189.37it/s, test=12.4%, test_loss=0.852, train=12.0%, train_loss=0.845]

process_architecture/outcome:  34%|███▍      | 681/2000 [00:04<00:06, 189.37it/s, test=15.4%, test_loss=0.849, train=14.3%, train_loss=0.849]

process_architecture/outcome:  35%|███▌      | 701/2000 [00:04<00:07, 182.83it/s, test=15.4%, test_loss=0.849, train=14.3%, train_loss=0.849]

process_architecture/outcome:  36%|███▌      | 721/2000 [00:04<00:06, 187.47it/s, test=15.4%, test_loss=0.849, train=14.3%, train_loss=0.849]

process_architecture/outcome:  37%|███▋      | 742/2000 [00:04<00:06, 191.07it/s, test=15.4%, test_loss=0.849, train=14.3%, train_loss=0.849]

process_architecture/outcome:  37%|███▋      | 742/2000 [00:04<00:06, 191.07it/s, test=14.7%, test_loss=0.849, train=12.7%, train_loss=0.840]

process_architecture/outcome:  38%|███▊      | 762/2000 [00:04<00:06, 185.07it/s, test=14.7%, test_loss=0.849, train=12.7%, train_loss=0.840]

process_architecture/outcome:  39%|███▉      | 782/2000 [00:04<00:06, 187.89it/s, test=14.7%, test_loss=0.849, train=12.7%, train_loss=0.840]

process_architecture/outcome:  39%|███▉      | 782/2000 [00:04<00:06, 187.89it/s, test=14.0%, test_loss=0.857, train=13.3%, train_loss=0.842]

process_architecture/outcome:  40%|████      | 801/2000 [00:04<00:06, 182.17it/s, test=14.0%, test_loss=0.857, train=13.3%, train_loss=0.842]

process_architecture/outcome:  41%|████      | 822/2000 [00:04<00:06, 186.30it/s, test=14.0%, test_loss=0.857, train=13.3%, train_loss=0.842]

process_architecture/outcome:  42%|████▏     | 842/2000 [00:04<00:06, 188.14it/s, test=14.0%, test_loss=0.857, train=13.3%, train_loss=0.842]

process_architecture/outcome:  42%|████▏     | 842/2000 [00:04<00:06, 188.14it/s, test=15.6%, test_loss=0.838, train=13.0%, train_loss=0.835]

process_architecture/outcome:  43%|████▎     | 861/2000 [00:04<00:06, 183.54it/s, test=15.6%, test_loss=0.838, train=13.0%, train_loss=0.835]

process_architecture/outcome:  44%|████▍     | 882/2000 [00:05<00:05, 187.47it/s, test=15.6%, test_loss=0.838, train=13.0%, train_loss=0.835]

process_architecture/outcome:  44%|████▍     | 882/2000 [00:05<00:05, 187.47it/s, test=15.8%, test_loss=0.867, train=13.3%, train_loss=0.838]

process_architecture/outcome:  45%|████▌     | 901/2000 [00:05<00:06, 180.09it/s, test=15.8%, test_loss=0.867, train=13.3%, train_loss=0.838]

process_architecture/outcome:  46%|████▌     | 922/2000 [00:05<00:05, 186.09it/s, test=15.8%, test_loss=0.867, train=13.3%, train_loss=0.838]

process_architecture/outcome:  47%|████▋     | 942/2000 [00:05<00:05, 187.59it/s, test=15.8%, test_loss=0.867, train=13.3%, train_loss=0.838]

process_architecture/outcome:  47%|████▋     | 942/2000 [00:05<00:05, 187.59it/s, test=18.6%, test_loss=0.841, train=15.0%, train_loss=0.850]

process_architecture/outcome:  48%|████▊     | 961/2000 [00:05<00:05, 182.24it/s, test=18.6%, test_loss=0.841, train=15.0%, train_loss=0.850]

process_architecture/outcome:  49%|████▉     | 982/2000 [00:05<00:05, 188.13it/s, test=18.6%, test_loss=0.841, train=15.0%, train_loss=0.850]

process_architecture/outcome:  49%|████▉     | 982/2000 [00:05<00:05, 188.13it/s, test=18.6%, test_loss=0.831, train=15.7%, train_loss=0.798]

process_architecture/outcome:  50%|█████     | 1001/2000 [00:05<00:05, 181.15it/s, test=18.6%, test_loss=0.831, train=15.7%, train_loss=0.798]

process_architecture/outcome:  51%|█████     | 1022/2000 [00:05<00:05, 186.75it/s, test=18.6%, test_loss=0.831, train=15.7%, train_loss=0.798]

process_architecture/outcome:  52%|█████▏    | 1043/2000 [00:05<00:05, 191.08it/s, test=18.6%, test_loss=0.831, train=15.7%, train_loss=0.798]

process_architecture/outcome:  52%|█████▏    | 1043/2000 [00:06<00:05, 191.08it/s, test=18.9%, test_loss=0.792, train=18.3%, train_loss=0.816]

process_architecture/outcome:  53%|█████▎    | 1063/2000 [00:06<00:05, 181.92it/s, test=18.9%, test_loss=0.792, train=18.3%, train_loss=0.816]

process_architecture/outcome:  54%|█████▍    | 1083/2000 [00:06<00:04, 186.82it/s, test=18.9%, test_loss=0.792, train=18.3%, train_loss=0.816]

process_architecture/outcome:  54%|█████▍    | 1083/2000 [00:06<00:04, 186.82it/s, test=17.1%, test_loss=0.815, train=20.7%, train_loss=0.799]

process_architecture/outcome:  55%|█████▌    | 1102/2000 [00:06<00:04, 181.80it/s, test=17.1%, test_loss=0.815, train=20.7%, train_loss=0.799]

process_architecture/outcome:  56%|█████▌    | 1121/2000 [00:06<00:04, 183.27it/s, test=17.1%, test_loss=0.815, train=20.7%, train_loss=0.799]

process_architecture/outcome:  57%|█████▋    | 1142/2000 [00:06<00:04, 189.14it/s, test=17.1%, test_loss=0.815, train=20.7%, train_loss=0.799]

process_architecture/outcome:  57%|█████▋    | 1142/2000 [00:06<00:04, 189.14it/s, test=18.1%, test_loss=0.772, train=19.3%, train_loss=0.764]

process_architecture/outcome:  58%|█████▊    | 1161/2000 [00:06<00:04, 183.81it/s, test=18.1%, test_loss=0.772, train=19.3%, train_loss=0.764]

process_architecture/outcome:  59%|█████▉    | 1180/2000 [00:06<00:04, 184.13it/s, test=18.1%, test_loss=0.772, train=19.3%, train_loss=0.764]

process_architecture/outcome:  59%|█████▉    | 1180/2000 [00:06<00:04, 184.13it/s, test=21.0%, test_loss=0.793, train=22.0%, train_loss=0.751]

process_architecture/outcome:  60%|██████    | 1200/2000 [00:06<00:04, 180.08it/s, test=21.0%, test_loss=0.793, train=22.0%, train_loss=0.751]

process_architecture/outcome:  61%|██████    | 1221/2000 [00:06<00:04, 186.34it/s, test=21.0%, test_loss=0.793, train=22.0%, train_loss=0.751]

process_architecture/outcome:  62%|██████▏   | 1242/2000 [00:07<00:03, 190.50it/s, test=21.0%, test_loss=0.793, train=22.0%, train_loss=0.751]

process_architecture/outcome:  62%|██████▏   | 1242/2000 [00:07<00:03, 190.50it/s, test=19.9%, test_loss=0.781, train=19.3%, train_loss=0.757]

process_architecture/outcome:  63%|██████▎   | 1262/2000 [00:07<00:04, 184.37it/s, test=19.9%, test_loss=0.781, train=19.3%, train_loss=0.757]

process_architecture/outcome:  64%|██████▍   | 1283/2000 [00:07<00:03, 189.81it/s, test=19.9%, test_loss=0.781, train=19.3%, train_loss=0.757]

process_architecture/outcome:  64%|██████▍   | 1283/2000 [00:07<00:03, 189.81it/s, test=23.7%, test_loss=0.755, train=20.3%, train_loss=0.696]

process_architecture/outcome:  65%|██████▌   | 1303/2000 [00:07<00:03, 183.45it/s, test=23.7%, test_loss=0.755, train=20.3%, train_loss=0.696]

process_architecture/outcome:  66%|██████▌   | 1324/2000 [00:07<00:03, 188.55it/s, test=23.7%, test_loss=0.755, train=20.3%, train_loss=0.696]

process_architecture/outcome:  67%|██████▋   | 1345/2000 [00:07<00:03, 192.35it/s, test=23.7%, test_loss=0.755, train=20.3%, train_loss=0.696]

process_architecture/outcome:  67%|██████▋   | 1345/2000 [00:07<00:03, 192.35it/s, test=21.5%, test_loss=0.757, train=19.7%, train_loss=0.690]

process_architecture/outcome:  68%|██████▊   | 1365/2000 [00:07<00:03, 184.71it/s, test=21.5%, test_loss=0.757, train=19.7%, train_loss=0.690]

process_architecture/outcome:  69%|██████▉   | 1386/2000 [00:07<00:03, 189.36it/s, test=21.5%, test_loss=0.757, train=19.7%, train_loss=0.690]

process_architecture/outcome:  69%|██████▉   | 1386/2000 [00:07<00:03, 189.36it/s, test=25.8%, test_loss=0.794, train=23.0%, train_loss=0.660]

process_architecture/outcome:  70%|███████   | 1406/2000 [00:07<00:03, 182.91it/s, test=25.8%, test_loss=0.794, train=23.0%, train_loss=0.660]

process_architecture/outcome:  71%|███████▏  | 1425/2000 [00:08<00:03, 181.44it/s, test=25.8%, test_loss=0.794, train=23.0%, train_loss=0.660]

process_architecture/outcome:  72%|███████▏  | 1446/2000 [00:08<00:02, 187.86it/s, test=25.8%, test_loss=0.794, train=23.0%, train_loss=0.660]

process_architecture/outcome:  72%|███████▏  | 1446/2000 [00:08<00:02, 187.86it/s, test=24.9%, test_loss=0.730, train=29.3%, train_loss=0.674]

process_architecture/outcome:  73%|███████▎  | 1465/2000 [00:08<00:02, 182.41it/s, test=24.9%, test_loss=0.730, train=29.3%, train_loss=0.674]

process_architecture/outcome:  74%|███████▍  | 1485/2000 [00:08<00:02, 186.64it/s, test=24.9%, test_loss=0.730, train=29.3%, train_loss=0.674]

process_architecture/outcome:  74%|███████▍  | 1485/2000 [00:08<00:02, 186.64it/s, test=27.0%, test_loss=0.684, train=28.3%, train_loss=0.606]

process_architecture/outcome:  75%|███████▌  | 1504/2000 [00:08<00:02, 181.80it/s, test=27.0%, test_loss=0.684, train=28.3%, train_loss=0.606]

process_architecture/outcome:  76%|███████▋  | 1525/2000 [00:08<00:02, 188.26it/s, test=27.0%, test_loss=0.684, train=28.3%, train_loss=0.606]

process_architecture/outcome:  77%|███████▋  | 1546/2000 [00:08<00:02, 191.80it/s, test=27.0%, test_loss=0.684, train=28.3%, train_loss=0.606]

process_architecture/outcome:  77%|███████▋  | 1546/2000 [00:08<00:02, 191.80it/s, test=28.5%, test_loss=0.709, train=31.0%, train_loss=0.639]

process_architecture/outcome:  78%|███████▊  | 1566/2000 [00:08<00:02, 185.64it/s, test=28.5%, test_loss=0.709, train=31.0%, train_loss=0.639]

process_architecture/outcome:  79%|███████▉  | 1585/2000 [00:08<00:02, 186.19it/s, test=28.5%, test_loss=0.709, train=31.0%, train_loss=0.639]

process_architecture/outcome:  79%|███████▉  | 1585/2000 [00:08<00:02, 186.19it/s, test=27.5%, test_loss=0.736, train=34.3%, train_loss=0.589]

process_architecture/outcome:  80%|████████  | 1604/2000 [00:08<00:02, 181.59it/s, test=27.5%, test_loss=0.736, train=34.3%, train_loss=0.589]

process_architecture/outcome:  81%|████████▏ | 1625/2000 [00:09<00:01, 188.54it/s, test=27.5%, test_loss=0.736, train=34.3%, train_loss=0.589]

process_architecture/outcome:  82%|████████▏ | 1646/2000 [00:09<00:01, 192.84it/s, test=27.5%, test_loss=0.736, train=34.3%, train_loss=0.589]

process_architecture/outcome:  82%|████████▏ | 1646/2000 [00:09<00:01, 192.84it/s, test=29.9%, test_loss=0.725, train=35.7%, train_loss=0.661]

process_architecture/outcome:  83%|████████▎ | 1666/2000 [00:09<00:01, 185.91it/s, test=29.9%, test_loss=0.725, train=35.7%, train_loss=0.661]

process_architecture/outcome:  84%|████████▍ | 1687/2000 [00:09<00:01, 190.81it/s, test=29.9%, test_loss=0.725, train=35.7%, train_loss=0.661]

process_architecture/outcome:  84%|████████▍ | 1687/2000 [00:09<00:01, 190.81it/s, test=28.6%, test_loss=0.707, train=35.3%, train_loss=0.618]

process_architecture/outcome:  85%|████████▌ | 1707/2000 [00:09<00:01, 185.12it/s, test=28.6%, test_loss=0.707, train=35.3%, train_loss=0.618]

process_architecture/outcome:  86%|████████▋ | 1728/2000 [00:09<00:01, 190.20it/s, test=28.6%, test_loss=0.707, train=35.3%, train_loss=0.618]

process_architecture/outcome:  87%|████████▋ | 1749/2000 [00:09<00:01, 193.66it/s, test=28.6%, test_loss=0.707, train=35.3%, train_loss=0.618]

process_architecture/outcome:  87%|████████▋ | 1749/2000 [00:09<00:01, 193.66it/s, test=30.7%, test_loss=0.671, train=35.3%, train_loss=0.616]

process_architecture/outcome:  88%|████████▊ | 1769/2000 [00:09<00:01, 186.44it/s, test=30.7%, test_loss=0.671, train=35.3%, train_loss=0.616]

process_architecture/outcome:  90%|████████▉ | 1790/2000 [00:09<00:01, 191.29it/s, test=30.7%, test_loss=0.671, train=35.3%, train_loss=0.616]

process_architecture/outcome:  90%|████████▉ | 1790/2000 [00:10<00:01, 191.29it/s, test=31.2%, test_loss=0.673, train=32.3%, train_loss=0.630]

process_architecture/outcome:  90%|█████████ | 1810/2000 [00:10<00:01, 185.28it/s, test=31.2%, test_loss=0.673, train=32.3%, train_loss=0.630]

process_architecture/outcome:  92%|█████████▏| 1831/2000 [00:10<00:00, 190.06it/s, test=31.2%, test_loss=0.673, train=32.3%, train_loss=0.630]

process_architecture/outcome:  92%|█████████▏| 1831/2000 [00:10<00:00, 190.06it/s, test=33.2%, test_loss=0.621, train=31.7%, train_loss=0.580]

process_architecture/outcome:  93%|█████████▎| 1851/2000 [00:10<00:00, 184.06it/s, test=33.2%, test_loss=0.621, train=31.7%, train_loss=0.580]

process_architecture/outcome:  94%|█████████▎| 1872/2000 [00:10<00:00, 188.75it/s, test=33.2%, test_loss=0.621, train=31.7%, train_loss=0.580]

process_architecture/outcome:  95%|█████████▍| 1891/2000 [00:10<00:00, 188.89it/s, test=33.2%, test_loss=0.621, train=31.7%, train_loss=0.580]

process_architecture/outcome:  95%|█████████▍| 1891/2000 [00:10<00:00, 188.89it/s, test=31.9%, test_loss=0.650, train=33.3%, train_loss=0.597]

process_architecture/outcome:  96%|█████████▌| 1910/2000 [00:10<00:00, 183.79it/s, test=31.9%, test_loss=0.650, train=33.3%, train_loss=0.597]

process_architecture/outcome:  97%|█████████▋| 1931/2000 [00:10<00:00, 188.73it/s, test=31.9%, test_loss=0.650, train=33.3%, train_loss=0.597]

process_architecture/outcome:  97%|█████████▋| 1931/2000 [00:10<00:00, 188.73it/s, test=33.5%, test_loss=0.639, train=35.7%, train_loss=0.532]

process_architecture/outcome:  98%|█████████▊| 1950/2000 [00:10<00:00, 180.48it/s, test=33.5%, test_loss=0.639, train=35.7%, train_loss=0.532]

process_architecture/outcome:  99%|█████████▊| 1971/2000 [00:10<00:00, 187.42it/s, test=33.5%, test_loss=0.639, train=35.7%, train_loss=0.532]

process_architecture/outcome: 100%|█████████▉| 1991/2000 [00:11<00:00, 190.25it/s, test=33.5%, test_loss=0.639, train=35.7%, train_loss=0.532]

process_architecture/outcome: 100%|█████████▉| 1991/2000 [00:11<00:00, 190.25it/s, test=32.9%, test_loss=0.640, train=39.3%, train_loss=0.594]

process_architecture/outcome: 100%|██████████| 2000/2000 [00:11<00:00, 180.21it/s, test=32.9%, test_loss=0.640, train=39.3%, train_loss=0.594]

architecture/mode:  25%|██▌       | 1/4 [00:11<00:33, 11.12s/it]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.260, train=0.0%, train_loss=4.260]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.235, train=0.0%, train_loss=4.236]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.903, train=0.0%, train_loss=3.919]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.660, train=0.0%, train_loss=3.685]

process_architecture/process:   0%|          | 10/2000 [00:00<00:23, 86.47it/s, test=0.0%, test_loss=3.660, train=0.0%, train_loss=3.685]

process_architecture/process:   0%|          | 10/2000 [00:00<00:23, 86.47it/s, test=5.2%, test_loss=3.025, train=7.3%, train_loss=3.021]

process_architecture/process:   1%|          | 20/2000 [00:00<00:21, 91.83it/s, test=5.2%, test_loss=3.025, train=7.3%, train_loss=3.021]

process_architecture/process:   1%|          | 20/2000 [00:00<00:21, 91.83it/s, test=6.4%, test_loss=2.804, train=5.0%, train_loss=2.810]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:21, 93.41it/s, test=6.4%, test_loss=2.804, train=5.0%, train_loss=2.810]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:21, 93.41it/s, test=6.3%, test_loss=2.603, train=5.0%, train_loss=2.648]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:17, 111.75it/s, test=6.3%, test_loss=2.603, train=5.0%, train_loss=2.648]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:13, 140.94it/s, test=6.3%, test_loss=2.603, train=5.0%, train_loss=2.648]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:13, 140.94it/s, test=9.8%, test_loss=2.376, train=7.0%, train_loss=2.413]

process_architecture/process:   4%|▍         | 86/2000 [00:00<00:14, 132.17it/s, test=9.8%, test_loss=2.376, train=7.0%, train_loss=2.413]

process_architecture/process:   4%|▍         | 86/2000 [00:00<00:14, 132.17it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   5%|▌         | 100/2000 [00:00<00:15, 126.42it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   6%|▌         | 121/2000 [00:00<00:12, 148.79it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 165.01it/s, test=12.0%, test_loss=2.193, train=7.3%, train_loss=2.225]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 165.01it/s, test=13.3%, test_loss=1.988, train=10.7%, train_loss=2.019]

process_architecture/process:   8%|▊         | 159/2000 [00:01<00:12, 150.43it/s, test=13.3%, test_loss=1.988, train=10.7%, train_loss=2.019]

process_architecture/process:   9%|▉         | 179/2000 [00:01<00:11, 163.53it/s, test=13.3%, test_loss=1.988, train=10.7%, train_loss=2.019]

process_architecture/process:   9%|▉         | 179/2000 [00:01<00:11, 163.53it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  10%|█         | 200/2000 [00:01<00:11, 152.37it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  11%|█         | 221/2000 [00:01<00:10, 165.53it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  12%|█▏        | 242/2000 [00:01<00:09, 175.81it/s, test=16.6%, test_loss=1.135, train=18.0%, train_loss=1.126]

process_architecture/process:  12%|█▏        | 242/2000 [00:01<00:09, 175.81it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  13%|█▎        | 261/2000 [00:01<00:10, 158.73it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  14%|█▍        | 280/2000 [00:01<00:10, 165.15it/s, test=38.5%, test_loss=0.219, train=41.7%, train_loss=0.218]

process_architecture/process:  14%|█▍        | 280/2000 [00:02<00:10, 165.15it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  15%|█▌        | 300/2000 [00:02<00:11, 153.87it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  16%|█▌        | 321/2000 [00:02<00:10, 166.06it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  17%|█▋        | 341/2000 [00:02<00:09, 173.14it/s, test=63.7%, test_loss=0.097, train=62.3%, train_loss=0.107]

process_architecture/process:  17%|█▋        | 341/2000 [00:02<00:09, 173.14it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  18%|█▊        | 359/2000 [00:02<00:10, 157.06it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  19%|█▉        | 380/2000 [00:02<00:09, 169.75it/s, test=85.4%, test_loss=0.041, train=79.7%, train_loss=0.060]

process_architecture/process:  19%|█▉        | 380/2000 [00:02<00:09, 169.75it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  20%|██        | 400/2000 [00:02<00:10, 156.87it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  21%|██        | 421/2000 [00:02<00:09, 169.15it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  22%|██▏       | 442/2000 [00:02<00:08, 178.99it/s, test=95.9%, test_loss=0.016, train=95.3%, train_loss=0.016]

process_architecture/process:  22%|██▏       | 442/2000 [00:02<00:08, 178.99it/s, test=99.8%, test_loss=0.005, train=100.0%, train_loss=0.005]

process_architecture/process:  23%|██▎       | 461/2000 [00:02<00:09, 162.25it/s, test=99.8%, test_loss=0.005, train=100.0%, train_loss=0.005]

process_architecture/process:  24%|██▍       | 482/2000 [00:03<00:08, 173.72it/s, test=99.8%, test_loss=0.005, train=100.0%, train_loss=0.005]

process_architecture/process:  24%|██▍       | 482/2000 [00:03<00:08, 173.72it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  25%|██▌       | 500/2000 [00:03<00:09, 157.72it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  26%|██▌       | 521/2000 [00:03<00:08, 170.00it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 542/2000 [00:03<00:08, 179.41it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 542/2000 [00:03<00:08, 179.41it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  28%|██▊       | 561/2000 [00:03<00:09, 152.76it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 580/2000 [00:03<00:08, 161.17it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 580/2000 [00:03<00:08, 161.17it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|███       | 600/2000 [00:03<00:09, 150.25it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  31%|███       | 621/2000 [00:03<00:08, 163.15it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 639/2000 [00:04<00:08, 166.12it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 639/2000 [00:04<00:08, 166.12it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  33%|███▎      | 657/2000 [00:04<00:08, 150.04it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 677/2000 [00:04<00:08, 161.42it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  35%|███▍      | 697/2000 [00:04<00:07, 170.54it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  35%|███▍      | 697/2000 [00:04<00:07, 170.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 715/2000 [00:04<00:08, 152.21it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 736/2000 [00:04<00:07, 164.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 736/2000 [00:04<00:07, 164.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 754/2000 [00:04<00:08, 148.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▊      | 774/2000 [00:04<00:07, 161.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 794/2000 [00:05<00:07, 171.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 794/2000 [00:05<00:07, 171.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 812/2000 [00:05<00:07, 152.66it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 832/2000 [00:05<00:07, 164.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 832/2000 [00:05<00:07, 164.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▎     | 850/2000 [00:05<00:07, 151.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▎     | 870/2000 [00:05<00:06, 163.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 891/2000 [00:05<00:06, 173.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 891/2000 [00:05<00:06, 173.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 909/2000 [00:05<00:06, 156.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 930/2000 [00:05<00:06, 168.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 930/2000 [00:06<00:06, 168.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 950/2000 [00:06<00:06, 154.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 970/2000 [00:06<00:06, 165.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|████▉     | 991/2000 [00:06<00:05, 175.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|████▉     | 991/2000 [00:06<00:05, 175.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1010/2000 [00:06<00:06, 158.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1031/2000 [00:06<00:05, 169.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1031/2000 [00:06<00:05, 169.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▎    | 1050/2000 [00:06<00:06, 155.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▎    | 1071/2000 [00:06<00:05, 167.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▍    | 1092/2000 [00:06<00:05, 176.02it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▍    | 1092/2000 [00:06<00:05, 176.02it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1111/2000 [00:07<00:05, 158.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1132/2000 [00:07<00:05, 169.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1132/2000 [00:07<00:05, 169.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▊    | 1150/2000 [00:07<00:05, 154.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▊    | 1171/2000 [00:07<00:04, 166.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1191/2000 [00:07<00:04, 174.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1191/2000 [00:07<00:04, 174.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1210/2000 [00:07<00:05, 157.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1231/2000 [00:07<00:04, 169.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1231/2000 [00:07<00:04, 169.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▎   | 1250/2000 [00:07<00:04, 154.19it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▎   | 1270/2000 [00:07<00:04, 165.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1290/2000 [00:08<00:04, 174.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1290/2000 [00:08<00:04, 174.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▌   | 1309/2000 [00:08<00:04, 156.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▋   | 1330/2000 [00:08<00:03, 168.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▋   | 1330/2000 [00:08<00:03, 168.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1350/2000 [00:08<00:04, 154.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1370/2000 [00:08<00:03, 165.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|██████▉   | 1390/2000 [00:08<00:03, 174.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|██████▉   | 1390/2000 [00:08<00:03, 174.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1409/2000 [00:08<00:03, 157.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████▏  | 1429/2000 [00:08<00:03, 168.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1449/2000 [00:09<00:03, 176.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1449/2000 [00:09<00:03, 176.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1468/2000 [00:09<00:03, 158.82it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1489/2000 [00:09<00:03, 170.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1489/2000 [00:09<00:03, 170.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1507/2000 [00:09<00:03, 154.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1524/2000 [00:09<00:03, 154.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1540/2000 [00:09<00:03, 146.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1540/2000 [00:09<00:03, 146.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1555/2000 [00:09<00:03, 134.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▊  | 1574/2000 [00:09<00:02, 146.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1593/2000 [00:10<00:02, 155.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1593/2000 [00:10<00:02, 155.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1609/2000 [00:10<00:02, 140.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████▏ | 1628/2000 [00:10<00:02, 152.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1647/2000 [00:10<00:02, 161.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1647/2000 [00:10<00:02, 161.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1664/2000 [00:10<00:02, 135.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1680/2000 [00:10<00:02, 140.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1698/2000 [00:10<00:02, 148.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1698/2000 [00:10<00:02, 148.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1714/2000 [00:10<00:02, 132.66it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1731/2000 [00:10<00:01, 140.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1749/2000 [00:11<00:01, 149.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1749/2000 [00:11<00:01, 149.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1765/2000 [00:11<00:01, 132.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1783/2000 [00:11<00:01, 143.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1783/2000 [00:11<00:01, 143.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|█████████ | 1800/2000 [00:11<00:01, 118.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1819/2000 [00:11<00:01, 134.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1838/2000 [00:11<00:01, 147.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1838/2000 [00:11<00:01, 147.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1854/2000 [00:11<00:01, 137.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▎| 1873/2000 [00:12<00:00, 149.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1893/2000 [00:12<00:00, 161.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1893/2000 [00:12<00:00, 161.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1910/2000 [00:12<00:00, 147.39it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▋| 1930/2000 [00:12<00:00, 160.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▋| 1930/2000 [00:12<00:00, 160.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1950/2000 [00:12<00:00, 143.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1969/2000 [00:12<00:00, 153.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1986/2000 [00:12<00:00, 156.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1986/2000 [00:12<00:00, 156.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 155.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode:  50%|█████     | 2/4 [00:24<00:24, 12.17s/it]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.568, train=0.0%, train_loss=3.567]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=13.683, train=0.0%, train_loss=13.521]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:50, 39.52it/s, test=0.0%, test_loss=13.683, train=0.0%, train_loss=13.521]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:50, 39.52it/s, test=0.0%, test_loss=3.547, train=0.0%, train_loss=3.546]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:50, 39.52it/s, test=0.0%, test_loss=1.457, train=0.0%, train_loss=1.457]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:43, 45.37it/s, test=0.0%, test_loss=1.457, train=0.0%, train_loss=1.457]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:43, 45.37it/s, test=6.5%, test_loss=0.963, train=5.0%, train_loss=0.999]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:34, 57.27it/s, test=6.5%, test_loss=0.963, train=5.0%, train_loss=0.999]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:34, 57.27it/s, test=6.6%, test_loss=0.935, train=6.7%, train_loss=0.934]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:32, 60.54it/s, test=6.6%, test_loss=0.935, train=6.7%, train_loss=0.934]

outcome_architecture/outcome:   2%|▏         | 38/2000 [00:00<00:26, 73.61it/s, test=6.6%, test_loss=0.935, train=6.7%, train_loss=0.934]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:25, 77.12it/s, test=6.6%, test_loss=0.935, train=6.7%, train_loss=0.934]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:25, 77.12it/s, test=6.3%, test_loss=0.943, train=4.3%, train_loss=0.955]

outcome_architecture/outcome:   3%|▎         | 55/2000 [00:00<00:25, 74.99it/s, test=6.3%, test_loss=0.943, train=4.3%, train_loss=0.955]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:00<00:22, 84.12it/s, test=6.3%, test_loss=0.943, train=4.3%, train_loss=0.955]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:01<00:22, 84.12it/s, test=8.3%, test_loss=0.919, train=6.7%, train_loss=0.957]

outcome_architecture/outcome:   4%|▍         | 75/2000 [00:01<00:23, 80.53it/s, test=8.3%, test_loss=0.919, train=6.7%, train_loss=0.957]

outcome_architecture/outcome:   4%|▍         | 86/2000 [00:01<00:22, 86.78it/s, test=8.3%, test_loss=0.919, train=6.7%, train_loss=0.957]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:22, 84.48it/s, test=8.3%, test_loss=0.919, train=6.7%, train_loss=0.957]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:22, 84.48it/s, test=10.8%, test_loss=0.901, train=8.3%, train_loss=0.916]

outcome_architecture/outcome:   5%|▌         | 104/2000 [00:01<00:24, 78.31it/s, test=10.8%, test_loss=0.901, train=8.3%, train_loss=0.916]

outcome_architecture/outcome:   6%|▌         | 115/2000 [00:01<00:22, 84.43it/s, test=10.8%, test_loss=0.901, train=8.3%, train_loss=0.916]

outcome_architecture/outcome:   6%|▌         | 124/2000 [00:01<00:22, 82.86it/s, test=10.8%, test_loss=0.901, train=8.3%, train_loss=0.916]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:26, 71.61it/s, test=10.8%, test_loss=0.901, train=8.3%, train_loss=0.916]

outcome_architecture/outcome:   7%|▋         | 141/2000 [00:01<00:25, 72.10it/s, test=10.8%, test_loss=0.901, train=8.3%, train_loss=0.916]

outcome_architecture/outcome:   7%|▋         | 141/2000 [00:02<00:25, 72.10it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:   8%|▊         | 150/2000 [00:02<00:25, 71.37it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:   8%|▊         | 160/2000 [00:02<00:23, 77.91it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:   8%|▊         | 170/2000 [00:02<00:22, 82.94it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:   9%|▉         | 179/2000 [00:02<00:23, 78.73it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:   9%|▉         | 189/2000 [00:02<00:21, 83.74it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:20, 87.46it/s, test=11.9%, test_loss=0.905, train=11.7%, train_loss=0.905]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:20, 87.46it/s, test=13.0%, test_loss=0.888, train=13.3%, train_loss=0.907]

outcome_architecture/outcome:  10%|█         | 208/2000 [00:02<00:24, 73.74it/s, test=13.0%, test_loss=0.888, train=13.3%, train_loss=0.907]

outcome_architecture/outcome:  11%|█         | 218/2000 [00:02<00:22, 79.50it/s, test=13.0%, test_loss=0.888, train=13.3%, train_loss=0.907]

outcome_architecture/outcome:  11%|█▏        | 227/2000 [00:02<00:21, 81.97it/s, test=13.0%, test_loss=0.888, train=13.3%, train_loss=0.907]

outcome_architecture/outcome:  12%|█▏        | 237/2000 [00:03<00:20, 85.30it/s, test=13.0%, test_loss=0.888, train=13.3%, train_loss=0.907]

outcome_architecture/outcome:  12%|█▏        | 246/2000 [00:03<00:20, 84.84it/s, test=13.0%, test_loss=0.888, train=13.3%, train_loss=0.907]

outcome_architecture/outcome:  12%|█▏        | 246/2000 [00:03<00:20, 84.84it/s, test=0.0%, test_loss=441.873, train=0.0%, train_loss=431.991]

outcome_architecture/outcome:  13%|█▎        | 255/2000 [00:03<00:25, 69.52it/s, test=0.0%, test_loss=441.873, train=0.0%, train_loss=431.991]

outcome_architecture/outcome:  13%|█▎        | 265/2000 [00:03<00:22, 76.25it/s, test=0.0%, test_loss=441.873, train=0.0%, train_loss=431.991]

outcome_architecture/outcome:  14%|█▍        | 276/2000 [00:03<00:20, 83.09it/s, test=0.0%, test_loss=441.873, train=0.0%, train_loss=431.991]

outcome_architecture/outcome:  14%|█▍        | 285/2000 [00:03<00:22, 75.66it/s, test=0.0%, test_loss=441.873, train=0.0%, train_loss=431.991]

outcome_architecture/outcome:  15%|█▍        | 296/2000 [00:03<00:20, 83.24it/s, test=0.0%, test_loss=441.873, train=0.0%, train_loss=431.991]

outcome_architecture/outcome:  15%|█▍        | 296/2000 [00:03<00:20, 83.24it/s, test=0.0%, test_loss=54.875, train=0.0%, train_loss=64.516]

outcome_architecture/outcome:  15%|█▌        | 305/2000 [00:03<00:21, 79.93it/s, test=0.0%, test_loss=54.875, train=0.0%, train_loss=64.516]

outcome_architecture/outcome:  16%|█▌        | 316/2000 [00:04<00:19, 86.42it/s, test=0.0%, test_loss=54.875, train=0.0%, train_loss=64.516]

outcome_architecture/outcome:  16%|█▋        | 327/2000 [00:04<00:18, 91.17it/s, test=0.0%, test_loss=54.875, train=0.0%, train_loss=64.516]

outcome_architecture/outcome:  17%|█▋        | 337/2000 [00:04<00:18, 92.15it/s, test=0.0%, test_loss=54.875, train=0.0%, train_loss=64.516]

outcome_architecture/outcome:  17%|█▋        | 347/2000 [00:04<00:20, 80.43it/s, test=0.0%, test_loss=54.875, train=0.0%, train_loss=64.516]

outcome_architecture/outcome:  17%|█▋        | 347/2000 [00:04<00:20, 80.43it/s, test=1.3%, test_loss=3.140, train=2.3%, train_loss=2.522]

outcome_architecture/outcome:  18%|█▊        | 356/2000 [00:04<00:21, 77.13it/s, test=1.3%, test_loss=3.140, train=2.3%, train_loss=2.522]

outcome_architecture/outcome:  18%|█▊        | 367/2000 [00:04<00:19, 84.15it/s, test=1.3%, test_loss=3.140, train=2.3%, train_loss=2.522]

outcome_architecture/outcome:  19%|█▉        | 378/2000 [00:04<00:18, 89.62it/s, test=1.3%, test_loss=3.140, train=2.3%, train_loss=2.522]

outcome_architecture/outcome:  19%|█▉        | 389/2000 [00:04<00:17, 93.68it/s, test=1.3%, test_loss=3.140, train=2.3%, train_loss=2.522]

outcome_architecture/outcome:  20%|█▉        | 399/2000 [00:04<00:17, 92.29it/s, test=1.3%, test_loss=3.140, train=2.3%, train_loss=2.522]

outcome_architecture/outcome:  20%|█▉        | 399/2000 [00:05<00:17, 92.29it/s, test=1.0%, test_loss=1.781, train=4.3%, train_loss=1.666]

outcome_architecture/outcome:  20%|██        | 409/2000 [00:05<00:19, 82.64it/s, test=1.0%, test_loss=1.781, train=4.3%, train_loss=1.666]

outcome_architecture/outcome:  21%|██        | 419/2000 [00:05<00:18, 85.46it/s, test=1.0%, test_loss=1.781, train=4.3%, train_loss=1.666]

outcome_architecture/outcome:  21%|██▏       | 428/2000 [00:05<00:18, 83.44it/s, test=1.0%, test_loss=1.781, train=4.3%, train_loss=1.666]

outcome_architecture/outcome:  22%|██▏       | 438/2000 [00:05<00:18, 86.33it/s, test=1.0%, test_loss=1.781, train=4.3%, train_loss=1.666]

outcome_architecture/outcome:  22%|██▏       | 448/2000 [00:05<00:17, 89.06it/s, test=1.0%, test_loss=1.781, train=4.3%, train_loss=1.666]

outcome_architecture/outcome:  22%|██▏       | 448/2000 [00:05<00:17, 89.06it/s, test=2.7%, test_loss=1.388, train=5.0%, train_loss=1.394]

outcome_architecture/outcome:  23%|██▎       | 458/2000 [00:05<00:18, 82.93it/s, test=2.7%, test_loss=1.388, train=5.0%, train_loss=1.394]

outcome_architecture/outcome:  23%|██▎       | 468/2000 [00:05<00:17, 86.62it/s, test=2.7%, test_loss=1.388, train=5.0%, train_loss=1.394]

outcome_architecture/outcome:  24%|██▍       | 478/2000 [00:05<00:17, 88.92it/s, test=2.7%, test_loss=1.388, train=5.0%, train_loss=1.394]

outcome_architecture/outcome:  24%|██▍       | 488/2000 [00:06<00:16, 91.09it/s, test=2.7%, test_loss=1.388, train=5.0%, train_loss=1.394]

outcome_architecture/outcome:  25%|██▍       | 499/2000 [00:06<00:15, 94.40it/s, test=2.7%, test_loss=1.388, train=5.0%, train_loss=1.394]

outcome_architecture/outcome:  25%|██▍       | 499/2000 [00:06<00:15, 94.40it/s, test=6.2%, test_loss=1.227, train=7.3%, train_loss=1.198]

outcome_architecture/outcome:  25%|██▌       | 509/2000 [00:06<00:17, 86.39it/s, test=6.2%, test_loss=1.227, train=7.3%, train_loss=1.198]

outcome_architecture/outcome:  26%|██▌       | 519/2000 [00:06<00:16, 88.29it/s, test=6.2%, test_loss=1.227, train=7.3%, train_loss=1.198]

outcome_architecture/outcome:  26%|██▋       | 529/2000 [00:06<00:16, 90.22it/s, test=6.2%, test_loss=1.227, train=7.3%, train_loss=1.198]

outcome_architecture/outcome:  27%|██▋       | 539/2000 [00:06<00:16, 90.09it/s, test=6.2%, test_loss=1.227, train=7.3%, train_loss=1.198]

outcome_architecture/outcome:  27%|██▋       | 549/2000 [00:06<00:15, 91.04it/s, test=6.2%, test_loss=1.227, train=7.3%, train_loss=1.198]

outcome_architecture/outcome:  27%|██▋       | 549/2000 [00:06<00:15, 91.04it/s, test=4.2%, test_loss=1.337, train=6.0%, train_loss=1.259]

outcome_architecture/outcome:  28%|██▊       | 559/2000 [00:06<00:17, 83.85it/s, test=4.2%, test_loss=1.337, train=6.0%, train_loss=1.259]

outcome_architecture/outcome:  28%|██▊       | 568/2000 [00:06<00:16, 84.87it/s, test=4.2%, test_loss=1.337, train=6.0%, train_loss=1.259]

outcome_architecture/outcome:  29%|██▉       | 578/2000 [00:07<00:16, 87.58it/s, test=4.2%, test_loss=1.337, train=6.0%, train_loss=1.259]

outcome_architecture/outcome:  29%|██▉       | 588/2000 [00:07<00:15, 89.81it/s, test=4.2%, test_loss=1.337, train=6.0%, train_loss=1.259]

outcome_architecture/outcome:  30%|██▉       | 598/2000 [00:07<00:15, 89.81it/s, test=4.2%, test_loss=1.337, train=6.0%, train_loss=1.259]

outcome_architecture/outcome:  30%|██▉       | 598/2000 [00:07<00:15, 89.81it/s, test=5.8%, test_loss=1.144, train=5.7%, train_loss=1.210]

outcome_architecture/outcome:  30%|███       | 608/2000 [00:07<00:17, 81.77it/s, test=5.8%, test_loss=1.144, train=5.7%, train_loss=1.210]

outcome_architecture/outcome:  31%|███       | 618/2000 [00:07<00:16, 84.80it/s, test=5.8%, test_loss=1.144, train=5.7%, train_loss=1.210]

outcome_architecture/outcome:  31%|███▏      | 628/2000 [00:07<00:15, 86.99it/s, test=5.8%, test_loss=1.144, train=5.7%, train_loss=1.210]

outcome_architecture/outcome:  32%|███▏      | 638/2000 [00:07<00:15, 89.39it/s, test=5.8%, test_loss=1.144, train=5.7%, train_loss=1.210]

outcome_architecture/outcome:  32%|███▏      | 648/2000 [00:07<00:14, 90.53it/s, test=5.8%, test_loss=1.144, train=5.7%, train_loss=1.210]

outcome_architecture/outcome:  32%|███▏      | 648/2000 [00:07<00:14, 90.53it/s, test=6.9%, test_loss=1.084, train=6.0%, train_loss=1.099]

outcome_architecture/outcome:  33%|███▎      | 658/2000 [00:07<00:16, 81.75it/s, test=6.9%, test_loss=1.084, train=6.0%, train_loss=1.099]

outcome_architecture/outcome:  33%|███▎      | 668/2000 [00:08<00:15, 84.47it/s, test=6.9%, test_loss=1.084, train=6.0%, train_loss=1.099]

outcome_architecture/outcome:  34%|███▍      | 678/2000 [00:08<00:15, 87.72it/s, test=6.9%, test_loss=1.084, train=6.0%, train_loss=1.099]

outcome_architecture/outcome:  34%|███▍      | 688/2000 [00:08<00:14, 90.33it/s, test=6.9%, test_loss=1.084, train=6.0%, train_loss=1.099]

outcome_architecture/outcome:  35%|███▍      | 698/2000 [00:08<00:14, 91.98it/s, test=6.9%, test_loss=1.084, train=6.0%, train_loss=1.099]

outcome_architecture/outcome:  35%|███▍      | 698/2000 [00:08<00:14, 91.98it/s, test=6.0%, test_loss=1.051, train=7.3%, train_loss=1.060]

outcome_architecture/outcome:  35%|███▌      | 708/2000 [00:08<00:15, 84.19it/s, test=6.0%, test_loss=1.051, train=7.3%, train_loss=1.060]

outcome_architecture/outcome:  36%|███▌      | 718/2000 [00:08<00:14, 87.71it/s, test=6.0%, test_loss=1.051, train=7.3%, train_loss=1.060]

outcome_architecture/outcome:  36%|███▋      | 728/2000 [00:08<00:14, 90.06it/s, test=6.0%, test_loss=1.051, train=7.3%, train_loss=1.060]

outcome_architecture/outcome:  37%|███▋      | 738/2000 [00:08<00:13, 91.00it/s, test=6.0%, test_loss=1.051, train=7.3%, train_loss=1.060]

outcome_architecture/outcome:  37%|███▋      | 748/2000 [00:08<00:13, 92.50it/s, test=6.0%, test_loss=1.051, train=7.3%, train_loss=1.060]

outcome_architecture/outcome:  37%|███▋      | 748/2000 [00:09<00:13, 92.50it/s, test=7.0%, test_loss=0.957, train=8.0%, train_loss=0.997]

outcome_architecture/outcome:  38%|███▊      | 758/2000 [00:09<00:14, 84.67it/s, test=7.0%, test_loss=0.957, train=8.0%, train_loss=0.997]

outcome_architecture/outcome:  38%|███▊      | 768/2000 [00:09<00:14, 87.77it/s, test=7.0%, test_loss=0.957, train=8.0%, train_loss=0.997]

outcome_architecture/outcome:  39%|███▉      | 777/2000 [00:09<00:13, 87.86it/s, test=7.0%, test_loss=0.957, train=8.0%, train_loss=0.997]

outcome_architecture/outcome:  39%|███▉      | 787/2000 [00:09<00:13, 90.22it/s, test=7.0%, test_loss=0.957, train=8.0%, train_loss=0.997]

outcome_architecture/outcome:  40%|███▉      | 798/2000 [00:09<00:12, 93.85it/s, test=7.0%, test_loss=0.957, train=8.0%, train_loss=0.997]

outcome_architecture/outcome:  40%|███▉      | 798/2000 [00:09<00:12, 93.85it/s, test=8.4%, test_loss=1.021, train=9.3%, train_loss=1.024]

outcome_architecture/outcome:  40%|████      | 808/2000 [00:09<00:13, 86.71it/s, test=8.4%, test_loss=1.021, train=9.3%, train_loss=1.024]

outcome_architecture/outcome:  41%|████      | 818/2000 [00:09<00:13, 88.87it/s, test=8.4%, test_loss=1.021, train=9.3%, train_loss=1.024]

outcome_architecture/outcome:  41%|████▏     | 828/2000 [00:09<00:12, 90.88it/s, test=8.4%, test_loss=1.021, train=9.3%, train_loss=1.024]

outcome_architecture/outcome:  42%|████▏     | 838/2000 [00:09<00:12, 91.62it/s, test=8.4%, test_loss=1.021, train=9.3%, train_loss=1.024]

outcome_architecture/outcome:  42%|████▏     | 849/2000 [00:10<00:12, 95.07it/s, test=8.4%, test_loss=1.021, train=9.3%, train_loss=1.024]

outcome_architecture/outcome:  42%|████▏     | 849/2000 [00:10<00:12, 95.07it/s, test=7.9%, test_loss=0.995, train=9.0%, train_loss=1.007]

outcome_architecture/outcome:  43%|████▎     | 859/2000 [00:10<00:13, 87.45it/s, test=7.9%, test_loss=0.995, train=9.0%, train_loss=1.007]

outcome_architecture/outcome:  43%|████▎     | 869/2000 [00:10<00:12, 90.75it/s, test=7.9%, test_loss=0.995, train=9.0%, train_loss=1.007]

outcome_architecture/outcome:  44%|████▍     | 879/2000 [00:10<00:12, 92.91it/s, test=7.9%, test_loss=0.995, train=9.0%, train_loss=1.007]

outcome_architecture/outcome:  44%|████▍     | 889/2000 [00:10<00:11, 94.02it/s, test=7.9%, test_loss=0.995, train=9.0%, train_loss=1.007]

outcome_architecture/outcome:  44%|████▍     | 889/2000 [00:10<00:11, 94.02it/s, test=6.3%, test_loss=0.972, train=7.7%, train_loss=0.989]

outcome_architecture/outcome:  45%|████▌     | 900/2000 [00:10<00:12, 87.65it/s, test=6.3%, test_loss=0.972, train=7.7%, train_loss=0.989]

outcome_architecture/outcome:  46%|████▌     | 910/2000 [00:10<00:12, 89.89it/s, test=6.3%, test_loss=0.972, train=7.7%, train_loss=0.989]

outcome_architecture/outcome:  46%|████▌     | 920/2000 [00:10<00:11, 90.60it/s, test=6.3%, test_loss=0.972, train=7.7%, train_loss=0.989]

outcome_architecture/outcome:  46%|████▋     | 930/2000 [00:10<00:12, 88.77it/s, test=6.3%, test_loss=0.972, train=7.7%, train_loss=0.989]

outcome_architecture/outcome:  47%|████▋     | 940/2000 [00:11<00:11, 90.38it/s, test=6.3%, test_loss=0.972, train=7.7%, train_loss=0.989]

outcome_architecture/outcome:  47%|████▋     | 940/2000 [00:11<00:11, 90.38it/s, test=7.7%, test_loss=0.955, train=7.3%, train_loss=0.990]

outcome_architecture/outcome:  48%|████▊     | 950/2000 [00:11<00:12, 83.92it/s, test=7.7%, test_loss=0.955, train=7.3%, train_loss=0.990]

outcome_architecture/outcome:  48%|████▊     | 960/2000 [00:11<00:11, 87.39it/s, test=7.7%, test_loss=0.955, train=7.3%, train_loss=0.990]

outcome_architecture/outcome:  48%|████▊     | 970/2000 [00:11<00:11, 89.98it/s, test=7.7%, test_loss=0.955, train=7.3%, train_loss=0.990]

outcome_architecture/outcome:  49%|████▉     | 980/2000 [00:11<00:11, 92.10it/s, test=7.7%, test_loss=0.955, train=7.3%, train_loss=0.990]

outcome_architecture/outcome:  50%|████▉     | 990/2000 [00:11<00:11, 91.38it/s, test=7.7%, test_loss=0.955, train=7.3%, train_loss=0.990]

outcome_architecture/outcome:  50%|████▉     | 990/2000 [00:11<00:11, 91.38it/s, test=6.6%, test_loss=0.987, train=9.0%, train_loss=0.978]

outcome_architecture/outcome:  50%|█████     | 1000/2000 [00:11<00:11, 85.64it/s, test=6.6%, test_loss=0.987, train=9.0%, train_loss=0.978]

outcome_architecture/outcome:  50%|█████     | 1010/2000 [00:11<00:11, 89.39it/s, test=6.6%, test_loss=0.987, train=9.0%, train_loss=0.978]

outcome_architecture/outcome:  51%|█████     | 1020/2000 [00:11<00:10, 91.44it/s, test=6.6%, test_loss=0.987, train=9.0%, train_loss=0.978]

outcome_architecture/outcome:  52%|█████▏    | 1030/2000 [00:12<00:10, 92.28it/s, test=6.6%, test_loss=0.987, train=9.0%, train_loss=0.978]

outcome_architecture/outcome:  52%|█████▏    | 1040/2000 [00:12<00:10, 91.13it/s, test=6.6%, test_loss=0.987, train=9.0%, train_loss=0.978]

outcome_architecture/outcome:  52%|█████▏    | 1040/2000 [00:12<00:10, 91.13it/s, test=6.4%, test_loss=0.990, train=5.7%, train_loss=1.029]

outcome_architecture/outcome:  52%|█████▎    | 1050/2000 [00:12<00:11, 82.24it/s, test=6.4%, test_loss=0.990, train=5.7%, train_loss=1.029]

outcome_architecture/outcome:  53%|█████▎    | 1060/2000 [00:12<00:11, 85.06it/s, test=6.4%, test_loss=0.990, train=5.7%, train_loss=1.029]

outcome_architecture/outcome:  54%|█████▎    | 1071/2000 [00:12<00:10, 89.82it/s, test=6.4%, test_loss=0.990, train=5.7%, train_loss=1.029]

outcome_architecture/outcome:  54%|█████▍    | 1082/2000 [00:12<00:09, 93.69it/s, test=6.4%, test_loss=0.990, train=5.7%, train_loss=1.029]

outcome_architecture/outcome:  55%|█████▍    | 1093/2000 [00:12<00:09, 96.53it/s, test=6.4%, test_loss=0.990, train=5.7%, train_loss=1.029]

outcome_architecture/outcome:  55%|█████▍    | 1093/2000 [00:12<00:09, 96.53it/s, test=9.3%, test_loss=1.006, train=8.3%, train_loss=1.003]

outcome_architecture/outcome:  55%|█████▌    | 1103/2000 [00:12<00:10, 87.62it/s, test=9.3%, test_loss=1.006, train=8.3%, train_loss=1.003]

outcome_architecture/outcome:  56%|█████▌    | 1114/2000 [00:13<00:09, 91.80it/s, test=9.3%, test_loss=1.006, train=8.3%, train_loss=1.003]

outcome_architecture/outcome:  56%|█████▋    | 1125/2000 [00:13<00:09, 95.04it/s, test=9.3%, test_loss=1.006, train=8.3%, train_loss=1.003]

outcome_architecture/outcome:  57%|█████▋    | 1136/2000 [00:13<00:08, 97.37it/s, test=9.3%, test_loss=1.006, train=8.3%, train_loss=1.003]

outcome_architecture/outcome:  57%|█████▋    | 1147/2000 [00:13<00:08, 99.23it/s, test=9.3%, test_loss=1.006, train=8.3%, train_loss=1.003]

outcome_architecture/outcome:  57%|█████▋    | 1147/2000 [00:13<00:08, 99.23it/s, test=7.8%, test_loss=0.979, train=7.3%, train_loss=0.955]

outcome_architecture/outcome:  58%|█████▊    | 1158/2000 [00:13<00:09, 88.51it/s, test=7.8%, test_loss=0.979, train=7.3%, train_loss=0.955]

outcome_architecture/outcome:  58%|█████▊    | 1168/2000 [00:13<00:09, 91.20it/s, test=7.8%, test_loss=0.979, train=7.3%, train_loss=0.955]

outcome_architecture/outcome:  59%|█████▉    | 1179/2000 [00:13<00:08, 94.59it/s, test=7.8%, test_loss=0.979, train=7.3%, train_loss=0.955]

outcome_architecture/outcome:  60%|█████▉    | 1190/2000 [00:13<00:08, 96.67it/s, test=7.8%, test_loss=0.979, train=7.3%, train_loss=0.955]

outcome_architecture/outcome:  60%|█████▉    | 1190/2000 [00:13<00:08, 96.67it/s, test=8.0%, test_loss=0.991, train=7.7%, train_loss=0.995]

outcome_architecture/outcome:  60%|██████    | 1200/2000 [00:13<00:08, 89.07it/s, test=8.0%, test_loss=0.991, train=7.7%, train_loss=0.995]

outcome_architecture/outcome:  61%|██████    | 1211/2000 [00:14<00:08, 93.10it/s, test=8.0%, test_loss=0.991, train=7.7%, train_loss=0.995]

outcome_architecture/outcome:  61%|██████    | 1221/2000 [00:14<00:08, 91.88it/s, test=8.0%, test_loss=0.991, train=7.7%, train_loss=0.995]

outcome_architecture/outcome:  62%|██████▏   | 1232/2000 [00:14<00:08, 95.03it/s, test=8.0%, test_loss=0.991, train=7.7%, train_loss=0.995]

outcome_architecture/outcome:  62%|██████▏   | 1243/2000 [00:14<00:07, 97.59it/s, test=8.0%, test_loss=0.991, train=7.7%, train_loss=0.995]

outcome_architecture/outcome:  62%|██████▏   | 1243/2000 [00:14<00:07, 97.59it/s, test=8.9%, test_loss=0.972, train=9.3%, train_loss=0.964]

outcome_architecture/outcome:  63%|██████▎   | 1253/2000 [00:14<00:08, 89.50it/s, test=8.9%, test_loss=0.972, train=9.3%, train_loss=0.964]

outcome_architecture/outcome:  63%|██████▎   | 1264/2000 [00:14<00:07, 93.46it/s, test=8.9%, test_loss=0.972, train=9.3%, train_loss=0.964]

outcome_architecture/outcome:  64%|██████▍   | 1275/2000 [00:14<00:07, 96.34it/s, test=8.9%, test_loss=0.972, train=9.3%, train_loss=0.964]

outcome_architecture/outcome:  64%|██████▍   | 1285/2000 [00:14<00:07, 93.44it/s, test=8.9%, test_loss=0.972, train=9.3%, train_loss=0.964]

outcome_architecture/outcome:  65%|██████▍   | 1296/2000 [00:14<00:07, 96.18it/s, test=8.9%, test_loss=0.972, train=9.3%, train_loss=0.964]

outcome_architecture/outcome:  65%|██████▍   | 1296/2000 [00:15<00:07, 96.18it/s, test=7.2%, test_loss=0.949, train=8.0%, train_loss=0.948]

outcome_architecture/outcome:  65%|██████▌   | 1306/2000 [00:15<00:07, 88.79it/s, test=7.2%, test_loss=0.949, train=8.0%, train_loss=0.948]

outcome_architecture/outcome:  66%|██████▌   | 1317/2000 [00:15<00:07, 92.91it/s, test=7.2%, test_loss=0.949, train=8.0%, train_loss=0.948]

outcome_architecture/outcome:  66%|██████▋   | 1328/2000 [00:15<00:06, 96.22it/s, test=7.2%, test_loss=0.949, train=8.0%, train_loss=0.948]

outcome_architecture/outcome:  67%|██████▋   | 1338/2000 [00:15<00:06, 95.30it/s, test=7.2%, test_loss=0.949, train=8.0%, train_loss=0.948]

outcome_architecture/outcome:  67%|██████▋   | 1349/2000 [00:15<00:06, 97.87it/s, test=7.2%, test_loss=0.949, train=8.0%, train_loss=0.948]

outcome_architecture/outcome:  67%|██████▋   | 1349/2000 [00:15<00:06, 97.87it/s, test=9.2%, test_loss=0.939, train=11.7%, train_loss=0.936]

outcome_architecture/outcome:  68%|██████▊   | 1359/2000 [00:15<00:07, 90.25it/s, test=9.2%, test_loss=0.939, train=11.7%, train_loss=0.936]

outcome_architecture/outcome:  68%|██████▊   | 1370/2000 [00:15<00:06, 94.37it/s, test=9.2%, test_loss=0.939, train=11.7%, train_loss=0.936]

outcome_architecture/outcome:  69%|██████▉   | 1381/2000 [00:15<00:06, 97.22it/s, test=9.2%, test_loss=0.939, train=11.7%, train_loss=0.936]

outcome_architecture/outcome:  70%|██████▉   | 1392/2000 [00:15<00:06, 99.38it/s, test=9.2%, test_loss=0.939, train=11.7%, train_loss=0.936]

outcome_architecture/outcome:  70%|██████▉   | 1392/2000 [00:16<00:06, 99.38it/s, test=8.8%, test_loss=0.978, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  70%|███████   | 1403/2000 [00:16<00:06, 91.61it/s, test=8.8%, test_loss=0.978, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  71%|███████   | 1414/2000 [00:16<00:06, 95.18it/s, test=8.8%, test_loss=0.978, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  71%|███████▏  | 1425/2000 [00:16<00:05, 97.92it/s, test=8.8%, test_loss=0.978, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  72%|███████▏  | 1436/2000 [00:16<00:05, 99.83it/s, test=8.8%, test_loss=0.978, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  72%|███████▏  | 1447/2000 [00:16<00:05, 101.31it/s, test=8.8%, test_loss=0.978, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  72%|███████▏  | 1447/2000 [00:16<00:05, 101.31it/s, test=7.8%, test_loss=0.973, train=8.3%, train_loss=0.937]

outcome_architecture/outcome:  73%|███████▎  | 1458/2000 [00:16<00:06, 90.04it/s, test=7.8%, test_loss=0.973, train=8.3%, train_loss=0.937]

outcome_architecture/outcome:  73%|███████▎  | 1469/2000 [00:16<00:05, 93.93it/s, test=7.8%, test_loss=0.973, train=8.3%, train_loss=0.937]

outcome_architecture/outcome:  74%|███████▍  | 1480/2000 [00:16<00:05, 95.82it/s, test=7.8%, test_loss=0.973, train=8.3%, train_loss=0.937]

outcome_architecture/outcome:  74%|███████▍  | 1490/2000 [00:17<00:05, 87.69it/s, test=7.8%, test_loss=0.973, train=8.3%, train_loss=0.937]

outcome_architecture/outcome:  75%|███████▍  | 1499/2000 [00:17<00:06, 78.49it/s, test=7.8%, test_loss=0.973, train=8.3%, train_loss=0.937]

outcome_architecture/outcome:  75%|███████▍  | 1499/2000 [00:17<00:06, 78.49it/s, test=8.3%, test_loss=0.971, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  75%|███████▌  | 1508/2000 [00:17<00:07, 65.52it/s, test=8.3%, test_loss=0.971, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  76%|███████▌  | 1517/2000 [00:17<00:06, 70.38it/s, test=8.3%, test_loss=0.971, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  76%|███████▋  | 1528/2000 [00:17<00:06, 78.53it/s, test=8.3%, test_loss=0.971, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  77%|███████▋  | 1539/2000 [00:17<00:05, 85.18it/s, test=8.3%, test_loss=0.971, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  77%|███████▋  | 1539/2000 [00:17<00:05, 85.18it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  78%|███████▊  | 1550/2000 [00:17<00:05, 82.34it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  78%|███████▊  | 1559/2000 [00:17<00:05, 78.70it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  78%|███████▊  | 1568/2000 [00:18<00:05, 77.33it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  79%|███████▉  | 1577/2000 [00:18<00:05, 78.57it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  79%|███████▉  | 1587/2000 [00:18<00:04, 83.85it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  80%|███████▉  | 1598/2000 [00:18<00:04, 89.64it/s, test=9.2%, test_loss=0.959, train=11.0%, train_loss=0.939]

outcome_architecture/outcome:  80%|███████▉  | 1598/2000 [00:18<00:04, 89.64it/s, test=10.7%, test_loss=0.938, train=11.7%, train_loss=0.945]

outcome_architecture/outcome:  80%|████████  | 1608/2000 [00:18<00:04, 83.60it/s, test=10.7%, test_loss=0.938, train=11.7%, train_loss=0.945]

outcome_architecture/outcome:  81%|████████  | 1618/2000 [00:18<00:04, 87.56it/s, test=10.7%, test_loss=0.938, train=11.7%, train_loss=0.945]

outcome_architecture/outcome:  81%|████████▏ | 1628/2000 [00:18<00:04, 90.47it/s, test=10.7%, test_loss=0.938, train=11.7%, train_loss=0.945]

outcome_architecture/outcome:  82%|████████▏ | 1638/2000 [00:18<00:03, 92.30it/s, test=10.7%, test_loss=0.938, train=11.7%, train_loss=0.945]

outcome_architecture/outcome:  82%|████████▏ | 1648/2000 [00:18<00:03, 93.63it/s, test=10.7%, test_loss=0.938, train=11.7%, train_loss=0.945]

outcome_architecture/outcome:  82%|████████▏ | 1648/2000 [00:19<00:03, 93.63it/s, test=9.7%, test_loss=0.955, train=10.3%, train_loss=0.921]

outcome_architecture/outcome:  83%|████████▎ | 1658/2000 [00:19<00:03, 86.10it/s, test=9.7%, test_loss=0.955, train=10.3%, train_loss=0.921]

outcome_architecture/outcome:  83%|████████▎ | 1667/2000 [00:19<00:03, 86.48it/s, test=9.7%, test_loss=0.955, train=10.3%, train_loss=0.921]

outcome_architecture/outcome:  84%|████████▍ | 1677/2000 [00:19<00:03, 88.57it/s, test=9.7%, test_loss=0.955, train=10.3%, train_loss=0.921]

outcome_architecture/outcome:  84%|████████▍ | 1687/2000 [00:19<00:03, 90.73it/s, test=9.7%, test_loss=0.955, train=10.3%, train_loss=0.921]

outcome_architecture/outcome:  85%|████████▍ | 1697/2000 [00:19<00:03, 90.97it/s, test=9.7%, test_loss=0.955, train=10.3%, train_loss=0.921]

outcome_architecture/outcome:  85%|████████▍ | 1697/2000 [00:19<00:03, 90.97it/s, test=8.8%, test_loss=0.934, train=10.0%, train_loss=0.911]

outcome_architecture/outcome:  85%|████████▌ | 1707/2000 [00:19<00:03, 82.75it/s, test=8.8%, test_loss=0.934, train=10.0%, train_loss=0.911]

outcome_architecture/outcome:  86%|████████▌ | 1718/2000 [00:19<00:03, 87.83it/s, test=8.8%, test_loss=0.934, train=10.0%, train_loss=0.911]

outcome_architecture/outcome:  86%|████████▋ | 1729/2000 [00:19<00:02, 91.58it/s, test=8.8%, test_loss=0.934, train=10.0%, train_loss=0.911]

outcome_architecture/outcome:  87%|████████▋ | 1740/2000 [00:19<00:02, 94.19it/s, test=8.8%, test_loss=0.934, train=10.0%, train_loss=0.911]

outcome_architecture/outcome:  87%|████████▋ | 1740/2000 [00:20<00:02, 94.19it/s, test=9.9%, test_loss=0.949, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  88%|████████▊ | 1750/2000 [00:20<00:02, 86.99it/s, test=9.9%, test_loss=0.949, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  88%|████████▊ | 1761/2000 [00:20<00:02, 91.37it/s, test=9.9%, test_loss=0.949, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  89%|████████▊ | 1771/2000 [00:20<00:02, 93.59it/s, test=9.9%, test_loss=0.949, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  89%|████████▉ | 1781/2000 [00:20<00:02, 94.84it/s, test=9.9%, test_loss=0.949, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  90%|████████▉ | 1792/2000 [00:20<00:02, 96.49it/s, test=9.9%, test_loss=0.949, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  90%|████████▉ | 1792/2000 [00:20<00:02, 96.49it/s, test=10.2%, test_loss=0.960, train=8.3%, train_loss=0.942]

outcome_architecture/outcome:  90%|█████████ | 1802/2000 [00:20<00:02, 85.60it/s, test=10.2%, test_loss=0.960, train=8.3%, train_loss=0.942]

outcome_architecture/outcome:  91%|█████████ | 1813/2000 [00:20<00:02, 90.82it/s, test=10.2%, test_loss=0.960, train=8.3%, train_loss=0.942]

outcome_architecture/outcome:  91%|█████████ | 1823/2000 [00:20<00:01, 92.26it/s, test=10.2%, test_loss=0.960, train=8.3%, train_loss=0.942]

outcome_architecture/outcome:  92%|█████████▏| 1833/2000 [00:21<00:01, 93.34it/s, test=10.2%, test_loss=0.960, train=8.3%, train_loss=0.942]

outcome_architecture/outcome:  92%|█████████▏| 1843/2000 [00:21<00:01, 94.58it/s, test=10.2%, test_loss=0.960, train=8.3%, train_loss=0.942]

outcome_architecture/outcome:  92%|█████████▏| 1843/2000 [00:21<00:01, 94.58it/s, test=9.7%, test_loss=0.951, train=10.7%, train_loss=0.949]

outcome_architecture/outcome:  93%|█████████▎| 1853/2000 [00:21<00:01, 86.31it/s, test=9.7%, test_loss=0.951, train=10.7%, train_loss=0.949]

outcome_architecture/outcome:  93%|█████████▎| 1863/2000 [00:21<00:01, 87.98it/s, test=9.7%, test_loss=0.951, train=10.7%, train_loss=0.949]

outcome_architecture/outcome:  94%|█████████▎| 1873/2000 [00:21<00:01, 90.32it/s, test=9.7%, test_loss=0.951, train=10.7%, train_loss=0.949]

outcome_architecture/outcome:  94%|█████████▍| 1883/2000 [00:21<00:01, 92.18it/s, test=9.7%, test_loss=0.951, train=10.7%, train_loss=0.949]

outcome_architecture/outcome:  95%|█████████▍| 1893/2000 [00:21<00:01, 90.16it/s, test=9.7%, test_loss=0.951, train=10.7%, train_loss=0.949]

outcome_architecture/outcome:  95%|█████████▍| 1893/2000 [00:21<00:01, 90.16it/s, test=9.6%, test_loss=0.926, train=11.0%, train_loss=0.918]

outcome_architecture/outcome:  95%|█████████▌| 1903/2000 [00:21<00:01, 76.94it/s, test=9.6%, test_loss=0.926, train=11.0%, train_loss=0.918]

outcome_architecture/outcome:  96%|█████████▌| 1912/2000 [00:21<00:01, 79.83it/s, test=9.6%, test_loss=0.926, train=11.0%, train_loss=0.918]

outcome_architecture/outcome:  96%|█████████▌| 1923/2000 [00:22<00:00, 86.58it/s, test=9.6%, test_loss=0.926, train=11.0%, train_loss=0.918]

outcome_architecture/outcome:  97%|█████████▋| 1934/2000 [00:22<00:00, 91.55it/s, test=9.6%, test_loss=0.926, train=11.0%, train_loss=0.918]

outcome_architecture/outcome:  97%|█████████▋| 1945/2000 [00:22<00:00, 94.99it/s, test=9.6%, test_loss=0.926, train=11.0%, train_loss=0.918]

outcome_architecture/outcome:  97%|█████████▋| 1945/2000 [00:22<00:00, 94.99it/s, test=8.7%, test_loss=0.919, train=7.7%, train_loss=0.919]

outcome_architecture/outcome:  98%|█████████▊| 1955/2000 [00:22<00:00, 87.53it/s, test=8.7%, test_loss=0.919, train=7.7%, train_loss=0.919]

outcome_architecture/outcome:  98%|█████████▊| 1966/2000 [00:22<00:00, 92.13it/s, test=8.7%, test_loss=0.919, train=7.7%, train_loss=0.919]

outcome_architecture/outcome:  99%|█████████▉| 1977/2000 [00:22<00:00, 95.33it/s, test=8.7%, test_loss=0.919, train=7.7%, train_loss=0.919]

outcome_architecture/outcome:  99%|█████████▉| 1988/2000 [00:22<00:00, 98.07it/s, test=8.7%, test_loss=0.919, train=7.7%, train_loss=0.919]

outcome_architecture/outcome: 100%|█████████▉| 1998/2000 [00:22<00:00, 91.64it/s, test=8.7%, test_loss=0.919, train=7.7%, train_loss=0.919]

outcome_architecture/outcome: 100%|█████████▉| 1998/2000 [00:22<00:00, 91.64it/s, test=8.3%, test_loss=1.000, train=8.3%, train_loss=1.007]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:22<00:00, 87.28it/s, test=8.3%, test_loss=1.000, train=8.3%, train_loss=1.007]

architecture/mode:  75%|███████▌  | 3/4 [00:46<00:17, 17.10s/it]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.112, train=0.0%, train_loss=4.113]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=16.870, train=0.0%, train_loss=16.956]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.063, train=0.0%, train_loss=4.066]

outcome_architecture/process:   0%|          | 5/2000 [00:00<01:37, 20.43it/s, test=0.0%, test_loss=4.063, train=0.0%, train_loss=4.066]

outcome_architecture/process:   0%|          | 5/2000 [00:00<01:37, 20.43it/s, test=0.0%, test_loss=3.698, train=0.0%, train_loss=3.725]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:26, 22.93it/s, test=0.0%, test_loss=3.698, train=0.0%, train_loss=3.725]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:26, 22.93it/s, test=0.1%, test_loss=2.864, train=0.0%, train_loss=2.876]

outcome_architecture/process:   1%|          | 20/2000 [00:00<00:58, 33.76it/s, test=0.1%, test_loss=2.864, train=0.0%, train_loss=2.876]

outcome_architecture/process:   1%|          | 20/2000 [00:00<00:58, 33.76it/s, test=7.2%, test_loss=2.790, train=5.3%, train_loss=2.817]

outcome_architecture/process:   1%|▏         | 25/2000 [00:00<01:04, 30.47it/s, test=7.2%, test_loss=2.790, train=5.3%, train_loss=2.817]

outcome_architecture/process:   2%|▏         | 36/2000 [00:00<00:42, 46.66it/s, test=7.2%, test_loss=2.790, train=5.3%, train_loss=2.817]

outcome_architecture/process:   2%|▏         | 47/2000 [00:01<00:32, 60.11it/s, test=7.2%, test_loss=2.790, train=5.3%, train_loss=2.817]

outcome_architecture/process:   2%|▏         | 47/2000 [00:01<00:32, 60.11it/s, test=0.0%, test_loss=55.991, train=0.0%, train_loss=54.198]

outcome_architecture/process:   3%|▎         | 55/2000 [00:01<00:40, 47.89it/s, test=0.0%, test_loss=55.991, train=0.0%, train_loss=54.198]

outcome_architecture/process:   3%|▎         | 66/2000 [00:01<00:32, 59.84it/s, test=0.0%, test_loss=55.991, train=0.0%, train_loss=54.198]

outcome_architecture/process:   3%|▎         | 66/2000 [00:01<00:32, 59.84it/s, test=0.4%, test_loss=4.659, train=1.3%, train_loss=4.527]

outcome_architecture/process:   4%|▍         | 75/2000 [00:01<00:37, 50.96it/s, test=0.4%, test_loss=4.659, train=1.3%, train_loss=4.527]

outcome_architecture/process:   4%|▍         | 84/2000 [00:01<00:33, 57.96it/s, test=0.4%, test_loss=4.659, train=1.3%, train_loss=4.527]

outcome_architecture/process:   5%|▍         | 94/2000 [00:01<00:28, 66.84it/s, test=0.4%, test_loss=4.659, train=1.3%, train_loss=4.527]

outcome_architecture/process:   5%|▍         | 94/2000 [00:02<00:28, 66.84it/s, test=6.1%, test_loss=3.516, train=5.0%, train_loss=3.539]

outcome_architecture/process:   5%|▌         | 102/2000 [00:02<00:35, 53.63it/s, test=6.1%, test_loss=3.516, train=5.0%, train_loss=3.539]

outcome_architecture/process:   6%|▌         | 113/2000 [00:02<00:29, 64.30it/s, test=6.1%, test_loss=3.516, train=5.0%, train_loss=3.539]

outcome_architecture/process:   6%|▌         | 123/2000 [00:02<00:26, 72.14it/s, test=6.1%, test_loss=3.516, train=5.0%, train_loss=3.539]

outcome_architecture/process:   7%|▋         | 132/2000 [00:02<00:24, 76.05it/s, test=6.1%, test_loss=3.516, train=5.0%, train_loss=3.539]

outcome_architecture/process:   7%|▋         | 143/2000 [00:02<00:22, 83.07it/s, test=6.1%, test_loss=3.516, train=5.0%, train_loss=3.539]

outcome_architecture/process:   7%|▋         | 143/2000 [00:02<00:22, 83.07it/s, test=5.8%, test_loss=2.656, train=5.7%, train_loss=2.685]

outcome_architecture/process:   8%|▊         | 152/2000 [00:02<00:29, 62.09it/s, test=5.8%, test_loss=2.656, train=5.7%, train_loss=2.685]

outcome_architecture/process:   8%|▊         | 163/2000 [00:02<00:25, 71.35it/s, test=5.8%, test_loss=2.656, train=5.7%, train_loss=2.685]

outcome_architecture/process:   9%|▊         | 174/2000 [00:02<00:23, 78.84it/s, test=5.8%, test_loss=2.656, train=5.7%, train_loss=2.685]

outcome_architecture/process:   9%|▉         | 185/2000 [00:03<00:21, 85.03it/s, test=5.8%, test_loss=2.656, train=5.7%, train_loss=2.685]

outcome_architecture/process:  10%|▉         | 196/2000 [00:03<00:20, 89.67it/s, test=5.8%, test_loss=2.656, train=5.7%, train_loss=2.685]

outcome_architecture/process:  10%|▉         | 196/2000 [00:03<00:20, 89.67it/s, test=9.0%, test_loss=2.572, train=6.7%, train_loss=2.615]

outcome_architecture/process:  10%|█         | 206/2000 [00:03<00:27, 66.39it/s, test=9.0%, test_loss=2.572, train=6.7%, train_loss=2.615]

outcome_architecture/process:  11%|█         | 217/2000 [00:03<00:23, 74.58it/s, test=9.0%, test_loss=2.572, train=6.7%, train_loss=2.615]

outcome_architecture/process:  11%|█▏        | 228/2000 [00:03<00:21, 81.21it/s, test=9.0%, test_loss=2.572, train=6.7%, train_loss=2.615]

outcome_architecture/process:  12%|█▏        | 239/2000 [00:03<00:20, 86.82it/s, test=9.0%, test_loss=2.572, train=6.7%, train_loss=2.615]

outcome_architecture/process:  12%|█▏        | 239/2000 [00:04<00:20, 86.82it/s, test=10.0%, test_loss=2.457, train=8.0%, train_loss=2.537]

outcome_architecture/process:  12%|█▎        | 250/2000 [00:04<00:26, 66.16it/s, test=10.0%, test_loss=2.457, train=8.0%, train_loss=2.537]

outcome_architecture/process:  13%|█▎        | 261/2000 [00:04<00:23, 74.06it/s, test=10.0%, test_loss=2.457, train=8.0%, train_loss=2.537]

outcome_architecture/process:  14%|█▎        | 272/2000 [00:04<00:21, 80.77it/s, test=10.0%, test_loss=2.457, train=8.0%, train_loss=2.537]

outcome_architecture/process:  14%|█▍        | 283/2000 [00:04<00:19, 86.34it/s, test=10.0%, test_loss=2.457, train=8.0%, train_loss=2.537]

outcome_architecture/process:  15%|█▍        | 294/2000 [00:04<00:18, 90.53it/s, test=10.0%, test_loss=2.457, train=8.0%, train_loss=2.537]

outcome_architecture/process:  15%|█▍        | 294/2000 [00:04<00:18, 90.53it/s, test=10.7%, test_loss=2.425, train=9.3%, train_loss=2.451]

outcome_architecture/process:  15%|█▌        | 304/2000 [00:04<00:25, 67.11it/s, test=10.7%, test_loss=2.425, train=9.3%, train_loss=2.451]

outcome_architecture/process:  16%|█▌        | 315/2000 [00:04<00:22, 74.98it/s, test=10.7%, test_loss=2.425, train=9.3%, train_loss=2.451]

outcome_architecture/process:  16%|█▋        | 326/2000 [00:04<00:20, 81.67it/s, test=10.7%, test_loss=2.425, train=9.3%, train_loss=2.451]

outcome_architecture/process:  17%|█▋        | 337/2000 [00:05<00:19, 87.10it/s, test=10.7%, test_loss=2.425, train=9.3%, train_loss=2.451]

outcome_architecture/process:  17%|█▋        | 348/2000 [00:05<00:18, 91.30it/s, test=10.7%, test_loss=2.425, train=9.3%, train_loss=2.451]

outcome_architecture/process:  17%|█▋        | 348/2000 [00:05<00:18, 91.30it/s, test=12.9%, test_loss=2.287, train=11.7%, train_loss=2.331]

outcome_architecture/process:  18%|█▊        | 358/2000 [00:05<00:24, 67.07it/s, test=12.9%, test_loss=2.287, train=11.7%, train_loss=2.331]

outcome_architecture/process:  18%|█▊        | 369/2000 [00:05<00:21, 75.15it/s, test=12.9%, test_loss=2.287, train=11.7%, train_loss=2.331]

outcome_architecture/process:  19%|█▉        | 380/2000 [00:05<00:19, 81.78it/s, test=12.9%, test_loss=2.287, train=11.7%, train_loss=2.331]

outcome_architecture/process:  20%|█▉        | 391/2000 [00:05<00:18, 86.94it/s, test=12.9%, test_loss=2.287, train=11.7%, train_loss=2.331]

outcome_architecture/process:  20%|█▉        | 391/2000 [00:05<00:18, 86.94it/s, test=8.9%, test_loss=2.185, train=9.3%, train_loss=2.147]

outcome_architecture/process:  20%|██        | 401/2000 [00:05<00:24, 65.26it/s, test=8.9%, test_loss=2.185, train=9.3%, train_loss=2.147]

outcome_architecture/process:  21%|██        | 412/2000 [00:06<00:21, 73.56it/s, test=8.9%, test_loss=2.185, train=9.3%, train_loss=2.147]

outcome_architecture/process:  21%|██        | 423/2000 [00:06<00:19, 80.25it/s, test=8.9%, test_loss=2.185, train=9.3%, train_loss=2.147]

outcome_architecture/process:  22%|██▏       | 434/2000 [00:06<00:18, 86.01it/s, test=8.9%, test_loss=2.185, train=9.3%, train_loss=2.147]

outcome_architecture/process:  22%|██▏       | 444/2000 [00:06<00:17, 88.25it/s, test=8.9%, test_loss=2.185, train=9.3%, train_loss=2.147]

outcome_architecture/process:  22%|██▏       | 444/2000 [00:06<00:17, 88.25it/s, test=11.2%, test_loss=2.019, train=10.3%, train_loss=2.014]

outcome_architecture/process:  23%|██▎       | 454/2000 [00:06<00:23, 65.69it/s, test=11.2%, test_loss=2.019, train=10.3%, train_loss=2.014]

outcome_architecture/process:  23%|██▎       | 465/2000 [00:06<00:20, 74.01it/s, test=11.2%, test_loss=2.019, train=10.3%, train_loss=2.014]

outcome_architecture/process:  24%|██▍       | 476/2000 [00:06<00:18, 80.94it/s, test=11.2%, test_loss=2.019, train=10.3%, train_loss=2.014]

outcome_architecture/process:  24%|██▍       | 487/2000 [00:06<00:17, 86.55it/s, test=11.2%, test_loss=2.019, train=10.3%, train_loss=2.014]

outcome_architecture/process:  25%|██▍       | 498/2000 [00:07<00:16, 90.76it/s, test=11.2%, test_loss=2.019, train=10.3%, train_loss=2.014]

outcome_architecture/process:  25%|██▍       | 498/2000 [00:07<00:16, 90.76it/s, test=11.8%, test_loss=1.857, train=8.7%, train_loss=1.885]

outcome_architecture/process:  25%|██▌       | 508/2000 [00:07<00:22, 66.89it/s, test=11.8%, test_loss=1.857, train=8.7%, train_loss=1.885]

outcome_architecture/process:  26%|██▌       | 519/2000 [00:07<00:19, 74.91it/s, test=11.8%, test_loss=1.857, train=8.7%, train_loss=1.885]

outcome_architecture/process:  26%|██▋       | 530/2000 [00:07<00:18, 81.52it/s, test=11.8%, test_loss=1.857, train=8.7%, train_loss=1.885]

outcome_architecture/process:  27%|██▋       | 541/2000 [00:07<00:16, 86.88it/s, test=11.8%, test_loss=1.857, train=8.7%, train_loss=1.885]

outcome_architecture/process:  27%|██▋       | 541/2000 [00:07<00:16, 86.88it/s, test=12.4%, test_loss=1.886, train=10.3%, train_loss=1.880]

outcome_architecture/process:  28%|██▊       | 551/2000 [00:07<00:22, 65.48it/s, test=12.4%, test_loss=1.886, train=10.3%, train_loss=1.880]

outcome_architecture/process:  28%|██▊       | 562/2000 [00:07<00:19, 73.79it/s, test=12.4%, test_loss=1.886, train=10.3%, train_loss=1.880]

outcome_architecture/process:  29%|██▊       | 573/2000 [00:08<00:17, 80.70it/s, test=12.4%, test_loss=1.886, train=10.3%, train_loss=1.880]

outcome_architecture/process:  29%|██▉       | 584/2000 [00:08<00:16, 86.31it/s, test=12.4%, test_loss=1.886, train=10.3%, train_loss=1.880]

outcome_architecture/process:  30%|██▉       | 595/2000 [00:08<00:15, 90.64it/s, test=12.4%, test_loss=1.886, train=10.3%, train_loss=1.880]

outcome_architecture/process:  30%|██▉       | 595/2000 [00:08<00:15, 90.64it/s, test=12.6%, test_loss=1.655, train=12.0%, train_loss=1.623]

outcome_architecture/process:  30%|███       | 605/2000 [00:08<00:20, 66.98it/s, test=12.6%, test_loss=1.655, train=12.0%, train_loss=1.623]

outcome_architecture/process:  31%|███       | 616/2000 [00:08<00:18, 75.16it/s, test=12.6%, test_loss=1.655, train=12.0%, train_loss=1.623]

outcome_architecture/process:  31%|███▏      | 627/2000 [00:08<00:16, 81.82it/s, test=12.6%, test_loss=1.655, train=12.0%, train_loss=1.623]

outcome_architecture/process:  32%|███▏      | 638/2000 [00:08<00:15, 87.25it/s, test=12.6%, test_loss=1.655, train=12.0%, train_loss=1.623]

outcome_architecture/process:  32%|███▏      | 649/2000 [00:08<00:14, 91.56it/s, test=12.6%, test_loss=1.655, train=12.0%, train_loss=1.623]

outcome_architecture/process:  32%|███▏      | 649/2000 [00:09<00:14, 91.56it/s, test=12.6%, test_loss=1.494, train=12.7%, train_loss=1.471]

outcome_architecture/process:  33%|███▎      | 659/2000 [00:09<00:20, 66.71it/s, test=12.6%, test_loss=1.494, train=12.7%, train_loss=1.471]

outcome_architecture/process:  33%|███▎      | 668/2000 [00:09<00:18, 71.03it/s, test=12.6%, test_loss=1.494, train=12.7%, train_loss=1.471]

outcome_architecture/process:  34%|███▍      | 677/2000 [00:09<00:17, 75.22it/s, test=12.6%, test_loss=1.494, train=12.7%, train_loss=1.471]

outcome_architecture/process:  34%|███▍      | 686/2000 [00:09<00:16, 78.23it/s, test=12.6%, test_loss=1.494, train=12.7%, train_loss=1.471]

outcome_architecture/process:  35%|███▍      | 697/2000 [00:09<00:15, 84.80it/s, test=12.6%, test_loss=1.494, train=12.7%, train_loss=1.471]

outcome_architecture/process:  35%|███▍      | 697/2000 [00:09<00:15, 84.80it/s, test=0.0%, test_loss=6.183, train=0.0%, train_loss=6.778]

outcome_architecture/process:  35%|███▌      | 707/2000 [00:09<00:20, 63.78it/s, test=0.0%, test_loss=6.183, train=0.0%, train_loss=6.778]

outcome_architecture/process:  36%|███▌      | 718/2000 [00:09<00:17, 72.57it/s, test=0.0%, test_loss=6.183, train=0.0%, train_loss=6.778]

outcome_architecture/process:  36%|███▋      | 728/2000 [00:10<00:16, 78.11it/s, test=0.0%, test_loss=6.183, train=0.0%, train_loss=6.778]

outcome_architecture/process:  37%|███▋      | 738/2000 [00:10<00:15, 81.84it/s, test=0.0%, test_loss=6.183, train=0.0%, train_loss=6.778]

outcome_architecture/process:  37%|███▋      | 748/2000 [00:10<00:14, 85.41it/s, test=0.0%, test_loss=6.183, train=0.0%, train_loss=6.778]

outcome_architecture/process:  37%|███▋      | 748/2000 [00:10<00:14, 85.41it/s, test=9.9%, test_loss=1.414, train=9.0%, train_loss=1.388]

outcome_architecture/process:  38%|███▊      | 758/2000 [00:10<00:20, 61.71it/s, test=9.9%, test_loss=1.414, train=9.0%, train_loss=1.388]

outcome_architecture/process:  38%|███▊      | 768/2000 [00:10<00:17, 69.04it/s, test=9.9%, test_loss=1.414, train=9.0%, train_loss=1.388]

outcome_architecture/process:  39%|███▉      | 778/2000 [00:10<00:16, 75.24it/s, test=9.9%, test_loss=1.414, train=9.0%, train_loss=1.388]

outcome_architecture/process:  39%|███▉      | 788/2000 [00:10<00:15, 80.49it/s, test=9.9%, test_loss=1.414, train=9.0%, train_loss=1.388]

outcome_architecture/process:  40%|███▉      | 798/2000 [00:10<00:14, 84.73it/s, test=9.9%, test_loss=1.414, train=9.0%, train_loss=1.388]

outcome_architecture/process:  40%|███▉      | 798/2000 [00:11<00:14, 84.73it/s, test=13.0%, test_loss=0.866, train=11.0%, train_loss=0.837]

outcome_architecture/process:  40%|████      | 808/2000 [00:11<00:18, 63.46it/s, test=13.0%, test_loss=0.866, train=11.0%, train_loss=0.837]

outcome_architecture/process:  41%|████      | 819/2000 [00:11<00:16, 71.88it/s, test=13.0%, test_loss=0.866, train=11.0%, train_loss=0.837]

outcome_architecture/process:  41%|████▏     | 829/2000 [00:11<00:14, 78.13it/s, test=13.0%, test_loss=0.866, train=11.0%, train_loss=0.837]

outcome_architecture/process:  42%|████▏     | 839/2000 [00:11<00:13, 83.42it/s, test=13.0%, test_loss=0.866, train=11.0%, train_loss=0.837]

outcome_architecture/process:  42%|████▏     | 839/2000 [00:11<00:13, 83.42it/s, test=13.0%, test_loss=0.718, train=10.0%, train_loss=0.654]

outcome_architecture/process:  42%|████▎     | 850/2000 [00:11<00:18, 63.77it/s, test=13.0%, test_loss=0.718, train=10.0%, train_loss=0.654]

outcome_architecture/process:  43%|████▎     | 860/2000 [00:11<00:16, 71.09it/s, test=13.0%, test_loss=0.718, train=10.0%, train_loss=0.654]

outcome_architecture/process:  44%|████▎     | 870/2000 [00:12<00:14, 77.58it/s, test=13.0%, test_loss=0.718, train=10.0%, train_loss=0.654]

outcome_architecture/process:  44%|████▍     | 880/2000 [00:12<00:13, 82.99it/s, test=13.0%, test_loss=0.718, train=10.0%, train_loss=0.654]

outcome_architecture/process:  44%|████▍     | 890/2000 [00:12<00:12, 87.22it/s, test=13.0%, test_loss=0.718, train=10.0%, train_loss=0.654]

outcome_architecture/process:  44%|████▍     | 890/2000 [00:12<00:12, 87.22it/s, test=15.6%, test_loss=0.630, train=12.3%, train_loss=0.557]

outcome_architecture/process:  45%|████▌     | 900/2000 [00:12<00:17, 64.29it/s, test=15.6%, test_loss=0.630, train=12.3%, train_loss=0.557]

outcome_architecture/process:  46%|████▌     | 911/2000 [00:12<00:14, 72.87it/s, test=15.6%, test_loss=0.630, train=12.3%, train_loss=0.557]

outcome_architecture/process:  46%|████▌     | 922/2000 [00:12<00:13, 80.04it/s, test=15.6%, test_loss=0.630, train=12.3%, train_loss=0.557]

outcome_architecture/process:  47%|████▋     | 933/2000 [00:12<00:12, 85.47it/s, test=15.6%, test_loss=0.630, train=12.3%, train_loss=0.557]

outcome_architecture/process:  47%|████▋     | 944/2000 [00:12<00:11, 89.63it/s, test=15.6%, test_loss=0.630, train=12.3%, train_loss=0.557]

outcome_architecture/process:  47%|████▋     | 944/2000 [00:13<00:11, 89.63it/s, test=18.5%, test_loss=0.487, train=14.3%, train_loss=0.468]

outcome_architecture/process:  48%|████▊     | 954/2000 [00:13<00:15, 66.20it/s, test=18.5%, test_loss=0.487, train=14.3%, train_loss=0.468]

outcome_architecture/process:  48%|████▊     | 965/2000 [00:13<00:13, 74.33it/s, test=18.5%, test_loss=0.487, train=14.3%, train_loss=0.468]

outcome_architecture/process:  49%|████▉     | 976/2000 [00:13<00:12, 81.10it/s, test=18.5%, test_loss=0.487, train=14.3%, train_loss=0.468]

outcome_architecture/process:  49%|████▉     | 987/2000 [00:13<00:11, 86.64it/s, test=18.5%, test_loss=0.487, train=14.3%, train_loss=0.468]

outcome_architecture/process:  50%|████▉     | 998/2000 [00:13<00:11, 91.00it/s, test=18.5%, test_loss=0.487, train=14.3%, train_loss=0.468]

outcome_architecture/process:  50%|████▉     | 998/2000 [00:13<00:11, 91.00it/s, test=34.6%, test_loss=0.280, train=33.3%, train_loss=0.257]

outcome_architecture/process:  50%|█████     | 1008/2000 [00:13<00:15, 66.12it/s, test=34.6%, test_loss=0.280, train=33.3%, train_loss=0.257]

outcome_architecture/process:  51%|█████     | 1019/2000 [00:13<00:13, 74.31it/s, test=34.6%, test_loss=0.280, train=33.3%, train_loss=0.257]

outcome_architecture/process:  52%|█████▏    | 1030/2000 [00:14<00:11, 81.07it/s, test=34.6%, test_loss=0.280, train=33.3%, train_loss=0.257]

outcome_architecture/process:  52%|█████▏    | 1041/2000 [00:14<00:11, 86.51it/s, test=34.6%, test_loss=0.280, train=33.3%, train_loss=0.257]

outcome_architecture/process:  52%|█████▏    | 1041/2000 [00:14<00:11, 86.51it/s, test=56.2%, test_loss=0.131, train=52.3%, train_loss=0.144]

outcome_architecture/process:  53%|█████▎    | 1051/2000 [00:14<00:14, 65.28it/s, test=56.2%, test_loss=0.131, train=52.3%, train_loss=0.144]

outcome_architecture/process:  53%|█████▎    | 1061/2000 [00:14<00:13, 71.69it/s, test=56.2%, test_loss=0.131, train=52.3%, train_loss=0.144]

outcome_architecture/process:  54%|█████▎    | 1072/2000 [00:14<00:11, 79.07it/s, test=56.2%, test_loss=0.131, train=52.3%, train_loss=0.144]

outcome_architecture/process:  54%|█████▍    | 1083/2000 [00:14<00:10, 85.08it/s, test=56.2%, test_loss=0.131, train=52.3%, train_loss=0.144]

outcome_architecture/process:  55%|█████▍    | 1094/2000 [00:14<00:10, 89.73it/s, test=56.2%, test_loss=0.131, train=52.3%, train_loss=0.144]

outcome_architecture/process:  55%|█████▍    | 1094/2000 [00:15<00:10, 89.73it/s, test=57.3%, test_loss=0.154, train=56.7%, train_loss=0.126]

outcome_architecture/process:  55%|█████▌    | 1104/2000 [00:15<00:13, 66.57it/s, test=57.3%, test_loss=0.154, train=56.7%, train_loss=0.126]

outcome_architecture/process:  56%|█████▌    | 1115/2000 [00:15<00:11, 74.68it/s, test=57.3%, test_loss=0.154, train=56.7%, train_loss=0.126]

outcome_architecture/process:  56%|█████▋    | 1126/2000 [00:15<00:10, 81.23it/s, test=57.3%, test_loss=0.154, train=56.7%, train_loss=0.126]

outcome_architecture/process:  57%|█████▋    | 1137/2000 [00:15<00:09, 86.49it/s, test=57.3%, test_loss=0.154, train=56.7%, train_loss=0.126]

outcome_architecture/process:  57%|█████▋    | 1147/2000 [00:15<00:09, 88.68it/s, test=57.3%, test_loss=0.154, train=56.7%, train_loss=0.126]

outcome_architecture/process:  57%|█████▋    | 1147/2000 [00:15<00:09, 88.68it/s, test=66.0%, test_loss=0.093, train=63.3%, train_loss=0.082]

outcome_architecture/process:  58%|█████▊    | 1157/2000 [00:15<00:13, 64.73it/s, test=66.0%, test_loss=0.093, train=63.3%, train_loss=0.082]

outcome_architecture/process:  58%|█████▊    | 1167/2000 [00:15<00:11, 72.02it/s, test=66.0%, test_loss=0.093, train=63.3%, train_loss=0.082]

outcome_architecture/process:  59%|█████▉    | 1178/2000 [00:15<00:10, 79.40it/s, test=66.0%, test_loss=0.093, train=63.3%, train_loss=0.082]

outcome_architecture/process:  59%|█████▉    | 1189/2000 [00:16<00:09, 85.24it/s, test=66.0%, test_loss=0.093, train=63.3%, train_loss=0.082]

outcome_architecture/process:  59%|█████▉    | 1189/2000 [00:16<00:09, 85.24it/s, test=0.0%, test_loss=68125.297, train=0.0%, train_loss=69853.117]

outcome_architecture/process:  60%|██████    | 1200/2000 [00:16<00:12, 65.50it/s, test=0.0%, test_loss=68125.297, train=0.0%, train_loss=69853.117]

outcome_architecture/process:  61%|██████    | 1211/2000 [00:16<00:10, 73.54it/s, test=0.0%, test_loss=68125.297, train=0.0%, train_loss=69853.117]

outcome_architecture/process:  61%|██████    | 1222/2000 [00:16<00:09, 80.55it/s, test=0.0%, test_loss=68125.297, train=0.0%, train_loss=69853.117]

outcome_architecture/process:  62%|██████▏   | 1233/2000 [00:16<00:08, 86.12it/s, test=0.0%, test_loss=68125.297, train=0.0%, train_loss=69853.117]

outcome_architecture/process:  62%|██████▏   | 1244/2000 [00:16<00:08, 90.39it/s, test=0.0%, test_loss=68125.297, train=0.0%, train_loss=69853.117]

outcome_architecture/process:  62%|██████▏   | 1244/2000 [00:16<00:08, 90.39it/s, test=0.0%, test_loss=301866.094, train=0.0%, train_loss=272674.094]

outcome_architecture/process:  63%|██████▎   | 1254/2000 [00:17<00:11, 66.87it/s, test=0.0%, test_loss=301866.094, train=0.0%, train_loss=272674.094]

outcome_architecture/process:  63%|██████▎   | 1265/2000 [00:17<00:09, 74.87it/s, test=0.0%, test_loss=301866.094, train=0.0%, train_loss=272674.094]

outcome_architecture/process:  64%|██████▍   | 1276/2000 [00:17<00:08, 81.63it/s, test=0.0%, test_loss=301866.094, train=0.0%, train_loss=272674.094]

outcome_architecture/process:  64%|██████▍   | 1287/2000 [00:17<00:08, 86.97it/s, test=0.0%, test_loss=301866.094, train=0.0%, train_loss=272674.094]

outcome_architecture/process:  65%|██████▍   | 1298/2000 [00:17<00:07, 91.17it/s, test=0.0%, test_loss=301866.094, train=0.0%, train_loss=272674.094]

outcome_architecture/process:  65%|██████▍   | 1298/2000 [00:17<00:07, 91.17it/s, test=0.0%, test_loss=316454.719, train=0.0%, train_loss=229047.609]

outcome_architecture/process:  65%|██████▌   | 1308/2000 [00:17<00:10, 67.39it/s, test=0.0%, test_loss=316454.719, train=0.0%, train_loss=229047.609]

outcome_architecture/process:  66%|██████▌   | 1318/2000 [00:17<00:09, 74.23it/s, test=0.0%, test_loss=316454.719, train=0.0%, train_loss=229047.609]

outcome_architecture/process:  66%|██████▋   | 1329/2000 [00:17<00:08, 80.95it/s, test=0.0%, test_loss=316454.719, train=0.0%, train_loss=229047.609]

outcome_architecture/process:  67%|██████▋   | 1340/2000 [00:18<00:07, 86.33it/s, test=0.0%, test_loss=316454.719, train=0.0%, train_loss=229047.609]

outcome_architecture/process:  67%|██████▋   | 1340/2000 [00:18<00:07, 86.33it/s, test=0.0%, test_loss=75300.102, train=0.0%, train_loss=94935.094]

outcome_architecture/process:  68%|██████▊   | 1350/2000 [00:18<00:09, 65.27it/s, test=0.0%, test_loss=75300.102, train=0.0%, train_loss=94935.094]

outcome_architecture/process:  68%|██████▊   | 1360/2000 [00:18<00:08, 72.49it/s, test=0.0%, test_loss=75300.102, train=0.0%, train_loss=94935.094]

outcome_architecture/process:  69%|██████▊   | 1371/2000 [00:18<00:07, 79.90it/s, test=0.0%, test_loss=75300.102, train=0.0%, train_loss=94935.094]

outcome_architecture/process:  69%|██████▉   | 1382/2000 [00:18<00:07, 85.58it/s, test=0.0%, test_loss=75300.102, train=0.0%, train_loss=94935.094]

outcome_architecture/process:  70%|██████▉   | 1393/2000 [00:18<00:06, 89.94it/s, test=0.0%, test_loss=75300.102, train=0.0%, train_loss=94935.094]

outcome_architecture/process:  70%|██████▉   | 1393/2000 [00:18<00:06, 89.94it/s, test=0.0%, test_loss=21468.475, train=0.0%, train_loss=27679.775]

outcome_architecture/process:  70%|███████   | 1403/2000 [00:18<00:08, 66.68it/s, test=0.0%, test_loss=21468.475, train=0.0%, train_loss=27679.775]

outcome_architecture/process:  71%|███████   | 1414/2000 [00:19<00:07, 74.67it/s, test=0.0%, test_loss=21468.475, train=0.0%, train_loss=27679.775]

outcome_architecture/process:  71%|███████▏  | 1425/2000 [00:19<00:07, 81.38it/s, test=0.0%, test_loss=21468.475, train=0.0%, train_loss=27679.775]

outcome_architecture/process:  72%|███████▏  | 1436/2000 [00:19<00:06, 86.73it/s, test=0.0%, test_loss=21468.475, train=0.0%, train_loss=27679.775]

outcome_architecture/process:  72%|███████▏  | 1447/2000 [00:19<00:06, 91.20it/s, test=0.0%, test_loss=21468.475, train=0.0%, train_loss=27679.775]

outcome_architecture/process:  72%|███████▏  | 1447/2000 [00:19<00:06, 91.20it/s, test=0.0%, test_loss=4140.783, train=0.0%, train_loss=4605.023]

outcome_architecture/process:  73%|███████▎  | 1457/2000 [00:19<00:08, 67.01it/s, test=0.0%, test_loss=4140.783, train=0.0%, train_loss=4605.023]

outcome_architecture/process:  73%|███████▎  | 1468/2000 [00:19<00:07, 74.87it/s, test=0.0%, test_loss=4140.783, train=0.0%, train_loss=4605.023]

outcome_architecture/process:  74%|███████▍  | 1478/2000 [00:19<00:06, 79.15it/s, test=0.0%, test_loss=4140.783, train=0.0%, train_loss=4605.023]

outcome_architecture/process:  74%|███████▍  | 1488/2000 [00:19<00:06, 82.16it/s, test=0.0%, test_loss=4140.783, train=0.0%, train_loss=4605.023]

outcome_architecture/process:  75%|███████▍  | 1499/2000 [00:20<00:05, 88.17it/s, test=0.0%, test_loss=4140.783, train=0.0%, train_loss=4605.023]

outcome_architecture/process:  75%|███████▍  | 1499/2000 [00:20<00:05, 88.17it/s, test=0.0%, test_loss=2643.008, train=0.0%, train_loss=2897.435]

outcome_architecture/process:  75%|███████▌  | 1509/2000 [00:20<00:07, 65.94it/s, test=0.0%, test_loss=2643.008, train=0.0%, train_loss=2897.435]

outcome_architecture/process:  76%|███████▌  | 1520/2000 [00:20<00:06, 74.06it/s, test=0.0%, test_loss=2643.008, train=0.0%, train_loss=2897.435]

outcome_architecture/process:  77%|███████▋  | 1531/2000 [00:20<00:05, 80.65it/s, test=0.0%, test_loss=2643.008, train=0.0%, train_loss=2897.435]

outcome_architecture/process:  77%|███████▋  | 1542/2000 [00:20<00:05, 85.90it/s, test=0.0%, test_loss=2643.008, train=0.0%, train_loss=2897.435]

outcome_architecture/process:  77%|███████▋  | 1542/2000 [00:20<00:05, 85.90it/s, test=0.0%, test_loss=603654.438, train=0.0%, train_loss=508219.375]

outcome_architecture/process:  78%|███████▊  | 1552/2000 [00:20<00:06, 65.17it/s, test=0.0%, test_loss=603654.438, train=0.0%, train_loss=508219.375]

outcome_architecture/process:  78%|███████▊  | 1563/2000 [00:20<00:05, 73.44it/s, test=0.0%, test_loss=603654.438, train=0.0%, train_loss=508219.375]

outcome_architecture/process:  79%|███████▊  | 1574/2000 [00:21<00:05, 80.31it/s, test=0.0%, test_loss=603654.438, train=0.0%, train_loss=508219.375]

outcome_architecture/process:  79%|███████▉  | 1585/2000 [00:21<00:04, 86.18it/s, test=0.0%, test_loss=603654.438, train=0.0%, train_loss=508219.375]

outcome_architecture/process:  80%|███████▉  | 1596/2000 [00:21<00:04, 90.57it/s, test=0.0%, test_loss=603654.438, train=0.0%, train_loss=508219.375]

outcome_architecture/process:  80%|███████▉  | 1596/2000 [00:21<00:04, 90.57it/s, test=0.0%, test_loss=26787.283, train=0.0%, train_loss=25960.643]

outcome_architecture/process:  80%|████████  | 1606/2000 [00:21<00:05, 67.23it/s, test=0.0%, test_loss=26787.283, train=0.0%, train_loss=25960.643]

outcome_architecture/process:  81%|████████  | 1617/2000 [00:21<00:05, 75.14it/s, test=0.0%, test_loss=26787.283, train=0.0%, train_loss=25960.643]

outcome_architecture/process:  81%|████████▏ | 1628/2000 [00:21<00:04, 81.78it/s, test=0.0%, test_loss=26787.283, train=0.0%, train_loss=25960.643]

outcome_architecture/process:  82%|████████▏ | 1639/2000 [00:21<00:04, 86.82it/s, test=0.0%, test_loss=26787.283, train=0.0%, train_loss=25960.643]

outcome_architecture/process:  82%|████████▏ | 1639/2000 [00:22<00:04, 86.82it/s, test=0.1%, test_loss=8940.812, train=0.0%, train_loss=9111.694]

outcome_architecture/process:  82%|████████▎ | 1650/2000 [00:22<00:05, 65.88it/s, test=0.1%, test_loss=8940.812, train=0.0%, train_loss=9111.694]

outcome_architecture/process:  83%|████████▎ | 1661/2000 [00:22<00:04, 73.70it/s, test=0.1%, test_loss=8940.812, train=0.0%, train_loss=9111.694]

outcome_architecture/process:  84%|████████▎ | 1672/2000 [00:22<00:04, 80.53it/s, test=0.1%, test_loss=8940.812, train=0.0%, train_loss=9111.694]

outcome_architecture/process:  84%|████████▍ | 1683/2000 [00:22<00:03, 86.33it/s, test=0.1%, test_loss=8940.812, train=0.0%, train_loss=9111.694]

outcome_architecture/process:  85%|████████▍ | 1693/2000 [00:22<00:03, 89.47it/s, test=0.1%, test_loss=8940.812, train=0.0%, train_loss=9111.694]

outcome_architecture/process:  85%|████████▍ | 1693/2000 [00:22<00:03, 89.47it/s, test=0.0%, test_loss=6317.013, train=0.0%, train_loss=5722.024]

outcome_architecture/process:  85%|████████▌ | 1703/2000 [00:22<00:04, 65.21it/s, test=0.0%, test_loss=6317.013, train=0.0%, train_loss=5722.024]

outcome_architecture/process:  86%|████████▌ | 1713/2000 [00:22<00:04, 70.88it/s, test=0.0%, test_loss=6317.013, train=0.0%, train_loss=5722.024]

outcome_architecture/process:  86%|████████▌ | 1722/2000 [00:23<00:03, 74.97it/s, test=0.0%, test_loss=6317.013, train=0.0%, train_loss=5722.024]

outcome_architecture/process:  87%|████████▋ | 1732/2000 [00:23<00:03, 79.76it/s, test=0.0%, test_loss=6317.013, train=0.0%, train_loss=5722.024]

outcome_architecture/process:  87%|████████▋ | 1741/2000 [00:23<00:03, 82.08it/s, test=0.0%, test_loss=6317.013, train=0.0%, train_loss=5722.024]

outcome_architecture/process:  87%|████████▋ | 1741/2000 [00:23<00:03, 82.08it/s, test=0.2%, test_loss=5656.351, train=0.3%, train_loss=5417.054]

outcome_architecture/process:  88%|████████▊ | 1750/2000 [00:23<00:04, 58.89it/s, test=0.2%, test_loss=5656.351, train=0.3%, train_loss=5417.054]

outcome_architecture/process:  88%|████████▊ | 1760/2000 [00:23<00:03, 66.47it/s, test=0.2%, test_loss=5656.351, train=0.3%, train_loss=5417.054]

outcome_architecture/process:  88%|████████▊ | 1770/2000 [00:23<00:03, 72.79it/s, test=0.2%, test_loss=5656.351, train=0.3%, train_loss=5417.054]

outcome_architecture/process:  89%|████████▉ | 1780/2000 [00:23<00:02, 78.06it/s, test=0.2%, test_loss=5656.351, train=0.3%, train_loss=5417.054]

outcome_architecture/process:  90%|████████▉ | 1790/2000 [00:23<00:02, 82.14it/s, test=0.2%, test_loss=5656.351, train=0.3%, train_loss=5417.054]

outcome_architecture/process:  90%|████████▉ | 1790/2000 [00:24<00:02, 82.14it/s, test=0.0%, test_loss=2864976.750, train=0.0%, train_loss=2864131.000]

outcome_architecture/process:  90%|█████████ | 1800/2000 [00:24<00:03, 61.72it/s, test=0.0%, test_loss=2864976.750, train=0.0%, train_loss=2864131.000]

outcome_architecture/process:  90%|█████████ | 1810/2000 [00:24<00:02, 68.33it/s, test=0.0%, test_loss=2864976.750, train=0.0%, train_loss=2864131.000]

outcome_architecture/process:  91%|█████████ | 1820/2000 [00:24<00:02, 74.38it/s, test=0.0%, test_loss=2864976.750, train=0.0%, train_loss=2864131.000]

outcome_architecture/process:  92%|█████████▏| 1830/2000 [00:24<00:02, 79.46it/s, test=0.0%, test_loss=2864976.750, train=0.0%, train_loss=2864131.000]

outcome_architecture/process:  92%|█████████▏| 1840/2000 [00:24<00:01, 83.15it/s, test=0.0%, test_loss=2864976.750, train=0.0%, train_loss=2864131.000]

outcome_architecture/process:  92%|█████████▏| 1840/2000 [00:24<00:01, 83.15it/s, test=0.0%, test_loss=309716.594, train=0.0%, train_loss=310442.781]

outcome_architecture/process:  92%|█████████▎| 1850/2000 [00:24<00:02, 62.13it/s, test=0.0%, test_loss=309716.594, train=0.0%, train_loss=310442.781]

outcome_architecture/process:  93%|█████████▎| 1860/2000 [00:24<00:02, 69.14it/s, test=0.0%, test_loss=309716.594, train=0.0%, train_loss=310442.781]

outcome_architecture/process:  94%|█████████▎| 1870/2000 [00:25<00:01, 74.85it/s, test=0.0%, test_loss=309716.594, train=0.0%, train_loss=310442.781]

outcome_architecture/process:  94%|█████████▍| 1880/2000 [00:25<00:01, 79.47it/s, test=0.0%, test_loss=309716.594, train=0.0%, train_loss=310442.781]

outcome_architecture/process:  95%|█████████▍| 1891/2000 [00:25<00:01, 85.32it/s, test=0.0%, test_loss=309716.594, train=0.0%, train_loss=310442.781]

outcome_architecture/process:  95%|█████████▍| 1891/2000 [00:25<00:01, 85.32it/s, test=0.0%, test_loss=26270.398, train=0.0%, train_loss=22857.836]

outcome_architecture/process:  95%|█████████▌| 1901/2000 [00:25<00:01, 64.13it/s, test=0.0%, test_loss=26270.398, train=0.0%, train_loss=22857.836]

outcome_architecture/process:  96%|█████████▌| 1912/2000 [00:25<00:01, 72.81it/s, test=0.0%, test_loss=26270.398, train=0.0%, train_loss=22857.836]

outcome_architecture/process:  96%|█████████▌| 1923/2000 [00:25<00:00, 80.07it/s, test=0.0%, test_loss=26270.398, train=0.0%, train_loss=22857.836]

outcome_architecture/process:  97%|█████████▋| 1934/2000 [00:25<00:00, 85.93it/s, test=0.0%, test_loss=26270.398, train=0.0%, train_loss=22857.836]

outcome_architecture/process:  97%|█████████▋| 1945/2000 [00:25<00:00, 90.56it/s, test=0.0%, test_loss=26270.398, train=0.0%, train_loss=22857.836]

outcome_architecture/process:  97%|█████████▋| 1945/2000 [00:26<00:00, 90.56it/s, test=0.0%, test_loss=17053.461, train=0.0%, train_loss=14901.351]

outcome_architecture/process:  98%|█████████▊| 1955/2000 [00:26<00:00, 67.08it/s, test=0.0%, test_loss=17053.461, train=0.0%, train_loss=14901.351]

outcome_architecture/process:  98%|█████████▊| 1966/2000 [00:26<00:00, 75.11it/s, test=0.0%, test_loss=17053.461, train=0.0%, train_loss=14901.351]

outcome_architecture/process:  99%|█████████▉| 1977/2000 [00:26<00:00, 81.82it/s, test=0.0%, test_loss=17053.461, train=0.0%, train_loss=14901.351]

outcome_architecture/process:  99%|█████████▉| 1988/2000 [00:26<00:00, 87.07it/s, test=0.0%, test_loss=17053.461, train=0.0%, train_loss=14901.351]

outcome_architecture/process: 100%|█████████▉| 1999/2000 [00:26<00:00, 91.08it/s, test=0.0%, test_loss=17053.461, train=0.0%, train_loss=14901.351]

outcome_architecture/process: 100%|█████████▉| 1999/2000 [00:26<00:00, 91.08it/s, test=0.0%, test_loss=30588.467, train=0.0%, train_loss=27958.602]

outcome_architecture/process: 100%|██████████| 2000/2000 [00:26<00:00, 74.62it/s, test=0.0%, test_loss=30588.467, train=0.0%, train_loss=27958.602]

architecture/mode: 100%|██████████| 4/4 [01:13<00:00, 20.99s/it]

architecture/mode: 100%|██████████| 4/4 [01:13<00:00, 18.49s/it]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,outcome,4.272480e+00,0.0,0.0,0.0,4.271962e+00
1,1,process_architecture,outcome,4.212013e+00,0.0,0.0,0.0,4.211770e+00
2,2,process_architecture,outcome,4.124301e+00,0.0,0.0,0.0,4.124247e+00
3,5,process_architecture,outcome,2.994999e+00,0.0,0.0,0.0,2.991761e+00
4,10,process_architecture,outcome,1.763677e+00,0.0,0.0,0.0,1.747903e+00
...,...,...,...,...,...,...,...,...
187,1800,outcome_architecture,process,2.864131e+06,0.0,0.0,0.0,2.864977e+06
188,1850,outcome_architecture,process,3.104428e+05,0.0,0.0,0.0,3.097166e+05
189,1900,outcome_architecture,process,2.285784e+04,0.0,0.0,0.0,2.627040e+04
190,1950,outcome_architecture,process,1.490135e+04,0.0,0.0,0.0,1.705346e+04
191,2000,outcome_architecture,process,2.795860e+04,0.0,0.0,0.0,3.058847e+04

In [13]:

import json as _json, numpy as _np, pandas as _pd
def _clean(df):
    df = df.drop(columns=["circuit_matrix"], errors="ignore").copy()
    return _json.loads(df.to_json(orient="records"))

_payload = {
    "model_seed": MODEL_SEED,
    "steps": STEPS,
    "final_results": _clean(final_results),
    "history": _clean(history),
}
try:
    _payload["history_2x2"] = _clean(history_2x2)
except NameError:
    _payload["history_2x2"] = None

with open(_OUT_JSON, "w") as _f:
    _json.dump(_payload, _f, indent=2)
print("WROTE", _OUT_JSON)

WROTE /home/hariguru/aayus/trace/results/reachability_seeds/seed_46.json