
# Hand-coded solution reachability: train exactly two models

This notebook answers one precise question:

> The PROCESS and OUTCOME hand-coded Transformers already achieve 100% accuracy.  
> If we keep **each exact hand-coded architecture**, randomize its weights, and train it with its natural supervision, does gradient descent recover a 100%-accurate solution?

We train exactly **two models**:

| Trainable model | Architecture | Training target |
|---|---|---|
| `process_random_base` | exact `HandcodedProcessTransformer` layout | PROCESS / trace continuation |
| `outcome_random_base` | exact `HandcodedOutcomeTransformer` layout | OUTCOME-only continuation |

The two fixed hand-coded models are **references only** and are never optimized.

So the experiment is

\[
\boxed{
\text{2 fixed 100\% references}
+
\text{2 randomly initialized trainable models}
}
\]

with only the latter two undergoing gradient updates.

This is a **reachability experiment**, not yet an architecture-matched causal comparison between PROCESS and OUTCOME.


## 1. Imports and configuration

This notebook uses `handcoded_utils.py`, which contains the exact circuit generator, tokenizer, hand-coded architectures, training loop, and free-running evaluator.

In [1]:

import copy
import importlib
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

import handcoded_utils
importlib.reload(handcoded_utils)

from handcoded_utils import (
    BATCH_SIZE,
    BATCH_SEED,
    DATA_SEED,
    DEPTH,
    LR,
    MODEL_SEED,
    TEST_SEED,
    TEST_SIZE,
    TRAIN_SIZE,
    HandcodedOutcomeTransformer,
    HandcodedProcessTransformer,
    encode_dataset,
    free_run_metrics,
    generate,
    language_model_loss,
    make_batch_schedule,
    make_checkpoints,
    make_circuit_prompts,
    make_circuits,
    make_generation_evaluation,
    make_random_trainable_copy,
    make_tokenizer,
    train_one_model,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Main experiment settings.
N_TRAIN = TRAIN_SIZE
N_TEST = TEST_SIZE
STEPS = 2_000
LOSS_EVAL_SIZE = 64
CHECKPOINTS = make_checkpoints(STEPS, animation_checkpoints=40)

print("device:", DEVICE)
print("depth:", DEPTH)
print("train examples:", N_TRAIN)
print("test examples:", N_TEST)
print("steps:", STEPS)
print("loss eval examples:", LOSS_EVAL_SIZE)

device: cuda
depth: 4
train examples: 20000
test examples: 1000
steps: 2000
loss eval examples: 64

/home/hariguru/aayus/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# injected by run_seeds.py -- vary model init only
MODEL_SEED = 44
_OUT_JSON = '/home/hariguru/aayus/trace/results/reachability_seeds/seed_44.json'
print('MODEL_SEED =', MODEL_SEED)

MODEL_SEED = 44


## 2. Build the same dataset for both models

A circuit is

$$
s_t=\Phi(s_{t-1},g_t),\qquad t=1,\ldots,D.
$$

Both models receive the same prompt

```text
S0 g1 g2 ... gD <SEP>
```

but their supervised continuations differ.

PROCESS:

```text
g1 S1 g2 S2 ... gD SD <COLON> SD <EOS>
```

OUTCOME:

```text
<COLON> SD <EOS>
```

The underlying circuits, train/test split, and minibatch schedule are shared.

In [3]:

tokenizer = make_tokenizer()

train_circuits = make_circuits(N_TRAIN, DATA_SEED, DEPTH)
test_circuits = make_circuits(N_TEST, TEST_SEED, DEPTH)
example = test_circuits[0]

training_data = {
    mode: encode_dataset(train_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

# Held-out teacher-forced loss uses the test split. The training helper samples
# a deterministic prefix of this batch at checkpoints for speed.
test_loss_data = {
    mode: encode_dataset(test_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

batch_schedule = make_batch_schedule(
    N_TRAIN, STEPS, BATCH_SIZE, BATCH_SEED
)

train_eval = make_generation_evaluation(
    train_circuits[:min(300, len(train_circuits))],
    tokenizer,
    DEVICE,
)

test_eval = make_generation_evaluation(
    test_circuits,
    tokenizer,
    DEVICE,
)

circuit_prompts = make_circuit_prompts(
    example.gates,
    tokenizer,
    DEVICE,
)

print("Prompt :", tokenizer.decode(tokenizer.prompt(example)))
print("PROCESS:", tokenizer.decode(tokenizer.continuation(example, "process")))
print("OUTCOME:", tokenizer.decode(tokenizer.continuation(example, "outcome")))

Prompt : S1011 s02 c31 c31 t302 <SEP>
PROCESS: s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>
OUTCOME: <COLON> S1001 <EOS>


## 3. Fixed hand-coded references

These two models encode perfect algorithms directly in their weights.

### PROCESS reference

`HandcodedProcessTransformer`

- one causal attention/MLP block,
- four fixed attention heads,
- one ReLU unit for each `(state, gate)` pair,
- autoregressive reuse of the same block to emit intermediate states.

### OUTCOME reference

`HandcodedOutcomeTransformer`

- one causal attention/MLP block per circuit step,
- two attention heads per block,
- intermediate states remain internal to the residual stream,
- only the final answer is emitted.

They are not trained below. They establish that a 100% solution exists in each architecture class.

In [4]:

process_reference = HandcodedProcessTransformer(
    tokenizer, DEPTH
).to(DEVICE)

outcome_reference = HandcodedOutcomeTransformer(
    tokenizer, DEPTH
).to(DEVICE)

reference_rows = []

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    reference_rows.append({
        "model": name,
        "mode": mode,
        "answer_accuracy": metrics["final_answer"],
        "exact_continuation": metrics["exact_continuation"],
    })

pd.DataFrame(reference_rows)

           model     mode  answer_accuracy  exact_continuation
0  Fixed PROCESS  process              1.0                 1.0
1  Fixed OUTCOME  outcome              1.0                 1.0


Expected result:

$$
\operatorname{Acc}(\theta^\star_{\rm P})
=
\operatorname{Acc}(\theta^\star_{\rm O})
=
100\%.
$$

That is the realizability baseline.


## 4. Turn each exact hand-coded architecture into a random trainable model

This is the crucial correction.

We do **not** call `build_random_learned_model()`. That would create an unrelated ordinary one-layer Transformer.

Instead, `make_random_trainable_copy()`:

1. deep-copies the exact hand-coded model,
2. converts its stored weight buffers into `nn.Parameter`s,
3. randomly initializes those tensors.

Therefore the computational graph and tensor layout are inherited directly from the corresponding constructive model.

In [5]:

process_random_base = make_random_trainable_copy(
    process_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

outcome_random_base = make_random_trainable_copy(
    outcome_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

def trainable_params(model):
    return sum(p.numel() for p in model.parameters())

def stored_scalars(model):
    return sum(t.numel() for t in model.state_dict().values())

summary = pd.DataFrame([
    {
        "model": "Fixed PROCESS reference",
        "trainable_parameters": trainable_params(process_reference),
        "stored_scalars": stored_scalars(process_reference),
        "max_length": process_reference.max_length,
    },
    {
        "model": "Random trainable PROCESS architecture",
        "trainable_parameters": trainable_params(process_random_base),
        "stored_scalars": stored_scalars(process_random_base),
        "max_length": process_random_base.max_length,
    },
    {
        "model": "Fixed OUTCOME reference",
        "trainable_parameters": trainable_params(outcome_reference),
        "stored_scalars": stored_scalars(outcome_reference),
        "max_length": outcome_reference.max_length,
    },
    {
        "model": "Random trainable OUTCOME architecture",
        "trainable_parameters": trainable_params(outcome_random_base),
        "stored_scalars": stored_scalars(outcome_random_base),
        "max_length": outcome_random_base.max_length,
    },
])

summary

,model,trainable_parameters,stored_scalars,max_length
0,Fixed PROCESS reference,0,441664,16
1,Random trainable PROCESS architecture,441664,441664,16
2,Fixed OUTCOME reference,0,3588000,8
3,Random trainable OUTCOME architecture,3588000,3588000,8


A fixed reference reports zero **trainable** parameters because its constructed weights are registered as buffers. That does not mean it has zero weights. `stored_scalars` is the more relevant size diagnostic for the fixed models.


## 5. Sanity check: the trainable parameterization really contains the oracle

A useful stronger check is to convert the fixed buffers into trainable parameters **without changing their values**.

If the resulting model produces exactly the same logits as the fixed model, then the hand-coded optimum literally lies inside the trainable parameterization.

In [6]:

def make_trainable_oracle_copy(model, device):
    trainable = copy.deepcopy(model).cpu()

    def convert(module):
        for name, buffer in list(module._buffers.items()):
            if buffer is None:
                continue
            value = buffer.detach().clone()
            del module._buffers[name]
            module.register_parameter(name, torch.nn.Parameter(value))
        for child in module.children():
            convert(child)

    convert(trainable)
    return trainable.to(device)


process_oracle_trainable = make_trainable_oracle_copy(
    process_reference, DEVICE
)
outcome_oracle_trainable = make_trainable_oracle_copy(
    outcome_reference, DEVICE
)

prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

with torch.no_grad():
    process_error = (
        process_reference(prompt) - process_oracle_trainable(prompt)
    ).abs().max().item()

    outcome_error = (
        outcome_reference(prompt) - outcome_oracle_trainable(prompt)
    ).abs().max().item()

print("PROCESS max logit difference:", process_error)
print("OUTCOME max logit difference:", outcome_error)

assert process_error == 0.0
assert outcome_error == 0.0

PROCESS max logit difference: 0.0
OUTCOME max logit difference: 0.0


This gives the precise existence statement:

\[
\exists\,\theta^\star_{\rm P}\in\Theta_{\rm P},
\qquad
\exists\,\theta^\star_{\rm O}\in\Theta_{\rm O},
\]

with both achieving perfect execution.

The training experiment now asks whether random initialization reaches either solution class.


## 6. Train exactly two models

There is no `run_experiment(base, modes=("outcome","process"))` here.

That function would train two copies of the **same base architecture**.

Instead we make two explicit calls:

\[
\boxed{
\text{PROCESS architecture}+\text{PROCESS supervision}
}
\]

and

\[
\boxed{
\text{OUTCOME architecture}+\text{OUTCOME supervision}.
}
\]

So exactly two optimization runs occur.

In [7]:

trained_process, process_history = train_one_model(
    process_random_base,
    "process",
    training_data["process"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="process_architecture",
    test_loss_data=test_loss_data["process"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

trained_outcome, outcome_history = train_one_model(
    outcome_random_base,
    "outcome",
    training_data["outcome"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="outcome_architecture",
    test_loss_data=test_loss_data["outcome"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

history = pd.concat(
    [process_history, outcome_history],
    ignore_index=True,
)

display(
    history.drop(columns=["circuit_matrix"], errors="ignore")
)

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.258, train=0.0%, train_loss=4.258]

process_architecture/process:   0%|          | 1/2000 [00:00<05:02,  6.61it/s, test=0.0%, test_loss=4.258, train=0.0%, train_loss=4.258]

process_architecture/process:   0%|          | 1/2000 [00:00<05:02,  6.61it/s, test=0.0%, test_loss=4.232, train=0.0%, train_loss=4.232]

process_architecture/process:   0%|          | 1/2000 [00:00<05:02,  6.61it/s, test=0.0%, test_loss=3.885, train=0.0%, train_loss=3.896]

process_architecture/process:   0%|          | 1/2000 [00:00<05:02,  6.61it/s, test=0.0%, test_loss=3.642, train=0.0%, train_loss=3.660]

process_architecture/process:   0%|          | 10/2000 [00:00<00:46, 42.82it/s, test=0.0%, test_loss=3.642, train=0.0%, train_loss=3.660]

process_architecture/process:   0%|          | 10/2000 [00:00<00:46, 42.82it/s, test=7.5%, test_loss=3.020, train=7.0%, train_loss=3.027]

process_architecture/process:   1%|          | 20/2000 [00:00<00:31, 63.55it/s, test=7.5%, test_loss=3.020, train=7.0%, train_loss=3.027]

process_architecture/process:   1%|          | 20/2000 [00:00<00:31, 63.55it/s, test=6.5%, test_loss=2.801, train=8.7%, train_loss=2.812]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:26, 74.99it/s, test=6.5%, test_loss=2.801, train=8.7%, train_loss=2.812]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:26, 74.99it/s, test=10.0%, test_loss=2.581, train=5.3%, train_loss=2.609]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:19, 97.78it/s, test=10.0%, test_loss=2.581, train=5.3%, train_loss=2.609]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:15, 128.11it/s, test=10.0%, test_loss=2.581, train=5.3%, train_loss=2.609]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:15, 128.11it/s, test=9.2%, test_loss=2.421, train=7.3%, train_loss=2.428]

process_architecture/process:   4%|▍         | 85/2000 [00:00<00:15, 123.92it/s, test=9.2%, test_loss=2.421, train=7.3%, train_loss=2.428]

process_architecture/process:   4%|▍         | 85/2000 [00:00<00:15, 123.92it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   5%|▌         | 100/2000 [00:00<00:15, 122.00it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   6%|▌         | 121/2000 [00:01<00:12, 145.08it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 161.82it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 161.82it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:   8%|▊         | 159/2000 [00:01<00:12, 148.93it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:   9%|▉         | 180/2000 [00:01<00:11, 164.31it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:   9%|▉         | 180/2000 [00:01<00:11, 164.31it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  10%|█         | 200/2000 [00:01<00:11, 153.64it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  11%|█         | 221/2000 [00:01<00:10, 167.21it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  12%|█▏        | 241/2000 [00:01<00:10, 175.76it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  12%|█▏        | 241/2000 [00:01<00:10, 175.76it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  13%|█▎        | 260/2000 [00:01<00:11, 155.04it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  14%|█▍        | 280/2000 [00:02<00:10, 165.04it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  14%|█▍        | 280/2000 [00:02<00:10, 165.04it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  15%|█▌        | 300/2000 [00:02<00:11, 153.17it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  16%|█▌        | 321/2000 [00:02<00:10, 165.80it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  17%|█▋        | 342/2000 [00:02<00:09, 176.11it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  17%|█▋        | 342/2000 [00:02<00:09, 176.11it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  18%|█▊        | 361/2000 [00:02<00:10, 160.79it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  19%|█▉        | 382/2000 [00:02<00:09, 173.41it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  19%|█▉        | 382/2000 [00:02<00:09, 173.41it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  20%|██        | 400/2000 [00:02<00:10, 157.54it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  21%|██        | 421/2000 [00:02<00:09, 169.66it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  22%|██▏       | 442/2000 [00:02<00:08, 179.10it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  22%|██▏       | 442/2000 [00:03<00:08, 179.10it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  23%|██▎       | 461/2000 [00:03<00:09, 162.27it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  24%|██▍       | 482/2000 [00:03<00:08, 173.19it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  24%|██▍       | 482/2000 [00:03<00:08, 173.19it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  25%|██▌       | 500/2000 [00:03<00:09, 157.30it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  26%|██▌       | 521/2000 [00:03<00:08, 169.45it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 542/2000 [00:03<00:08, 179.64it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 542/2000 [00:03<00:08, 179.64it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  28%|██▊       | 561/2000 [00:03<00:08, 162.46it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 582/2000 [00:03<00:08, 173.09it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 582/2000 [00:03<00:08, 173.09it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|███       | 600/2000 [00:03<00:08, 157.48it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  31%|███       | 621/2000 [00:04<00:08, 170.00it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 642/2000 [00:04<00:07, 180.39it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 642/2000 [00:04<00:07, 180.39it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  33%|███▎      | 661/2000 [00:04<00:08, 162.81it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 682/2000 [00:04<00:07, 173.68it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 682/2000 [00:04<00:07, 173.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▌      | 700/2000 [00:04<00:08, 158.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 722/2000 [00:04<00:07, 172.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 743/2000 [00:04<00:06, 181.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 743/2000 [00:04<00:06, 181.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 762/2000 [00:04<00:07, 163.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 782/2000 [00:05<00:07, 172.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 782/2000 [00:05<00:07, 172.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|████      | 800/2000 [00:05<00:07, 157.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 821/2000 [00:05<00:06, 170.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 842/2000 [00:05<00:06, 179.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 842/2000 [00:05<00:06, 179.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  43%|████▎     | 861/2000 [00:05<00:07, 161.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 882/2000 [00:05<00:06, 173.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 882/2000 [00:05<00:06, 173.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 900/2000 [00:05<00:06, 158.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 921/2000 [00:05<00:06, 169.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 942/2000 [00:05<00:05, 179.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 942/2000 [00:06<00:05, 179.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 961/2000 [00:06<00:06, 162.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 982/2000 [00:06<00:05, 174.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 982/2000 [00:06<00:05, 174.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1001/2000 [00:06<00:06, 159.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1022/2000 [00:06<00:05, 170.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1043/2000 [00:06<00:05, 179.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1043/2000 [00:06<00:05, 179.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1062/2000 [00:06<00:05, 162.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1083/2000 [00:06<00:05, 174.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1083/2000 [00:06<00:05, 174.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1102/2000 [00:06<00:05, 159.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1123/2000 [00:07<00:05, 170.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1144/2000 [00:07<00:04, 180.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1144/2000 [00:07<00:04, 180.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1163/2000 [00:07<00:05, 163.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1184/2000 [00:07<00:04, 173.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1184/2000 [00:07<00:04, 173.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1202/2000 [00:07<00:05, 158.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1223/2000 [00:07<00:04, 170.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1244/2000 [00:07<00:04, 180.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1244/2000 [00:07<00:04, 180.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1263/2000 [00:07<00:04, 162.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1284/2000 [00:07<00:04, 173.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1284/2000 [00:08<00:04, 173.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▌   | 1302/2000 [00:08<00:04, 157.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1323/2000 [00:08<00:03, 170.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1344/2000 [00:08<00:03, 180.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1344/2000 [00:08<00:03, 180.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1363/2000 [00:08<00:03, 162.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1384/2000 [00:08<00:03, 173.39it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1384/2000 [00:08<00:03, 173.39it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1402/2000 [00:08<00:03, 157.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████   | 1423/2000 [00:08<00:03, 171.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1444/2000 [00:08<00:03, 180.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1444/2000 [00:09<00:03, 180.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1463/2000 [00:09<00:03, 162.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1484/2000 [00:09<00:02, 174.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1484/2000 [00:09<00:02, 174.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1503/2000 [00:09<00:03, 159.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1523/2000 [00:09<00:02, 167.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1544/2000 [00:09<00:02, 177.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1544/2000 [00:09<00:02, 177.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1563/2000 [00:09<00:02, 156.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1583/2000 [00:09<00:02, 166.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1583/2000 [00:09<00:02, 166.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1601/2000 [00:09<00:02, 148.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1621/2000 [00:10<00:02, 159.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1641/2000 [00:10<00:02, 168.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1641/2000 [00:10<00:02, 168.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1659/2000 [00:10<00:02, 149.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1679/2000 [00:10<00:01, 161.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1699/2000 [00:10<00:01, 169.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1699/2000 [00:10<00:01, 169.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1717/2000 [00:10<00:01, 149.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1737/2000 [00:10<00:01, 160.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1737/2000 [00:10<00:01, 160.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1754/2000 [00:10<00:01, 144.66it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▊ | 1774/2000 [00:11<00:01, 157.03it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1794/2000 [00:11<00:01, 166.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1794/2000 [00:11<00:01, 166.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1812/2000 [00:11<00:01, 148.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1832/2000 [00:11<00:01, 160.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1832/2000 [00:11<00:01, 160.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▎| 1850/2000 [00:11<00:01, 144.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▎| 1870/2000 [00:11<00:00, 157.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1890/2000 [00:11<00:00, 166.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1890/2000 [00:11<00:00, 166.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▌| 1908/2000 [00:11<00:00, 149.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▋| 1928/2000 [00:12<00:00, 160.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1948/2000 [00:12<00:00, 169.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1948/2000 [00:12<00:00, 169.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1966/2000 [00:12<00:00, 150.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1986/2000 [00:12<00:00, 161.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1986/2000 [00:12<00:00, 161.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 159.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.523, train=0.0%, train_loss=3.526]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=13.485, train=0.0%, train_loss=13.464]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:51, 38.67it/s, test=0.0%, test_loss=13.485, train=0.0%, train_loss=13.464]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:51, 38.67it/s, test=0.0%, test_loss=3.629, train=0.0%, train_loss=3.626]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:51, 38.67it/s, test=0.0%, test_loss=1.114, train=0.0%, train_loss=1.113]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:43, 45.73it/s, test=0.0%, test_loss=1.114, train=0.0%, train_loss=1.113]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:43, 45.73it/s, test=2.4%, test_loss=1.308, train=1.7%, train_loss=1.432]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 61.22it/s, test=2.4%, test_loss=1.308, train=1.7%, train_loss=1.432]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 61.22it/s, test=7.2%, test_loss=1.062, train=5.3%, train_loss=1.063]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:30, 63.98it/s, test=7.2%, test_loss=1.062, train=5.3%, train_loss=1.063]

outcome_architecture/outcome:   2%|▏         | 38/2000 [00:00<00:25, 78.33it/s, test=7.2%, test_loss=1.062, train=5.3%, train_loss=1.063]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:22, 87.32it/s, test=7.2%, test_loss=1.062, train=5.3%, train_loss=1.063]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:22, 87.32it/s, test=7.5%, test_loss=0.931, train=3.7%, train_loss=0.938]

outcome_architecture/outcome:   3%|▎         | 58/2000 [00:00<00:23, 82.85it/s, test=7.5%, test_loss=0.931, train=3.7%, train_loss=0.938]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 90.06it/s, test=7.5%, test_loss=0.931, train=3.7%, train_loss=0.938]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 90.06it/s, test=7.0%, test_loss=0.923, train=7.3%, train_loss=0.939]

outcome_architecture/outcome:   4%|▍         | 79/2000 [00:01<00:22, 85.24it/s, test=7.0%, test_loss=0.923, train=7.3%, train_loss=0.939]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:20, 91.58it/s, test=7.0%, test_loss=0.923, train=7.3%, train_loss=0.939]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:20, 91.58it/s, test=11.2%, test_loss=0.903, train=9.3%, train_loss=0.926]

outcome_architecture/outcome:   5%|▌         | 100/2000 [00:01<00:21, 87.08it/s, test=11.2%, test_loss=0.903, train=9.3%, train_loss=0.926]

outcome_architecture/outcome:   6%|▌         | 111/2000 [00:01<00:20, 92.83it/s, test=11.2%, test_loss=0.903, train=9.3%, train_loss=0.926]

outcome_architecture/outcome:   6%|▌         | 122/2000 [00:01<00:19, 96.96it/s, test=11.2%, test_loss=0.903, train=9.3%, train_loss=0.926]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:18, 99.83it/s, test=11.2%, test_loss=0.903, train=9.3%, train_loss=0.926]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 101.67it/s, test=11.2%, test_loss=0.903, train=9.3%, train_loss=0.926]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 101.67it/s, test=11.2%, test_loss=0.907, train=9.3%, train_loss=0.907]

outcome_architecture/outcome:   8%|▊         | 155/2000 [00:01<00:19, 93.91it/s, test=11.2%, test_loss=0.907, train=9.3%, train_loss=0.907]

outcome_architecture/outcome:   8%|▊         | 166/2000 [00:01<00:18, 96.77it/s, test=11.2%, test_loss=0.907, train=9.3%, train_loss=0.907]

outcome_architecture/outcome:   9%|▉         | 177/2000 [00:02<00:18, 99.80it/s, test=11.2%, test_loss=0.907, train=9.3%, train_loss=0.907]

outcome_architecture/outcome:   9%|▉         | 188/2000 [00:02<00:17, 101.84it/s, test=11.2%, test_loss=0.907, train=9.3%, train_loss=0.907]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 103.13it/s, test=11.2%, test_loss=0.907, train=9.3%, train_loss=0.907]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 103.13it/s, test=11.1%, test_loss=0.894, train=8.7%, train_loss=0.894]

outcome_architecture/outcome:  10%|█         | 210/2000 [00:02<00:18, 94.72it/s, test=11.1%, test_loss=0.894, train=8.7%, train_loss=0.894]

outcome_architecture/outcome:  11%|█         | 221/2000 [00:02<00:18, 98.24it/s, test=11.1%, test_loss=0.894, train=8.7%, train_loss=0.894]

outcome_architecture/outcome:  12%|█▏        | 232/2000 [00:02<00:17, 100.81it/s, test=11.1%, test_loss=0.894, train=8.7%, train_loss=0.894]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:17, 102.49it/s, test=11.1%, test_loss=0.894, train=8.7%, train_loss=0.894]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:17, 102.49it/s, test=0.0%, test_loss=6532.897, train=0.0%, train_loss=6802.108]

outcome_architecture/outcome:  13%|█▎        | 254/2000 [00:02<00:18, 94.49it/s, test=0.0%, test_loss=6532.897, train=0.0%, train_loss=6802.108]

outcome_architecture/outcome:  13%|█▎        | 265/2000 [00:02<00:17, 97.88it/s, test=0.0%, test_loss=6532.897, train=0.0%, train_loss=6802.108]

outcome_architecture/outcome:  14%|█▍        | 276/2000 [00:02<00:17, 100.67it/s, test=0.0%, test_loss=6532.897, train=0.0%, train_loss=6802.108]

outcome_architecture/outcome:  14%|█▍        | 287/2000 [00:03<00:16, 102.44it/s, test=0.0%, test_loss=6532.897, train=0.0%, train_loss=6802.108]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 103.87it/s, test=0.0%, test_loss=6532.897, train=0.0%, train_loss=6802.108]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 103.87it/s, test=0.0%, test_loss=305.773, train=0.0%, train_loss=237.767]

outcome_architecture/outcome:  15%|█▌        | 309/2000 [00:03<00:17, 95.22it/s, test=0.0%, test_loss=305.773, train=0.0%, train_loss=237.767]

outcome_architecture/outcome:  16%|█▌        | 320/2000 [00:03<00:17, 98.59it/s, test=0.0%, test_loss=305.773, train=0.0%, train_loss=237.767]

outcome_architecture/outcome:  17%|█▋        | 331/2000 [00:03<00:16, 101.23it/s, test=0.0%, test_loss=305.773, train=0.0%, train_loss=237.767]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:16, 101.20it/s, test=0.0%, test_loss=305.773, train=0.0%, train_loss=237.767]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:16, 101.20it/s, test=0.2%, test_loss=187.956, train=0.0%, train_loss=185.505]

outcome_architecture/outcome:  18%|█▊        | 353/2000 [00:03<00:17, 93.67it/s, test=0.2%, test_loss=187.956, train=0.0%, train_loss=185.505]

outcome_architecture/outcome:  18%|█▊        | 364/2000 [00:03<00:16, 97.18it/s, test=0.2%, test_loss=187.956, train=0.0%, train_loss=185.505]

outcome_architecture/outcome:  19%|█▉        | 375/2000 [00:03<00:16, 100.11it/s, test=0.2%, test_loss=187.956, train=0.0%, train_loss=185.505]

outcome_architecture/outcome:  19%|█▉        | 386/2000 [00:04<00:15, 102.28it/s, test=0.2%, test_loss=187.956, train=0.0%, train_loss=185.505]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 103.78it/s, test=0.2%, test_loss=187.956, train=0.0%, train_loss=185.505]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 103.78it/s, test=2.7%, test_loss=10.311, train=2.0%, train_loss=10.326]

outcome_architecture/outcome:  20%|██        | 408/2000 [00:04<00:16, 95.32it/s, test=2.7%, test_loss=10.311, train=2.0%, train_loss=10.326]

outcome_architecture/outcome:  21%|██        | 419/2000 [00:04<00:16, 98.80it/s, test=2.7%, test_loss=10.311, train=2.0%, train_loss=10.326]

outcome_architecture/outcome:  22%|██▏       | 430/2000 [00:04<00:15, 101.28it/s, test=2.7%, test_loss=10.311, train=2.0%, train_loss=10.326]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 103.13it/s, test=2.7%, test_loss=10.311, train=2.0%, train_loss=10.326]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 103.13it/s, test=2.3%, test_loss=4.718, train=2.7%, train_loss=3.989]

outcome_architecture/outcome:  23%|██▎       | 452/2000 [00:04<00:16, 94.85it/s, test=2.3%, test_loss=4.718, train=2.7%, train_loss=3.989]

outcome_architecture/outcome:  23%|██▎       | 463/2000 [00:04<00:15, 98.32it/s, test=2.3%, test_loss=4.718, train=2.7%, train_loss=3.989]

outcome_architecture/outcome:  24%|██▎       | 474/2000 [00:04<00:15, 100.82it/s, test=2.3%, test_loss=4.718, train=2.7%, train_loss=3.989]

outcome_architecture/outcome:  24%|██▍       | 485/2000 [00:05<00:14, 102.68it/s, test=2.3%, test_loss=4.718, train=2.7%, train_loss=3.989]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 104.13it/s, test=2.3%, test_loss=4.718, train=2.7%, train_loss=3.989]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 104.13it/s, test=3.5%, test_loss=3.725, train=2.7%, train_loss=4.277]

outcome_architecture/outcome:  25%|██▌       | 507/2000 [00:05<00:15, 95.24it/s, test=3.5%, test_loss=3.725, train=2.7%, train_loss=4.277]

outcome_architecture/outcome:  26%|██▌       | 518/2000 [00:05<00:15, 98.29it/s, test=3.5%, test_loss=3.725, train=2.7%, train_loss=4.277]

outcome_architecture/outcome:  26%|██▋       | 529/2000 [00:05<00:14, 100.80it/s, test=3.5%, test_loss=3.725, train=2.7%, train_loss=4.277]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 102.73it/s, test=3.5%, test_loss=3.725, train=2.7%, train_loss=4.277]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 102.73it/s, test=4.6%, test_loss=2.095, train=5.0%, train_loss=2.239]

outcome_architecture/outcome:  28%|██▊       | 551/2000 [00:05<00:15, 94.57it/s, test=4.6%, test_loss=2.095, train=5.0%, train_loss=2.239]

outcome_architecture/outcome:  28%|██▊       | 562/2000 [00:05<00:14, 98.07it/s, test=4.6%, test_loss=2.095, train=5.0%, train_loss=2.239]

outcome_architecture/outcome:  29%|██▊       | 573/2000 [00:05<00:14, 100.58it/s, test=4.6%, test_loss=2.095, train=5.0%, train_loss=2.239]

outcome_architecture/outcome:  29%|██▉       | 584/2000 [00:06<00:13, 102.41it/s, test=4.6%, test_loss=2.095, train=5.0%, train_loss=2.239]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 103.77it/s, test=4.6%, test_loss=2.095, train=5.0%, train_loss=2.239]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 103.77it/s, test=6.2%, test_loss=2.019, train=7.0%, train_loss=2.050]

outcome_architecture/outcome:  30%|███       | 606/2000 [00:06<00:14, 95.12it/s, test=6.2%, test_loss=2.019, train=7.0%, train_loss=2.050]

outcome_architecture/outcome:  31%|███       | 617/2000 [00:06<00:14, 98.47it/s, test=6.2%, test_loss=2.019, train=7.0%, train_loss=2.050]

outcome_architecture/outcome:  31%|███▏      | 628/2000 [00:06<00:13, 101.02it/s, test=6.2%, test_loss=2.019, train=7.0%, train_loss=2.050]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 102.76it/s, test=6.2%, test_loss=2.019, train=7.0%, train_loss=2.050]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 102.76it/s, test=6.9%, test_loss=1.502, train=4.7%, train_loss=1.629]

outcome_architecture/outcome:  32%|███▎      | 650/2000 [00:06<00:14, 94.73it/s, test=6.9%, test_loss=1.502, train=4.7%, train_loss=1.629]

outcome_architecture/outcome:  33%|███▎      | 661/2000 [00:06<00:13, 98.23it/s, test=6.9%, test_loss=1.502, train=4.7%, train_loss=1.629]

outcome_architecture/outcome:  34%|███▎      | 672/2000 [00:06<00:13, 100.76it/s, test=6.9%, test_loss=1.502, train=4.7%, train_loss=1.629]

outcome_architecture/outcome:  34%|███▍      | 683/2000 [00:07<00:12, 102.58it/s, test=6.9%, test_loss=1.502, train=4.7%, train_loss=1.629]

outcome_architecture/outcome:  35%|███▍      | 694/2000 [00:07<00:12, 103.96it/s, test=6.9%, test_loss=1.502, train=4.7%, train_loss=1.629]

outcome_architecture/outcome:  35%|███▍      | 694/2000 [00:07<00:12, 103.96it/s, test=8.2%, test_loss=1.248, train=5.0%, train_loss=1.386]

outcome_architecture/outcome:  35%|███▌      | 705/2000 [00:07<00:13, 95.41it/s, test=8.2%, test_loss=1.248, train=5.0%, train_loss=1.386]

outcome_architecture/outcome:  36%|███▌      | 716/2000 [00:07<00:13, 98.76it/s, test=8.2%, test_loss=1.248, train=5.0%, train_loss=1.386]

outcome_architecture/outcome:  36%|███▋      | 727/2000 [00:07<00:12, 101.06it/s, test=8.2%, test_loss=1.248, train=5.0%, train_loss=1.386]

outcome_architecture/outcome:  37%|███▋      | 738/2000 [00:07<00:12, 102.76it/s, test=8.2%, test_loss=1.248, train=5.0%, train_loss=1.386]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:07<00:12, 104.15it/s, test=8.2%, test_loss=1.248, train=5.0%, train_loss=1.386]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:07<00:12, 104.15it/s, test=6.4%, test_loss=1.436, train=4.7%, train_loss=1.367]

outcome_architecture/outcome:  38%|███▊      | 760/2000 [00:07<00:12, 95.41it/s, test=6.4%, test_loss=1.436, train=4.7%, train_loss=1.367]

outcome_architecture/outcome:  39%|███▊      | 771/2000 [00:07<00:12, 98.60it/s, test=6.4%, test_loss=1.436, train=4.7%, train_loss=1.367]

outcome_architecture/outcome:  39%|███▉      | 782/2000 [00:08<00:12, 101.03it/s, test=6.4%, test_loss=1.436, train=4.7%, train_loss=1.367]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:11, 103.06it/s, test=6.4%, test_loss=1.436, train=4.7%, train_loss=1.367]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:11, 103.06it/s, test=10.0%, test_loss=1.227, train=8.7%, train_loss=1.346]

outcome_architecture/outcome:  40%|████      | 804/2000 [00:08<00:12, 94.01it/s, test=10.0%, test_loss=1.227, train=8.7%, train_loss=1.346]

outcome_architecture/outcome:  41%|████      | 815/2000 [00:08<00:12, 96.35it/s, test=10.0%, test_loss=1.227, train=8.7%, train_loss=1.346]

outcome_architecture/outcome:  41%|████▏     | 826/2000 [00:08<00:11, 97.84it/s, test=10.0%, test_loss=1.227, train=8.7%, train_loss=1.346]

outcome_architecture/outcome:  42%|████▏     | 837/2000 [00:08<00:11, 99.28it/s, test=10.0%, test_loss=1.227, train=8.7%, train_loss=1.346]

outcome_architecture/outcome:  42%|████▏     | 848/2000 [00:08<00:11, 100.07it/s, test=10.0%, test_loss=1.227, train=8.7%, train_loss=1.346]

outcome_architecture/outcome:  42%|████▏     | 848/2000 [00:08<00:11, 100.07it/s, test=10.3%, test_loss=1.236, train=7.3%, train_loss=1.354]

outcome_architecture/outcome:  43%|████▎     | 859/2000 [00:08<00:12, 92.13it/s, test=10.3%, test_loss=1.236, train=7.3%, train_loss=1.354]

outcome_architecture/outcome:  44%|████▎     | 870/2000 [00:08<00:11, 94.93it/s, test=10.3%, test_loss=1.236, train=7.3%, train_loss=1.354]

outcome_architecture/outcome:  44%|████▍     | 881/2000 [00:09<00:11, 96.93it/s, test=10.3%, test_loss=1.236, train=7.3%, train_loss=1.354]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:11, 98.53it/s, test=10.3%, test_loss=1.236, train=7.3%, train_loss=1.354]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:11, 98.53it/s, test=11.2%, test_loss=1.099, train=8.3%, train_loss=1.248]

outcome_architecture/outcome:  45%|████▌     | 902/2000 [00:09<00:12, 90.58it/s, test=11.2%, test_loss=1.099, train=8.3%, train_loss=1.248]

outcome_architecture/outcome:  46%|████▌     | 913/2000 [00:09<00:11, 93.84it/s, test=11.2%, test_loss=1.099, train=8.3%, train_loss=1.248]

outcome_architecture/outcome:  46%|████▌     | 924/2000 [00:09<00:11, 96.31it/s, test=11.2%, test_loss=1.099, train=8.3%, train_loss=1.248]

outcome_architecture/outcome:  47%|████▋     | 935/2000 [00:09<00:10, 98.10it/s, test=11.2%, test_loss=1.099, train=8.3%, train_loss=1.248]

outcome_architecture/outcome:  47%|████▋     | 946/2000 [00:09<00:10, 99.40it/s, test=11.2%, test_loss=1.099, train=8.3%, train_loss=1.248]

outcome_architecture/outcome:  47%|████▋     | 946/2000 [00:09<00:10, 99.40it/s, test=11.0%, test_loss=1.060, train=9.0%, train_loss=1.174]

outcome_architecture/outcome:  48%|████▊     | 956/2000 [00:09<00:11, 91.24it/s, test=11.0%, test_loss=1.060, train=9.0%, train_loss=1.174]

outcome_architecture/outcome:  48%|████▊     | 967/2000 [00:10<00:10, 94.34it/s, test=11.0%, test_loss=1.060, train=9.0%, train_loss=1.174]

outcome_architecture/outcome:  49%|████▉     | 978/2000 [00:10<00:10, 96.77it/s, test=11.0%, test_loss=1.060, train=9.0%, train_loss=1.174]

outcome_architecture/outcome:  49%|████▉     | 989/2000 [00:10<00:10, 98.31it/s, test=11.0%, test_loss=1.060, train=9.0%, train_loss=1.174]

outcome_architecture/outcome:  49%|████▉     | 989/2000 [00:10<00:10, 98.31it/s, test=7.8%, test_loss=1.199, train=7.0%, train_loss=1.302]

outcome_architecture/outcome:  50%|█████     | 1000/2000 [00:10<00:11, 90.66it/s, test=7.8%, test_loss=1.199, train=7.0%, train_loss=1.302]

outcome_architecture/outcome:  51%|█████     | 1011/2000 [00:10<00:10, 94.06it/s, test=7.8%, test_loss=1.199, train=7.0%, train_loss=1.302]

outcome_architecture/outcome:  51%|█████     | 1022/2000 [00:10<00:10, 96.24it/s, test=7.8%, test_loss=1.199, train=7.0%, train_loss=1.302]

outcome_architecture/outcome:  52%|█████▏    | 1033/2000 [00:10<00:09, 98.03it/s, test=7.8%, test_loss=1.199, train=7.0%, train_loss=1.302]

outcome_architecture/outcome:  52%|█████▏    | 1044/2000 [00:10<00:09, 99.20it/s, test=7.8%, test_loss=1.199, train=7.0%, train_loss=1.302]

outcome_architecture/outcome:  52%|█████▏    | 1044/2000 [00:10<00:09, 99.20it/s, test=10.3%, test_loss=1.172, train=9.0%, train_loss=1.249]

outcome_architecture/outcome:  53%|█████▎    | 1054/2000 [00:10<00:10, 90.77it/s, test=10.3%, test_loss=1.172, train=9.0%, train_loss=1.249]

outcome_architecture/outcome:  53%|█████▎    | 1065/2000 [00:11<00:09, 93.99it/s, test=10.3%, test_loss=1.172, train=9.0%, train_loss=1.249]

outcome_architecture/outcome:  54%|█████▍    | 1076/2000 [00:11<00:09, 96.70it/s, test=10.3%, test_loss=1.172, train=9.0%, train_loss=1.249]

outcome_architecture/outcome:  54%|█████▍    | 1087/2000 [00:11<00:09, 97.98it/s, test=10.3%, test_loss=1.172, train=9.0%, train_loss=1.249]

outcome_architecture/outcome:  55%|█████▍    | 1098/2000 [00:11<00:09, 99.00it/s, test=10.3%, test_loss=1.172, train=9.0%, train_loss=1.249]

outcome_architecture/outcome:  55%|█████▍    | 1098/2000 [00:11<00:09, 99.00it/s, test=9.7%, test_loss=1.065, train=8.7%, train_loss=1.120]

outcome_architecture/outcome:  55%|█████▌    | 1108/2000 [00:11<00:09, 90.56it/s, test=9.7%, test_loss=1.065, train=8.7%, train_loss=1.120]

outcome_architecture/outcome:  56%|█████▌    | 1119/2000 [00:11<00:09, 93.59it/s, test=9.7%, test_loss=1.065, train=8.7%, train_loss=1.120]

outcome_architecture/outcome:  56%|█████▋    | 1130/2000 [00:11<00:09, 96.27it/s, test=9.7%, test_loss=1.065, train=8.7%, train_loss=1.120]

outcome_architecture/outcome:  57%|█████▋    | 1141/2000 [00:11<00:08, 97.92it/s, test=9.7%, test_loss=1.065, train=8.7%, train_loss=1.120]

outcome_architecture/outcome:  57%|█████▋    | 1141/2000 [00:11<00:08, 97.92it/s, test=8.6%, test_loss=1.052, train=11.0%, train_loss=1.109]

outcome_architecture/outcome:  58%|█████▊    | 1151/2000 [00:11<00:09, 90.72it/s, test=8.6%, test_loss=1.052, train=11.0%, train_loss=1.109]

outcome_architecture/outcome:  58%|█████▊    | 1162/2000 [00:12<00:08, 94.92it/s, test=8.6%, test_loss=1.052, train=11.0%, train_loss=1.109]

outcome_architecture/outcome:  59%|█████▊    | 1173/2000 [00:12<00:08, 97.76it/s, test=8.6%, test_loss=1.052, train=11.0%, train_loss=1.109]

outcome_architecture/outcome:  59%|█████▉    | 1184/2000 [00:12<00:08, 99.96it/s, test=8.6%, test_loss=1.052, train=11.0%, train_loss=1.109]

outcome_architecture/outcome:  60%|█████▉    | 1195/2000 [00:12<00:07, 101.52it/s, test=8.6%, test_loss=1.052, train=11.0%, train_loss=1.109]

outcome_architecture/outcome:  60%|█████▉    | 1195/2000 [00:12<00:07, 101.52it/s, test=10.0%, test_loss=1.066, train=12.3%, train_loss=1.073]

outcome_architecture/outcome:  60%|██████    | 1206/2000 [00:12<00:08, 92.53it/s, test=10.0%, test_loss=1.066, train=12.3%, train_loss=1.073]

outcome_architecture/outcome:  61%|██████    | 1217/2000 [00:12<00:08, 96.16it/s, test=10.0%, test_loss=1.066, train=12.3%, train_loss=1.073]

outcome_architecture/outcome:  61%|██████▏   | 1228/2000 [00:12<00:07, 98.70it/s, test=10.0%, test_loss=1.066, train=12.3%, train_loss=1.073]

outcome_architecture/outcome:  62%|██████▏   | 1239/2000 [00:12<00:07, 100.28it/s, test=10.0%, test_loss=1.066, train=12.3%, train_loss=1.073]

outcome_architecture/outcome:  62%|██████▏   | 1239/2000 [00:12<00:07, 100.28it/s, test=6.3%, test_loss=1.273, train=7.7%, train_loss=1.343]

outcome_architecture/outcome:  62%|██████▎   | 1250/2000 [00:12<00:08, 93.01it/s, test=6.3%, test_loss=1.273, train=7.7%, train_loss=1.343]

outcome_architecture/outcome:  63%|██████▎   | 1261/2000 [00:13<00:07, 96.71it/s, test=6.3%, test_loss=1.273, train=7.7%, train_loss=1.343]

outcome_architecture/outcome:  64%|██████▎   | 1272/2000 [00:13<00:07, 99.37it/s, test=6.3%, test_loss=1.273, train=7.7%, train_loss=1.343]

outcome_architecture/outcome:  64%|██████▍   | 1283/2000 [00:13<00:07, 101.23it/s, test=6.3%, test_loss=1.273, train=7.7%, train_loss=1.343]

outcome_architecture/outcome:  65%|██████▍   | 1294/2000 [00:13<00:06, 102.75it/s, test=6.3%, test_loss=1.273, train=7.7%, train_loss=1.343]

outcome_architecture/outcome:  65%|██████▍   | 1294/2000 [00:13<00:06, 102.75it/s, test=9.9%, test_loss=1.135, train=11.3%, train_loss=1.142]

outcome_architecture/outcome:  65%|██████▌   | 1305/2000 [00:13<00:07, 94.28it/s, test=9.9%, test_loss=1.135, train=11.3%, train_loss=1.142]

outcome_architecture/outcome:  66%|██████▌   | 1316/2000 [00:13<00:06, 97.72it/s, test=9.9%, test_loss=1.135, train=11.3%, train_loss=1.142]

outcome_architecture/outcome:  66%|██████▋   | 1327/2000 [00:13<00:06, 100.06it/s, test=9.9%, test_loss=1.135, train=11.3%, train_loss=1.142]

outcome_architecture/outcome:  67%|██████▋   | 1338/2000 [00:13<00:06, 101.96it/s, test=9.9%, test_loss=1.135, train=11.3%, train_loss=1.142]

outcome_architecture/outcome:  67%|██████▋   | 1349/2000 [00:13<00:06, 103.23it/s, test=9.9%, test_loss=1.135, train=11.3%, train_loss=1.142]

outcome_architecture/outcome:  67%|██████▋   | 1349/2000 [00:13<00:06, 103.23it/s, test=7.2%, test_loss=1.108, train=9.3%, train_loss=1.130]

outcome_architecture/outcome:  68%|██████▊   | 1360/2000 [00:14<00:06, 94.49it/s, test=7.2%, test_loss=1.108, train=9.3%, train_loss=1.130]

outcome_architecture/outcome:  69%|██████▊   | 1371/2000 [00:14<00:06, 97.72it/s, test=7.2%, test_loss=1.108, train=9.3%, train_loss=1.130]

outcome_architecture/outcome:  69%|██████▉   | 1382/2000 [00:14<00:06, 100.19it/s, test=7.2%, test_loss=1.108, train=9.3%, train_loss=1.130]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:14<00:05, 102.11it/s, test=7.2%, test_loss=1.108, train=9.3%, train_loss=1.130]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:14<00:05, 102.11it/s, test=10.4%, test_loss=1.048, train=8.3%, train_loss=1.115]

outcome_architecture/outcome:  70%|███████   | 1404/2000 [00:14<00:06, 93.91it/s, test=10.4%, test_loss=1.048, train=8.3%, train_loss=1.115]

outcome_architecture/outcome:  71%|███████   | 1415/2000 [00:14<00:06, 97.18it/s, test=10.4%, test_loss=1.048, train=8.3%, train_loss=1.115]

outcome_architecture/outcome:  71%|███████▏  | 1426/2000 [00:14<00:05, 99.62it/s, test=10.4%, test_loss=1.048, train=8.3%, train_loss=1.115]

outcome_architecture/outcome:  72%|███████▏  | 1437/2000 [00:14<00:05, 101.64it/s, test=10.4%, test_loss=1.048, train=8.3%, train_loss=1.115]

outcome_architecture/outcome:  72%|███████▏  | 1448/2000 [00:14<00:05, 103.04it/s, test=10.4%, test_loss=1.048, train=8.3%, train_loss=1.115]

outcome_architecture/outcome:  72%|███████▏  | 1448/2000 [00:14<00:05, 103.04it/s, test=9.6%, test_loss=1.014, train=8.3%, train_loss=1.074]

outcome_architecture/outcome:  73%|███████▎  | 1459/2000 [00:15<00:05, 94.16it/s, test=9.6%, test_loss=1.014, train=8.3%, train_loss=1.074]

outcome_architecture/outcome:  74%|███████▎  | 1470/2000 [00:15<00:05, 97.35it/s, test=9.6%, test_loss=1.014, train=8.3%, train_loss=1.074]

outcome_architecture/outcome:  74%|███████▍  | 1481/2000 [00:15<00:05, 99.65it/s, test=9.6%, test_loss=1.014, train=8.3%, train_loss=1.074]

outcome_architecture/outcome:  75%|███████▍  | 1492/2000 [00:15<00:05, 101.43it/s, test=9.6%, test_loss=1.014, train=8.3%, train_loss=1.074]

outcome_architecture/outcome:  75%|███████▍  | 1492/2000 [00:15<00:05, 101.43it/s, test=10.0%, test_loss=1.063, train=9.3%, train_loss=1.082]

outcome_architecture/outcome:  75%|███████▌  | 1503/2000 [00:15<00:05, 93.42it/s, test=10.0%, test_loss=1.063, train=9.3%, train_loss=1.082]

outcome_architecture/outcome:  76%|███████▌  | 1514/2000 [00:15<00:05, 96.66it/s, test=10.0%, test_loss=1.063, train=9.3%, train_loss=1.082]

outcome_architecture/outcome:  76%|███████▋  | 1525/2000 [00:15<00:04, 99.25it/s, test=10.0%, test_loss=1.063, train=9.3%, train_loss=1.082]

outcome_architecture/outcome:  77%|███████▋  | 1536/2000 [00:15<00:04, 100.98it/s, test=10.0%, test_loss=1.063, train=9.3%, train_loss=1.082]

outcome_architecture/outcome:  77%|███████▋  | 1547/2000 [00:15<00:04, 99.47it/s, test=10.0%, test_loss=1.063, train=9.3%, train_loss=1.082]

outcome_architecture/outcome:  77%|███████▋  | 1547/2000 [00:16<00:04, 99.47it/s, test=9.3%, test_loss=1.059, train=9.0%, train_loss=1.104]

outcome_architecture/outcome:  78%|███████▊  | 1558/2000 [00:16<00:04, 90.34it/s, test=9.3%, test_loss=1.059, train=9.0%, train_loss=1.104]

outcome_architecture/outcome:  78%|███████▊  | 1568/2000 [00:16<00:04, 91.80it/s, test=9.3%, test_loss=1.059, train=9.0%, train_loss=1.104]

outcome_architecture/outcome:  79%|███████▉  | 1578/2000 [00:16<00:04, 93.41it/s, test=9.3%, test_loss=1.059, train=9.0%, train_loss=1.104]

outcome_architecture/outcome:  79%|███████▉  | 1588/2000 [00:16<00:04, 94.78it/s, test=9.3%, test_loss=1.059, train=9.0%, train_loss=1.104]

outcome_architecture/outcome:  80%|███████▉  | 1598/2000 [00:16<00:04, 95.94it/s, test=9.3%, test_loss=1.059, train=9.0%, train_loss=1.104]

outcome_architecture/outcome:  80%|███████▉  | 1598/2000 [00:16<00:04, 95.94it/s, test=8.7%, test_loss=1.007, train=7.7%, train_loss=1.021]

outcome_architecture/outcome:  80%|████████  | 1608/2000 [00:16<00:04, 87.82it/s, test=8.7%, test_loss=1.007, train=7.7%, train_loss=1.021]

outcome_architecture/outcome:  81%|████████  | 1618/2000 [00:16<00:04, 90.45it/s, test=8.7%, test_loss=1.007, train=7.7%, train_loss=1.021]

outcome_architecture/outcome:  81%|████████▏ | 1628/2000 [00:16<00:04, 92.18it/s, test=8.7%, test_loss=1.007, train=7.7%, train_loss=1.021]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:16<00:03, 94.50it/s, test=8.7%, test_loss=1.007, train=7.7%, train_loss=1.021]

outcome_architecture/outcome:  82%|████████▏ | 1649/2000 [00:17<00:03, 95.63it/s, test=8.7%, test_loss=1.007, train=7.7%, train_loss=1.021]

outcome_architecture/outcome:  82%|████████▏ | 1649/2000 [00:17<00:03, 95.63it/s, test=9.5%, test_loss=1.032, train=8.7%, train_loss=1.055]

outcome_architecture/outcome:  83%|████████▎ | 1659/2000 [00:17<00:03, 87.62it/s, test=9.5%, test_loss=1.032, train=8.7%, train_loss=1.055]

outcome_architecture/outcome:  83%|████████▎ | 1669/2000 [00:17<00:03, 90.40it/s, test=9.5%, test_loss=1.032, train=8.7%, train_loss=1.055]

outcome_architecture/outcome:  84%|████████▍ | 1679/2000 [00:17<00:03, 92.60it/s, test=9.5%, test_loss=1.032, train=8.7%, train_loss=1.055]

outcome_architecture/outcome:  84%|████████▍ | 1689/2000 [00:17<00:03, 94.46it/s, test=9.5%, test_loss=1.032, train=8.7%, train_loss=1.055]

outcome_architecture/outcome:  85%|████████▍ | 1699/2000 [00:17<00:03, 95.97it/s, test=9.5%, test_loss=1.032, train=8.7%, train_loss=1.055]

outcome_architecture/outcome:  85%|████████▍ | 1699/2000 [00:17<00:03, 95.97it/s, test=8.1%, test_loss=1.044, train=8.3%, train_loss=1.089]

outcome_architecture/outcome:  85%|████████▌ | 1709/2000 [00:17<00:03, 85.93it/s, test=8.1%, test_loss=1.044, train=8.3%, train_loss=1.089]

outcome_architecture/outcome:  86%|████████▌ | 1719/2000 [00:17<00:03, 89.14it/s, test=8.1%, test_loss=1.044, train=8.3%, train_loss=1.089]

outcome_architecture/outcome:  86%|████████▋ | 1729/2000 [00:17<00:02, 92.05it/s, test=8.1%, test_loss=1.044, train=8.3%, train_loss=1.089]

outcome_architecture/outcome:  87%|████████▋ | 1739/2000 [00:18<00:02, 94.05it/s, test=8.1%, test_loss=1.044, train=8.3%, train_loss=1.089]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:18<00:02, 95.24it/s, test=8.1%, test_loss=1.044, train=8.3%, train_loss=1.089]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:18<00:02, 95.24it/s, test=10.2%, test_loss=1.044, train=8.7%, train_loss=1.083]

outcome_architecture/outcome:  88%|████████▊ | 1759/2000 [00:18<00:02, 87.04it/s, test=10.2%, test_loss=1.044, train=8.7%, train_loss=1.083]

outcome_architecture/outcome:  88%|████████▊ | 1769/2000 [00:18<00:02, 89.75it/s, test=10.2%, test_loss=1.044, train=8.7%, train_loss=1.083]

outcome_architecture/outcome:  89%|████████▉ | 1779/2000 [00:18<00:02, 92.16it/s, test=10.2%, test_loss=1.044, train=8.7%, train_loss=1.083]

outcome_architecture/outcome:  89%|████████▉ | 1789/2000 [00:18<00:02, 94.02it/s, test=10.2%, test_loss=1.044, train=8.7%, train_loss=1.083]

outcome_architecture/outcome:  90%|████████▉ | 1799/2000 [00:18<00:02, 95.60it/s, test=10.2%, test_loss=1.044, train=8.7%, train_loss=1.083]

outcome_architecture/outcome:  90%|████████▉ | 1799/2000 [00:18<00:02, 95.60it/s, test=10.9%, test_loss=1.024, train=8.3%, train_loss=1.054]

outcome_architecture/outcome:  90%|█████████ | 1809/2000 [00:18<00:02, 87.69it/s, test=10.9%, test_loss=1.024, train=8.3%, train_loss=1.054]

outcome_architecture/outcome:  91%|█████████ | 1819/2000 [00:18<00:01, 91.05it/s, test=10.9%, test_loss=1.024, train=8.3%, train_loss=1.054]

outcome_architecture/outcome:  91%|█████████▏| 1829/2000 [00:19<00:01, 93.24it/s, test=10.9%, test_loss=1.024, train=8.3%, train_loss=1.054]

outcome_architecture/outcome:  92%|█████████▏| 1839/2000 [00:19<00:01, 94.77it/s, test=10.9%, test_loss=1.024, train=8.3%, train_loss=1.054]

outcome_architecture/outcome:  92%|█████████▏| 1849/2000 [00:19<00:01, 95.84it/s, test=10.9%, test_loss=1.024, train=8.3%, train_loss=1.054]

outcome_architecture/outcome:  92%|█████████▏| 1849/2000 [00:19<00:01, 95.84it/s, test=12.1%, test_loss=0.947, train=10.7%, train_loss=0.992]

outcome_architecture/outcome:  93%|█████████▎| 1859/2000 [00:19<00:01, 87.91it/s, test=12.1%, test_loss=0.947, train=10.7%, train_loss=0.992]

outcome_architecture/outcome:  93%|█████████▎| 1869/2000 [00:19<00:01, 91.12it/s, test=12.1%, test_loss=0.947, train=10.7%, train_loss=0.992]

outcome_architecture/outcome:  94%|█████████▍| 1879/2000 [00:19<00:01, 93.37it/s, test=12.1%, test_loss=0.947, train=10.7%, train_loss=0.992]

outcome_architecture/outcome:  94%|█████████▍| 1889/2000 [00:19<00:01, 94.74it/s, test=12.1%, test_loss=0.947, train=10.7%, train_loss=0.992]

outcome_architecture/outcome:  95%|█████████▍| 1899/2000 [00:19<00:01, 95.60it/s, test=12.1%, test_loss=0.947, train=10.7%, train_loss=0.992]

outcome_architecture/outcome:  95%|█████████▍| 1899/2000 [00:19<00:01, 95.60it/s, test=8.1%, test_loss=1.073, train=8.3%, train_loss=1.130]

outcome_architecture/outcome:  95%|█████████▌| 1909/2000 [00:19<00:01, 87.31it/s, test=8.1%, test_loss=1.073, train=8.3%, train_loss=1.130]

outcome_architecture/outcome:  96%|█████████▌| 1919/2000 [00:20<00:00, 90.16it/s, test=8.1%, test_loss=1.073, train=8.3%, train_loss=1.130]

outcome_architecture/outcome:  96%|█████████▋| 1929/2000 [00:20<00:00, 92.37it/s, test=8.1%, test_loss=1.073, train=8.3%, train_loss=1.130]

outcome_architecture/outcome:  97%|█████████▋| 1939/2000 [00:20<00:00, 93.85it/s, test=8.1%, test_loss=1.073, train=8.3%, train_loss=1.130]

outcome_architecture/outcome:  97%|█████████▋| 1949/2000 [00:20<00:00, 95.48it/s, test=8.1%, test_loss=1.073, train=8.3%, train_loss=1.130]

outcome_architecture/outcome:  97%|█████████▋| 1949/2000 [00:20<00:00, 95.48it/s, test=10.3%, test_loss=0.974, train=9.3%, train_loss=1.038]

outcome_architecture/outcome:  98%|█████████▊| 1959/2000 [00:20<00:00, 87.57it/s, test=10.3%, test_loss=0.974, train=9.3%, train_loss=1.038]

outcome_architecture/outcome:  98%|█████████▊| 1969/2000 [00:20<00:00, 90.52it/s, test=10.3%, test_loss=0.974, train=9.3%, train_loss=1.038]

outcome_architecture/outcome:  99%|█████████▉| 1979/2000 [00:20<00:00, 92.73it/s, test=10.3%, test_loss=0.974, train=9.3%, train_loss=1.038]

outcome_architecture/outcome:  99%|█████████▉| 1989/2000 [00:20<00:00, 94.36it/s, test=10.3%, test_loss=0.974, train=9.3%, train_loss=1.038]

outcome_architecture/outcome: 100%|█████████▉| 1999/2000 [00:20<00:00, 95.47it/s, test=10.3%, test_loss=0.974, train=9.3%, train_loss=1.038]

outcome_architecture/outcome: 100%|█████████▉| 1999/2000 [00:20<00:00, 95.47it/s, test=11.4%, test_loss=0.972, train=12.3%, train_loss=1.040]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:20<00:00, 95.58it/s, test=11.4%, test_loss=0.972, train=12.3%, train_loss=1.040]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,process,4.275183,0.000000,0.000,0.000,4.275544
1,1,process_architecture,process,4.258227,0.000000,0.000,0.000,4.258392
2,2,process_architecture,process,4.232203,0.000000,0.000,0.000,4.231857
3,5,process_architecture,process,3.895732,0.000000,0.000,0.000,3.884660
4,10,process_architecture,process,3.660068,0.000000,0.000,0.000,3.641936
...,...,...,...,...,...,...,...,...
91,1800,outcome_architecture,outcome,1.054410,0.083333,0.109,0.109,1.023786
92,1850,outcome_architecture,outcome,0.992265,0.106667,0.121,0.121,0.946928
93,1900,outcome_architecture,outcome,1.130156,0.083333,0.081,0.081,1.072578
94,1950,outcome_architecture,outcome,1.037937,0.093333,0.103,0.103,0.974400
95,2000,outcome_architecture,outcome,1.039695,0.123333,0.114,0.114,0.972050


## 7. Final behavioral comparison

The four displayed rows are:

- two fixed references,
- two trained models.

But only the latter two were optimized.

In [8]:

rows = []

for name, model, mode, trained in [
    ("Fixed PROCESS reference", process_reference, "process", False),
    ("Trained PROCESS architecture", trained_process, "process", True),
    ("Fixed OUTCOME reference", outcome_reference, "outcome", False),
    ("Trained OUTCOME architecture", trained_outcome, "outcome", True),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    rows.append({
        "model": name,
        "optimized": trained,
        "mode": mode,
        "test_answer_accuracy": metrics["final_answer"],
        "test_exact_continuation": metrics["exact_continuation"],
    })

final_results = pd.DataFrame(rows)
final_results

,model,optimized,mode,test_answer_accuracy,test_exact_continuation
0,Fixed PROCESS reference,False,process,1.000,1.000
1,Trained PROCESS architecture,True,process,1.000,1.000
2,Fixed OUTCOME reference,False,outcome,1.000,1.000
3,Trained OUTCOME architecture,True,outcome,0.114,0.114

## 8. Learning curves

The first plot tracks free-running answer accuracy. The second plot tracks teacher-forced training and held-out test loss at the same checkpoints.

In [9]:

fig, ax = plt.subplots(figsize=(8, 4.5))

for (architecture, mode), frame in history.groupby(["architecture", "mode"]):
    ax.plot(
        frame["step"],
        frame["test_answer_accuracy"],
        marker="o",
        label=f"{architecture} / {mode}",
    )

ax.axhline(1.0, linestyle="--", label="constructive solution = 100%")
ax.axhline(1 / tokenizer.n_states, linestyle=":", label="chance")
ax.set_xlabel("optimization step")
ax.set_ylabel("free-running test answer accuracy")
ax.set_ylim(-0.02, 1.03)
ax.legend()
plt.show()

In [10]:
def plot_train_test_loss(history, *, steps=STEPS):
    required = {"architecture", "mode", "step", "train_loss", "test_loss"}
    missing = required.difference(history.columns)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"history is missing required columns: {missing_text}")

    fig, ax = plt.subplots(figsize=(9, 5))
    styles = {
        ("process_architecture", "process"): {
            "color": "#2ca02c",
            "label": "PROCESS architecture / process",
        },
        ("outcome_architecture", "outcome"): {
            "color": "#d62728",
            "label": "OUTCOME architecture / outcome",
        },
    }

    for key, frame in history.sort_values("step").groupby(["architecture", "mode"]):
        style = styles.get(key, {"color": None, "label": " / ".join(map(str, key))})
        ax.plot(
            frame["step"],
            frame["train_loss"],
            color=style["color"],
            linewidth=2.2,
            label=f"{style['label']} train",
        )
        ax.plot(
            frame["step"],
            frame["test_loss"],
            color=style["color"],
            linestyle="--",
            linewidth=2.2,
            label=f"{style['label']} test",
        )

    ax.set_xlabel("Iteration", fontsize=13)
    ax.set_ylabel("Teacher-forced loss", fontsize=13)
    ax.set_xlim(0, steps)
    ax.grid(True, alpha=0.35)
    ax.legend(frameon=True, fontsize=10)
    fig.tight_layout()
    return fig, ax

plot_train_test_loss(history)
plt.show()


## 9. Inspect one free-running example

No gold continuation is fed to the model during this evaluation.

In [11]:

example_prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Trained PROCESS", trained_process, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
    ("Trained OUTCOME", trained_outcome, "outcome"),
]:
    budget = 3 if mode == "outcome" else 2 * DEPTH + 3
    generated = generate(
        model,
        example_prompt,
        budget,
        tokenizer.eos,
    )
    continuation = generated[0, example_prompt.shape[1]:]
    print(f"\n{name}")
    print(tokenizer.decode(continuation))

Fixed PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Trained PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Fixed OUTCOME
<COLON> S1001 <EOS>

Trained OUTCOME
<COLON> S1001 <EOS>


## 10. How to interpret the result

There are four broad possibilities.

### Both trained models reach 100%

The two constructive solution classes are readily reachable from this initialization and optimizer.

### PROCESS reaches 100%, OUTCOME does not

Then

\[
\exists\theta^\star_{\rm O}:\operatorname{Err}(\theta^\star_{\rm O})=0
\]

but the tested terminal-supervision optimization trajectory does not discover it.

That is evidence for a **trainability / accessibility gap**, not an expressivity gap.

### OUTCOME reaches 100%, PROCESS does not

Then the existence of an explicit local process circuit does not by itself guarantee that ordinary trace training discovers it.

### Neither reaches 100%

Then constructive realizability and optimization reachability are substantially different for both architectures.

---

Do not infer an impossibility theorem from a failed run. Multiple seeds, learning-rate controls, and optimizer-stability diagnostics are needed before making a strong optimization claim.


# Optional appendix: full $2\times2$ architecture × supervision experiment

The primary notebook above trains exactly **two** models.

A separate, stronger control can cross:

\[
\{\text{PROCESS architecture},\text{OUTCOME architecture}\}
\times
\{\text{PROCESS supervision},\text{OUTCOME supervision}\}.
\]

That experiment trains **four** models and should be reported separately.

It requires the OUTCOME architecture to use the longer PROCESS position budget, so it is intentionally not the exact diagonal reachability experiment above.

In [12]:
RUN_OPTIONAL_2X2 = True

if RUN_OPTIONAL_2X2:
    from handcoded_utils import (
        build_random_trainable_outcome_architecture,
        build_random_trainable_process_architecture,
        run_architecture_experiment,
    )

    bases = {
        "process_architecture": build_random_trainable_process_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
        "outcome_architecture": build_random_trainable_outcome_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
    }

    models_2x2, history_2x2 = run_architecture_experiment(
        bases,
        training_data,
        batch_schedule,
        LR,
        CHECKPOINTS,
        train_eval,
        test_eval,
        tokenizer,
        circuit_prompts,
        test_loss_data=test_loss_data,
        loss_eval_size=LOSS_EVAL_SIZE,
    )

    display(history_2x2.drop(columns=["circuit_matrix"], errors="ignore"))
else:
    print("Skipping optional 2x2 experiment. Set RUN_OPTIONAL_2X2 = True to run it.")

architecture/mode:   0%|          | 0/4 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.225, train=0.0%, train_loss=4.225]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.145, train=0.0%, train_loss=4.145]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:03, 10.87it/s, test=0.0%, test_loss=4.145, train=0.0%, train_loss=4.145]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:03, 10.87it/s, test=0.0%, test_loss=3.069, train=0.0%, train_loss=3.075]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:03, 10.87it/s, test=0.0%, test_loss=1.782, train=0.0%, train_loss=1.805]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:31, 62.05it/s, test=0.0%, test_loss=1.782, train=0.0%, train_loss=1.805]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:31, 62.05it/s, test=0.0%, test_loss=1.175, train=0.0%, train_loss=1.172]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:31, 62.05it/s, test=0.0%, test_loss=1.106, train=0.0%, train_loss=1.105]

process_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:23, 83.03it/s, test=0.0%, test_loss=1.106, train=0.0%, train_loss=1.105]

process_architecture/outcome:   2%|▏         | 45/2000 [00:00<00:16, 115.70it/s, test=0.0%, test_loss=1.106, train=0.0%, train_loss=1.105]

process_architecture/outcome:   2%|▏         | 45/2000 [00:00<00:16, 115.70it/s, test=7.2%, test_loss=0.920, train=6.0%, train_loss=0.933]

process_architecture/outcome:   3%|▎         | 60/2000 [00:00<00:15, 126.24it/s, test=7.2%, test_loss=0.920, train=6.0%, train_loss=0.933]

process_architecture/outcome:   3%|▎         | 60/2000 [00:00<00:15, 126.24it/s, test=7.5%, test_loss=0.936, train=7.0%, train_loss=0.946]

process_architecture/outcome:   4%|▍         | 75/2000 [00:00<00:14, 133.68it/s, test=7.5%, test_loss=0.936, train=7.0%, train_loss=0.946]

process_architecture/outcome:   5%|▍         | 94/2000 [00:00<00:12, 149.15it/s, test=7.5%, test_loss=0.936, train=7.0%, train_loss=0.946]

process_architecture/outcome:   5%|▍         | 94/2000 [00:00<00:12, 149.15it/s, test=8.6%, test_loss=0.926, train=8.3%, train_loss=0.940]

process_architecture/outcome:   6%|▌         | 110/2000 [00:00<00:12, 148.22it/s, test=8.6%, test_loss=0.926, train=8.3%, train_loss=0.940]

process_architecture/outcome:   6%|▋         | 128/2000 [00:01<00:11, 157.48it/s, test=8.6%, test_loss=0.926, train=8.3%, train_loss=0.940]

process_architecture/outcome:   7%|▋         | 146/2000 [00:01<00:11, 163.82it/s, test=8.6%, test_loss=0.926, train=8.3%, train_loss=0.940]

process_architecture/outcome:   7%|▋         | 146/2000 [00:01<00:11, 163.82it/s, test=10.3%, test_loss=0.902, train=7.7%, train_loss=0.899]

process_architecture/outcome:   8%|▊         | 163/2000 [00:01<00:11, 162.78it/s, test=10.3%, test_loss=0.902, train=7.7%, train_loss=0.899]

process_architecture/outcome:   9%|▉         | 184/2000 [00:01<00:10, 174.90it/s, test=10.3%, test_loss=0.902, train=7.7%, train_loss=0.899]

process_architecture/outcome:   9%|▉         | 184/2000 [00:01<00:10, 174.90it/s, test=10.5%, test_loss=0.902, train=12.0%, train_loss=0.898]

process_architecture/outcome:  10%|█         | 202/2000 [00:01<00:10, 172.53it/s, test=10.5%, test_loss=0.902, train=12.0%, train_loss=0.898]

process_architecture/outcome:  11%|█         | 222/2000 [00:01<00:09, 179.96it/s, test=10.5%, test_loss=0.902, train=12.0%, train_loss=0.898]

process_architecture/outcome:  12%|█▏        | 243/2000 [00:01<00:09, 186.02it/s, test=10.5%, test_loss=0.902, train=12.0%, train_loss=0.898]

process_architecture/outcome:  12%|█▏        | 243/2000 [00:01<00:09, 186.02it/s, test=10.0%, test_loss=0.883, train=8.3%, train_loss=0.872]

process_architecture/outcome:  13%|█▎        | 262/2000 [00:01<00:09, 180.92it/s, test=10.0%, test_loss=0.883, train=8.3%, train_loss=0.872]

process_architecture/outcome:  14%|█▍        | 283/2000 [00:01<00:09, 187.65it/s, test=10.0%, test_loss=0.883, train=8.3%, train_loss=0.872]

process_architecture/outcome:  14%|█▍        | 283/2000 [00:01<00:09, 187.65it/s, test=11.6%, test_loss=0.879, train=9.3%, train_loss=0.876]

process_architecture/outcome:  15%|█▌        | 302/2000 [00:01<00:09, 183.29it/s, test=11.6%, test_loss=0.879, train=9.3%, train_loss=0.876]

process_architecture/outcome:  16%|█▌        | 322/2000 [00:02<00:08, 187.83it/s, test=11.6%, test_loss=0.879, train=9.3%, train_loss=0.876]

process_architecture/outcome:  17%|█▋        | 343/2000 [00:02<00:08, 192.02it/s, test=11.6%, test_loss=0.879, train=9.3%, train_loss=0.876]

process_architecture/outcome:  17%|█▋        | 343/2000 [00:02<00:08, 192.02it/s, test=11.8%, test_loss=0.870, train=11.0%, train_loss=0.889]

process_architecture/outcome:  18%|█▊        | 363/2000 [00:02<00:08, 185.21it/s, test=11.8%, test_loss=0.870, train=11.0%, train_loss=0.889]

process_architecture/outcome:  19%|█▉        | 384/2000 [00:02<00:08, 190.26it/s, test=11.8%, test_loss=0.870, train=11.0%, train_loss=0.889]

process_architecture/outcome:  19%|█▉        | 384/2000 [00:02<00:08, 190.26it/s, test=12.4%, test_loss=0.864, train=12.7%, train_loss=0.886]

process_architecture/outcome:  20%|██        | 404/2000 [00:02<00:08, 185.02it/s, test=12.4%, test_loss=0.864, train=12.7%, train_loss=0.886]

process_architecture/outcome:  21%|██        | 424/2000 [00:02<00:08, 189.23it/s, test=12.4%, test_loss=0.864, train=12.7%, train_loss=0.886]

process_architecture/outcome:  22%|██▏       | 445/2000 [00:02<00:08, 192.74it/s, test=12.4%, test_loss=0.864, train=12.7%, train_loss=0.886]

process_architecture/outcome:  22%|██▏       | 445/2000 [00:02<00:08, 192.74it/s, test=12.3%, test_loss=0.855, train=11.3%, train_loss=0.853]

process_architecture/outcome:  23%|██▎       | 465/2000 [00:02<00:08, 186.52it/s, test=12.3%, test_loss=0.855, train=11.3%, train_loss=0.853]

process_architecture/outcome:  24%|██▍       | 486/2000 [00:02<00:07, 191.34it/s, test=12.3%, test_loss=0.855, train=11.3%, train_loss=0.853]

process_architecture/outcome:  24%|██▍       | 486/2000 [00:03<00:07, 191.34it/s, test=14.0%, test_loss=0.850, train=12.0%, train_loss=0.861]

process_architecture/outcome:  25%|██▌       | 506/2000 [00:03<00:08, 185.45it/s, test=14.0%, test_loss=0.850, train=12.0%, train_loss=0.861]

process_architecture/outcome:  26%|██▋       | 526/2000 [00:03<00:07, 189.43it/s, test=14.0%, test_loss=0.850, train=12.0%, train_loss=0.861]

process_architecture/outcome:  27%|██▋       | 546/2000 [00:03<00:07, 190.14it/s, test=14.0%, test_loss=0.850, train=12.0%, train_loss=0.861]

process_architecture/outcome:  27%|██▋       | 546/2000 [00:03<00:07, 190.14it/s, test=13.9%, test_loss=0.867, train=11.7%, train_loss=0.840]

process_architecture/outcome:  28%|██▊       | 566/2000 [00:03<00:07, 184.08it/s, test=13.9%, test_loss=0.867, train=11.7%, train_loss=0.840]

process_architecture/outcome:  29%|██▉       | 587/2000 [00:03<00:07, 189.60it/s, test=13.9%, test_loss=0.867, train=11.7%, train_loss=0.840]

process_architecture/outcome:  29%|██▉       | 587/2000 [00:03<00:07, 189.60it/s, test=15.0%, test_loss=0.859, train=12.7%, train_loss=0.834]

process_architecture/outcome:  30%|███       | 607/2000 [00:03<00:07, 183.30it/s, test=15.0%, test_loss=0.859, train=12.7%, train_loss=0.834]

process_architecture/outcome:  31%|███▏      | 627/2000 [00:03<00:07, 187.96it/s, test=15.0%, test_loss=0.859, train=12.7%, train_loss=0.834]

process_architecture/outcome:  32%|███▏      | 648/2000 [00:03<00:07, 192.01it/s, test=15.0%, test_loss=0.859, train=12.7%, train_loss=0.834]

process_architecture/outcome:  32%|███▏      | 648/2000 [00:03<00:07, 192.01it/s, test=9.1%, test_loss=0.944, train=7.7%, train_loss=0.950]

process_architecture/outcome:  33%|███▎      | 668/2000 [00:03<00:07, 185.79it/s, test=9.1%, test_loss=0.944, train=7.7%, train_loss=0.950]

process_architecture/outcome:  34%|███▍      | 689/2000 [00:04<00:06, 190.77it/s, test=9.1%, test_loss=0.944, train=7.7%, train_loss=0.950]

process_architecture/outcome:  34%|███▍      | 689/2000 [00:04<00:06, 190.77it/s, test=10.6%, test_loss=0.923, train=9.3%, train_loss=0.904]

process_architecture/outcome:  35%|███▌      | 709/2000 [00:04<00:07, 183.70it/s, test=10.6%, test_loss=0.923, train=9.3%, train_loss=0.904]

process_architecture/outcome:  36%|███▋      | 730/2000 [00:04<00:06, 188.80it/s, test=10.6%, test_loss=0.923, train=9.3%, train_loss=0.904]

process_architecture/outcome:  36%|███▋      | 730/2000 [00:04<00:06, 188.80it/s, test=13.2%, test_loss=0.887, train=11.7%, train_loss=0.894]

process_architecture/outcome:  38%|███▊      | 750/2000 [00:04<00:06, 183.59it/s, test=13.2%, test_loss=0.887, train=11.7%, train_loss=0.894]

process_architecture/outcome:  39%|███▊      | 771/2000 [00:04<00:06, 188.93it/s, test=13.2%, test_loss=0.887, train=11.7%, train_loss=0.894]

process_architecture/outcome:  40%|███▉      | 792/2000 [00:04<00:06, 192.96it/s, test=13.2%, test_loss=0.887, train=11.7%, train_loss=0.894]

process_architecture/outcome:  40%|███▉      | 792/2000 [00:04<00:06, 192.96it/s, test=11.4%, test_loss=0.885, train=12.3%, train_loss=0.909]

process_architecture/outcome:  41%|████      | 812/2000 [00:04<00:06, 185.92it/s, test=11.4%, test_loss=0.885, train=12.3%, train_loss=0.909]

process_architecture/outcome:  42%|████▏     | 833/2000 [00:04<00:06, 190.34it/s, test=11.4%, test_loss=0.885, train=12.3%, train_loss=0.909]

process_architecture/outcome:  42%|████▏     | 833/2000 [00:04<00:06, 190.34it/s, test=14.2%, test_loss=0.873, train=13.7%, train_loss=0.867]

process_architecture/outcome:  43%|████▎     | 853/2000 [00:04<00:06, 184.67it/s, test=14.2%, test_loss=0.873, train=13.7%, train_loss=0.867]

process_architecture/outcome:  44%|████▎     | 874/2000 [00:04<00:05, 190.80it/s, test=14.2%, test_loss=0.873, train=13.7%, train_loss=0.867]

process_architecture/outcome:  45%|████▍     | 895/2000 [00:05<00:05, 194.34it/s, test=14.2%, test_loss=0.873, train=13.7%, train_loss=0.867]

process_architecture/outcome:  45%|████▍     | 895/2000 [00:05<00:05, 194.34it/s, test=13.9%, test_loss=0.868, train=15.0%, train_loss=0.843]

process_architecture/outcome:  46%|████▌     | 915/2000 [00:05<00:05, 187.23it/s, test=13.9%, test_loss=0.868, train=15.0%, train_loss=0.843]

process_architecture/outcome:  47%|████▋     | 936/2000 [00:05<00:05, 191.01it/s, test=13.9%, test_loss=0.868, train=15.0%, train_loss=0.843]

process_architecture/outcome:  47%|████▋     | 936/2000 [00:05<00:05, 191.01it/s, test=17.4%, test_loss=0.842, train=13.3%, train_loss=0.825]

process_architecture/outcome:  48%|████▊     | 956/2000 [00:05<00:05, 184.97it/s, test=17.4%, test_loss=0.842, train=13.3%, train_loss=0.825]

process_architecture/outcome:  49%|████▉     | 977/2000 [00:05<00:05, 190.81it/s, test=17.4%, test_loss=0.842, train=13.3%, train_loss=0.825]

process_architecture/outcome:  50%|████▉     | 998/2000 [00:05<00:05, 193.91it/s, test=17.4%, test_loss=0.842, train=13.3%, train_loss=0.825]

process_architecture/outcome:  50%|████▉     | 998/2000 [00:05<00:05, 193.91it/s, test=14.8%, test_loss=0.834, train=16.3%, train_loss=0.846]

process_architecture/outcome:  51%|█████     | 1018/2000 [00:05<00:05, 186.49it/s, test=14.8%, test_loss=0.834, train=16.3%, train_loss=0.846]

process_architecture/outcome:  52%|█████▏    | 1039/2000 [00:05<00:05, 190.63it/s, test=14.8%, test_loss=0.834, train=16.3%, train_loss=0.846]

process_architecture/outcome:  52%|█████▏    | 1039/2000 [00:05<00:05, 190.63it/s, test=14.4%, test_loss=0.832, train=10.7%, train_loss=0.806]

process_architecture/outcome:  53%|█████▎    | 1059/2000 [00:05<00:05, 184.99it/s, test=14.4%, test_loss=0.832, train=10.7%, train_loss=0.806]

process_architecture/outcome:  54%|█████▍    | 1080/2000 [00:06<00:04, 190.30it/s, test=14.4%, test_loss=0.832, train=10.7%, train_loss=0.806]

process_architecture/outcome:  54%|█████▍    | 1080/2000 [00:06<00:04, 190.30it/s, test=14.9%, test_loss=0.826, train=11.3%, train_loss=0.814]

process_architecture/outcome:  55%|█████▌    | 1100/2000 [00:06<00:04, 180.85it/s, test=14.9%, test_loss=0.826, train=11.3%, train_loss=0.814]

process_architecture/outcome:  56%|█████▌    | 1120/2000 [00:06<00:04, 186.00it/s, test=14.9%, test_loss=0.826, train=11.3%, train_loss=0.814]

process_architecture/outcome:  57%|█████▋    | 1141/2000 [00:06<00:04, 190.28it/s, test=14.9%, test_loss=0.826, train=11.3%, train_loss=0.814]

process_architecture/outcome:  57%|█████▋    | 1141/2000 [00:06<00:04, 190.28it/s, test=17.0%, test_loss=0.818, train=13.7%, train_loss=0.807]

process_architecture/outcome:  58%|█████▊    | 1161/2000 [00:06<00:04, 185.31it/s, test=17.0%, test_loss=0.818, train=13.7%, train_loss=0.807]

process_architecture/outcome:  59%|█████▉    | 1182/2000 [00:06<00:04, 190.09it/s, test=17.0%, test_loss=0.818, train=13.7%, train_loss=0.807]

process_architecture/outcome:  59%|█████▉    | 1182/2000 [00:06<00:04, 190.09it/s, test=16.5%, test_loss=0.834, train=17.3%, train_loss=0.777]

process_architecture/outcome:  60%|██████    | 1202/2000 [00:06<00:04, 183.40it/s, test=16.5%, test_loss=0.834, train=17.3%, train_loss=0.777]

process_architecture/outcome:  61%|██████    | 1222/2000 [00:06<00:04, 188.01it/s, test=16.5%, test_loss=0.834, train=17.3%, train_loss=0.777]

process_architecture/outcome:  62%|██████▏   | 1243/2000 [00:06<00:03, 191.95it/s, test=16.5%, test_loss=0.834, train=17.3%, train_loss=0.777]

process_architecture/outcome:  62%|██████▏   | 1243/2000 [00:06<00:03, 191.95it/s, test=17.1%, test_loss=0.825, train=15.0%, train_loss=0.810]

process_architecture/outcome:  63%|██████▎   | 1263/2000 [00:07<00:03, 186.19it/s, test=17.1%, test_loss=0.825, train=15.0%, train_loss=0.810]

process_architecture/outcome:  64%|██████▍   | 1284/2000 [00:07<00:03, 190.48it/s, test=17.1%, test_loss=0.825, train=15.0%, train_loss=0.810]

process_architecture/outcome:  64%|██████▍   | 1284/2000 [00:07<00:03, 190.48it/s, test=19.6%, test_loss=0.780, train=17.0%, train_loss=0.751]

process_architecture/outcome:  65%|██████▌   | 1304/2000 [00:07<00:03, 184.65it/s, test=19.6%, test_loss=0.780, train=17.0%, train_loss=0.751]

process_architecture/outcome:  66%|██████▋   | 1325/2000 [00:07<00:03, 189.38it/s, test=19.6%, test_loss=0.780, train=17.0%, train_loss=0.751]

process_architecture/outcome:  67%|██████▋   | 1346/2000 [00:07<00:03, 193.24it/s, test=19.6%, test_loss=0.780, train=17.0%, train_loss=0.751]

process_architecture/outcome:  67%|██████▋   | 1346/2000 [00:07<00:03, 193.24it/s, test=16.7%, test_loss=0.785, train=15.0%, train_loss=0.784]

process_architecture/outcome:  68%|██████▊   | 1366/2000 [00:07<00:03, 187.27it/s, test=16.7%, test_loss=0.785, train=15.0%, train_loss=0.784]

process_architecture/outcome:  69%|██████▉   | 1386/2000 [00:07<00:03, 190.84it/s, test=16.7%, test_loss=0.785, train=15.0%, train_loss=0.784]

process_architecture/outcome:  69%|██████▉   | 1386/2000 [00:07<00:03, 190.84it/s, test=19.4%, test_loss=0.788, train=18.0%, train_loss=0.788]

process_architecture/outcome:  70%|███████   | 1406/2000 [00:07<00:03, 184.12it/s, test=19.4%, test_loss=0.788, train=18.0%, train_loss=0.788]

process_architecture/outcome:  71%|███████▏  | 1427/2000 [00:07<00:03, 188.88it/s, test=19.4%, test_loss=0.788, train=18.0%, train_loss=0.788]

process_architecture/outcome:  72%|███████▏  | 1448/2000 [00:08<00:02, 193.00it/s, test=19.4%, test_loss=0.788, train=18.0%, train_loss=0.788]

process_architecture/outcome:  72%|███████▏  | 1448/2000 [00:08<00:02, 193.00it/s, test=18.0%, test_loss=0.831, train=19.7%, train_loss=0.789]

process_architecture/outcome:  73%|███████▎  | 1468/2000 [00:08<00:02, 186.49it/s, test=18.0%, test_loss=0.831, train=19.7%, train_loss=0.789]

process_architecture/outcome:  74%|███████▍  | 1488/2000 [00:08<00:02, 190.20it/s, test=18.0%, test_loss=0.831, train=19.7%, train_loss=0.789]

process_architecture/outcome:  74%|███████▍  | 1488/2000 [00:08<00:02, 190.20it/s, test=20.4%, test_loss=0.784, train=20.0%, train_loss=0.734]

process_architecture/outcome:  75%|███████▌  | 1508/2000 [00:08<00:02, 184.31it/s, test=20.4%, test_loss=0.784, train=20.0%, train_loss=0.734]

process_architecture/outcome:  76%|███████▋  | 1529/2000 [00:08<00:02, 189.45it/s, test=20.4%, test_loss=0.784, train=20.0%, train_loss=0.734]

process_architecture/outcome:  76%|███████▋  | 1529/2000 [00:08<00:02, 189.45it/s, test=17.5%, test_loss=0.799, train=17.7%, train_loss=0.790]

process_architecture/outcome:  78%|███████▊  | 1550/2000 [00:08<00:02, 185.08it/s, test=17.5%, test_loss=0.799, train=17.7%, train_loss=0.790]

process_architecture/outcome:  79%|███████▊  | 1571/2000 [00:08<00:02, 189.83it/s, test=17.5%, test_loss=0.799, train=17.7%, train_loss=0.790]

process_architecture/outcome:  80%|███████▉  | 1591/2000 [00:08<00:02, 192.62it/s, test=17.5%, test_loss=0.799, train=17.7%, train_loss=0.790]

process_architecture/outcome:  80%|███████▉  | 1591/2000 [00:08<00:02, 192.62it/s, test=20.0%, test_loss=0.787, train=22.3%, train_loss=0.724]

process_architecture/outcome:  81%|████████  | 1611/2000 [00:08<00:02, 185.22it/s, test=20.0%, test_loss=0.787, train=22.3%, train_loss=0.724]

process_architecture/outcome:  82%|████████▏ | 1632/2000 [00:09<00:01, 189.79it/s, test=20.0%, test_loss=0.787, train=22.3%, train_loss=0.724]

process_architecture/outcome:  82%|████████▏ | 1632/2000 [00:09<00:01, 189.79it/s, test=23.0%, test_loss=0.769, train=20.3%, train_loss=0.759]

process_architecture/outcome:  83%|████████▎ | 1652/2000 [00:09<00:01, 184.38it/s, test=23.0%, test_loss=0.769, train=20.3%, train_loss=0.759]

process_architecture/outcome:  84%|████████▎ | 1673/2000 [00:09<00:01, 189.11it/s, test=23.0%, test_loss=0.769, train=20.3%, train_loss=0.759]

process_architecture/outcome:  85%|████████▍ | 1694/2000 [00:09<00:01, 192.37it/s, test=23.0%, test_loss=0.769, train=20.3%, train_loss=0.759]

process_architecture/outcome:  85%|████████▍ | 1694/2000 [00:09<00:01, 192.37it/s, test=21.5%, test_loss=0.743, train=22.3%, train_loss=0.711]

process_architecture/outcome:  86%|████████▌ | 1714/2000 [00:09<00:01, 185.15it/s, test=21.5%, test_loss=0.743, train=22.3%, train_loss=0.711]

process_architecture/outcome:  87%|████████▋ | 1735/2000 [00:09<00:01, 190.35it/s, test=21.5%, test_loss=0.743, train=22.3%, train_loss=0.711]

process_architecture/outcome:  87%|████████▋ | 1735/2000 [00:09<00:01, 190.35it/s, test=22.2%, test_loss=0.748, train=22.3%, train_loss=0.702]

process_architecture/outcome:  88%|████████▊ | 1755/2000 [00:09<00:01, 185.49it/s, test=22.2%, test_loss=0.748, train=22.3%, train_loss=0.702]

process_architecture/outcome:  89%|████████▉ | 1775/2000 [00:09<00:01, 189.44it/s, test=22.2%, test_loss=0.748, train=22.3%, train_loss=0.702]

process_architecture/outcome:  90%|████████▉ | 1795/2000 [00:09<00:01, 190.31it/s, test=22.2%, test_loss=0.748, train=22.3%, train_loss=0.702]

process_architecture/outcome:  90%|████████▉ | 1795/2000 [00:09<00:01, 190.31it/s, test=22.7%, test_loss=0.758, train=22.3%, train_loss=0.699]

process_architecture/outcome:  91%|█████████ | 1815/2000 [00:10<00:01, 181.96it/s, test=22.7%, test_loss=0.758, train=22.3%, train_loss=0.699]

process_architecture/outcome:  92%|█████████▏| 1835/2000 [00:10<00:00, 184.88it/s, test=22.7%, test_loss=0.758, train=22.3%, train_loss=0.699]

process_architecture/outcome:  92%|█████████▏| 1835/2000 [00:10<00:00, 184.88it/s, test=22.9%, test_loss=0.731, train=24.3%, train_loss=0.649]

process_architecture/outcome:  93%|█████████▎| 1854/2000 [00:10<00:00, 178.36it/s, test=22.9%, test_loss=0.731, train=24.3%, train_loss=0.649]

process_architecture/outcome:  94%|█████████▎| 1874/2000 [00:10<00:00, 182.03it/s, test=22.9%, test_loss=0.731, train=24.3%, train_loss=0.649]

process_architecture/outcome:  95%|█████████▍| 1894/2000 [00:10<00:00, 185.07it/s, test=22.9%, test_loss=0.731, train=24.3%, train_loss=0.649]

process_architecture/outcome:  95%|█████████▍| 1894/2000 [00:10<00:00, 185.07it/s, test=23.9%, test_loss=0.747, train=26.0%, train_loss=0.682]

process_architecture/outcome:  96%|█████████▌| 1913/2000 [00:10<00:00, 178.33it/s, test=23.9%, test_loss=0.747, train=26.0%, train_loss=0.682]

process_architecture/outcome:  97%|█████████▋| 1933/2000 [00:10<00:00, 182.59it/s, test=23.9%, test_loss=0.747, train=26.0%, train_loss=0.682]

process_architecture/outcome:  97%|█████████▋| 1933/2000 [00:10<00:00, 182.59it/s, test=24.5%, test_loss=0.698, train=22.3%, train_loss=0.624]

process_architecture/outcome:  98%|█████████▊| 1952/2000 [00:10<00:00, 176.80it/s, test=24.5%, test_loss=0.698, train=22.3%, train_loss=0.624]

process_architecture/outcome:  99%|█████████▊| 1972/2000 [00:10<00:00, 180.86it/s, test=24.5%, test_loss=0.698, train=22.3%, train_loss=0.624]

process_architecture/outcome: 100%|█████████▉| 1992/2000 [00:10<00:00, 183.87it/s, test=24.5%, test_loss=0.698, train=22.3%, train_loss=0.624]

process_architecture/outcome: 100%|█████████▉| 1992/2000 [00:11<00:00, 183.87it/s, test=26.2%, test_loss=0.692, train=25.3%, train_loss=0.684]

process_architecture/outcome: 100%|██████████| 2000/2000 [00:11<00:00, 181.27it/s, test=26.2%, test_loss=0.692, train=25.3%, train_loss=0.684]

architecture/mode:  25%|██▌       | 1/4 [00:11<00:33, 11.05s/it]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.258, train=0.0%, train_loss=4.258]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.232, train=0.0%, train_loss=4.232]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.885, train=0.0%, train_loss=3.896]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.642, train=0.0%, train_loss=3.660]

process_architecture/process:   0%|          | 10/2000 [00:00<00:27, 72.38it/s, test=0.0%, test_loss=3.642, train=0.0%, train_loss=3.660]

process_architecture/process:   0%|          | 10/2000 [00:00<00:27, 72.38it/s, test=7.5%, test_loss=3.020, train=7.0%, train_loss=3.027]

process_architecture/process:   1%|          | 20/2000 [00:00<00:23, 82.65it/s, test=7.5%, test_loss=3.020, train=7.0%, train_loss=3.027]

process_architecture/process:   1%|          | 20/2000 [00:00<00:23, 82.65it/s, test=6.5%, test_loss=2.801, train=8.7%, train_loss=2.812]

process_architecture/process:   1%|▏         | 29/2000 [00:00<00:23, 85.61it/s, test=6.5%, test_loss=2.801, train=8.7%, train_loss=2.812]

process_architecture/process:   1%|▏         | 29/2000 [00:00<00:23, 85.61it/s, test=10.0%, test_loss=2.581, train=5.3%, train_loss=2.609]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:17, 108.38it/s, test=10.0%, test_loss=2.581, train=5.3%, train_loss=2.609]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:13, 138.10it/s, test=10.0%, test_loss=2.581, train=5.3%, train_loss=2.609]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:13, 138.10it/s, test=9.2%, test_loss=2.421, train=7.3%, train_loss=2.428]

process_architecture/process:   4%|▍         | 86/2000 [00:00<00:14, 130.49it/s, test=9.2%, test_loss=2.421, train=7.3%, train_loss=2.428]

process_architecture/process:   4%|▍         | 86/2000 [00:00<00:14, 130.49it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   5%|▌         | 100/2000 [00:00<00:15, 124.87it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   6%|▌         | 121/2000 [00:00<00:12, 146.57it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 162.69it/s, test=12.9%, test_loss=2.315, train=9.3%, train_loss=2.334]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 162.69it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:   8%|▊         | 159/2000 [00:01<00:12, 148.61it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:   9%|▉         | 179/2000 [00:01<00:11, 162.24it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:  10%|▉         | 199/2000 [00:01<00:10, 172.59it/s, test=12.6%, test_loss=2.017, train=11.0%, train_loss=2.023]

process_architecture/process:  10%|▉         | 199/2000 [00:01<00:10, 172.59it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  11%|█         | 217/2000 [00:01<00:11, 155.53it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  12%|█▏        | 238/2000 [00:01<00:10, 168.97it/s, test=15.8%, test_loss=1.472, train=12.0%, train_loss=1.487]

process_architecture/process:  12%|█▏        | 238/2000 [00:01<00:10, 168.97it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  13%|█▎        | 256/2000 [00:01<00:11, 153.33it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  14%|█▍        | 276/2000 [00:01<00:10, 165.03it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  15%|█▍        | 296/2000 [00:01<00:09, 174.08it/s, test=31.6%, test_loss=0.311, train=26.7%, train_loss=0.298]

process_architecture/process:  15%|█▍        | 296/2000 [00:02<00:09, 174.08it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  16%|█▌        | 314/2000 [00:02<00:10, 156.65it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  17%|█▋        | 335/2000 [00:02<00:09, 169.11it/s, test=60.3%, test_loss=0.134, train=59.7%, train_loss=0.135]

process_architecture/process:  17%|█▋        | 335/2000 [00:02<00:09, 169.11it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  18%|█▊        | 353/2000 [00:02<00:10, 153.70it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  19%|█▊        | 374/2000 [00:02<00:09, 166.39it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  20%|█▉        | 395/2000 [00:02<00:09, 176.51it/s, test=80.0%, test_loss=0.050, train=78.7%, train_loss=0.078]

process_architecture/process:  20%|█▉        | 395/2000 [00:02<00:09, 176.51it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  21%|██        | 414/2000 [00:02<00:10, 157.93it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  22%|██▏       | 434/2000 [00:02<00:09, 168.29it/s, test=95.0%, test_loss=0.033, train=93.3%, train_loss=0.022]

process_architecture/process:  22%|██▏       | 434/2000 [00:02<00:09, 168.29it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  23%|██▎       | 452/2000 [00:02<00:10, 153.66it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  24%|██▎       | 473/2000 [00:03<00:09, 167.16it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  25%|██▍       | 494/2000 [00:03<00:08, 177.06it/s, test=99.6%, test_loss=0.006, train=100.0%, train_loss=0.004]

process_architecture/process:  25%|██▍       | 494/2000 [00:03<00:08, 177.06it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  26%|██▌       | 513/2000 [00:03<00:09, 159.70it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 534/2000 [00:03<00:08, 171.62it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.002]

process_architecture/process:  27%|██▋       | 534/2000 [00:03<00:08, 171.62it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  28%|██▊       | 552/2000 [00:03<00:09, 155.74it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▊       | 573/2000 [00:03<00:08, 168.78it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|██▉       | 594/2000 [00:03<00:07, 178.42it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|██▉       | 594/2000 [00:03<00:07, 178.42it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  31%|███       | 613/2000 [00:03<00:08, 160.44it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 633/2000 [00:04<00:08, 170.60it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 633/2000 [00:04<00:08, 170.60it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  33%|███▎      | 651/2000 [00:04<00:08, 154.63it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▎      | 672/2000 [00:04<00:07, 167.44it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  35%|███▍      | 693/2000 [00:04<00:07, 177.16it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  35%|███▍      | 693/2000 [00:04<00:07, 177.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 712/2000 [00:04<00:08, 158.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 733/2000 [00:04<00:07, 170.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 733/2000 [00:04<00:07, 170.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 751/2000 [00:04<00:08, 155.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▊      | 772/2000 [00:04<00:07, 168.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 792/2000 [00:04<00:06, 176.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 792/2000 [00:05<00:06, 176.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 811/2000 [00:05<00:07, 155.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 831/2000 [00:05<00:07, 166.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 831/2000 [00:05<00:07, 166.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▎     | 850/2000 [00:05<00:07, 152.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▎     | 870/2000 [00:05<00:06, 163.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 889/2000 [00:05<00:06, 169.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 889/2000 [00:05<00:06, 169.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 907/2000 [00:05<00:07, 146.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 927/2000 [00:05<00:06, 158.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 944/2000 [00:05<00:06, 160.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 944/2000 [00:06<00:06, 160.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 961/2000 [00:06<00:07, 143.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 981/2000 [00:06<00:06, 156.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 981/2000 [00:06<00:06, 156.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1000/2000 [00:06<00:07, 142.73it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1020/2000 [00:06<00:06, 155.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1040/2000 [00:06<00:05, 164.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1040/2000 [00:06<00:05, 164.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1058/2000 [00:06<00:06, 149.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1078/2000 [00:06<00:05, 160.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▍    | 1098/2000 [00:06<00:05, 169.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▍    | 1098/2000 [00:07<00:05, 169.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1116/2000 [00:07<00:05, 151.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1136/2000 [00:07<00:05, 162.43it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1136/2000 [00:07<00:05, 162.43it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1153/2000 [00:07<00:05, 147.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▊    | 1173/2000 [00:07<00:05, 159.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1193/2000 [00:07<00:04, 168.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1193/2000 [00:07<00:04, 168.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1211/2000 [00:07<00:05, 151.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1231/2000 [00:07<00:04, 162.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1231/2000 [00:07<00:04, 162.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▎   | 1250/2000 [00:07<00:05, 149.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▎   | 1270/2000 [00:08<00:04, 161.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1290/2000 [00:08<00:04, 171.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1290/2000 [00:08<00:04, 171.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▌   | 1308/2000 [00:08<00:04, 155.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▋   | 1328/2000 [00:08<00:04, 166.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1348/2000 [00:08<00:03, 174.89it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1348/2000 [00:08<00:03, 174.89it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1367/2000 [00:08<00:03, 158.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1388/2000 [00:08<00:03, 170.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1388/2000 [00:08<00:03, 170.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1406/2000 [00:08<00:03, 155.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████▏  | 1426/2000 [00:09<00:03, 166.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1445/2000 [00:09<00:03, 171.77it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1445/2000 [00:09<00:03, 171.77it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1463/2000 [00:09<00:03, 152.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1482/2000 [00:09<00:03, 162.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1482/2000 [00:09<00:03, 162.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1500/2000 [00:09<00:03, 147.43it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1519/2000 [00:09<00:03, 157.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1540/2000 [00:09<00:02, 169.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1540/2000 [00:09<00:02, 169.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1558/2000 [00:09<00:02, 152.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1577/2000 [00:09<00:02, 161.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1596/2000 [00:10<00:02, 168.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1596/2000 [00:10<00:02, 168.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1614/2000 [00:10<00:02, 150.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1633/2000 [00:10<00:02, 160.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1633/2000 [00:10<00:02, 160.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▎ | 1650/2000 [00:10<00:02, 146.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1669/2000 [00:10<00:02, 156.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1689/2000 [00:10<00:01, 166.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1689/2000 [00:10<00:01, 166.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▌ | 1707/2000 [00:10<00:01, 151.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▋ | 1728/2000 [00:10<00:01, 165.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1749/2000 [00:11<00:01, 175.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1749/2000 [00:11<00:01, 175.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1768/2000 [00:11<00:01, 158.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1789/2000 [00:11<00:01, 169.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1789/2000 [00:11<00:01, 169.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|█████████ | 1807/2000 [00:11<00:01, 154.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████▏| 1828/2000 [00:11<00:01, 166.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1849/2000 [00:11<00:00, 176.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1849/2000 [00:11<00:00, 176.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1868/2000 [00:11<00:00, 159.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1889/2000 [00:11<00:00, 170.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1889/2000 [00:11<00:00, 170.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▌| 1907/2000 [00:12<00:00, 155.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▋| 1928/2000 [00:12<00:00, 167.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1948/2000 [00:12<00:00, 176.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1948/2000 [00:12<00:00, 176.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1967/2000 [00:12<00:00, 159.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1988/2000 [00:12<00:00, 170.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1988/2000 [00:12<00:00, 170.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 158.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode:  50%|█████     | 2/4 [00:23<00:23, 11.99s/it]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.650, train=0.0%, train_loss=3.647]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=8.943, train=0.0%, train_loss=8.949]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.011, train=0.0%, train_loss=3.012]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:53, 37.57it/s, test=0.0%, test_loss=3.011, train=0.0%, train_loss=3.012]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:53, 37.57it/s, test=0.0%, test_loss=1.099, train=0.0%, train_loss=1.109]

outcome_architecture/outcome:   1%|          | 13/2000 [00:00<00:34, 58.29it/s, test=0.0%, test_loss=1.099, train=0.0%, train_loss=1.109]

outcome_architecture/outcome:   1%|          | 13/2000 [00:00<00:34, 58.29it/s, test=5.4%, test_loss=1.796, train=5.7%, train_loss=1.824]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:31, 62.40it/s, test=5.4%, test_loss=1.796, train=5.7%, train_loss=1.824]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:31, 62.40it/s, test=0.7%, test_loss=1.387, train=1.3%, train_loss=1.464]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:30, 64.60it/s, test=0.7%, test_loss=1.387, train=1.3%, train_loss=1.464]

outcome_architecture/outcome:   2%|▏         | 38/2000 [00:00<00:24, 79.34it/s, test=0.7%, test_loss=1.387, train=1.3%, train_loss=1.464]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:22, 88.25it/s, test=0.7%, test_loss=1.387, train=1.3%, train_loss=1.464]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:22, 88.25it/s, test=4.9%, test_loss=2.151, train=5.7%, train_loss=2.209]

outcome_architecture/outcome:   3%|▎         | 58/2000 [00:00<00:23, 83.02it/s, test=4.9%, test_loss=2.151, train=5.7%, train_loss=2.209]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 89.89it/s, test=4.9%, test_loss=2.151, train=5.7%, train_loss=2.209]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 89.89it/s, test=0.0%, test_loss=8.739, train=0.0%, train_loss=8.905]

outcome_architecture/outcome:   4%|▍         | 79/2000 [00:00<00:21, 89.07it/s, test=0.0%, test_loss=8.739, train=0.0%, train_loss=8.905]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:20, 94.09it/s, test=0.0%, test_loss=8.739, train=0.0%, train_loss=8.905]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:20, 94.09it/s, test=0.0%, test_loss=3.148, train=0.0%, train_loss=3.019]

outcome_architecture/outcome:   5%|▌         | 100/2000 [00:01<00:21, 88.16it/s, test=0.0%, test_loss=3.148, train=0.0%, train_loss=3.019]

outcome_architecture/outcome:   6%|▌         | 111/2000 [00:01<00:20, 93.17it/s, test=0.0%, test_loss=3.148, train=0.0%, train_loss=3.019]

outcome_architecture/outcome:   6%|▌         | 122/2000 [00:01<00:19, 96.70it/s, test=0.0%, test_loss=3.148, train=0.0%, train_loss=3.019]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:18, 99.42it/s, test=0.0%, test_loss=3.148, train=0.0%, train_loss=3.019]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 101.18it/s, test=0.0%, test_loss=3.148, train=0.0%, train_loss=3.019]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 101.18it/s, test=6.6%, test_loss=0.998, train=4.7%, train_loss=0.997]

outcome_architecture/outcome:   8%|▊         | 155/2000 [00:01<00:19, 92.94it/s, test=6.6%, test_loss=0.998, train=4.7%, train_loss=0.997]

outcome_architecture/outcome:   8%|▊         | 166/2000 [00:01<00:19, 96.40it/s, test=6.6%, test_loss=0.998, train=4.7%, train_loss=0.997]

outcome_architecture/outcome:   9%|▉         | 177/2000 [00:01<00:18, 99.04it/s, test=6.6%, test_loss=0.998, train=4.7%, train_loss=0.997]

outcome_architecture/outcome:   9%|▉         | 188/2000 [00:02<00:17, 101.06it/s, test=6.6%, test_loss=0.998, train=4.7%, train_loss=0.997]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 102.61it/s, test=6.6%, test_loss=0.998, train=4.7%, train_loss=0.997]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 102.61it/s, test=9.6%, test_loss=0.915, train=8.7%, train_loss=0.927]

outcome_architecture/outcome:  10%|█         | 210/2000 [00:02<00:19, 93.73it/s, test=9.6%, test_loss=0.915, train=8.7%, train_loss=0.927]

outcome_architecture/outcome:  11%|█         | 221/2000 [00:02<00:18, 97.11it/s, test=9.6%, test_loss=0.915, train=8.7%, train_loss=0.927]

outcome_architecture/outcome:  12%|█▏        | 232/2000 [00:02<00:17, 99.77it/s, test=9.6%, test_loss=0.915, train=8.7%, train_loss=0.927]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:17, 101.50it/s, test=9.6%, test_loss=0.915, train=8.7%, train_loss=0.927]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:17, 101.50it/s, test=10.7%, test_loss=0.905, train=9.3%, train_loss=0.920]

outcome_architecture/outcome:  13%|█▎        | 254/2000 [00:02<00:18, 93.20it/s, test=10.7%, test_loss=0.905, train=9.3%, train_loss=0.920]

outcome_architecture/outcome:  13%|█▎        | 265/2000 [00:02<00:17, 96.41it/s, test=10.7%, test_loss=0.905, train=9.3%, train_loss=0.920]

outcome_architecture/outcome:  14%|█▍        | 276/2000 [00:02<00:17, 98.85it/s, test=10.7%, test_loss=0.905, train=9.3%, train_loss=0.920]

outcome_architecture/outcome:  14%|█▍        | 287/2000 [00:03<00:16, 100.89it/s, test=10.7%, test_loss=0.905, train=9.3%, train_loss=0.920]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 102.36it/s, test=10.7%, test_loss=0.905, train=9.3%, train_loss=0.920]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 102.36it/s, test=12.4%, test_loss=0.899, train=8.0%, train_loss=0.921]

outcome_architecture/outcome:  15%|█▌        | 309/2000 [00:03<00:18, 93.73it/s, test=12.4%, test_loss=0.899, train=8.0%, train_loss=0.921]

outcome_architecture/outcome:  16%|█▌        | 320/2000 [00:03<00:17, 97.04it/s, test=12.4%, test_loss=0.899, train=8.0%, train_loss=0.921]

outcome_architecture/outcome:  17%|█▋        | 331/2000 [00:03<00:16, 99.62it/s, test=12.4%, test_loss=0.899, train=8.0%, train_loss=0.921]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:16, 101.40it/s, test=12.4%, test_loss=0.899, train=8.0%, train_loss=0.921]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:16, 101.40it/s, test=11.5%, test_loss=0.891, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  18%|█▊        | 353/2000 [00:03<00:17, 93.17it/s, test=11.5%, test_loss=0.891, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  18%|█▊        | 364/2000 [00:03<00:16, 96.50it/s, test=11.5%, test_loss=0.891, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  19%|█▉        | 375/2000 [00:04<00:16, 99.05it/s, test=11.5%, test_loss=0.891, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  19%|█▉        | 386/2000 [00:04<00:15, 100.95it/s, test=11.5%, test_loss=0.891, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 102.19it/s, test=11.5%, test_loss=0.891, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 102.19it/s, test=11.4%, test_loss=0.886, train=8.0%, train_loss=0.899]

outcome_architecture/outcome:  20%|██        | 408/2000 [00:04<00:16, 93.77it/s, test=11.4%, test_loss=0.886, train=8.0%, train_loss=0.899]

outcome_architecture/outcome:  21%|██        | 419/2000 [00:04<00:16, 96.98it/s, test=11.4%, test_loss=0.886, train=8.0%, train_loss=0.899]

outcome_architecture/outcome:  22%|██▏       | 430/2000 [00:04<00:15, 99.52it/s, test=11.4%, test_loss=0.886, train=8.0%, train_loss=0.899]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 101.19it/s, test=11.4%, test_loss=0.886, train=8.0%, train_loss=0.899]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 101.19it/s, test=12.5%, test_loss=0.879, train=11.0%, train_loss=0.878]

outcome_architecture/outcome:  23%|██▎       | 452/2000 [00:04<00:16, 93.11it/s, test=12.5%, test_loss=0.879, train=11.0%, train_loss=0.878]

outcome_architecture/outcome:  23%|██▎       | 463/2000 [00:04<00:15, 96.52it/s, test=12.5%, test_loss=0.879, train=11.0%, train_loss=0.878]

outcome_architecture/outcome:  24%|██▎       | 474/2000 [00:05<00:15, 99.06it/s, test=12.5%, test_loss=0.879, train=11.0%, train_loss=0.878]

outcome_architecture/outcome:  24%|██▍       | 485/2000 [00:05<00:15, 98.53it/s, test=12.5%, test_loss=0.879, train=11.0%, train_loss=0.878]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 100.47it/s, test=12.5%, test_loss=0.879, train=11.0%, train_loss=0.878]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 100.47it/s, test=11.4%, test_loss=0.904, train=9.7%, train_loss=0.909]

outcome_architecture/outcome:  25%|██▌       | 507/2000 [00:05<00:16, 92.38it/s, test=11.4%, test_loss=0.904, train=9.7%, train_loss=0.909]

outcome_architecture/outcome:  26%|██▌       | 518/2000 [00:05<00:15, 95.83it/s, test=11.4%, test_loss=0.904, train=9.7%, train_loss=0.909]

outcome_architecture/outcome:  26%|██▋       | 529/2000 [00:05<00:14, 98.39it/s, test=11.4%, test_loss=0.904, train=9.7%, train_loss=0.909]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 100.24it/s, test=11.4%, test_loss=0.904, train=9.7%, train_loss=0.909]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 100.24it/s, test=12.3%, test_loss=0.907, train=10.3%, train_loss=0.880]

outcome_architecture/outcome:  28%|██▊       | 551/2000 [00:05<00:15, 91.86it/s, test=12.3%, test_loss=0.907, train=10.3%, train_loss=0.880]

outcome_architecture/outcome:  28%|██▊       | 562/2000 [00:05<00:15, 95.05it/s, test=12.3%, test_loss=0.907, train=10.3%, train_loss=0.880]

outcome_architecture/outcome:  29%|██▊       | 573/2000 [00:06<00:14, 97.73it/s, test=12.3%, test_loss=0.907, train=10.3%, train_loss=0.880]

outcome_architecture/outcome:  29%|██▉       | 584/2000 [00:06<00:14, 99.88it/s, test=12.3%, test_loss=0.907, train=10.3%, train_loss=0.880]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 101.45it/s, test=12.3%, test_loss=0.907, train=10.3%, train_loss=0.880]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 101.45it/s, test=11.7%, test_loss=0.892, train=12.3%, train_loss=0.908]

outcome_architecture/outcome:  30%|███       | 606/2000 [00:06<00:14, 93.28it/s, test=11.7%, test_loss=0.892, train=12.3%, train_loss=0.908]

outcome_architecture/outcome:  31%|███       | 617/2000 [00:06<00:14, 97.29it/s, test=11.7%, test_loss=0.892, train=12.3%, train_loss=0.908]

outcome_architecture/outcome:  31%|███▏      | 628/2000 [00:06<00:13, 100.36it/s, test=11.7%, test_loss=0.892, train=12.3%, train_loss=0.908]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 102.82it/s, test=11.7%, test_loss=0.892, train=12.3%, train_loss=0.908]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 102.82it/s, test=11.8%, test_loss=0.905, train=10.3%, train_loss=0.911]

outcome_architecture/outcome:  32%|███▎      | 650/2000 [00:06<00:14, 94.87it/s, test=11.8%, test_loss=0.905, train=10.3%, train_loss=0.911]

outcome_architecture/outcome:  33%|███▎      | 661/2000 [00:06<00:13, 98.71it/s, test=11.8%, test_loss=0.905, train=10.3%, train_loss=0.911]

outcome_architecture/outcome:  34%|███▎      | 672/2000 [00:07<00:13, 101.55it/s, test=11.8%, test_loss=0.905, train=10.3%, train_loss=0.911]

outcome_architecture/outcome:  34%|███▍      | 683/2000 [00:07<00:12, 103.87it/s, test=11.8%, test_loss=0.905, train=10.3%, train_loss=0.911]

outcome_architecture/outcome:  35%|███▍      | 694/2000 [00:07<00:12, 105.48it/s, test=11.8%, test_loss=0.905, train=10.3%, train_loss=0.911]

outcome_architecture/outcome:  35%|███▍      | 694/2000 [00:07<00:12, 105.48it/s, test=13.9%, test_loss=0.898, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  35%|███▌      | 705/2000 [00:07<00:13, 96.39it/s, test=13.9%, test_loss=0.898, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  36%|███▌      | 716/2000 [00:07<00:12, 99.78it/s, test=13.9%, test_loss=0.898, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  36%|███▋      | 727/2000 [00:07<00:12, 102.25it/s, test=13.9%, test_loss=0.898, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  37%|███▋      | 738/2000 [00:07<00:12, 104.21it/s, test=13.9%, test_loss=0.898, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:07<00:11, 105.60it/s, test=13.9%, test_loss=0.898, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:07<00:11, 105.60it/s, test=13.3%, test_loss=0.886, train=11.3%, train_loss=0.891]

outcome_architecture/outcome:  38%|███▊      | 760/2000 [00:07<00:12, 96.53it/s, test=13.3%, test_loss=0.886, train=11.3%, train_loss=0.891]

outcome_architecture/outcome:  39%|███▊      | 771/2000 [00:08<00:12, 99.62it/s, test=13.3%, test_loss=0.886, train=11.3%, train_loss=0.891]

outcome_architecture/outcome:  39%|███▉      | 782/2000 [00:08<00:11, 102.24it/s, test=13.3%, test_loss=0.886, train=11.3%, train_loss=0.891]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:11, 104.10it/s, test=13.3%, test_loss=0.886, train=11.3%, train_loss=0.891]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:11, 104.10it/s, test=13.8%, test_loss=0.884, train=11.0%, train_loss=0.891]

outcome_architecture/outcome:  40%|████      | 804/2000 [00:08<00:12, 95.54it/s, test=13.8%, test_loss=0.884, train=11.0%, train_loss=0.891]

outcome_architecture/outcome:  41%|████      | 815/2000 [00:08<00:11, 99.05it/s, test=13.8%, test_loss=0.884, train=11.0%, train_loss=0.891]

outcome_architecture/outcome:  41%|████▏     | 826/2000 [00:08<00:11, 101.73it/s, test=13.8%, test_loss=0.884, train=11.0%, train_loss=0.891]

outcome_architecture/outcome:  42%|████▏     | 837/2000 [00:08<00:11, 103.62it/s, test=13.8%, test_loss=0.884, train=11.0%, train_loss=0.891]

outcome_architecture/outcome:  42%|████▏     | 848/2000 [00:08<00:10, 105.11it/s, test=13.8%, test_loss=0.884, train=11.0%, train_loss=0.891]

outcome_architecture/outcome:  42%|████▏     | 848/2000 [00:08<00:10, 105.11it/s, test=13.5%, test_loss=0.896, train=12.0%, train_loss=0.911]

outcome_architecture/outcome:  43%|████▎     | 859/2000 [00:08<00:11, 95.94it/s, test=13.5%, test_loss=0.896, train=12.0%, train_loss=0.911]

outcome_architecture/outcome:  44%|████▎     | 870/2000 [00:09<00:11, 99.22it/s, test=13.5%, test_loss=0.896, train=12.0%, train_loss=0.911]

outcome_architecture/outcome:  44%|████▍     | 881/2000 [00:09<00:10, 101.86it/s, test=13.5%, test_loss=0.896, train=12.0%, train_loss=0.911]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:10, 103.56it/s, test=13.5%, test_loss=0.896, train=12.0%, train_loss=0.911]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:10, 103.56it/s, test=12.6%, test_loss=0.894, train=11.0%, train_loss=0.919]

outcome_architecture/outcome:  45%|████▌     | 903/2000 [00:09<00:11, 92.42it/s, test=12.6%, test_loss=0.894, train=11.0%, train_loss=0.919]

outcome_architecture/outcome:  46%|████▌     | 913/2000 [00:09<00:11, 93.68it/s, test=12.6%, test_loss=0.894, train=11.0%, train_loss=0.919]

outcome_architecture/outcome:  46%|████▌     | 923/2000 [00:09<00:11, 94.41it/s, test=12.6%, test_loss=0.894, train=11.0%, train_loss=0.919]

outcome_architecture/outcome:  47%|████▋     | 933/2000 [00:09<00:11, 95.08it/s, test=12.6%, test_loss=0.894, train=11.0%, train_loss=0.919]

outcome_architecture/outcome:  47%|████▋     | 943/2000 [00:09<00:11, 94.37it/s, test=12.6%, test_loss=0.894, train=11.0%, train_loss=0.919]

outcome_architecture/outcome:  47%|████▋     | 943/2000 [00:09<00:11, 94.37it/s, test=14.5%, test_loss=0.889, train=12.0%, train_loss=0.901]

outcome_architecture/outcome:  48%|████▊     | 953/2000 [00:09<00:12, 84.76it/s, test=14.5%, test_loss=0.889, train=12.0%, train_loss=0.901]

outcome_architecture/outcome:  48%|████▊     | 963/2000 [00:10<00:11, 87.81it/s, test=14.5%, test_loss=0.889, train=12.0%, train_loss=0.901]

outcome_architecture/outcome:  49%|████▊     | 973/2000 [00:10<00:11, 90.16it/s, test=14.5%, test_loss=0.889, train=12.0%, train_loss=0.901]

outcome_architecture/outcome:  49%|████▉     | 983/2000 [00:10<00:10, 92.51it/s, test=14.5%, test_loss=0.889, train=12.0%, train_loss=0.901]

outcome_architecture/outcome:  50%|████▉     | 993/2000 [00:10<00:10, 92.22it/s, test=14.5%, test_loss=0.889, train=12.0%, train_loss=0.901]

outcome_architecture/outcome:  50%|████▉     | 993/2000 [00:10<00:10, 92.22it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  50%|█████     | 1003/2000 [00:10<00:12, 80.67it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  51%|█████     | 1012/2000 [00:10<00:12, 80.02it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  51%|█████     | 1021/2000 [00:10<00:12, 80.00it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  52%|█████▏    | 1030/2000 [00:10<00:12, 80.16it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  52%|█████▏    | 1039/2000 [00:10<00:11, 80.49it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  52%|█████▏    | 1048/2000 [00:11<00:11, 80.61it/s, test=14.4%, test_loss=0.888, train=12.0%, train_loss=0.877]

outcome_architecture/outcome:  52%|█████▏    | 1048/2000 [00:11<00:11, 80.61it/s, test=14.2%, test_loss=0.878, train=11.7%, train_loss=0.862]

outcome_architecture/outcome:  53%|█████▎    | 1057/2000 [00:11<00:12, 73.94it/s, test=14.2%, test_loss=0.878, train=11.7%, train_loss=0.862]

outcome_architecture/outcome:  53%|█████▎    | 1065/2000 [00:11<00:12, 75.43it/s, test=14.2%, test_loss=0.878, train=11.7%, train_loss=0.862]

outcome_architecture/outcome:  54%|█████▎    | 1074/2000 [00:11<00:11, 77.49it/s, test=14.2%, test_loss=0.878, train=11.7%, train_loss=0.862]

outcome_architecture/outcome:  54%|█████▍    | 1083/2000 [00:11<00:11, 78.60it/s, test=14.2%, test_loss=0.878, train=11.7%, train_loss=0.862]

outcome_architecture/outcome:  55%|█████▍    | 1092/2000 [00:11<00:11, 80.07it/s, test=14.2%, test_loss=0.878, train=11.7%, train_loss=0.862]

outcome_architecture/outcome:  55%|█████▍    | 1092/2000 [00:11<00:11, 80.07it/s, test=14.2%, test_loss=0.894, train=15.7%, train_loss=0.872]

outcome_architecture/outcome:  55%|█████▌    | 1101/2000 [00:11<00:11, 76.61it/s, test=14.2%, test_loss=0.894, train=15.7%, train_loss=0.872]

outcome_architecture/outcome:  56%|█████▌    | 1111/2000 [00:11<00:10, 82.59it/s, test=14.2%, test_loss=0.894, train=15.7%, train_loss=0.872]

outcome_architecture/outcome:  56%|█████▌    | 1121/2000 [00:11<00:10, 86.99it/s, test=14.2%, test_loss=0.894, train=15.7%, train_loss=0.872]

outcome_architecture/outcome:  57%|█████▋    | 1131/2000 [00:12<00:09, 90.52it/s, test=14.2%, test_loss=0.894, train=15.7%, train_loss=0.872]

outcome_architecture/outcome:  57%|█████▋    | 1141/2000 [00:12<00:09, 92.99it/s, test=14.2%, test_loss=0.894, train=15.7%, train_loss=0.872]

outcome_architecture/outcome:  57%|█████▋    | 1141/2000 [00:12<00:09, 92.99it/s, test=15.4%, test_loss=0.870, train=12.3%, train_loss=0.864]

outcome_architecture/outcome:  58%|█████▊    | 1151/2000 [00:12<00:09, 85.47it/s, test=15.4%, test_loss=0.870, train=12.3%, train_loss=0.864]

outcome_architecture/outcome:  58%|█████▊    | 1161/2000 [00:12<00:09, 88.84it/s, test=15.4%, test_loss=0.870, train=12.3%, train_loss=0.864]

outcome_architecture/outcome:  59%|█████▊    | 1171/2000 [00:12<00:09, 91.27it/s, test=15.4%, test_loss=0.870, train=12.3%, train_loss=0.864]

outcome_architecture/outcome:  59%|█████▉    | 1181/2000 [00:12<00:08, 93.06it/s, test=15.4%, test_loss=0.870, train=12.3%, train_loss=0.864]

outcome_architecture/outcome:  60%|█████▉    | 1191/2000 [00:12<00:08, 94.31it/s, test=15.4%, test_loss=0.870, train=12.3%, train_loss=0.864]

outcome_architecture/outcome:  60%|█████▉    | 1191/2000 [00:12<00:08, 94.31it/s, test=14.0%, test_loss=0.895, train=12.7%, train_loss=0.884]

outcome_architecture/outcome:  60%|██████    | 1201/2000 [00:12<00:09, 86.35it/s, test=14.0%, test_loss=0.895, train=12.7%, train_loss=0.884]

outcome_architecture/outcome:  61%|██████    | 1211/2000 [00:12<00:08, 89.66it/s, test=14.0%, test_loss=0.895, train=12.7%, train_loss=0.884]

outcome_architecture/outcome:  61%|██████    | 1221/2000 [00:13<00:08, 92.00it/s, test=14.0%, test_loss=0.895, train=12.7%, train_loss=0.884]

outcome_architecture/outcome:  62%|██████▏   | 1231/2000 [00:13<00:08, 93.66it/s, test=14.0%, test_loss=0.895, train=12.7%, train_loss=0.884]

outcome_architecture/outcome:  62%|██████▏   | 1241/2000 [00:13<00:08, 94.87it/s, test=14.0%, test_loss=0.895, train=12.7%, train_loss=0.884]

outcome_architecture/outcome:  62%|██████▏   | 1241/2000 [00:13<00:08, 94.87it/s, test=17.5%, test_loss=0.871, train=12.7%, train_loss=0.885]

outcome_architecture/outcome:  63%|██████▎   | 1251/2000 [00:13<00:08, 86.61it/s, test=17.5%, test_loss=0.871, train=12.7%, train_loss=0.885]

outcome_architecture/outcome:  63%|██████▎   | 1261/2000 [00:13<00:08, 89.99it/s, test=17.5%, test_loss=0.871, train=12.7%, train_loss=0.885]

outcome_architecture/outcome:  64%|██████▎   | 1271/2000 [00:13<00:07, 92.69it/s, test=17.5%, test_loss=0.871, train=12.7%, train_loss=0.885]

outcome_architecture/outcome:  64%|██████▍   | 1281/2000 [00:13<00:07, 94.75it/s, test=17.5%, test_loss=0.871, train=12.7%, train_loss=0.885]

outcome_architecture/outcome:  65%|██████▍   | 1291/2000 [00:13<00:07, 96.19it/s, test=17.5%, test_loss=0.871, train=12.7%, train_loss=0.885]

outcome_architecture/outcome:  65%|██████▍   | 1291/2000 [00:13<00:07, 96.19it/s, test=12.9%, test_loss=0.877, train=8.3%, train_loss=0.885]

outcome_architecture/outcome:  65%|██████▌   | 1301/2000 [00:13<00:07, 87.71it/s, test=12.9%, test_loss=0.877, train=8.3%, train_loss=0.885]

outcome_architecture/outcome:  66%|██████▌   | 1311/2000 [00:14<00:07, 90.83it/s, test=12.9%, test_loss=0.877, train=8.3%, train_loss=0.885]

outcome_architecture/outcome:  66%|██████▌   | 1321/2000 [00:14<00:07, 92.62it/s, test=12.9%, test_loss=0.877, train=8.3%, train_loss=0.885]

outcome_architecture/outcome:  67%|██████▋   | 1331/2000 [00:14<00:07, 94.03it/s, test=12.9%, test_loss=0.877, train=8.3%, train_loss=0.885]

outcome_architecture/outcome:  67%|██████▋   | 1341/2000 [00:14<00:06, 95.20it/s, test=12.9%, test_loss=0.877, train=8.3%, train_loss=0.885]

outcome_architecture/outcome:  67%|██████▋   | 1341/2000 [00:14<00:06, 95.20it/s, test=15.2%, test_loss=0.879, train=13.7%, train_loss=0.860]

outcome_architecture/outcome:  68%|██████▊   | 1351/2000 [00:14<00:07, 86.94it/s, test=15.2%, test_loss=0.879, train=13.7%, train_loss=0.860]

outcome_architecture/outcome:  68%|██████▊   | 1361/2000 [00:14<00:07, 89.79it/s, test=15.2%, test_loss=0.879, train=13.7%, train_loss=0.860]

outcome_architecture/outcome:  69%|██████▊   | 1371/2000 [00:14<00:06, 92.13it/s, test=15.2%, test_loss=0.879, train=13.7%, train_loss=0.860]

outcome_architecture/outcome:  69%|██████▉   | 1381/2000 [00:14<00:06, 94.02it/s, test=15.2%, test_loss=0.879, train=13.7%, train_loss=0.860]

outcome_architecture/outcome:  70%|██████▉   | 1391/2000 [00:14<00:06, 95.14it/s, test=15.2%, test_loss=0.879, train=13.7%, train_loss=0.860]

outcome_architecture/outcome:  70%|██████▉   | 1391/2000 [00:15<00:06, 95.14it/s, test=15.8%, test_loss=0.881, train=14.0%, train_loss=0.839]

outcome_architecture/outcome:  70%|███████   | 1401/2000 [00:15<00:06, 86.77it/s, test=15.8%, test_loss=0.881, train=14.0%, train_loss=0.839]

outcome_architecture/outcome:  71%|███████   | 1411/2000 [00:15<00:06, 90.07it/s, test=15.8%, test_loss=0.881, train=14.0%, train_loss=0.839]

outcome_architecture/outcome:  71%|███████   | 1421/2000 [00:15<00:06, 92.04it/s, test=15.8%, test_loss=0.881, train=14.0%, train_loss=0.839]

outcome_architecture/outcome:  72%|███████▏  | 1431/2000 [00:15<00:06, 93.49it/s, test=15.8%, test_loss=0.881, train=14.0%, train_loss=0.839]

outcome_architecture/outcome:  72%|███████▏  | 1441/2000 [00:15<00:05, 94.60it/s, test=15.8%, test_loss=0.881, train=14.0%, train_loss=0.839]

outcome_architecture/outcome:  72%|███████▏  | 1441/2000 [00:15<00:05, 94.60it/s, test=15.6%, test_loss=0.882, train=14.0%, train_loss=0.834]

outcome_architecture/outcome:  73%|███████▎  | 1451/2000 [00:15<00:06, 86.27it/s, test=15.6%, test_loss=0.882, train=14.0%, train_loss=0.834]

outcome_architecture/outcome:  73%|███████▎  | 1461/2000 [00:15<00:06, 89.60it/s, test=15.6%, test_loss=0.882, train=14.0%, train_loss=0.834]

outcome_architecture/outcome:  74%|███████▎  | 1471/2000 [00:15<00:05, 91.98it/s, test=15.6%, test_loss=0.882, train=14.0%, train_loss=0.834]

outcome_architecture/outcome:  74%|███████▍  | 1481/2000 [00:15<00:05, 93.52it/s, test=15.6%, test_loss=0.882, train=14.0%, train_loss=0.834]

outcome_architecture/outcome:  75%|███████▍  | 1491/2000 [00:15<00:05, 94.69it/s, test=15.6%, test_loss=0.882, train=14.0%, train_loss=0.834]

outcome_architecture/outcome:  75%|███████▍  | 1491/2000 [00:16<00:05, 94.69it/s, test=13.6%, test_loss=0.841, train=14.3%, train_loss=0.837]

outcome_architecture/outcome:  75%|███████▌  | 1501/2000 [00:16<00:05, 86.56it/s, test=13.6%, test_loss=0.841, train=14.3%, train_loss=0.837]

outcome_architecture/outcome:  76%|███████▌  | 1511/2000 [00:16<00:05, 89.46it/s, test=13.6%, test_loss=0.841, train=14.3%, train_loss=0.837]

outcome_architecture/outcome:  76%|███████▌  | 1521/2000 [00:16<00:05, 91.94it/s, test=13.6%, test_loss=0.841, train=14.3%, train_loss=0.837]

outcome_architecture/outcome:  77%|███████▋  | 1531/2000 [00:16<00:05, 93.68it/s, test=13.6%, test_loss=0.841, train=14.3%, train_loss=0.837]

outcome_architecture/outcome:  77%|███████▋  | 1541/2000 [00:16<00:04, 94.38it/s, test=13.6%, test_loss=0.841, train=14.3%, train_loss=0.837]

outcome_architecture/outcome:  77%|███████▋  | 1541/2000 [00:16<00:04, 94.38it/s, test=16.0%, test_loss=0.842, train=13.7%, train_loss=0.839]

outcome_architecture/outcome:  78%|███████▊  | 1551/2000 [00:16<00:05, 87.98it/s, test=16.0%, test_loss=0.842, train=13.7%, train_loss=0.839]

outcome_architecture/outcome:  78%|███████▊  | 1562/2000 [00:16<00:04, 92.97it/s, test=16.0%, test_loss=0.842, train=13.7%, train_loss=0.839]

outcome_architecture/outcome:  79%|███████▊  | 1573/2000 [00:16<00:04, 96.55it/s, test=16.0%, test_loss=0.842, train=13.7%, train_loss=0.839]

outcome_architecture/outcome:  79%|███████▉  | 1584/2000 [00:16<00:04, 99.26it/s, test=16.0%, test_loss=0.842, train=13.7%, train_loss=0.839]

outcome_architecture/outcome:  80%|███████▉  | 1595/2000 [00:17<00:04, 101.18it/s, test=16.0%, test_loss=0.842, train=13.7%, train_loss=0.839]

outcome_architecture/outcome:  80%|███████▉  | 1595/2000 [00:17<00:04, 101.18it/s, test=16.6%, test_loss=0.891, train=11.0%, train_loss=0.840]

outcome_architecture/outcome:  80%|████████  | 1606/2000 [00:17<00:04, 92.66it/s, test=16.6%, test_loss=0.891, train=11.0%, train_loss=0.840]

outcome_architecture/outcome:  81%|████████  | 1617/2000 [00:17<00:03, 96.28it/s, test=16.6%, test_loss=0.891, train=11.0%, train_loss=0.840]

outcome_architecture/outcome:  81%|████████▏ | 1628/2000 [00:17<00:03, 98.95it/s, test=16.6%, test_loss=0.891, train=11.0%, train_loss=0.840]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:17<00:03, 100.81it/s, test=16.6%, test_loss=0.891, train=11.0%, train_loss=0.840]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:17<00:03, 100.81it/s, test=14.4%, test_loss=0.832, train=13.7%, train_loss=0.849]

outcome_architecture/outcome:  82%|████████▎ | 1650/2000 [00:17<00:03, 92.82it/s, test=14.4%, test_loss=0.832, train=13.7%, train_loss=0.849]

outcome_architecture/outcome:  83%|████████▎ | 1661/2000 [00:17<00:03, 96.27it/s, test=14.4%, test_loss=0.832, train=13.7%, train_loss=0.849]

outcome_architecture/outcome:  84%|████████▎ | 1672/2000 [00:17<00:03, 98.95it/s, test=14.4%, test_loss=0.832, train=13.7%, train_loss=0.849]

outcome_architecture/outcome:  84%|████████▍ | 1683/2000 [00:17<00:03, 100.87it/s, test=14.4%, test_loss=0.832, train=13.7%, train_loss=0.849]

outcome_architecture/outcome:  85%|████████▍ | 1694/2000 [00:18<00:02, 102.34it/s, test=14.4%, test_loss=0.832, train=13.7%, train_loss=0.849]

outcome_architecture/outcome:  85%|████████▍ | 1694/2000 [00:18<00:02, 102.34it/s, test=15.2%, test_loss=0.806, train=13.0%, train_loss=0.859]

outcome_architecture/outcome:  85%|████████▌ | 1705/2000 [00:18<00:03, 93.58it/s, test=15.2%, test_loss=0.806, train=13.0%, train_loss=0.859]

outcome_architecture/outcome:  86%|████████▌ | 1716/2000 [00:18<00:02, 97.10it/s, test=15.2%, test_loss=0.806, train=13.0%, train_loss=0.859]

outcome_architecture/outcome:  86%|████████▋ | 1727/2000 [00:18<00:02, 99.65it/s, test=15.2%, test_loss=0.806, train=13.0%, train_loss=0.859]

outcome_architecture/outcome:  87%|████████▋ | 1738/2000 [00:18<00:02, 101.35it/s, test=15.2%, test_loss=0.806, train=13.0%, train_loss=0.859]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:18<00:02, 102.56it/s, test=15.2%, test_loss=0.806, train=13.0%, train_loss=0.859]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:18<00:02, 102.56it/s, test=15.0%, test_loss=0.854, train=12.0%, train_loss=0.880]

outcome_architecture/outcome:  88%|████████▊ | 1760/2000 [00:18<00:02, 93.52it/s, test=15.0%, test_loss=0.854, train=12.0%, train_loss=0.880]

outcome_architecture/outcome:  89%|████████▊ | 1771/2000 [00:18<00:02, 96.42it/s, test=15.0%, test_loss=0.854, train=12.0%, train_loss=0.880]

outcome_architecture/outcome:  89%|████████▉ | 1782/2000 [00:19<00:02, 98.78it/s, test=15.0%, test_loss=0.854, train=12.0%, train_loss=0.880]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 100.76it/s, test=15.0%, test_loss=0.854, train=12.0%, train_loss=0.880]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 100.76it/s, test=15.4%, test_loss=0.851, train=14.3%, train_loss=0.863]

outcome_architecture/outcome:  90%|█████████ | 1804/2000 [00:19<00:02, 92.66it/s, test=15.4%, test_loss=0.851, train=14.3%, train_loss=0.863]

outcome_architecture/outcome:  91%|█████████ | 1815/2000 [00:19<00:01, 96.25it/s, test=15.4%, test_loss=0.851, train=14.3%, train_loss=0.863]

outcome_architecture/outcome:  91%|█████████▏| 1826/2000 [00:19<00:01, 98.90it/s, test=15.4%, test_loss=0.851, train=14.3%, train_loss=0.863]

outcome_architecture/outcome:  92%|█████████▏| 1837/2000 [00:19<00:01, 100.95it/s, test=15.4%, test_loss=0.851, train=14.3%, train_loss=0.863]

outcome_architecture/outcome:  92%|█████████▏| 1848/2000 [00:19<00:01, 102.34it/s, test=15.4%, test_loss=0.851, train=14.3%, train_loss=0.863]

outcome_architecture/outcome:  92%|█████████▏| 1848/2000 [00:19<00:01, 102.34it/s, test=13.8%, test_loss=0.836, train=11.7%, train_loss=0.864]

outcome_architecture/outcome:  93%|█████████▎| 1859/2000 [00:19<00:01, 93.55it/s, test=13.8%, test_loss=0.836, train=11.7%, train_loss=0.864]

outcome_architecture/outcome:  94%|█████████▎| 1870/2000 [00:19<00:01, 96.88it/s, test=13.8%, test_loss=0.836, train=11.7%, train_loss=0.864]

outcome_architecture/outcome:  94%|█████████▍| 1881/2000 [00:20<00:01, 99.07it/s, test=13.8%, test_loss=0.836, train=11.7%, train_loss=0.864]

outcome_architecture/outcome:  95%|█████████▍| 1892/2000 [00:20<00:01, 100.94it/s, test=13.8%, test_loss=0.836, train=11.7%, train_loss=0.864]

outcome_architecture/outcome:  95%|█████████▍| 1892/2000 [00:20<00:01, 100.94it/s, test=17.0%, test_loss=0.824, train=13.7%, train_loss=0.851]

outcome_architecture/outcome:  95%|█████████▌| 1903/2000 [00:20<00:01, 92.68it/s, test=17.0%, test_loss=0.824, train=13.7%, train_loss=0.851]

outcome_architecture/outcome:  96%|█████████▌| 1914/2000 [00:20<00:00, 96.29it/s, test=17.0%, test_loss=0.824, train=13.7%, train_loss=0.851]

outcome_architecture/outcome:  96%|█████████▋| 1925/2000 [00:20<00:00, 98.81it/s, test=17.0%, test_loss=0.824, train=13.7%, train_loss=0.851]

outcome_architecture/outcome:  97%|█████████▋| 1936/2000 [00:20<00:00, 100.91it/s, test=17.0%, test_loss=0.824, train=13.7%, train_loss=0.851]

outcome_architecture/outcome:  97%|█████████▋| 1947/2000 [00:20<00:00, 102.29it/s, test=17.0%, test_loss=0.824, train=13.7%, train_loss=0.851]

outcome_architecture/outcome:  97%|█████████▋| 1947/2000 [00:20<00:00, 102.29it/s, test=14.4%, test_loss=0.847, train=14.3%, train_loss=0.864]

outcome_architecture/outcome:  98%|█████████▊| 1958/2000 [00:20<00:00, 93.51it/s, test=14.4%, test_loss=0.847, train=14.3%, train_loss=0.864]

outcome_architecture/outcome:  98%|█████████▊| 1969/2000 [00:20<00:00, 96.87it/s, test=14.4%, test_loss=0.847, train=14.3%, train_loss=0.864]

outcome_architecture/outcome:  99%|█████████▉| 1980/2000 [00:21<00:00, 99.33it/s, test=14.4%, test_loss=0.847, train=14.3%, train_loss=0.864]

outcome_architecture/outcome: 100%|█████████▉| 1991/2000 [00:21<00:00, 101.13it/s, test=14.4%, test_loss=0.847, train=14.3%, train_loss=0.864]

outcome_architecture/outcome: 100%|█████████▉| 1991/2000 [00:21<00:00, 101.13it/s, test=15.9%, test_loss=0.829, train=14.0%, train_loss=0.833]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 94.08it/s, test=15.9%, test_loss=0.829, train=14.0%, train_loss=0.833]

architecture/mode:  75%|███████▌  | 3/4 [00:44<00:16, 16.24s/it]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.099, train=0.0%, train_loss=4.100]

outcome_architecture/process:   0%|          | 1/2000 [00:00<05:23,  6.18it/s, test=0.0%, test_loss=4.099, train=0.0%, train_loss=4.100]

outcome_architecture/process:   0%|          | 1/2000 [00:00<05:23,  6.18it/s, test=0.0%, test_loss=16.887, train=0.0%, train_loss=17.013]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:22,  6.19it/s, test=0.0%, test_loss=16.887, train=0.0%, train_loss=17.013]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:22,  6.19it/s, test=0.0%, test_loss=4.073, train=0.0%, train_loss=4.079]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:22,  6.19it/s, test=0.0%, test_loss=3.681, train=0.0%, train_loss=3.713]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:07, 29.53it/s, test=0.0%, test_loss=3.681, train=0.0%, train_loss=3.713]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:07, 29.53it/s, test=6.4%, test_loss=5.174, train=5.0%, train_loss=5.195]

outcome_architecture/process:   1%|          | 20/2000 [00:00<00:55, 35.57it/s, test=6.4%, test_loss=5.174, train=5.0%, train_loss=5.195]

outcome_architecture/process:   1%|          | 20/2000 [00:00<00:55, 35.57it/s, test=6.9%, test_loss=2.902, train=6.7%, train_loss=2.926]

outcome_architecture/process:   1%|▏         | 25/2000 [00:00<01:02, 31.72it/s, test=6.9%, test_loss=2.902, train=6.7%, train_loss=2.926]

outcome_architecture/process:   2%|▏         | 36/2000 [00:00<00:40, 47.99it/s, test=6.9%, test_loss=2.902, train=6.7%, train_loss=2.926]

outcome_architecture/process:   2%|▏         | 47/2000 [00:01<00:31, 61.73it/s, test=6.9%, test_loss=2.902, train=6.7%, train_loss=2.926]

outcome_architecture/process:   2%|▏         | 47/2000 [00:01<00:31, 61.73it/s, test=4.9%, test_loss=2.773, train=5.7%, train_loss=2.766]

outcome_architecture/process:   3%|▎         | 55/2000 [00:01<00:38, 50.53it/s, test=4.9%, test_loss=2.773, train=5.7%, train_loss=2.766]

outcome_architecture/process:   3%|▎         | 66/2000 [00:01<00:30, 62.48it/s, test=4.9%, test_loss=2.773, train=5.7%, train_loss=2.766]

outcome_architecture/process:   3%|▎         | 66/2000 [00:01<00:30, 62.48it/s, test=0.5%, test_loss=4.699, train=0.0%, train_loss=4.589]

outcome_architecture/process:   4%|▍         | 75/2000 [00:01<00:36, 53.19it/s, test=0.5%, test_loss=4.699, train=0.0%, train_loss=4.589]

outcome_architecture/process:   4%|▍         | 86/2000 [00:01<00:29, 64.07it/s, test=0.5%, test_loss=4.699, train=0.0%, train_loss=4.589]

outcome_architecture/process:   5%|▍         | 96/2000 [00:01<00:26, 72.01it/s, test=0.5%, test_loss=4.699, train=0.0%, train_loss=4.589]

outcome_architecture/process:   5%|▍         | 96/2000 [00:02<00:26, 72.01it/s, test=5.7%, test_loss=2.828, train=6.7%, train_loss=2.884]

outcome_architecture/process:   5%|▌         | 105/2000 [00:02<00:32, 57.60it/s, test=5.7%, test_loss=2.828, train=6.7%, train_loss=2.884]

outcome_architecture/process:   6%|▌         | 116/2000 [00:02<00:27, 67.76it/s, test=5.7%, test_loss=2.828, train=6.7%, train_loss=2.884]

outcome_architecture/process:   6%|▋         | 127/2000 [00:02<00:24, 76.61it/s, test=5.7%, test_loss=2.828, train=6.7%, train_loss=2.884]

outcome_architecture/process:   7%|▋         | 138/2000 [00:02<00:22, 82.93it/s, test=5.7%, test_loss=2.828, train=6.7%, train_loss=2.884]

outcome_architecture/process:   7%|▋         | 149/2000 [00:02<00:20, 88.33it/s, test=5.7%, test_loss=2.828, train=6.7%, train_loss=2.884]

outcome_architecture/process:   7%|▋         | 149/2000 [00:02<00:20, 88.33it/s, test=9.4%, test_loss=2.548, train=8.7%, train_loss=2.554]

outcome_architecture/process:   8%|▊         | 159/2000 [00:02<00:27, 66.17it/s, test=9.4%, test_loss=2.548, train=8.7%, train_loss=2.554]

outcome_architecture/process:   8%|▊         | 170/2000 [00:02<00:24, 74.62it/s, test=9.4%, test_loss=2.548, train=8.7%, train_loss=2.554]

outcome_architecture/process:   9%|▉         | 181/2000 [00:02<00:22, 81.79it/s, test=9.4%, test_loss=2.548, train=8.7%, train_loss=2.554]

outcome_architecture/process:  10%|▉         | 192/2000 [00:03<00:20, 87.69it/s, test=9.4%, test_loss=2.548, train=8.7%, train_loss=2.554]

outcome_architecture/process:  10%|▉         | 192/2000 [00:03<00:20, 87.69it/s, test=10.7%, test_loss=2.472, train=9.7%, train_loss=2.472]

outcome_architecture/process:  10%|█         | 202/2000 [00:03<00:27, 66.08it/s, test=10.7%, test_loss=2.472, train=9.7%, train_loss=2.472]

outcome_architecture/process:  11%|█         | 213/2000 [00:03<00:23, 74.55it/s, test=10.7%, test_loss=2.472, train=9.7%, train_loss=2.472]

outcome_architecture/process:  11%|█         | 224/2000 [00:03<00:21, 81.71it/s, test=10.7%, test_loss=2.472, train=9.7%, train_loss=2.472]

outcome_architecture/process:  12%|█▏        | 235/2000 [00:03<00:20, 87.62it/s, test=10.7%, test_loss=2.472, train=9.7%, train_loss=2.472]

outcome_architecture/process:  12%|█▏        | 246/2000 [00:03<00:19, 92.21it/s, test=10.7%, test_loss=2.472, train=9.7%, train_loss=2.472]

outcome_architecture/process:  12%|█▏        | 246/2000 [00:03<00:19, 92.21it/s, test=12.0%, test_loss=2.389, train=12.0%, train_loss=2.392]

outcome_architecture/process:  13%|█▎        | 256/2000 [00:03<00:25, 67.98it/s, test=12.0%, test_loss=2.389, train=12.0%, train_loss=2.392]

outcome_architecture/process:  13%|█▎        | 267/2000 [00:04<00:22, 76.15it/s, test=12.0%, test_loss=2.389, train=12.0%, train_loss=2.392]

outcome_architecture/process:  14%|█▍        | 278/2000 [00:04<00:20, 82.98it/s, test=12.0%, test_loss=2.389, train=12.0%, train_loss=2.392]

outcome_architecture/process:  14%|█▍        | 289/2000 [00:04<00:19, 88.50it/s, test=12.0%, test_loss=2.389, train=12.0%, train_loss=2.392]

outcome_architecture/process:  14%|█▍        | 289/2000 [00:04<00:19, 88.50it/s, test=10.1%, test_loss=2.271, train=9.0%, train_loss=2.246]

outcome_architecture/process:  15%|█▌        | 300/2000 [00:04<00:25, 67.33it/s, test=10.1%, test_loss=2.271, train=9.0%, train_loss=2.246]

outcome_architecture/process:  16%|█▌        | 311/2000 [00:04<00:22, 75.33it/s, test=10.1%, test_loss=2.271, train=9.0%, train_loss=2.246]

outcome_architecture/process:  16%|█▌        | 322/2000 [00:04<00:20, 82.19it/s, test=10.1%, test_loss=2.271, train=9.0%, train_loss=2.246]

outcome_architecture/process:  17%|█▋        | 333/2000 [00:04<00:18, 87.83it/s, test=10.1%, test_loss=2.271, train=9.0%, train_loss=2.246]

outcome_architecture/process:  17%|█▋        | 344/2000 [00:04<00:18, 91.65it/s, test=10.1%, test_loss=2.271, train=9.0%, train_loss=2.246]

outcome_architecture/process:  17%|█▋        | 344/2000 [00:05<00:18, 91.65it/s, test=10.4%, test_loss=2.439, train=10.0%, train_loss=2.418]

outcome_architecture/process:  18%|█▊        | 354/2000 [00:05<00:24, 67.76it/s, test=10.4%, test_loss=2.439, train=10.0%, train_loss=2.418]

outcome_architecture/process:  18%|█▊        | 365/2000 [00:05<00:21, 75.97it/s, test=10.4%, test_loss=2.439, train=10.0%, train_loss=2.418]

outcome_architecture/process:  19%|█▉        | 376/2000 [00:05<00:19, 82.76it/s, test=10.4%, test_loss=2.439, train=10.0%, train_loss=2.418]

outcome_architecture/process:  19%|█▉        | 387/2000 [00:05<00:18, 88.25it/s, test=10.4%, test_loss=2.439, train=10.0%, train_loss=2.418]

outcome_architecture/process:  20%|█▉        | 398/2000 [00:05<00:17, 92.48it/s, test=10.4%, test_loss=2.439, train=10.0%, train_loss=2.418]

outcome_architecture/process:  20%|█▉        | 398/2000 [00:05<00:17, 92.48it/s, test=13.3%, test_loss=2.153, train=9.7%, train_loss=2.122]

outcome_architecture/process:  20%|██        | 408/2000 [00:05<00:23, 68.17it/s, test=13.3%, test_loss=2.153, train=9.7%, train_loss=2.122]

outcome_architecture/process:  21%|██        | 419/2000 [00:06<00:20, 76.34it/s, test=13.3%, test_loss=2.153, train=9.7%, train_loss=2.122]

outcome_architecture/process:  22%|██▏       | 430/2000 [00:06<00:19, 82.60it/s, test=13.3%, test_loss=2.153, train=9.7%, train_loss=2.122]

outcome_architecture/process:  22%|██▏       | 441/2000 [00:06<00:17, 87.34it/s, test=13.3%, test_loss=2.153, train=9.7%, train_loss=2.122]

outcome_architecture/process:  22%|██▏       | 441/2000 [00:06<00:17, 87.34it/s, test=13.1%, test_loss=1.933, train=15.3%, train_loss=1.905]

outcome_architecture/process:  23%|██▎       | 451/2000 [00:06<00:23, 65.64it/s, test=13.1%, test_loss=1.933, train=15.3%, train_loss=1.905]

outcome_architecture/process:  23%|██▎       | 462/2000 [00:06<00:20, 73.44it/s, test=13.1%, test_loss=1.933, train=15.3%, train_loss=1.905]

outcome_architecture/process:  24%|██▎       | 473/2000 [00:06<00:19, 80.18it/s, test=13.1%, test_loss=1.933, train=15.3%, train_loss=1.905]

outcome_architecture/process:  24%|██▍       | 484/2000 [00:06<00:17, 86.17it/s, test=13.1%, test_loss=1.933, train=15.3%, train_loss=1.905]

outcome_architecture/process:  25%|██▍       | 495/2000 [00:06<00:16, 91.00it/s, test=13.1%, test_loss=1.933, train=15.3%, train_loss=1.905]

outcome_architecture/process:  25%|██▍       | 495/2000 [00:07<00:16, 91.00it/s, test=12.6%, test_loss=1.864, train=12.3%, train_loss=1.837]

outcome_architecture/process:  25%|██▌       | 505/2000 [00:07<00:22, 67.58it/s, test=12.6%, test_loss=1.864, train=12.3%, train_loss=1.837]

outcome_architecture/process:  26%|██▌       | 516/2000 [00:07<00:19, 75.91it/s, test=12.6%, test_loss=1.864, train=12.3%, train_loss=1.837]

outcome_architecture/process:  26%|██▋       | 527/2000 [00:07<00:17, 82.75it/s, test=12.6%, test_loss=1.864, train=12.3%, train_loss=1.837]

outcome_architecture/process:  27%|██▋       | 538/2000 [00:07<00:16, 88.28it/s, test=12.6%, test_loss=1.864, train=12.3%, train_loss=1.837]

outcome_architecture/process:  27%|██▋       | 549/2000 [00:07<00:15, 92.43it/s, test=12.6%, test_loss=1.864, train=12.3%, train_loss=1.837]

outcome_architecture/process:  27%|██▋       | 549/2000 [00:07<00:15, 92.43it/s, test=12.6%, test_loss=1.637, train=11.3%, train_loss=1.624]

outcome_architecture/process:  28%|██▊       | 559/2000 [00:07<00:21, 68.01it/s, test=12.6%, test_loss=1.637, train=11.3%, train_loss=1.624]

outcome_architecture/process:  28%|██▊       | 570/2000 [00:07<00:18, 76.06it/s, test=12.6%, test_loss=1.637, train=11.3%, train_loss=1.624]

outcome_architecture/process:  29%|██▉       | 581/2000 [00:08<00:17, 82.84it/s, test=12.6%, test_loss=1.637, train=11.3%, train_loss=1.624]

outcome_architecture/process:  30%|██▉       | 592/2000 [00:08<00:15, 88.43it/s, test=12.6%, test_loss=1.637, train=11.3%, train_loss=1.624]

outcome_architecture/process:  30%|██▉       | 592/2000 [00:08<00:15, 88.43it/s, test=10.9%, test_loss=1.360, train=12.3%, train_loss=1.385]

outcome_architecture/process:  30%|███       | 602/2000 [00:08<00:21, 66.54it/s, test=10.9%, test_loss=1.360, train=12.3%, train_loss=1.385]

outcome_architecture/process:  31%|███       | 613/2000 [00:08<00:18, 74.92it/s, test=10.9%, test_loss=1.360, train=12.3%, train_loss=1.385]

outcome_architecture/process:  31%|███       | 624/2000 [00:08<00:16, 82.05it/s, test=10.9%, test_loss=1.360, train=12.3%, train_loss=1.385]

outcome_architecture/process:  32%|███▏      | 635/2000 [00:08<00:15, 87.75it/s, test=10.9%, test_loss=1.360, train=12.3%, train_loss=1.385]

outcome_architecture/process:  32%|███▏      | 646/2000 [00:08<00:14, 92.19it/s, test=10.9%, test_loss=1.360, train=12.3%, train_loss=1.385]

outcome_architecture/process:  32%|███▏      | 646/2000 [00:08<00:14, 92.19it/s, test=14.3%, test_loss=1.130, train=13.3%, train_loss=1.136]

outcome_architecture/process:  33%|███▎      | 656/2000 [00:09<00:19, 68.19it/s, test=14.3%, test_loss=1.130, train=13.3%, train_loss=1.136]

outcome_architecture/process:  33%|███▎      | 667/2000 [00:09<00:17, 76.41it/s, test=14.3%, test_loss=1.130, train=13.3%, train_loss=1.136]

outcome_architecture/process:  34%|███▍      | 678/2000 [00:09<00:15, 83.23it/s, test=14.3%, test_loss=1.130, train=13.3%, train_loss=1.136]

outcome_architecture/process:  34%|███▍      | 689/2000 [00:09<00:14, 88.69it/s, test=14.3%, test_loss=1.130, train=13.3%, train_loss=1.136]

outcome_architecture/process:  34%|███▍      | 689/2000 [00:09<00:14, 88.69it/s, test=13.4%, test_loss=1.129, train=10.3%, train_loss=1.117]

outcome_architecture/process:  35%|███▌      | 700/2000 [00:09<00:19, 67.51it/s, test=13.4%, test_loss=1.129, train=10.3%, train_loss=1.117]

outcome_architecture/process:  36%|███▌      | 711/2000 [00:09<00:17, 75.64it/s, test=13.4%, test_loss=1.129, train=10.3%, train_loss=1.117]

outcome_architecture/process:  36%|███▌      | 722/2000 [00:09<00:15, 81.83it/s, test=13.4%, test_loss=1.129, train=10.3%, train_loss=1.117]

outcome_architecture/process:  37%|███▋      | 732/2000 [00:09<00:14, 86.17it/s, test=13.4%, test_loss=1.129, train=10.3%, train_loss=1.117]

outcome_architecture/process:  37%|███▋      | 743/2000 [00:10<00:13, 90.52it/s, test=13.4%, test_loss=1.129, train=10.3%, train_loss=1.117]

outcome_architecture/process:  37%|███▋      | 743/2000 [00:10<00:13, 90.52it/s, test=13.9%, test_loss=0.815, train=10.3%, train_loss=0.786]

outcome_architecture/process:  38%|███▊      | 753/2000 [00:10<00:18, 66.60it/s, test=13.9%, test_loss=0.815, train=10.3%, train_loss=0.786]

outcome_architecture/process:  38%|███▊      | 764/2000 [00:10<00:16, 74.79it/s, test=13.9%, test_loss=0.815, train=10.3%, train_loss=0.786]

outcome_architecture/process:  39%|███▉      | 775/2000 [00:10<00:15, 81.57it/s, test=13.9%, test_loss=0.815, train=10.3%, train_loss=0.786]

outcome_architecture/process:  39%|███▉      | 786/2000 [00:10<00:13, 86.82it/s, test=13.9%, test_loss=0.815, train=10.3%, train_loss=0.786]

outcome_architecture/process:  40%|███▉      | 796/2000 [00:10<00:13, 90.11it/s, test=13.9%, test_loss=0.815, train=10.3%, train_loss=0.786]

outcome_architecture/process:  40%|███▉      | 796/2000 [00:10<00:13, 90.11it/s, test=15.4%, test_loss=0.677, train=12.7%, train_loss=0.642]

outcome_architecture/process:  40%|████      | 806/2000 [00:10<00:17, 66.78it/s, test=15.4%, test_loss=0.677, train=12.7%, train_loss=0.642]

outcome_architecture/process:  41%|████      | 817/2000 [00:11<00:15, 75.36it/s, test=15.4%, test_loss=0.677, train=12.7%, train_loss=0.642]

outcome_architecture/process:  41%|████▏     | 828/2000 [00:11<00:14, 82.53it/s, test=15.4%, test_loss=0.677, train=12.7%, train_loss=0.642]

outcome_architecture/process:  42%|████▏     | 839/2000 [00:11<00:13, 88.24it/s, test=15.4%, test_loss=0.677, train=12.7%, train_loss=0.642]

outcome_architecture/process:  42%|████▏     | 839/2000 [00:11<00:13, 88.24it/s, test=15.9%, test_loss=0.648, train=17.0%, train_loss=0.622]

outcome_architecture/process:  42%|████▎     | 850/2000 [00:11<00:17, 67.05it/s, test=15.9%, test_loss=0.648, train=17.0%, train_loss=0.622]

outcome_architecture/process:  43%|████▎     | 861/2000 [00:11<00:15, 75.12it/s, test=15.9%, test_loss=0.648, train=17.0%, train_loss=0.622]

outcome_architecture/process:  44%|████▎     | 872/2000 [00:11<00:13, 82.06it/s, test=15.9%, test_loss=0.648, train=17.0%, train_loss=0.622]

outcome_architecture/process:  44%|████▍     | 883/2000 [00:11<00:12, 87.81it/s, test=15.9%, test_loss=0.648, train=17.0%, train_loss=0.622]

outcome_architecture/process:  45%|████▍     | 894/2000 [00:11<00:12, 91.86it/s, test=15.9%, test_loss=0.648, train=17.0%, train_loss=0.622]

outcome_architecture/process:  45%|████▍     | 894/2000 [00:12<00:12, 91.86it/s, test=19.7%, test_loss=0.554, train=17.3%, train_loss=0.529]

outcome_architecture/process:  45%|████▌     | 904/2000 [00:12<00:16, 67.13it/s, test=19.7%, test_loss=0.554, train=17.3%, train_loss=0.529]

outcome_architecture/process:  46%|████▌     | 915/2000 [00:12<00:14, 75.26it/s, test=19.7%, test_loss=0.554, train=17.3%, train_loss=0.529]

outcome_architecture/process:  46%|████▋     | 926/2000 [00:12<00:13, 81.96it/s, test=19.7%, test_loss=0.554, train=17.3%, train_loss=0.529]

outcome_architecture/process:  47%|████▋     | 937/2000 [00:12<00:12, 86.94it/s, test=19.7%, test_loss=0.554, train=17.3%, train_loss=0.529]

outcome_architecture/process:  47%|████▋     | 948/2000 [00:12<00:11, 91.17it/s, test=19.7%, test_loss=0.554, train=17.3%, train_loss=0.529]

outcome_architecture/process:  47%|████▋     | 948/2000 [00:12<00:11, 91.17it/s, test=26.1%, test_loss=0.431, train=24.7%, train_loss=0.399]

outcome_architecture/process:  48%|████▊     | 958/2000 [00:12<00:15, 66.65it/s, test=26.1%, test_loss=0.431, train=24.7%, train_loss=0.399]

outcome_architecture/process:  48%|████▊     | 969/2000 [00:12<00:13, 74.92it/s, test=26.1%, test_loss=0.431, train=24.7%, train_loss=0.399]

outcome_architecture/process:  49%|████▉     | 980/2000 [00:13<00:12, 81.82it/s, test=26.1%, test_loss=0.431, train=24.7%, train_loss=0.399]

outcome_architecture/process:  50%|████▉     | 991/2000 [00:13<00:11, 87.48it/s, test=26.1%, test_loss=0.431, train=24.7%, train_loss=0.399]

outcome_architecture/process:  50%|████▉     | 991/2000 [00:13<00:11, 87.48it/s, test=29.5%, test_loss=0.330, train=29.7%, train_loss=0.295]

outcome_architecture/process:  50%|█████     | 1001/2000 [00:13<00:15, 65.65it/s, test=29.5%, test_loss=0.330, train=29.7%, train_loss=0.295]

outcome_architecture/process:  51%|█████     | 1012/2000 [00:13<00:13, 73.89it/s, test=29.5%, test_loss=0.330, train=29.7%, train_loss=0.295]

outcome_architecture/process:  51%|█████     | 1023/2000 [00:13<00:12, 80.85it/s, test=29.5%, test_loss=0.330, train=29.7%, train_loss=0.295]

outcome_architecture/process:  52%|█████▏    | 1034/2000 [00:13<00:11, 86.64it/s, test=29.5%, test_loss=0.330, train=29.7%, train_loss=0.295]

outcome_architecture/process:  52%|█████▏    | 1045/2000 [00:13<00:10, 91.04it/s, test=29.5%, test_loss=0.330, train=29.7%, train_loss=0.295]

outcome_architecture/process:  52%|█████▏    | 1045/2000 [00:14<00:10, 91.04it/s, test=0.0%, test_loss=15750.312, train=0.0%, train_loss=14405.202]

outcome_architecture/process:  53%|█████▎    | 1055/2000 [00:14<00:14, 66.60it/s, test=0.0%, test_loss=15750.312, train=0.0%, train_loss=14405.202]

outcome_architecture/process:  53%|█████▎    | 1066/2000 [00:14<00:12, 74.60it/s, test=0.0%, test_loss=15750.312, train=0.0%, train_loss=14405.202]

outcome_architecture/process:  54%|█████▍    | 1077/2000 [00:14<00:11, 81.42it/s, test=0.0%, test_loss=15750.312, train=0.0%, train_loss=14405.202]

outcome_architecture/process:  54%|█████▍    | 1088/2000 [00:14<00:10, 87.10it/s, test=0.0%, test_loss=15750.312, train=0.0%, train_loss=14405.202]

outcome_architecture/process:  55%|█████▍    | 1099/2000 [00:14<00:09, 91.57it/s, test=0.0%, test_loss=15750.312, train=0.0%, train_loss=14405.202]

outcome_architecture/process:  55%|█████▍    | 1099/2000 [00:14<00:09, 91.57it/s, test=0.1%, test_loss=70386.672, train=0.0%, train_loss=67532.133]

outcome_architecture/process:  55%|█████▌    | 1109/2000 [00:14<00:13, 67.24it/s, test=0.1%, test_loss=70386.672, train=0.0%, train_loss=67532.133]

outcome_architecture/process:  56%|█████▌    | 1120/2000 [00:14<00:11, 75.25it/s, test=0.1%, test_loss=70386.672, train=0.0%, train_loss=67532.133]

outcome_architecture/process:  57%|█████▋    | 1131/2000 [00:15<00:10, 82.15it/s, test=0.1%, test_loss=70386.672, train=0.0%, train_loss=67532.133]

outcome_architecture/process:  57%|█████▋    | 1142/2000 [00:15<00:09, 87.78it/s, test=0.1%, test_loss=70386.672, train=0.0%, train_loss=67532.133]

outcome_architecture/process:  57%|█████▋    | 1142/2000 [00:15<00:09, 87.78it/s, test=0.0%, test_loss=4307.583, train=0.0%, train_loss=3690.511]

outcome_architecture/process:  58%|█████▊    | 1152/2000 [00:15<00:13, 64.97it/s, test=0.0%, test_loss=4307.583, train=0.0%, train_loss=3690.511]

outcome_architecture/process:  58%|█████▊    | 1163/2000 [00:15<00:11, 73.55it/s, test=0.0%, test_loss=4307.583, train=0.0%, train_loss=3690.511]

outcome_architecture/process:  59%|█████▊    | 1174/2000 [00:15<00:10, 80.91it/s, test=0.0%, test_loss=4307.583, train=0.0%, train_loss=3690.511]

outcome_architecture/process:  59%|█████▉    | 1185/2000 [00:15<00:09, 86.68it/s, test=0.0%, test_loss=4307.583, train=0.0%, train_loss=3690.511]

outcome_architecture/process:  60%|█████▉    | 1196/2000 [00:15<00:08, 91.29it/s, test=0.0%, test_loss=4307.583, train=0.0%, train_loss=3690.511]

outcome_architecture/process:  60%|█████▉    | 1196/2000 [00:15<00:08, 91.29it/s, test=0.7%, test_loss=445.614, train=1.3%, train_loss=418.100]

outcome_architecture/process:  60%|██████    | 1206/2000 [00:16<00:11, 67.60it/s, test=0.7%, test_loss=445.614, train=1.3%, train_loss=418.100]

outcome_architecture/process:  61%|██████    | 1217/2000 [00:16<00:10, 75.89it/s, test=0.7%, test_loss=445.614, train=1.3%, train_loss=418.100]

outcome_architecture/process:  61%|██████▏   | 1228/2000 [00:16<00:09, 82.87it/s, test=0.7%, test_loss=445.614, train=1.3%, train_loss=418.100]

outcome_architecture/process:  62%|██████▏   | 1239/2000 [00:16<00:08, 88.23it/s, test=0.7%, test_loss=445.614, train=1.3%, train_loss=418.100]

outcome_architecture/process:  62%|██████▏   | 1239/2000 [00:16<00:08, 88.23it/s, test=2.6%, test_loss=221.487, train=2.3%, train_loss=209.270]

outcome_architecture/process:  62%|██████▎   | 1250/2000 [00:16<00:11, 66.79it/s, test=2.6%, test_loss=221.487, train=2.3%, train_loss=209.270]

outcome_architecture/process:  63%|██████▎   | 1260/2000 [00:16<00:10, 73.54it/s, test=2.6%, test_loss=221.487, train=2.3%, train_loss=209.270]

outcome_architecture/process:  64%|██████▎   | 1271/2000 [00:16<00:09, 80.53it/s, test=2.6%, test_loss=221.487, train=2.3%, train_loss=209.270]

outcome_architecture/process:  64%|██████▍   | 1282/2000 [00:16<00:08, 85.78it/s, test=2.6%, test_loss=221.487, train=2.3%, train_loss=209.270]

outcome_architecture/process:  65%|██████▍   | 1293/2000 [00:17<00:07, 90.18it/s, test=2.6%, test_loss=221.487, train=2.3%, train_loss=209.270]

outcome_architecture/process:  65%|██████▍   | 1293/2000 [00:17<00:07, 90.18it/s, test=1.1%, test_loss=145.492, train=0.3%, train_loss=135.630]

outcome_architecture/process:  65%|██████▌   | 1303/2000 [00:17<00:10, 66.69it/s, test=1.1%, test_loss=145.492, train=0.3%, train_loss=135.630]

outcome_architecture/process:  66%|██████▌   | 1313/2000 [00:17<00:09, 73.16it/s, test=1.1%, test_loss=145.492, train=0.3%, train_loss=135.630]

outcome_architecture/process:  66%|██████▌   | 1323/2000 [00:17<00:08, 78.60it/s, test=1.1%, test_loss=145.492, train=0.3%, train_loss=135.630]

outcome_architecture/process:  67%|██████▋   | 1333/2000 [00:17<00:08, 83.25it/s, test=1.1%, test_loss=145.492, train=0.3%, train_loss=135.630]

outcome_architecture/process:  67%|██████▋   | 1343/2000 [00:17<00:07, 86.32it/s, test=1.1%, test_loss=145.492, train=0.3%, train_loss=135.630]

outcome_architecture/process:  67%|██████▋   | 1343/2000 [00:17<00:07, 86.32it/s, test=0.0%, test_loss=137.555, train=0.0%, train_loss=123.821]

outcome_architecture/process:  68%|██████▊   | 1353/2000 [00:17<00:10, 63.91it/s, test=0.0%, test_loss=137.555, train=0.0%, train_loss=123.821]

outcome_architecture/process:  68%|██████▊   | 1363/2000 [00:18<00:08, 71.06it/s, test=0.0%, test_loss=137.555, train=0.0%, train_loss=123.821]

outcome_architecture/process:  69%|██████▊   | 1373/2000 [00:18<00:08, 77.26it/s, test=0.0%, test_loss=137.555, train=0.0%, train_loss=123.821]

outcome_architecture/process:  69%|██████▉   | 1383/2000 [00:18<00:07, 82.28it/s, test=0.0%, test_loss=137.555, train=0.0%, train_loss=123.821]

outcome_architecture/process:  70%|██████▉   | 1393/2000 [00:18<00:07, 86.30it/s, test=0.0%, test_loss=137.555, train=0.0%, train_loss=123.821]

outcome_architecture/process:  70%|██████▉   | 1393/2000 [00:18<00:07, 86.30it/s, test=0.0%, test_loss=168.209, train=0.0%, train_loss=153.322]

outcome_architecture/process:  70%|███████   | 1403/2000 [00:18<00:09, 63.81it/s, test=0.0%, test_loss=168.209, train=0.0%, train_loss=153.322]

outcome_architecture/process:  71%|███████   | 1413/2000 [00:18<00:08, 71.02it/s, test=0.0%, test_loss=168.209, train=0.0%, train_loss=153.322]

outcome_architecture/process:  71%|███████   | 1423/2000 [00:18<00:07, 77.08it/s, test=0.0%, test_loss=168.209, train=0.0%, train_loss=153.322]

outcome_architecture/process:  72%|███████▏  | 1433/2000 [00:18<00:06, 82.13it/s, test=0.0%, test_loss=168.209, train=0.0%, train_loss=153.322]

outcome_architecture/process:  72%|███████▏  | 1443/2000 [00:19<00:06, 86.24it/s, test=0.0%, test_loss=168.209, train=0.0%, train_loss=153.322]

outcome_architecture/process:  72%|███████▏  | 1443/2000 [00:19<00:06, 86.24it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  73%|███████▎  | 1453/2000 [00:19<00:08, 60.85it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  73%|███████▎  | 1461/2000 [00:19<00:08, 64.78it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  73%|███████▎  | 1469/2000 [00:19<00:07, 67.88it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  74%|███████▍  | 1478/2000 [00:19<00:07, 72.15it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  74%|███████▍  | 1488/2000 [00:19<00:06, 78.83it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  75%|███████▍  | 1498/2000 [00:19<00:05, 83.73it/s, test=1.5%, test_loss=83.216, train=2.0%, train_loss=79.921]

outcome_architecture/process:  75%|███████▍  | 1498/2000 [00:19<00:05, 83.73it/s, test=0.0%, test_loss=171.740, train=0.0%, train_loss=168.024]

outcome_architecture/process:  75%|███████▌  | 1507/2000 [00:20<00:07, 61.71it/s, test=0.0%, test_loss=171.740, train=0.0%, train_loss=168.024]

outcome_architecture/process:  76%|███████▌  | 1517/2000 [00:20<00:06, 69.75it/s, test=0.0%, test_loss=171.740, train=0.0%, train_loss=168.024]

outcome_architecture/process:  76%|███████▋  | 1527/2000 [00:20<00:06, 76.61it/s, test=0.0%, test_loss=171.740, train=0.0%, train_loss=168.024]

outcome_architecture/process:  77%|███████▋  | 1537/2000 [00:20<00:05, 82.02it/s, test=0.0%, test_loss=171.740, train=0.0%, train_loss=168.024]

outcome_architecture/process:  77%|███████▋  | 1547/2000 [00:20<00:05, 85.98it/s, test=0.0%, test_loss=171.740, train=0.0%, train_loss=168.024]

outcome_architecture/process:  77%|███████▋  | 1547/2000 [00:20<00:05, 85.98it/s, test=1.3%, test_loss=70.101, train=1.3%, train_loss=74.352]

outcome_architecture/process:  78%|███████▊  | 1557/2000 [00:20<00:06, 63.51it/s, test=1.3%, test_loss=70.101, train=1.3%, train_loss=74.352]

outcome_architecture/process:  78%|███████▊  | 1567/2000 [00:20<00:06, 70.80it/s, test=1.3%, test_loss=70.101, train=1.3%, train_loss=74.352]

outcome_architecture/process:  79%|███████▉  | 1577/2000 [00:20<00:05, 77.28it/s, test=1.3%, test_loss=70.101, train=1.3%, train_loss=74.352]

outcome_architecture/process:  79%|███████▉  | 1587/2000 [00:21<00:05, 82.50it/s, test=1.3%, test_loss=70.101, train=1.3%, train_loss=74.352]

outcome_architecture/process:  80%|███████▉  | 1597/2000 [00:21<00:04, 86.69it/s, test=1.3%, test_loss=70.101, train=1.3%, train_loss=74.352]

outcome_architecture/process:  80%|███████▉  | 1597/2000 [00:21<00:04, 86.69it/s, test=0.0%, test_loss=51.118, train=0.0%, train_loss=54.004]

outcome_architecture/process:  80%|████████  | 1607/2000 [00:21<00:06, 64.08it/s, test=0.0%, test_loss=51.118, train=0.0%, train_loss=54.004]

outcome_architecture/process:  81%|████████  | 1617/2000 [00:21<00:05, 71.29it/s, test=0.0%, test_loss=51.118, train=0.0%, train_loss=54.004]

outcome_architecture/process:  81%|████████▏ | 1627/2000 [00:21<00:04, 77.33it/s, test=0.0%, test_loss=51.118, train=0.0%, train_loss=54.004]

outcome_architecture/process:  82%|████████▏ | 1637/2000 [00:21<00:04, 82.67it/s, test=0.0%, test_loss=51.118, train=0.0%, train_loss=54.004]

outcome_architecture/process:  82%|████████▏ | 1647/2000 [00:21<00:04, 86.44it/s, test=0.0%, test_loss=51.118, train=0.0%, train_loss=54.004]

outcome_architecture/process:  82%|████████▏ | 1647/2000 [00:21<00:04, 86.44it/s, test=1.4%, test_loss=45.983, train=0.7%, train_loss=47.379]

outcome_architecture/process:  83%|████████▎ | 1657/2000 [00:22<00:05, 63.85it/s, test=1.4%, test_loss=45.983, train=0.7%, train_loss=47.379]

outcome_architecture/process:  83%|████████▎ | 1667/2000 [00:22<00:04, 71.36it/s, test=1.4%, test_loss=45.983, train=0.7%, train_loss=47.379]

outcome_architecture/process:  84%|████████▍ | 1677/2000 [00:22<00:04, 77.79it/s, test=1.4%, test_loss=45.983, train=0.7%, train_loss=47.379]

outcome_architecture/process:  84%|████████▍ | 1687/2000 [00:22<00:03, 82.66it/s, test=1.4%, test_loss=45.983, train=0.7%, train_loss=47.379]

outcome_architecture/process:  85%|████████▍ | 1697/2000 [00:22<00:03, 86.37it/s, test=1.4%, test_loss=45.983, train=0.7%, train_loss=47.379]

outcome_architecture/process:  85%|████████▍ | 1697/2000 [00:22<00:03, 86.37it/s, test=3.3%, test_loss=56.334, train=2.7%, train_loss=49.871]

outcome_architecture/process:  85%|████████▌ | 1707/2000 [00:22<00:04, 63.84it/s, test=3.3%, test_loss=56.334, train=2.7%, train_loss=49.871]

outcome_architecture/process:  86%|████████▌ | 1717/2000 [00:22<00:03, 71.11it/s, test=3.3%, test_loss=56.334, train=2.7%, train_loss=49.871]

outcome_architecture/process:  86%|████████▋ | 1727/2000 [00:22<00:03, 77.41it/s, test=3.3%, test_loss=56.334, train=2.7%, train_loss=49.871]

outcome_architecture/process:  87%|████████▋ | 1737/2000 [00:23<00:03, 82.57it/s, test=3.3%, test_loss=56.334, train=2.7%, train_loss=49.871]

outcome_architecture/process:  87%|████████▋ | 1747/2000 [00:23<00:02, 86.36it/s, test=3.3%, test_loss=56.334, train=2.7%, train_loss=49.871]

outcome_architecture/process:  87%|████████▋ | 1747/2000 [00:23<00:02, 86.36it/s, test=3.4%, test_loss=48.821, train=2.7%, train_loss=48.312]

outcome_architecture/process:  88%|████████▊ | 1757/2000 [00:23<00:03, 64.70it/s, test=3.4%, test_loss=48.821, train=2.7%, train_loss=48.312]

outcome_architecture/process:  88%|████████▊ | 1768/2000 [00:23<00:03, 73.61it/s, test=3.4%, test_loss=48.821, train=2.7%, train_loss=48.312]

outcome_architecture/process:  89%|████████▉ | 1779/2000 [00:23<00:02, 81.13it/s, test=3.4%, test_loss=48.821, train=2.7%, train_loss=48.312]

outcome_architecture/process:  90%|████████▉ | 1790/2000 [00:23<00:02, 87.10it/s, test=3.4%, test_loss=48.821, train=2.7%, train_loss=48.312]

outcome_architecture/process:  90%|████████▉ | 1790/2000 [00:23<00:02, 87.10it/s, test=0.2%, test_loss=42.677, train=0.0%, train_loss=41.690]

outcome_architecture/process:  90%|█████████ | 1800/2000 [00:23<00:03, 65.87it/s, test=0.2%, test_loss=42.677, train=0.0%, train_loss=41.690]

outcome_architecture/process:  91%|█████████ | 1811/2000 [00:24<00:02, 74.24it/s, test=0.2%, test_loss=42.677, train=0.0%, train_loss=41.690]

outcome_architecture/process:  91%|█████████ | 1822/2000 [00:24<00:02, 81.46it/s, test=0.2%, test_loss=42.677, train=0.0%, train_loss=41.690]

outcome_architecture/process:  92%|█████████▏| 1833/2000 [00:24<00:01, 87.18it/s, test=0.2%, test_loss=42.677, train=0.0%, train_loss=41.690]

outcome_architecture/process:  92%|█████████▏| 1844/2000 [00:24<00:01, 91.55it/s, test=0.2%, test_loss=42.677, train=0.0%, train_loss=41.690]

outcome_architecture/process:  92%|█████████▏| 1844/2000 [00:24<00:01, 91.55it/s, test=0.0%, test_loss=47.014, train=0.0%, train_loss=43.314]

outcome_architecture/process:  93%|█████████▎| 1854/2000 [00:24<00:02, 67.84it/s, test=0.0%, test_loss=47.014, train=0.0%, train_loss=43.314]

outcome_architecture/process:  93%|█████████▎| 1865/2000 [00:24<00:01, 76.00it/s, test=0.0%, test_loss=47.014, train=0.0%, train_loss=43.314]

outcome_architecture/process:  94%|█████████▍| 1876/2000 [00:24<00:01, 82.85it/s, test=0.0%, test_loss=47.014, train=0.0%, train_loss=43.314]

outcome_architecture/process:  94%|█████████▍| 1887/2000 [00:24<00:01, 88.35it/s, test=0.0%, test_loss=47.014, train=0.0%, train_loss=43.314]

outcome_architecture/process:  95%|█████████▍| 1898/2000 [00:25<00:01, 92.66it/s, test=0.0%, test_loss=47.014, train=0.0%, train_loss=43.314]

outcome_architecture/process:  95%|█████████▍| 1898/2000 [00:25<00:01, 92.66it/s, test=0.0%, test_loss=39.558, train=0.0%, train_loss=38.653]

outcome_architecture/process:  95%|█████████▌| 1908/2000 [00:25<00:01, 68.20it/s, test=0.0%, test_loss=39.558, train=0.0%, train_loss=38.653]

outcome_architecture/process:  96%|█████████▌| 1919/2000 [00:25<00:01, 76.13it/s, test=0.0%, test_loss=39.558, train=0.0%, train_loss=38.653]

outcome_architecture/process:  96%|█████████▋| 1930/2000 [00:25<00:00, 82.58it/s, test=0.0%, test_loss=39.558, train=0.0%, train_loss=38.653]

outcome_architecture/process:  97%|█████████▋| 1941/2000 [00:25<00:00, 87.98it/s, test=0.0%, test_loss=39.558, train=0.0%, train_loss=38.653]

outcome_architecture/process:  97%|█████████▋| 1941/2000 [00:25<00:00, 87.98it/s, test=1.1%, test_loss=41.361, train=0.3%, train_loss=40.329]

outcome_architecture/process:  98%|█████████▊| 1951/2000 [00:25<00:00, 66.35it/s, test=1.1%, test_loss=41.361, train=0.3%, train_loss=40.329]

outcome_architecture/process:  98%|█████████▊| 1962/2000 [00:25<00:00, 74.68it/s, test=1.1%, test_loss=41.361, train=0.3%, train_loss=40.329]

outcome_architecture/process:  99%|█████████▊| 1973/2000 [00:26<00:00, 81.66it/s, test=1.1%, test_loss=41.361, train=0.3%, train_loss=40.329]

outcome_architecture/process:  99%|█████████▉| 1984/2000 [00:26<00:00, 87.44it/s, test=1.1%, test_loss=41.361, train=0.3%, train_loss=40.329]

outcome_architecture/process: 100%|█████████▉| 1995/2000 [00:26<00:00, 91.91it/s, test=1.1%, test_loss=41.361, train=0.3%, train_loss=40.329]

outcome_architecture/process: 100%|█████████▉| 1995/2000 [00:26<00:00, 91.91it/s, test=0.0%, test_loss=55.773, train=0.0%, train_loss=52.561]

outcome_architecture/process: 100%|██████████| 2000/2000 [00:26<00:00, 75.63it/s, test=0.0%, test_loss=55.773, train=0.0%, train_loss=52.561]

architecture/mode: 100%|██████████| 4/4 [01:11<00:00, 20.33s/it]

architecture/mode: 100%|██████████| 4/4 [01:11<00:00, 17.90s/it]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,outcome,4.282169,0.000000,0.000,0.0,4.282012
1,1,process_architecture,outcome,4.224769,0.000000,0.000,0.0,4.224516
2,2,process_architecture,outcome,4.145308,0.000000,0.000,0.0,4.145055
3,5,process_architecture,outcome,3.074533,0.000000,0.000,0.0,3.068828
4,10,process_architecture,outcome,1.804695,0.000000,0.000,0.0,1.781588
...,...,...,...,...,...,...,...,...
187,1800,outcome_architecture,process,41.689671,0.000000,0.002,0.0,42.677311
188,1850,outcome_architecture,process,43.314465,0.000000,0.000,0.0,47.014015
189,1900,outcome_architecture,process,38.653374,0.000000,0.000,0.0,39.557980
190,1950,outcome_architecture,process,40.329369,0.003333,0.011,0.0,41.361118
191,2000,outcome_architecture,process,52.560764,0.000000,0.000,0.0,55.772823

In [13]:

import json as _json, numpy as _np, pandas as _pd
def _clean(df):
    df = df.drop(columns=["circuit_matrix"], errors="ignore").copy()
    return _json.loads(df.to_json(orient="records"))

_payload = {
    "model_seed": MODEL_SEED,
    "steps": STEPS,
    "final_results": _clean(final_results),
    "history": _clean(history),
}
try:
    _payload["history_2x2"] = _clean(history_2x2)
except NameError:
    _payload["history_2x2"] = None

with open(_OUT_JSON, "w") as _f:
    _json.dump(_payload, _f, indent=2)
print("WROTE", _OUT_JSON)

WROTE /home/hariguru/aayus/trace/results/reachability_seeds/seed_44.json