
# Hand-coded solution reachability: train exactly two models

This notebook answers one precise question:

> The PROCESS and OUTCOME hand-coded Transformers already achieve 100% accuracy.  
> If we keep **each exact hand-coded architecture**, randomize its weights, and train it with its natural supervision, does gradient descent recover a 100%-accurate solution?

We train exactly **two models**:

| Trainable model | Architecture | Training target |
|---|---|---|
| `process_random_base` | exact `HandcodedProcessTransformer` layout | PROCESS / trace continuation |
| `outcome_random_base` | exact `HandcodedOutcomeTransformer` layout | OUTCOME-only continuation |

The two fixed hand-coded models are **references only** and are never optimized.

So the experiment is

\[
\boxed{
\text{2 fixed 100\% references}
+
\text{2 randomly initialized trainable models}
}
\]

with only the latter two undergoing gradient updates.

This is a **reachability experiment**, not yet an architecture-matched causal comparison between PROCESS and OUTCOME.


## 1. Imports and configuration

This notebook uses `handcoded_utils.py`, which contains the exact circuit generator, tokenizer, hand-coded architectures, training loop, and free-running evaluator.

In [1]:

import copy
import importlib
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

import handcoded_utils
importlib.reload(handcoded_utils)

from handcoded_utils import (
    BATCH_SIZE,
    BATCH_SEED,
    DATA_SEED,
    DEPTH,
    LR,
    MODEL_SEED,
    TEST_SEED,
    TEST_SIZE,
    TRAIN_SIZE,
    HandcodedOutcomeTransformer,
    HandcodedProcessTransformer,
    encode_dataset,
    free_run_metrics,
    generate,
    language_model_loss,
    make_batch_schedule,
    make_checkpoints,
    make_circuit_prompts,
    make_circuits,
    make_generation_evaluation,
    make_random_trainable_copy,
    make_tokenizer,
    train_one_model,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Main experiment settings.
N_TRAIN = TRAIN_SIZE
N_TEST = TEST_SIZE
STEPS = 2_000
LOSS_EVAL_SIZE = 64
CHECKPOINTS = make_checkpoints(STEPS, animation_checkpoints=40)

print("device:", DEVICE)
print("depth:", DEPTH)
print("train examples:", N_TRAIN)
print("test examples:", N_TEST)
print("steps:", STEPS)
print("loss eval examples:", LOSS_EVAL_SIZE)

device: cuda
depth: 4
train examples: 20000
test examples: 1000
steps: 2000
loss eval examples: 64

/home/hariguru/aayus/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# injected by run_seeds.py -- vary model init only
MODEL_SEED = 43
_OUT_JSON = '/home/hariguru/aayus/trace/results/reachability_seeds/seed_43.json'
print('MODEL_SEED =', MODEL_SEED)

MODEL_SEED = 43


## 2. Build the same dataset for both models

A circuit is

$$
s_t=\Phi(s_{t-1},g_t),\qquad t=1,\ldots,D.
$$

Both models receive the same prompt

```text
S0 g1 g2 ... gD <SEP>
```

but their supervised continuations differ.

PROCESS:

```text
g1 S1 g2 S2 ... gD SD <COLON> SD <EOS>
```

OUTCOME:

```text
<COLON> SD <EOS>
```

The underlying circuits, train/test split, and minibatch schedule are shared.

In [3]:

tokenizer = make_tokenizer()

train_circuits = make_circuits(N_TRAIN, DATA_SEED, DEPTH)
test_circuits = make_circuits(N_TEST, TEST_SEED, DEPTH)
example = test_circuits[0]

training_data = {
    mode: encode_dataset(train_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

# Held-out teacher-forced loss uses the test split. The training helper samples
# a deterministic prefix of this batch at checkpoints for speed.
test_loss_data = {
    mode: encode_dataset(test_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

batch_schedule = make_batch_schedule(
    N_TRAIN, STEPS, BATCH_SIZE, BATCH_SEED
)

train_eval = make_generation_evaluation(
    train_circuits[:min(300, len(train_circuits))],
    tokenizer,
    DEVICE,
)

test_eval = make_generation_evaluation(
    test_circuits,
    tokenizer,
    DEVICE,
)

circuit_prompts = make_circuit_prompts(
    example.gates,
    tokenizer,
    DEVICE,
)

print("Prompt :", tokenizer.decode(tokenizer.prompt(example)))
print("PROCESS:", tokenizer.decode(tokenizer.continuation(example, "process")))
print("OUTCOME:", tokenizer.decode(tokenizer.continuation(example, "outcome")))

Prompt : S1011 s02 c31 c31 t302 <SEP>
PROCESS: s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>
OUTCOME: <COLON> S1001 <EOS>


## 3. Fixed hand-coded references

These two models encode perfect algorithms directly in their weights.

### PROCESS reference

`HandcodedProcessTransformer`

- one causal attention/MLP block,
- four fixed attention heads,
- one ReLU unit for each `(state, gate)` pair,
- autoregressive reuse of the same block to emit intermediate states.

### OUTCOME reference

`HandcodedOutcomeTransformer`

- one causal attention/MLP block per circuit step,
- two attention heads per block,
- intermediate states remain internal to the residual stream,
- only the final answer is emitted.

They are not trained below. They establish that a 100% solution exists in each architecture class.

In [4]:

process_reference = HandcodedProcessTransformer(
    tokenizer, DEPTH
).to(DEVICE)

outcome_reference = HandcodedOutcomeTransformer(
    tokenizer, DEPTH
).to(DEVICE)

reference_rows = []

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    reference_rows.append({
        "model": name,
        "mode": mode,
        "answer_accuracy": metrics["final_answer"],
        "exact_continuation": metrics["exact_continuation"],
    })

pd.DataFrame(reference_rows)

           model     mode  answer_accuracy  exact_continuation
0  Fixed PROCESS  process              1.0                 1.0
1  Fixed OUTCOME  outcome              1.0                 1.0


Expected result:

$$
\operatorname{Acc}(\theta^\star_{\rm P})
=
\operatorname{Acc}(\theta^\star_{\rm O})
=
100\%.
$$

That is the realizability baseline.


## 4. Turn each exact hand-coded architecture into a random trainable model

This is the crucial correction.

We do **not** call `build_random_learned_model()`. That would create an unrelated ordinary one-layer Transformer.

Instead, `make_random_trainable_copy()`:

1. deep-copies the exact hand-coded model,
2. converts its stored weight buffers into `nn.Parameter`s,
3. randomly initializes those tensors.

Therefore the computational graph and tensor layout are inherited directly from the corresponding constructive model.

In [5]:

process_random_base = make_random_trainable_copy(
    process_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

outcome_random_base = make_random_trainable_copy(
    outcome_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

def trainable_params(model):
    return sum(p.numel() for p in model.parameters())

def stored_scalars(model):
    return sum(t.numel() for t in model.state_dict().values())

summary = pd.DataFrame([
    {
        "model": "Fixed PROCESS reference",
        "trainable_parameters": trainable_params(process_reference),
        "stored_scalars": stored_scalars(process_reference),
        "max_length": process_reference.max_length,
    },
    {
        "model": "Random trainable PROCESS architecture",
        "trainable_parameters": trainable_params(process_random_base),
        "stored_scalars": stored_scalars(process_random_base),
        "max_length": process_random_base.max_length,
    },
    {
        "model": "Fixed OUTCOME reference",
        "trainable_parameters": trainable_params(outcome_reference),
        "stored_scalars": stored_scalars(outcome_reference),
        "max_length": outcome_reference.max_length,
    },
    {
        "model": "Random trainable OUTCOME architecture",
        "trainable_parameters": trainable_params(outcome_random_base),
        "stored_scalars": stored_scalars(outcome_random_base),
        "max_length": outcome_random_base.max_length,
    },
])

summary

,model,trainable_parameters,stored_scalars,max_length
0,Fixed PROCESS reference,0,441664,16
1,Random trainable PROCESS architecture,441664,441664,16
2,Fixed OUTCOME reference,0,3588000,8
3,Random trainable OUTCOME architecture,3588000,3588000,8


A fixed reference reports zero **trainable** parameters because its constructed weights are registered as buffers. That does not mean it has zero weights. `stored_scalars` is the more relevant size diagnostic for the fixed models.


## 5. Sanity check: the trainable parameterization really contains the oracle

A useful stronger check is to convert the fixed buffers into trainable parameters **without changing their values**.

If the resulting model produces exactly the same logits as the fixed model, then the hand-coded optimum literally lies inside the trainable parameterization.

In [6]:

def make_trainable_oracle_copy(model, device):
    trainable = copy.deepcopy(model).cpu()

    def convert(module):
        for name, buffer in list(module._buffers.items()):
            if buffer is None:
                continue
            value = buffer.detach().clone()
            del module._buffers[name]
            module.register_parameter(name, torch.nn.Parameter(value))
        for child in module.children():
            convert(child)

    convert(trainable)
    return trainable.to(device)


process_oracle_trainable = make_trainable_oracle_copy(
    process_reference, DEVICE
)
outcome_oracle_trainable = make_trainable_oracle_copy(
    outcome_reference, DEVICE
)

prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

with torch.no_grad():
    process_error = (
        process_reference(prompt) - process_oracle_trainable(prompt)
    ).abs().max().item()

    outcome_error = (
        outcome_reference(prompt) - outcome_oracle_trainable(prompt)
    ).abs().max().item()

print("PROCESS max logit difference:", process_error)
print("OUTCOME max logit difference:", outcome_error)

assert process_error == 0.0
assert outcome_error == 0.0

PROCESS max logit difference: 0.0
OUTCOME max logit difference: 0.0


This gives the precise existence statement:

\[
\exists\,\theta^\star_{\rm P}\in\Theta_{\rm P},
\qquad
\exists\,\theta^\star_{\rm O}\in\Theta_{\rm O},
\]

with both achieving perfect execution.

The training experiment now asks whether random initialization reaches either solution class.


## 6. Train exactly two models

There is no `run_experiment(base, modes=("outcome","process"))` here.

That function would train two copies of the **same base architecture**.

Instead we make two explicit calls:

\[
\boxed{
\text{PROCESS architecture}+\text{PROCESS supervision}
}
\]

and

\[
\boxed{
\text{OUTCOME architecture}+\text{OUTCOME supervision}.
}
\]

So exactly two optimization runs occur.

In [7]:

trained_process, process_history = train_one_model(
    process_random_base,
    "process",
    training_data["process"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="process_architecture",
    test_loss_data=test_loss_data["process"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

trained_outcome, outcome_history = train_one_model(
    outcome_random_base,
    "outcome",
    training_data["outcome"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="outcome_architecture",
    test_loss_data=test_loss_data["outcome"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

history = pd.concat(
    [process_history, outcome_history],
    ignore_index=True,
)

display(
    history.drop(columns=["circuit_matrix"], errors="ignore")
)

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.262, train=0.0%, train_loss=4.263]

process_architecture/process:   0%|          | 1/2000 [00:00<06:32,  5.09it/s, test=0.0%, test_loss=4.262, train=0.0%, train_loss=4.263]

process_architecture/process:   0%|          | 1/2000 [00:00<06:32,  5.09it/s, test=0.0%, test_loss=4.240, train=0.0%, train_loss=4.241]

process_architecture/process:   0%|          | 1/2000 [00:00<06:32,  5.09it/s, test=0.0%, test_loss=3.942, train=0.0%, train_loss=3.956]

process_architecture/process:   0%|          | 5/2000 [00:00<01:52, 17.78it/s, test=0.0%, test_loss=3.942, train=0.0%, train_loss=3.956]

process_architecture/process:   0%|          | 5/2000 [00:00<01:52, 17.78it/s, test=0.0%, test_loss=3.663, train=0.0%, train_loss=3.676]

process_architecture/process:   0%|          | 5/2000 [00:00<01:52, 17.78it/s, test=7.7%, test_loss=2.991, train=4.0%, train_loss=2.996]

process_architecture/process:   1%|          | 20/2000 [00:00<00:36, 54.99it/s, test=7.7%, test_loss=2.991, train=4.0%, train_loss=2.996]

process_architecture/process:   1%|          | 20/2000 [00:00<00:36, 54.99it/s, test=6.5%, test_loss=2.752, train=8.7%, train_loss=2.771]

process_architecture/process:   1%|▏         | 29/2000 [00:00<00:30, 65.40it/s, test=6.5%, test_loss=2.752, train=8.7%, train_loss=2.771]

process_architecture/process:   2%|▏         | 48/2000 [00:00<00:19, 102.64it/s, test=6.5%, test_loss=2.752, train=8.7%, train_loss=2.771]

process_architecture/process:   2%|▏         | 48/2000 [00:00<00:19, 102.64it/s, test=8.1%, test_loss=2.570, train=4.7%, train_loss=2.595]

process_architecture/process:   3%|▎         | 60/2000 [00:00<00:18, 102.84it/s, test=8.1%, test_loss=2.570, train=4.7%, train_loss=2.595]

process_architecture/process:   3%|▎         | 60/2000 [00:00<00:18, 102.84it/s, test=11.4%, test_loss=2.382, train=7.7%, train_loss=2.417]

process_architecture/process:   4%|▍         | 75/2000 [00:00<00:18, 106.91it/s, test=11.4%, test_loss=2.382, train=7.7%, train_loss=2.417]

process_architecture/process:   5%|▍         | 95/2000 [00:01<00:14, 131.35it/s, test=11.4%, test_loss=2.382, train=7.7%, train_loss=2.417]

process_architecture/process:   5%|▍         | 95/2000 [00:01<00:14, 131.35it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   5%|▌         | 109/2000 [00:01<00:15, 124.42it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   6%|▋         | 128/2000 [00:01<00:13, 142.03it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   7%|▋         | 148/2000 [00:01<00:11, 156.04it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   7%|▋         | 148/2000 [00:01<00:11, 156.04it/s, test=13.2%, test_loss=1.918, train=10.7%, train_loss=1.904]

process_architecture/process:   8%|▊         | 165/2000 [00:01<00:12, 143.37it/s, test=13.2%, test_loss=1.918, train=10.7%, train_loss=1.904]

process_architecture/process:   9%|▉         | 185/2000 [00:01<00:11, 156.35it/s, test=13.2%, test_loss=1.918, train=10.7%, train_loss=1.904]

process_architecture/process:   9%|▉         | 185/2000 [00:01<00:11, 156.35it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  10%|█         | 202/2000 [00:01<00:12, 143.52it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  11%|█         | 222/2000 [00:01<00:11, 156.36it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  12%|█▏        | 241/2000 [00:01<00:10, 165.11it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  12%|█▏        | 241/2000 [00:02<00:10, 165.11it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  13%|█▎        | 258/2000 [00:02<00:11, 149.16it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  14%|█▍        | 277/2000 [00:02<00:10, 159.42it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  15%|█▍        | 297/2000 [00:02<00:10, 168.20it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  15%|█▍        | 297/2000 [00:02<00:10, 168.20it/s, test=68.9%, test_loss=0.094, train=68.0%, train_loss=0.093]

process_architecture/process:  16%|█▌        | 315/2000 [00:02<00:11, 151.90it/s, test=68.9%, test_loss=0.094, train=68.0%, train_loss=0.093]

process_architecture/process:  17%|█▋        | 335/2000 [00:02<00:10, 162.42it/s, test=68.9%, test_loss=0.094, train=68.0%, train_loss=0.093]

process_architecture/process:  17%|█▋        | 335/2000 [00:02<00:10, 162.42it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  18%|█▊        | 352/2000 [00:02<00:11, 147.83it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  19%|█▊        | 371/2000 [00:02<00:10, 158.33it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  20%|█▉        | 391/2000 [00:02<00:09, 167.85it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  20%|█▉        | 391/2000 [00:02<00:09, 167.85it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  20%|██        | 409/2000 [00:03<00:10, 152.50it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  21%|██▏       | 428/2000 [00:03<00:09, 162.19it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  22%|██▏       | 447/2000 [00:03<00:09, 168.85it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  22%|██▏       | 447/2000 [00:03<00:09, 168.85it/s, test=98.6%, test_loss=0.008, train=98.3%, train_loss=0.008]

process_architecture/process:  23%|██▎       | 465/2000 [00:03<00:09, 154.45it/s, test=98.6%, test_loss=0.008, train=98.3%, train_loss=0.008]

process_architecture/process:  24%|██▍       | 486/2000 [00:03<00:09, 168.13it/s, test=98.6%, test_loss=0.008, train=98.3%, train_loss=0.008]

process_architecture/process:  24%|██▍       | 486/2000 [00:03<00:09, 168.13it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  25%|██▌       | 504/2000 [00:03<00:09, 155.20it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  26%|██▌       | 524/2000 [00:03<00:08, 166.69it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  27%|██▋       | 544/2000 [00:03<00:08, 175.67it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  27%|██▋       | 544/2000 [00:03<00:08, 175.67it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  28%|██▊       | 563/2000 [00:03<00:08, 159.74it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  29%|██▉       | 584/2000 [00:04<00:08, 172.02it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  29%|██▉       | 584/2000 [00:04<00:08, 172.02it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  30%|███       | 602/2000 [00:04<00:08, 157.42it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  31%|███       | 623/2000 [00:04<00:08, 169.48it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 644/2000 [00:04<00:07, 178.37it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 644/2000 [00:04<00:07, 178.37it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  33%|███▎      | 663/2000 [00:04<00:08, 162.20it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 684/2000 [00:04<00:07, 174.04it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 684/2000 [00:04<00:07, 174.04it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  35%|███▌      | 702/2000 [00:04<00:08, 158.23it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  36%|███▌      | 723/2000 [00:04<00:07, 170.39it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  37%|███▋      | 744/2000 [00:05<00:06, 179.72it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  37%|███▋      | 744/2000 [00:05<00:06, 179.72it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  38%|███▊      | 763/2000 [00:05<00:07, 163.27it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  39%|███▉      | 784/2000 [00:05<00:06, 174.22it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  39%|███▉      | 784/2000 [00:05<00:06, 174.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  40%|████      | 802/2000 [00:05<00:07, 158.50it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  41%|████      | 823/2000 [00:05<00:06, 170.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  42%|████▏     | 844/2000 [00:05<00:06, 179.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  42%|████▏     | 844/2000 [00:05<00:06, 179.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  43%|████▎     | 863/2000 [00:05<00:06, 162.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  44%|████▍     | 884/2000 [00:05<00:06, 174.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  44%|████▍     | 884/2000 [00:05<00:06, 174.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 902/2000 [00:05<00:06, 158.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 923/2000 [00:06<00:06, 171.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 944/2000 [00:06<00:05, 181.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 944/2000 [00:06<00:05, 181.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 963/2000 [00:06<00:06, 163.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 984/2000 [00:06<00:05, 174.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 984/2000 [00:06<00:05, 174.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1003/2000 [00:06<00:06, 159.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1024/2000 [00:06<00:05, 171.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1045/2000 [00:06<00:05, 181.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1045/2000 [00:06<00:05, 181.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1064/2000 [00:06<00:05, 163.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1085/2000 [00:07<00:05, 174.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1085/2000 [00:07<00:05, 174.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1104/2000 [00:07<00:05, 159.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▋    | 1125/2000 [00:07<00:05, 171.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1146/2000 [00:07<00:04, 180.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1146/2000 [00:07<00:04, 180.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1165/2000 [00:07<00:05, 163.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1186/2000 [00:07<00:04, 173.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1186/2000 [00:07<00:04, 173.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1204/2000 [00:07<00:05, 158.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████▏   | 1225/2000 [00:07<00:04, 170.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1246/2000 [00:07<00:04, 180.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1246/2000 [00:08<00:04, 180.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1265/2000 [00:08<00:04, 163.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1287/2000 [00:08<00:04, 176.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1287/2000 [00:08<00:04, 176.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▌   | 1306/2000 [00:08<00:04, 160.43it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▋   | 1327/2000 [00:08<00:03, 172.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1348/2000 [00:08<00:03, 182.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1348/2000 [00:08<00:03, 182.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1367/2000 [00:08<00:03, 164.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1388/2000 [00:08<00:03, 175.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1388/2000 [00:08<00:03, 175.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1407/2000 [00:08<00:03, 160.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████▏  | 1428/2000 [00:09<00:03, 172.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████▏  | 1428/2000 [00:09<00:03, 172.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▎  | 1450/2000 [00:09<00:03, 160.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▎  | 1472/2000 [00:09<00:03, 173.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▍  | 1493/2000 [00:09<00:02, 181.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▍  | 1493/2000 [00:09<00:02, 181.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1512/2000 [00:09<00:02, 164.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1533/2000 [00:09<00:02, 175.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1533/2000 [00:09<00:02, 175.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1552/2000 [00:09<00:02, 161.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▊  | 1573/2000 [00:09<00:02, 172.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1594/2000 [00:10<00:02, 181.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|███████▉  | 1594/2000 [00:10<00:02, 181.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1613/2000 [00:10<00:02, 164.03it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1634/2000 [00:10<00:02, 175.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1634/2000 [00:10<00:02, 175.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1653/2000 [00:10<00:02, 160.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▎ | 1674/2000 [00:10<00:01, 172.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1695/2000 [00:10<00:01, 180.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1695/2000 [00:10<00:01, 180.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1714/2000 [00:10<00:01, 163.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1735/2000 [00:10<00:01, 175.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1735/2000 [00:10<00:01, 175.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1754/2000 [00:10<00:01, 159.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1775/2000 [00:11<00:01, 171.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1796/2000 [00:11<00:01, 180.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1796/2000 [00:11<00:01, 180.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1815/2000 [00:11<00:01, 164.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1836/2000 [00:11<00:00, 175.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1836/2000 [00:11<00:00, 175.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1855/2000 [00:11<00:00, 159.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1876/2000 [00:11<00:00, 171.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1897/2000 [00:11<00:00, 181.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1897/2000 [00:11<00:00, 181.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1916/2000 [00:11<00:00, 163.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1937/2000 [00:12<00:00, 175.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1937/2000 [00:12<00:00, 175.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1956/2000 [00:12<00:00, 160.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1977/2000 [00:12<00:00, 172.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1998/2000 [00:12<00:00, 182.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1998/2000 [00:12<00:00, 182.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 160.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.637, train=0.0%, train_loss=3.632]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=10.935, train=0.0%, train_loss=10.881]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.503, train=0.0%, train_loss=3.503]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:51, 38.43it/s, test=0.0%, test_loss=3.503, train=0.0%, train_loss=3.503]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:51, 38.43it/s, test=0.0%, test_loss=1.109, train=0.0%, train_loss=1.108]

outcome_architecture/outcome:   1%|          | 13/2000 [00:00<00:33, 59.46it/s, test=0.0%, test_loss=1.109, train=0.0%, train_loss=1.108]

outcome_architecture/outcome:   1%|          | 13/2000 [00:00<00:33, 59.46it/s, test=0.0%, test_loss=1.191, train=0.0%, train_loss=1.220]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:31, 63.84it/s, test=0.0%, test_loss=1.191, train=0.0%, train_loss=1.220]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:31, 63.84it/s, test=1.6%, test_loss=1.466, train=2.0%, train_loss=1.447]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:29, 66.09it/s, test=1.6%, test_loss=1.466, train=2.0%, train_loss=1.447]

outcome_architecture/outcome:   2%|▏         | 38/2000 [00:00<00:24, 80.48it/s, test=1.6%, test_loss=1.466, train=2.0%, train_loss=1.447]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:21, 89.32it/s, test=1.6%, test_loss=1.466, train=2.0%, train_loss=1.447]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:21, 89.32it/s, test=10.3%, test_loss=0.927, train=7.7%, train_loss=0.945]

outcome_architecture/outcome:   3%|▎         | 58/2000 [00:00<00:23, 84.34it/s, test=10.3%, test_loss=0.927, train=7.7%, train_loss=0.945]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 91.13it/s, test=10.3%, test_loss=0.927, train=7.7%, train_loss=0.945]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 91.13it/s, test=9.0%, test_loss=0.920, train=9.0%, train_loss=0.945]

outcome_architecture/outcome:   4%|▍         | 79/2000 [00:00<00:22, 86.48it/s, test=9.0%, test_loss=0.920, train=9.0%, train_loss=0.945]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:20, 92.23it/s, test=9.0%, test_loss=0.920, train=9.0%, train_loss=0.945]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:20, 92.23it/s, test=12.6%, test_loss=0.898, train=11.3%, train_loss=0.912]

outcome_architecture/outcome:   5%|▌         | 100/2000 [00:01<00:21, 87.06it/s, test=12.6%, test_loss=0.898, train=11.3%, train_loss=0.912]

outcome_architecture/outcome:   6%|▌         | 111/2000 [00:01<00:20, 92.39it/s, test=12.6%, test_loss=0.898, train=11.3%, train_loss=0.912]

outcome_architecture/outcome:   6%|▌         | 122/2000 [00:01<00:19, 96.40it/s, test=12.6%, test_loss=0.898, train=11.3%, train_loss=0.912]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:18, 99.27it/s, test=12.6%, test_loss=0.898, train=11.3%, train_loss=0.912]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 101.24it/s, test=12.6%, test_loss=0.898, train=11.3%, train_loss=0.912]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 101.24it/s, test=11.9%, test_loss=0.907, train=10.0%, train_loss=0.904]

outcome_architecture/outcome:   8%|▊         | 155/2000 [00:01<00:19, 93.47it/s, test=11.9%, test_loss=0.907, train=10.0%, train_loss=0.904]

outcome_architecture/outcome:   8%|▊         | 166/2000 [00:01<00:18, 97.01it/s, test=11.9%, test_loss=0.907, train=10.0%, train_loss=0.904]

outcome_architecture/outcome:   9%|▉         | 177/2000 [00:01<00:18, 99.58it/s, test=11.9%, test_loss=0.907, train=10.0%, train_loss=0.904]

outcome_architecture/outcome:   9%|▉         | 188/2000 [00:02<00:17, 101.52it/s, test=11.9%, test_loss=0.907, train=10.0%, train_loss=0.904]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 102.78it/s, test=11.9%, test_loss=0.907, train=10.0%, train_loss=0.904]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 102.78it/s, test=11.5%, test_loss=0.905, train=10.7%, train_loss=0.897]

outcome_architecture/outcome:  10%|█         | 210/2000 [00:02<00:18, 94.44it/s, test=11.5%, test_loss=0.905, train=10.7%, train_loss=0.897]

outcome_architecture/outcome:  11%|█         | 221/2000 [00:02<00:18, 97.47it/s, test=11.5%, test_loss=0.905, train=10.7%, train_loss=0.897]

outcome_architecture/outcome:  12%|█▏        | 232/2000 [00:02<00:17, 99.94it/s, test=11.5%, test_loss=0.905, train=10.7%, train_loss=0.897]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:17, 101.75it/s, test=11.5%, test_loss=0.905, train=10.7%, train_loss=0.897]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:17, 101.75it/s, test=12.0%, test_loss=0.888, train=10.3%, train_loss=0.892]

outcome_architecture/outcome:  13%|█▎        | 254/2000 [00:02<00:18, 93.92it/s, test=12.0%, test_loss=0.888, train=10.3%, train_loss=0.892]

outcome_architecture/outcome:  13%|█▎        | 265/2000 [00:02<00:17, 97.15it/s, test=12.0%, test_loss=0.888, train=10.3%, train_loss=0.892]

outcome_architecture/outcome:  14%|█▍        | 276/2000 [00:02<00:17, 99.79it/s, test=12.0%, test_loss=0.888, train=10.3%, train_loss=0.892]

outcome_architecture/outcome:  14%|█▍        | 287/2000 [00:03<00:16, 101.71it/s, test=12.0%, test_loss=0.888, train=10.3%, train_loss=0.892]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 103.03it/s, test=12.0%, test_loss=0.888, train=10.3%, train_loss=0.892]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 103.03it/s, test=12.6%, test_loss=0.903, train=7.0%, train_loss=0.898]

outcome_architecture/outcome:  15%|█▌        | 309/2000 [00:03<00:17, 94.16it/s, test=12.6%, test_loss=0.903, train=7.0%, train_loss=0.898]

outcome_architecture/outcome:  16%|█▌        | 320/2000 [00:03<00:17, 97.70it/s, test=12.6%, test_loss=0.903, train=7.0%, train_loss=0.898]

outcome_architecture/outcome:  17%|█▋        | 331/2000 [00:03<00:16, 100.15it/s, test=12.6%, test_loss=0.903, train=7.0%, train_loss=0.898]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:16, 102.08it/s, test=12.6%, test_loss=0.903, train=7.0%, train_loss=0.898]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:16, 102.08it/s, test=13.9%, test_loss=0.883, train=11.7%, train_loss=0.907]

outcome_architecture/outcome:  18%|█▊        | 353/2000 [00:03<00:17, 94.07it/s, test=13.9%, test_loss=0.883, train=11.7%, train_loss=0.907]

outcome_architecture/outcome:  18%|█▊        | 364/2000 [00:03<00:16, 97.43it/s, test=13.9%, test_loss=0.883, train=11.7%, train_loss=0.907]

outcome_architecture/outcome:  19%|█▉        | 375/2000 [00:03<00:16, 99.92it/s, test=13.9%, test_loss=0.883, train=11.7%, train_loss=0.907]

outcome_architecture/outcome:  19%|█▉        | 386/2000 [00:04<00:15, 101.52it/s, test=13.9%, test_loss=0.883, train=11.7%, train_loss=0.907]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 102.30it/s, test=13.9%, test_loss=0.883, train=11.7%, train_loss=0.907]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 102.30it/s, test=13.4%, test_loss=0.892, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  20%|██        | 408/2000 [00:04<00:16, 93.93it/s, test=13.4%, test_loss=0.892, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  21%|██        | 419/2000 [00:04<00:16, 97.38it/s, test=13.4%, test_loss=0.892, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  22%|██▏       | 430/2000 [00:04<00:15, 99.76it/s, test=13.4%, test_loss=0.892, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 101.59it/s, test=13.4%, test_loss=0.892, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 101.59it/s, test=15.7%, test_loss=0.874, train=12.7%, train_loss=0.849]

outcome_architecture/outcome:  23%|██▎       | 452/2000 [00:04<00:16, 93.86it/s, test=15.7%, test_loss=0.874, train=12.7%, train_loss=0.849]

outcome_architecture/outcome:  23%|██▎       | 463/2000 [00:04<00:15, 97.42it/s, test=15.7%, test_loss=0.874, train=12.7%, train_loss=0.849]

outcome_architecture/outcome:  24%|██▎       | 474/2000 [00:04<00:15, 99.85it/s, test=15.7%, test_loss=0.874, train=12.7%, train_loss=0.849]

outcome_architecture/outcome:  24%|██▍       | 485/2000 [00:05<00:14, 101.80it/s, test=15.7%, test_loss=0.874, train=12.7%, train_loss=0.849]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 102.65it/s, test=15.7%, test_loss=0.874, train=12.7%, train_loss=0.849]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 102.65it/s, test=10.4%, test_loss=0.921, train=11.7%, train_loss=0.978]

outcome_architecture/outcome:  25%|██▌       | 507/2000 [00:05<00:16, 93.05it/s, test=10.4%, test_loss=0.921, train=11.7%, train_loss=0.978]

outcome_architecture/outcome:  26%|██▌       | 518/2000 [00:05<00:15, 96.86it/s, test=10.4%, test_loss=0.921, train=11.7%, train_loss=0.978]

outcome_architecture/outcome:  26%|██▋       | 529/2000 [00:05<00:14, 99.75it/s, test=10.4%, test_loss=0.921, train=11.7%, train_loss=0.978]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 101.92it/s, test=10.4%, test_loss=0.921, train=11.7%, train_loss=0.978]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 101.92it/s, test=0.0%, test_loss=822.369, train=0.0%, train_loss=761.902]

outcome_architecture/outcome:  28%|██▊       | 551/2000 [00:05<00:15, 94.06it/s, test=0.0%, test_loss=822.369, train=0.0%, train_loss=761.902]

outcome_architecture/outcome:  28%|██▊       | 562/2000 [00:05<00:14, 97.65it/s, test=0.0%, test_loss=822.369, train=0.0%, train_loss=761.902]

outcome_architecture/outcome:  29%|██▊       | 573/2000 [00:05<00:14, 100.31it/s, test=0.0%, test_loss=822.369, train=0.0%, train_loss=761.902]

outcome_architecture/outcome:  29%|██▉       | 584/2000 [00:06<00:13, 102.25it/s, test=0.0%, test_loss=822.369, train=0.0%, train_loss=761.902]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 103.18it/s, test=0.0%, test_loss=822.369, train=0.0%, train_loss=761.902]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 103.18it/s, test=0.7%, test_loss=860.955, train=0.7%, train_loss=932.828]

outcome_architecture/outcome:  30%|███       | 606/2000 [00:06<00:14, 94.76it/s, test=0.7%, test_loss=860.955, train=0.7%, train_loss=932.828]

outcome_architecture/outcome:  31%|███       | 617/2000 [00:06<00:14, 98.21it/s, test=0.7%, test_loss=860.955, train=0.7%, train_loss=932.828]

outcome_architecture/outcome:  31%|███▏      | 628/2000 [00:06<00:13, 100.73it/s, test=0.7%, test_loss=860.955, train=0.7%, train_loss=932.828]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 102.68it/s, test=0.7%, test_loss=860.955, train=0.7%, train_loss=932.828]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 102.68it/s, test=1.0%, test_loss=557.121, train=1.0%, train_loss=469.519]

outcome_architecture/outcome:  32%|███▎      | 650/2000 [00:06<00:14, 94.62it/s, test=1.0%, test_loss=557.121, train=1.0%, train_loss=469.519]

outcome_architecture/outcome:  33%|███▎      | 661/2000 [00:06<00:13, 98.08it/s, test=1.0%, test_loss=557.121, train=1.0%, train_loss=469.519]

outcome_architecture/outcome:  34%|███▎      | 672/2000 [00:06<00:13, 100.59it/s, test=1.0%, test_loss=557.121, train=1.0%, train_loss=469.519]

outcome_architecture/outcome:  34%|███▍      | 683/2000 [00:07<00:13, 101.30it/s, test=1.0%, test_loss=557.121, train=1.0%, train_loss=469.519]

outcome_architecture/outcome:  35%|███▍      | 694/2000 [00:07<00:12, 101.60it/s, test=1.0%, test_loss=557.121, train=1.0%, train_loss=469.519]

outcome_architecture/outcome:  35%|███▍      | 694/2000 [00:07<00:12, 101.60it/s, test=0.2%, test_loss=4574.993, train=0.0%, train_loss=4704.599]

outcome_architecture/outcome:  35%|███▌      | 705/2000 [00:07<00:13, 93.03it/s, test=0.2%, test_loss=4574.993, train=0.0%, train_loss=4704.599]

outcome_architecture/outcome:  36%|███▌      | 716/2000 [00:07<00:13, 95.83it/s, test=0.2%, test_loss=4574.993, train=0.0%, train_loss=4704.599]

outcome_architecture/outcome:  36%|███▋      | 727/2000 [00:07<00:13, 97.86it/s, test=0.2%, test_loss=4574.993, train=0.0%, train_loss=4704.599]

outcome_architecture/outcome:  37%|███▋      | 738/2000 [00:07<00:12, 99.39it/s, test=0.2%, test_loss=4574.993, train=0.0%, train_loss=4704.599]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:07<00:12, 100.48it/s, test=0.2%, test_loss=4574.993, train=0.0%, train_loss=4704.599]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:07<00:12, 100.48it/s, test=0.8%, test_loss=1034.981, train=0.0%, train_loss=1223.000]

outcome_architecture/outcome:  38%|███▊      | 760/2000 [00:07<00:13, 92.48it/s, test=0.8%, test_loss=1034.981, train=0.0%, train_loss=1223.000]

outcome_architecture/outcome:  39%|███▊      | 771/2000 [00:08<00:12, 94.75it/s, test=0.8%, test_loss=1034.981, train=0.0%, train_loss=1223.000]

outcome_architecture/outcome:  39%|███▉      | 782/2000 [00:08<00:12, 96.50it/s, test=0.8%, test_loss=1034.981, train=0.0%, train_loss=1223.000]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:12, 98.25it/s, test=0.8%, test_loss=1034.981, train=0.0%, train_loss=1223.000]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:12, 98.25it/s, test=1.5%, test_loss=174.549, train=0.3%, train_loss=174.487]

outcome_architecture/outcome:  40%|████      | 803/2000 [00:08<00:13, 90.75it/s, test=1.5%, test_loss=174.549, train=0.3%, train_loss=174.487]

outcome_architecture/outcome:  41%|████      | 814/2000 [00:08<00:12, 94.30it/s, test=1.5%, test_loss=174.549, train=0.3%, train_loss=174.487]

outcome_architecture/outcome:  41%|████▏     | 825/2000 [00:08<00:12, 96.75it/s, test=1.5%, test_loss=174.549, train=0.3%, train_loss=174.487]

outcome_architecture/outcome:  42%|████▏     | 836/2000 [00:08<00:11, 98.63it/s, test=1.5%, test_loss=174.549, train=0.3%, train_loss=174.487]

outcome_architecture/outcome:  42%|████▏     | 847/2000 [00:08<00:11, 99.93it/s, test=1.5%, test_loss=174.549, train=0.3%, train_loss=174.487]

outcome_architecture/outcome:  42%|████▏     | 847/2000 [00:08<00:11, 99.93it/s, test=0.5%, test_loss=67.718, train=0.7%, train_loss=60.053]

outcome_architecture/outcome:  43%|████▎     | 858/2000 [00:08<00:12, 91.99it/s, test=0.5%, test_loss=67.718, train=0.7%, train_loss=60.053]

outcome_architecture/outcome:  43%|████▎     | 869/2000 [00:09<00:11, 95.12it/s, test=0.5%, test_loss=67.718, train=0.7%, train_loss=60.053]

outcome_architecture/outcome:  44%|████▍     | 880/2000 [00:09<00:11, 96.89it/s, test=0.5%, test_loss=67.718, train=0.7%, train_loss=60.053]

outcome_architecture/outcome:  45%|████▍     | 891/2000 [00:09<00:11, 98.52it/s, test=0.5%, test_loss=67.718, train=0.7%, train_loss=60.053]

outcome_architecture/outcome:  45%|████▍     | 891/2000 [00:09<00:11, 98.52it/s, test=2.4%, test_loss=57.028, train=1.3%, train_loss=50.229]

outcome_architecture/outcome:  45%|████▌     | 901/2000 [00:09<00:12, 90.84it/s, test=2.4%, test_loss=57.028, train=1.3%, train_loss=50.229]

outcome_architecture/outcome:  46%|████▌     | 912/2000 [00:09<00:11, 94.30it/s, test=2.4%, test_loss=57.028, train=1.3%, train_loss=50.229]

outcome_architecture/outcome:  46%|████▌     | 923/2000 [00:09<00:11, 96.89it/s, test=2.4%, test_loss=57.028, train=1.3%, train_loss=50.229]

outcome_architecture/outcome:  47%|████▋     | 934/2000 [00:09<00:10, 98.63it/s, test=2.4%, test_loss=57.028, train=1.3%, train_loss=50.229]

outcome_architecture/outcome:  47%|████▋     | 945/2000 [00:09<00:10, 99.98it/s, test=2.4%, test_loss=57.028, train=1.3%, train_loss=50.229]

outcome_architecture/outcome:  47%|████▋     | 945/2000 [00:09<00:10, 99.98it/s, test=3.0%, test_loss=56.490, train=1.3%, train_loss=50.304]

outcome_architecture/outcome:  48%|████▊     | 956/2000 [00:09<00:11, 92.04it/s, test=3.0%, test_loss=56.490, train=1.3%, train_loss=50.304]

outcome_architecture/outcome:  48%|████▊     | 967/2000 [00:10<00:10, 95.06it/s, test=3.0%, test_loss=56.490, train=1.3%, train_loss=50.304]

outcome_architecture/outcome:  49%|████▉     | 978/2000 [00:10<00:10, 97.01it/s, test=3.0%, test_loss=56.490, train=1.3%, train_loss=50.304]

outcome_architecture/outcome:  49%|████▉     | 989/2000 [00:10<00:10, 98.65it/s, test=3.0%, test_loss=56.490, train=1.3%, train_loss=50.304]

outcome_architecture/outcome:  49%|████▉     | 989/2000 [00:10<00:10, 98.65it/s, test=2.3%, test_loss=36.774, train=1.7%, train_loss=32.298]

outcome_architecture/outcome:  50%|█████     | 1000/2000 [00:10<00:10, 91.27it/s, test=2.3%, test_loss=36.774, train=1.7%, train_loss=32.298]

outcome_architecture/outcome:  51%|█████     | 1011/2000 [00:10<00:10, 94.53it/s, test=2.3%, test_loss=36.774, train=1.7%, train_loss=32.298]

outcome_architecture/outcome:  51%|█████     | 1022/2000 [00:10<00:10, 96.92it/s, test=2.3%, test_loss=36.774, train=1.7%, train_loss=32.298]

outcome_architecture/outcome:  52%|█████▏    | 1033/2000 [00:10<00:09, 98.55it/s, test=2.3%, test_loss=36.774, train=1.7%, train_loss=32.298]

outcome_architecture/outcome:  52%|█████▏    | 1044/2000 [00:10<00:09, 99.88it/s, test=2.3%, test_loss=36.774, train=1.7%, train_loss=32.298]

outcome_architecture/outcome:  52%|█████▏    | 1044/2000 [00:10<00:09, 99.88it/s, test=0.0%, test_loss=30.083, train=0.0%, train_loss=25.450]

outcome_architecture/outcome:  53%|█████▎    | 1055/2000 [00:10<00:10, 91.88it/s, test=0.0%, test_loss=30.083, train=0.0%, train_loss=25.450]

outcome_architecture/outcome:  53%|█████▎    | 1066/2000 [00:11<00:09, 94.90it/s, test=0.0%, test_loss=30.083, train=0.0%, train_loss=25.450]

outcome_architecture/outcome:  54%|█████▍    | 1077/2000 [00:11<00:09, 96.56it/s, test=0.0%, test_loss=30.083, train=0.0%, train_loss=25.450]

outcome_architecture/outcome:  54%|█████▍    | 1088/2000 [00:11<00:09, 98.41it/s, test=0.0%, test_loss=30.083, train=0.0%, train_loss=25.450]

outcome_architecture/outcome:  55%|█████▍    | 1099/2000 [00:11<00:09, 99.59it/s, test=0.0%, test_loss=30.083, train=0.0%, train_loss=25.450]

outcome_architecture/outcome:  55%|█████▍    | 1099/2000 [00:11<00:09, 99.59it/s, test=2.7%, test_loss=75.453, train=0.3%, train_loss=81.766]

outcome_architecture/outcome:  56%|█████▌    | 1110/2000 [00:11<00:09, 91.81it/s, test=2.7%, test_loss=75.453, train=0.3%, train_loss=81.766]

outcome_architecture/outcome:  56%|█████▌    | 1121/2000 [00:11<00:09, 94.80it/s, test=2.7%, test_loss=75.453, train=0.3%, train_loss=81.766]

outcome_architecture/outcome:  57%|█████▋    | 1132/2000 [00:11<00:08, 97.03it/s, test=2.7%, test_loss=75.453, train=0.3%, train_loss=81.766]

outcome_architecture/outcome:  57%|█████▋    | 1143/2000 [00:11<00:08, 98.69it/s, test=2.7%, test_loss=75.453, train=0.3%, train_loss=81.766]

outcome_architecture/outcome:  57%|█████▋    | 1143/2000 [00:11<00:08, 98.69it/s, test=3.9%, test_loss=20.122, train=6.0%, train_loss=18.943]

outcome_architecture/outcome:  58%|█████▊    | 1153/2000 [00:12<00:09, 90.93it/s, test=3.9%, test_loss=20.122, train=6.0%, train_loss=18.943]

outcome_architecture/outcome:  58%|█████▊    | 1164/2000 [00:12<00:08, 94.03it/s, test=3.9%, test_loss=20.122, train=6.0%, train_loss=18.943]

outcome_architecture/outcome:  59%|█████▉    | 1175/2000 [00:12<00:08, 96.52it/s, test=3.9%, test_loss=20.122, train=6.0%, train_loss=18.943]

outcome_architecture/outcome:  59%|█████▉    | 1186/2000 [00:12<00:08, 98.37it/s, test=3.9%, test_loss=20.122, train=6.0%, train_loss=18.943]

outcome_architecture/outcome:  60%|█████▉    | 1197/2000 [00:12<00:08, 99.70it/s, test=3.9%, test_loss=20.122, train=6.0%, train_loss=18.943]

outcome_architecture/outcome:  60%|█████▉    | 1197/2000 [00:12<00:08, 99.70it/s, test=1.0%, test_loss=17.429, train=0.7%, train_loss=16.539]

outcome_architecture/outcome:  60%|██████    | 1208/2000 [00:12<00:08, 91.69it/s, test=1.0%, test_loss=17.429, train=0.7%, train_loss=16.539]

outcome_architecture/outcome:  61%|██████    | 1219/2000 [00:12<00:08, 94.69it/s, test=1.0%, test_loss=17.429, train=0.7%, train_loss=16.539]

outcome_architecture/outcome:  62%|██████▏   | 1230/2000 [00:12<00:07, 96.91it/s, test=1.0%, test_loss=17.429, train=0.7%, train_loss=16.539]

outcome_architecture/outcome:  62%|██████▏   | 1241/2000 [00:12<00:07, 98.45it/s, test=1.0%, test_loss=17.429, train=0.7%, train_loss=16.539]

outcome_architecture/outcome:  62%|██████▏   | 1241/2000 [00:13<00:07, 98.45it/s, test=2.1%, test_loss=58.125, train=2.7%, train_loss=57.385]

outcome_architecture/outcome:  63%|██████▎   | 1251/2000 [00:13<00:08, 90.71it/s, test=2.1%, test_loss=58.125, train=2.7%, train_loss=57.385]

outcome_architecture/outcome:  63%|██████▎   | 1262/2000 [00:13<00:07, 93.88it/s, test=2.1%, test_loss=58.125, train=2.7%, train_loss=57.385]

outcome_architecture/outcome:  64%|██████▎   | 1273/2000 [00:13<00:07, 97.38it/s, test=2.1%, test_loss=58.125, train=2.7%, train_loss=57.385]

outcome_architecture/outcome:  64%|██████▍   | 1284/2000 [00:13<00:07, 100.15it/s, test=2.1%, test_loss=58.125, train=2.7%, train_loss=57.385]

outcome_architecture/outcome:  65%|██████▍   | 1295/2000 [00:13<00:06, 100.86it/s, test=2.1%, test_loss=58.125, train=2.7%, train_loss=57.385]

outcome_architecture/outcome:  65%|██████▍   | 1295/2000 [00:13<00:06, 100.86it/s, test=4.7%, test_loss=20.217, train=4.0%, train_loss=17.454]

outcome_architecture/outcome:  65%|██████▌   | 1306/2000 [00:13<00:07, 92.30it/s, test=4.7%, test_loss=20.217, train=4.0%, train_loss=17.454]

outcome_architecture/outcome:  66%|██████▌   | 1317/2000 [00:13<00:07, 95.26it/s, test=4.7%, test_loss=20.217, train=4.0%, train_loss=17.454]

outcome_architecture/outcome:  66%|██████▋   | 1328/2000 [00:13<00:06, 97.43it/s, test=4.7%, test_loss=20.217, train=4.0%, train_loss=17.454]

outcome_architecture/outcome:  67%|██████▋   | 1339/2000 [00:13<00:06, 99.00it/s, test=4.7%, test_loss=20.217, train=4.0%, train_loss=17.454]

outcome_architecture/outcome:  67%|██████▋   | 1339/2000 [00:14<00:06, 99.00it/s, test=3.6%, test_loss=15.441, train=4.3%, train_loss=13.548]

outcome_architecture/outcome:  68%|██████▊   | 1350/2000 [00:14<00:07, 91.40it/s, test=3.6%, test_loss=15.441, train=4.3%, train_loss=13.548]

outcome_architecture/outcome:  68%|██████▊   | 1361/2000 [00:14<00:06, 94.09it/s, test=3.6%, test_loss=15.441, train=4.3%, train_loss=13.548]

outcome_architecture/outcome:  69%|██████▊   | 1372/2000 [00:14<00:06, 96.51it/s, test=3.6%, test_loss=15.441, train=4.3%, train_loss=13.548]

outcome_architecture/outcome:  69%|██████▉   | 1383/2000 [00:14<00:06, 98.35it/s, test=3.6%, test_loss=15.441, train=4.3%, train_loss=13.548]

outcome_architecture/outcome:  70%|██████▉   | 1394/2000 [00:14<00:06, 99.58it/s, test=3.6%, test_loss=15.441, train=4.3%, train_loss=13.548]

outcome_architecture/outcome:  70%|██████▉   | 1394/2000 [00:14<00:06, 99.58it/s, test=4.1%, test_loss=16.146, train=2.7%, train_loss=15.013]

outcome_architecture/outcome:  70%|███████   | 1405/2000 [00:14<00:06, 91.74it/s, test=4.1%, test_loss=16.146, train=2.7%, train_loss=15.013]

outcome_architecture/outcome:  71%|███████   | 1416/2000 [00:14<00:06, 94.76it/s, test=4.1%, test_loss=16.146, train=2.7%, train_loss=15.013]

outcome_architecture/outcome:  71%|███████▏  | 1427/2000 [00:14<00:05, 96.96it/s, test=4.1%, test_loss=16.146, train=2.7%, train_loss=15.013]

outcome_architecture/outcome:  72%|███████▏  | 1438/2000 [00:14<00:05, 98.65it/s, test=4.1%, test_loss=16.146, train=2.7%, train_loss=15.013]

outcome_architecture/outcome:  72%|███████▏  | 1449/2000 [00:15<00:05, 99.84it/s, test=4.1%, test_loss=16.146, train=2.7%, train_loss=15.013]

outcome_architecture/outcome:  72%|███████▏  | 1449/2000 [00:15<00:05, 99.84it/s, test=4.9%, test_loss=9.757, train=3.3%, train_loss=9.877]

outcome_architecture/outcome:  73%|███████▎  | 1460/2000 [00:15<00:05, 91.51it/s, test=4.9%, test_loss=9.757, train=3.3%, train_loss=9.877]

outcome_architecture/outcome:  74%|███████▎  | 1471/2000 [00:15<00:05, 94.50it/s, test=4.9%, test_loss=9.757, train=3.3%, train_loss=9.877]

outcome_architecture/outcome:  74%|███████▍  | 1482/2000 [00:15<00:05, 96.71it/s, test=4.9%, test_loss=9.757, train=3.3%, train_loss=9.877]

outcome_architecture/outcome:  75%|███████▍  | 1493/2000 [00:15<00:05, 98.42it/s, test=4.9%, test_loss=9.757, train=3.3%, train_loss=9.877]

outcome_architecture/outcome:  75%|███████▍  | 1493/2000 [00:15<00:05, 98.42it/s, test=5.2%, test_loss=11.484, train=4.3%, train_loss=10.963]

outcome_architecture/outcome:  75%|███████▌  | 1503/2000 [00:15<00:05, 90.63it/s, test=5.2%, test_loss=11.484, train=4.3%, train_loss=10.963]

outcome_architecture/outcome:  76%|███████▌  | 1514/2000 [00:15<00:05, 93.77it/s, test=5.2%, test_loss=11.484, train=4.3%, train_loss=10.963]

outcome_architecture/outcome:  76%|███████▋  | 1525/2000 [00:15<00:04, 96.14it/s, test=5.2%, test_loss=11.484, train=4.3%, train_loss=10.963]

outcome_architecture/outcome:  77%|███████▋  | 1536/2000 [00:15<00:04, 97.82it/s, test=5.2%, test_loss=11.484, train=4.3%, train_loss=10.963]

outcome_architecture/outcome:  77%|███████▋  | 1547/2000 [00:16<00:04, 99.09it/s, test=5.2%, test_loss=11.484, train=4.3%, train_loss=10.963]

outcome_architecture/outcome:  77%|███████▋  | 1547/2000 [00:16<00:04, 99.09it/s, test=4.9%, test_loss=10.372, train=6.0%, train_loss=10.392]

outcome_architecture/outcome:  78%|███████▊  | 1557/2000 [00:16<00:04, 90.70it/s, test=4.9%, test_loss=10.372, train=6.0%, train_loss=10.392]

outcome_architecture/outcome:  78%|███████▊  | 1568/2000 [00:16<00:04, 93.88it/s, test=4.9%, test_loss=10.372, train=6.0%, train_loss=10.392]

outcome_architecture/outcome:  79%|███████▉  | 1579/2000 [00:16<00:04, 96.19it/s, test=4.9%, test_loss=10.372, train=6.0%, train_loss=10.392]

outcome_architecture/outcome:  80%|███████▉  | 1590/2000 [00:16<00:04, 98.00it/s, test=4.9%, test_loss=10.372, train=6.0%, train_loss=10.392]

outcome_architecture/outcome:  80%|███████▉  | 1590/2000 [00:16<00:04, 98.00it/s, test=3.9%, test_loss=9.660, train=4.3%, train_loss=8.337]

outcome_architecture/outcome:  80%|████████  | 1600/2000 [00:16<00:04, 90.27it/s, test=3.9%, test_loss=9.660, train=4.3%, train_loss=8.337]

outcome_architecture/outcome:  81%|████████  | 1611/2000 [00:16<00:04, 93.52it/s, test=3.9%, test_loss=9.660, train=4.3%, train_loss=8.337]

outcome_architecture/outcome:  81%|████████  | 1622/2000 [00:16<00:03, 96.09it/s, test=3.9%, test_loss=9.660, train=4.3%, train_loss=8.337]

outcome_architecture/outcome:  82%|████████▏ | 1633/2000 [00:17<00:03, 97.90it/s, test=3.9%, test_loss=9.660, train=4.3%, train_loss=8.337]

outcome_architecture/outcome:  82%|████████▏ | 1644/2000 [00:17<00:03, 99.33it/s, test=3.9%, test_loss=9.660, train=4.3%, train_loss=8.337]

outcome_architecture/outcome:  82%|████████▏ | 1644/2000 [00:17<00:03, 99.33it/s, test=3.5%, test_loss=7.267, train=6.0%, train_loss=6.615]

outcome_architecture/outcome:  83%|████████▎ | 1654/2000 [00:17<00:03, 90.93it/s, test=3.5%, test_loss=7.267, train=6.0%, train_loss=6.615]

outcome_architecture/outcome:  83%|████████▎ | 1665/2000 [00:17<00:03, 94.16it/s, test=3.5%, test_loss=7.267, train=6.0%, train_loss=6.615]

outcome_architecture/outcome:  84%|████████▍ | 1676/2000 [00:17<00:03, 96.45it/s, test=3.5%, test_loss=7.267, train=6.0%, train_loss=6.615]

outcome_architecture/outcome:  84%|████████▍ | 1687/2000 [00:17<00:03, 98.15it/s, test=3.5%, test_loss=7.267, train=6.0%, train_loss=6.615]

outcome_architecture/outcome:  85%|████████▍ | 1698/2000 [00:17<00:03, 99.39it/s, test=3.5%, test_loss=7.267, train=6.0%, train_loss=6.615]

outcome_architecture/outcome:  85%|████████▍ | 1698/2000 [00:17<00:03, 99.39it/s, test=6.3%, test_loss=6.418, train=2.3%, train_loss=7.001]

outcome_architecture/outcome:  85%|████████▌ | 1708/2000 [00:17<00:03, 90.97it/s, test=6.3%, test_loss=6.418, train=2.3%, train_loss=7.001]

outcome_architecture/outcome:  86%|████████▌ | 1719/2000 [00:17<00:02, 95.11it/s, test=6.3%, test_loss=6.418, train=2.3%, train_loss=7.001]

outcome_architecture/outcome:  86%|████████▋ | 1730/2000 [00:18<00:02, 98.05it/s, test=6.3%, test_loss=6.418, train=2.3%, train_loss=7.001]

outcome_architecture/outcome:  87%|████████▋ | 1740/2000 [00:18<00:02, 97.59it/s, test=6.3%, test_loss=6.418, train=2.3%, train_loss=7.001]

outcome_architecture/outcome:  87%|████████▋ | 1740/2000 [00:18<00:02, 97.59it/s, test=5.2%, test_loss=5.780, train=5.3%, train_loss=6.006]

outcome_architecture/outcome:  88%|████████▊ | 1750/2000 [00:18<00:02, 90.68it/s, test=5.2%, test_loss=5.780, train=5.3%, train_loss=6.006]

outcome_architecture/outcome:  88%|████████▊ | 1761/2000 [00:18<00:02, 95.01it/s, test=5.2%, test_loss=5.780, train=5.3%, train_loss=6.006]

outcome_architecture/outcome:  89%|████████▊ | 1771/2000 [00:18<00:02, 95.68it/s, test=5.2%, test_loss=5.780, train=5.3%, train_loss=6.006]

outcome_architecture/outcome:  89%|████████▉ | 1782/2000 [00:18<00:02, 98.64it/s, test=5.2%, test_loss=5.780, train=5.3%, train_loss=6.006]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:18<00:02, 100.75it/s, test=5.2%, test_loss=5.780, train=5.3%, train_loss=6.006]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:18<00:02, 100.75it/s, test=5.9%, test_loss=5.974, train=4.7%, train_loss=5.671]

outcome_architecture/outcome:  90%|█████████ | 1804/2000 [00:18<00:02, 90.97it/s, test=5.9%, test_loss=5.974, train=4.7%, train_loss=5.671]

outcome_architecture/outcome:  91%|█████████ | 1815/2000 [00:18<00:01, 95.05it/s, test=5.9%, test_loss=5.974, train=4.7%, train_loss=5.671]

outcome_architecture/outcome:  91%|█████████▏| 1826/2000 [00:19<00:01, 96.88it/s, test=5.9%, test_loss=5.974, train=4.7%, train_loss=5.671]

outcome_architecture/outcome:  92%|█████████▏| 1837/2000 [00:19<00:01, 98.31it/s, test=5.9%, test_loss=5.974, train=4.7%, train_loss=5.671]

outcome_architecture/outcome:  92%|█████████▏| 1848/2000 [00:19<00:01, 100.38it/s, test=5.9%, test_loss=5.974, train=4.7%, train_loss=5.671]

outcome_architecture/outcome:  92%|█████████▏| 1848/2000 [00:19<00:01, 100.38it/s, test=6.0%, test_loss=3.971, train=6.0%, train_loss=3.912]

outcome_architecture/outcome:  93%|█████████▎| 1859/2000 [00:19<00:01, 91.19it/s, test=6.0%, test_loss=3.971, train=6.0%, train_loss=3.912]

outcome_architecture/outcome:  94%|█████████▎| 1870/2000 [00:19<00:01, 94.96it/s, test=6.0%, test_loss=3.971, train=6.0%, train_loss=3.912]

outcome_architecture/outcome:  94%|█████████▍| 1881/2000 [00:19<00:01, 98.02it/s, test=6.0%, test_loss=3.971, train=6.0%, train_loss=3.912]

outcome_architecture/outcome:  95%|█████████▍| 1891/2000 [00:19<00:01, 97.84it/s, test=6.0%, test_loss=3.971, train=6.0%, train_loss=3.912]

outcome_architecture/outcome:  95%|█████████▍| 1891/2000 [00:19<00:01, 97.84it/s, test=6.0%, test_loss=6.223, train=6.3%, train_loss=5.436]

outcome_architecture/outcome:  95%|█████████▌| 1901/2000 [00:19<00:01, 90.87it/s, test=6.0%, test_loss=6.223, train=6.3%, train_loss=5.436]

outcome_architecture/outcome:  96%|█████████▌| 1912/2000 [00:19<00:00, 95.16it/s, test=6.0%, test_loss=6.223, train=6.3%, train_loss=5.436]

outcome_architecture/outcome:  96%|█████████▌| 1922/2000 [00:20<00:00, 95.98it/s, test=6.0%, test_loss=6.223, train=6.3%, train_loss=5.436]

outcome_architecture/outcome:  97%|█████████▋| 1933/2000 [00:20<00:00, 98.91it/s, test=6.0%, test_loss=6.223, train=6.3%, train_loss=5.436]

outcome_architecture/outcome:  97%|█████████▋| 1944/2000 [00:20<00:00, 100.85it/s, test=6.0%, test_loss=6.223, train=6.3%, train_loss=5.436]

outcome_architecture/outcome:  97%|█████████▋| 1944/2000 [00:20<00:00, 100.85it/s, test=4.7%, test_loss=5.725, train=5.0%, train_loss=5.987]

outcome_architecture/outcome:  98%|█████████▊| 1955/2000 [00:20<00:00, 91.54it/s, test=4.7%, test_loss=5.725, train=5.0%, train_loss=5.987]

outcome_architecture/outcome:  98%|█████████▊| 1966/2000 [00:20<00:00, 95.43it/s, test=4.7%, test_loss=5.725, train=5.0%, train_loss=5.987]

outcome_architecture/outcome:  99%|█████████▉| 1977/2000 [00:20<00:00, 98.31it/s, test=4.7%, test_loss=5.725, train=5.0%, train_loss=5.987]

outcome_architecture/outcome:  99%|█████████▉| 1987/2000 [00:20<00:00, 97.82it/s, test=4.7%, test_loss=5.725, train=5.0%, train_loss=5.987]

outcome_architecture/outcome: 100%|█████████▉| 1998/2000 [00:20<00:00, 100.13it/s, test=4.7%, test_loss=5.725, train=5.0%, train_loss=5.987]

outcome_architecture/outcome: 100%|█████████▉| 1998/2000 [00:20<00:00, 100.13it/s, test=6.9%, test_loss=7.101, train=5.7%, train_loss=7.634]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:20<00:00, 95.85it/s, test=6.9%, test_loss=7.101, train=5.7%, train_loss=7.634]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,process,4.277299,0.000000,0.000,0.000,4.277391
1,1,process_architecture,process,4.262680,0.000000,0.000,0.000,4.262407
2,2,process_architecture,process,4.240857,0.000000,0.000,0.000,4.240028
3,5,process_architecture,process,3.956355,0.000000,0.000,0.000,3.942208
4,10,process_architecture,process,3.676264,0.000000,0.000,0.000,3.662949
...,...,...,...,...,...,...,...,...
91,1800,outcome_architecture,outcome,5.670868,0.046667,0.059,0.050,5.974432
92,1850,outcome_architecture,outcome,3.911817,0.060000,0.060,0.049,3.970916
93,1900,outcome_architecture,outcome,5.435932,0.063333,0.060,0.050,6.223381
94,1950,outcome_architecture,outcome,5.986771,0.050000,0.047,0.033,5.724681
95,2000,outcome_architecture,outcome,7.634152,0.056667,0.069,0.028,7.100903


## 7. Final behavioral comparison

The four displayed rows are:

- two fixed references,
- two trained models.

But only the latter two were optimized.

In [8]:

rows = []

for name, model, mode, trained in [
    ("Fixed PROCESS reference", process_reference, "process", False),
    ("Trained PROCESS architecture", trained_process, "process", True),
    ("Fixed OUTCOME reference", outcome_reference, "outcome", False),
    ("Trained OUTCOME architecture", trained_outcome, "outcome", True),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    rows.append({
        "model": name,
        "optimized": trained,
        "mode": mode,
        "test_answer_accuracy": metrics["final_answer"],
        "test_exact_continuation": metrics["exact_continuation"],
    })

final_results = pd.DataFrame(rows)
final_results

,model,optimized,mode,test_answer_accuracy,test_exact_continuation
0,Fixed PROCESS reference,False,process,1.000,1.000
1,Trained PROCESS architecture,True,process,1.000,1.000
2,Fixed OUTCOME reference,False,outcome,1.000,1.000
3,Trained OUTCOME architecture,True,outcome,0.069,0.028

## 8. Learning curves

The first plot tracks free-running answer accuracy. The second plot tracks teacher-forced training and held-out test loss at the same checkpoints.

In [9]:

fig, ax = plt.subplots(figsize=(8, 4.5))

for (architecture, mode), frame in history.groupby(["architecture", "mode"]):
    ax.plot(
        frame["step"],
        frame["test_answer_accuracy"],
        marker="o",
        label=f"{architecture} / {mode}",
    )

ax.axhline(1.0, linestyle="--", label="constructive solution = 100%")
ax.axhline(1 / tokenizer.n_states, linestyle=":", label="chance")
ax.set_xlabel("optimization step")
ax.set_ylabel("free-running test answer accuracy")
ax.set_ylim(-0.02, 1.03)
ax.legend()
plt.show()

In [10]:
def plot_train_test_loss(history, *, steps=STEPS):
    required = {"architecture", "mode", "step", "train_loss", "test_loss"}
    missing = required.difference(history.columns)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"history is missing required columns: {missing_text}")

    fig, ax = plt.subplots(figsize=(9, 5))
    styles = {
        ("process_architecture", "process"): {
            "color": "#2ca02c",
            "label": "PROCESS architecture / process",
        },
        ("outcome_architecture", "outcome"): {
            "color": "#d62728",
            "label": "OUTCOME architecture / outcome",
        },
    }

    for key, frame in history.sort_values("step").groupby(["architecture", "mode"]):
        style = styles.get(key, {"color": None, "label": " / ".join(map(str, key))})
        ax.plot(
            frame["step"],
            frame["train_loss"],
            color=style["color"],
            linewidth=2.2,
            label=f"{style['label']} train",
        )
        ax.plot(
            frame["step"],
            frame["test_loss"],
            color=style["color"],
            linestyle="--",
            linewidth=2.2,
            label=f"{style['label']} test",
        )

    ax.set_xlabel("Iteration", fontsize=13)
    ax.set_ylabel("Teacher-forced loss", fontsize=13)
    ax.set_xlim(0, steps)
    ax.grid(True, alpha=0.35)
    ax.legend(frameon=True, fontsize=10)
    fig.tight_layout()
    return fig, ax

plot_train_test_loss(history)
plt.show()


## 9. Inspect one free-running example

No gold continuation is fed to the model during this evaluation.

In [11]:

example_prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Trained PROCESS", trained_process, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
    ("Trained OUTCOME", trained_outcome, "outcome"),
]:
    budget = 3 if mode == "outcome" else 2 * DEPTH + 3
    generated = generate(
        model,
        example_prompt,
        budget,
        tokenizer.eos,
    )
    continuation = generated[0, example_prompt.shape[1]:]
    print(f"\n{name}")
    print(tokenizer.decode(continuation))

Fixed PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Trained PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Fixed OUTCOME
<COLON> S1001 <EOS>

Trained OUTCOME
<COLON> S0011 <EOS>


## 10. How to interpret the result

There are four broad possibilities.

### Both trained models reach 100%

The two constructive solution classes are readily reachable from this initialization and optimizer.

### PROCESS reaches 100%, OUTCOME does not

Then

\[
\exists\theta^\star_{\rm O}:\operatorname{Err}(\theta^\star_{\rm O})=0
\]

but the tested terminal-supervision optimization trajectory does not discover it.

That is evidence for a **trainability / accessibility gap**, not an expressivity gap.

### OUTCOME reaches 100%, PROCESS does not

Then the existence of an explicit local process circuit does not by itself guarantee that ordinary trace training discovers it.

### Neither reaches 100%

Then constructive realizability and optimization reachability are substantially different for both architectures.

---

Do not infer an impossibility theorem from a failed run. Multiple seeds, learning-rate controls, and optimizer-stability diagnostics are needed before making a strong optimization claim.


# Optional appendix: full $2\times2$ architecture × supervision experiment

The primary notebook above trains exactly **two** models.

A separate, stronger control can cross:

\[
\{\text{PROCESS architecture},\text{OUTCOME architecture}\}
\times
\{\text{PROCESS supervision},\text{OUTCOME supervision}\}.
\]

That experiment trains **four** models and should be reported separately.

It requires the OUTCOME architecture to use the longer PROCESS position budget, so it is intentionally not the exact diagonal reachability experiment above.

In [12]:
RUN_OPTIONAL_2X2 = True

if RUN_OPTIONAL_2X2:
    from handcoded_utils import (
        build_random_trainable_outcome_architecture,
        build_random_trainable_process_architecture,
        run_architecture_experiment,
    )

    bases = {
        "process_architecture": build_random_trainable_process_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
        "outcome_architecture": build_random_trainable_outcome_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
    }

    models_2x2, history_2x2 = run_architecture_experiment(
        bases,
        training_data,
        batch_schedule,
        LR,
        CHECKPOINTS,
        train_eval,
        test_eval,
        tokenizer,
        circuit_prompts,
        test_loss_data=test_loss_data,
        loss_eval_size=LOSS_EVAL_SIZE,
    )

    display(history_2x2.drop(columns=["circuit_matrix"], errors="ignore"))
else:
    print("Skipping optional 2x2 experiment. Set RUN_OPTIONAL_2X2 = True to run it.")

architecture/mode:   0%|          | 0/4 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.217, train=0.0%, train_loss=4.217]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.135, train=0.0%, train_loss=4.135]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.075, train=0.0%, train_loss=3.077]

process_architecture/outcome:   0%|          | 5/2000 [00:00<01:26, 23.06it/s, test=0.0%, test_loss=3.075, train=0.0%, train_loss=3.077]

process_architecture/outcome:   0%|          | 5/2000 [00:00<01:26, 23.06it/s, test=0.0%, test_loss=1.779, train=0.0%, train_loss=1.804]

process_architecture/outcome:   1%|          | 19/2000 [00:00<00:28, 68.67it/s, test=0.0%, test_loss=1.779, train=0.0%, train_loss=1.804]

process_architecture/outcome:   1%|          | 19/2000 [00:00<00:28, 68.67it/s, test=0.0%, test_loss=1.159, train=0.0%, train_loss=1.154]

process_architecture/outcome:   1%|          | 19/2000 [00:00<00:28, 68.67it/s, test=0.0%, test_loss=1.110, train=0.0%, train_loss=1.105]

process_architecture/outcome:   2%|▏         | 32/2000 [00:00<00:21, 90.49it/s, test=0.0%, test_loss=1.110, train=0.0%, train_loss=1.105]

process_architecture/outcome:   2%|▏         | 32/2000 [00:00<00:21, 90.49it/s, test=6.8%, test_loss=0.919, train=5.7%, train_loss=0.935]

process_architecture/outcome:   2%|▎         | 50/2000 [00:00<00:16, 115.58it/s, test=6.8%, test_loss=0.919, train=5.7%, train_loss=0.935]

process_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:14, 137.74it/s, test=6.8%, test_loss=0.919, train=5.7%, train_loss=0.935]

process_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:14, 137.74it/s, test=7.5%, test_loss=0.935, train=7.0%, train_loss=0.943]

process_architecture/outcome:   4%|▍         | 85/2000 [00:00<00:13, 143.22it/s, test=7.5%, test_loss=0.935, train=7.0%, train_loss=0.943]

process_architecture/outcome:   4%|▍         | 85/2000 [00:00<00:13, 143.22it/s, test=9.1%, test_loss=0.928, train=9.3%, train_loss=0.944]

process_architecture/outcome:   5%|▌         | 101/2000 [00:00<00:12, 146.61it/s, test=9.1%, test_loss=0.928, train=9.3%, train_loss=0.944]

process_architecture/outcome:   6%|▌         | 121/2000 [00:00<00:11, 161.64it/s, test=9.1%, test_loss=0.928, train=9.3%, train_loss=0.944]

process_architecture/outcome:   7%|▋         | 142/2000 [00:01<00:10, 174.20it/s, test=9.1%, test_loss=0.928, train=9.3%, train_loss=0.944]

process_architecture/outcome:   7%|▋         | 142/2000 [00:01<00:10, 174.20it/s, test=11.5%, test_loss=0.898, train=8.3%, train_loss=0.902]

process_architecture/outcome:   8%|▊         | 160/2000 [00:01<00:10, 171.77it/s, test=11.5%, test_loss=0.898, train=8.3%, train_loss=0.902]

process_architecture/outcome:   9%|▉         | 180/2000 [00:01<00:10, 178.89it/s, test=11.5%, test_loss=0.898, train=8.3%, train_loss=0.902]

process_architecture/outcome:   9%|▉         | 180/2000 [00:01<00:10, 178.89it/s, test=10.7%, test_loss=0.900, train=11.7%, train_loss=0.899]

process_architecture/outcome:  10%|█         | 200/2000 [00:01<00:10, 175.70it/s, test=10.7%, test_loss=0.900, train=11.7%, train_loss=0.899]

process_architecture/outcome:  11%|█         | 220/2000 [00:01<00:09, 181.67it/s, test=10.7%, test_loss=0.900, train=11.7%, train_loss=0.899]

process_architecture/outcome:  12%|█▏        | 241/2000 [00:01<00:09, 187.28it/s, test=10.7%, test_loss=0.900, train=11.7%, train_loss=0.899]

process_architecture/outcome:  12%|█▏        | 241/2000 [00:01<00:09, 187.28it/s, test=12.4%, test_loss=0.887, train=8.0%, train_loss=0.882]

process_architecture/outcome:  13%|█▎        | 260/2000 [00:01<00:09, 181.21it/s, test=12.4%, test_loss=0.887, train=8.0%, train_loss=0.882]

process_architecture/outcome:  14%|█▍        | 280/2000 [00:01<00:09, 186.54it/s, test=12.4%, test_loss=0.887, train=8.0%, train_loss=0.882]

process_architecture/outcome:  14%|█▍        | 280/2000 [00:01<00:09, 186.54it/s, test=8.8%, test_loss=0.886, train=9.7%, train_loss=0.883]

process_architecture/outcome:  15%|█▌        | 300/2000 [00:01<00:09, 181.52it/s, test=8.8%, test_loss=0.886, train=9.7%, train_loss=0.883]

process_architecture/outcome:  16%|█▌        | 321/2000 [00:02<00:08, 187.18it/s, test=8.8%, test_loss=0.886, train=9.7%, train_loss=0.883]

process_architecture/outcome:  17%|█▋        | 342/2000 [00:02<00:08, 191.58it/s, test=8.8%, test_loss=0.886, train=9.7%, train_loss=0.883]

process_architecture/outcome:  17%|█▋        | 342/2000 [00:02<00:08, 191.58it/s, test=12.5%, test_loss=0.875, train=11.3%, train_loss=0.887]

process_architecture/outcome:  18%|█▊        | 362/2000 [00:02<00:08, 184.15it/s, test=12.5%, test_loss=0.875, train=11.3%, train_loss=0.887]

process_architecture/outcome:  19%|█▉        | 382/2000 [00:02<00:08, 188.27it/s, test=12.5%, test_loss=0.875, train=11.3%, train_loss=0.887]

process_architecture/outcome:  19%|█▉        | 382/2000 [00:02<00:08, 188.27it/s, test=12.5%, test_loss=0.868, train=12.7%, train_loss=0.885]

process_architecture/outcome:  20%|██        | 401/2000 [00:02<00:08, 182.35it/s, test=12.5%, test_loss=0.868, train=12.7%, train_loss=0.885]

process_architecture/outcome:  21%|██        | 421/2000 [00:02<00:08, 187.32it/s, test=12.5%, test_loss=0.868, train=12.7%, train_loss=0.885]

process_architecture/outcome:  22%|██▏       | 442/2000 [00:02<00:08, 191.27it/s, test=12.5%, test_loss=0.868, train=12.7%, train_loss=0.885]

process_architecture/outcome:  22%|██▏       | 442/2000 [00:02<00:08, 191.27it/s, test=11.8%, test_loss=0.876, train=11.7%, train_loss=0.849]

process_architecture/outcome:  23%|██▎       | 462/2000 [00:02<00:08, 184.57it/s, test=11.8%, test_loss=0.876, train=11.7%, train_loss=0.849]

process_architecture/outcome:  24%|██▍       | 483/2000 [00:02<00:08, 189.20it/s, test=11.8%, test_loss=0.876, train=11.7%, train_loss=0.849]

process_architecture/outcome:  24%|██▍       | 483/2000 [00:02<00:08, 189.20it/s, test=12.9%, test_loss=0.868, train=11.7%, train_loss=0.857]

process_architecture/outcome:  25%|██▌       | 503/2000 [00:02<00:08, 183.95it/s, test=12.9%, test_loss=0.868, train=11.7%, train_loss=0.857]

process_architecture/outcome:  26%|██▌       | 524/2000 [00:03<00:07, 189.18it/s, test=12.9%, test_loss=0.868, train=11.7%, train_loss=0.857]

process_architecture/outcome:  27%|██▋       | 544/2000 [00:03<00:07, 192.12it/s, test=12.9%, test_loss=0.868, train=11.7%, train_loss=0.857]

process_architecture/outcome:  27%|██▋       | 544/2000 [00:03<00:07, 192.12it/s, test=14.1%, test_loss=0.866, train=13.0%, train_loss=0.836]

process_architecture/outcome:  28%|██▊       | 564/2000 [00:03<00:07, 184.70it/s, test=14.1%, test_loss=0.866, train=13.0%, train_loss=0.836]

process_architecture/outcome:  29%|██▉       | 585/2000 [00:03<00:07, 189.42it/s, test=14.1%, test_loss=0.866, train=13.0%, train_loss=0.836]

process_architecture/outcome:  29%|██▉       | 585/2000 [00:03<00:07, 189.42it/s, test=14.1%, test_loss=0.863, train=12.3%, train_loss=0.843]

process_architecture/outcome:  30%|███       | 605/2000 [00:03<00:07, 184.02it/s, test=14.1%, test_loss=0.863, train=12.3%, train_loss=0.843]

process_architecture/outcome:  31%|███▏      | 626/2000 [00:03<00:07, 190.07it/s, test=14.1%, test_loss=0.863, train=12.3%, train_loss=0.843]

process_architecture/outcome:  32%|███▏      | 646/2000 [00:03<00:07, 192.72it/s, test=14.1%, test_loss=0.863, train=12.3%, train_loss=0.843]

process_architecture/outcome:  32%|███▏      | 646/2000 [00:03<00:07, 192.72it/s, test=13.4%, test_loss=0.855, train=13.7%, train_loss=0.838]

process_architecture/outcome:  33%|███▎      | 666/2000 [00:03<00:07, 185.77it/s, test=13.4%, test_loss=0.855, train=13.7%, train_loss=0.838]

process_architecture/outcome:  34%|███▍      | 686/2000 [00:03<00:06, 189.64it/s, test=13.4%, test_loss=0.855, train=13.7%, train_loss=0.838]

process_architecture/outcome:  34%|███▍      | 686/2000 [00:04<00:06, 189.64it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.842]

process_architecture/outcome:  35%|███▌      | 706/2000 [00:04<00:07, 183.68it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.842]

process_architecture/outcome:  36%|███▋      | 727/2000 [00:04<00:06, 188.72it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.842]

process_architecture/outcome:  37%|███▋      | 747/2000 [00:04<00:06, 191.75it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.842]

process_architecture/outcome:  37%|███▋      | 747/2000 [00:04<00:06, 191.75it/s, test=16.1%, test_loss=0.853, train=16.3%, train_loss=0.831]

process_architecture/outcome:  38%|███▊      | 767/2000 [00:04<00:06, 185.41it/s, test=16.1%, test_loss=0.853, train=16.3%, train_loss=0.831]

process_architecture/outcome:  39%|███▉      | 788/2000 [00:04<00:06, 189.80it/s, test=16.1%, test_loss=0.853, train=16.3%, train_loss=0.831]

process_architecture/outcome:  39%|███▉      | 788/2000 [00:04<00:06, 189.80it/s, test=18.0%, test_loss=0.847, train=18.0%, train_loss=0.828]

process_architecture/outcome:  40%|████      | 808/2000 [00:04<00:06, 184.44it/s, test=18.0%, test_loss=0.847, train=18.0%, train_loss=0.828]

process_architecture/outcome:  41%|████▏     | 828/2000 [00:04<00:06, 188.50it/s, test=18.0%, test_loss=0.847, train=18.0%, train_loss=0.828]

process_architecture/outcome:  42%|████▏     | 849/2000 [00:04<00:05, 192.20it/s, test=18.0%, test_loss=0.847, train=18.0%, train_loss=0.828]

process_architecture/outcome:  42%|████▏     | 849/2000 [00:04<00:05, 192.20it/s, test=17.6%, test_loss=0.808, train=18.0%, train_loss=0.797]

process_architecture/outcome:  43%|████▎     | 869/2000 [00:04<00:06, 185.93it/s, test=17.6%, test_loss=0.808, train=18.0%, train_loss=0.797]

process_architecture/outcome:  44%|████▍     | 890/2000 [00:05<00:05, 190.81it/s, test=17.6%, test_loss=0.808, train=18.0%, train_loss=0.797]

process_architecture/outcome:  44%|████▍     | 890/2000 [00:05<00:05, 190.81it/s, test=18.5%, test_loss=0.813, train=17.3%, train_loss=0.770]

process_architecture/outcome:  46%|████▌     | 910/2000 [00:05<00:05, 185.62it/s, test=18.5%, test_loss=0.813, train=17.3%, train_loss=0.770]

process_architecture/outcome:  47%|████▋     | 931/2000 [00:05<00:05, 189.88it/s, test=18.5%, test_loss=0.813, train=17.3%, train_loss=0.770]

process_architecture/outcome:  47%|████▋     | 931/2000 [00:05<00:05, 189.88it/s, test=20.3%, test_loss=0.786, train=19.3%, train_loss=0.757]

process_architecture/outcome:  48%|████▊     | 951/2000 [00:05<00:05, 183.43it/s, test=20.3%, test_loss=0.786, train=19.3%, train_loss=0.757]

process_architecture/outcome:  49%|████▊     | 971/2000 [00:05<00:05, 187.88it/s, test=20.3%, test_loss=0.786, train=19.3%, train_loss=0.757]

process_architecture/outcome:  50%|████▉     | 992/2000 [00:05<00:05, 191.85it/s, test=20.3%, test_loss=0.786, train=19.3%, train_loss=0.757]

process_architecture/outcome:  50%|████▉     | 992/2000 [00:05<00:05, 191.85it/s, test=19.3%, test_loss=0.796, train=20.7%, train_loss=0.769]

process_architecture/outcome:  51%|█████     | 1012/2000 [00:05<00:05, 186.02it/s, test=19.3%, test_loss=0.796, train=20.7%, train_loss=0.769]

process_architecture/outcome:  52%|█████▏    | 1032/2000 [00:05<00:05, 189.87it/s, test=19.3%, test_loss=0.796, train=20.7%, train_loss=0.769]

process_architecture/outcome:  52%|█████▏    | 1032/2000 [00:05<00:05, 189.87it/s, test=19.0%, test_loss=0.792, train=19.7%, train_loss=0.757]

process_architecture/outcome:  53%|█████▎    | 1052/2000 [00:05<00:05, 184.25it/s, test=19.0%, test_loss=0.792, train=19.7%, train_loss=0.757]

process_architecture/outcome:  54%|█████▎    | 1072/2000 [00:06<00:04, 188.15it/s, test=19.0%, test_loss=0.792, train=19.7%, train_loss=0.757]

process_architecture/outcome:  55%|█████▍    | 1093/2000 [00:06<00:04, 191.68it/s, test=19.0%, test_loss=0.792, train=19.7%, train_loss=0.757]

process_architecture/outcome:  55%|█████▍    | 1093/2000 [00:06<00:04, 191.68it/s, test=20.3%, test_loss=0.809, train=24.0%, train_loss=0.745]

process_architecture/outcome:  56%|█████▌    | 1113/2000 [00:06<00:04, 186.13it/s, test=20.3%, test_loss=0.809, train=24.0%, train_loss=0.745]

process_architecture/outcome:  57%|█████▋    | 1133/2000 [00:06<00:04, 189.44it/s, test=20.3%, test_loss=0.809, train=24.0%, train_loss=0.745]

process_architecture/outcome:  57%|█████▋    | 1133/2000 [00:06<00:04, 189.44it/s, test=23.7%, test_loss=0.755, train=23.3%, train_loss=0.697]

process_architecture/outcome:  58%|█████▊    | 1153/2000 [00:06<00:04, 183.40it/s, test=23.7%, test_loss=0.755, train=23.3%, train_loss=0.697]

process_architecture/outcome:  59%|█████▊    | 1174/2000 [00:06<00:04, 188.21it/s, test=23.7%, test_loss=0.755, train=23.3%, train_loss=0.697]

process_architecture/outcome:  60%|█████▉    | 1195/2000 [00:06<00:04, 192.13it/s, test=23.7%, test_loss=0.755, train=23.3%, train_loss=0.697]

process_architecture/outcome:  60%|█████▉    | 1195/2000 [00:06<00:04, 192.13it/s, test=26.5%, test_loss=0.801, train=26.0%, train_loss=0.652]

process_architecture/outcome:  61%|██████    | 1215/2000 [00:06<00:04, 186.04it/s, test=26.5%, test_loss=0.801, train=26.0%, train_loss=0.652]

process_architecture/outcome:  62%|██████▏   | 1235/2000 [00:06<00:04, 189.72it/s, test=26.5%, test_loss=0.801, train=26.0%, train_loss=0.652]

process_architecture/outcome:  62%|██████▏   | 1235/2000 [00:06<00:04, 189.72it/s, test=24.2%, test_loss=0.733, train=20.3%, train_loss=0.728]

process_architecture/outcome:  63%|██████▎   | 1255/2000 [00:06<00:04, 184.01it/s, test=24.2%, test_loss=0.733, train=20.3%, train_loss=0.728]

process_architecture/outcome:  64%|██████▍   | 1276/2000 [00:07<00:03, 189.65it/s, test=24.2%, test_loss=0.733, train=20.3%, train_loss=0.728]

process_architecture/outcome:  65%|██████▍   | 1297/2000 [00:07<00:03, 194.20it/s, test=24.2%, test_loss=0.733, train=20.3%, train_loss=0.728]

process_architecture/outcome:  65%|██████▍   | 1297/2000 [00:07<00:03, 194.20it/s, test=27.4%, test_loss=0.704, train=28.7%, train_loss=0.631]

process_architecture/outcome:  66%|██████▌   | 1317/2000 [00:07<00:03, 187.15it/s, test=27.4%, test_loss=0.704, train=28.7%, train_loss=0.631]

process_architecture/outcome:  67%|██████▋   | 1337/2000 [00:07<00:03, 190.75it/s, test=27.4%, test_loss=0.704, train=28.7%, train_loss=0.631]

process_architecture/outcome:  67%|██████▋   | 1337/2000 [00:07<00:03, 190.75it/s, test=26.5%, test_loss=0.720, train=28.0%, train_loss=0.649]

process_architecture/outcome:  68%|██████▊   | 1357/2000 [00:07<00:03, 185.47it/s, test=26.5%, test_loss=0.720, train=28.0%, train_loss=0.649]

process_architecture/outcome:  69%|██████▉   | 1378/2000 [00:07<00:03, 189.88it/s, test=26.5%, test_loss=0.720, train=28.0%, train_loss=0.649]

process_architecture/outcome:  70%|██████▉   | 1399/2000 [00:07<00:03, 194.36it/s, test=26.5%, test_loss=0.720, train=28.0%, train_loss=0.649]

process_architecture/outcome:  70%|██████▉   | 1399/2000 [00:07<00:03, 194.36it/s, test=27.9%, test_loss=0.737, train=26.0%, train_loss=0.634]

process_architecture/outcome:  71%|███████   | 1419/2000 [00:07<00:03, 186.85it/s, test=27.9%, test_loss=0.737, train=26.0%, train_loss=0.634]

process_architecture/outcome:  72%|███████▏  | 1440/2000 [00:07<00:02, 191.35it/s, test=27.9%, test_loss=0.737, train=26.0%, train_loss=0.634]

process_architecture/outcome:  72%|███████▏  | 1440/2000 [00:08<00:02, 191.35it/s, test=26.6%, test_loss=0.755, train=28.7%, train_loss=0.654]

process_architecture/outcome:  73%|███████▎  | 1460/2000 [00:08<00:02, 185.31it/s, test=26.6%, test_loss=0.755, train=28.7%, train_loss=0.654]

process_architecture/outcome:  74%|███████▍  | 1481/2000 [00:08<00:02, 190.98it/s, test=26.6%, test_loss=0.755, train=28.7%, train_loss=0.654]

process_architecture/outcome:  74%|███████▍  | 1481/2000 [00:08<00:02, 190.98it/s, test=26.6%, test_loss=0.692, train=34.7%, train_loss=0.579]

process_architecture/outcome:  75%|███████▌  | 1501/2000 [00:08<00:02, 186.22it/s, test=26.6%, test_loss=0.692, train=34.7%, train_loss=0.579]

process_architecture/outcome:  76%|███████▌  | 1521/2000 [00:08<00:02, 190.00it/s, test=26.6%, test_loss=0.692, train=34.7%, train_loss=0.579]

process_architecture/outcome:  77%|███████▋  | 1542/2000 [00:08<00:02, 193.22it/s, test=26.6%, test_loss=0.692, train=34.7%, train_loss=0.579]

process_architecture/outcome:  77%|███████▋  | 1542/2000 [00:08<00:02, 193.22it/s, test=28.4%, test_loss=0.697, train=32.3%, train_loss=0.617]

process_architecture/outcome:  78%|███████▊  | 1562/2000 [00:08<00:02, 187.15it/s, test=28.4%, test_loss=0.697, train=32.3%, train_loss=0.617]

process_architecture/outcome:  79%|███████▉  | 1583/2000 [00:08<00:02, 192.27it/s, test=28.4%, test_loss=0.697, train=32.3%, train_loss=0.617]

process_architecture/outcome:  79%|███████▉  | 1583/2000 [00:08<00:02, 192.27it/s, test=30.9%, test_loss=0.703, train=30.3%, train_loss=0.558]

process_architecture/outcome:  80%|████████  | 1603/2000 [00:08<00:02, 186.05it/s, test=30.9%, test_loss=0.703, train=30.3%, train_loss=0.558]

process_architecture/outcome:  81%|████████  | 1623/2000 [00:08<00:01, 189.72it/s, test=30.9%, test_loss=0.703, train=30.3%, train_loss=0.558]

process_architecture/outcome:  82%|████████▏ | 1643/2000 [00:09<00:01, 192.52it/s, test=30.9%, test_loss=0.703, train=30.3%, train_loss=0.558]

process_architecture/outcome:  82%|████████▏ | 1643/2000 [00:09<00:01, 192.52it/s, test=31.1%, test_loss=0.689, train=32.3%, train_loss=0.624]

process_architecture/outcome:  83%|████████▎ | 1663/2000 [00:09<00:01, 186.14it/s, test=31.1%, test_loss=0.689, train=32.3%, train_loss=0.624]

process_architecture/outcome:  84%|████████▍ | 1684/2000 [00:09<00:01, 191.62it/s, test=31.1%, test_loss=0.689, train=32.3%, train_loss=0.624]

process_architecture/outcome:  84%|████████▍ | 1684/2000 [00:09<00:01, 191.62it/s, test=31.4%, test_loss=0.650, train=34.7%, train_loss=0.591]

process_architecture/outcome:  85%|████████▌ | 1704/2000 [00:09<00:01, 185.78it/s, test=31.4%, test_loss=0.650, train=34.7%, train_loss=0.591]

process_architecture/outcome:  86%|████████▌ | 1724/2000 [00:09<00:01, 189.66it/s, test=31.4%, test_loss=0.650, train=34.7%, train_loss=0.591]

process_architecture/outcome:  87%|████████▋ | 1744/2000 [00:09<00:01, 192.58it/s, test=31.4%, test_loss=0.650, train=34.7%, train_loss=0.591]

process_architecture/outcome:  87%|████████▋ | 1744/2000 [00:09<00:01, 192.58it/s, test=29.8%, test_loss=0.673, train=35.7%, train_loss=0.594]

process_architecture/outcome:  88%|████████▊ | 1764/2000 [00:09<00:01, 185.65it/s, test=29.8%, test_loss=0.673, train=35.7%, train_loss=0.594]

process_architecture/outcome:  89%|████████▉ | 1785/2000 [00:09<00:01, 191.06it/s, test=29.8%, test_loss=0.673, train=35.7%, train_loss=0.594]

process_architecture/outcome:  89%|████████▉ | 1785/2000 [00:09<00:01, 191.06it/s, test=31.4%, test_loss=0.718, train=34.0%, train_loss=0.602]

process_architecture/outcome:  90%|█████████ | 1805/2000 [00:09<00:01, 185.08it/s, test=31.4%, test_loss=0.718, train=34.0%, train_loss=0.602]

process_architecture/outcome:  91%|█████████▏| 1825/2000 [00:10<00:00, 189.17it/s, test=31.4%, test_loss=0.718, train=34.0%, train_loss=0.602]

process_architecture/outcome:  92%|█████████▏| 1845/2000 [00:10<00:00, 192.22it/s, test=31.4%, test_loss=0.718, train=34.0%, train_loss=0.602]

process_architecture/outcome:  92%|█████████▏| 1845/2000 [00:10<00:00, 192.22it/s, test=31.1%, test_loss=0.649, train=38.3%, train_loss=0.588]

process_architecture/outcome:  93%|█████████▎| 1865/2000 [00:10<00:00, 186.84it/s, test=31.1%, test_loss=0.649, train=38.3%, train_loss=0.588]

process_architecture/outcome:  94%|█████████▍| 1886/2000 [00:10<00:00, 192.23it/s, test=31.1%, test_loss=0.649, train=38.3%, train_loss=0.588]

process_architecture/outcome:  94%|█████████▍| 1886/2000 [00:10<00:00, 192.23it/s, test=31.7%, test_loss=0.663, train=33.7%, train_loss=0.609]

process_architecture/outcome:  95%|█████████▌| 1906/2000 [00:10<00:00, 184.67it/s, test=31.7%, test_loss=0.663, train=33.7%, train_loss=0.609]

process_architecture/outcome:  96%|█████████▋| 1926/2000 [00:10<00:00, 188.29it/s, test=31.7%, test_loss=0.663, train=33.7%, train_loss=0.609]

process_architecture/outcome:  97%|█████████▋| 1946/2000 [00:10<00:00, 191.61it/s, test=31.7%, test_loss=0.663, train=33.7%, train_loss=0.609]

process_architecture/outcome:  97%|█████████▋| 1946/2000 [00:10<00:00, 191.61it/s, test=34.6%, test_loss=0.657, train=38.3%, train_loss=0.527]

process_architecture/outcome:  98%|█████████▊| 1966/2000 [00:10<00:00, 186.15it/s, test=34.6%, test_loss=0.657, train=38.3%, train_loss=0.527]

process_architecture/outcome:  99%|█████████▉| 1987/2000 [00:10<00:00, 190.73it/s, test=34.6%, test_loss=0.657, train=38.3%, train_loss=0.527]

process_architecture/outcome:  99%|█████████▉| 1987/2000 [00:10<00:00, 190.73it/s, test=34.6%, test_loss=0.635, train=37.7%, train_loss=0.579]

process_architecture/outcome: 100%|██████████| 2000/2000 [00:10<00:00, 182.82it/s, test=34.6%, test_loss=0.635, train=37.7%, train_loss=0.579]

architecture/mode:  25%|██▌       | 1/4 [00:10<00:32, 10.96s/it]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.262, train=0.0%, train_loss=4.263]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.240, train=0.0%, train_loss=4.241]

process_architecture/process:   0%|          | 2/2000 [00:00<01:56, 17.17it/s, test=0.0%, test_loss=4.240, train=0.0%, train_loss=4.241]

process_architecture/process:   0%|          | 2/2000 [00:00<01:56, 17.17it/s, test=0.0%, test_loss=3.942, train=0.0%, train_loss=3.956]

process_architecture/process:   0%|          | 2/2000 [00:00<01:56, 17.17it/s, test=0.0%, test_loss=3.663, train=0.0%, train_loss=3.676]

process_architecture/process:   0%|          | 10/2000 [00:00<00:39, 50.39it/s, test=0.0%, test_loss=3.663, train=0.0%, train_loss=3.676]

process_architecture/process:   0%|          | 10/2000 [00:00<00:39, 50.39it/s, test=7.7%, test_loss=2.991, train=4.0%, train_loss=2.996]

process_architecture/process:   1%|          | 20/2000 [00:00<00:27, 71.15it/s, test=7.7%, test_loss=2.991, train=4.0%, train_loss=2.996]

process_architecture/process:   1%|          | 20/2000 [00:00<00:27, 71.15it/s, test=6.5%, test_loss=2.752, train=8.7%, train_loss=2.771]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:24, 81.11it/s, test=6.5%, test_loss=2.752, train=8.7%, train_loss=2.771]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:24, 81.11it/s, test=8.1%, test_loss=2.570, train=4.7%, train_loss=2.595]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:18, 103.07it/s, test=8.1%, test_loss=2.570, train=4.7%, train_loss=2.595]

process_architecture/process:   4%|▎         | 70/2000 [00:00<00:14, 130.95it/s, test=8.1%, test_loss=2.570, train=4.7%, train_loss=2.595]

process_architecture/process:   4%|▎         | 70/2000 [00:00<00:14, 130.95it/s, test=11.4%, test_loss=2.382, train=7.7%, train_loss=2.417]

process_architecture/process:   4%|▍         | 84/2000 [00:00<00:15, 125.37it/s, test=11.4%, test_loss=2.382, train=7.7%, train_loss=2.417]

process_architecture/process:   4%|▍         | 84/2000 [00:00<00:15, 125.37it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   5%|▌         | 100/2000 [00:00<00:15, 124.12it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   6%|▌         | 120/2000 [00:01<00:12, 144.66it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   7%|▋         | 141/2000 [00:01<00:11, 161.32it/s, test=12.7%, test_loss=2.220, train=7.7%, train_loss=2.215]

process_architecture/process:   7%|▋         | 141/2000 [00:01<00:11, 161.32it/s, test=13.2%, test_loss=1.918, train=10.7%, train_loss=1.904]

process_architecture/process:   8%|▊         | 158/2000 [00:01<00:12, 148.28it/s, test=13.2%, test_loss=1.918, train=10.7%, train_loss=1.904]

process_architecture/process:   9%|▉         | 179/2000 [00:01<00:11, 163.84it/s, test=13.2%, test_loss=1.918, train=10.7%, train_loss=1.904]

process_architecture/process:   9%|▉         | 179/2000 [00:01<00:11, 163.84it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  10%|█         | 200/2000 [00:01<00:11, 152.18it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  11%|█         | 220/2000 [00:01<00:10, 164.14it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  12%|█▏        | 241/2000 [00:01<00:10, 174.06it/s, test=20.9%, test_loss=0.422, train=15.0%, train_loss=0.429]

process_architecture/process:  12%|█▏        | 241/2000 [00:01<00:10, 174.06it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  13%|█▎        | 259/2000 [00:01<00:10, 158.44it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  14%|█▍        | 278/2000 [00:01<00:10, 166.41it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  15%|█▍        | 297/2000 [00:02<00:09, 171.66it/s, test=41.9%, test_loss=0.195, train=38.0%, train_loss=0.214]

process_architecture/process:  15%|█▍        | 297/2000 [00:02<00:09, 171.66it/s, test=68.9%, test_loss=0.094, train=68.0%, train_loss=0.093]

process_architecture/process:  16%|█▌        | 315/2000 [00:02<00:10, 153.45it/s, test=68.9%, test_loss=0.094, train=68.0%, train_loss=0.093]

process_architecture/process:  17%|█▋        | 336/2000 [00:02<00:09, 166.61it/s, test=68.9%, test_loss=0.094, train=68.0%, train_loss=0.093]

process_architecture/process:  17%|█▋        | 336/2000 [00:02<00:09, 166.61it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  18%|█▊        | 354/2000 [00:02<00:11, 146.57it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  19%|█▊        | 373/2000 [00:02<00:10, 156.32it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  20%|█▉        | 392/2000 [00:02<00:09, 164.80it/s, test=82.4%, test_loss=0.061, train=83.7%, train_loss=0.058]

process_architecture/process:  20%|█▉        | 392/2000 [00:02<00:09, 164.80it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  20%|██        | 410/2000 [00:02<00:10, 148.93it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  21%|██▏       | 429/2000 [00:02<00:09, 158.68it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  22%|██▏       | 448/2000 [00:03<00:09, 165.22it/s, test=93.7%, test_loss=0.019, train=92.7%, train_loss=0.024]

process_architecture/process:  22%|██▏       | 448/2000 [00:03<00:09, 165.22it/s, test=98.6%, test_loss=0.008, train=98.3%, train_loss=0.008]

process_architecture/process:  23%|██▎       | 466/2000 [00:03<00:10, 148.57it/s, test=98.6%, test_loss=0.008, train=98.3%, train_loss=0.008]

process_architecture/process:  24%|██▍       | 485/2000 [00:03<00:09, 159.08it/s, test=98.6%, test_loss=0.008, train=98.3%, train_loss=0.008]

process_architecture/process:  24%|██▍       | 485/2000 [00:03<00:09, 159.08it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  25%|██▌       | 502/2000 [00:03<00:10, 144.07it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  26%|██▌       | 521/2000 [00:03<00:09, 154.02it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  27%|██▋       | 540/2000 [00:03<00:09, 161.71it/s, test=100.0%, test_loss=0.004, train=100.0%, train_loss=0.003]

process_architecture/process:  27%|██▋       | 540/2000 [00:03<00:09, 161.71it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  28%|██▊       | 557/2000 [00:03<00:09, 146.02it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  29%|██▉       | 576/2000 [00:03<00:09, 157.07it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  30%|██▉       | 595/2000 [00:04<00:08, 165.53it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  30%|██▉       | 595/2000 [00:04<00:08, 165.53it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  31%|███       | 613/2000 [00:04<00:09, 148.19it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 632/2000 [00:04<00:08, 157.64it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▏      | 632/2000 [00:04<00:08, 157.64it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  32%|███▎      | 650/2000 [00:04<00:09, 144.42it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  33%|███▎      | 669/2000 [00:04<00:08, 154.65it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 688/2000 [00:04<00:08, 162.51it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  34%|███▍      | 688/2000 [00:04<00:08, 162.51it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  35%|███▌      | 705/2000 [00:04<00:08, 146.16it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  36%|███▌      | 724/2000 [00:04<00:08, 156.70it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  37%|███▋      | 743/2000 [00:04<00:07, 165.08it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  37%|███▋      | 743/2000 [00:05<00:07, 165.08it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  38%|███▊      | 761/2000 [00:05<00:08, 148.81it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  39%|███▉      | 780/2000 [00:05<00:07, 158.25it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  40%|███▉      | 799/2000 [00:05<00:07, 165.23it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  40%|███▉      | 799/2000 [00:05<00:07, 165.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  41%|████      | 816/2000 [00:05<00:08, 147.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  42%|████▏     | 835/2000 [00:05<00:07, 157.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  42%|████▏     | 835/2000 [00:05<00:07, 157.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  43%|████▎     | 852/2000 [00:05<00:08, 143.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  44%|████▎     | 871/2000 [00:05<00:07, 155.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  44%|████▍     | 890/2000 [00:05<00:06, 163.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.001]

process_architecture/process:  44%|████▍     | 890/2000 [00:06<00:06, 163.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 907/2000 [00:06<00:07, 146.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 926/2000 [00:06<00:06, 156.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 945/2000 [00:06<00:06, 164.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 945/2000 [00:06<00:06, 164.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 962/2000 [00:06<00:07, 147.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 982/2000 [00:06<00:06, 159.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 982/2000 [00:06<00:06, 159.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1000/2000 [00:06<00:06, 145.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1019/2000 [00:06<00:06, 155.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1038/2000 [00:06<00:05, 163.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1038/2000 [00:06<00:05, 163.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1055/2000 [00:07<00:06, 147.03it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▎    | 1074/2000 [00:07<00:05, 157.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▍    | 1093/2000 [00:07<00:05, 165.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▍    | 1093/2000 [00:07<00:05, 165.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1111/2000 [00:07<00:05, 148.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▋    | 1130/2000 [00:07<00:05, 157.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1149/2000 [00:07<00:05, 165.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1149/2000 [00:07<00:05, 165.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1167/2000 [00:07<00:05, 148.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1186/2000 [00:07<00:05, 157.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1186/2000 [00:07<00:05, 157.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1203/2000 [00:07<00:05, 143.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1222/2000 [00:08<00:05, 153.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1241/2000 [00:08<00:04, 162.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1241/2000 [00:08<00:04, 162.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1258/2000 [00:08<00:05, 146.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1277/2000 [00:08<00:04, 156.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1296/2000 [00:08<00:04, 164.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1296/2000 [00:08<00:04, 164.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1313/2000 [00:08<00:04, 147.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1332/2000 [00:08<00:04, 157.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1332/2000 [00:08<00:04, 157.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1350/2000 [00:08<00:04, 143.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1369/2000 [00:09<00:04, 155.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1388/2000 [00:09<00:03, 163.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1388/2000 [00:09<00:03, 163.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1405/2000 [00:09<00:04, 147.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████   | 1422/2000 [00:09<00:03, 152.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1441/2000 [00:09<00:03, 161.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1441/2000 [00:09<00:03, 161.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1458/2000 [00:09<00:03, 146.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1476/2000 [00:09<00:03, 153.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▍  | 1495/2000 [00:09<00:03, 163.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▍  | 1495/2000 [00:09<00:03, 163.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1512/2000 [00:09<00:03, 144.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1531/2000 [00:10<00:03, 155.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1531/2000 [00:10<00:03, 155.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1550/2000 [00:10<00:03, 143.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1568/2000 [00:10<00:02, 151.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1587/2000 [00:10<00:02, 160.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1587/2000 [00:10<00:02, 160.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1604/2000 [00:10<00:02, 145.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1621/2000 [00:10<00:02, 151.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1640/2000 [00:10<00:02, 161.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1640/2000 [00:10<00:02, 161.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1657/2000 [00:10<00:02, 143.73it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1676/2000 [00:11<00:02, 155.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1695/2000 [00:11<00:01, 164.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1695/2000 [00:11<00:01, 164.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1712/2000 [00:11<00:01, 144.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1731/2000 [00:11<00:01, 156.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1731/2000 [00:11<00:01, 156.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1750/2000 [00:11<00:01, 144.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1768/2000 [00:11<00:01, 153.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1787/2000 [00:11<00:01, 162.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1787/2000 [00:11<00:01, 162.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|█████████ | 1804/2000 [00:11<00:01, 146.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1823/2000 [00:12<00:01, 156.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1842/2000 [00:12<00:00, 164.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1842/2000 [00:12<00:00, 164.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1859/2000 [00:12<00:00, 148.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1878/2000 [00:12<00:00, 158.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1897/2000 [00:12<00:00, 166.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1897/2000 [00:12<00:00, 166.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1915/2000 [00:12<00:00, 150.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1935/2000 [00:12<00:00, 161.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1935/2000 [00:12<00:00, 161.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1952/2000 [00:12<00:00, 146.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▊| 1971/2000 [00:12<00:00, 156.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1990/2000 [00:13<00:00, 164.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1990/2000 [00:13<00:00, 164.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:13<00:00, 151.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode:  50%|█████     | 2/4 [00:24<00:24, 12.29s/it]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.387, train=0.0%, train_loss=3.388]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=15.568, train=0.0%, train_loss=15.587]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.681, train=0.0%, train_loss=3.681]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:54, 36.39it/s, test=0.0%, test_loss=3.681, train=0.0%, train_loss=3.681]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:54, 36.39it/s, test=0.0%, test_loss=1.125, train=0.0%, train_loss=1.134]

outcome_architecture/outcome:   1%|          | 12/2000 [00:00<00:37, 53.25it/s, test=0.0%, test_loss=1.125, train=0.0%, train_loss=1.134]

outcome_architecture/outcome:   1%|          | 12/2000 [00:00<00:37, 53.25it/s, test=5.4%, test_loss=1.020, train=6.0%, train_loss=1.033]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:33, 59.97it/s, test=5.4%, test_loss=1.020, train=6.0%, train_loss=1.033]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:33, 59.97it/s, test=0.0%, test_loss=1.439, train=0.0%, train_loss=1.496]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:31, 61.73it/s, test=0.0%, test_loss=1.439, train=0.0%, train_loss=1.496]

outcome_architecture/outcome:   2%|▏         | 37/2000 [00:00<00:26, 73.91it/s, test=0.0%, test_loss=1.439, train=0.0%, train_loss=1.496]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:23, 81.93it/s, test=0.0%, test_loss=1.439, train=0.0%, train_loss=1.496]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:23, 81.93it/s, test=5.9%, test_loss=0.950, train=5.3%, train_loss=0.970]

outcome_architecture/outcome:   3%|▎         | 56/2000 [00:00<00:24, 77.80it/s, test=5.9%, test_loss=0.950, train=5.3%, train_loss=0.970]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:00<00:23, 83.99it/s, test=5.9%, test_loss=0.950, train=5.3%, train_loss=0.970]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:01<00:23, 83.99it/s, test=6.7%, test_loss=0.937, train=10.0%, train_loss=0.941]

outcome_architecture/outcome:   4%|▍         | 75/2000 [00:01<00:24, 79.39it/s, test=6.7%, test_loss=0.937, train=10.0%, train_loss=0.941]

outcome_architecture/outcome:   4%|▍         | 85/2000 [00:01<00:22, 84.66it/s, test=6.7%, test_loss=0.937, train=10.0%, train_loss=0.941]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 88.58it/s, test=6.7%, test_loss=0.937, train=10.0%, train_loss=0.941]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 88.58it/s, test=9.5%, test_loss=0.924, train=9.0%, train_loss=0.929]

outcome_architecture/outcome:   5%|▌         | 104/2000 [00:01<00:22, 82.48it/s, test=9.5%, test_loss=0.924, train=9.0%, train_loss=0.929]

outcome_architecture/outcome:   6%|▌         | 114/2000 [00:01<00:21, 86.89it/s, test=9.5%, test_loss=0.924, train=9.0%, train_loss=0.929]

outcome_architecture/outcome:   6%|▌         | 124/2000 [00:01<00:20, 89.98it/s, test=9.5%, test_loss=0.924, train=9.0%, train_loss=0.929]

outcome_architecture/outcome:   7%|▋         | 134/2000 [00:01<00:20, 92.51it/s, test=9.5%, test_loss=0.924, train=9.0%, train_loss=0.929]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:19, 93.91it/s, test=9.5%, test_loss=0.924, train=9.0%, train_loss=0.929]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:19, 93.91it/s, test=11.7%, test_loss=0.895, train=10.3%, train_loss=0.902]

outcome_architecture/outcome:   8%|▊         | 154/2000 [00:01<00:21, 85.76it/s, test=11.7%, test_loss=0.895, train=10.3%, train_loss=0.902]

outcome_architecture/outcome:   8%|▊         | 164/2000 [00:02<00:20, 89.24it/s, test=11.7%, test_loss=0.895, train=10.3%, train_loss=0.902]

outcome_architecture/outcome:   9%|▊         | 174/2000 [00:02<00:19, 91.82it/s, test=11.7%, test_loss=0.895, train=10.3%, train_loss=0.902]

outcome_architecture/outcome:   9%|▉         | 184/2000 [00:02<00:19, 93.83it/s, test=11.7%, test_loss=0.895, train=10.3%, train_loss=0.902]

outcome_architecture/outcome:  10%|▉         | 194/2000 [00:02<00:19, 94.88it/s, test=11.7%, test_loss=0.895, train=10.3%, train_loss=0.902]

outcome_architecture/outcome:  10%|▉         | 194/2000 [00:02<00:19, 94.88it/s, test=11.6%, test_loss=0.900, train=9.7%, train_loss=0.898]

outcome_architecture/outcome:  10%|█         | 204/2000 [00:02<00:20, 85.98it/s, test=11.6%, test_loss=0.900, train=9.7%, train_loss=0.898]

outcome_architecture/outcome:  11%|█         | 214/2000 [00:02<00:20, 89.01it/s, test=11.6%, test_loss=0.900, train=9.7%, train_loss=0.898]

outcome_architecture/outcome:  11%|█         | 224/2000 [00:02<00:19, 91.35it/s, test=11.6%, test_loss=0.900, train=9.7%, train_loss=0.898]

outcome_architecture/outcome:  12%|█▏        | 234/2000 [00:02<00:18, 92.97it/s, test=11.6%, test_loss=0.900, train=9.7%, train_loss=0.898]

outcome_architecture/outcome:  12%|█▏        | 244/2000 [00:02<00:18, 92.99it/s, test=11.6%, test_loss=0.900, train=9.7%, train_loss=0.898]

outcome_architecture/outcome:  12%|█▏        | 244/2000 [00:02<00:18, 92.99it/s, test=11.6%, test_loss=0.893, train=10.0%, train_loss=0.887]

outcome_architecture/outcome:  13%|█▎        | 254/2000 [00:03<00:20, 85.03it/s, test=11.6%, test_loss=0.893, train=10.0%, train_loss=0.887]

outcome_architecture/outcome:  13%|█▎        | 264/2000 [00:03<00:19, 88.63it/s, test=11.6%, test_loss=0.893, train=10.0%, train_loss=0.887]

outcome_architecture/outcome:  14%|█▎        | 274/2000 [00:03<00:18, 91.52it/s, test=11.6%, test_loss=0.893, train=10.0%, train_loss=0.887]

outcome_architecture/outcome:  14%|█▍        | 284/2000 [00:03<00:18, 93.22it/s, test=11.6%, test_loss=0.893, train=10.0%, train_loss=0.887]

outcome_architecture/outcome:  15%|█▍        | 294/2000 [00:03<00:18, 94.31it/s, test=11.6%, test_loss=0.893, train=10.0%, train_loss=0.887]

outcome_architecture/outcome:  15%|█▍        | 294/2000 [00:03<00:18, 94.31it/s, test=13.1%, test_loss=0.905, train=7.3%, train_loss=0.893]

outcome_architecture/outcome:  15%|█▌        | 304/2000 [00:03<00:19, 86.50it/s, test=13.1%, test_loss=0.905, train=7.3%, train_loss=0.893]

outcome_architecture/outcome:  16%|█▌        | 314/2000 [00:03<00:18, 89.94it/s, test=13.1%, test_loss=0.905, train=7.3%, train_loss=0.893]

outcome_architecture/outcome:  16%|█▌        | 324/2000 [00:03<00:18, 91.49it/s, test=13.1%, test_loss=0.905, train=7.3%, train_loss=0.893]

outcome_architecture/outcome:  17%|█▋        | 334/2000 [00:03<00:17, 93.50it/s, test=13.1%, test_loss=0.905, train=7.3%, train_loss=0.893]

outcome_architecture/outcome:  17%|█▋        | 344/2000 [00:03<00:17, 94.94it/s, test=13.1%, test_loss=0.905, train=7.3%, train_loss=0.893]

outcome_architecture/outcome:  17%|█▋        | 344/2000 [00:04<00:17, 94.94it/s, test=12.4%, test_loss=0.889, train=11.7%, train_loss=0.906]

outcome_architecture/outcome:  18%|█▊        | 354/2000 [00:04<00:18, 86.67it/s, test=12.4%, test_loss=0.889, train=11.7%, train_loss=0.906]

outcome_architecture/outcome:  18%|█▊        | 364/2000 [00:04<00:18, 90.07it/s, test=12.4%, test_loss=0.889, train=11.7%, train_loss=0.906]

outcome_architecture/outcome:  19%|█▊        | 374/2000 [00:04<00:17, 91.98it/s, test=12.4%, test_loss=0.889, train=11.7%, train_loss=0.906]

outcome_architecture/outcome:  19%|█▉        | 384/2000 [00:04<00:17, 92.97it/s, test=12.4%, test_loss=0.889, train=11.7%, train_loss=0.906]

outcome_architecture/outcome:  20%|█▉        | 394/2000 [00:04<00:17, 89.56it/s, test=12.4%, test_loss=0.889, train=11.7%, train_loss=0.906]

outcome_architecture/outcome:  20%|█▉        | 394/2000 [00:04<00:17, 89.56it/s, test=12.0%, test_loss=0.916, train=10.0%, train_loss=0.938]

outcome_architecture/outcome:  20%|██        | 404/2000 [00:04<00:20, 79.78it/s, test=12.0%, test_loss=0.916, train=10.0%, train_loss=0.938]

outcome_architecture/outcome:  21%|██        | 413/2000 [00:04<00:19, 82.07it/s, test=12.0%, test_loss=0.916, train=10.0%, train_loss=0.938]

outcome_architecture/outcome:  21%|██        | 423/2000 [00:04<00:18, 85.94it/s, test=12.0%, test_loss=0.916, train=10.0%, train_loss=0.938]

outcome_architecture/outcome:  22%|██▏       | 433/2000 [00:04<00:17, 89.32it/s, test=12.0%, test_loss=0.916, train=10.0%, train_loss=0.938]

outcome_architecture/outcome:  22%|██▏       | 443/2000 [00:05<00:16, 91.88it/s, test=12.0%, test_loss=0.916, train=10.0%, train_loss=0.938]

outcome_architecture/outcome:  22%|██▏       | 443/2000 [00:05<00:16, 91.88it/s, test=11.6%, test_loss=0.898, train=12.0%, train_loss=0.886]

outcome_architecture/outcome:  23%|██▎       | 453/2000 [00:05<00:18, 84.66it/s, test=11.6%, test_loss=0.898, train=12.0%, train_loss=0.886]

outcome_architecture/outcome:  23%|██▎       | 463/2000 [00:05<00:17, 88.41it/s, test=11.6%, test_loss=0.898, train=12.0%, train_loss=0.886]

outcome_architecture/outcome:  24%|██▎       | 473/2000 [00:05<00:16, 90.47it/s, test=11.6%, test_loss=0.898, train=12.0%, train_loss=0.886]

outcome_architecture/outcome:  24%|██▍       | 483/2000 [00:05<00:16, 92.61it/s, test=11.6%, test_loss=0.898, train=12.0%, train_loss=0.886]

outcome_architecture/outcome:  25%|██▍       | 493/2000 [00:05<00:15, 94.51it/s, test=11.6%, test_loss=0.898, train=12.0%, train_loss=0.886]

outcome_architecture/outcome:  25%|██▍       | 493/2000 [00:05<00:15, 94.51it/s, test=11.6%, test_loss=0.905, train=9.3%, train_loss=0.895]

outcome_architecture/outcome:  25%|██▌       | 503/2000 [00:05<00:17, 86.25it/s, test=11.6%, test_loss=0.905, train=9.3%, train_loss=0.895]

outcome_architecture/outcome:  26%|██▌       | 513/2000 [00:05<00:16, 89.64it/s, test=11.6%, test_loss=0.905, train=9.3%, train_loss=0.895]

outcome_architecture/outcome:  26%|██▌       | 523/2000 [00:05<00:16, 92.10it/s, test=11.6%, test_loss=0.905, train=9.3%, train_loss=0.895]

outcome_architecture/outcome:  27%|██▋       | 533/2000 [00:06<00:15, 94.13it/s, test=11.6%, test_loss=0.905, train=9.3%, train_loss=0.895]

outcome_architecture/outcome:  27%|██▋       | 544/2000 [00:06<00:15, 95.93it/s, test=11.6%, test_loss=0.905, train=9.3%, train_loss=0.895]

outcome_architecture/outcome:  27%|██▋       | 544/2000 [00:06<00:15, 95.93it/s, test=11.9%, test_loss=0.915, train=11.3%, train_loss=0.897]

outcome_architecture/outcome:  28%|██▊       | 554/2000 [00:06<00:16, 87.26it/s, test=11.9%, test_loss=0.915, train=11.3%, train_loss=0.897]

outcome_architecture/outcome:  28%|██▊       | 565/2000 [00:06<00:15, 90.92it/s, test=11.9%, test_loss=0.915, train=11.3%, train_loss=0.897]

outcome_architecture/outcome:  29%|██▉       | 575/2000 [00:06<00:15, 93.22it/s, test=11.9%, test_loss=0.915, train=11.3%, train_loss=0.897]

outcome_architecture/outcome:  29%|██▉       | 585/2000 [00:06<00:14, 95.05it/s, test=11.9%, test_loss=0.915, train=11.3%, train_loss=0.897]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:14, 96.41it/s, test=11.9%, test_loss=0.915, train=11.3%, train_loss=0.897]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:14, 96.41it/s, test=12.8%, test_loss=0.890, train=12.7%, train_loss=0.899]

outcome_architecture/outcome:  30%|███       | 605/2000 [00:06<00:15, 87.72it/s, test=12.8%, test_loss=0.890, train=12.7%, train_loss=0.899]

outcome_architecture/outcome:  31%|███       | 615/2000 [00:06<00:15, 90.98it/s, test=12.8%, test_loss=0.890, train=12.7%, train_loss=0.899]

outcome_architecture/outcome:  31%|███▏      | 625/2000 [00:07<00:14, 93.20it/s, test=12.8%, test_loss=0.890, train=12.7%, train_loss=0.899]

outcome_architecture/outcome:  32%|███▏      | 635/2000 [00:07<00:14, 94.65it/s, test=12.8%, test_loss=0.890, train=12.7%, train_loss=0.899]

outcome_architecture/outcome:  32%|███▏      | 645/2000 [00:07<00:14, 95.24it/s, test=12.8%, test_loss=0.890, train=12.7%, train_loss=0.899]

outcome_architecture/outcome:  32%|███▏      | 645/2000 [00:07<00:14, 95.24it/s, test=12.0%, test_loss=0.894, train=12.0%, train_loss=0.888]

outcome_architecture/outcome:  33%|███▎      | 655/2000 [00:07<00:15, 86.44it/s, test=12.0%, test_loss=0.894, train=12.0%, train_loss=0.888]

outcome_architecture/outcome:  33%|███▎      | 665/2000 [00:07<00:15, 88.96it/s, test=12.0%, test_loss=0.894, train=12.0%, train_loss=0.888]

outcome_architecture/outcome:  34%|███▍      | 675/2000 [00:07<00:14, 91.09it/s, test=12.0%, test_loss=0.894, train=12.0%, train_loss=0.888]

outcome_architecture/outcome:  34%|███▍      | 685/2000 [00:07<00:14, 92.69it/s, test=12.0%, test_loss=0.894, train=12.0%, train_loss=0.888]

outcome_architecture/outcome:  35%|███▍      | 695/2000 [00:07<00:13, 94.43it/s, test=12.0%, test_loss=0.894, train=12.0%, train_loss=0.888]

outcome_architecture/outcome:  35%|███▍      | 695/2000 [00:07<00:13, 94.43it/s, test=15.3%, test_loss=0.879, train=13.7%, train_loss=0.877]

outcome_architecture/outcome:  35%|███▌      | 705/2000 [00:08<00:15, 82.69it/s, test=15.3%, test_loss=0.879, train=13.7%, train_loss=0.877]

outcome_architecture/outcome:  36%|███▌      | 716/2000 [00:08<00:14, 88.57it/s, test=15.3%, test_loss=0.879, train=13.7%, train_loss=0.877]

outcome_architecture/outcome:  36%|███▋      | 727/2000 [00:08<00:13, 93.30it/s, test=15.3%, test_loss=0.879, train=13.7%, train_loss=0.877]

outcome_architecture/outcome:  37%|███▋      | 738/2000 [00:08<00:13, 96.79it/s, test=15.3%, test_loss=0.879, train=13.7%, train_loss=0.877]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:08<00:12, 98.86it/s, test=15.3%, test_loss=0.879, train=13.7%, train_loss=0.877]

outcome_architecture/outcome:  37%|███▋      | 749/2000 [00:08<00:12, 98.86it/s, test=14.5%, test_loss=0.888, train=15.0%, train_loss=0.881]

outcome_architecture/outcome:  38%|███▊      | 760/2000 [00:08<00:13, 91.37it/s, test=14.5%, test_loss=0.888, train=15.0%, train_loss=0.881]

outcome_architecture/outcome:  39%|███▊      | 771/2000 [00:08<00:12, 95.22it/s, test=14.5%, test_loss=0.888, train=15.0%, train_loss=0.881]

outcome_architecture/outcome:  39%|███▉      | 782/2000 [00:08<00:12, 98.04it/s, test=14.5%, test_loss=0.888, train=15.0%, train_loss=0.881]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:12, 100.07it/s, test=14.5%, test_loss=0.888, train=15.0%, train_loss=0.881]

outcome_architecture/outcome:  40%|███▉      | 793/2000 [00:08<00:12, 100.07it/s, test=16.4%, test_loss=0.869, train=16.0%, train_loss=0.865]

outcome_architecture/outcome:  40%|████      | 804/2000 [00:09<00:12, 92.18it/s, test=16.4%, test_loss=0.869, train=16.0%, train_loss=0.865]

outcome_architecture/outcome:  41%|████      | 815/2000 [00:09<00:12, 95.73it/s, test=16.4%, test_loss=0.869, train=16.0%, train_loss=0.865]

outcome_architecture/outcome:  41%|████▏     | 826/2000 [00:09<00:11, 98.44it/s, test=16.4%, test_loss=0.869, train=16.0%, train_loss=0.865]

outcome_architecture/outcome:  42%|████▏     | 837/2000 [00:09<00:11, 100.57it/s, test=16.4%, test_loss=0.869, train=16.0%, train_loss=0.865]

outcome_architecture/outcome:  42%|████▏     | 848/2000 [00:09<00:11, 101.96it/s, test=16.4%, test_loss=0.869, train=16.0%, train_loss=0.865]

outcome_architecture/outcome:  42%|████▏     | 848/2000 [00:09<00:11, 101.96it/s, test=15.3%, test_loss=0.878, train=17.0%, train_loss=0.834]

outcome_architecture/outcome:  43%|████▎     | 859/2000 [00:09<00:12, 93.51it/s, test=15.3%, test_loss=0.878, train=17.0%, train_loss=0.834]

outcome_architecture/outcome:  44%|████▎     | 870/2000 [00:09<00:11, 97.00it/s, test=15.3%, test_loss=0.878, train=17.0%, train_loss=0.834]

outcome_architecture/outcome:  44%|████▍     | 881/2000 [00:09<00:11, 99.32it/s, test=15.3%, test_loss=0.878, train=17.0%, train_loss=0.834]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:10, 101.02it/s, test=15.3%, test_loss=0.878, train=17.0%, train_loss=0.834]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:10<00:10, 101.02it/s, test=16.7%, test_loss=0.885, train=14.3%, train_loss=0.827]

outcome_architecture/outcome:  45%|████▌     | 903/2000 [00:10<00:11, 92.76it/s, test=16.7%, test_loss=0.885, train=14.3%, train_loss=0.827]

outcome_architecture/outcome:  46%|████▌     | 914/2000 [00:10<00:11, 96.18it/s, test=16.7%, test_loss=0.885, train=14.3%, train_loss=0.827]

outcome_architecture/outcome:  46%|████▋     | 925/2000 [00:10<00:10, 98.77it/s, test=16.7%, test_loss=0.885, train=14.3%, train_loss=0.827]

outcome_architecture/outcome:  47%|████▋     | 936/2000 [00:10<00:10, 100.66it/s, test=16.7%, test_loss=0.885, train=14.3%, train_loss=0.827]

outcome_architecture/outcome:  47%|████▋     | 947/2000 [00:10<00:10, 101.37it/s, test=16.7%, test_loss=0.885, train=14.3%, train_loss=0.827]

outcome_architecture/outcome:  47%|████▋     | 947/2000 [00:10<00:10, 101.37it/s, test=18.7%, test_loss=0.858, train=17.0%, train_loss=0.829]

outcome_architecture/outcome:  48%|████▊     | 958/2000 [00:10<00:11, 93.18it/s, test=18.7%, test_loss=0.858, train=17.0%, train_loss=0.829]

outcome_architecture/outcome:  48%|████▊     | 969/2000 [00:10<00:10, 96.49it/s, test=18.7%, test_loss=0.858, train=17.0%, train_loss=0.829]

outcome_architecture/outcome:  49%|████▉     | 980/2000 [00:10<00:10, 98.96it/s, test=18.7%, test_loss=0.858, train=17.0%, train_loss=0.829]

outcome_architecture/outcome:  50%|████▉     | 991/2000 [00:10<00:10, 98.06it/s, test=18.7%, test_loss=0.858, train=17.0%, train_loss=0.829]

outcome_architecture/outcome:  50%|████▉     | 991/2000 [00:11<00:10, 98.06it/s, test=20.0%, test_loss=0.853, train=16.7%, train_loss=0.762]

outcome_architecture/outcome:  50%|█████     | 1001/2000 [00:11<00:11, 88.61it/s, test=20.0%, test_loss=0.853, train=16.7%, train_loss=0.762]

outcome_architecture/outcome:  51%|█████     | 1011/2000 [00:11<00:11, 88.41it/s, test=20.0%, test_loss=0.853, train=16.7%, train_loss=0.762]

outcome_architecture/outcome:  51%|█████     | 1021/2000 [00:11<00:10, 91.02it/s, test=20.0%, test_loss=0.853, train=16.7%, train_loss=0.762]

outcome_architecture/outcome:  52%|█████▏    | 1031/2000 [00:11<00:10, 93.02it/s, test=20.0%, test_loss=0.853, train=16.7%, train_loss=0.762]

outcome_architecture/outcome:  52%|█████▏    | 1041/2000 [00:11<00:10, 93.87it/s, test=20.0%, test_loss=0.853, train=16.7%, train_loss=0.762]

outcome_architecture/outcome:  52%|█████▏    | 1041/2000 [00:11<00:10, 93.87it/s, test=18.4%, test_loss=0.834, train=17.0%, train_loss=0.756]

outcome_architecture/outcome:  53%|█████▎    | 1051/2000 [00:11<00:10, 86.62it/s, test=18.4%, test_loss=0.834, train=17.0%, train_loss=0.756]

outcome_architecture/outcome:  53%|█████▎    | 1061/2000 [00:11<00:10, 88.99it/s, test=18.4%, test_loss=0.834, train=17.0%, train_loss=0.756]

outcome_architecture/outcome:  54%|█████▎    | 1071/2000 [00:11<00:10, 91.76it/s, test=18.4%, test_loss=0.834, train=17.0%, train_loss=0.756]

outcome_architecture/outcome:  54%|█████▍    | 1081/2000 [00:11<00:09, 93.31it/s, test=18.4%, test_loss=0.834, train=17.0%, train_loss=0.756]

outcome_architecture/outcome:  55%|█████▍    | 1091/2000 [00:12<00:09, 91.35it/s, test=18.4%, test_loss=0.834, train=17.0%, train_loss=0.756]

outcome_architecture/outcome:  55%|█████▍    | 1091/2000 [00:12<00:09, 91.35it/s, test=20.4%, test_loss=0.806, train=22.0%, train_loss=0.741]

outcome_architecture/outcome:  55%|█████▌    | 1101/2000 [00:12<00:10, 84.42it/s, test=20.4%, test_loss=0.806, train=22.0%, train_loss=0.741]

outcome_architecture/outcome:  56%|█████▌    | 1112/2000 [00:12<00:09, 90.42it/s, test=20.4%, test_loss=0.806, train=22.0%, train_loss=0.741]

outcome_architecture/outcome:  56%|█████▌    | 1123/2000 [00:12<00:09, 94.87it/s, test=20.4%, test_loss=0.806, train=22.0%, train_loss=0.741]

outcome_architecture/outcome:  57%|█████▋    | 1134/2000 [00:12<00:08, 98.19it/s, test=20.4%, test_loss=0.806, train=22.0%, train_loss=0.741]

outcome_architecture/outcome:  57%|█████▋    | 1145/2000 [00:12<00:08, 100.51it/s, test=20.4%, test_loss=0.806, train=22.0%, train_loss=0.741]

outcome_architecture/outcome:  57%|█████▋    | 1145/2000 [00:12<00:08, 100.51it/s, test=20.9%, test_loss=0.836, train=18.7%, train_loss=0.720]

outcome_architecture/outcome:  58%|█████▊    | 1156/2000 [00:12<00:09, 90.77it/s, test=20.9%, test_loss=0.836, train=18.7%, train_loss=0.720]

outcome_architecture/outcome:  58%|█████▊    | 1167/2000 [00:12<00:08, 94.92it/s, test=20.9%, test_loss=0.836, train=18.7%, train_loss=0.720]

outcome_architecture/outcome:  59%|█████▉    | 1178/2000 [00:12<00:08, 97.85it/s, test=20.9%, test_loss=0.836, train=18.7%, train_loss=0.720]

outcome_architecture/outcome:  59%|█████▉    | 1189/2000 [00:13<00:08, 100.17it/s, test=20.9%, test_loss=0.836, train=18.7%, train_loss=0.720]

outcome_architecture/outcome:  59%|█████▉    | 1189/2000 [00:13<00:08, 100.17it/s, test=19.3%, test_loss=0.855, train=21.7%, train_loss=0.711]

outcome_architecture/outcome:  60%|██████    | 1200/2000 [00:13<00:08, 92.78it/s, test=19.3%, test_loss=0.855, train=21.7%, train_loss=0.711]

outcome_architecture/outcome:  61%|██████    | 1211/2000 [00:13<00:08, 96.33it/s, test=19.3%, test_loss=0.855, train=21.7%, train_loss=0.711]

outcome_architecture/outcome:  61%|██████    | 1222/2000 [00:13<00:07, 98.89it/s, test=19.3%, test_loss=0.855, train=21.7%, train_loss=0.711]

outcome_architecture/outcome:  62%|██████▏   | 1233/2000 [00:13<00:07, 100.32it/s, test=19.3%, test_loss=0.855, train=21.7%, train_loss=0.711]

outcome_architecture/outcome:  62%|██████▏   | 1244/2000 [00:13<00:07, 99.20it/s, test=19.3%, test_loss=0.855, train=21.7%, train_loss=0.711]

outcome_architecture/outcome:  62%|██████▏   | 1244/2000 [00:13<00:07, 99.20it/s, test=19.1%, test_loss=0.792, train=20.7%, train_loss=0.709]

outcome_architecture/outcome:  63%|██████▎   | 1254/2000 [00:13<00:08, 88.20it/s, test=19.1%, test_loss=0.792, train=20.7%, train_loss=0.709]

outcome_architecture/outcome:  63%|██████▎   | 1264/2000 [00:13<00:08, 91.06it/s, test=19.1%, test_loss=0.792, train=20.7%, train_loss=0.709]

outcome_architecture/outcome:  64%|██████▎   | 1274/2000 [00:13<00:07, 93.07it/s, test=19.1%, test_loss=0.792, train=20.7%, train_loss=0.709]

outcome_architecture/outcome:  64%|██████▍   | 1284/2000 [00:14<00:07, 94.35it/s, test=19.1%, test_loss=0.792, train=20.7%, train_loss=0.709]

outcome_architecture/outcome:  65%|██████▍   | 1294/2000 [00:14<00:07, 95.41it/s, test=19.1%, test_loss=0.792, train=20.7%, train_loss=0.709]

outcome_architecture/outcome:  65%|██████▍   | 1294/2000 [00:14<00:07, 95.41it/s, test=22.4%, test_loss=0.754, train=27.0%, train_loss=0.705]

outcome_architecture/outcome:  65%|██████▌   | 1304/2000 [00:14<00:07, 87.21it/s, test=22.4%, test_loss=0.754, train=27.0%, train_loss=0.705]

outcome_architecture/outcome:  66%|██████▌   | 1314/2000 [00:14<00:07, 90.18it/s, test=22.4%, test_loss=0.754, train=27.0%, train_loss=0.705]

outcome_architecture/outcome:  66%|██████▌   | 1324/2000 [00:14<00:07, 92.45it/s, test=22.4%, test_loss=0.754, train=27.0%, train_loss=0.705]

outcome_architecture/outcome:  67%|██████▋   | 1334/2000 [00:14<00:07, 93.90it/s, test=22.4%, test_loss=0.754, train=27.0%, train_loss=0.705]

outcome_architecture/outcome:  67%|██████▋   | 1344/2000 [00:14<00:06, 95.11it/s, test=22.4%, test_loss=0.754, train=27.0%, train_loss=0.705]

outcome_architecture/outcome:  67%|██████▋   | 1344/2000 [00:14<00:06, 95.11it/s, test=23.8%, test_loss=0.744, train=24.3%, train_loss=0.660]

outcome_architecture/outcome:  68%|██████▊   | 1354/2000 [00:14<00:07, 83.74it/s, test=23.8%, test_loss=0.744, train=24.3%, train_loss=0.660]

outcome_architecture/outcome:  68%|██████▊   | 1363/2000 [00:14<00:07, 84.54it/s, test=23.8%, test_loss=0.744, train=24.3%, train_loss=0.660]

outcome_architecture/outcome:  69%|██████▊   | 1373/2000 [00:15<00:07, 88.29it/s, test=23.8%, test_loss=0.744, train=24.3%, train_loss=0.660]

outcome_architecture/outcome:  69%|██████▉   | 1383/2000 [00:15<00:06, 91.12it/s, test=23.8%, test_loss=0.744, train=24.3%, train_loss=0.660]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:15<00:06, 92.68it/s, test=23.8%, test_loss=0.744, train=24.3%, train_loss=0.660]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:15<00:06, 92.68it/s, test=23.1%, test_loss=0.762, train=23.3%, train_loss=0.665]

outcome_architecture/outcome:  70%|███████   | 1403/2000 [00:15<00:07, 84.79it/s, test=23.1%, test_loss=0.762, train=23.3%, train_loss=0.665]

outcome_architecture/outcome:  71%|███████   | 1413/2000 [00:15<00:06, 87.61it/s, test=23.1%, test_loss=0.762, train=23.3%, train_loss=0.665]

outcome_architecture/outcome:  71%|███████   | 1422/2000 [00:15<00:06, 88.09it/s, test=23.1%, test_loss=0.762, train=23.3%, train_loss=0.665]

outcome_architecture/outcome:  72%|███████▏  | 1432/2000 [00:15<00:06, 90.63it/s, test=23.1%, test_loss=0.762, train=23.3%, train_loss=0.665]

outcome_architecture/outcome:  72%|███████▏  | 1442/2000 [00:15<00:06, 92.09it/s, test=23.1%, test_loss=0.762, train=23.3%, train_loss=0.665]

outcome_architecture/outcome:  72%|███████▏  | 1442/2000 [00:15<00:06, 92.09it/s, test=24.6%, test_loss=0.740, train=25.0%, train_loss=0.643]

outcome_architecture/outcome:  73%|███████▎  | 1452/2000 [00:15<00:06, 84.40it/s, test=24.6%, test_loss=0.740, train=25.0%, train_loss=0.643]

outcome_architecture/outcome:  73%|███████▎  | 1462/2000 [00:16<00:06, 87.27it/s, test=24.6%, test_loss=0.740, train=25.0%, train_loss=0.643]

outcome_architecture/outcome:  74%|███████▎  | 1471/2000 [00:16<00:06, 87.99it/s, test=24.6%, test_loss=0.740, train=25.0%, train_loss=0.643]

outcome_architecture/outcome:  74%|███████▍  | 1481/2000 [00:16<00:05, 90.27it/s, test=24.6%, test_loss=0.740, train=25.0%, train_loss=0.643]

outcome_architecture/outcome:  75%|███████▍  | 1491/2000 [00:16<00:05, 92.46it/s, test=24.6%, test_loss=0.740, train=25.0%, train_loss=0.643]

outcome_architecture/outcome:  75%|███████▍  | 1491/2000 [00:16<00:05, 92.46it/s, test=24.8%, test_loss=0.743, train=30.3%, train_loss=0.599]

outcome_architecture/outcome:  75%|███████▌  | 1501/2000 [00:16<00:05, 84.35it/s, test=24.8%, test_loss=0.743, train=30.3%, train_loss=0.599]

outcome_architecture/outcome:  76%|███████▌  | 1511/2000 [00:16<00:05, 87.92it/s, test=24.8%, test_loss=0.743, train=30.3%, train_loss=0.599]

outcome_architecture/outcome:  76%|███████▌  | 1521/2000 [00:16<00:05, 90.93it/s, test=24.8%, test_loss=0.743, train=30.3%, train_loss=0.599]

outcome_architecture/outcome:  77%|███████▋  | 1531/2000 [00:16<00:05, 90.09it/s, test=24.8%, test_loss=0.743, train=30.3%, train_loss=0.599]

outcome_architecture/outcome:  77%|███████▋  | 1541/2000 [00:16<00:04, 92.68it/s, test=24.8%, test_loss=0.743, train=30.3%, train_loss=0.599]

outcome_architecture/outcome:  77%|███████▋  | 1541/2000 [00:17<00:04, 92.68it/s, test=24.7%, test_loss=0.716, train=25.7%, train_loss=0.640]

outcome_architecture/outcome:  78%|███████▊  | 1551/2000 [00:17<00:05, 85.21it/s, test=24.7%, test_loss=0.716, train=25.7%, train_loss=0.640]

outcome_architecture/outcome:  78%|███████▊  | 1562/2000 [00:17<00:04, 91.10it/s, test=24.7%, test_loss=0.716, train=25.7%, train_loss=0.640]

outcome_architecture/outcome:  79%|███████▊  | 1573/2000 [00:17<00:04, 95.37it/s, test=24.7%, test_loss=0.716, train=25.7%, train_loss=0.640]

outcome_architecture/outcome:  79%|███████▉  | 1584/2000 [00:17<00:04, 98.66it/s, test=24.7%, test_loss=0.716, train=25.7%, train_loss=0.640]

outcome_architecture/outcome:  80%|███████▉  | 1595/2000 [00:17<00:04, 100.30it/s, test=24.7%, test_loss=0.716, train=25.7%, train_loss=0.640]

outcome_architecture/outcome:  80%|███████▉  | 1595/2000 [00:17<00:04, 100.30it/s, test=24.8%, test_loss=0.732, train=32.0%, train_loss=0.614]

outcome_architecture/outcome:  80%|████████  | 1606/2000 [00:17<00:04, 92.76it/s, test=24.8%, test_loss=0.732, train=32.0%, train_loss=0.614]

outcome_architecture/outcome:  81%|████████  | 1617/2000 [00:17<00:03, 96.52it/s, test=24.8%, test_loss=0.732, train=32.0%, train_loss=0.614]

outcome_architecture/outcome:  81%|████████▏ | 1628/2000 [00:17<00:03, 99.17it/s, test=24.8%, test_loss=0.732, train=32.0%, train_loss=0.614]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:17<00:03, 101.21it/s, test=24.8%, test_loss=0.732, train=32.0%, train_loss=0.614]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:18<00:03, 101.21it/s, test=26.2%, test_loss=0.783, train=29.7%, train_loss=0.638]

outcome_architecture/outcome:  82%|████████▎ | 1650/2000 [00:18<00:03, 93.53it/s, test=26.2%, test_loss=0.783, train=29.7%, train_loss=0.638]

outcome_architecture/outcome:  83%|████████▎ | 1661/2000 [00:18<00:03, 96.98it/s, test=26.2%, test_loss=0.783, train=29.7%, train_loss=0.638]

outcome_architecture/outcome:  84%|████████▎ | 1672/2000 [00:18<00:03, 99.70it/s, test=26.2%, test_loss=0.783, train=29.7%, train_loss=0.638]

outcome_architecture/outcome:  84%|████████▍ | 1683/2000 [00:18<00:03, 101.60it/s, test=26.2%, test_loss=0.783, train=29.7%, train_loss=0.638]

outcome_architecture/outcome:  85%|████████▍ | 1694/2000 [00:18<00:02, 102.44it/s, test=26.2%, test_loss=0.783, train=29.7%, train_loss=0.638]

outcome_architecture/outcome:  85%|████████▍ | 1694/2000 [00:18<00:02, 102.44it/s, test=28.6%, test_loss=0.670, train=32.7%, train_loss=0.538]

outcome_architecture/outcome:  85%|████████▌ | 1705/2000 [00:18<00:03, 94.18it/s, test=28.6%, test_loss=0.670, train=32.7%, train_loss=0.538]

outcome_architecture/outcome:  86%|████████▌ | 1716/2000 [00:18<00:02, 97.53it/s, test=28.6%, test_loss=0.670, train=32.7%, train_loss=0.538]

outcome_architecture/outcome:  86%|████████▋ | 1727/2000 [00:18<00:02, 100.16it/s, test=28.6%, test_loss=0.670, train=32.7%, train_loss=0.538]

outcome_architecture/outcome:  87%|████████▋ | 1738/2000 [00:18<00:02, 102.40it/s, test=28.6%, test_loss=0.670, train=32.7%, train_loss=0.538]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:19<00:02, 101.42it/s, test=28.6%, test_loss=0.670, train=32.7%, train_loss=0.538]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:19<00:02, 101.42it/s, test=24.8%, test_loss=0.759, train=27.3%, train_loss=0.665]

outcome_architecture/outcome:  88%|████████▊ | 1760/2000 [00:19<00:02, 92.39it/s, test=24.8%, test_loss=0.759, train=27.3%, train_loss=0.665]

outcome_architecture/outcome:  89%|████████▊ | 1771/2000 [00:19<00:02, 95.29it/s, test=24.8%, test_loss=0.759, train=27.3%, train_loss=0.665]

outcome_architecture/outcome:  89%|████████▉ | 1782/2000 [00:19<00:02, 97.57it/s, test=24.8%, test_loss=0.759, train=27.3%, train_loss=0.665]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 98.48it/s, test=24.8%, test_loss=0.759, train=27.3%, train_loss=0.665]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 98.48it/s, test=28.1%, test_loss=0.690, train=33.0%, train_loss=0.567]

outcome_architecture/outcome:  90%|█████████ | 1803/2000 [00:19<00:02, 90.20it/s, test=28.1%, test_loss=0.690, train=33.0%, train_loss=0.567]

outcome_architecture/outcome:  91%|█████████ | 1814/2000 [00:19<00:01, 93.45it/s, test=28.1%, test_loss=0.690, train=33.0%, train_loss=0.567]

outcome_architecture/outcome:  91%|█████████▏| 1825/2000 [00:19<00:01, 95.61it/s, test=28.1%, test_loss=0.690, train=33.0%, train_loss=0.567]

outcome_architecture/outcome:  92%|█████████▏| 1836/2000 [00:19<00:01, 97.86it/s, test=28.1%, test_loss=0.690, train=33.0%, train_loss=0.567]

outcome_architecture/outcome:  92%|█████████▏| 1846/2000 [00:20<00:01, 97.64it/s, test=28.1%, test_loss=0.690, train=33.0%, train_loss=0.567]

outcome_architecture/outcome:  92%|█████████▏| 1846/2000 [00:20<00:01, 97.64it/s, test=31.8%, test_loss=0.632, train=33.0%, train_loss=0.575]

outcome_architecture/outcome:  93%|█████████▎| 1856/2000 [00:20<00:01, 89.77it/s, test=31.8%, test_loss=0.632, train=33.0%, train_loss=0.575]

outcome_architecture/outcome:  93%|█████████▎| 1867/2000 [00:20<00:01, 93.89it/s, test=31.8%, test_loss=0.632, train=33.0%, train_loss=0.575]

outcome_architecture/outcome:  94%|█████████▍| 1878/2000 [00:20<00:01, 96.50it/s, test=31.8%, test_loss=0.632, train=33.0%, train_loss=0.575]

outcome_architecture/outcome:  94%|█████████▍| 1888/2000 [00:20<00:01, 96.58it/s, test=31.8%, test_loss=0.632, train=33.0%, train_loss=0.575]

outcome_architecture/outcome:  95%|█████████▍| 1899/2000 [00:20<00:01, 98.89it/s, test=31.8%, test_loss=0.632, train=33.0%, train_loss=0.575]

outcome_architecture/outcome:  95%|█████████▍| 1899/2000 [00:20<00:01, 98.89it/s, test=31.2%, test_loss=0.666, train=31.3%, train_loss=0.620]

outcome_architecture/outcome:  95%|█████████▌| 1909/2000 [00:20<00:01, 90.79it/s, test=31.2%, test_loss=0.666, train=31.3%, train_loss=0.620]

outcome_architecture/outcome:  96%|█████████▌| 1920/2000 [00:20<00:00, 94.74it/s, test=31.2%, test_loss=0.666, train=31.3%, train_loss=0.620]

outcome_architecture/outcome:  97%|█████████▋| 1931/2000 [00:20<00:00, 97.69it/s, test=31.2%, test_loss=0.666, train=31.3%, train_loss=0.620]

outcome_architecture/outcome:  97%|█████████▋| 1942/2000 [00:21<00:00, 99.66it/s, test=31.2%, test_loss=0.666, train=31.3%, train_loss=0.620]

outcome_architecture/outcome:  97%|█████████▋| 1942/2000 [00:21<00:00, 99.66it/s, test=30.6%, test_loss=0.684, train=36.7%, train_loss=0.537]

outcome_architecture/outcome:  98%|█████████▊| 1953/2000 [00:21<00:00, 91.72it/s, test=30.6%, test_loss=0.684, train=36.7%, train_loss=0.537]

outcome_architecture/outcome:  98%|█████████▊| 1964/2000 [00:21<00:00, 95.35it/s, test=30.6%, test_loss=0.684, train=36.7%, train_loss=0.537]

outcome_architecture/outcome:  99%|█████████▉| 1975/2000 [00:21<00:00, 97.49it/s, test=30.6%, test_loss=0.684, train=36.7%, train_loss=0.537]

outcome_architecture/outcome:  99%|█████████▉| 1986/2000 [00:21<00:00, 99.16it/s, test=30.6%, test_loss=0.684, train=36.7%, train_loss=0.537]

outcome_architecture/outcome: 100%|█████████▉| 1997/2000 [00:21<00:00, 100.50it/s, test=30.6%, test_loss=0.684, train=36.7%, train_loss=0.537]

outcome_architecture/outcome: 100%|█████████▉| 1997/2000 [00:21<00:00, 100.50it/s, test=33.9%, test_loss=0.677, train=36.3%, train_loss=0.550]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 92.04it/s, test=33.9%, test_loss=0.677, train=36.3%, train_loss=0.550]

architecture/mode:  75%|███████▌  | 3/4 [00:45<00:16, 16.62s/it]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.051, train=0.0%, train_loss=4.057]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=24.711, train=0.0%, train_loss=25.127]

outcome_architecture/process:   0%|          | 3/2000 [00:00<01:07, 29.63it/s, test=0.0%, test_loss=24.711, train=0.0%, train_loss=25.127]

outcome_architecture/process:   0%|          | 3/2000 [00:00<01:07, 29.63it/s, test=7.5%, test_loss=4.103, train=7.0%, train_loss=4.105]

outcome_architecture/process:   0%|          | 6/2000 [00:00<01:39, 20.10it/s, test=7.5%, test_loss=4.103, train=7.0%, train_loss=4.105]

outcome_architecture/process:   0%|          | 6/2000 [00:00<01:39, 20.10it/s, test=0.0%, test_loss=3.667, train=0.0%, train_loss=3.671]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:36, 20.58it/s, test=0.0%, test_loss=3.667, train=0.0%, train_loss=3.671]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:36, 20.58it/s, test=6.6%, test_loss=2.704, train=5.7%, train_loss=2.749]

outcome_architecture/process:   1%|          | 20/2000 [00:00<01:06, 29.85it/s, test=6.6%, test_loss=2.704, train=5.7%, train_loss=2.749]

outcome_architecture/process:   1%|          | 20/2000 [00:00<01:06, 29.85it/s, test=6.4%, test_loss=2.887, train=5.0%, train_loss=2.935]

outcome_architecture/process:   1%|▏         | 25/2000 [00:00<01:10, 27.90it/s, test=6.4%, test_loss=2.887, train=5.0%, train_loss=2.935]

outcome_architecture/process:   2%|▏         | 36/2000 [00:01<00:44, 43.74it/s, test=6.4%, test_loss=2.887, train=5.0%, train_loss=2.935]

outcome_architecture/process:   2%|▏         | 46/2000 [00:01<00:35, 55.49it/s, test=6.4%, test_loss=2.887, train=5.0%, train_loss=2.935]

outcome_architecture/process:   2%|▏         | 46/2000 [00:01<00:35, 55.49it/s, test=11.8%, test_loss=2.554, train=7.3%, train_loss=2.607]

outcome_architecture/process:   3%|▎         | 53/2000 [00:01<00:42, 45.83it/s, test=11.8%, test_loss=2.554, train=7.3%, train_loss=2.607]

outcome_architecture/process:   3%|▎         | 64/2000 [00:01<00:33, 58.12it/s, test=11.8%, test_loss=2.554, train=7.3%, train_loss=2.607]

outcome_architecture/process:   4%|▎         | 74/2000 [00:01<00:28, 67.45it/s, test=11.8%, test_loss=2.554, train=7.3%, train_loss=2.607]

outcome_architecture/process:   4%|▎         | 74/2000 [00:01<00:28, 67.45it/s, test=10.9%, test_loss=2.497, train=8.3%, train_loss=2.506]

outcome_architecture/process:   4%|▍         | 82/2000 [00:01<00:35, 53.55it/s, test=10.9%, test_loss=2.497, train=8.3%, train_loss=2.506]

outcome_architecture/process:   5%|▍         | 93/2000 [00:01<00:29, 64.43it/s, test=10.9%, test_loss=2.497, train=8.3%, train_loss=2.506]

outcome_architecture/process:   5%|▍         | 93/2000 [00:02<00:29, 64.43it/s, test=9.6%, test_loss=2.417, train=11.7%, train_loss=2.432]

outcome_architecture/process:   5%|▌         | 101/2000 [00:02<00:36, 51.88it/s, test=9.6%, test_loss=2.417, train=11.7%, train_loss=2.432]

outcome_architecture/process:   6%|▌         | 112/2000 [00:02<00:30, 62.86it/s, test=9.6%, test_loss=2.417, train=11.7%, train_loss=2.432]

outcome_architecture/process:   6%|▌         | 123/2000 [00:02<00:25, 72.42it/s, test=9.6%, test_loss=2.417, train=11.7%, train_loss=2.432]

outcome_architecture/process:   7%|▋         | 134/2000 [00:02<00:23, 80.05it/s, test=9.6%, test_loss=2.417, train=11.7%, train_loss=2.432]

outcome_architecture/process:   7%|▋         | 145/2000 [00:02<00:21, 85.88it/s, test=9.6%, test_loss=2.417, train=11.7%, train_loss=2.432]

outcome_architecture/process:   7%|▋         | 145/2000 [00:02<00:21, 85.88it/s, test=0.0%, test_loss=4.369, train=0.0%, train_loss=4.182]

outcome_architecture/process:   8%|▊         | 155/2000 [00:02<00:28, 64.26it/s, test=0.0%, test_loss=4.369, train=0.0%, train_loss=4.182]

outcome_architecture/process:   8%|▊         | 166/2000 [00:02<00:25, 72.77it/s, test=0.0%, test_loss=4.369, train=0.0%, train_loss=4.182]

outcome_architecture/process:   9%|▉         | 177/2000 [00:03<00:22, 79.76it/s, test=0.0%, test_loss=4.369, train=0.0%, train_loss=4.182]

outcome_architecture/process:   9%|▉         | 187/2000 [00:03<00:21, 83.90it/s, test=0.0%, test_loss=4.369, train=0.0%, train_loss=4.182]

outcome_architecture/process:  10%|▉         | 198/2000 [00:03<00:20, 89.36it/s, test=0.0%, test_loss=4.369, train=0.0%, train_loss=4.182]

outcome_architecture/process:  10%|▉         | 198/2000 [00:03<00:20, 89.36it/s, test=9.3%, test_loss=2.481, train=10.3%, train_loss=2.528]

outcome_architecture/process:  10%|█         | 208/2000 [00:03<00:26, 66.98it/s, test=9.3%, test_loss=2.481, train=10.3%, train_loss=2.528]

outcome_architecture/process:  11%|█         | 219/2000 [00:03<00:23, 75.14it/s, test=9.3%, test_loss=2.481, train=10.3%, train_loss=2.528]

outcome_architecture/process:  11%|█▏        | 229/2000 [00:03<00:22, 80.28it/s, test=9.3%, test_loss=2.481, train=10.3%, train_loss=2.528]

outcome_architecture/process:  12%|█▏        | 240/2000 [00:03<00:20, 86.75it/s, test=9.3%, test_loss=2.481, train=10.3%, train_loss=2.528]

outcome_architecture/process:  12%|█▏        | 240/2000 [00:04<00:20, 86.75it/s, test=9.7%, test_loss=2.292, train=8.7%, train_loss=2.366]

outcome_architecture/process:  12%|█▎        | 250/2000 [00:04<00:26, 65.52it/s, test=9.7%, test_loss=2.292, train=8.7%, train_loss=2.366]

outcome_architecture/process:  13%|█▎        | 260/2000 [00:04<00:23, 72.68it/s, test=9.7%, test_loss=2.292, train=8.7%, train_loss=2.366]

outcome_architecture/process:  14%|█▎        | 271/2000 [00:04<00:21, 80.48it/s, test=9.7%, test_loss=2.292, train=8.7%, train_loss=2.366]

outcome_architecture/process:  14%|█▍        | 282/2000 [00:04<00:19, 86.64it/s, test=9.7%, test_loss=2.292, train=8.7%, train_loss=2.366]

outcome_architecture/process:  15%|█▍        | 293/2000 [00:04<00:18, 91.64it/s, test=9.7%, test_loss=2.292, train=8.7%, train_loss=2.366]

outcome_architecture/process:  15%|█▍        | 293/2000 [00:04<00:18, 91.64it/s, test=14.0%, test_loss=2.112, train=8.7%, train_loss=2.095]

outcome_architecture/process:  15%|█▌        | 303/2000 [00:04<00:24, 67.88it/s, test=14.0%, test_loss=2.112, train=8.7%, train_loss=2.095]

outcome_architecture/process:  16%|█▌        | 314/2000 [00:04<00:22, 76.28it/s, test=14.0%, test_loss=2.112, train=8.7%, train_loss=2.095]

outcome_architecture/process:  16%|█▋        | 325/2000 [00:04<00:20, 83.38it/s, test=14.0%, test_loss=2.112, train=8.7%, train_loss=2.095]

outcome_architecture/process:  17%|█▋        | 336/2000 [00:05<00:18, 88.98it/s, test=14.0%, test_loss=2.112, train=8.7%, train_loss=2.095]

outcome_architecture/process:  17%|█▋        | 347/2000 [00:05<00:17, 92.61it/s, test=14.0%, test_loss=2.112, train=8.7%, train_loss=2.095]

outcome_architecture/process:  17%|█▋        | 347/2000 [00:05<00:17, 92.61it/s, test=13.9%, test_loss=1.729, train=10.0%, train_loss=1.730]

outcome_architecture/process:  18%|█▊        | 357/2000 [00:05<00:24, 68.30it/s, test=13.9%, test_loss=1.729, train=10.0%, train_loss=1.730]

outcome_architecture/process:  18%|█▊        | 368/2000 [00:05<00:21, 76.35it/s, test=13.9%, test_loss=1.729, train=10.0%, train_loss=1.730]

outcome_architecture/process:  19%|█▉        | 379/2000 [00:05<00:19, 83.21it/s, test=13.9%, test_loss=1.729, train=10.0%, train_loss=1.730]

outcome_architecture/process:  20%|█▉        | 390/2000 [00:05<00:18, 88.58it/s, test=13.9%, test_loss=1.729, train=10.0%, train_loss=1.730]

outcome_architecture/process:  20%|█▉        | 390/2000 [00:05<00:18, 88.58it/s, test=13.6%, test_loss=1.516, train=8.0%, train_loss=1.517]

outcome_architecture/process:  20%|██        | 400/2000 [00:05<00:24, 66.46it/s, test=13.6%, test_loss=1.516, train=8.0%, train_loss=1.517]

outcome_architecture/process:  21%|██        | 411/2000 [00:06<00:21, 74.75it/s, test=13.6%, test_loss=1.516, train=8.0%, train_loss=1.517]

outcome_architecture/process:  21%|██        | 422/2000 [00:06<00:19, 81.75it/s, test=13.6%, test_loss=1.516, train=8.0%, train_loss=1.517]

outcome_architecture/process:  22%|██▏       | 433/2000 [00:06<00:17, 87.30it/s, test=13.6%, test_loss=1.516, train=8.0%, train_loss=1.517]

outcome_architecture/process:  22%|██▏       | 444/2000 [00:06<00:16, 91.68it/s, test=13.6%, test_loss=1.516, train=8.0%, train_loss=1.517]

outcome_architecture/process:  22%|██▏       | 444/2000 [00:06<00:16, 91.68it/s, test=12.7%, test_loss=1.293, train=9.7%, train_loss=1.274]

outcome_architecture/process:  23%|██▎       | 454/2000 [00:06<00:22, 67.71it/s, test=12.7%, test_loss=1.293, train=9.7%, train_loss=1.274]

outcome_architecture/process:  23%|██▎       | 465/2000 [00:06<00:20, 75.75it/s, test=12.7%, test_loss=1.293, train=9.7%, train_loss=1.274]

outcome_architecture/process:  24%|██▍       | 476/2000 [00:06<00:18, 82.58it/s, test=12.7%, test_loss=1.293, train=9.7%, train_loss=1.274]

outcome_architecture/process:  24%|██▍       | 487/2000 [00:06<00:17, 88.08it/s, test=12.7%, test_loss=1.293, train=9.7%, train_loss=1.274]

outcome_architecture/process:  25%|██▍       | 498/2000 [00:07<00:16, 92.43it/s, test=12.7%, test_loss=1.293, train=9.7%, train_loss=1.274]

outcome_architecture/process:  25%|██▍       | 498/2000 [00:07<00:16, 92.43it/s, test=13.3%, test_loss=0.872, train=7.7%, train_loss=0.841]

outcome_architecture/process:  25%|██▌       | 508/2000 [00:07<00:21, 67.91it/s, test=13.3%, test_loss=0.872, train=7.7%, train_loss=0.841]

outcome_architecture/process:  26%|██▌       | 519/2000 [00:07<00:19, 76.08it/s, test=13.3%, test_loss=0.872, train=7.7%, train_loss=0.841]

outcome_architecture/process:  26%|██▋       | 530/2000 [00:07<00:17, 82.82it/s, test=13.3%, test_loss=0.872, train=7.7%, train_loss=0.841]

outcome_architecture/process:  27%|██▋       | 541/2000 [00:07<00:16, 88.29it/s, test=13.3%, test_loss=0.872, train=7.7%, train_loss=0.841]

outcome_architecture/process:  27%|██▋       | 541/2000 [00:07<00:16, 88.29it/s, test=13.0%, test_loss=0.762, train=8.7%, train_loss=0.710]

outcome_architecture/process:  28%|██▊       | 551/2000 [00:07<00:22, 65.81it/s, test=13.0%, test_loss=0.762, train=8.7%, train_loss=0.710]

outcome_architecture/process:  28%|██▊       | 562/2000 [00:07<00:19, 74.44it/s, test=13.0%, test_loss=0.762, train=8.7%, train_loss=0.710]

outcome_architecture/process:  29%|██▊       | 573/2000 [00:08<00:17, 81.61it/s, test=13.0%, test_loss=0.762, train=8.7%, train_loss=0.710]

outcome_architecture/process:  29%|██▉       | 583/2000 [00:08<00:16, 85.11it/s, test=13.0%, test_loss=0.762, train=8.7%, train_loss=0.710]

outcome_architecture/process:  30%|██▉       | 593/2000 [00:08<00:15, 88.00it/s, test=13.0%, test_loss=0.762, train=8.7%, train_loss=0.710]

outcome_architecture/process:  30%|██▉       | 593/2000 [00:08<00:15, 88.00it/s, test=13.9%, test_loss=0.703, train=12.7%, train_loss=0.641]

outcome_architecture/process:  30%|███       | 603/2000 [00:08<00:21, 64.71it/s, test=13.9%, test_loss=0.703, train=12.7%, train_loss=0.641]

outcome_architecture/process:  31%|███       | 613/2000 [00:08<00:19, 70.80it/s, test=13.9%, test_loss=0.703, train=12.7%, train_loss=0.641]

outcome_architecture/process:  31%|███       | 624/2000 [00:08<00:17, 78.49it/s, test=13.9%, test_loss=0.703, train=12.7%, train_loss=0.641]

outcome_architecture/process:  32%|███▏      | 635/2000 [00:08<00:16, 84.76it/s, test=13.9%, test_loss=0.703, train=12.7%, train_loss=0.641]

outcome_architecture/process:  32%|███▏      | 645/2000 [00:08<00:15, 87.94it/s, test=13.9%, test_loss=0.703, train=12.7%, train_loss=0.641]

outcome_architecture/process:  32%|███▏      | 645/2000 [00:09<00:15, 87.94it/s, test=15.2%, test_loss=0.569, train=12.3%, train_loss=0.530]

outcome_architecture/process:  33%|███▎      | 655/2000 [00:09<00:20, 64.62it/s, test=15.2%, test_loss=0.569, train=12.3%, train_loss=0.530]

outcome_architecture/process:  33%|███▎      | 665/2000 [00:09<00:18, 71.38it/s, test=15.2%, test_loss=0.569, train=12.3%, train_loss=0.530]

outcome_architecture/process:  34%|███▍      | 675/2000 [00:09<00:17, 77.23it/s, test=15.2%, test_loss=0.569, train=12.3%, train_loss=0.530]

outcome_architecture/process:  34%|███▍      | 685/2000 [00:09<00:15, 82.38it/s, test=15.2%, test_loss=0.569, train=12.3%, train_loss=0.530]

outcome_architecture/process:  35%|███▍      | 695/2000 [00:09<00:15, 85.94it/s, test=15.2%, test_loss=0.569, train=12.3%, train_loss=0.530]

outcome_architecture/process:  35%|███▍      | 695/2000 [00:09<00:15, 85.94it/s, test=14.2%, test_loss=0.724, train=12.3%, train_loss=0.675]

outcome_architecture/process:  35%|███▌      | 705/2000 [00:09<00:20, 63.73it/s, test=14.2%, test_loss=0.724, train=12.3%, train_loss=0.675]

outcome_architecture/process:  36%|███▌      | 715/2000 [00:09<00:18, 70.87it/s, test=14.2%, test_loss=0.724, train=12.3%, train_loss=0.675]

outcome_architecture/process:  36%|███▋      | 725/2000 [00:10<00:16, 76.65it/s, test=14.2%, test_loss=0.724, train=12.3%, train_loss=0.675]

outcome_architecture/process:  37%|███▋      | 735/2000 [00:10<00:15, 82.25it/s, test=14.2%, test_loss=0.724, train=12.3%, train_loss=0.675]

outcome_architecture/process:  37%|███▋      | 746/2000 [00:10<00:14, 88.20it/s, test=14.2%, test_loss=0.724, train=12.3%, train_loss=0.675]

outcome_architecture/process:  37%|███▋      | 746/2000 [00:10<00:14, 88.20it/s, test=21.8%, test_loss=0.415, train=21.3%, train_loss=0.392]

outcome_architecture/process:  38%|███▊      | 756/2000 [00:10<00:18, 65.84it/s, test=21.8%, test_loss=0.415, train=21.3%, train_loss=0.392]

outcome_architecture/process:  38%|███▊      | 767/2000 [00:10<00:16, 74.47it/s, test=21.8%, test_loss=0.415, train=21.3%, train_loss=0.392]

outcome_architecture/process:  39%|███▉      | 778/2000 [00:10<00:14, 81.58it/s, test=21.8%, test_loss=0.415, train=21.3%, train_loss=0.392]

outcome_architecture/process:  39%|███▉      | 789/2000 [00:10<00:13, 87.45it/s, test=21.8%, test_loss=0.415, train=21.3%, train_loss=0.392]

outcome_architecture/process:  39%|███▉      | 789/2000 [00:11<00:13, 87.45it/s, test=36.4%, test_loss=0.216, train=35.7%, train_loss=0.246]

outcome_architecture/process:  40%|████      | 800/2000 [00:11<00:18, 66.62it/s, test=36.4%, test_loss=0.216, train=35.7%, train_loss=0.246]

outcome_architecture/process:  41%|████      | 811/2000 [00:11<00:15, 74.78it/s, test=36.4%, test_loss=0.216, train=35.7%, train_loss=0.246]

outcome_architecture/process:  41%|████      | 822/2000 [00:11<00:14, 81.68it/s, test=36.4%, test_loss=0.216, train=35.7%, train_loss=0.246]

outcome_architecture/process:  42%|████▏     | 833/2000 [00:11<00:13, 87.20it/s, test=36.4%, test_loss=0.216, train=35.7%, train_loss=0.246]

outcome_architecture/process:  42%|████▏     | 844/2000 [00:11<00:12, 91.68it/s, test=36.4%, test_loss=0.216, train=35.7%, train_loss=0.246]

outcome_architecture/process:  42%|████▏     | 844/2000 [00:11<00:12, 91.68it/s, test=42.8%, test_loss=0.175, train=49.0%, train_loss=0.175]

outcome_architecture/process:  43%|████▎     | 854/2000 [00:11<00:16, 67.56it/s, test=42.8%, test_loss=0.175, train=49.0%, train_loss=0.175]

outcome_architecture/process:  43%|████▎     | 865/2000 [00:11<00:14, 75.70it/s, test=42.8%, test_loss=0.175, train=49.0%, train_loss=0.175]

outcome_architecture/process:  44%|████▍     | 876/2000 [00:11<00:13, 82.57it/s, test=42.8%, test_loss=0.175, train=49.0%, train_loss=0.175]

outcome_architecture/process:  44%|████▍     | 887/2000 [00:12<00:12, 88.02it/s, test=42.8%, test_loss=0.175, train=49.0%, train_loss=0.175]

outcome_architecture/process:  45%|████▍     | 897/2000 [00:12<00:12, 90.31it/s, test=42.8%, test_loss=0.175, train=49.0%, train_loss=0.175]

outcome_architecture/process:  45%|████▍     | 897/2000 [00:12<00:12, 90.31it/s, test=54.2%, test_loss=0.125, train=61.7%, train_loss=0.127]

outcome_architecture/process:  45%|████▌     | 907/2000 [00:12<00:16, 65.34it/s, test=54.2%, test_loss=0.125, train=61.7%, train_loss=0.127]

outcome_architecture/process:  46%|████▌     | 918/2000 [00:12<00:14, 73.36it/s, test=54.2%, test_loss=0.125, train=61.7%, train_loss=0.127]

outcome_architecture/process:  46%|████▋     | 929/2000 [00:12<00:13, 80.51it/s, test=54.2%, test_loss=0.125, train=61.7%, train_loss=0.127]

outcome_architecture/process:  47%|████▋     | 940/2000 [00:12<00:12, 86.36it/s, test=54.2%, test_loss=0.125, train=61.7%, train_loss=0.127]

outcome_architecture/process:  47%|████▋     | 940/2000 [00:13<00:12, 86.36it/s, test=58.6%, test_loss=0.117, train=58.0%, train_loss=0.139]

outcome_architecture/process:  48%|████▊     | 950/2000 [00:13<00:16, 65.54it/s, test=58.6%, test_loss=0.117, train=58.0%, train_loss=0.139]

outcome_architecture/process:  48%|████▊     | 961/2000 [00:13<00:14, 74.04it/s, test=58.6%, test_loss=0.117, train=58.0%, train_loss=0.139]

outcome_architecture/process:  49%|████▊     | 972/2000 [00:13<00:12, 81.18it/s, test=58.6%, test_loss=0.117, train=58.0%, train_loss=0.139]

outcome_architecture/process:  49%|████▉     | 983/2000 [00:13<00:11, 87.05it/s, test=58.6%, test_loss=0.117, train=58.0%, train_loss=0.139]

outcome_architecture/process:  50%|████▉     | 994/2000 [00:13<00:10, 91.50it/s, test=58.6%, test_loss=0.117, train=58.0%, train_loss=0.139]

outcome_architecture/process:  50%|████▉     | 994/2000 [00:13<00:10, 91.50it/s, test=74.7%, test_loss=0.059, train=78.7%, train_loss=0.072]

outcome_architecture/process:  50%|█████     | 1004/2000 [00:13<00:14, 67.84it/s, test=74.7%, test_loss=0.059, train=78.7%, train_loss=0.072]

outcome_architecture/process:  51%|█████     | 1015/2000 [00:13<00:12, 75.93it/s, test=74.7%, test_loss=0.059, train=78.7%, train_loss=0.072]

outcome_architecture/process:  51%|█████▏    | 1026/2000 [00:13<00:11, 82.82it/s, test=74.7%, test_loss=0.059, train=78.7%, train_loss=0.072]

outcome_architecture/process:  52%|█████▏    | 1037/2000 [00:14<00:10, 88.30it/s, test=74.7%, test_loss=0.059, train=78.7%, train_loss=0.072]

outcome_architecture/process:  52%|█████▏    | 1048/2000 [00:14<00:10, 92.41it/s, test=74.7%, test_loss=0.059, train=78.7%, train_loss=0.072]

outcome_architecture/process:  52%|█████▏    | 1048/2000 [00:14<00:10, 92.41it/s, test=79.3%, test_loss=0.050, train=78.0%, train_loss=0.072]

outcome_architecture/process:  53%|█████▎    | 1058/2000 [00:14<00:13, 68.28it/s, test=79.3%, test_loss=0.050, train=78.0%, train_loss=0.072]

outcome_architecture/process:  53%|█████▎    | 1069/2000 [00:14<00:12, 76.33it/s, test=79.3%, test_loss=0.050, train=78.0%, train_loss=0.072]

outcome_architecture/process:  54%|█████▍    | 1080/2000 [00:14<00:11, 82.77it/s, test=79.3%, test_loss=0.050, train=78.0%, train_loss=0.072]

outcome_architecture/process:  55%|█████▍    | 1091/2000 [00:14<00:10, 88.14it/s, test=79.3%, test_loss=0.050, train=78.0%, train_loss=0.072]

outcome_architecture/process:  55%|█████▍    | 1091/2000 [00:14<00:10, 88.14it/s, test=88.1%, test_loss=0.033, train=90.7%, train_loss=0.062]

outcome_architecture/process:  55%|█████▌    | 1101/2000 [00:14<00:13, 66.43it/s, test=88.1%, test_loss=0.033, train=90.7%, train_loss=0.062]

outcome_architecture/process:  56%|█████▌    | 1112/2000 [00:15<00:11, 74.87it/s, test=88.1%, test_loss=0.033, train=90.7%, train_loss=0.062]

outcome_architecture/process:  56%|█████▌    | 1123/2000 [00:15<00:10, 81.83it/s, test=88.1%, test_loss=0.033, train=90.7%, train_loss=0.062]

outcome_architecture/process:  57%|█████▋    | 1134/2000 [00:15<00:09, 87.42it/s, test=88.1%, test_loss=0.033, train=90.7%, train_loss=0.062]

outcome_architecture/process:  57%|█████▋    | 1145/2000 [00:15<00:09, 91.80it/s, test=88.1%, test_loss=0.033, train=90.7%, train_loss=0.062]

outcome_architecture/process:  57%|█████▋    | 1145/2000 [00:15<00:09, 91.80it/s, test=92.2%, test_loss=0.021, train=94.3%, train_loss=0.018]

outcome_architecture/process:  58%|█████▊    | 1155/2000 [00:15<00:12, 68.00it/s, test=92.2%, test_loss=0.021, train=94.3%, train_loss=0.018]

outcome_architecture/process:  58%|█████▊    | 1166/2000 [00:15<00:10, 76.07it/s, test=92.2%, test_loss=0.021, train=94.3%, train_loss=0.018]

outcome_architecture/process:  59%|█████▉    | 1177/2000 [00:15<00:09, 82.73it/s, test=92.2%, test_loss=0.021, train=94.3%, train_loss=0.018]

outcome_architecture/process:  59%|█████▉    | 1188/2000 [00:15<00:09, 88.09it/s, test=92.2%, test_loss=0.021, train=94.3%, train_loss=0.018]

outcome_architecture/process:  60%|█████▉    | 1199/2000 [00:16<00:08, 92.03it/s, test=92.2%, test_loss=0.021, train=94.3%, train_loss=0.018]

outcome_architecture/process:  60%|█████▉    | 1199/2000 [00:16<00:08, 92.03it/s, test=70.8%, test_loss=0.098, train=76.7%, train_loss=0.092]

outcome_architecture/process:  60%|██████    | 1209/2000 [00:16<00:11, 68.12it/s, test=70.8%, test_loss=0.098, train=76.7%, train_loss=0.092]

outcome_architecture/process:  61%|██████    | 1220/2000 [00:16<00:10, 76.18it/s, test=70.8%, test_loss=0.098, train=76.7%, train_loss=0.092]

outcome_architecture/process:  62%|██████▏   | 1231/2000 [00:16<00:09, 82.86it/s, test=70.8%, test_loss=0.098, train=76.7%, train_loss=0.092]

outcome_architecture/process:  62%|██████▏   | 1242/2000 [00:16<00:08, 87.85it/s, test=70.8%, test_loss=0.098, train=76.7%, train_loss=0.092]

outcome_architecture/process:  62%|██████▏   | 1242/2000 [00:16<00:08, 87.85it/s, test=79.1%, test_loss=0.050, train=76.7%, train_loss=0.076]

outcome_architecture/process:  63%|██████▎   | 1252/2000 [00:16<00:11, 66.22it/s, test=79.1%, test_loss=0.050, train=76.7%, train_loss=0.076]

outcome_architecture/process:  63%|██████▎   | 1263/2000 [00:16<00:09, 74.33it/s, test=79.1%, test_loss=0.050, train=76.7%, train_loss=0.076]

outcome_architecture/process:  64%|██████▎   | 1274/2000 [00:17<00:08, 81.18it/s, test=79.1%, test_loss=0.050, train=76.7%, train_loss=0.076]

outcome_architecture/process:  64%|██████▍   | 1285/2000 [00:17<00:08, 86.94it/s, test=79.1%, test_loss=0.050, train=76.7%, train_loss=0.076]

outcome_architecture/process:  65%|██████▍   | 1296/2000 [00:17<00:07, 91.30it/s, test=79.1%, test_loss=0.050, train=76.7%, train_loss=0.076]

outcome_architecture/process:  65%|██████▍   | 1296/2000 [00:17<00:07, 91.30it/s, test=63.7%, test_loss=0.123, train=65.7%, train_loss=0.154]

outcome_architecture/process:  65%|██████▌   | 1306/2000 [00:17<00:10, 67.77it/s, test=63.7%, test_loss=0.123, train=65.7%, train_loss=0.154]

outcome_architecture/process:  66%|██████▌   | 1317/2000 [00:17<00:09, 75.81it/s, test=63.7%, test_loss=0.123, train=65.7%, train_loss=0.154]

outcome_architecture/process:  66%|██████▋   | 1328/2000 [00:17<00:08, 82.71it/s, test=63.7%, test_loss=0.123, train=65.7%, train_loss=0.154]

outcome_architecture/process:  67%|██████▋   | 1339/2000 [00:17<00:07, 88.29it/s, test=63.7%, test_loss=0.123, train=65.7%, train_loss=0.154]

outcome_architecture/process:  67%|██████▋   | 1339/2000 [00:18<00:07, 88.29it/s, test=0.0%, test_loss=9023.094, train=0.0%, train_loss=9309.562]

outcome_architecture/process:  68%|██████▊   | 1350/2000 [00:18<00:09, 67.32it/s, test=0.0%, test_loss=9023.094, train=0.0%, train_loss=9309.562]

outcome_architecture/process:  68%|██████▊   | 1361/2000 [00:18<00:08, 75.41it/s, test=0.0%, test_loss=9023.094, train=0.0%, train_loss=9309.562]

outcome_architecture/process:  69%|██████▊   | 1372/2000 [00:18<00:07, 82.30it/s, test=0.0%, test_loss=9023.094, train=0.0%, train_loss=9309.562]

outcome_architecture/process:  69%|██████▉   | 1383/2000 [00:18<00:07, 87.91it/s, test=0.0%, test_loss=9023.094, train=0.0%, train_loss=9309.562]

outcome_architecture/process:  70%|██████▉   | 1394/2000 [00:18<00:06, 92.40it/s, test=0.0%, test_loss=9023.094, train=0.0%, train_loss=9309.562]

outcome_architecture/process:  70%|██████▉   | 1394/2000 [00:18<00:06, 92.40it/s, test=0.0%, test_loss=34605.109, train=0.0%, train_loss=32788.914]

outcome_architecture/process:  70%|███████   | 1404/2000 [00:18<00:08, 68.32it/s, test=0.0%, test_loss=34605.109, train=0.0%, train_loss=32788.914]

outcome_architecture/process:  71%|███████   | 1415/2000 [00:18<00:07, 76.37it/s, test=0.0%, test_loss=34605.109, train=0.0%, train_loss=32788.914]

outcome_architecture/process:  71%|███████▏  | 1426/2000 [00:18<00:06, 83.07it/s, test=0.0%, test_loss=34605.109, train=0.0%, train_loss=32788.914]

outcome_architecture/process:  72%|███████▏  | 1437/2000 [00:19<00:06, 88.56it/s, test=0.0%, test_loss=34605.109, train=0.0%, train_loss=32788.914]

outcome_architecture/process:  72%|███████▏  | 1448/2000 [00:19<00:05, 92.74it/s, test=0.0%, test_loss=34605.109, train=0.0%, train_loss=32788.914]

outcome_architecture/process:  72%|███████▏  | 1448/2000 [00:19<00:05, 92.74it/s, test=0.0%, test_loss=1217614.500, train=0.0%, train_loss=987479.625]

outcome_architecture/process:  73%|███████▎  | 1458/2000 [00:19<00:07, 68.44it/s, test=0.0%, test_loss=1217614.500, train=0.0%, train_loss=987479.625]

outcome_architecture/process:  73%|███████▎  | 1469/2000 [00:19<00:06, 76.46it/s, test=0.0%, test_loss=1217614.500, train=0.0%, train_loss=987479.625]

outcome_architecture/process:  74%|███████▍  | 1480/2000 [00:19<00:06, 82.98it/s, test=0.0%, test_loss=1217614.500, train=0.0%, train_loss=987479.625]

outcome_architecture/process:  75%|███████▍  | 1491/2000 [00:19<00:05, 88.38it/s, test=0.0%, test_loss=1217614.500, train=0.0%, train_loss=987479.625]

outcome_architecture/process:  75%|███████▍  | 1491/2000 [00:19<00:05, 88.38it/s, test=0.0%, test_loss=146144576.000, train=0.0%, train_loss=169674192.000]

outcome_architecture/process:  75%|███████▌  | 1501/2000 [00:19<00:07, 66.71it/s, test=0.0%, test_loss=146144576.000, train=0.0%, train_loss=169674192.000]

outcome_architecture/process:  76%|███████▌  | 1512/2000 [00:20<00:06, 74.98it/s, test=0.0%, test_loss=146144576.000, train=0.0%, train_loss=169674192.000]

outcome_architecture/process:  76%|███████▌  | 1523/2000 [00:20<00:05, 81.92it/s, test=0.0%, test_loss=146144576.000, train=0.0%, train_loss=169674192.000]

outcome_architecture/process:  77%|███████▋  | 1534/2000 [00:20<00:05, 87.53it/s, test=0.0%, test_loss=146144576.000, train=0.0%, train_loss=169674192.000]

outcome_architecture/process:  77%|███████▋  | 1545/2000 [00:20<00:04, 91.96it/s, test=0.0%, test_loss=146144576.000, train=0.0%, train_loss=169674192.000]

outcome_architecture/process:  77%|███████▋  | 1545/2000 [00:20<00:04, 91.96it/s, test=0.0%, test_loss=37224752.000, train=0.0%, train_loss=53534052.000]

outcome_architecture/process:  78%|███████▊  | 1555/2000 [00:20<00:06, 67.89it/s, test=0.0%, test_loss=37224752.000, train=0.0%, train_loss=53534052.000]

outcome_architecture/process:  78%|███████▊  | 1566/2000 [00:20<00:05, 76.03it/s, test=0.0%, test_loss=37224752.000, train=0.0%, train_loss=53534052.000]

outcome_architecture/process:  79%|███████▉  | 1577/2000 [00:20<00:05, 82.89it/s, test=0.0%, test_loss=37224752.000, train=0.0%, train_loss=53534052.000]

outcome_architecture/process:  79%|███████▉  | 1588/2000 [00:20<00:04, 87.99it/s, test=0.0%, test_loss=37224752.000, train=0.0%, train_loss=53534052.000]

outcome_architecture/process:  80%|███████▉  | 1599/2000 [00:21<00:04, 92.12it/s, test=0.0%, test_loss=37224752.000, train=0.0%, train_loss=53534052.000]

outcome_architecture/process:  80%|███████▉  | 1599/2000 [00:21<00:04, 92.12it/s, test=0.0%, test_loss=47733252096.000, train=0.0%, train_loss=48246165504.000]

outcome_architecture/process:  80%|████████  | 1609/2000 [00:21<00:05, 68.08it/s, test=0.0%, test_loss=47733252096.000, train=0.0%, train_loss=48246165504.000]

outcome_architecture/process:  81%|████████  | 1620/2000 [00:21<00:04, 76.21it/s, test=0.0%, test_loss=47733252096.000, train=0.0%, train_loss=48246165504.000]

outcome_architecture/process:  82%|████████▏ | 1631/2000 [00:21<00:04, 82.90it/s, test=0.0%, test_loss=47733252096.000, train=0.0%, train_loss=48246165504.000]

outcome_architecture/process:  82%|████████▏ | 1642/2000 [00:21<00:04, 88.21it/s, test=0.0%, test_loss=47733252096.000, train=0.0%, train_loss=48246165504.000]

outcome_architecture/process:  82%|████████▏ | 1642/2000 [00:21<00:04, 88.21it/s, test=0.0%, test_loss=285688856576.000, train=0.0%, train_loss=156016902144.000]

outcome_architecture/process:  83%|████████▎ | 1652/2000 [00:21<00:05, 66.42it/s, test=0.0%, test_loss=285688856576.000, train=0.0%, train_loss=156016902144.000]

outcome_architecture/process:  83%|████████▎ | 1663/2000 [00:21<00:04, 74.63it/s, test=0.0%, test_loss=285688856576.000, train=0.0%, train_loss=156016902144.000]

outcome_architecture/process:  84%|████████▎ | 1674/2000 [00:22<00:03, 81.54it/s, test=0.0%, test_loss=285688856576.000, train=0.0%, train_loss=156016902144.000]

outcome_architecture/process:  84%|████████▍ | 1685/2000 [00:22<00:03, 87.07it/s, test=0.0%, test_loss=285688856576.000, train=0.0%, train_loss=156016902144.000]

outcome_architecture/process:  85%|████████▍ | 1696/2000 [00:22<00:03, 91.58it/s, test=0.0%, test_loss=285688856576.000, train=0.0%, train_loss=156016902144.000]

outcome_architecture/process:  85%|████████▍ | 1696/2000 [00:22<00:03, 91.58it/s, test=0.0%, test_loss=96119660544.000, train=0.0%, train_loss=256825245696.000]

outcome_architecture/process:  85%|████████▌ | 1706/2000 [00:22<00:04, 67.96it/s, test=0.0%, test_loss=96119660544.000, train=0.0%, train_loss=256825245696.000]

outcome_architecture/process:  86%|████████▌ | 1717/2000 [00:22<00:03, 75.74it/s, test=0.0%, test_loss=96119660544.000, train=0.0%, train_loss=256825245696.000]

outcome_architecture/process:  86%|████████▋ | 1728/2000 [00:22<00:03, 82.52it/s, test=0.0%, test_loss=96119660544.000, train=0.0%, train_loss=256825245696.000]

outcome_architecture/process:  87%|████████▋ | 1739/2000 [00:22<00:02, 87.97it/s, test=0.0%, test_loss=96119660544.000, train=0.0%, train_loss=256825245696.000]

outcome_architecture/process:  87%|████████▋ | 1739/2000 [00:23<00:02, 87.97it/s, test=0.0%, test_loss=88773066752.000, train=0.0%, train_loss=67195441152.000]

outcome_architecture/process:  88%|████████▊ | 1750/2000 [00:23<00:03, 67.06it/s, test=0.0%, test_loss=88773066752.000, train=0.0%, train_loss=67195441152.000]

outcome_architecture/process:  88%|████████▊ | 1760/2000 [00:23<00:03, 73.53it/s, test=0.0%, test_loss=88773066752.000, train=0.0%, train_loss=67195441152.000]

outcome_architecture/process:  89%|████████▊ | 1771/2000 [00:23<00:02, 80.86it/s, test=0.0%, test_loss=88773066752.000, train=0.0%, train_loss=67195441152.000]

outcome_architecture/process:  89%|████████▉ | 1782/2000 [00:23<00:02, 86.68it/s, test=0.0%, test_loss=88773066752.000, train=0.0%, train_loss=67195441152.000]

outcome_architecture/process:  90%|████████▉ | 1793/2000 [00:23<00:02, 91.20it/s, test=0.0%, test_loss=88773066752.000, train=0.0%, train_loss=67195441152.000]

outcome_architecture/process:  90%|████████▉ | 1793/2000 [00:23<00:02, 91.20it/s, test=0.0%, test_loss=216477319168.000, train=0.0%, train_loss=148569833472.000]

outcome_architecture/process:  90%|█████████ | 1803/2000 [00:23<00:02, 67.26it/s, test=0.0%, test_loss=216477319168.000, train=0.0%, train_loss=148569833472.000]

outcome_architecture/process:  91%|█████████ | 1814/2000 [00:23<00:02, 75.51it/s, test=0.0%, test_loss=216477319168.000, train=0.0%, train_loss=148569833472.000]

outcome_architecture/process:  91%|█████████▏| 1825/2000 [00:23<00:02, 82.41it/s, test=0.0%, test_loss=216477319168.000, train=0.0%, train_loss=148569833472.000]

outcome_architecture/process:  92%|█████████▏| 1836/2000 [00:24<00:01, 87.88it/s, test=0.0%, test_loss=216477319168.000, train=0.0%, train_loss=148569833472.000]

outcome_architecture/process:  92%|█████████▏| 1846/2000 [00:24<00:01, 89.83it/s, test=0.0%, test_loss=216477319168.000, train=0.0%, train_loss=148569833472.000]

outcome_architecture/process:  92%|█████████▏| 1846/2000 [00:24<00:01, 89.83it/s, test=0.0%, test_loss=86790758400.000, train=0.0%, train_loss=54560579584.000]

outcome_architecture/process:  93%|█████████▎| 1856/2000 [00:24<00:02, 66.36it/s, test=0.0%, test_loss=86790758400.000, train=0.0%, train_loss=54560579584.000]

outcome_architecture/process:  93%|█████████▎| 1866/2000 [00:24<00:01, 73.35it/s, test=0.0%, test_loss=86790758400.000, train=0.0%, train_loss=54560579584.000]

outcome_architecture/process:  94%|█████████▍| 1876/2000 [00:24<00:01, 79.19it/s, test=0.0%, test_loss=86790758400.000, train=0.0%, train_loss=54560579584.000]

outcome_architecture/process:  94%|█████████▍| 1886/2000 [00:24<00:01, 83.94it/s, test=0.0%, test_loss=86790758400.000, train=0.0%, train_loss=54560579584.000]

outcome_architecture/process:  95%|█████████▍| 1896/2000 [00:24<00:01, 87.84it/s, test=0.0%, test_loss=86790758400.000, train=0.0%, train_loss=54560579584.000]

outcome_architecture/process:  95%|█████████▍| 1896/2000 [00:25<00:01, 87.84it/s, test=0.0%, test_loss=50693816320.000, train=0.0%, train_loss=30832359424.000]

outcome_architecture/process:  95%|█████████▌| 1906/2000 [00:25<00:01, 64.81it/s, test=0.0%, test_loss=50693816320.000, train=0.0%, train_loss=30832359424.000]

outcome_architecture/process:  96%|█████████▌| 1916/2000 [00:25<00:01, 71.41it/s, test=0.0%, test_loss=50693816320.000, train=0.0%, train_loss=30832359424.000]

outcome_architecture/process:  96%|█████████▋| 1927/2000 [00:25<00:00, 79.29it/s, test=0.0%, test_loss=50693816320.000, train=0.0%, train_loss=30832359424.000]

outcome_architecture/process:  97%|█████████▋| 1938/2000 [00:25<00:00, 85.91it/s, test=0.0%, test_loss=50693816320.000, train=0.0%, train_loss=30832359424.000]

outcome_architecture/process:  97%|█████████▋| 1949/2000 [00:25<00:00, 90.81it/s, test=0.0%, test_loss=50693816320.000, train=0.0%, train_loss=30832359424.000]

outcome_architecture/process:  97%|█████████▋| 1949/2000 [00:25<00:00, 90.81it/s, test=0.0%, test_loss=28902811648.000, train=0.0%, train_loss=19393355776.000]

outcome_architecture/process:  98%|█████████▊| 1959/2000 [00:25<00:00, 67.26it/s, test=0.0%, test_loss=28902811648.000, train=0.0%, train_loss=19393355776.000]

outcome_architecture/process:  98%|█████████▊| 1970/2000 [00:25<00:00, 75.63it/s, test=0.0%, test_loss=28902811648.000, train=0.0%, train_loss=19393355776.000]

outcome_architecture/process:  99%|█████████▉| 1981/2000 [00:25<00:00, 82.74it/s, test=0.0%, test_loss=28902811648.000, train=0.0%, train_loss=19393355776.000]

outcome_architecture/process: 100%|█████████▉| 1992/2000 [00:26<00:00, 88.34it/s, test=0.0%, test_loss=28902811648.000, train=0.0%, train_loss=19393355776.000]

outcome_architecture/process: 100%|█████████▉| 1992/2000 [00:26<00:00, 88.34it/s, test=0.0%, test_loss=132870021120.000, train=0.0%, train_loss=64687509504.000]

outcome_architecture/process: 100%|██████████| 2000/2000 [00:26<00:00, 76.05it/s, test=0.0%, test_loss=132870021120.000, train=0.0%, train_loss=64687509504.000]

architecture/mode: 100%|██████████| 4/4 [01:12<00:00, 20.50s/it]

architecture/mode: 100%|██████████| 4/4 [01:12<00:00, 18.10s/it]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,outcome,4.273900e+00,0.0,0.0,0.0,4.273296e+00
1,1,process_architecture,outcome,4.217267e+00,0.0,0.0,0.0,4.216685e+00
2,2,process_architecture,outcome,4.135499e+00,0.0,0.0,0.0,4.135159e+00
3,5,process_architecture,outcome,3.077316e+00,0.0,0.0,0.0,3.075355e+00
4,10,process_architecture,outcome,1.803697e+00,0.0,0.0,0.0,1.779382e+00
...,...,...,...,...,...,...,...,...
187,1800,outcome_architecture,process,1.485698e+11,0.0,0.0,0.0,2.164773e+11
188,1850,outcome_architecture,process,5.456058e+10,0.0,0.0,0.0,8.679076e+10
189,1900,outcome_architecture,process,3.083236e+10,0.0,0.0,0.0,5.069382e+10
190,1950,outcome_architecture,process,1.939336e+10,0.0,0.0,0.0,2.890281e+10
191,2000,outcome_architecture,process,6.468751e+10,0.0,0.0,0.0,1.328700e+11

In [13]:

import json as _json, numpy as _np, pandas as _pd
def _clean(df):
    df = df.drop(columns=["circuit_matrix"], errors="ignore").copy()
    return _json.loads(df.to_json(orient="records"))

_payload = {
    "model_seed": MODEL_SEED,
    "steps": STEPS,
    "final_results": _clean(final_results),
    "history": _clean(history),
}
try:
    _payload["history_2x2"] = _clean(history_2x2)
except NameError:
    _payload["history_2x2"] = None

with open(_OUT_JSON, "w") as _f:
    _json.dump(_payload, _f, indent=2)
print("WROTE", _OUT_JSON)

WROTE /home/hariguru/aayus/trace/results/reachability_seeds/seed_43.json