
# Hand-coded solution reachability: train exactly two models

This notebook answers one precise question:

> The PROCESS and OUTCOME hand-coded Transformers already achieve 100% accuracy.  
> If we keep **each exact hand-coded architecture**, randomize its weights, and train it with its natural supervision, does gradient descent recover a 100%-accurate solution?

We train exactly **two models**:

| Trainable model | Architecture | Training target |
|---|---|---|
| `process_random_base` | exact `HandcodedProcessTransformer` layout | PROCESS / trace continuation |
| `outcome_random_base` | exact `HandcodedOutcomeTransformer` layout | OUTCOME-only continuation |

The two fixed hand-coded models are **references only** and are never optimized.

So the experiment is

\[
\boxed{
\text{2 fixed 100\% references}
+
\text{2 randomly initialized trainable models}
}
\]

with only the latter two undergoing gradient updates.

This is a **reachability experiment**, not yet an architecture-matched causal comparison between PROCESS and OUTCOME.


## 1. Imports and configuration

This notebook uses `handcoded_utils.py`, which contains the exact circuit generator, tokenizer, hand-coded architectures, training loop, and free-running evaluator.

In [1]:

import copy
import importlib
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

import handcoded_utils
importlib.reload(handcoded_utils)

from handcoded_utils import (
    BATCH_SIZE,
    BATCH_SEED,
    DATA_SEED,
    DEPTH,
    LR,
    MODEL_SEED,
    TEST_SEED,
    TEST_SIZE,
    TRAIN_SIZE,
    HandcodedOutcomeTransformer,
    HandcodedProcessTransformer,
    encode_dataset,
    free_run_metrics,
    generate,
    language_model_loss,
    make_batch_schedule,
    make_checkpoints,
    make_circuit_prompts,
    make_circuits,
    make_generation_evaluation,
    make_random_trainable_copy,
    make_tokenizer,
    train_one_model,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Main experiment settings.
N_TRAIN = TRAIN_SIZE
N_TEST = TEST_SIZE
STEPS = 2_000
LOSS_EVAL_SIZE = 64
CHECKPOINTS = make_checkpoints(STEPS, animation_checkpoints=40)

print("device:", DEVICE)
print("depth:", DEPTH)
print("train examples:", N_TRAIN)
print("test examples:", N_TEST)
print("steps:", STEPS)
print("loss eval examples:", LOSS_EVAL_SIZE)

device: cuda
depth: 4
train examples: 20000
test examples: 1000
steps: 2000
loss eval examples: 64

/home/hariguru/aayus/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# injected by run_seeds.py -- vary model init only
MODEL_SEED = 42
_OUT_JSON = '/home/hariguru/aayus/trace/results/reachability_seeds/seed_42.json'
print('MODEL_SEED =', MODEL_SEED)

MODEL_SEED = 42


## 2. Build the same dataset for both models

A circuit is

$$
s_t=\Phi(s_{t-1},g_t),\qquad t=1,\ldots,D.
$$

Both models receive the same prompt

```text
S0 g1 g2 ... gD <SEP>
```

but their supervised continuations differ.

PROCESS:

```text
g1 S1 g2 S2 ... gD SD <COLON> SD <EOS>
```

OUTCOME:

```text
<COLON> SD <EOS>
```

The underlying circuits, train/test split, and minibatch schedule are shared.

In [3]:

tokenizer = make_tokenizer()

train_circuits = make_circuits(N_TRAIN, DATA_SEED, DEPTH)
test_circuits = make_circuits(N_TEST, TEST_SEED, DEPTH)
example = test_circuits[0]

training_data = {
    mode: encode_dataset(train_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

# Held-out teacher-forced loss uses the test split. The training helper samples
# a deterministic prefix of this batch at checkpoints for speed.
test_loss_data = {
    mode: encode_dataset(test_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

batch_schedule = make_batch_schedule(
    N_TRAIN, STEPS, BATCH_SIZE, BATCH_SEED
)

train_eval = make_generation_evaluation(
    train_circuits[:min(300, len(train_circuits))],
    tokenizer,
    DEVICE,
)

test_eval = make_generation_evaluation(
    test_circuits,
    tokenizer,
    DEVICE,
)

circuit_prompts = make_circuit_prompts(
    example.gates,
    tokenizer,
    DEVICE,
)

print("Prompt :", tokenizer.decode(tokenizer.prompt(example)))
print("PROCESS:", tokenizer.decode(tokenizer.continuation(example, "process")))
print("OUTCOME:", tokenizer.decode(tokenizer.continuation(example, "outcome")))

Prompt : S1011 s02 c31 c31 t302 <SEP>
PROCESS: s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>
OUTCOME: <COLON> S1001 <EOS>


## 3. Fixed hand-coded references

These two models encode perfect algorithms directly in their weights.

### PROCESS reference

`HandcodedProcessTransformer`

- one causal attention/MLP block,
- four fixed attention heads,
- one ReLU unit for each `(state, gate)` pair,
- autoregressive reuse of the same block to emit intermediate states.

### OUTCOME reference

`HandcodedOutcomeTransformer`

- one causal attention/MLP block per circuit step,
- two attention heads per block,
- intermediate states remain internal to the residual stream,
- only the final answer is emitted.

They are not trained below. They establish that a 100% solution exists in each architecture class.

In [4]:

process_reference = HandcodedProcessTransformer(
    tokenizer, DEPTH
).to(DEVICE)

outcome_reference = HandcodedOutcomeTransformer(
    tokenizer, DEPTH
).to(DEVICE)

reference_rows = []

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    reference_rows.append({
        "model": name,
        "mode": mode,
        "answer_accuracy": metrics["final_answer"],
        "exact_continuation": metrics["exact_continuation"],
    })

pd.DataFrame(reference_rows)

           model     mode  answer_accuracy  exact_continuation
0  Fixed PROCESS  process              1.0                 1.0
1  Fixed OUTCOME  outcome              1.0                 1.0


Expected result:

$$
\operatorname{Acc}(\theta^\star_{\rm P})
=
\operatorname{Acc}(\theta^\star_{\rm O})
=
100\%.
$$

That is the realizability baseline.


## 4. Turn each exact hand-coded architecture into a random trainable model

This is the crucial correction.

We do **not** call `build_random_learned_model()`. That would create an unrelated ordinary one-layer Transformer.

Instead, `make_random_trainable_copy()`:

1. deep-copies the exact hand-coded model,
2. converts its stored weight buffers into `nn.Parameter`s,
3. randomly initializes those tensors.

Therefore the computational graph and tensor layout are inherited directly from the corresponding constructive model.

In [5]:

process_random_base = make_random_trainable_copy(
    process_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

outcome_random_base = make_random_trainable_copy(
    outcome_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

def trainable_params(model):
    return sum(p.numel() for p in model.parameters())

def stored_scalars(model):
    return sum(t.numel() for t in model.state_dict().values())

summary = pd.DataFrame([
    {
        "model": "Fixed PROCESS reference",
        "trainable_parameters": trainable_params(process_reference),
        "stored_scalars": stored_scalars(process_reference),
        "max_length": process_reference.max_length,
    },
    {
        "model": "Random trainable PROCESS architecture",
        "trainable_parameters": trainable_params(process_random_base),
        "stored_scalars": stored_scalars(process_random_base),
        "max_length": process_random_base.max_length,
    },
    {
        "model": "Fixed OUTCOME reference",
        "trainable_parameters": trainable_params(outcome_reference),
        "stored_scalars": stored_scalars(outcome_reference),
        "max_length": outcome_reference.max_length,
    },
    {
        "model": "Random trainable OUTCOME architecture",
        "trainable_parameters": trainable_params(outcome_random_base),
        "stored_scalars": stored_scalars(outcome_random_base),
        "max_length": outcome_random_base.max_length,
    },
])

summary

,model,trainable_parameters,stored_scalars,max_length
0,Fixed PROCESS reference,0,441664,16
1,Random trainable PROCESS architecture,441664,441664,16
2,Fixed OUTCOME reference,0,3588000,8
3,Random trainable OUTCOME architecture,3588000,3588000,8


A fixed reference reports zero **trainable** parameters because its constructed weights are registered as buffers. That does not mean it has zero weights. `stored_scalars` is the more relevant size diagnostic for the fixed models.


## 5. Sanity check: the trainable parameterization really contains the oracle

A useful stronger check is to convert the fixed buffers into trainable parameters **without changing their values**.

If the resulting model produces exactly the same logits as the fixed model, then the hand-coded optimum literally lies inside the trainable parameterization.

In [6]:

def make_trainable_oracle_copy(model, device):
    trainable = copy.deepcopy(model).cpu()

    def convert(module):
        for name, buffer in list(module._buffers.items()):
            if buffer is None:
                continue
            value = buffer.detach().clone()
            del module._buffers[name]
            module.register_parameter(name, torch.nn.Parameter(value))
        for child in module.children():
            convert(child)

    convert(trainable)
    return trainable.to(device)


process_oracle_trainable = make_trainable_oracle_copy(
    process_reference, DEVICE
)
outcome_oracle_trainable = make_trainable_oracle_copy(
    outcome_reference, DEVICE
)

prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

with torch.no_grad():
    process_error = (
        process_reference(prompt) - process_oracle_trainable(prompt)
    ).abs().max().item()

    outcome_error = (
        outcome_reference(prompt) - outcome_oracle_trainable(prompt)
    ).abs().max().item()

print("PROCESS max logit difference:", process_error)
print("OUTCOME max logit difference:", outcome_error)

assert process_error == 0.0
assert outcome_error == 0.0

PROCESS max logit difference: 0.0
OUTCOME max logit difference: 0.0


This gives the precise existence statement:

\[
\exists\,\theta^\star_{\rm P}\in\Theta_{\rm P},
\qquad
\exists\,\theta^\star_{\rm O}\in\Theta_{\rm O},
\]

with both achieving perfect execution.

The training experiment now asks whether random initialization reaches either solution class.


## 6. Train exactly two models

There is no `run_experiment(base, modes=("outcome","process"))` here.

That function would train two copies of the **same base architecture**.

Instead we make two explicit calls:

\[
\boxed{
\text{PROCESS architecture}+\text{PROCESS supervision}
}
\]

and

\[
\boxed{
\text{OUTCOME architecture}+\text{OUTCOME supervision}.
}
\]

So exactly two optimization runs occur.

In [7]:

trained_process, process_history = train_one_model(
    process_random_base,
    "process",
    training_data["process"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="process_architecture",
    test_loss_data=test_loss_data["process"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

trained_outcome, outcome_history = train_one_model(
    outcome_random_base,
    "outcome",
    training_data["outcome"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="outcome_architecture",
    test_loss_data=test_loss_data["outcome"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

history = pd.concat(
    [process_history, outcome_history],
    ignore_index=True,
)

display(
    history.drop(columns=["circuit_matrix"], errors="ignore")
)

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=7.0%, test_loss=4.260, train=8.7%, train_loss=4.260]

process_architecture/process:   0%|          | 1/2000 [00:00<06:27,  5.15it/s, test=7.0%, test_loss=4.260, train=8.7%, train_loss=4.260]

process_architecture/process:   0%|          | 1/2000 [00:00<06:27,  5.15it/s, test=0.0%, test_loss=4.235, train=0.0%, train_loss=4.236]

process_architecture/process:   0%|          | 1/2000 [00:00<06:27,  5.15it/s, test=0.0%, test_loss=3.907, train=0.0%, train_loss=3.919]

process_architecture/process:   0%|          | 5/2000 [00:00<01:51, 17.85it/s, test=0.0%, test_loss=3.907, train=0.0%, train_loss=3.919]

process_architecture/process:   0%|          | 5/2000 [00:00<01:51, 17.85it/s, test=0.0%, test_loss=3.650, train=0.0%, train_loss=3.664]

process_architecture/process:   0%|          | 5/2000 [00:00<01:51, 17.85it/s, test=0.0%, test_loss=3.034, train=0.0%, train_loss=3.026]

process_architecture/process:   1%|          | 20/2000 [00:00<00:35, 56.45it/s, test=0.0%, test_loss=3.034, train=0.0%, train_loss=3.026]

process_architecture/process:   1%|          | 20/2000 [00:00<00:35, 56.45it/s, test=6.5%, test_loss=2.813, train=8.7%, train_loss=2.826]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:28, 68.93it/s, test=6.5%, test_loss=2.813, train=8.7%, train_loss=2.826]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:28, 68.93it/s, test=6.7%, test_loss=2.617, train=5.3%, train_loss=2.647]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:21, 92.84it/s, test=6.7%, test_loss=2.617, train=5.3%, train_loss=2.647]

process_architecture/process:   4%|▎         | 70/2000 [00:00<00:15, 121.01it/s, test=6.7%, test_loss=2.617, train=5.3%, train_loss=2.647]

process_architecture/process:   4%|▎         | 70/2000 [00:00<00:15, 121.01it/s, test=11.5%, test_loss=2.437, train=10.3%, train_loss=2.426]

process_architecture/process:   4%|▍         | 83/2000 [00:00<00:16, 117.49it/s, test=11.5%, test_loss=2.437, train=10.3%, train_loss=2.426]

process_architecture/process:   4%|▍         | 83/2000 [00:01<00:16, 117.49it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   5%|▌         | 100/2000 [00:01<00:15, 119.28it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   6%|▌         | 120/2000 [00:01<00:13, 139.40it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   7%|▋         | 140/2000 [00:01<00:12, 154.71it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   7%|▋         | 140/2000 [00:01<00:12, 154.71it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:   8%|▊         | 157/2000 [00:01<00:12, 143.32it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:   9%|▉         | 177/2000 [00:01<00:11, 157.77it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:  10%|▉         | 197/2000 [00:01<00:10, 167.54it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:  10%|▉         | 197/2000 [00:01<00:10, 167.54it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  11%|█         | 215/2000 [00:01<00:11, 151.85it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  12%|█▏        | 235/2000 [00:01<00:10, 163.80it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  12%|█▏        | 235/2000 [00:02<00:10, 163.80it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  13%|█▎        | 252/2000 [00:02<00:11, 149.04it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  14%|█▎        | 272/2000 [00:02<00:10, 161.92it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  15%|█▍        | 292/2000 [00:02<00:09, 170.80it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  15%|█▍        | 292/2000 [00:02<00:09, 170.80it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  16%|█▌        | 310/2000 [00:02<00:10, 153.97it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  16%|█▋        | 330/2000 [00:02<00:10, 165.45it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  16%|█▋        | 330/2000 [00:02<00:10, 165.45it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  18%|█▊        | 350/2000 [00:02<00:10, 152.26it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  18%|█▊        | 370/2000 [00:02<00:09, 163.03it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  20%|█▉        | 390/2000 [00:02<00:09, 171.76it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  20%|█▉        | 390/2000 [00:02<00:09, 171.76it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  20%|██        | 408/2000 [00:02<00:10, 155.39it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  21%|██▏       | 428/2000 [00:03<00:09, 166.80it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  22%|██▏       | 448/2000 [00:03<00:08, 175.19it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  22%|██▏       | 448/2000 [00:03<00:08, 175.19it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  23%|██▎       | 467/2000 [00:03<00:09, 156.49it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  24%|██▍       | 487/2000 [00:03<00:09, 166.59it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  24%|██▍       | 487/2000 [00:03<00:09, 166.59it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  25%|██▌       | 505/2000 [00:03<00:09, 152.39it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  26%|██▋       | 525/2000 [00:03<00:08, 164.08it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 545/2000 [00:03<00:08, 173.05it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 545/2000 [00:03<00:08, 173.05it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  28%|██▊       | 563/2000 [00:03<00:09, 155.48it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 583/2000 [00:04<00:08, 166.09it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 583/2000 [00:04<00:08, 166.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  30%|███       | 601/2000 [00:04<00:09, 151.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  31%|███       | 621/2000 [00:04<00:08, 163.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 641/2000 [00:04<00:07, 172.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 641/2000 [00:04<00:07, 172.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  33%|███▎      | 659/2000 [00:04<00:08, 155.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 679/2000 [00:04<00:07, 166.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▍      | 699/2000 [00:04<00:07, 175.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▍      | 699/2000 [00:04<00:07, 175.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 718/2000 [00:04<00:08, 157.82it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 738/2000 [00:04<00:07, 168.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 738/2000 [00:05<00:07, 168.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 756/2000 [00:05<00:08, 153.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 776/2000 [00:05<00:07, 163.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 796/2000 [00:05<00:06, 172.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 796/2000 [00:05<00:06, 172.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 814/2000 [00:05<00:07, 155.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 834/2000 [00:05<00:07, 166.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 834/2000 [00:05<00:07, 166.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  43%|████▎     | 852/2000 [00:05<00:07, 150.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▎     | 872/2000 [00:05<00:06, 162.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 892/2000 [00:05<00:06, 170.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 892/2000 [00:06<00:06, 170.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 910/2000 [00:06<00:07, 153.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 930/2000 [00:06<00:06, 164.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 930/2000 [00:06<00:06, 164.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 950/2000 [00:06<00:06, 150.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 969/2000 [00:06<00:06, 160.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 988/2000 [00:06<00:06, 167.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 988/2000 [00:06<00:06, 167.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1006/2000 [00:06<00:06, 149.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████▏    | 1025/2000 [00:06<00:06, 159.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1045/2000 [00:06<00:05, 168.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1045/2000 [00:06<00:05, 168.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1063/2000 [00:07<00:06, 152.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1083/2000 [00:07<00:05, 163.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1083/2000 [00:07<00:05, 163.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1100/2000 [00:07<00:05, 150.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1120/2000 [00:07<00:05, 162.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1140/2000 [00:07<00:05, 171.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1140/2000 [00:07<00:05, 171.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1158/2000 [00:07<00:05, 155.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1178/2000 [00:07<00:04, 166.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1198/2000 [00:07<00:04, 174.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1198/2000 [00:07<00:04, 174.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1216/2000 [00:07<00:05, 156.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1236/2000 [00:08<00:04, 166.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1236/2000 [00:08<00:04, 166.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1254/2000 [00:08<00:04, 151.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▎   | 1274/2000 [00:08<00:04, 162.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1294/2000 [00:08<00:04, 171.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1294/2000 [00:08<00:04, 171.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1312/2000 [00:08<00:04, 154.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1332/2000 [00:08<00:04, 165.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1332/2000 [00:08<00:04, 165.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1350/2000 [00:08<00:04, 151.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1370/2000 [00:08<00:03, 162.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|██████▉   | 1390/2000 [00:09<00:03, 170.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|██████▉   | 1390/2000 [00:09<00:03, 170.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1408/2000 [00:09<00:03, 154.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████▏  | 1428/2000 [00:09<00:03, 165.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1448/2000 [00:09<00:03, 173.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1448/2000 [00:09<00:03, 173.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1466/2000 [00:09<00:03, 156.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1486/2000 [00:09<00:03, 166.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1486/2000 [00:09<00:03, 166.26it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1504/2000 [00:09<00:03, 151.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1524/2000 [00:09<00:02, 162.56it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1544/2000 [00:09<00:02, 171.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1544/2000 [00:10<00:02, 171.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1562/2000 [00:10<00:02, 152.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1582/2000 [00:10<00:02, 163.81it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1582/2000 [00:10<00:02, 163.81it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1600/2000 [00:10<00:02, 148.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1620/2000 [00:10<00:02, 160.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1640/2000 [00:10<00:02, 170.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1640/2000 [00:10<00:02, 170.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1658/2000 [00:10<00:02, 150.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1678/2000 [00:10<00:01, 162.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1698/2000 [00:10<00:01, 171.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1698/2000 [00:10<00:01, 171.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1716/2000 [00:11<00:01, 153.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1736/2000 [00:11<00:01, 164.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1736/2000 [00:11<00:01, 164.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1754/2000 [00:11<00:01, 148.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▊ | 1774/2000 [00:11<00:01, 160.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1794/2000 [00:11<00:01, 169.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1794/2000 [00:11<00:01, 169.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1812/2000 [00:11<00:01, 153.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1832/2000 [00:11<00:01, 164.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1832/2000 [00:11<00:01, 164.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▎| 1850/2000 [00:11<00:00, 151.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▎| 1870/2000 [00:12<00:00, 163.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1889/2000 [00:12<00:00, 169.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1889/2000 [00:12<00:00, 169.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▌| 1907/2000 [00:12<00:00, 149.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▋| 1926/2000 [00:12<00:00, 158.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1945/2000 [00:12<00:00, 165.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1945/2000 [00:12<00:00, 165.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1963/2000 [00:12<00:00, 146.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1982/2000 [00:12<00:00, 155.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1982/2000 [00:12<00:00, 155.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 141.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 154.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.611, train=0.0%, train_loss=3.611]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=11.186, train=0.0%, train_loss=11.134]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.635, train=0.0%, train_loss=3.636]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:59, 33.77it/s, test=0.0%, test_loss=3.635, train=0.0%, train_loss=3.636]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:59, 33.77it/s, test=0.0%, test_loss=1.127, train=0.0%, train_loss=1.127]

outcome_architecture/outcome:   1%|          | 11/2000 [00:00<00:43, 45.87it/s, test=0.0%, test_loss=1.127, train=0.0%, train_loss=1.127]

outcome_architecture/outcome:   1%|          | 11/2000 [00:00<00:43, 45.87it/s, test=6.2%, test_loss=0.960, train=4.7%, train_loss=0.961]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:35, 55.80it/s, test=6.2%, test_loss=0.960, train=4.7%, train_loss=0.961]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:35, 55.80it/s, test=7.0%, test_loss=0.932, train=6.3%, train_loss=0.932]

outcome_architecture/outcome:   1%|▏         | 26/2000 [00:00<00:35, 56.19it/s, test=7.0%, test_loss=0.932, train=6.3%, train_loss=0.932]

outcome_architecture/outcome:   2%|▏         | 37/2000 [00:00<00:27, 71.59it/s, test=7.0%, test_loss=0.932, train=6.3%, train_loss=0.932]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:24, 80.33it/s, test=7.0%, test_loss=0.932, train=6.3%, train_loss=0.932]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:24, 80.33it/s, test=10.9%, test_loss=0.928, train=6.0%, train_loss=0.941]

outcome_architecture/outcome:   3%|▎         | 56/2000 [00:00<00:25, 77.19it/s, test=10.9%, test_loss=0.928, train=6.0%, train_loss=0.941]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:00<00:23, 83.58it/s, test=10.9%, test_loss=0.928, train=6.0%, train_loss=0.941]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:01<00:23, 83.58it/s, test=12.2%, test_loss=0.914, train=9.0%, train_loss=0.907]

outcome_architecture/outcome:   4%|▍         | 75/2000 [00:01<00:24, 79.49it/s, test=12.2%, test_loss=0.914, train=9.0%, train_loss=0.907]

outcome_architecture/outcome:   4%|▍         | 85/2000 [00:01<00:22, 85.01it/s, test=12.2%, test_loss=0.914, train=9.0%, train_loss=0.907]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 89.24it/s, test=12.2%, test_loss=0.914, train=9.0%, train_loss=0.907]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 89.24it/s, test=11.0%, test_loss=0.898, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:   5%|▌         | 105/2000 [00:01<00:22, 83.77it/s, test=11.0%, test_loss=0.898, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:   6%|▌         | 116/2000 [00:01<00:21, 88.76it/s, test=11.0%, test_loss=0.898, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:   6%|▋         | 127/2000 [00:01<00:20, 92.58it/s, test=11.0%, test_loss=0.898, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:   7%|▋         | 138/2000 [00:01<00:19, 96.08it/s, test=11.0%, test_loss=0.898, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:   7%|▋         | 149/2000 [00:01<00:18, 98.93it/s, test=11.0%, test_loss=0.898, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:   7%|▋         | 149/2000 [00:01<00:18, 98.93it/s, test=11.7%, test_loss=0.911, train=8.0%, train_loss=0.907]

outcome_architecture/outcome:   8%|▊         | 159/2000 [00:01<00:20, 91.45it/s, test=11.7%, test_loss=0.911, train=8.0%, train_loss=0.907]

outcome_architecture/outcome:   8%|▊         | 170/2000 [00:02<00:19, 95.13it/s, test=11.7%, test_loss=0.911, train=8.0%, train_loss=0.907]

outcome_architecture/outcome:   9%|▉         | 181/2000 [00:02<00:18, 98.01it/s, test=11.7%, test_loss=0.911, train=8.0%, train_loss=0.907]

outcome_architecture/outcome:  10%|▉         | 192/2000 [00:02<00:18, 100.31it/s, test=11.7%, test_loss=0.911, train=8.0%, train_loss=0.907]

outcome_architecture/outcome:  10%|▉         | 192/2000 [00:02<00:18, 100.31it/s, test=11.7%, test_loss=0.897, train=11.7%, train_loss=0.888]

outcome_architecture/outcome:  10%|█         | 203/2000 [00:02<00:19, 91.74it/s, test=11.7%, test_loss=0.897, train=11.7%, train_loss=0.888]

outcome_architecture/outcome:  11%|█         | 214/2000 [00:02<00:18, 94.71it/s, test=11.7%, test_loss=0.897, train=11.7%, train_loss=0.888]

outcome_architecture/outcome:  11%|█▏        | 225/2000 [00:02<00:18, 96.89it/s, test=11.7%, test_loss=0.897, train=11.7%, train_loss=0.888]

outcome_architecture/outcome:  12%|█▏        | 236/2000 [00:02<00:17, 98.58it/s, test=11.7%, test_loss=0.897, train=11.7%, train_loss=0.888]

outcome_architecture/outcome:  12%|█▏        | 247/2000 [00:02<00:17, 99.79it/s, test=11.7%, test_loss=0.897, train=11.7%, train_loss=0.888]

outcome_architecture/outcome:  12%|█▏        | 247/2000 [00:02<00:17, 99.79it/s, test=12.6%, test_loss=0.902, train=8.3%, train_loss=0.886]

outcome_architecture/outcome:  13%|█▎        | 258/2000 [00:02<00:19, 91.34it/s, test=12.6%, test_loss=0.902, train=8.3%, train_loss=0.886]

outcome_architecture/outcome:  13%|█▎        | 268/2000 [00:03<00:18, 93.59it/s, test=12.6%, test_loss=0.902, train=8.3%, train_loss=0.886]

outcome_architecture/outcome:  14%|█▍        | 278/2000 [00:03<00:18, 95.21it/s, test=12.6%, test_loss=0.902, train=8.3%, train_loss=0.886]

outcome_architecture/outcome:  14%|█▍        | 289/2000 [00:03<00:17, 96.52it/s, test=12.6%, test_loss=0.902, train=8.3%, train_loss=0.886]

outcome_architecture/outcome:  15%|█▍        | 299/2000 [00:03<00:17, 97.15it/s, test=12.6%, test_loss=0.902, train=8.3%, train_loss=0.886]

outcome_architecture/outcome:  15%|█▍        | 299/2000 [00:03<00:17, 97.15it/s, test=13.8%, test_loss=0.901, train=11.7%, train_loss=0.885]

outcome_architecture/outcome:  15%|█▌        | 309/2000 [00:03<00:19, 87.80it/s, test=13.8%, test_loss=0.901, train=11.7%, train_loss=0.885]

outcome_architecture/outcome:  16%|█▌        | 319/2000 [00:03<00:18, 91.00it/s, test=13.8%, test_loss=0.901, train=11.7%, train_loss=0.885]

outcome_architecture/outcome:  16%|█▋        | 329/2000 [00:03<00:17, 93.48it/s, test=13.8%, test_loss=0.901, train=11.7%, train_loss=0.885]

outcome_architecture/outcome:  17%|█▋        | 339/2000 [00:03<00:17, 95.19it/s, test=13.8%, test_loss=0.901, train=11.7%, train_loss=0.885]

outcome_architecture/outcome:  17%|█▋        | 349/2000 [00:03<00:17, 96.40it/s, test=13.8%, test_loss=0.901, train=11.7%, train_loss=0.885]

outcome_architecture/outcome:  17%|█▋        | 349/2000 [00:03<00:17, 96.40it/s, test=12.5%, test_loss=0.901, train=10.3%, train_loss=1.039]

outcome_architecture/outcome:  18%|█▊        | 359/2000 [00:04<00:18, 87.29it/s, test=12.5%, test_loss=0.901, train=10.3%, train_loss=1.039]

outcome_architecture/outcome:  18%|█▊        | 369/2000 [00:04<00:18, 90.34it/s, test=12.5%, test_loss=0.901, train=10.3%, train_loss=1.039]

outcome_architecture/outcome:  19%|█▉        | 379/2000 [00:04<00:17, 92.81it/s, test=12.5%, test_loss=0.901, train=10.3%, train_loss=1.039]

outcome_architecture/outcome:  19%|█▉        | 389/2000 [00:04<00:17, 94.11it/s, test=12.5%, test_loss=0.901, train=10.3%, train_loss=1.039]

outcome_architecture/outcome:  20%|█▉        | 399/2000 [00:04<00:16, 94.75it/s, test=12.5%, test_loss=0.901, train=10.3%, train_loss=1.039]

outcome_architecture/outcome:  20%|█▉        | 399/2000 [00:04<00:16, 94.75it/s, test=0.1%, test_loss=71849.688, train=0.0%, train_loss=67868.336]

outcome_architecture/outcome:  20%|██        | 409/2000 [00:04<00:18, 86.49it/s, test=0.1%, test_loss=71849.688, train=0.0%, train_loss=67868.336]

outcome_architecture/outcome:  21%|██        | 419/2000 [00:04<00:17, 89.09it/s, test=0.1%, test_loss=71849.688, train=0.0%, train_loss=67868.336]

outcome_architecture/outcome:  21%|██▏       | 429/2000 [00:04<00:17, 91.03it/s, test=0.1%, test_loss=71849.688, train=0.0%, train_loss=67868.336]

outcome_architecture/outcome:  22%|██▏       | 439/2000 [00:04<00:16, 92.75it/s, test=0.1%, test_loss=71849.688, train=0.0%, train_loss=67868.336]

outcome_architecture/outcome:  22%|██▏       | 449/2000 [00:05<00:16, 93.64it/s, test=0.1%, test_loss=71849.688, train=0.0%, train_loss=67868.336]

outcome_architecture/outcome:  22%|██▏       | 449/2000 [00:05<00:16, 93.64it/s, test=0.0%, test_loss=767280.688, train=0.0%, train_loss=740427.688]

outcome_architecture/outcome:  23%|██▎       | 459/2000 [00:05<00:17, 86.06it/s, test=0.0%, test_loss=767280.688, train=0.0%, train_loss=740427.688]

outcome_architecture/outcome:  23%|██▎       | 469/2000 [00:05<00:17, 88.98it/s, test=0.0%, test_loss=767280.688, train=0.0%, train_loss=740427.688]

outcome_architecture/outcome:  24%|██▍       | 479/2000 [00:05<00:16, 90.93it/s, test=0.0%, test_loss=767280.688, train=0.0%, train_loss=740427.688]

outcome_architecture/outcome:  24%|██▍       | 489/2000 [00:05<00:16, 92.60it/s, test=0.0%, test_loss=767280.688, train=0.0%, train_loss=740427.688]

outcome_architecture/outcome:  25%|██▍       | 499/2000 [00:05<00:15, 94.18it/s, test=0.0%, test_loss=767280.688, train=0.0%, train_loss=740427.688]

outcome_architecture/outcome:  25%|██▍       | 499/2000 [00:05<00:15, 94.18it/s, test=0.0%, test_loss=449636.625, train=0.0%, train_loss=452622.531]

outcome_architecture/outcome:  25%|██▌       | 509/2000 [00:05<00:16, 87.92it/s, test=0.0%, test_loss=449636.625, train=0.0%, train_loss=452622.531]

outcome_architecture/outcome:  26%|██▌       | 519/2000 [00:05<00:16, 91.16it/s, test=0.0%, test_loss=449636.625, train=0.0%, train_loss=452622.531]

outcome_architecture/outcome:  26%|██▋       | 530/2000 [00:05<00:15, 93.85it/s, test=0.0%, test_loss=449636.625, train=0.0%, train_loss=452622.531]

outcome_architecture/outcome:  27%|██▋       | 541/2000 [00:06<00:15, 95.89it/s, test=0.0%, test_loss=449636.625, train=0.0%, train_loss=452622.531]

outcome_architecture/outcome:  27%|██▋       | 541/2000 [00:06<00:15, 95.89it/s, test=0.0%, test_loss=16516.578, train=0.0%, train_loss=18877.746]

outcome_architecture/outcome:  28%|██▊       | 551/2000 [00:06<00:16, 87.01it/s, test=0.0%, test_loss=16516.578, train=0.0%, train_loss=18877.746]

outcome_architecture/outcome:  28%|██▊       | 561/2000 [00:06<00:16, 88.09it/s, test=0.0%, test_loss=16516.578, train=0.0%, train_loss=18877.746]

outcome_architecture/outcome:  29%|██▊       | 571/2000 [00:06<00:16, 88.63it/s, test=0.0%, test_loss=16516.578, train=0.0%, train_loss=18877.746]

outcome_architecture/outcome:  29%|██▉       | 581/2000 [00:06<00:15, 90.59it/s, test=0.0%, test_loss=16516.578, train=0.0%, train_loss=18877.746]

outcome_architecture/outcome:  30%|██▉       | 591/2000 [00:06<00:15, 92.14it/s, test=0.0%, test_loss=16516.578, train=0.0%, train_loss=18877.746]

outcome_architecture/outcome:  30%|██▉       | 591/2000 [00:06<00:15, 92.14it/s, test=1.2%, test_loss=5803.849, train=1.7%, train_loss=6227.365]

outcome_architecture/outcome:  30%|███       | 601/2000 [00:06<00:16, 83.37it/s, test=1.2%, test_loss=5803.849, train=1.7%, train_loss=6227.365]

outcome_architecture/outcome:  31%|███       | 611/2000 [00:06<00:16, 86.61it/s, test=1.2%, test_loss=5803.849, train=1.7%, train_loss=6227.365]

outcome_architecture/outcome:  31%|███       | 621/2000 [00:06<00:15, 88.88it/s, test=1.2%, test_loss=5803.849, train=1.7%, train_loss=6227.365]

outcome_architecture/outcome:  32%|███▏      | 631/2000 [00:07<00:15, 89.50it/s, test=1.2%, test_loss=5803.849, train=1.7%, train_loss=6227.365]

outcome_architecture/outcome:  32%|███▏      | 641/2000 [00:07<00:14, 91.81it/s, test=1.2%, test_loss=5803.849, train=1.7%, train_loss=6227.365]

outcome_architecture/outcome:  32%|███▏      | 641/2000 [00:07<00:14, 91.81it/s, test=1.5%, test_loss=1612.126, train=2.3%, train_loss=1823.728]

outcome_architecture/outcome:  33%|███▎      | 651/2000 [00:07<00:15, 84.90it/s, test=1.5%, test_loss=1612.126, train=2.3%, train_loss=1823.728]

outcome_architecture/outcome:  33%|███▎      | 661/2000 [00:07<00:15, 86.62it/s, test=1.5%, test_loss=1612.126, train=2.3%, train_loss=1823.728]

outcome_architecture/outcome:  34%|███▎      | 671/2000 [00:07<00:14, 89.28it/s, test=1.5%, test_loss=1612.126, train=2.3%, train_loss=1823.728]

outcome_architecture/outcome:  34%|███▍      | 681/2000 [00:07<00:14, 91.49it/s, test=1.5%, test_loss=1612.126, train=2.3%, train_loss=1823.728]

outcome_architecture/outcome:  35%|███▍      | 691/2000 [00:07<00:14, 92.00it/s, test=1.5%, test_loss=1612.126, train=2.3%, train_loss=1823.728]

outcome_architecture/outcome:  35%|███▍      | 691/2000 [00:07<00:14, 92.00it/s, test=0.6%, test_loss=731.785, train=1.0%, train_loss=863.258]

outcome_architecture/outcome:  35%|███▌      | 701/2000 [00:07<00:15, 84.89it/s, test=0.6%, test_loss=731.785, train=1.0%, train_loss=863.258]

outcome_architecture/outcome:  36%|███▌      | 711/2000 [00:07<00:14, 86.75it/s, test=0.6%, test_loss=731.785, train=1.0%, train_loss=863.258]

outcome_architecture/outcome:  36%|███▌      | 721/2000 [00:08<00:14, 89.33it/s, test=0.6%, test_loss=731.785, train=1.0%, train_loss=863.258]

outcome_architecture/outcome:  37%|███▋      | 731/2000 [00:08<00:13, 91.54it/s, test=0.6%, test_loss=731.785, train=1.0%, train_loss=863.258]

outcome_architecture/outcome:  37%|███▋      | 741/2000 [00:08<00:13, 91.74it/s, test=0.6%, test_loss=731.785, train=1.0%, train_loss=863.258]

outcome_architecture/outcome:  37%|███▋      | 741/2000 [00:08<00:13, 91.74it/s, test=0.6%, test_loss=642.991, train=1.7%, train_loss=686.314]

outcome_architecture/outcome:  38%|███▊      | 751/2000 [00:08<00:14, 84.51it/s, test=0.6%, test_loss=642.991, train=1.7%, train_loss=686.314]

outcome_architecture/outcome:  38%|███▊      | 761/2000 [00:08<00:14, 87.96it/s, test=0.6%, test_loss=642.991, train=1.7%, train_loss=686.314]

outcome_architecture/outcome:  39%|███▊      | 771/2000 [00:08<00:13, 89.36it/s, test=0.6%, test_loss=642.991, train=1.7%, train_loss=686.314]

outcome_architecture/outcome:  39%|███▉      | 781/2000 [00:08<00:13, 91.18it/s, test=0.6%, test_loss=642.991, train=1.7%, train_loss=686.314]

outcome_architecture/outcome:  40%|███▉      | 791/2000 [00:08<00:13, 93.00it/s, test=0.6%, test_loss=642.991, train=1.7%, train_loss=686.314]

outcome_architecture/outcome:  40%|███▉      | 791/2000 [00:08<00:13, 93.00it/s, test=1.7%, test_loss=480.206, train=3.3%, train_loss=463.479]

outcome_architecture/outcome:  40%|████      | 801/2000 [00:09<00:14, 84.38it/s, test=1.7%, test_loss=480.206, train=3.3%, train_loss=463.479]

outcome_architecture/outcome:  41%|████      | 811/2000 [00:09<00:13, 87.91it/s, test=1.7%, test_loss=480.206, train=3.3%, train_loss=463.479]

outcome_architecture/outcome:  41%|████      | 821/2000 [00:09<00:12, 91.00it/s, test=1.7%, test_loss=480.206, train=3.3%, train_loss=463.479]

outcome_architecture/outcome:  42%|████▏     | 831/2000 [00:09<00:12, 91.78it/s, test=1.7%, test_loss=480.206, train=3.3%, train_loss=463.479]

outcome_architecture/outcome:  42%|████▏     | 841/2000 [00:09<00:12, 94.04it/s, test=1.7%, test_loss=480.206, train=3.3%, train_loss=463.479]

outcome_architecture/outcome:  42%|████▏     | 841/2000 [00:09<00:12, 94.04it/s, test=2.7%, test_loss=479.265, train=1.7%, train_loss=531.957]

outcome_architecture/outcome:  43%|████▎     | 851/2000 [00:09<00:13, 85.37it/s, test=2.7%, test_loss=479.265, train=1.7%, train_loss=531.957]

outcome_architecture/outcome:  43%|████▎     | 861/2000 [00:09<00:12, 88.51it/s, test=2.7%, test_loss=479.265, train=1.7%, train_loss=531.957]

outcome_architecture/outcome:  44%|████▎     | 872/2000 [00:09<00:12, 92.01it/s, test=2.7%, test_loss=479.265, train=1.7%, train_loss=531.957]

outcome_architecture/outcome:  44%|████▍     | 882/2000 [00:09<00:12, 92.50it/s, test=2.7%, test_loss=479.265, train=1.7%, train_loss=531.957]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:11, 94.43it/s, test=2.7%, test_loss=479.265, train=1.7%, train_loss=531.957]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:10<00:11, 94.43it/s, test=2.8%, test_loss=491.937, train=3.0%, train_loss=367.084]

outcome_architecture/outcome:  45%|████▌     | 902/2000 [00:10<00:12, 87.29it/s, test=2.8%, test_loss=491.937, train=3.0%, train_loss=367.084]

outcome_architecture/outcome:  46%|████▌     | 912/2000 [00:10<00:12, 89.59it/s, test=2.8%, test_loss=491.937, train=3.0%, train_loss=367.084]

outcome_architecture/outcome:  46%|████▌     | 923/2000 [00:10<00:11, 94.39it/s, test=2.8%, test_loss=491.937, train=3.0%, train_loss=367.084]

outcome_architecture/outcome:  47%|████▋     | 934/2000 [00:10<00:10, 97.90it/s, test=2.8%, test_loss=491.937, train=3.0%, train_loss=367.084]

outcome_architecture/outcome:  47%|████▋     | 945/2000 [00:10<00:10, 98.94it/s, test=2.8%, test_loss=491.937, train=3.0%, train_loss=367.084]

outcome_architecture/outcome:  47%|████▋     | 945/2000 [00:10<00:10, 98.94it/s, test=4.5%, test_loss=406.730, train=6.0%, train_loss=403.880]

outcome_architecture/outcome:  48%|████▊     | 955/2000 [00:10<00:11, 91.57it/s, test=4.5%, test_loss=406.730, train=6.0%, train_loss=403.880]

outcome_architecture/outcome:  48%|████▊     | 966/2000 [00:10<00:10, 95.77it/s, test=4.5%, test_loss=406.730, train=6.0%, train_loss=403.880]

outcome_architecture/outcome:  49%|████▉     | 977/2000 [00:10<00:10, 98.77it/s, test=4.5%, test_loss=406.730, train=6.0%, train_loss=403.880]

outcome_architecture/outcome:  49%|████▉     | 988/2000 [00:10<00:10, 101.05it/s, test=4.5%, test_loss=406.730, train=6.0%, train_loss=403.880]

outcome_architecture/outcome:  50%|████▉     | 999/2000 [00:11<00:09, 102.63it/s, test=4.5%, test_loss=406.730, train=6.0%, train_loss=403.880]

outcome_architecture/outcome:  50%|████▉     | 999/2000 [00:11<00:09, 102.63it/s, test=2.8%, test_loss=326.525, train=3.3%, train_loss=378.319]

outcome_architecture/outcome:  50%|█████     | 1010/2000 [00:11<00:10, 94.44it/s, test=2.8%, test_loss=326.525, train=3.3%, train_loss=378.319]

outcome_architecture/outcome:  51%|█████     | 1021/2000 [00:11<00:10, 97.81it/s, test=2.8%, test_loss=326.525, train=3.3%, train_loss=378.319]

outcome_architecture/outcome:  52%|█████▏    | 1032/2000 [00:11<00:09, 100.34it/s, test=2.8%, test_loss=326.525, train=3.3%, train_loss=378.319]

outcome_architecture/outcome:  52%|█████▏    | 1043/2000 [00:11<00:09, 102.08it/s, test=2.8%, test_loss=326.525, train=3.3%, train_loss=378.319]

outcome_architecture/outcome:  52%|█████▏    | 1043/2000 [00:11<00:09, 102.08it/s, test=2.7%, test_loss=254.029, train=2.3%, train_loss=268.986]

outcome_architecture/outcome:  53%|█████▎    | 1054/2000 [00:11<00:10, 93.95it/s, test=2.7%, test_loss=254.029, train=2.3%, train_loss=268.986]

outcome_architecture/outcome:  53%|█████▎    | 1065/2000 [00:11<00:09, 97.47it/s, test=2.7%, test_loss=254.029, train=2.3%, train_loss=268.986]

outcome_architecture/outcome:  54%|█████▍    | 1076/2000 [00:11<00:09, 99.98it/s, test=2.7%, test_loss=254.029, train=2.3%, train_loss=268.986]

outcome_architecture/outcome:  54%|█████▍    | 1087/2000 [00:11<00:08, 101.91it/s, test=2.7%, test_loss=254.029, train=2.3%, train_loss=268.986]

outcome_architecture/outcome:  55%|█████▍    | 1098/2000 [00:12<00:08, 103.24it/s, test=2.7%, test_loss=254.029, train=2.3%, train_loss=268.986]

outcome_architecture/outcome:  55%|█████▍    | 1098/2000 [00:12<00:08, 103.24it/s, test=4.1%, test_loss=174.589, train=3.3%, train_loss=183.462]

outcome_architecture/outcome:  55%|█████▌    | 1109/2000 [00:12<00:09, 94.62it/s, test=4.1%, test_loss=174.589, train=3.3%, train_loss=183.462]

outcome_architecture/outcome:  56%|█████▌    | 1120/2000 [00:12<00:08, 97.83it/s, test=4.1%, test_loss=174.589, train=3.3%, train_loss=183.462]

outcome_architecture/outcome:  57%|█████▋    | 1131/2000 [00:12<00:08, 100.17it/s, test=4.1%, test_loss=174.589, train=3.3%, train_loss=183.462]

outcome_architecture/outcome:  57%|█████▋    | 1142/2000 [00:12<00:08, 102.02it/s, test=4.1%, test_loss=174.589, train=3.3%, train_loss=183.462]

outcome_architecture/outcome:  57%|█████▋    | 1142/2000 [00:12<00:08, 102.02it/s, test=0.0%, test_loss=6949.095, train=0.7%, train_loss=6711.733]

outcome_architecture/outcome:  58%|█████▊    | 1153/2000 [00:12<00:09, 93.94it/s, test=0.0%, test_loss=6949.095, train=0.7%, train_loss=6711.733]

outcome_architecture/outcome:  58%|█████▊    | 1164/2000 [00:12<00:08, 97.53it/s, test=0.0%, test_loss=6949.095, train=0.7%, train_loss=6711.733]

outcome_architecture/outcome:  59%|█████▉    | 1175/2000 [00:12<00:08, 100.02it/s, test=0.0%, test_loss=6949.095, train=0.7%, train_loss=6711.733]

outcome_architecture/outcome:  59%|█████▉    | 1186/2000 [00:12<00:07, 102.10it/s, test=0.0%, test_loss=6949.095, train=0.7%, train_loss=6711.733]

outcome_architecture/outcome:  60%|█████▉    | 1197/2000 [00:13<00:07, 103.50it/s, test=0.0%, test_loss=6949.095, train=0.7%, train_loss=6711.733]

outcome_architecture/outcome:  60%|█████▉    | 1197/2000 [00:13<00:07, 103.50it/s, test=1.1%, test_loss=3282.371, train=1.0%, train_loss=4375.762]

outcome_architecture/outcome:  60%|██████    | 1208/2000 [00:13<00:08, 94.94it/s, test=1.1%, test_loss=3282.371, train=1.0%, train_loss=4375.762]

outcome_architecture/outcome:  61%|██████    | 1219/2000 [00:13<00:07, 98.16it/s, test=1.1%, test_loss=3282.371, train=1.0%, train_loss=4375.762]

outcome_architecture/outcome:  62%|██████▏   | 1230/2000 [00:13<00:07, 100.80it/s, test=1.1%, test_loss=3282.371, train=1.0%, train_loss=4375.762]

outcome_architecture/outcome:  62%|██████▏   | 1241/2000 [00:13<00:07, 102.40it/s, test=1.1%, test_loss=3282.371, train=1.0%, train_loss=4375.762]

outcome_architecture/outcome:  62%|██████▏   | 1241/2000 [00:13<00:07, 102.40it/s, test=2.3%, test_loss=1125.235, train=2.7%, train_loss=1516.102]

outcome_architecture/outcome:  63%|██████▎   | 1252/2000 [00:13<00:07, 94.21it/s, test=2.3%, test_loss=1125.235, train=2.7%, train_loss=1516.102]

outcome_architecture/outcome:  63%|██████▎   | 1263/2000 [00:13<00:07, 97.54it/s, test=2.3%, test_loss=1125.235, train=2.7%, train_loss=1516.102]

outcome_architecture/outcome:  64%|██████▎   | 1274/2000 [00:13<00:07, 100.00it/s, test=2.3%, test_loss=1125.235, train=2.7%, train_loss=1516.102]

outcome_architecture/outcome:  64%|██████▍   | 1285/2000 [00:13<00:07, 101.86it/s, test=2.3%, test_loss=1125.235, train=2.7%, train_loss=1516.102]

outcome_architecture/outcome:  65%|██████▍   | 1296/2000 [00:14<00:06, 103.14it/s, test=2.3%, test_loss=1125.235, train=2.7%, train_loss=1516.102]

outcome_architecture/outcome:  65%|██████▍   | 1296/2000 [00:14<00:06, 103.14it/s, test=2.4%, test_loss=609.858, train=1.7%, train_loss=989.220]

outcome_architecture/outcome:  65%|██████▌   | 1307/2000 [00:14<00:07, 94.43it/s, test=2.4%, test_loss=609.858, train=1.7%, train_loss=989.220]

outcome_architecture/outcome:  66%|██████▌   | 1318/2000 [00:14<00:06, 97.71it/s, test=2.4%, test_loss=609.858, train=1.7%, train_loss=989.220]

outcome_architecture/outcome:  66%|██████▋   | 1329/2000 [00:14<00:06, 99.89it/s, test=2.4%, test_loss=609.858, train=1.7%, train_loss=989.220]

outcome_architecture/outcome:  67%|██████▋   | 1340/2000 [00:14<00:06, 101.67it/s, test=2.4%, test_loss=609.858, train=1.7%, train_loss=989.220]

outcome_architecture/outcome:  67%|██████▋   | 1340/2000 [00:14<00:06, 101.67it/s, test=3.6%, test_loss=481.771, train=3.3%, train_loss=752.960]

outcome_architecture/outcome:  68%|██████▊   | 1351/2000 [00:14<00:07, 91.87it/s, test=3.6%, test_loss=481.771, train=3.3%, train_loss=752.960]

outcome_architecture/outcome:  68%|██████▊   | 1362/2000 [00:14<00:06, 95.62it/s, test=3.6%, test_loss=481.771, train=3.3%, train_loss=752.960]

outcome_architecture/outcome:  69%|██████▊   | 1373/2000 [00:14<00:06, 98.40it/s, test=3.6%, test_loss=481.771, train=3.3%, train_loss=752.960]

outcome_architecture/outcome:  69%|██████▉   | 1384/2000 [00:14<00:06, 98.92it/s, test=3.6%, test_loss=481.771, train=3.3%, train_loss=752.960]

outcome_architecture/outcome:  70%|██████▉   | 1395/2000 [00:15<00:05, 100.93it/s, test=3.6%, test_loss=481.771, train=3.3%, train_loss=752.960]

outcome_architecture/outcome:  70%|██████▉   | 1395/2000 [00:15<00:05, 100.93it/s, test=1.9%, test_loss=371.885, train=4.3%, train_loss=425.450]

outcome_architecture/outcome:  70%|███████   | 1406/2000 [00:15<00:06, 93.32it/s, test=1.9%, test_loss=371.885, train=4.3%, train_loss=425.450]

outcome_architecture/outcome:  71%|███████   | 1416/2000 [00:15<00:06, 95.08it/s, test=1.9%, test_loss=371.885, train=4.3%, train_loss=425.450]

outcome_architecture/outcome:  71%|███████▏  | 1427/2000 [00:15<00:05, 98.07it/s, test=1.9%, test_loss=371.885, train=4.3%, train_loss=425.450]

outcome_architecture/outcome:  72%|███████▏  | 1438/2000 [00:15<00:05, 100.30it/s, test=1.9%, test_loss=371.885, train=4.3%, train_loss=425.450]

outcome_architecture/outcome:  72%|███████▏  | 1449/2000 [00:15<00:05, 99.91it/s, test=1.9%, test_loss=371.885, train=4.3%, train_loss=425.450]

outcome_architecture/outcome:  72%|███████▏  | 1449/2000 [00:15<00:05, 99.91it/s, test=3.1%, test_loss=279.679, train=3.3%, train_loss=300.243]

outcome_architecture/outcome:  73%|███████▎  | 1460/2000 [00:15<00:06, 89.94it/s, test=3.1%, test_loss=279.679, train=3.3%, train_loss=300.243]

outcome_architecture/outcome:  74%|███████▎  | 1470/2000 [00:15<00:05, 92.24it/s, test=3.1%, test_loss=279.679, train=3.3%, train_loss=300.243]

outcome_architecture/outcome:  74%|███████▍  | 1480/2000 [00:16<00:05, 93.92it/s, test=3.1%, test_loss=279.679, train=3.3%, train_loss=300.243]

outcome_architecture/outcome:  74%|███████▍  | 1490/2000 [00:16<00:05, 95.13it/s, test=3.1%, test_loss=279.679, train=3.3%, train_loss=300.243]

outcome_architecture/outcome:  74%|███████▍  | 1490/2000 [00:16<00:05, 95.13it/s, test=2.8%, test_loss=248.925, train=4.0%, train_loss=241.152]

outcome_architecture/outcome:  75%|███████▌  | 1500/2000 [00:16<00:05, 87.02it/s, test=2.8%, test_loss=248.925, train=4.0%, train_loss=241.152]

outcome_architecture/outcome:  76%|███████▌  | 1510/2000 [00:16<00:05, 90.15it/s, test=2.8%, test_loss=248.925, train=4.0%, train_loss=241.152]

outcome_architecture/outcome:  76%|███████▌  | 1520/2000 [00:16<00:05, 92.54it/s, test=2.8%, test_loss=248.925, train=4.0%, train_loss=241.152]

outcome_architecture/outcome:  76%|███████▋  | 1530/2000 [00:16<00:04, 94.50it/s, test=2.8%, test_loss=248.925, train=4.0%, train_loss=241.152]

outcome_architecture/outcome:  77%|███████▋  | 1540/2000 [00:16<00:04, 95.60it/s, test=2.8%, test_loss=248.925, train=4.0%, train_loss=241.152]

outcome_architecture/outcome:  77%|███████▋  | 1540/2000 [00:16<00:04, 95.60it/s, test=3.9%, test_loss=235.507, train=4.0%, train_loss=323.094]

outcome_architecture/outcome:  78%|███████▊  | 1550/2000 [00:16<00:05, 86.71it/s, test=3.9%, test_loss=235.507, train=4.0%, train_loss=323.094]

outcome_architecture/outcome:  78%|███████▊  | 1560/2000 [00:16<00:04, 90.08it/s, test=3.9%, test_loss=235.507, train=4.0%, train_loss=323.094]

outcome_architecture/outcome:  79%|███████▊  | 1571/2000 [00:16<00:04, 94.20it/s, test=3.9%, test_loss=235.507, train=4.0%, train_loss=323.094]

outcome_architecture/outcome:  79%|███████▉  | 1582/2000 [00:17<00:04, 97.77it/s, test=3.9%, test_loss=235.507, train=4.0%, train_loss=323.094]

outcome_architecture/outcome:  80%|███████▉  | 1593/2000 [00:17<00:04, 100.41it/s, test=3.9%, test_loss=235.507, train=4.0%, train_loss=323.094]

outcome_architecture/outcome:  80%|███████▉  | 1593/2000 [00:17<00:04, 100.41it/s, test=1.4%, test_loss=161.904, train=2.0%, train_loss=185.751]

outcome_architecture/outcome:  80%|████████  | 1604/2000 [00:17<00:04, 92.87it/s, test=1.4%, test_loss=161.904, train=2.0%, train_loss=185.751]

outcome_architecture/outcome:  81%|████████  | 1615/2000 [00:17<00:03, 96.57it/s, test=1.4%, test_loss=161.904, train=2.0%, train_loss=185.751]

outcome_architecture/outcome:  81%|████████▏ | 1626/2000 [00:17<00:03, 99.39it/s, test=1.4%, test_loss=161.904, train=2.0%, train_loss=185.751]

outcome_architecture/outcome:  82%|████████▏ | 1637/2000 [00:17<00:03, 101.63it/s, test=1.4%, test_loss=161.904, train=2.0%, train_loss=185.751]

outcome_architecture/outcome:  82%|████████▏ | 1648/2000 [00:17<00:03, 103.13it/s, test=1.4%, test_loss=161.904, train=2.0%, train_loss=185.751]

outcome_architecture/outcome:  82%|████████▏ | 1648/2000 [00:17<00:03, 103.13it/s, test=4.1%, test_loss=1605.628, train=4.7%, train_loss=1700.273]

outcome_architecture/outcome:  83%|████████▎ | 1659/2000 [00:17<00:03, 94.70it/s, test=4.1%, test_loss=1605.628, train=4.7%, train_loss=1700.273]

outcome_architecture/outcome:  84%|████████▎ | 1670/2000 [00:17<00:03, 98.15it/s, test=4.1%, test_loss=1605.628, train=4.7%, train_loss=1700.273]

outcome_architecture/outcome:  84%|████████▍ | 1681/2000 [00:18<00:03, 100.76it/s, test=4.1%, test_loss=1605.628, train=4.7%, train_loss=1700.273]

outcome_architecture/outcome:  85%|████████▍ | 1692/2000 [00:18<00:03, 102.64it/s, test=4.1%, test_loss=1605.628, train=4.7%, train_loss=1700.273]

outcome_architecture/outcome:  85%|████████▍ | 1692/2000 [00:18<00:03, 102.64it/s, test=0.9%, test_loss=1221.679, train=1.0%, train_loss=1004.446]

outcome_architecture/outcome:  85%|████████▌ | 1703/2000 [00:18<00:03, 93.61it/s, test=0.9%, test_loss=1221.679, train=1.0%, train_loss=1004.446]

outcome_architecture/outcome:  86%|████████▌ | 1713/2000 [00:18<00:03, 94.70it/s, test=0.9%, test_loss=1221.679, train=1.0%, train_loss=1004.446]

outcome_architecture/outcome:  86%|████████▌ | 1723/2000 [00:18<00:02, 95.15it/s, test=0.9%, test_loss=1221.679, train=1.0%, train_loss=1004.446]

outcome_architecture/outcome:  87%|████████▋ | 1733/2000 [00:18<00:02, 95.34it/s, test=0.9%, test_loss=1221.679, train=1.0%, train_loss=1004.446]

outcome_architecture/outcome:  87%|████████▋ | 1743/2000 [00:18<00:02, 95.87it/s, test=0.9%, test_loss=1221.679, train=1.0%, train_loss=1004.446]

outcome_architecture/outcome:  87%|████████▋ | 1743/2000 [00:18<00:02, 95.87it/s, test=0.0%, test_loss=9647.374, train=0.0%, train_loss=9080.239]

outcome_architecture/outcome:  88%|████████▊ | 1753/2000 [00:18<00:02, 87.60it/s, test=0.0%, test_loss=9647.374, train=0.0%, train_loss=9080.239]

outcome_architecture/outcome:  88%|████████▊ | 1763/2000 [00:18<00:02, 90.02it/s, test=0.0%, test_loss=9647.374, train=0.0%, train_loss=9080.239]

outcome_architecture/outcome:  89%|████████▊ | 1773/2000 [00:19<00:02, 92.02it/s, test=0.0%, test_loss=9647.374, train=0.0%, train_loss=9080.239]

outcome_architecture/outcome:  89%|████████▉ | 1783/2000 [00:19<00:02, 93.00it/s, test=0.0%, test_loss=9647.374, train=0.0%, train_loss=9080.239]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 93.75it/s, test=0.0%, test_loss=9647.374, train=0.0%, train_loss=9080.239]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 93.75it/s, test=3.1%, test_loss=1160.509, train=2.0%, train_loss=1021.382]

outcome_architecture/outcome:  90%|█████████ | 1803/2000 [00:19<00:02, 85.61it/s, test=3.1%, test_loss=1160.509, train=2.0%, train_loss=1021.382]

outcome_architecture/outcome:  91%|█████████ | 1813/2000 [00:19<00:02, 88.73it/s, test=3.1%, test_loss=1160.509, train=2.0%, train_loss=1021.382]

outcome_architecture/outcome:  91%|█████████ | 1823/2000 [00:19<00:01, 90.64it/s, test=3.1%, test_loss=1160.509, train=2.0%, train_loss=1021.382]

outcome_architecture/outcome:  92%|█████████▏| 1833/2000 [00:19<00:01, 92.07it/s, test=3.1%, test_loss=1160.509, train=2.0%, train_loss=1021.382]

outcome_architecture/outcome:  92%|█████████▏| 1843/2000 [00:19<00:01, 93.29it/s, test=3.1%, test_loss=1160.509, train=2.0%, train_loss=1021.382]

outcome_architecture/outcome:  92%|█████████▏| 1843/2000 [00:19<00:01, 93.29it/s, test=3.1%, test_loss=471.957, train=2.7%, train_loss=501.897]

outcome_architecture/outcome:  93%|█████████▎| 1853/2000 [00:20<00:01, 85.42it/s, test=3.1%, test_loss=471.957, train=2.7%, train_loss=501.897]

outcome_architecture/outcome:  93%|█████████▎| 1863/2000 [00:20<00:01, 88.18it/s, test=3.1%, test_loss=471.957, train=2.7%, train_loss=501.897]

outcome_architecture/outcome:  94%|█████████▎| 1873/2000 [00:20<00:01, 90.52it/s, test=3.1%, test_loss=471.957, train=2.7%, train_loss=501.897]

outcome_architecture/outcome:  94%|█████████▍| 1883/2000 [00:20<00:01, 91.85it/s, test=3.1%, test_loss=471.957, train=2.7%, train_loss=501.897]

outcome_architecture/outcome:  95%|█████████▍| 1893/2000 [00:20<00:01, 93.29it/s, test=3.1%, test_loss=471.957, train=2.7%, train_loss=501.897]

outcome_architecture/outcome:  95%|█████████▍| 1893/2000 [00:20<00:01, 93.29it/s, test=4.5%, test_loss=1251.175, train=4.0%, train_loss=1353.193]

outcome_architecture/outcome:  95%|█████████▌| 1903/2000 [00:20<00:01, 85.63it/s, test=4.5%, test_loss=1251.175, train=4.0%, train_loss=1353.193]

outcome_architecture/outcome:  96%|█████████▌| 1913/2000 [00:20<00:00, 88.39it/s, test=4.5%, test_loss=1251.175, train=4.0%, train_loss=1353.193]

outcome_architecture/outcome:  96%|█████████▌| 1923/2000 [00:20<00:00, 90.39it/s, test=4.5%, test_loss=1251.175, train=4.0%, train_loss=1353.193]

outcome_architecture/outcome:  97%|█████████▋| 1933/2000 [00:20<00:00, 92.07it/s, test=4.5%, test_loss=1251.175, train=4.0%, train_loss=1353.193]

outcome_architecture/outcome:  97%|█████████▋| 1943/2000 [00:20<00:00, 93.14it/s, test=4.5%, test_loss=1251.175, train=4.0%, train_loss=1353.193]

outcome_architecture/outcome:  97%|█████████▋| 1943/2000 [00:21<00:00, 93.14it/s, test=6.6%, test_loss=1276.730, train=6.0%, train_loss=1269.027]

outcome_architecture/outcome:  98%|█████████▊| 1953/2000 [00:21<00:00, 85.14it/s, test=6.6%, test_loss=1276.730, train=6.0%, train_loss=1269.027]

outcome_architecture/outcome:  98%|█████████▊| 1963/2000 [00:21<00:00, 88.34it/s, test=6.6%, test_loss=1276.730, train=6.0%, train_loss=1269.027]

outcome_architecture/outcome:  99%|█████████▊| 1973/2000 [00:21<00:00, 90.60it/s, test=6.6%, test_loss=1276.730, train=6.0%, train_loss=1269.027]

outcome_architecture/outcome:  99%|█████████▉| 1983/2000 [00:21<00:00, 91.85it/s, test=6.6%, test_loss=1276.730, train=6.0%, train_loss=1269.027]

outcome_architecture/outcome: 100%|█████████▉| 1993/2000 [00:21<00:00, 93.25it/s, test=6.6%, test_loss=1276.730, train=6.0%, train_loss=1269.027]

outcome_architecture/outcome: 100%|█████████▉| 1993/2000 [00:21<00:00, 93.25it/s, test=1.7%, test_loss=1046.179, train=1.0%, train_loss=1073.228]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 92.40it/s, test=1.7%, test_loss=1046.179, train=1.0%, train_loss=1073.228]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,process,4.275756,0.000000,0.000,0.000,4.276346
1,1,process_architecture,process,4.260089,0.086667,0.070,0.000,4.260307
2,2,process_architecture,process,4.235738,0.000000,0.000,0.000,4.235439
3,5,process_architecture,process,3.918922,0.000000,0.000,0.000,3.906769
4,10,process_architecture,process,3.664499,0.000000,0.000,0.000,3.650196
...,...,...,...,...,...,...,...,...
91,1800,outcome_architecture,outcome,1021.381775,0.020000,0.031,0.000,1160.509033
92,1850,outcome_architecture,outcome,501.897308,0.026667,0.031,0.000,471.956787
93,1900,outcome_architecture,outcome,1353.193481,0.040000,0.045,0.002,1251.174683
94,1950,outcome_architecture,outcome,1269.027466,0.060000,0.066,0.000,1276.730469
95,2000,outcome_architecture,outcome,1073.227905,0.010000,0.017,0.000,1046.178833


## 7. Final behavioral comparison

The four displayed rows are:

- two fixed references,
- two trained models.

But only the latter two were optimized.

In [8]:

rows = []

for name, model, mode, trained in [
    ("Fixed PROCESS reference", process_reference, "process", False),
    ("Trained PROCESS architecture", trained_process, "process", True),
    ("Fixed OUTCOME reference", outcome_reference, "outcome", False),
    ("Trained OUTCOME architecture", trained_outcome, "outcome", True),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    rows.append({
        "model": name,
        "optimized": trained,
        "mode": mode,
        "test_answer_accuracy": metrics["final_answer"],
        "test_exact_continuation": metrics["exact_continuation"],
    })

final_results = pd.DataFrame(rows)
final_results

,model,optimized,mode,test_answer_accuracy,test_exact_continuation
0,Fixed PROCESS reference,False,process,1.000,1.0
1,Trained PROCESS architecture,True,process,1.000,1.0
2,Fixed OUTCOME reference,False,outcome,1.000,1.0
3,Trained OUTCOME architecture,True,outcome,0.017,0.0

## 8. Learning curves

The first plot tracks free-running answer accuracy. The second plot tracks teacher-forced training and held-out test loss at the same checkpoints.

In [9]:

fig, ax = plt.subplots(figsize=(8, 4.5))

for (architecture, mode), frame in history.groupby(["architecture", "mode"]):
    ax.plot(
        frame["step"],
        frame["test_answer_accuracy"],
        marker="o",
        label=f"{architecture} / {mode}",
    )

ax.axhline(1.0, linestyle="--", label="constructive solution = 100%")
ax.axhline(1 / tokenizer.n_states, linestyle=":", label="chance")
ax.set_xlabel("optimization step")
ax.set_ylabel("free-running test answer accuracy")
ax.set_ylim(-0.02, 1.03)
ax.legend()
plt.show()

In [10]:
def plot_train_test_loss(history, *, steps=STEPS):
    required = {"architecture", "mode", "step", "train_loss", "test_loss"}
    missing = required.difference(history.columns)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"history is missing required columns: {missing_text}")

    fig, ax = plt.subplots(figsize=(9, 5))
    styles = {
        ("process_architecture", "process"): {
            "color": "#2ca02c",
            "label": "PROCESS architecture / process",
        },
        ("outcome_architecture", "outcome"): {
            "color": "#d62728",
            "label": "OUTCOME architecture / outcome",
        },
    }

    for key, frame in history.sort_values("step").groupby(["architecture", "mode"]):
        style = styles.get(key, {"color": None, "label": " / ".join(map(str, key))})
        ax.plot(
            frame["step"],
            frame["train_loss"],
            color=style["color"],
            linewidth=2.2,
            label=f"{style['label']} train",
        )
        ax.plot(
            frame["step"],
            frame["test_loss"],
            color=style["color"],
            linestyle="--",
            linewidth=2.2,
            label=f"{style['label']} test",
        )

    ax.set_xlabel("Iteration", fontsize=13)
    ax.set_ylabel("Teacher-forced loss", fontsize=13)
    ax.set_xlim(0, steps)
    ax.grid(True, alpha=0.35)
    ax.legend(frameon=True, fontsize=10)
    fig.tight_layout()
    return fig, ax

plot_train_test_loss(history)
plt.show()


## 9. Inspect one free-running example

No gold continuation is fed to the model during this evaluation.

In [11]:

example_prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Trained PROCESS", trained_process, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
    ("Trained OUTCOME", trained_outcome, "outcome"),
]:
    budget = 3 if mode == "outcome" else 2 * DEPTH + 3
    generated = generate(
        model,
        example_prompt,
        budget,
        tokenizer.eos,
    )
    continuation = generated[0, example_prompt.shape[1]:]
    print(f"\n{name}")
    print(tokenizer.decode(continuation))

Fixed PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Trained PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Fixed OUTCOME
<COLON> S1001 <EOS>

Trained OUTCOME
<COLON> <COLON> <COLON>


## 10. How to interpret the result

There are four broad possibilities.

### Both trained models reach 100%

The two constructive solution classes are readily reachable from this initialization and optimizer.

### PROCESS reaches 100%, OUTCOME does not

Then

\[
\exists\theta^\star_{\rm O}:\operatorname{Err}(\theta^\star_{\rm O})=0
\]

but the tested terminal-supervision optimization trajectory does not discover it.

That is evidence for a **trainability / accessibility gap**, not an expressivity gap.

### OUTCOME reaches 100%, PROCESS does not

Then the existence of an explicit local process circuit does not by itself guarantee that ordinary trace training discovers it.

### Neither reaches 100%

Then constructive realizability and optimization reachability are substantially different for both architectures.

---

Do not infer an impossibility theorem from a failed run. Multiple seeds, learning-rate controls, and optimizer-stability diagnostics are needed before making a strong optimization claim.


# Optional appendix: full $2\times2$ architecture × supervision experiment

The primary notebook above trains exactly **two** models.

A separate, stronger control can cross:

\[
\{\text{PROCESS architecture},\text{OUTCOME architecture}\}
\times
\{\text{PROCESS supervision},\text{OUTCOME supervision}\}.
\]

That experiment trains **four** models and should be reported separately.

It requires the OUTCOME architecture to use the longer PROCESS position budget, so it is intentionally not the exact diagonal reachability experiment above.

In [12]:
RUN_OPTIONAL_2X2 = True

if RUN_OPTIONAL_2X2:
    from handcoded_utils import (
        build_random_trainable_outcome_architecture,
        build_random_trainable_process_architecture,
        run_architecture_experiment,
    )

    bases = {
        "process_architecture": build_random_trainable_process_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
        "outcome_architecture": build_random_trainable_outcome_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
    }

    models_2x2, history_2x2 = run_architecture_experiment(
        bases,
        training_data,
        batch_schedule,
        LR,
        CHECKPOINTS,
        train_eval,
        test_eval,
        tokenizer,
        circuit_prompts,
        test_loss_data=test_loss_data,
        loss_eval_size=LOSS_EVAL_SIZE,
    )

    display(history_2x2.drop(columns=["circuit_matrix"], errors="ignore"))
else:
    print("Skipping optional 2x2 experiment. Set RUN_OPTIONAL_2X2 = True to run it.")

architecture/mode:   0%|          | 0/4 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.223, train=0.0%, train_loss=4.223]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.143, train=0.0%, train_loss=4.144]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:30,  9.49it/s, test=0.0%, test_loss=4.143, train=0.0%, train_loss=4.144]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:30,  9.49it/s, test=0.0%, test_loss=3.063, train=0.0%, train_loss=3.074]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:30,  9.49it/s, test=0.0%, test_loss=1.821, train=0.0%, train_loss=1.842]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:34, 58.03it/s, test=0.0%, test_loss=1.821, train=0.0%, train_loss=1.842]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:34, 58.03it/s, test=0.0%, test_loss=1.194, train=0.0%, train_loss=1.186]

process_architecture/outcome:   1%|          | 15/2000 [00:00<00:34, 58.03it/s, test=0.0%, test_loss=1.138, train=0.0%, train_loss=1.137]

process_architecture/outcome:   1%|▏         | 28/2000 [00:00<00:23, 83.35it/s, test=0.0%, test_loss=1.138, train=0.0%, train_loss=1.137]

process_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:16, 119.12it/s, test=0.0%, test_loss=1.138, train=0.0%, train_loss=1.137]

process_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:16, 119.12it/s, test=6.6%, test_loss=0.924, train=4.0%, train_loss=0.929]

process_architecture/outcome:   3%|▎         | 63/2000 [00:00<00:14, 131.63it/s, test=6.6%, test_loss=0.924, train=4.0%, train_loss=0.929]

process_architecture/outcome:   3%|▎         | 63/2000 [00:00<00:14, 131.63it/s, test=6.5%, test_loss=0.929, train=8.7%, train_loss=0.943]

process_architecture/outcome:   4%|▍         | 79/2000 [00:00<00:13, 139.99it/s, test=6.5%, test_loss=0.929, train=8.7%, train_loss=0.943]

process_architecture/outcome:   5%|▍         | 98/2000 [00:00<00:12, 154.83it/s, test=6.5%, test_loss=0.929, train=8.7%, train_loss=0.943]

process_architecture/outcome:   5%|▍         | 98/2000 [00:00<00:12, 154.83it/s, test=10.0%, test_loss=0.911, train=10.0%, train_loss=0.922]

process_architecture/outcome:   6%|▌         | 115/2000 [00:00<00:12, 155.19it/s, test=10.0%, test_loss=0.911, train=10.0%, train_loss=0.922]

process_architecture/outcome:   7%|▋         | 134/2000 [00:01<00:11, 164.75it/s, test=10.0%, test_loss=0.911, train=10.0%, train_loss=0.922]

process_architecture/outcome:   7%|▋         | 134/2000 [00:01<00:11, 164.75it/s, test=11.1%, test_loss=0.904, train=8.0%, train_loss=0.905]

process_architecture/outcome:   8%|▊         | 151/2000 [00:01<00:11, 161.40it/s, test=11.1%, test_loss=0.904, train=8.0%, train_loss=0.905]

process_architecture/outcome:   8%|▊         | 170/2000 [00:01<00:10, 168.93it/s, test=11.1%, test_loss=0.904, train=8.0%, train_loss=0.905]

process_architecture/outcome:   9%|▉         | 189/2000 [00:01<00:10, 174.39it/s, test=11.1%, test_loss=0.904, train=8.0%, train_loss=0.905]

process_architecture/outcome:   9%|▉         | 189/2000 [00:01<00:10, 174.39it/s, test=11.7%, test_loss=0.901, train=10.3%, train_loss=0.897]

process_architecture/outcome:  10%|█         | 207/2000 [00:01<00:10, 168.41it/s, test=11.7%, test_loss=0.901, train=10.3%, train_loss=0.897]

process_architecture/outcome:  11%|█▏        | 226/2000 [00:01<00:10, 174.52it/s, test=11.7%, test_loss=0.901, train=10.3%, train_loss=0.897]

process_architecture/outcome:  12%|█▏        | 245/2000 [00:01<00:09, 178.85it/s, test=11.7%, test_loss=0.901, train=10.3%, train_loss=0.897]

process_architecture/outcome:  12%|█▏        | 245/2000 [00:01<00:09, 178.85it/s, test=9.9%, test_loss=0.886, train=8.0%, train_loss=0.879]

process_architecture/outcome:  13%|█▎        | 263/2000 [00:01<00:10, 172.01it/s, test=9.9%, test_loss=0.886, train=8.0%, train_loss=0.879]

process_architecture/outcome:  14%|█▍        | 282/2000 [00:01<00:09, 176.86it/s, test=9.9%, test_loss=0.886, train=8.0%, train_loss=0.879]

process_architecture/outcome:  14%|█▍        | 282/2000 [00:01<00:09, 176.86it/s, test=9.8%, test_loss=0.881, train=7.7%, train_loss=0.883]

process_architecture/outcome:  15%|█▌        | 300/2000 [00:01<00:09, 170.43it/s, test=9.8%, test_loss=0.881, train=7.7%, train_loss=0.883]

process_architecture/outcome:  16%|█▌        | 319/2000 [00:02<00:09, 175.10it/s, test=9.8%, test_loss=0.881, train=7.7%, train_loss=0.883]

process_architecture/outcome:  17%|█▋        | 338/2000 [00:02<00:09, 178.19it/s, test=9.8%, test_loss=0.881, train=7.7%, train_loss=0.883]

process_architecture/outcome:  17%|█▋        | 338/2000 [00:02<00:09, 178.19it/s, test=12.3%, test_loss=0.872, train=10.7%, train_loss=0.899]

process_architecture/outcome:  18%|█▊        | 356/2000 [00:02<00:09, 171.87it/s, test=12.3%, test_loss=0.872, train=10.7%, train_loss=0.899]

process_architecture/outcome:  19%|█▉        | 375/2000 [00:02<00:09, 176.61it/s, test=12.3%, test_loss=0.872, train=10.7%, train_loss=0.899]

process_architecture/outcome:  20%|█▉        | 394/2000 [00:02<00:08, 179.97it/s, test=12.3%, test_loss=0.872, train=10.7%, train_loss=0.899]

process_architecture/outcome:  20%|█▉        | 394/2000 [00:02<00:08, 179.97it/s, test=11.7%, test_loss=0.864, train=10.7%, train_loss=0.877]

process_architecture/outcome:  21%|██        | 413/2000 [00:02<00:09, 174.51it/s, test=11.7%, test_loss=0.864, train=10.7%, train_loss=0.877]

process_architecture/outcome:  22%|██▏       | 431/2000 [00:02<00:08, 175.10it/s, test=11.7%, test_loss=0.864, train=10.7%, train_loss=0.877]

process_architecture/outcome:  22%|██▏       | 431/2000 [00:02<00:08, 175.10it/s, test=11.8%, test_loss=0.853, train=13.7%, train_loss=0.850]

process_architecture/outcome:  22%|██▎       | 450/2000 [00:02<00:09, 170.95it/s, test=11.8%, test_loss=0.853, train=13.7%, train_loss=0.850]

process_architecture/outcome:  23%|██▎       | 469/2000 [00:02<00:08, 175.66it/s, test=11.8%, test_loss=0.853, train=13.7%, train_loss=0.850]

process_architecture/outcome:  24%|██▍       | 487/2000 [00:03<00:08, 176.54it/s, test=11.8%, test_loss=0.853, train=13.7%, train_loss=0.850]

process_architecture/outcome:  24%|██▍       | 487/2000 [00:03<00:08, 176.54it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.857]

process_architecture/outcome:  25%|██▌       | 505/2000 [00:03<00:08, 170.23it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.857]

process_architecture/outcome:  26%|██▌       | 524/2000 [00:03<00:08, 174.74it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.857]

process_architecture/outcome:  27%|██▋       | 542/2000 [00:03<00:08, 175.46it/s, test=14.4%, test_loss=0.854, train=15.3%, train_loss=0.857]

process_architecture/outcome:  27%|██▋       | 542/2000 [00:03<00:08, 175.46it/s, test=13.2%, test_loss=0.860, train=12.7%, train_loss=0.833]

process_architecture/outcome:  28%|██▊       | 560/2000 [00:03<00:08, 169.49it/s, test=13.2%, test_loss=0.860, train=12.7%, train_loss=0.833]

process_architecture/outcome:  29%|██▉       | 579/2000 [00:03<00:08, 174.31it/s, test=13.2%, test_loss=0.860, train=12.7%, train_loss=0.833]

process_architecture/outcome:  30%|██▉       | 597/2000 [00:03<00:07, 175.68it/s, test=13.2%, test_loss=0.860, train=12.7%, train_loss=0.833]

process_architecture/outcome:  30%|██▉       | 597/2000 [00:03<00:07, 175.68it/s, test=13.4%, test_loss=0.855, train=11.0%, train_loss=0.839]

process_architecture/outcome:  31%|███       | 615/2000 [00:03<00:08, 170.76it/s, test=13.4%, test_loss=0.855, train=11.0%, train_loss=0.839]

process_architecture/outcome:  32%|███▏      | 634/2000 [00:03<00:07, 174.66it/s, test=13.4%, test_loss=0.855, train=11.0%, train_loss=0.839]

process_architecture/outcome:  32%|███▏      | 634/2000 [00:04<00:07, 174.66it/s, test=15.2%, test_loss=0.838, train=13.3%, train_loss=0.832]

process_architecture/outcome:  33%|███▎      | 652/2000 [00:04<00:08, 166.02it/s, test=15.2%, test_loss=0.838, train=13.3%, train_loss=0.832]

process_architecture/outcome:  34%|███▎      | 671/2000 [00:04<00:07, 171.68it/s, test=15.2%, test_loss=0.838, train=13.3%, train_loss=0.832]

process_architecture/outcome:  34%|███▍      | 690/2000 [00:04<00:07, 176.25it/s, test=15.2%, test_loss=0.838, train=13.3%, train_loss=0.832]

process_architecture/outcome:  34%|███▍      | 690/2000 [00:04<00:07, 176.25it/s, test=15.3%, test_loss=0.810, train=14.3%, train_loss=0.818]

process_architecture/outcome:  35%|███▌      | 708/2000 [00:04<00:07, 168.46it/s, test=15.3%, test_loss=0.810, train=14.3%, train_loss=0.818]

process_architecture/outcome:  36%|███▋      | 728/2000 [00:04<00:07, 175.64it/s, test=15.3%, test_loss=0.810, train=14.3%, train_loss=0.818]

process_architecture/outcome:  37%|███▋      | 748/2000 [00:04<00:06, 180.95it/s, test=15.3%, test_loss=0.810, train=14.3%, train_loss=0.818]

process_architecture/outcome:  37%|███▋      | 748/2000 [00:04<00:06, 180.95it/s, test=16.8%, test_loss=0.841, train=17.7%, train_loss=0.793]

process_architecture/outcome:  38%|███▊      | 767/2000 [00:04<00:07, 175.51it/s, test=16.8%, test_loss=0.841, train=17.7%, train_loss=0.793]

process_architecture/outcome:  39%|███▉      | 787/2000 [00:04<00:06, 180.63it/s, test=16.8%, test_loss=0.841, train=17.7%, train_loss=0.793]

process_architecture/outcome:  39%|███▉      | 787/2000 [00:04<00:06, 180.63it/s, test=16.7%, test_loss=0.838, train=20.7%, train_loss=0.779]

process_architecture/outcome:  40%|████      | 806/2000 [00:04<00:06, 175.16it/s, test=16.7%, test_loss=0.838, train=20.7%, train_loss=0.779]

process_architecture/outcome:  41%|████▏     | 825/2000 [00:04<00:06, 178.16it/s, test=16.7%, test_loss=0.838, train=20.7%, train_loss=0.779]

process_architecture/outcome:  42%|████▏     | 844/2000 [00:05<00:06, 180.62it/s, test=16.7%, test_loss=0.838, train=20.7%, train_loss=0.779]

process_architecture/outcome:  42%|████▏     | 844/2000 [00:05<00:06, 180.62it/s, test=16.9%, test_loss=0.819, train=16.0%, train_loss=0.745]

process_architecture/outcome:  43%|████▎     | 863/2000 [00:05<00:06, 173.89it/s, test=16.9%, test_loss=0.819, train=16.0%, train_loss=0.745]

process_architecture/outcome:  44%|████▍     | 883/2000 [00:05<00:06, 178.65it/s, test=16.9%, test_loss=0.819, train=16.0%, train_loss=0.745]

process_architecture/outcome:  44%|████▍     | 883/2000 [00:05<00:06, 178.65it/s, test=17.3%, test_loss=0.835, train=19.3%, train_loss=0.784]

process_architecture/outcome:  45%|████▌     | 901/2000 [00:05<00:06, 173.33it/s, test=17.3%, test_loss=0.835, train=19.3%, train_loss=0.784]

process_architecture/outcome:  46%|████▌     | 920/2000 [00:05<00:06, 177.77it/s, test=17.3%, test_loss=0.835, train=19.3%, train_loss=0.784]

process_architecture/outcome:  47%|████▋     | 940/2000 [00:05<00:05, 182.14it/s, test=17.3%, test_loss=0.835, train=19.3%, train_loss=0.784]

process_architecture/outcome:  47%|████▋     | 940/2000 [00:05<00:05, 182.14it/s, test=19.5%, test_loss=0.856, train=20.0%, train_loss=0.768]

process_architecture/outcome:  48%|████▊     | 959/2000 [00:05<00:05, 176.04it/s, test=19.5%, test_loss=0.856, train=20.0%, train_loss=0.768]

process_architecture/outcome:  49%|████▉     | 980/2000 [00:05<00:05, 183.72it/s, test=19.5%, test_loss=0.856, train=20.0%, train_loss=0.768]

process_architecture/outcome:  49%|████▉     | 980/2000 [00:05<00:05, 183.72it/s, test=17.2%, test_loss=0.856, train=17.7%, train_loss=0.752]

process_architecture/outcome:  50%|█████     | 1000/2000 [00:05<00:05, 181.10it/s, test=17.2%, test_loss=0.856, train=17.7%, train_loss=0.752]

process_architecture/outcome:  51%|█████     | 1021/2000 [00:06<00:05, 187.89it/s, test=17.2%, test_loss=0.856, train=17.7%, train_loss=0.752]

process_architecture/outcome:  52%|█████▏    | 1041/2000 [00:06<00:05, 189.95it/s, test=17.2%, test_loss=0.856, train=17.7%, train_loss=0.752]

process_architecture/outcome:  52%|█████▏    | 1041/2000 [00:06<00:05, 189.95it/s, test=18.7%, test_loss=0.811, train=16.0%, train_loss=0.760]

process_architecture/outcome:  53%|█████▎    | 1061/2000 [00:06<00:05, 181.46it/s, test=18.7%, test_loss=0.811, train=16.0%, train_loss=0.760]

process_architecture/outcome:  54%|█████▍    | 1082/2000 [00:06<00:04, 188.81it/s, test=18.7%, test_loss=0.811, train=16.0%, train_loss=0.760]

process_architecture/outcome:  54%|█████▍    | 1082/2000 [00:06<00:04, 188.81it/s, test=22.2%, test_loss=0.771, train=22.7%, train_loss=0.720]

process_architecture/outcome:  55%|█████▌    | 1102/2000 [00:06<00:04, 184.37it/s, test=22.2%, test_loss=0.771, train=22.7%, train_loss=0.720]

process_architecture/outcome:  56%|█████▌    | 1123/2000 [00:06<00:04, 190.52it/s, test=22.2%, test_loss=0.771, train=22.7%, train_loss=0.720]

process_architecture/outcome:  57%|█████▋    | 1144/2000 [00:06<00:04, 194.63it/s, test=22.2%, test_loss=0.771, train=22.7%, train_loss=0.720]

process_architecture/outcome:  57%|█████▋    | 1144/2000 [00:06<00:04, 194.63it/s, test=22.0%, test_loss=0.774, train=19.7%, train_loss=0.701]

process_architecture/outcome:  58%|█████▊    | 1164/2000 [00:06<00:04, 188.82it/s, test=22.0%, test_loss=0.774, train=19.7%, train_loss=0.701]

process_architecture/outcome:  59%|█████▉    | 1185/2000 [00:06<00:04, 193.89it/s, test=22.0%, test_loss=0.774, train=19.7%, train_loss=0.701]

process_architecture/outcome:  59%|█████▉    | 1185/2000 [00:07<00:04, 193.89it/s, test=24.1%, test_loss=0.787, train=22.3%, train_loss=0.693]

process_architecture/outcome:  60%|██████    | 1205/2000 [00:07<00:04, 187.62it/s, test=24.1%, test_loss=0.787, train=22.3%, train_loss=0.693]

process_architecture/outcome:  61%|██████▏   | 1226/2000 [00:07<00:04, 192.48it/s, test=24.1%, test_loss=0.787, train=22.3%, train_loss=0.693]

process_architecture/outcome:  62%|██████▏   | 1247/2000 [00:07<00:03, 196.03it/s, test=24.1%, test_loss=0.787, train=22.3%, train_loss=0.693]

process_architecture/outcome:  62%|██████▏   | 1247/2000 [00:07<00:03, 196.03it/s, test=24.5%, test_loss=0.750, train=23.0%, train_loss=0.718]

process_architecture/outcome:  63%|██████▎   | 1267/2000 [00:07<00:03, 189.70it/s, test=24.5%, test_loss=0.750, train=23.0%, train_loss=0.718]

process_architecture/outcome:  64%|██████▍   | 1287/2000 [00:07<00:03, 190.55it/s, test=24.5%, test_loss=0.750, train=23.0%, train_loss=0.718]

process_architecture/outcome:  64%|██████▍   | 1287/2000 [00:07<00:03, 190.55it/s, test=26.3%, test_loss=0.713, train=25.7%, train_loss=0.660]

process_architecture/outcome:  65%|██████▌   | 1307/2000 [00:07<00:03, 185.32it/s, test=26.3%, test_loss=0.713, train=25.7%, train_loss=0.660]

process_architecture/outcome:  66%|██████▋   | 1328/2000 [00:07<00:03, 190.06it/s, test=26.3%, test_loss=0.713, train=25.7%, train_loss=0.660]

process_architecture/outcome:  67%|██████▋   | 1349/2000 [00:07<00:03, 194.50it/s, test=26.3%, test_loss=0.713, train=25.7%, train_loss=0.660]

process_architecture/outcome:  67%|██████▋   | 1349/2000 [00:07<00:03, 194.50it/s, test=27.8%, test_loss=0.712, train=30.3%, train_loss=0.630]

process_architecture/outcome:  68%|██████▊   | 1369/2000 [00:07<00:03, 187.96it/s, test=27.8%, test_loss=0.712, train=30.3%, train_loss=0.630]

process_architecture/outcome:  70%|██████▉   | 1390/2000 [00:08<00:03, 192.54it/s, test=27.8%, test_loss=0.712, train=30.3%, train_loss=0.630]

process_architecture/outcome:  70%|██████▉   | 1390/2000 [00:08<00:03, 192.54it/s, test=26.8%, test_loss=0.731, train=26.7%, train_loss=0.676]

process_architecture/outcome:  70%|███████   | 1410/2000 [00:08<00:03, 186.37it/s, test=26.8%, test_loss=0.731, train=26.7%, train_loss=0.676]

process_architecture/outcome:  72%|███████▏  | 1431/2000 [00:08<00:02, 191.73it/s, test=26.8%, test_loss=0.731, train=26.7%, train_loss=0.676]

process_architecture/outcome:  72%|███████▏  | 1431/2000 [00:08<00:02, 191.73it/s, test=29.5%, test_loss=0.694, train=30.0%, train_loss=0.621]

process_architecture/outcome:  73%|███████▎  | 1451/2000 [00:08<00:02, 186.47it/s, test=29.5%, test_loss=0.694, train=30.0%, train_loss=0.621]

process_architecture/outcome:  74%|███████▎  | 1472/2000 [00:08<00:02, 191.97it/s, test=29.5%, test_loss=0.694, train=30.0%, train_loss=0.621]

process_architecture/outcome:  75%|███████▍  | 1493/2000 [00:08<00:02, 195.55it/s, test=29.5%, test_loss=0.694, train=30.0%, train_loss=0.621]

process_architecture/outcome:  75%|███████▍  | 1493/2000 [00:08<00:02, 195.55it/s, test=27.6%, test_loss=0.683, train=31.3%, train_loss=0.624]

process_architecture/outcome:  76%|███████▌  | 1513/2000 [00:08<00:02, 188.25it/s, test=27.6%, test_loss=0.683, train=31.3%, train_loss=0.624]

process_architecture/outcome:  77%|███████▋  | 1534/2000 [00:08<00:02, 193.00it/s, test=27.6%, test_loss=0.683, train=31.3%, train_loss=0.624]

process_architecture/outcome:  77%|███████▋  | 1534/2000 [00:08<00:02, 193.00it/s, test=29.7%, test_loss=0.691, train=36.3%, train_loss=0.640]

process_architecture/outcome:  78%|███████▊  | 1554/2000 [00:08<00:02, 187.01it/s, test=29.7%, test_loss=0.691, train=36.3%, train_loss=0.640]

process_architecture/outcome:  79%|███████▉  | 1575/2000 [00:08<00:02, 192.47it/s, test=29.7%, test_loss=0.691, train=36.3%, train_loss=0.640]

process_architecture/outcome:  80%|███████▉  | 1596/2000 [00:09<00:02, 195.72it/s, test=29.7%, test_loss=0.691, train=36.3%, train_loss=0.640]

process_architecture/outcome:  80%|███████▉  | 1596/2000 [00:09<00:02, 195.72it/s, test=28.2%, test_loss=0.688, train=33.0%, train_loss=0.582]

process_architecture/outcome:  81%|████████  | 1616/2000 [00:09<00:02, 188.86it/s, test=28.2%, test_loss=0.688, train=33.0%, train_loss=0.582]

process_architecture/outcome:  82%|████████▏ | 1637/2000 [00:09<00:01, 193.41it/s, test=28.2%, test_loss=0.688, train=33.0%, train_loss=0.582]

process_architecture/outcome:  82%|████████▏ | 1637/2000 [00:09<00:01, 193.41it/s, test=29.0%, test_loss=0.675, train=33.0%, train_loss=0.635]

process_architecture/outcome:  83%|████████▎ | 1657/2000 [00:09<00:01, 187.40it/s, test=29.0%, test_loss=0.675, train=33.0%, train_loss=0.635]

process_architecture/outcome:  84%|████████▍ | 1678/2000 [00:09<00:01, 192.23it/s, test=29.0%, test_loss=0.675, train=33.0%, train_loss=0.635]

process_architecture/outcome:  85%|████████▍ | 1699/2000 [00:09<00:01, 195.41it/s, test=29.0%, test_loss=0.675, train=33.0%, train_loss=0.635]

process_architecture/outcome:  85%|████████▍ | 1699/2000 [00:09<00:01, 195.41it/s, test=30.8%, test_loss=0.666, train=34.7%, train_loss=0.565]

process_architecture/outcome:  86%|████████▌ | 1719/2000 [00:09<00:01, 188.68it/s, test=30.8%, test_loss=0.666, train=34.7%, train_loss=0.565]

process_architecture/outcome:  87%|████████▋ | 1740/2000 [00:09<00:01, 193.44it/s, test=30.8%, test_loss=0.666, train=34.7%, train_loss=0.565]

process_architecture/outcome:  87%|████████▋ | 1740/2000 [00:09<00:01, 193.44it/s, test=30.3%, test_loss=0.662, train=35.7%, train_loss=0.596]

process_architecture/outcome:  88%|████████▊ | 1760/2000 [00:09<00:01, 187.32it/s, test=30.3%, test_loss=0.662, train=35.7%, train_loss=0.596]

process_architecture/outcome:  89%|████████▉ | 1781/2000 [00:10<00:01, 192.49it/s, test=30.3%, test_loss=0.662, train=35.7%, train_loss=0.596]

process_architecture/outcome:  89%|████████▉ | 1781/2000 [00:10<00:01, 192.49it/s, test=32.4%, test_loss=0.658, train=33.7%, train_loss=0.611]

process_architecture/outcome:  90%|█████████ | 1801/2000 [00:10<00:01, 186.43it/s, test=32.4%, test_loss=0.658, train=33.7%, train_loss=0.611]

process_architecture/outcome:  91%|█████████ | 1822/2000 [00:10<00:00, 191.81it/s, test=32.4%, test_loss=0.658, train=33.7%, train_loss=0.611]

process_architecture/outcome:  92%|█████████▏| 1843/2000 [00:10<00:00, 195.71it/s, test=32.4%, test_loss=0.658, train=33.7%, train_loss=0.611]

process_architecture/outcome:  92%|█████████▏| 1843/2000 [00:10<00:00, 195.71it/s, test=31.0%, test_loss=0.615, train=37.3%, train_loss=0.553]

process_architecture/outcome:  93%|█████████▎| 1863/2000 [00:10<00:00, 189.04it/s, test=31.0%, test_loss=0.615, train=37.3%, train_loss=0.553]

process_architecture/outcome:  94%|█████████▍| 1884/2000 [00:10<00:00, 193.56it/s, test=31.0%, test_loss=0.615, train=37.3%, train_loss=0.553]

process_architecture/outcome:  94%|█████████▍| 1884/2000 [00:10<00:00, 193.56it/s, test=33.0%, test_loss=0.655, train=34.0%, train_loss=0.567]

process_architecture/outcome:  95%|█████████▌| 1904/2000 [00:10<00:00, 187.04it/s, test=33.0%, test_loss=0.655, train=34.0%, train_loss=0.567]

process_architecture/outcome:  96%|█████████▋| 1925/2000 [00:10<00:00, 191.99it/s, test=33.0%, test_loss=0.655, train=34.0%, train_loss=0.567]

process_architecture/outcome:  97%|█████████▋| 1946/2000 [00:10<00:00, 195.64it/s, test=33.0%, test_loss=0.655, train=34.0%, train_loss=0.567]

process_architecture/outcome:  97%|█████████▋| 1946/2000 [00:10<00:00, 195.64it/s, test=30.9%, test_loss=0.635, train=34.0%, train_loss=0.547]

process_architecture/outcome:  98%|█████████▊| 1966/2000 [00:11<00:00, 188.76it/s, test=30.9%, test_loss=0.635, train=34.0%, train_loss=0.547]

process_architecture/outcome:  99%|█████████▉| 1987/2000 [00:11<00:00, 193.48it/s, test=30.9%, test_loss=0.635, train=34.0%, train_loss=0.547]

process_architecture/outcome:  99%|█████████▉| 1987/2000 [00:11<00:00, 193.48it/s, test=31.3%, test_loss=0.626, train=36.7%, train_loss=0.577]

process_architecture/outcome: 100%|██████████| 2000/2000 [00:11<00:00, 178.46it/s, test=31.3%, test_loss=0.626, train=36.7%, train_loss=0.577]

architecture/mode:  25%|██▌       | 1/4 [00:11<00:33, 11.23s/it]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=7.0%, test_loss=4.260, train=8.7%, train_loss=4.260]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.235, train=0.0%, train_loss=4.236]

process_architecture/process:   0%|          | 2/2000 [00:00<01:55, 17.27it/s, test=0.0%, test_loss=4.235, train=0.0%, train_loss=4.236]

process_architecture/process:   0%|          | 2/2000 [00:00<01:55, 17.27it/s, test=0.0%, test_loss=3.907, train=0.0%, train_loss=3.919]

process_architecture/process:   0%|          | 2/2000 [00:00<01:55, 17.27it/s, test=0.0%, test_loss=3.650, train=0.0%, train_loss=3.664]

process_architecture/process:   0%|          | 10/2000 [00:00<00:38, 51.16it/s, test=0.0%, test_loss=3.650, train=0.0%, train_loss=3.664]

process_architecture/process:   0%|          | 10/2000 [00:00<00:38, 51.16it/s, test=0.0%, test_loss=3.034, train=0.0%, train_loss=3.026]

process_architecture/process:   1%|          | 20/2000 [00:00<00:27, 72.10it/s, test=0.0%, test_loss=3.034, train=0.0%, train_loss=3.026]

process_architecture/process:   1%|          | 20/2000 [00:00<00:27, 72.10it/s, test=6.5%, test_loss=2.813, train=8.7%, train_loss=2.826]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:24, 81.90it/s, test=6.5%, test_loss=2.813, train=8.7%, train_loss=2.826]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:24, 81.90it/s, test=6.7%, test_loss=2.617, train=5.3%, train_loss=2.647]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:18, 104.69it/s, test=6.7%, test_loss=2.617, train=5.3%, train_loss=2.647]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:14, 135.19it/s, test=6.7%, test_loss=2.617, train=5.3%, train_loss=2.647]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:14, 135.19it/s, test=11.5%, test_loss=2.437, train=10.3%, train_loss=2.426]

process_architecture/process:   4%|▍         | 85/2000 [00:00<00:14, 128.37it/s, test=11.5%, test_loss=2.437, train=10.3%, train_loss=2.426]

process_architecture/process:   4%|▍         | 85/2000 [00:00<00:14, 128.37it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   5%|▌         | 100/2000 [00:00<00:15, 124.92it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   6%|▌         | 121/2000 [00:01<00:12, 147.47it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 163.91it/s, test=14.5%, test_loss=2.306, train=10.3%, train_loss=2.302]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 163.91it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:   8%|▊         | 159/2000 [00:01<00:12, 150.40it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:   9%|▉         | 180/2000 [00:01<00:10, 165.73it/s, test=11.9%, test_loss=1.978, train=12.0%, train_loss=1.973]

process_architecture/process:   9%|▉         | 180/2000 [00:01<00:10, 165.73it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  10%|█         | 200/2000 [00:01<00:11, 153.23it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  11%|█         | 221/2000 [00:01<00:10, 166.81it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  12%|█▏        | 242/2000 [00:01<00:09, 177.60it/s, test=16.2%, test_loss=0.906, train=15.0%, train_loss=0.926]

process_architecture/process:  12%|█▏        | 242/2000 [00:01<00:09, 177.60it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  13%|█▎        | 261/2000 [00:01<00:10, 160.57it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  14%|█▍        | 282/2000 [00:01<00:09, 172.58it/s, test=41.4%, test_loss=0.203, train=42.3%, train_loss=0.219]

process_architecture/process:  14%|█▍        | 282/2000 [00:02<00:09, 172.58it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  15%|█▌        | 300/2000 [00:02<00:10, 157.17it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  16%|█▌        | 320/2000 [00:02<00:10, 167.69it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  17%|█▋        | 341/2000 [00:02<00:09, 178.05it/s, test=71.2%, test_loss=0.072, train=72.0%, train_loss=0.076]

process_architecture/process:  17%|█▋        | 341/2000 [00:02<00:09, 178.05it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  18%|█▊        | 360/2000 [00:02<00:10, 160.32it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  19%|█▉        | 381/2000 [00:02<00:09, 171.47it/s, test=95.1%, test_loss=0.023, train=94.7%, train_loss=0.025]

process_architecture/process:  19%|█▉        | 381/2000 [00:02<00:09, 171.47it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  20%|██        | 400/2000 [00:02<00:10, 157.23it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  21%|██        | 420/2000 [00:02<00:09, 168.00it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  22%|██▏       | 441/2000 [00:02<00:08, 177.16it/s, test=99.3%, test_loss=0.006, train=99.7%, train_loss=0.006]

process_architecture/process:  22%|██▏       | 441/2000 [00:03<00:08, 177.16it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  23%|██▎       | 460/2000 [00:03<00:09, 159.77it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  24%|██▍       | 481/2000 [00:03<00:08, 170.72it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  24%|██▍       | 481/2000 [00:03<00:08, 170.72it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  25%|██▌       | 500/2000 [00:03<00:09, 156.17it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  26%|██▌       | 520/2000 [00:03<00:08, 167.22it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 541/2000 [00:03<00:08, 177.81it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 541/2000 [00:03<00:08, 177.81it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  28%|██▊       | 560/2000 [00:03<00:08, 160.21it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 581/2000 [00:03<00:08, 171.05it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  29%|██▉       | 581/2000 [00:03<00:08, 171.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  30%|███       | 600/2000 [00:03<00:08, 157.02it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  31%|███       | 621/2000 [00:04<00:08, 169.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 642/2000 [00:04<00:07, 179.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 642/2000 [00:04<00:07, 179.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  33%|███▎      | 661/2000 [00:04<00:08, 162.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 682/2000 [00:04<00:07, 173.82it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 682/2000 [00:04<00:07, 173.82it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▌      | 701/2000 [00:04<00:08, 158.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 722/2000 [00:04<00:07, 169.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 743/2000 [00:04<00:07, 179.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 743/2000 [00:04<00:07, 179.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 762/2000 [00:04<00:07, 161.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 782/2000 [00:04<00:07, 170.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 782/2000 [00:05<00:07, 170.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|████      | 800/2000 [00:05<00:07, 155.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 820/2000 [00:05<00:07, 166.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 840/2000 [00:05<00:06, 175.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 840/2000 [00:05<00:06, 175.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  43%|████▎     | 859/2000 [00:05<00:07, 157.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 879/2000 [00:05<00:06, 168.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 879/2000 [00:05<00:06, 168.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 900/2000 [00:05<00:07, 155.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 921/2000 [00:05<00:06, 167.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 942/2000 [00:05<00:06, 176.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 942/2000 [00:06<00:06, 176.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 961/2000 [00:06<00:06, 159.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 981/2000 [00:06<00:06, 169.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 981/2000 [00:06<00:06, 169.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1000/2000 [00:06<00:06, 155.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1021/2000 [00:06<00:05, 167.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1039/2000 [00:06<00:05, 169.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1039/2000 [00:06<00:05, 169.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1057/2000 [00:06<00:06, 150.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1078/2000 [00:06<00:05, 165.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1078/2000 [00:06<00:05, 165.18it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1100/2000 [00:06<00:05, 155.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1121/2000 [00:07<00:05, 168.39it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1142/2000 [00:07<00:04, 178.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1142/2000 [00:07<00:04, 178.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1161/2000 [00:07<00:05, 161.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1182/2000 [00:07<00:04, 173.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1182/2000 [00:07<00:04, 173.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1200/2000 [00:07<00:05, 157.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1221/2000 [00:07<00:04, 169.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1242/2000 [00:07<00:04, 179.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1242/2000 [00:07<00:04, 179.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1261/2000 [00:07<00:04, 162.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1282/2000 [00:07<00:04, 173.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1282/2000 [00:08<00:04, 173.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▌   | 1301/2000 [00:08<00:04, 158.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1322/2000 [00:08<00:03, 170.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1343/2000 [00:08<00:03, 180.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1343/2000 [00:08<00:03, 180.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1362/2000 [00:08<00:03, 162.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1383/2000 [00:08<00:03, 174.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1383/2000 [00:08<00:03, 174.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1402/2000 [00:08<00:03, 158.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████   | 1423/2000 [00:08<00:03, 171.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1444/2000 [00:08<00:03, 180.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1444/2000 [00:09<00:03, 180.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1463/2000 [00:09<00:03, 163.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1484/2000 [00:09<00:02, 174.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1484/2000 [00:09<00:02, 174.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1503/2000 [00:09<00:03, 159.19it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1524/2000 [00:09<00:02, 171.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1545/2000 [00:09<00:02, 181.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1545/2000 [00:09<00:02, 181.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1564/2000 [00:09<00:02, 163.19it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1585/2000 [00:09<00:02, 173.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1585/2000 [00:09<00:02, 173.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1603/2000 [00:09<00:02, 155.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1623/2000 [00:10<00:02, 166.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1643/2000 [00:10<00:02, 175.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1643/2000 [00:10<00:02, 175.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1662/2000 [00:10<00:02, 157.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1682/2000 [00:10<00:01, 168.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1682/2000 [00:10<00:01, 168.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▌ | 1700/2000 [00:10<00:01, 153.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1720/2000 [00:10<00:01, 165.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1741/2000 [00:10<00:01, 175.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1741/2000 [00:10<00:01, 175.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1760/2000 [00:10<00:01, 158.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1780/2000 [00:10<00:01, 168.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1780/2000 [00:11<00:01, 168.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|█████████ | 1800/2000 [00:11<00:01, 154.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1821/2000 [00:11<00:01, 167.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1841/2000 [00:11<00:00, 176.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1841/2000 [00:11<00:00, 176.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1860/2000 [00:11<00:00, 160.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1881/2000 [00:11<00:00, 170.89it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1881/2000 [00:11<00:00, 170.89it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▌| 1900/2000 [00:11<00:00, 155.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1921/2000 [00:11<00:00, 168.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1942/2000 [00:11<00:00, 178.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1942/2000 [00:12<00:00, 178.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1961/2000 [00:12<00:00, 160.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1982/2000 [00:12<00:00, 172.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1982/2000 [00:12<00:00, 172.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 157.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 162.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode:  50%|█████     | 2/4 [00:23<00:23, 11.90s/it]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.588, train=0.0%, train_loss=3.584]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=10.187, train=0.0%, train_loss=10.065]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:52, 38.31it/s, test=0.0%, test_loss=10.187, train=0.0%, train_loss=10.065]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:52, 38.31it/s, test=0.0%, test_loss=3.159, train=0.0%, train_loss=3.158]

outcome_architecture/outcome:   0%|          | 4/2000 [00:00<00:52, 38.31it/s, test=0.0%, test_loss=1.261, train=0.0%, train_loss=1.251]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:44, 45.14it/s, test=0.0%, test_loss=1.261, train=0.0%, train_loss=1.251]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:44, 45.14it/s, test=5.2%, test_loss=0.943, train=7.3%, train_loss=0.960]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 61.01it/s, test=5.2%, test_loss=0.943, train=7.3%, train_loss=0.960]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 61.01it/s, test=6.5%, test_loss=0.934, train=8.7%, train_loss=0.952]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:30, 63.99it/s, test=6.5%, test_loss=0.934, train=8.7%, train_loss=0.952]

outcome_architecture/outcome:   2%|▏         | 38/2000 [00:00<00:24, 78.95it/s, test=6.5%, test_loss=0.934, train=8.7%, train_loss=0.952]

outcome_architecture/outcome:   2%|▏         | 48/2000 [00:00<00:22, 85.37it/s, test=6.5%, test_loss=0.934, train=8.7%, train_loss=0.952]

outcome_architecture/outcome:   2%|▏         | 48/2000 [00:00<00:22, 85.37it/s, test=0.0%, test_loss=182.795, train=0.0%, train_loss=190.686]

outcome_architecture/outcome:   3%|▎         | 57/2000 [00:00<00:22, 86.11it/s, test=0.0%, test_loss=182.795, train=0.0%, train_loss=190.686]

outcome_architecture/outcome:   3%|▎         | 68/2000 [00:00<00:20, 92.93it/s, test=0.0%, test_loss=182.795, train=0.0%, train_loss=190.686]

outcome_architecture/outcome:   3%|▎         | 68/2000 [00:00<00:20, 92.93it/s, test=0.0%, test_loss=98.744, train=0.0%, train_loss=95.902]

outcome_architecture/outcome:   4%|▍         | 78/2000 [00:00<00:21, 87.61it/s, test=0.0%, test_loss=98.744, train=0.0%, train_loss=95.902]

outcome_architecture/outcome:   4%|▍         | 89/2000 [00:01<00:20, 93.71it/s, test=0.0%, test_loss=98.744, train=0.0%, train_loss=95.902]

outcome_architecture/outcome:   4%|▍         | 89/2000 [00:01<00:20, 93.71it/s, test=0.0%, test_loss=6.861, train=0.0%, train_loss=5.561]

outcome_architecture/outcome:   5%|▌         | 100/2000 [00:01<00:21, 89.08it/s, test=0.0%, test_loss=6.861, train=0.0%, train_loss=5.561]

outcome_architecture/outcome:   6%|▌         | 111/2000 [00:01<00:19, 94.65it/s, test=0.0%, test_loss=6.861, train=0.0%, train_loss=5.561]

outcome_architecture/outcome:   6%|▌         | 122/2000 [00:01<00:19, 98.61it/s, test=0.0%, test_loss=6.861, train=0.0%, train_loss=5.561]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:18, 101.52it/s, test=0.0%, test_loss=6.861, train=0.0%, train_loss=5.561]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:17, 103.67it/s, test=0.0%, test_loss=6.861, train=0.0%, train_loss=5.561]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:17, 103.67it/s, test=2.6%, test_loss=1.195, train=1.3%, train_loss=1.164]

outcome_architecture/outcome:   8%|▊         | 155/2000 [00:01<00:19, 95.19it/s, test=2.6%, test_loss=1.195, train=1.3%, train_loss=1.164]

outcome_architecture/outcome:   8%|▊         | 166/2000 [00:01<00:18, 98.91it/s, test=2.6%, test_loss=1.195, train=1.3%, train_loss=1.164]

outcome_architecture/outcome:   9%|▉         | 177/2000 [00:01<00:17, 101.50it/s, test=2.6%, test_loss=1.195, train=1.3%, train_loss=1.164]

outcome_architecture/outcome:   9%|▉         | 188/2000 [00:02<00:17, 103.72it/s, test=2.6%, test_loss=1.195, train=1.3%, train_loss=1.164]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 105.32it/s, test=2.6%, test_loss=1.195, train=1.3%, train_loss=1.164]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 105.32it/s, test=8.2%, test_loss=0.968, train=8.0%, train_loss=0.959]

outcome_architecture/outcome:  10%|█         | 210/2000 [00:02<00:18, 96.35it/s, test=8.2%, test_loss=0.968, train=8.0%, train_loss=0.959]

outcome_architecture/outcome:  11%|█         | 221/2000 [00:02<00:17, 99.79it/s, test=8.2%, test_loss=0.968, train=8.0%, train_loss=0.959]

outcome_architecture/outcome:  12%|█▏        | 232/2000 [00:02<00:17, 102.25it/s, test=8.2%, test_loss=0.968, train=8.0%, train_loss=0.959]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:16, 104.09it/s, test=8.2%, test_loss=0.968, train=8.0%, train_loss=0.959]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:16, 104.09it/s, test=9.9%, test_loss=0.951, train=9.7%, train_loss=0.940]

outcome_architecture/outcome:  13%|█▎        | 254/2000 [00:02<00:18, 95.28it/s, test=9.9%, test_loss=0.951, train=9.7%, train_loss=0.940]

outcome_architecture/outcome:  13%|█▎        | 265/2000 [00:02<00:17, 98.96it/s, test=9.9%, test_loss=0.951, train=9.7%, train_loss=0.940]

outcome_architecture/outcome:  14%|█▍        | 276/2000 [00:02<00:16, 101.71it/s, test=9.9%, test_loss=0.951, train=9.7%, train_loss=0.940]

outcome_architecture/outcome:  14%|█▍        | 287/2000 [00:03<00:16, 103.63it/s, test=9.9%, test_loss=0.951, train=9.7%, train_loss=0.940]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 105.14it/s, test=9.9%, test_loss=0.951, train=9.7%, train_loss=0.940]

outcome_architecture/outcome:  15%|█▍        | 298/2000 [00:03<00:16, 105.14it/s, test=11.5%, test_loss=0.921, train=5.7%, train_loss=0.915]

outcome_architecture/outcome:  15%|█▌        | 309/2000 [00:03<00:17, 96.15it/s, test=11.5%, test_loss=0.921, train=5.7%, train_loss=0.915]

outcome_architecture/outcome:  16%|█▌        | 320/2000 [00:03<00:16, 99.61it/s, test=11.5%, test_loss=0.921, train=5.7%, train_loss=0.915]

outcome_architecture/outcome:  17%|█▋        | 331/2000 [00:03<00:16, 102.16it/s, test=11.5%, test_loss=0.921, train=5.7%, train_loss=0.915]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:15, 104.11it/s, test=11.5%, test_loss=0.921, train=5.7%, train_loss=0.915]

outcome_architecture/outcome:  17%|█▋        | 342/2000 [00:03<00:15, 104.11it/s, test=11.2%, test_loss=0.905, train=11.0%, train_loss=0.928]

outcome_architecture/outcome:  18%|█▊        | 353/2000 [00:03<00:17, 95.60it/s, test=11.2%, test_loss=0.905, train=11.0%, train_loss=0.928]

outcome_architecture/outcome:  18%|█▊        | 364/2000 [00:03<00:16, 99.28it/s, test=11.2%, test_loss=0.905, train=11.0%, train_loss=0.928]

outcome_architecture/outcome:  19%|█▉        | 375/2000 [00:03<00:15, 101.96it/s, test=11.2%, test_loss=0.905, train=11.0%, train_loss=0.928]

outcome_architecture/outcome:  19%|█▉        | 386/2000 [00:04<00:15, 103.84it/s, test=11.2%, test_loss=0.905, train=11.0%, train_loss=0.928]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 102.67it/s, test=11.2%, test_loss=0.905, train=11.0%, train_loss=0.928]

outcome_architecture/outcome:  20%|█▉        | 397/2000 [00:04<00:15, 102.67it/s, test=11.2%, test_loss=0.914, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  20%|██        | 408/2000 [00:04<00:16, 93.66it/s, test=11.2%, test_loss=0.914, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  21%|██        | 419/2000 [00:04<00:16, 97.16it/s, test=11.2%, test_loss=0.914, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  22%|██▏       | 430/2000 [00:04<00:15, 99.75it/s, test=11.2%, test_loss=0.914, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 101.67it/s, test=11.2%, test_loss=0.914, train=9.0%, train_loss=0.948]

outcome_architecture/outcome:  22%|██▏       | 441/2000 [00:04<00:15, 101.67it/s, test=13.2%, test_loss=0.924, train=11.3%, train_loss=0.951]

outcome_architecture/outcome:  23%|██▎       | 452/2000 [00:04<00:16, 93.27it/s, test=13.2%, test_loss=0.924, train=11.3%, train_loss=0.951]

outcome_architecture/outcome:  23%|██▎       | 463/2000 [00:04<00:15, 96.80it/s, test=13.2%, test_loss=0.924, train=11.3%, train_loss=0.951]

outcome_architecture/outcome:  24%|██▎       | 474/2000 [00:04<00:15, 99.50it/s, test=13.2%, test_loss=0.924, train=11.3%, train_loss=0.951]

outcome_architecture/outcome:  24%|██▍       | 485/2000 [00:05<00:14, 101.50it/s, test=13.2%, test_loss=0.924, train=11.3%, train_loss=0.951]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 102.80it/s, test=13.2%, test_loss=0.924, train=11.3%, train_loss=0.951]

outcome_architecture/outcome:  25%|██▍       | 496/2000 [00:05<00:14, 102.80it/s, test=10.8%, test_loss=0.928, train=11.3%, train_loss=0.932]

outcome_architecture/outcome:  25%|██▌       | 507/2000 [00:05<00:15, 94.25it/s, test=10.8%, test_loss=0.928, train=11.3%, train_loss=0.932]

outcome_architecture/outcome:  26%|██▌       | 518/2000 [00:05<00:15, 97.22it/s, test=10.8%, test_loss=0.928, train=11.3%, train_loss=0.932]

outcome_architecture/outcome:  26%|██▋       | 529/2000 [00:05<00:14, 99.86it/s, test=10.8%, test_loss=0.928, train=11.3%, train_loss=0.932]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 101.80it/s, test=10.8%, test_loss=0.928, train=11.3%, train_loss=0.932]

outcome_architecture/outcome:  27%|██▋       | 540/2000 [00:05<00:14, 101.80it/s, test=11.1%, test_loss=0.922, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  28%|██▊       | 551/2000 [00:05<00:15, 91.38it/s, test=11.1%, test_loss=0.922, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  28%|██▊       | 562/2000 [00:05<00:15, 95.41it/s, test=11.1%, test_loss=0.922, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  29%|██▊       | 573/2000 [00:05<00:14, 98.41it/s, test=11.1%, test_loss=0.922, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  29%|██▉       | 584/2000 [00:06<00:14, 98.61it/s, test=11.1%, test_loss=0.922, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 100.72it/s, test=11.1%, test_loss=0.922, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  30%|██▉       | 595/2000 [00:06<00:13, 100.72it/s, test=13.3%, test_loss=0.920, train=9.7%, train_loss=0.942]

outcome_architecture/outcome:  30%|███       | 606/2000 [00:06<00:15, 90.88it/s, test=13.3%, test_loss=0.920, train=9.7%, train_loss=0.942]

outcome_architecture/outcome:  31%|███       | 617/2000 [00:06<00:14, 95.02it/s, test=13.3%, test_loss=0.920, train=9.7%, train_loss=0.942]

outcome_architecture/outcome:  31%|███▏      | 628/2000 [00:06<00:13, 98.16it/s, test=13.3%, test_loss=0.920, train=9.7%, train_loss=0.942]

outcome_architecture/outcome:  32%|███▏      | 639/2000 [00:06<00:13, 98.06it/s, test=13.3%, test_loss=0.920, train=9.7%, train_loss=0.942]

outcome_architecture/outcome:  32%|███▏      | 649/2000 [00:06<00:13, 96.87it/s, test=13.3%, test_loss=0.920, train=9.7%, train_loss=0.942]

outcome_architecture/outcome:  32%|███▏      | 649/2000 [00:06<00:13, 96.87it/s, test=11.6%, test_loss=0.919, train=6.7%, train_loss=0.930]

outcome_architecture/outcome:  33%|███▎      | 659/2000 [00:06<00:14, 89.45it/s, test=11.6%, test_loss=0.919, train=6.7%, train_loss=0.930]

outcome_architecture/outcome:  33%|███▎      | 669/2000 [00:06<00:14, 92.08it/s, test=11.6%, test_loss=0.919, train=6.7%, train_loss=0.930]

outcome_architecture/outcome:  34%|███▍      | 680/2000 [00:07<00:13, 96.60it/s, test=11.6%, test_loss=0.919, train=6.7%, train_loss=0.930]

outcome_architecture/outcome:  35%|███▍      | 691/2000 [00:07<00:13, 99.90it/s, test=11.6%, test_loss=0.919, train=6.7%, train_loss=0.930]

outcome_architecture/outcome:  35%|███▍      | 691/2000 [00:07<00:13, 99.90it/s, test=12.5%, test_loss=0.898, train=11.0%, train_loss=0.915]

outcome_architecture/outcome:  35%|███▌      | 702/2000 [00:07<00:14, 90.88it/s, test=12.5%, test_loss=0.898, train=11.0%, train_loss=0.915]

outcome_architecture/outcome:  36%|███▌      | 713/2000 [00:07<00:13, 95.63it/s, test=12.5%, test_loss=0.898, train=11.0%, train_loss=0.915]

outcome_architecture/outcome:  36%|███▌      | 724/2000 [00:07<00:12, 99.03it/s, test=12.5%, test_loss=0.898, train=11.0%, train_loss=0.915]

outcome_architecture/outcome:  37%|███▋      | 735/2000 [00:07<00:12, 99.06it/s, test=12.5%, test_loss=0.898, train=11.0%, train_loss=0.915]

outcome_architecture/outcome:  37%|███▋      | 746/2000 [00:07<00:12, 101.69it/s, test=12.5%, test_loss=0.898, train=11.0%, train_loss=0.915]

outcome_architecture/outcome:  37%|███▋      | 746/2000 [00:07<00:12, 101.69it/s, test=12.1%, test_loss=0.918, train=13.0%, train_loss=0.918]

outcome_architecture/outcome:  38%|███▊      | 757/2000 [00:07<00:13, 93.81it/s, test=12.1%, test_loss=0.918, train=13.0%, train_loss=0.918]

outcome_architecture/outcome:  38%|███▊      | 767/2000 [00:07<00:12, 95.05it/s, test=12.1%, test_loss=0.918, train=13.0%, train_loss=0.918]

outcome_architecture/outcome:  39%|███▉      | 778/2000 [00:08<00:12, 98.42it/s, test=12.1%, test_loss=0.918, train=13.0%, train_loss=0.918]

outcome_architecture/outcome:  39%|███▉      | 789/2000 [00:08<00:12, 100.83it/s, test=12.1%, test_loss=0.918, train=13.0%, train_loss=0.918]

outcome_architecture/outcome:  39%|███▉      | 789/2000 [00:08<00:12, 100.83it/s, test=12.6%, test_loss=0.911, train=11.7%, train_loss=0.925]

outcome_architecture/outcome:  40%|████      | 800/2000 [00:08<00:13, 91.34it/s, test=12.6%, test_loss=0.911, train=11.7%, train_loss=0.925]

outcome_architecture/outcome:  41%|████      | 811/2000 [00:08<00:12, 95.36it/s, test=12.6%, test_loss=0.911, train=11.7%, train_loss=0.925]

outcome_architecture/outcome:  41%|████      | 821/2000 [00:08<00:12, 95.95it/s, test=12.6%, test_loss=0.911, train=11.7%, train_loss=0.925]

outcome_architecture/outcome:  42%|████▏     | 832/2000 [00:08<00:11, 98.81it/s, test=12.6%, test_loss=0.911, train=11.7%, train_loss=0.925]

outcome_architecture/outcome:  42%|████▏     | 843/2000 [00:08<00:11, 100.81it/s, test=12.6%, test_loss=0.911, train=11.7%, train_loss=0.925]

outcome_architecture/outcome:  42%|████▏     | 843/2000 [00:08<00:11, 100.81it/s, test=11.0%, test_loss=0.908, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  43%|████▎     | 854/2000 [00:08<00:12, 93.03it/s, test=11.0%, test_loss=0.908, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  43%|████▎     | 865/2000 [00:08<00:11, 97.13it/s, test=11.0%, test_loss=0.908, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  44%|████▍     | 876/2000 [00:09<00:11, 100.04it/s, test=11.0%, test_loss=0.908, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  44%|████▍     | 887/2000 [00:09<00:11, 99.89it/s, test=11.0%, test_loss=0.908, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  45%|████▍     | 898/2000 [00:09<00:10, 102.20it/s, test=11.0%, test_loss=0.908, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  45%|████▍     | 898/2000 [00:09<00:10, 102.20it/s, test=13.0%, test_loss=0.901, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:  45%|████▌     | 909/2000 [00:09<00:11, 94.27it/s, test=13.0%, test_loss=0.901, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:  46%|████▌     | 920/2000 [00:09<00:11, 96.27it/s, test=13.0%, test_loss=0.901, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:  47%|████▋     | 931/2000 [00:09<00:10, 99.52it/s, test=13.0%, test_loss=0.901, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:  47%|████▋     | 942/2000 [00:09<00:10, 101.97it/s, test=13.0%, test_loss=0.901, train=11.0%, train_loss=0.907]

outcome_architecture/outcome:  47%|████▋     | 942/2000 [00:09<00:10, 101.97it/s, test=12.5%, test_loss=0.905, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  48%|████▊     | 953/2000 [00:09<00:11, 92.03it/s, test=12.5%, test_loss=0.905, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  48%|████▊     | 964/2000 [00:10<00:10, 95.98it/s, test=12.5%, test_loss=0.905, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  49%|████▉     | 975/2000 [00:10<00:10, 99.00it/s, test=12.5%, test_loss=0.905, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  49%|████▉     | 986/2000 [00:10<00:10, 99.31it/s, test=12.5%, test_loss=0.905, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  50%|████▉     | 997/2000 [00:10<00:09, 101.40it/s, test=12.5%, test_loss=0.905, train=11.7%, train_loss=0.912]

outcome_architecture/outcome:  50%|████▉     | 997/2000 [00:10<00:09, 101.40it/s, test=11.1%, test_loss=0.899, train=9.7%, train_loss=0.906]

outcome_architecture/outcome:  50%|█████     | 1008/2000 [00:10<00:10, 92.58it/s, test=11.1%, test_loss=0.899, train=9.7%, train_loss=0.906]

outcome_architecture/outcome:  51%|█████     | 1019/2000 [00:10<00:10, 96.29it/s, test=11.1%, test_loss=0.899, train=9.7%, train_loss=0.906]

outcome_architecture/outcome:  52%|█████▏    | 1030/2000 [00:10<00:09, 99.13it/s, test=11.1%, test_loss=0.899, train=9.7%, train_loss=0.906]

outcome_architecture/outcome:  52%|█████▏    | 1041/2000 [00:10<00:09, 101.12it/s, test=11.1%, test_loss=0.899, train=9.7%, train_loss=0.906]

outcome_architecture/outcome:  52%|█████▏    | 1041/2000 [00:10<00:09, 101.12it/s, test=12.4%, test_loss=0.906, train=11.0%, train_loss=0.909]

outcome_architecture/outcome:  53%|█████▎    | 1052/2000 [00:10<00:10, 93.13it/s, test=12.4%, test_loss=0.906, train=11.0%, train_loss=0.909]

outcome_architecture/outcome:  53%|█████▎    | 1063/2000 [00:11<00:09, 96.85it/s, test=12.4%, test_loss=0.906, train=11.0%, train_loss=0.909]

outcome_architecture/outcome:  54%|█████▎    | 1074/2000 [00:11<00:09, 99.53it/s, test=12.4%, test_loss=0.906, train=11.0%, train_loss=0.909]

outcome_architecture/outcome:  54%|█████▍    | 1085/2000 [00:11<00:09, 101.53it/s, test=12.4%, test_loss=0.906, train=11.0%, train_loss=0.909]

outcome_architecture/outcome:  55%|█████▍    | 1096/2000 [00:11<00:08, 103.06it/s, test=12.4%, test_loss=0.906, train=11.0%, train_loss=0.909]

outcome_architecture/outcome:  55%|█████▍    | 1096/2000 [00:11<00:08, 103.06it/s, test=10.1%, test_loss=0.946, train=11.7%, train_loss=0.939]

outcome_architecture/outcome:  55%|█████▌    | 1107/2000 [00:11<00:09, 94.37it/s, test=10.1%, test_loss=0.946, train=11.7%, train_loss=0.939]

outcome_architecture/outcome:  56%|█████▌    | 1118/2000 [00:11<00:09, 97.85it/s, test=10.1%, test_loss=0.946, train=11.7%, train_loss=0.939]

outcome_architecture/outcome:  56%|█████▋    | 1129/2000 [00:11<00:08, 100.48it/s, test=10.1%, test_loss=0.946, train=11.7%, train_loss=0.939]

outcome_architecture/outcome:  57%|█████▋    | 1140/2000 [00:11<00:08, 102.19it/s, test=10.1%, test_loss=0.946, train=11.7%, train_loss=0.939]

outcome_architecture/outcome:  57%|█████▋    | 1140/2000 [00:11<00:08, 102.19it/s, test=13.3%, test_loss=0.912, train=9.3%, train_loss=0.909]

outcome_architecture/outcome:  58%|█████▊    | 1151/2000 [00:11<00:09, 92.97it/s, test=13.3%, test_loss=0.912, train=9.3%, train_loss=0.909]

outcome_architecture/outcome:  58%|█████▊    | 1162/2000 [00:12<00:08, 95.79it/s, test=13.3%, test_loss=0.912, train=9.3%, train_loss=0.909]

outcome_architecture/outcome:  59%|█████▊    | 1173/2000 [00:12<00:08, 97.94it/s, test=13.3%, test_loss=0.912, train=9.3%, train_loss=0.909]

outcome_architecture/outcome:  59%|█████▉    | 1184/2000 [00:12<00:08, 99.45it/s, test=13.3%, test_loss=0.912, train=9.3%, train_loss=0.909]

outcome_architecture/outcome:  60%|█████▉    | 1195/2000 [00:12<00:07, 101.61it/s, test=13.3%, test_loss=0.912, train=9.3%, train_loss=0.909]

outcome_architecture/outcome:  60%|█████▉    | 1195/2000 [00:12<00:07, 101.61it/s, test=11.2%, test_loss=0.933, train=9.3%, train_loss=0.941]

outcome_architecture/outcome:  60%|██████    | 1206/2000 [00:12<00:08, 92.63it/s, test=11.2%, test_loss=0.933, train=9.3%, train_loss=0.941]

outcome_architecture/outcome:  61%|██████    | 1217/2000 [00:12<00:08, 95.59it/s, test=11.2%, test_loss=0.933, train=9.3%, train_loss=0.941]

outcome_architecture/outcome:  61%|██████▏   | 1228/2000 [00:12<00:07, 97.67it/s, test=11.2%, test_loss=0.933, train=9.3%, train_loss=0.941]

outcome_architecture/outcome:  62%|██████▏   | 1239/2000 [00:12<00:07, 99.25it/s, test=11.2%, test_loss=0.933, train=9.3%, train_loss=0.941]

outcome_architecture/outcome:  62%|██████▏   | 1239/2000 [00:12<00:07, 99.25it/s, test=11.6%, test_loss=0.928, train=10.7%, train_loss=0.925]

outcome_architecture/outcome:  62%|██████▎   | 1250/2000 [00:12<00:08, 88.64it/s, test=11.6%, test_loss=0.928, train=10.7%, train_loss=0.925]

outcome_architecture/outcome:  63%|██████▎   | 1260/2000 [00:13<00:08, 87.03it/s, test=11.6%, test_loss=0.928, train=10.7%, train_loss=0.925]

outcome_architecture/outcome:  64%|██████▎   | 1270/2000 [00:13<00:08, 88.12it/s, test=11.6%, test_loss=0.928, train=10.7%, train_loss=0.925]

outcome_architecture/outcome:  64%|██████▍   | 1280/2000 [00:13<00:08, 88.91it/s, test=11.6%, test_loss=0.928, train=10.7%, train_loss=0.925]

outcome_architecture/outcome:  64%|██████▍   | 1289/2000 [00:13<00:08, 88.68it/s, test=11.6%, test_loss=0.928, train=10.7%, train_loss=0.925]

outcome_architecture/outcome:  64%|██████▍   | 1289/2000 [00:13<00:08, 88.68it/s, test=12.7%, test_loss=0.907, train=9.0%, train_loss=0.902]

outcome_architecture/outcome:  65%|██████▌   | 1300/2000 [00:13<00:08, 84.94it/s, test=12.7%, test_loss=0.907, train=9.0%, train_loss=0.902]

outcome_architecture/outcome:  66%|██████▌   | 1311/2000 [00:13<00:07, 90.62it/s, test=12.7%, test_loss=0.907, train=9.0%, train_loss=0.902]

outcome_architecture/outcome:  66%|██████▌   | 1322/2000 [00:13<00:07, 95.06it/s, test=12.7%, test_loss=0.907, train=9.0%, train_loss=0.902]

outcome_architecture/outcome:  67%|██████▋   | 1333/2000 [00:13<00:06, 98.30it/s, test=12.7%, test_loss=0.907, train=9.0%, train_loss=0.902]

outcome_architecture/outcome:  67%|██████▋   | 1344/2000 [00:13<00:06, 100.63it/s, test=12.7%, test_loss=0.907, train=9.0%, train_loss=0.902]

outcome_architecture/outcome:  67%|██████▋   | 1344/2000 [00:14<00:06, 100.63it/s, test=13.1%, test_loss=0.927, train=11.3%, train_loss=0.924]

outcome_architecture/outcome:  68%|██████▊   | 1355/2000 [00:14<00:06, 92.59it/s, test=13.1%, test_loss=0.927, train=11.3%, train_loss=0.924]

outcome_architecture/outcome:  68%|██████▊   | 1366/2000 [00:14<00:06, 96.27it/s, test=13.1%, test_loss=0.927, train=11.3%, train_loss=0.924]

outcome_architecture/outcome:  69%|██████▉   | 1377/2000 [00:14<00:06, 98.96it/s, test=13.1%, test_loss=0.927, train=11.3%, train_loss=0.924]

outcome_architecture/outcome:  69%|██████▉   | 1388/2000 [00:14<00:06, 100.96it/s, test=13.1%, test_loss=0.927, train=11.3%, train_loss=0.924]

outcome_architecture/outcome:  70%|██████▉   | 1399/2000 [00:14<00:05, 102.50it/s, test=13.1%, test_loss=0.927, train=11.3%, train_loss=0.924]

outcome_architecture/outcome:  70%|██████▉   | 1399/2000 [00:14<00:05, 102.50it/s, test=14.2%, test_loss=0.910, train=8.7%, train_loss=0.907]

outcome_architecture/outcome:  70%|███████   | 1410/2000 [00:14<00:06, 93.59it/s, test=14.2%, test_loss=0.910, train=8.7%, train_loss=0.907]

outcome_architecture/outcome:  71%|███████   | 1421/2000 [00:14<00:05, 97.20it/s, test=14.2%, test_loss=0.910, train=8.7%, train_loss=0.907]

outcome_architecture/outcome:  72%|███████▏  | 1432/2000 [00:14<00:05, 98.41it/s, test=14.2%, test_loss=0.910, train=8.7%, train_loss=0.907]

outcome_architecture/outcome:  72%|███████▏  | 1442/2000 [00:14<00:05, 98.37it/s, test=14.2%, test_loss=0.910, train=8.7%, train_loss=0.907]

outcome_architecture/outcome:  72%|███████▏  | 1442/2000 [00:15<00:05, 98.37it/s, test=14.0%, test_loss=0.914, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  73%|███████▎  | 1452/2000 [00:15<00:06, 89.16it/s, test=14.0%, test_loss=0.914, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  73%|███████▎  | 1462/2000 [00:15<00:05, 91.63it/s, test=14.0%, test_loss=0.914, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  74%|███████▎  | 1472/2000 [00:15<00:05, 93.35it/s, test=14.0%, test_loss=0.914, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  74%|███████▍  | 1482/2000 [00:15<00:05, 94.41it/s, test=14.0%, test_loss=0.914, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  75%|███████▍  | 1492/2000 [00:15<00:05, 95.23it/s, test=14.0%, test_loss=0.914, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  75%|███████▍  | 1492/2000 [00:15<00:05, 95.23it/s, test=11.6%, test_loss=0.909, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  75%|███████▌  | 1502/2000 [00:15<00:05, 87.06it/s, test=11.6%, test_loss=0.909, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  76%|███████▌  | 1512/2000 [00:15<00:05, 90.32it/s, test=11.6%, test_loss=0.909, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  76%|███████▌  | 1522/2000 [00:15<00:05, 92.13it/s, test=11.6%, test_loss=0.909, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  77%|███████▋  | 1532/2000 [00:15<00:05, 93.52it/s, test=11.6%, test_loss=0.909, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  77%|███████▋  | 1542/2000 [00:16<00:04, 94.39it/s, test=11.6%, test_loss=0.909, train=12.3%, train_loss=0.899]

outcome_architecture/outcome:  77%|███████▋  | 1542/2000 [00:16<00:04, 94.39it/s, test=13.8%, test_loss=0.918, train=8.7%, train_loss=0.912]

outcome_architecture/outcome:  78%|███████▊  | 1552/2000 [00:16<00:05, 86.23it/s, test=13.8%, test_loss=0.918, train=8.7%, train_loss=0.912]

outcome_architecture/outcome:  78%|███████▊  | 1562/2000 [00:16<00:04, 89.38it/s, test=13.8%, test_loss=0.918, train=8.7%, train_loss=0.912]

outcome_architecture/outcome:  79%|███████▊  | 1572/2000 [00:16<00:04, 91.46it/s, test=13.8%, test_loss=0.918, train=8.7%, train_loss=0.912]

outcome_architecture/outcome:  79%|███████▉  | 1582/2000 [00:16<00:04, 93.06it/s, test=13.8%, test_loss=0.918, train=8.7%, train_loss=0.912]

outcome_architecture/outcome:  80%|███████▉  | 1592/2000 [00:16<00:04, 94.56it/s, test=13.8%, test_loss=0.918, train=8.7%, train_loss=0.912]

outcome_architecture/outcome:  80%|███████▉  | 1592/2000 [00:16<00:04, 94.56it/s, test=11.9%, test_loss=0.911, train=10.0%, train_loss=0.903]

outcome_architecture/outcome:  80%|████████  | 1602/2000 [00:16<00:04, 86.73it/s, test=11.9%, test_loss=0.911, train=10.0%, train_loss=0.903]

outcome_architecture/outcome:  81%|████████  | 1612/2000 [00:16<00:04, 88.55it/s, test=11.9%, test_loss=0.911, train=10.0%, train_loss=0.903]

outcome_architecture/outcome:  81%|████████  | 1622/2000 [00:16<00:04, 91.13it/s, test=11.9%, test_loss=0.911, train=10.0%, train_loss=0.903]

outcome_architecture/outcome:  82%|████████▏ | 1632/2000 [00:17<00:03, 93.09it/s, test=11.9%, test_loss=0.911, train=10.0%, train_loss=0.903]

outcome_architecture/outcome:  82%|████████▏ | 1642/2000 [00:17<00:03, 92.92it/s, test=11.9%, test_loss=0.911, train=10.0%, train_loss=0.903]

outcome_architecture/outcome:  82%|████████▏ | 1642/2000 [00:17<00:03, 92.92it/s, test=13.6%, test_loss=0.924, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  83%|████████▎ | 1652/2000 [00:17<00:04, 85.12it/s, test=13.6%, test_loss=0.924, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  83%|████████▎ | 1662/2000 [00:17<00:03, 88.50it/s, test=13.6%, test_loss=0.924, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  84%|████████▎ | 1672/2000 [00:17<00:03, 89.52it/s, test=13.6%, test_loss=0.924, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  84%|████████▍ | 1682/2000 [00:17<00:03, 91.91it/s, test=13.6%, test_loss=0.924, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  85%|████████▍ | 1692/2000 [00:17<00:03, 93.99it/s, test=13.6%, test_loss=0.924, train=11.3%, train_loss=0.923]

outcome_architecture/outcome:  85%|████████▍ | 1692/2000 [00:17<00:03, 93.99it/s, test=11.4%, test_loss=0.897, train=11.3%, train_loss=0.922]

outcome_architecture/outcome:  85%|████████▌ | 1702/2000 [00:17<00:03, 86.45it/s, test=11.4%, test_loss=0.897, train=11.3%, train_loss=0.922]

outcome_architecture/outcome:  86%|████████▌ | 1712/2000 [00:17<00:03, 89.57it/s, test=11.4%, test_loss=0.897, train=11.3%, train_loss=0.922]

outcome_architecture/outcome:  86%|████████▌ | 1722/2000 [00:18<00:03, 91.93it/s, test=11.4%, test_loss=0.897, train=11.3%, train_loss=0.922]

outcome_architecture/outcome:  87%|████████▋ | 1732/2000 [00:18<00:02, 92.92it/s, test=11.4%, test_loss=0.897, train=11.3%, train_loss=0.922]

outcome_architecture/outcome:  87%|████████▋ | 1742/2000 [00:18<00:02, 94.32it/s, test=11.4%, test_loss=0.897, train=11.3%, train_loss=0.922]

outcome_architecture/outcome:  87%|████████▋ | 1742/2000 [00:18<00:02, 94.32it/s, test=14.6%, test_loss=0.906, train=10.7%, train_loss=0.893]

outcome_architecture/outcome:  88%|████████▊ | 1752/2000 [00:18<00:02, 85.92it/s, test=14.6%, test_loss=0.906, train=10.7%, train_loss=0.893]

outcome_architecture/outcome:  88%|████████▊ | 1762/2000 [00:18<00:02, 88.32it/s, test=14.6%, test_loss=0.906, train=10.7%, train_loss=0.893]

outcome_architecture/outcome:  89%|████████▊ | 1772/2000 [00:18<00:02, 90.97it/s, test=14.6%, test_loss=0.906, train=10.7%, train_loss=0.893]

outcome_architecture/outcome:  89%|████████▉ | 1782/2000 [00:18<00:02, 93.09it/s, test=14.6%, test_loss=0.906, train=10.7%, train_loss=0.893]

outcome_architecture/outcome:  90%|████████▉ | 1792/2000 [00:18<00:02, 94.37it/s, test=14.6%, test_loss=0.906, train=10.7%, train_loss=0.893]

outcome_architecture/outcome:  90%|████████▉ | 1792/2000 [00:18<00:02, 94.37it/s, test=14.1%, test_loss=0.932, train=8.7%, train_loss=0.915]

outcome_architecture/outcome:  90%|█████████ | 1802/2000 [00:18<00:02, 86.69it/s, test=14.1%, test_loss=0.932, train=8.7%, train_loss=0.915]

outcome_architecture/outcome:  91%|█████████ | 1812/2000 [00:19<00:02, 89.95it/s, test=14.1%, test_loss=0.932, train=8.7%, train_loss=0.915]

outcome_architecture/outcome:  91%|█████████ | 1822/2000 [00:19<00:01, 92.45it/s, test=14.1%, test_loss=0.932, train=8.7%, train_loss=0.915]

outcome_architecture/outcome:  92%|█████████▏| 1832/2000 [00:19<00:01, 94.17it/s, test=14.1%, test_loss=0.932, train=8.7%, train_loss=0.915]

outcome_architecture/outcome:  92%|█████████▏| 1842/2000 [00:19<00:01, 95.54it/s, test=14.1%, test_loss=0.932, train=8.7%, train_loss=0.915]

outcome_architecture/outcome:  92%|█████████▏| 1842/2000 [00:19<00:01, 95.54it/s, test=12.1%, test_loss=0.897, train=12.0%, train_loss=0.895]

outcome_architecture/outcome:  93%|█████████▎| 1852/2000 [00:19<00:01, 87.38it/s, test=12.1%, test_loss=0.897, train=12.0%, train_loss=0.895]

outcome_architecture/outcome:  93%|█████████▎| 1862/2000 [00:19<00:01, 90.68it/s, test=12.1%, test_loss=0.897, train=12.0%, train_loss=0.895]

outcome_architecture/outcome:  94%|█████████▎| 1872/2000 [00:19<00:01, 93.00it/s, test=12.1%, test_loss=0.897, train=12.0%, train_loss=0.895]

outcome_architecture/outcome:  94%|█████████▍| 1882/2000 [00:19<00:01, 94.39it/s, test=12.1%, test_loss=0.897, train=12.0%, train_loss=0.895]

outcome_architecture/outcome:  95%|█████████▍| 1892/2000 [00:19<00:01, 95.23it/s, test=12.1%, test_loss=0.897, train=12.0%, train_loss=0.895]

outcome_architecture/outcome:  95%|█████████▍| 1892/2000 [00:20<00:01, 95.23it/s, test=12.6%, test_loss=0.909, train=10.3%, train_loss=0.908]

outcome_architecture/outcome:  95%|█████████▌| 1902/2000 [00:20<00:01, 86.77it/s, test=12.6%, test_loss=0.909, train=10.3%, train_loss=0.908]

outcome_architecture/outcome:  96%|█████████▌| 1912/2000 [00:20<00:00, 89.92it/s, test=12.6%, test_loss=0.909, train=10.3%, train_loss=0.908]

outcome_architecture/outcome:  96%|█████████▌| 1922/2000 [00:20<00:00, 92.39it/s, test=12.6%, test_loss=0.909, train=10.3%, train_loss=0.908]

outcome_architecture/outcome:  97%|█████████▋| 1932/2000 [00:20<00:00, 94.17it/s, test=12.6%, test_loss=0.909, train=10.3%, train_loss=0.908]

outcome_architecture/outcome:  97%|█████████▋| 1942/2000 [00:20<00:00, 95.69it/s, test=12.6%, test_loss=0.909, train=10.3%, train_loss=0.908]

outcome_architecture/outcome:  97%|█████████▋| 1942/2000 [00:20<00:00, 95.69it/s, test=15.0%, test_loss=0.905, train=8.3%, train_loss=0.909]

outcome_architecture/outcome:  98%|█████████▊| 1952/2000 [00:20<00:00, 87.27it/s, test=15.0%, test_loss=0.905, train=8.3%, train_loss=0.909]

outcome_architecture/outcome:  98%|█████████▊| 1962/2000 [00:20<00:00, 90.15it/s, test=15.0%, test_loss=0.905, train=8.3%, train_loss=0.909]

outcome_architecture/outcome:  99%|█████████▊| 1972/2000 [00:20<00:00, 92.35it/s, test=15.0%, test_loss=0.905, train=8.3%, train_loss=0.909]

outcome_architecture/outcome:  99%|█████████▉| 1982/2000 [00:20<00:00, 93.55it/s, test=15.0%, test_loss=0.905, train=8.3%, train_loss=0.909]

outcome_architecture/outcome: 100%|█████████▉| 1992/2000 [00:21<00:00, 94.75it/s, test=15.0%, test_loss=0.905, train=8.3%, train_loss=0.909]

outcome_architecture/outcome: 100%|█████████▉| 1992/2000 [00:21<00:00, 94.75it/s, test=14.1%, test_loss=0.903, train=10.7%, train_loss=0.887]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 94.65it/s, test=14.1%, test_loss=0.903, train=10.7%, train_loss=0.887]

architecture/mode:  75%|███████▌  | 3/4 [00:44<00:16, 16.14s/it]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.067, train=0.0%, train_loss=4.068]

outcome_architecture/process:   0%|          | 1/2000 [00:00<05:23,  6.18it/s, test=0.0%, test_loss=4.067, train=0.0%, train_loss=4.068]

outcome_architecture/process:   0%|          | 1/2000 [00:00<05:23,  6.18it/s, test=0.0%, test_loss=20.389, train=0.0%, train_loss=20.452]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:21,  6.21it/s, test=0.0%, test_loss=20.389, train=0.0%, train_loss=20.452]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:21,  6.21it/s, test=0.0%, test_loss=4.084, train=0.0%, train_loss=4.091]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:21,  6.21it/s, test=7.7%, test_loss=3.715, train=2.7%, train_loss=3.724]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:35, 20.79it/s, test=7.7%, test_loss=3.715, train=2.7%, train_loss=3.724]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:35, 20.79it/s, test=5.2%, test_loss=2.749, train=7.3%, train_loss=2.782]

outcome_architecture/process:   1%|          | 20/2000 [00:00<01:07, 29.36it/s, test=5.2%, test_loss=2.749, train=7.3%, train_loss=2.782]

outcome_architecture/process:   1%|          | 20/2000 [00:01<01:07, 29.36it/s, test=6.2%, test_loss=2.688, train=5.0%, train_loss=2.701]

outcome_architecture/process:   1%|▏         | 25/2000 [00:01<01:11, 27.79it/s, test=6.2%, test_loss=2.688, train=5.0%, train_loss=2.701]

outcome_architecture/process:   2%|▏         | 35/2000 [00:01<00:47, 41.50it/s, test=6.2%, test_loss=2.688, train=5.0%, train_loss=2.701]

outcome_architecture/process:   2%|▏         | 45/2000 [00:01<00:36, 53.70it/s, test=6.2%, test_loss=2.688, train=5.0%, train_loss=2.701]

outcome_architecture/process:   2%|▏         | 45/2000 [00:01<00:36, 53.70it/s, test=10.4%, test_loss=2.578, train=4.7%, train_loss=2.652]

outcome_architecture/process:   3%|▎         | 52/2000 [00:01<00:43, 44.81it/s, test=10.4%, test_loss=2.578, train=4.7%, train_loss=2.652]

outcome_architecture/process:   3%|▎         | 62/2000 [00:01<00:34, 55.78it/s, test=10.4%, test_loss=2.578, train=4.7%, train_loss=2.652]

outcome_architecture/process:   4%|▎         | 72/2000 [00:01<00:29, 65.22it/s, test=10.4%, test_loss=2.578, train=4.7%, train_loss=2.652]

outcome_architecture/process:   4%|▎         | 72/2000 [00:01<00:29, 65.22it/s, test=11.2%, test_loss=2.542, train=10.3%, train_loss=2.546]

outcome_architecture/process:   4%|▍         | 80/2000 [00:01<00:36, 52.24it/s, test=11.2%, test_loss=2.542, train=10.3%, train_loss=2.546]

outcome_architecture/process:   4%|▍         | 90/2000 [00:01<00:30, 61.79it/s, test=11.2%, test_loss=2.542, train=10.3%, train_loss=2.546]

outcome_architecture/process:   4%|▍         | 90/2000 [00:02<00:30, 61.79it/s, test=0.0%, test_loss=5.902, train=0.0%, train_loss=6.516]

outcome_architecture/process:   5%|▌         | 100/2000 [00:02<00:36, 52.46it/s, test=0.0%, test_loss=5.902, train=0.0%, train_loss=6.516]

outcome_architecture/process:   6%|▌         | 110/2000 [00:02<00:30, 61.47it/s, test=0.0%, test_loss=5.902, train=0.0%, train_loss=6.516]

outcome_architecture/process:   6%|▌         | 120/2000 [00:02<00:27, 69.62it/s, test=0.0%, test_loss=5.902, train=0.0%, train_loss=6.516]

outcome_architecture/process:   6%|▋         | 130/2000 [00:02<00:24, 76.27it/s, test=0.0%, test_loss=5.902, train=0.0%, train_loss=6.516]

outcome_architecture/process:   7%|▋         | 140/2000 [00:02<00:22, 81.88it/s, test=0.0%, test_loss=5.902, train=0.0%, train_loss=6.516]

outcome_architecture/process:   7%|▋         | 140/2000 [00:02<00:22, 81.88it/s, test=8.8%, test_loss=2.642, train=9.0%, train_loss=2.679]

outcome_architecture/process:   8%|▊         | 150/2000 [00:02<00:29, 62.12it/s, test=8.8%, test_loss=2.642, train=9.0%, train_loss=2.679]

outcome_architecture/process:   8%|▊         | 160/2000 [00:03<00:26, 69.68it/s, test=8.8%, test_loss=2.642, train=9.0%, train_loss=2.679]

outcome_architecture/process:   8%|▊         | 170/2000 [00:03<00:23, 76.34it/s, test=8.8%, test_loss=2.642, train=9.0%, train_loss=2.679]

outcome_architecture/process:   9%|▉         | 180/2000 [00:03<00:22, 81.85it/s, test=8.8%, test_loss=2.642, train=9.0%, train_loss=2.679]

outcome_architecture/process:  10%|▉         | 190/2000 [00:03<00:21, 85.84it/s, test=8.8%, test_loss=2.642, train=9.0%, train_loss=2.679]

outcome_architecture/process:  10%|▉         | 190/2000 [00:03<00:21, 85.84it/s, test=11.4%, test_loss=2.391, train=9.7%, train_loss=2.434]

outcome_architecture/process:  10%|█         | 200/2000 [00:03<00:28, 63.38it/s, test=11.4%, test_loss=2.391, train=9.7%, train_loss=2.434]

outcome_architecture/process:  10%|█         | 210/2000 [00:03<00:25, 70.69it/s, test=11.4%, test_loss=2.391, train=9.7%, train_loss=2.434]

outcome_architecture/process:  11%|█         | 220/2000 [00:03<00:23, 77.07it/s, test=11.4%, test_loss=2.391, train=9.7%, train_loss=2.434]

outcome_architecture/process:  12%|█▏        | 230/2000 [00:03<00:21, 82.39it/s, test=11.4%, test_loss=2.391, train=9.7%, train_loss=2.434]

outcome_architecture/process:  12%|█▏        | 240/2000 [00:03<00:20, 86.92it/s, test=11.4%, test_loss=2.391, train=9.7%, train_loss=2.434]

outcome_architecture/process:  12%|█▏        | 240/2000 [00:04<00:20, 86.92it/s, test=10.8%, test_loss=2.222, train=8.3%, train_loss=2.249]

outcome_architecture/process:  12%|█▎        | 250/2000 [00:04<00:27, 64.44it/s, test=10.8%, test_loss=2.222, train=8.3%, train_loss=2.249]

outcome_architecture/process:  13%|█▎        | 260/2000 [00:04<00:24, 71.99it/s, test=10.8%, test_loss=2.222, train=8.3%, train_loss=2.249]

outcome_architecture/process:  14%|█▎        | 270/2000 [00:04<00:22, 78.51it/s, test=10.8%, test_loss=2.222, train=8.3%, train_loss=2.249]

outcome_architecture/process:  14%|█▍        | 280/2000 [00:04<00:20, 83.64it/s, test=10.8%, test_loss=2.222, train=8.3%, train_loss=2.249]

outcome_architecture/process:  14%|█▍        | 290/2000 [00:04<00:19, 87.84it/s, test=10.8%, test_loss=2.222, train=8.3%, train_loss=2.249]

outcome_architecture/process:  14%|█▍        | 290/2000 [00:04<00:19, 87.84it/s, test=10.2%, test_loss=2.096, train=9.0%, train_loss=2.132]

outcome_architecture/process:  15%|█▌        | 300/2000 [00:04<00:26, 64.65it/s, test=10.2%, test_loss=2.096, train=9.0%, train_loss=2.132]

outcome_architecture/process:  16%|█▌        | 310/2000 [00:04<00:23, 72.01it/s, test=10.2%, test_loss=2.096, train=9.0%, train_loss=2.132]

outcome_architecture/process:  16%|█▌        | 320/2000 [00:05<00:21, 78.14it/s, test=10.2%, test_loss=2.096, train=9.0%, train_loss=2.132]

outcome_architecture/process:  16%|█▋        | 330/2000 [00:05<00:20, 83.38it/s, test=10.2%, test_loss=2.096, train=9.0%, train_loss=2.132]

outcome_architecture/process:  17%|█▋        | 340/2000 [00:05<00:19, 87.23it/s, test=10.2%, test_loss=2.096, train=9.0%, train_loss=2.132]

outcome_architecture/process:  17%|█▋        | 340/2000 [00:05<00:19, 87.23it/s, test=11.2%, test_loss=1.764, train=10.3%, train_loss=1.755]

outcome_architecture/process:  18%|█▊        | 350/2000 [00:05<00:25, 64.42it/s, test=11.2%, test_loss=1.764, train=10.3%, train_loss=1.755]

outcome_architecture/process:  18%|█▊        | 360/2000 [00:05<00:22, 71.89it/s, test=11.2%, test_loss=1.764, train=10.3%, train_loss=1.755]

outcome_architecture/process:  18%|█▊        | 370/2000 [00:05<00:20, 78.28it/s, test=11.2%, test_loss=1.764, train=10.3%, train_loss=1.755]

outcome_architecture/process:  19%|█▉        | 380/2000 [00:05<00:19, 83.39it/s, test=11.2%, test_loss=1.764, train=10.3%, train_loss=1.755]

outcome_architecture/process:  20%|█▉        | 390/2000 [00:05<00:18, 87.46it/s, test=11.2%, test_loss=1.764, train=10.3%, train_loss=1.755]

outcome_architecture/process:  20%|█▉        | 390/2000 [00:06<00:18, 87.46it/s, test=10.0%, test_loss=1.553, train=13.0%, train_loss=1.521]

outcome_architecture/process:  20%|██        | 400/2000 [00:06<00:24, 64.51it/s, test=10.0%, test_loss=1.553, train=13.0%, train_loss=1.521]

outcome_architecture/process:  20%|██        | 410/2000 [00:06<00:22, 72.02it/s, test=10.0%, test_loss=1.553, train=13.0%, train_loss=1.521]

outcome_architecture/process:  21%|██        | 420/2000 [00:06<00:20, 78.19it/s, test=10.0%, test_loss=1.553, train=13.0%, train_loss=1.521]

outcome_architecture/process:  22%|██▏       | 430/2000 [00:06<00:18, 83.37it/s, test=10.0%, test_loss=1.553, train=13.0%, train_loss=1.521]

outcome_architecture/process:  22%|██▏       | 440/2000 [00:06<00:17, 87.14it/s, test=10.0%, test_loss=1.553, train=13.0%, train_loss=1.521]

outcome_architecture/process:  22%|██▏       | 440/2000 [00:06<00:17, 87.14it/s, test=10.8%, test_loss=2.266, train=9.7%, train_loss=2.228]

outcome_architecture/process:  22%|██▎       | 450/2000 [00:06<00:24, 63.63it/s, test=10.8%, test_loss=2.266, train=9.7%, train_loss=2.228]

outcome_architecture/process:  23%|██▎       | 460/2000 [00:06<00:21, 71.02it/s, test=10.8%, test_loss=2.266, train=9.7%, train_loss=2.228]

outcome_architecture/process:  24%|██▎       | 470/2000 [00:07<00:19, 77.43it/s, test=10.8%, test_loss=2.266, train=9.7%, train_loss=2.228]

outcome_architecture/process:  24%|██▍       | 480/2000 [00:07<00:18, 82.79it/s, test=10.8%, test_loss=2.266, train=9.7%, train_loss=2.228]

outcome_architecture/process:  24%|██▍       | 490/2000 [00:07<00:17, 87.01it/s, test=10.8%, test_loss=2.266, train=9.7%, train_loss=2.228]

outcome_architecture/process:  24%|██▍       | 490/2000 [00:07<00:17, 87.01it/s, test=11.9%, test_loss=1.572, train=12.0%, train_loss=1.544]

outcome_architecture/process:  25%|██▌       | 500/2000 [00:07<00:23, 64.30it/s, test=11.9%, test_loss=1.572, train=12.0%, train_loss=1.544]

outcome_architecture/process:  26%|██▌       | 511/2000 [00:07<00:20, 73.41it/s, test=11.9%, test_loss=1.572, train=12.0%, train_loss=1.544]

outcome_architecture/process:  26%|██▌       | 522/2000 [00:07<00:18, 81.03it/s, test=11.9%, test_loss=1.572, train=12.0%, train_loss=1.544]

outcome_architecture/process:  27%|██▋       | 533/2000 [00:07<00:16, 87.11it/s, test=11.9%, test_loss=1.572, train=12.0%, train_loss=1.544]

outcome_architecture/process:  27%|██▋       | 544/2000 [00:07<00:15, 91.95it/s, test=11.9%, test_loss=1.572, train=12.0%, train_loss=1.544]

outcome_architecture/process:  27%|██▋       | 544/2000 [00:08<00:15, 91.95it/s, test=11.6%, test_loss=1.159, train=10.0%, train_loss=1.125]

outcome_architecture/process:  28%|██▊       | 554/2000 [00:08<00:21, 68.03it/s, test=11.6%, test_loss=1.159, train=10.0%, train_loss=1.125]

outcome_architecture/process:  28%|██▊       | 565/2000 [00:08<00:18, 76.38it/s, test=11.6%, test_loss=1.159, train=10.0%, train_loss=1.125]

outcome_architecture/process:  29%|██▉       | 576/2000 [00:08<00:17, 83.39it/s, test=11.6%, test_loss=1.159, train=10.0%, train_loss=1.125]

outcome_architecture/process:  29%|██▉       | 587/2000 [00:08<00:15, 89.00it/s, test=11.6%, test_loss=1.159, train=10.0%, train_loss=1.125]

outcome_architecture/process:  30%|██▉       | 598/2000 [00:08<00:15, 93.37it/s, test=11.6%, test_loss=1.159, train=10.0%, train_loss=1.125]

outcome_architecture/process:  30%|██▉       | 598/2000 [00:08<00:15, 93.37it/s, test=11.9%, test_loss=2.308, train=9.0%, train_loss=2.366]

outcome_architecture/process:  30%|███       | 608/2000 [00:08<00:20, 68.52it/s, test=11.9%, test_loss=2.308, train=9.0%, train_loss=2.366]

outcome_architecture/process:  31%|███       | 619/2000 [00:08<00:17, 76.81it/s, test=11.9%, test_loss=2.308, train=9.0%, train_loss=2.366]

outcome_architecture/process:  32%|███▏      | 630/2000 [00:09<00:16, 83.65it/s, test=11.9%, test_loss=2.308, train=9.0%, train_loss=2.366]

outcome_architecture/process:  32%|███▏      | 641/2000 [00:09<00:15, 89.10it/s, test=11.9%, test_loss=2.308, train=9.0%, train_loss=2.366]

outcome_architecture/process:  32%|███▏      | 641/2000 [00:09<00:15, 89.10it/s, test=14.8%, test_loss=1.678, train=12.0%, train_loss=1.705]

outcome_architecture/process:  33%|███▎      | 651/2000 [00:09<00:20, 67.04it/s, test=14.8%, test_loss=1.678, train=12.0%, train_loss=1.705]

outcome_architecture/process:  33%|███▎      | 662/2000 [00:09<00:17, 75.54it/s, test=14.8%, test_loss=1.678, train=12.0%, train_loss=1.705]

outcome_architecture/process:  34%|███▎      | 673/2000 [00:09<00:16, 82.77it/s, test=14.8%, test_loss=1.678, train=12.0%, train_loss=1.705]

outcome_architecture/process:  34%|███▍      | 684/2000 [00:09<00:14, 88.84it/s, test=14.8%, test_loss=1.678, train=12.0%, train_loss=1.705]

outcome_architecture/process:  35%|███▍      | 695/2000 [00:09<00:13, 93.31it/s, test=14.8%, test_loss=1.678, train=12.0%, train_loss=1.705]

outcome_architecture/process:  35%|███▍      | 695/2000 [00:10<00:13, 93.31it/s, test=11.1%, test_loss=1.281, train=10.3%, train_loss=1.302]

outcome_architecture/process:  35%|███▌      | 705/2000 [00:10<00:18, 68.77it/s, test=11.1%, test_loss=1.281, train=10.3%, train_loss=1.302]

outcome_architecture/process:  36%|███▌      | 716/2000 [00:10<00:16, 77.08it/s, test=11.1%, test_loss=1.281, train=10.3%, train_loss=1.302]

outcome_architecture/process:  36%|███▋      | 727/2000 [00:10<00:15, 83.81it/s, test=11.1%, test_loss=1.281, train=10.3%, train_loss=1.302]

outcome_architecture/process:  37%|███▋      | 738/2000 [00:10<00:14, 89.45it/s, test=11.1%, test_loss=1.281, train=10.3%, train_loss=1.302]

outcome_architecture/process:  37%|███▋      | 749/2000 [00:10<00:13, 93.88it/s, test=11.1%, test_loss=1.281, train=10.3%, train_loss=1.302]

outcome_architecture/process:  37%|███▋      | 749/2000 [00:10<00:13, 93.88it/s, test=15.1%, test_loss=0.964, train=14.0%, train_loss=0.954]

outcome_architecture/process:  38%|███▊      | 760/2000 [00:10<00:17, 69.38it/s, test=15.1%, test_loss=0.964, train=14.0%, train_loss=0.954]

outcome_architecture/process:  39%|███▊      | 771/2000 [00:10<00:15, 76.93it/s, test=15.1%, test_loss=0.964, train=14.0%, train_loss=0.954]

outcome_architecture/process:  39%|███▉      | 782/2000 [00:10<00:14, 83.28it/s, test=15.1%, test_loss=0.964, train=14.0%, train_loss=0.954]

outcome_architecture/process:  40%|███▉      | 793/2000 [00:11<00:13, 88.68it/s, test=15.1%, test_loss=0.964, train=14.0%, train_loss=0.954]

outcome_architecture/process:  40%|███▉      | 793/2000 [00:11<00:13, 88.68it/s, test=19.0%, test_loss=0.555, train=16.7%, train_loss=0.563]

outcome_architecture/process:  40%|████      | 803/2000 [00:11<00:18, 66.15it/s, test=19.0%, test_loss=0.555, train=16.7%, train_loss=0.563]

outcome_architecture/process:  41%|████      | 814/2000 [00:11<00:15, 74.66it/s, test=19.0%, test_loss=0.555, train=16.7%, train_loss=0.563]

outcome_architecture/process:  41%|████▏     | 825/2000 [00:11<00:14, 81.56it/s, test=19.0%, test_loss=0.555, train=16.7%, train_loss=0.563]

outcome_architecture/process:  42%|████▏     | 836/2000 [00:11<00:13, 87.39it/s, test=19.0%, test_loss=0.555, train=16.7%, train_loss=0.563]

outcome_architecture/process:  42%|████▏     | 847/2000 [00:11<00:12, 91.85it/s, test=19.0%, test_loss=0.555, train=16.7%, train_loss=0.563]

outcome_architecture/process:  42%|████▏     | 847/2000 [00:11<00:12, 91.85it/s, test=19.9%, test_loss=0.487, train=18.0%, train_loss=0.440]

outcome_architecture/process:  43%|████▎     | 857/2000 [00:11<00:16, 67.35it/s, test=19.9%, test_loss=0.487, train=18.0%, train_loss=0.440]

outcome_architecture/process:  43%|████▎     | 868/2000 [00:12<00:15, 75.44it/s, test=19.9%, test_loss=0.487, train=18.0%, train_loss=0.440]

outcome_architecture/process:  44%|████▍     | 879/2000 [00:12<00:13, 82.60it/s, test=19.9%, test_loss=0.487, train=18.0%, train_loss=0.440]

outcome_architecture/process:  44%|████▍     | 890/2000 [00:12<00:12, 88.21it/s, test=19.9%, test_loss=0.487, train=18.0%, train_loss=0.440]

outcome_architecture/process:  44%|████▍     | 890/2000 [00:12<00:12, 88.21it/s, test=42.4%, test_loss=0.235, train=41.7%, train_loss=0.204]

outcome_architecture/process:  45%|████▌     | 900/2000 [00:12<00:16, 66.10it/s, test=42.4%, test_loss=0.235, train=41.7%, train_loss=0.204]

outcome_architecture/process:  46%|████▌     | 911/2000 [00:12<00:14, 74.58it/s, test=42.4%, test_loss=0.235, train=41.7%, train_loss=0.204]

outcome_architecture/process:  46%|████▌     | 922/2000 [00:12<00:13, 81.95it/s, test=42.4%, test_loss=0.235, train=41.7%, train_loss=0.204]

outcome_architecture/process:  47%|████▋     | 933/2000 [00:12<00:12, 87.88it/s, test=42.4%, test_loss=0.235, train=41.7%, train_loss=0.204]

outcome_architecture/process:  47%|████▋     | 944/2000 [00:12<00:11, 92.62it/s, test=42.4%, test_loss=0.235, train=41.7%, train_loss=0.204]

outcome_architecture/process:  47%|████▋     | 944/2000 [00:13<00:11, 92.62it/s, test=61.6%, test_loss=0.128, train=61.3%, train_loss=0.134]

outcome_architecture/process:  48%|████▊     | 954/2000 [00:13<00:15, 68.39it/s, test=61.6%, test_loss=0.128, train=61.3%, train_loss=0.134]

outcome_architecture/process:  48%|████▊     | 965/2000 [00:13<00:13, 76.58it/s, test=61.6%, test_loss=0.128, train=61.3%, train_loss=0.134]

outcome_architecture/process:  49%|████▉     | 976/2000 [00:13<00:12, 83.54it/s, test=61.6%, test_loss=0.128, train=61.3%, train_loss=0.134]

outcome_architecture/process:  49%|████▉     | 987/2000 [00:13<00:11, 89.13it/s, test=61.6%, test_loss=0.128, train=61.3%, train_loss=0.134]

outcome_architecture/process:  50%|████▉     | 998/2000 [00:13<00:10, 93.32it/s, test=61.6%, test_loss=0.128, train=61.3%, train_loss=0.134]

outcome_architecture/process:  50%|████▉     | 998/2000 [00:13<00:10, 93.32it/s, test=22.4%, test_loss=0.429, train=26.7%, train_loss=0.396]

outcome_architecture/process:  50%|█████     | 1008/2000 [00:13<00:14, 68.58it/s, test=22.4%, test_loss=0.429, train=26.7%, train_loss=0.396]

outcome_architecture/process:  51%|█████     | 1019/2000 [00:13<00:12, 76.71it/s, test=22.4%, test_loss=0.429, train=26.7%, train_loss=0.396]

outcome_architecture/process:  52%|█████▏    | 1030/2000 [00:14<00:11, 83.65it/s, test=22.4%, test_loss=0.429, train=26.7%, train_loss=0.396]

outcome_architecture/process:  52%|█████▏    | 1041/2000 [00:14<00:10, 89.20it/s, test=22.4%, test_loss=0.429, train=26.7%, train_loss=0.396]

outcome_architecture/process:  52%|█████▏    | 1041/2000 [00:14<00:10, 89.20it/s, test=64.3%, test_loss=0.109, train=67.0%, train_loss=0.101]

outcome_architecture/process:  53%|█████▎    | 1051/2000 [00:14<00:14, 66.91it/s, test=64.3%, test_loss=0.109, train=67.0%, train_loss=0.101]

outcome_architecture/process:  53%|█████▎    | 1062/2000 [00:14<00:12, 75.33it/s, test=64.3%, test_loss=0.109, train=67.0%, train_loss=0.101]

outcome_architecture/process:  54%|█████▎    | 1073/2000 [00:14<00:11, 82.38it/s, test=64.3%, test_loss=0.109, train=67.0%, train_loss=0.101]

outcome_architecture/process:  54%|█████▍    | 1084/2000 [00:14<00:10, 88.14it/s, test=64.3%, test_loss=0.109, train=67.0%, train_loss=0.101]

outcome_architecture/process:  55%|█████▍    | 1095/2000 [00:14<00:09, 92.69it/s, test=64.3%, test_loss=0.109, train=67.0%, train_loss=0.101]

outcome_architecture/process:  55%|█████▍    | 1095/2000 [00:15<00:09, 92.69it/s, test=82.4%, test_loss=0.061, train=86.0%, train_loss=0.053]

outcome_architecture/process:  55%|█████▌    | 1105/2000 [00:15<00:13, 68.50it/s, test=82.4%, test_loss=0.061, train=86.0%, train_loss=0.053]

outcome_architecture/process:  56%|█████▌    | 1116/2000 [00:15<00:11, 76.65it/s, test=82.4%, test_loss=0.061, train=86.0%, train_loss=0.053]

outcome_architecture/process:  56%|█████▋    | 1127/2000 [00:15<00:10, 83.52it/s, test=82.4%, test_loss=0.061, train=86.0%, train_loss=0.053]

outcome_architecture/process:  57%|█████▋    | 1138/2000 [00:15<00:09, 89.06it/s, test=82.4%, test_loss=0.061, train=86.0%, train_loss=0.053]

outcome_architecture/process:  57%|█████▋    | 1149/2000 [00:15<00:09, 93.30it/s, test=82.4%, test_loss=0.061, train=86.0%, train_loss=0.053]

outcome_architecture/process:  57%|█████▋    | 1149/2000 [00:15<00:09, 93.30it/s, test=85.3%, test_loss=0.051, train=87.0%, train_loss=0.065]

outcome_architecture/process:  58%|█████▊    | 1159/2000 [00:15<00:12, 68.69it/s, test=85.3%, test_loss=0.051, train=87.0%, train_loss=0.065]

outcome_architecture/process:  58%|█████▊    | 1170/2000 [00:15<00:10, 76.86it/s, test=85.3%, test_loss=0.051, train=87.0%, train_loss=0.065]

outcome_architecture/process:  59%|█████▉    | 1181/2000 [00:15<00:09, 83.79it/s, test=85.3%, test_loss=0.051, train=87.0%, train_loss=0.065]

outcome_architecture/process:  60%|█████▉    | 1192/2000 [00:16<00:09, 89.19it/s, test=85.3%, test_loss=0.051, train=87.0%, train_loss=0.065]

outcome_architecture/process:  60%|█████▉    | 1192/2000 [00:16<00:09, 89.19it/s, test=95.0%, test_loss=0.031, train=92.3%, train_loss=0.019]

outcome_architecture/process:  60%|██████    | 1202/2000 [00:16<00:11, 66.98it/s, test=95.0%, test_loss=0.031, train=92.3%, train_loss=0.019]

outcome_architecture/process:  61%|██████    | 1213/2000 [00:16<00:10, 75.38it/s, test=95.0%, test_loss=0.031, train=92.3%, train_loss=0.019]

outcome_architecture/process:  61%|██████    | 1224/2000 [00:16<00:09, 82.36it/s, test=95.0%, test_loss=0.031, train=92.3%, train_loss=0.019]

outcome_architecture/process:  62%|██████▏   | 1235/2000 [00:16<00:08, 88.06it/s, test=95.0%, test_loss=0.031, train=92.3%, train_loss=0.019]

outcome_architecture/process:  62%|██████▏   | 1246/2000 [00:16<00:08, 92.48it/s, test=95.0%, test_loss=0.031, train=92.3%, train_loss=0.019]

outcome_architecture/process:  62%|██████▏   | 1246/2000 [00:16<00:08, 92.48it/s, test=95.0%, test_loss=0.015, train=97.0%, train_loss=0.008]

outcome_architecture/process:  63%|██████▎   | 1256/2000 [00:16<00:10, 68.22it/s, test=95.0%, test_loss=0.015, train=97.0%, train_loss=0.008]

outcome_architecture/process:  63%|██████▎   | 1267/2000 [00:17<00:09, 76.45it/s, test=95.0%, test_loss=0.015, train=97.0%, train_loss=0.008]

outcome_architecture/process:  64%|██████▍   | 1278/2000 [00:17<00:08, 83.35it/s, test=95.0%, test_loss=0.015, train=97.0%, train_loss=0.008]

outcome_architecture/process:  64%|██████▍   | 1289/2000 [00:17<00:08, 88.87it/s, test=95.0%, test_loss=0.015, train=97.0%, train_loss=0.008]

outcome_architecture/process:  64%|██████▍   | 1289/2000 [00:17<00:08, 88.87it/s, test=90.7%, test_loss=0.032, train=93.3%, train_loss=0.019]

outcome_architecture/process:  65%|██████▌   | 1300/2000 [00:17<00:10, 67.59it/s, test=90.7%, test_loss=0.032, train=93.3%, train_loss=0.019]

outcome_architecture/process:  65%|██████▌   | 1309/2000 [00:17<00:09, 71.64it/s, test=90.7%, test_loss=0.032, train=93.3%, train_loss=0.019]

outcome_architecture/process:  66%|██████▌   | 1320/2000 [00:17<00:08, 79.51it/s, test=90.7%, test_loss=0.032, train=93.3%, train_loss=0.019]

outcome_architecture/process:  67%|██████▋   | 1331/2000 [00:17<00:07, 85.97it/s, test=90.7%, test_loss=0.032, train=93.3%, train_loss=0.019]

outcome_architecture/process:  67%|██████▋   | 1342/2000 [00:17<00:07, 91.08it/s, test=90.7%, test_loss=0.032, train=93.3%, train_loss=0.019]

outcome_architecture/process:  67%|██████▋   | 1342/2000 [00:18<00:07, 91.08it/s, test=97.1%, test_loss=0.008, train=97.7%, train_loss=0.003]

outcome_architecture/process:  68%|██████▊   | 1352/2000 [00:18<00:09, 67.59it/s, test=97.1%, test_loss=0.008, train=97.7%, train_loss=0.003]

outcome_architecture/process:  68%|██████▊   | 1363/2000 [00:18<00:08, 75.80it/s, test=97.1%, test_loss=0.008, train=97.7%, train_loss=0.003]

outcome_architecture/process:  69%|██████▊   | 1374/2000 [00:18<00:07, 82.95it/s, test=97.1%, test_loss=0.008, train=97.7%, train_loss=0.003]

outcome_architecture/process:  69%|██████▉   | 1385/2000 [00:18<00:06, 88.45it/s, test=97.1%, test_loss=0.008, train=97.7%, train_loss=0.003]

outcome_architecture/process:  70%|██████▉   | 1396/2000 [00:18<00:06, 92.71it/s, test=97.1%, test_loss=0.008, train=97.7%, train_loss=0.003]

outcome_architecture/process:  70%|██████▉   | 1396/2000 [00:18<00:06, 92.71it/s, test=99.9%, test_loss=0.002, train=100.0%, train_loss=0.002]

outcome_architecture/process:  70%|███████   | 1406/2000 [00:18<00:08, 68.14it/s, test=99.9%, test_loss=0.002, train=100.0%, train_loss=0.002]

outcome_architecture/process:  71%|███████   | 1417/2000 [00:18<00:07, 76.31it/s, test=99.9%, test_loss=0.002, train=100.0%, train_loss=0.002]

outcome_architecture/process:  71%|███████▏  | 1428/2000 [00:19<00:06, 83.10it/s, test=99.9%, test_loss=0.002, train=100.0%, train_loss=0.002]

outcome_architecture/process:  72%|███████▏  | 1439/2000 [00:19<00:06, 88.63it/s, test=99.9%, test_loss=0.002, train=100.0%, train_loss=0.002]

outcome_architecture/process:  72%|███████▏  | 1439/2000 [00:19<00:06, 88.63it/s, test=97.1%, test_loss=0.009, train=97.7%, train_loss=0.011]

outcome_architecture/process:  72%|███████▎  | 1450/2000 [00:19<00:08, 67.45it/s, test=97.1%, test_loss=0.009, train=97.7%, train_loss=0.011]

outcome_architecture/process:  73%|███████▎  | 1461/2000 [00:19<00:07, 75.53it/s, test=97.1%, test_loss=0.009, train=97.7%, train_loss=0.011]

outcome_architecture/process:  74%|███████▎  | 1472/2000 [00:19<00:06, 82.44it/s, test=97.1%, test_loss=0.009, train=97.7%, train_loss=0.011]

outcome_architecture/process:  74%|███████▍  | 1483/2000 [00:19<00:05, 88.19it/s, test=97.1%, test_loss=0.009, train=97.7%, train_loss=0.011]

outcome_architecture/process:  75%|███████▍  | 1494/2000 [00:19<00:05, 92.75it/s, test=97.1%, test_loss=0.009, train=97.7%, train_loss=0.011]

outcome_architecture/process:  75%|███████▍  | 1494/2000 [00:20<00:05, 92.75it/s, test=98.0%, test_loss=0.009, train=98.3%, train_loss=0.003]

outcome_architecture/process:  75%|███████▌  | 1504/2000 [00:20<00:07, 68.67it/s, test=98.0%, test_loss=0.009, train=98.3%, train_loss=0.003]

outcome_architecture/process:  76%|███████▌  | 1515/2000 [00:20<00:06, 76.93it/s, test=98.0%, test_loss=0.009, train=98.3%, train_loss=0.003]

outcome_architecture/process:  76%|███████▋  | 1526/2000 [00:20<00:05, 83.79it/s, test=98.0%, test_loss=0.009, train=98.3%, train_loss=0.003]

outcome_architecture/process:  77%|███████▋  | 1537/2000 [00:20<00:05, 89.05it/s, test=98.0%, test_loss=0.009, train=98.3%, train_loss=0.003]

outcome_architecture/process:  77%|███████▋  | 1548/2000 [00:20<00:04, 93.19it/s, test=98.0%, test_loss=0.009, train=98.3%, train_loss=0.003]

outcome_architecture/process:  77%|███████▋  | 1548/2000 [00:20<00:04, 93.19it/s, test=99.7%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  78%|███████▊  | 1558/2000 [00:20<00:06, 68.83it/s, test=99.7%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  78%|███████▊  | 1569/2000 [00:20<00:05, 77.14it/s, test=99.7%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  79%|███████▉  | 1580/2000 [00:20<00:05, 83.94it/s, test=99.7%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  80%|███████▉  | 1591/2000 [00:21<00:04, 89.59it/s, test=99.7%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  80%|███████▉  | 1591/2000 [00:21<00:04, 89.59it/s, test=99.5%, test_loss=0.003, train=100.0%, train_loss=0.001]

outcome_architecture/process:  80%|████████  | 1601/2000 [00:21<00:05, 67.29it/s, test=99.5%, test_loss=0.003, train=100.0%, train_loss=0.001]

outcome_architecture/process:  81%|████████  | 1612/2000 [00:21<00:05, 75.78it/s, test=99.5%, test_loss=0.003, train=100.0%, train_loss=0.001]

outcome_architecture/process:  81%|████████  | 1623/2000 [00:21<00:04, 82.83it/s, test=99.5%, test_loss=0.003, train=100.0%, train_loss=0.001]

outcome_architecture/process:  82%|████████▏ | 1634/2000 [00:21<00:04, 88.61it/s, test=99.5%, test_loss=0.003, train=100.0%, train_loss=0.001]

outcome_architecture/process:  82%|████████▏ | 1645/2000 [00:21<00:03, 93.08it/s, test=99.5%, test_loss=0.003, train=100.0%, train_loss=0.001]

outcome_architecture/process:  82%|████████▏ | 1645/2000 [00:21<00:03, 93.08it/s, test=99.9%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  83%|████████▎ | 1655/2000 [00:21<00:05, 68.68it/s, test=99.9%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  83%|████████▎ | 1666/2000 [00:22<00:04, 77.13it/s, test=99.9%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  84%|████████▍ | 1677/2000 [00:22<00:03, 84.04it/s, test=99.9%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  84%|████████▍ | 1688/2000 [00:22<00:03, 89.58it/s, test=99.9%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  85%|████████▍ | 1699/2000 [00:22<00:03, 94.07it/s, test=99.9%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  85%|████████▍ | 1699/2000 [00:22<00:03, 94.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  86%|████████▌ | 1710/2000 [00:22<00:04, 69.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  86%|████████▌ | 1721/2000 [00:22<00:03, 77.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  87%|████████▋ | 1732/2000 [00:22<00:03, 84.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  87%|████████▋ | 1743/2000 [00:22<00:02, 89.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  87%|████████▋ | 1743/2000 [00:23<00:02, 89.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  88%|████████▊ | 1753/2000 [00:23<00:03, 65.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  88%|████████▊ | 1764/2000 [00:23<00:03, 74.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  89%|████████▉ | 1775/2000 [00:23<00:02, 81.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  89%|████████▉ | 1786/2000 [00:23<00:02, 87.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  90%|████████▉ | 1797/2000 [00:23<00:02, 92.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  90%|████████▉ | 1797/2000 [00:23<00:02, 92.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  90%|█████████ | 1807/2000 [00:23<00:02, 68.43it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  91%|█████████ | 1818/2000 [00:23<00:02, 76.73it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  91%|█████████▏| 1829/2000 [00:24<00:02, 83.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  92%|█████████▏| 1839/2000 [00:24<00:01, 86.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  92%|█████████▏| 1839/2000 [00:24<00:01, 86.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  92%|█████████▎| 1850/2000 [00:24<00:02, 66.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  93%|█████████▎| 1861/2000 [00:24<00:01, 74.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  94%|█████████▎| 1872/2000 [00:24<00:01, 82.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  94%|█████████▍| 1883/2000 [00:24<00:01, 86.91it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  95%|█████████▍| 1894/2000 [00:24<00:01, 91.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  95%|█████████▍| 1894/2000 [00:25<00:01, 91.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  95%|█████████▌| 1904/2000 [00:25<00:01, 67.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  96%|█████████▌| 1915/2000 [00:25<00:01, 76.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  96%|█████████▋| 1926/2000 [00:25<00:00, 83.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  97%|█████████▋| 1936/2000 [00:25<00:00, 86.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  97%|█████████▋| 1947/2000 [00:25<00:00, 91.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  97%|█████████▋| 1947/2000 [00:25<00:00, 91.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  98%|█████████▊| 1957/2000 [00:25<00:00, 67.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  98%|█████████▊| 1968/2000 [00:25<00:00, 76.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  99%|█████████▉| 1979/2000 [00:25<00:00, 83.29it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  99%|█████████▉| 1989/2000 [00:26<00:00, 86.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  99%|█████████▉| 1989/2000 [00:26<00:00, 86.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process: 100%|██████████| 2000/2000 [00:26<00:00, 66.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process: 100%|██████████| 2000/2000 [00:26<00:00, 76.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode: 100%|██████████| 4/4 [01:11<00:00, 20.22s/it]

architecture/mode: 100%|██████████| 4/4 [01:11<00:00, 17.81s/it]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,outcome,4.277899,0.0,0.0,0.0,4.278059
1,1,process_architecture,outcome,4.223438,0.0,0.0,0.0,4.223038
2,2,process_architecture,outcome,4.143684,0.0,0.0,0.0,4.142769
3,5,process_architecture,outcome,3.073819,0.0,0.0,0.0,3.063050
4,10,process_architecture,outcome,1.842070,0.0,0.0,0.0,1.820770
...,...,...,...,...,...,...,...,...
187,1800,outcome_architecture,process,0.000175,1.0,1.0,1.0,0.000249
188,1850,outcome_architecture,process,0.000165,1.0,1.0,1.0,0.000210
189,1900,outcome_architecture,process,0.000134,1.0,1.0,1.0,0.000230
190,1950,outcome_architecture,process,0.000117,1.0,1.0,1.0,0.000222
191,2000,outcome_architecture,process,0.000106,1.0,1.0,1.0,0.000168

In [13]:

import json as _json, numpy as _np, pandas as _pd
def _clean(df):
    df = df.drop(columns=["circuit_matrix"], errors="ignore").copy()
    return _json.loads(df.to_json(orient="records"))

_payload = {
    "model_seed": MODEL_SEED,
    "steps": STEPS,
    "final_results": _clean(final_results),
    "history": _clean(history),
}
try:
    _payload["history_2x2"] = _clean(history_2x2)
except NameError:
    _payload["history_2x2"] = None

with open(_OUT_JSON, "w") as _f:
    _json.dump(_payload, _f, indent=2)
print("WROTE", _OUT_JSON)

WROTE /home/hariguru/aayus/trace/results/reachability_seeds/seed_42.json