
# Hand-coded solution reachability: train exactly two models

This notebook answers one precise question:

> The PROCESS and OUTCOME hand-coded Transformers already achieve 100% accuracy.  
> If we keep **each exact hand-coded architecture**, randomize its weights, and train it with its natural supervision, does gradient descent recover a 100%-accurate solution?

We train exactly **two models**:

| Trainable model | Architecture | Training target |
|---|---|---|
| `process_random_base` | exact `HandcodedProcessTransformer` layout | PROCESS / trace continuation |
| `outcome_random_base` | exact `HandcodedOutcomeTransformer` layout | OUTCOME-only continuation |

The two fixed hand-coded models are **references only** and are never optimized.

So the experiment is

\[
\boxed{
\text{2 fixed 100\% references}
+
\text{2 randomly initialized trainable models}
}
\]

with only the latter two undergoing gradient updates.

This is a **reachability experiment**, not yet an architecture-matched causal comparison between PROCESS and OUTCOME.


## 1. Imports and configuration

This notebook uses `handcoded_utils.py`, which contains the exact circuit generator, tokenizer, hand-coded architectures, training loop, and free-running evaluator.

In [1]:

import copy
import importlib
import random
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

import handcoded_utils
importlib.reload(handcoded_utils)

from handcoded_utils import (
    BATCH_SIZE,
    BATCH_SEED,
    DATA_SEED,
    DEPTH,
    LR,
    MODEL_SEED,
    TEST_SEED,
    TEST_SIZE,
    TRAIN_SIZE,
    HandcodedOutcomeTransformer,
    HandcodedProcessTransformer,
    encode_dataset,
    free_run_metrics,
    generate,
    language_model_loss,
    make_batch_schedule,
    make_checkpoints,
    make_circuit_prompts,
    make_circuits,
    make_generation_evaluation,
    make_random_trainable_copy,
    make_tokenizer,
    train_one_model,
)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Main experiment settings.
N_TRAIN = TRAIN_SIZE
N_TEST = TEST_SIZE
STEPS = 2_000
LOSS_EVAL_SIZE = 64
CHECKPOINTS = make_checkpoints(STEPS, animation_checkpoints=40)

print("device:", DEVICE)
print("depth:", DEPTH)
print("train examples:", N_TRAIN)
print("test examples:", N_TEST)
print("steps:", STEPS)
print("loss eval examples:", LOSS_EVAL_SIZE)

device: cuda
depth: 4
train examples: 20000
test examples: 1000
steps: 2000
loss eval examples: 64

/home/hariguru/aayus/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# injected by run_seeds.py -- vary model init only
MODEL_SEED = 45
_OUT_JSON = '/home/hariguru/aayus/trace/results/reachability_seeds/seed_45.json'
print('MODEL_SEED =', MODEL_SEED)

MODEL_SEED = 45


## 2. Build the same dataset for both models

A circuit is

$$
s_t=\Phi(s_{t-1},g_t),\qquad t=1,\ldots,D.
$$

Both models receive the same prompt

```text
S0 g1 g2 ... gD <SEP>
```

but their supervised continuations differ.

PROCESS:

```text
g1 S1 g2 S2 ... gD SD <COLON> SD <EOS>
```

OUTCOME:

```text
<COLON> SD <EOS>
```

The underlying circuits, train/test split, and minibatch schedule are shared.

In [3]:

tokenizer = make_tokenizer()

train_circuits = make_circuits(N_TRAIN, DATA_SEED, DEPTH)
test_circuits = make_circuits(N_TEST, TEST_SEED, DEPTH)
example = test_circuits[0]

training_data = {
    mode: encode_dataset(train_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

# Held-out teacher-forced loss uses the test split. The training helper samples
# a deterministic prefix of this batch at checkpoints for speed.
test_loss_data = {
    mode: encode_dataset(test_circuits, tokenizer, mode).to(DEVICE)
    for mode in ("process", "outcome")
}

batch_schedule = make_batch_schedule(
    N_TRAIN, STEPS, BATCH_SIZE, BATCH_SEED
)

train_eval = make_generation_evaluation(
    train_circuits[:min(300, len(train_circuits))],
    tokenizer,
    DEVICE,
)

test_eval = make_generation_evaluation(
    test_circuits,
    tokenizer,
    DEVICE,
)

circuit_prompts = make_circuit_prompts(
    example.gates,
    tokenizer,
    DEVICE,
)

print("Prompt :", tokenizer.decode(tokenizer.prompt(example)))
print("PROCESS:", tokenizer.decode(tokenizer.continuation(example, "process")))
print("OUTCOME:", tokenizer.decode(tokenizer.continuation(example, "outcome")))

Prompt : S1011 s02 c31 c31 t302 <SEP>
PROCESS: s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>
OUTCOME: <COLON> S1001 <EOS>


## 3. Fixed hand-coded references

These two models encode perfect algorithms directly in their weights.

### PROCESS reference

`HandcodedProcessTransformer`

- one causal attention/MLP block,
- four fixed attention heads,
- one ReLU unit for each `(state, gate)` pair,
- autoregressive reuse of the same block to emit intermediate states.

### OUTCOME reference

`HandcodedOutcomeTransformer`

- one causal attention/MLP block per circuit step,
- two attention heads per block,
- intermediate states remain internal to the residual stream,
- only the final answer is emitted.

They are not trained below. They establish that a 100% solution exists in each architecture class.

In [4]:

process_reference = HandcodedProcessTransformer(
    tokenizer, DEPTH
).to(DEVICE)

outcome_reference = HandcodedOutcomeTransformer(
    tokenizer, DEPTH
).to(DEVICE)

reference_rows = []

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    reference_rows.append({
        "model": name,
        "mode": mode,
        "answer_accuracy": metrics["final_answer"],
        "exact_continuation": metrics["exact_continuation"],
    })

pd.DataFrame(reference_rows)

           model     mode  answer_accuracy  exact_continuation
0  Fixed PROCESS  process              1.0                 1.0
1  Fixed OUTCOME  outcome              1.0                 1.0


Expected result:

$$
\operatorname{Acc}(\theta^\star_{\rm P})
=
\operatorname{Acc}(\theta^\star_{\rm O})
=
100\%.
$$

That is the realizability baseline.


## 4. Turn each exact hand-coded architecture into a random trainable model

This is the crucial correction.

We do **not** call `build_random_learned_model()`. That would create an unrelated ordinary one-layer Transformer.

Instead, `make_random_trainable_copy()`:

1. deep-copies the exact hand-coded model,
2. converts its stored weight buffers into `nn.Parameter`s,
3. randomly initializes those tensors.

Therefore the computational graph and tensor layout are inherited directly from the corresponding constructive model.

In [5]:

process_random_base = make_random_trainable_copy(
    process_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

outcome_random_base = make_random_trainable_copy(
    outcome_reference,
    seed=MODEL_SEED,
    init_std=0.02,
    device=DEVICE,
)

def trainable_params(model):
    return sum(p.numel() for p in model.parameters())

def stored_scalars(model):
    return sum(t.numel() for t in model.state_dict().values())

summary = pd.DataFrame([
    {
        "model": "Fixed PROCESS reference",
        "trainable_parameters": trainable_params(process_reference),
        "stored_scalars": stored_scalars(process_reference),
        "max_length": process_reference.max_length,
    },
    {
        "model": "Random trainable PROCESS architecture",
        "trainable_parameters": trainable_params(process_random_base),
        "stored_scalars": stored_scalars(process_random_base),
        "max_length": process_random_base.max_length,
    },
    {
        "model": "Fixed OUTCOME reference",
        "trainable_parameters": trainable_params(outcome_reference),
        "stored_scalars": stored_scalars(outcome_reference),
        "max_length": outcome_reference.max_length,
    },
    {
        "model": "Random trainable OUTCOME architecture",
        "trainable_parameters": trainable_params(outcome_random_base),
        "stored_scalars": stored_scalars(outcome_random_base),
        "max_length": outcome_random_base.max_length,
    },
])

summary

,model,trainable_parameters,stored_scalars,max_length
0,Fixed PROCESS reference,0,441664,16
1,Random trainable PROCESS architecture,441664,441664,16
2,Fixed OUTCOME reference,0,3588000,8
3,Random trainable OUTCOME architecture,3588000,3588000,8


A fixed reference reports zero **trainable** parameters because its constructed weights are registered as buffers. That does not mean it has zero weights. `stored_scalars` is the more relevant size diagnostic for the fixed models.


## 5. Sanity check: the trainable parameterization really contains the oracle

A useful stronger check is to convert the fixed buffers into trainable parameters **without changing their values**.

If the resulting model produces exactly the same logits as the fixed model, then the hand-coded optimum literally lies inside the trainable parameterization.

In [6]:

def make_trainable_oracle_copy(model, device):
    trainable = copy.deepcopy(model).cpu()

    def convert(module):
        for name, buffer in list(module._buffers.items()):
            if buffer is None:
                continue
            value = buffer.detach().clone()
            del module._buffers[name]
            module.register_parameter(name, torch.nn.Parameter(value))
        for child in module.children():
            convert(child)

    convert(trainable)
    return trainable.to(device)


process_oracle_trainable = make_trainable_oracle_copy(
    process_reference, DEVICE
)
outcome_oracle_trainable = make_trainable_oracle_copy(
    outcome_reference, DEVICE
)

prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

with torch.no_grad():
    process_error = (
        process_reference(prompt) - process_oracle_trainable(prompt)
    ).abs().max().item()

    outcome_error = (
        outcome_reference(prompt) - outcome_oracle_trainable(prompt)
    ).abs().max().item()

print("PROCESS max logit difference:", process_error)
print("OUTCOME max logit difference:", outcome_error)

assert process_error == 0.0
assert outcome_error == 0.0

PROCESS max logit difference: 0.0
OUTCOME max logit difference: 0.0


This gives the precise existence statement:

\[
\exists\,\theta^\star_{\rm P}\in\Theta_{\rm P},
\qquad
\exists\,\theta^\star_{\rm O}\in\Theta_{\rm O},
\]

with both achieving perfect execution.

The training experiment now asks whether random initialization reaches either solution class.


## 6. Train exactly two models

There is no `run_experiment(base, modes=("outcome","process"))` here.

That function would train two copies of the **same base architecture**.

Instead we make two explicit calls:

\[
\boxed{
\text{PROCESS architecture}+\text{PROCESS supervision}
}
\]

and

\[
\boxed{
\text{OUTCOME architecture}+\text{OUTCOME supervision}.
}
\]

So exactly two optimization runs occur.

In [7]:

trained_process, process_history = train_one_model(
    process_random_base,
    "process",
    training_data["process"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="process_architecture",
    test_loss_data=test_loss_data["process"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

trained_outcome, outcome_history = train_one_model(
    outcome_random_base,
    "outcome",
    training_data["outcome"],
    batch_schedule,
    LR,
    CHECKPOINTS,
    train_eval,
    test_eval,
    tokenizer,
    circuit_prompts,
    architecture="outcome_architecture",
    test_loss_data=test_loss_data["outcome"],
    loss_eval_size=LOSS_EVAL_SIZE,
)

history = pd.concat(
    [process_history, outcome_history],
    ignore_index=True,
)

display(
    history.drop(columns=["circuit_matrix"], errors="ignore")
)

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=7.7%, test_loss=4.262, train=4.0%, train_loss=4.261]

process_architecture/process:   0%|          | 1/2000 [00:00<05:20,  6.23it/s, test=7.7%, test_loss=4.262, train=4.0%, train_loss=4.261]

process_architecture/process:   0%|          | 1/2000 [00:00<05:20,  6.23it/s, test=7.7%, test_loss=4.239, train=4.0%, train_loss=4.238]

process_architecture/process:   0%|          | 1/2000 [00:00<05:20,  6.23it/s, test=0.0%, test_loss=3.950, train=0.0%, train_loss=3.955]

process_architecture/process:   0%|          | 5/2000 [00:00<01:37, 20.42it/s, test=0.0%, test_loss=3.950, train=0.0%, train_loss=3.955]

process_architecture/process:   0%|          | 5/2000 [00:00<01:37, 20.42it/s, test=0.0%, test_loss=3.606, train=0.0%, train_loss=3.626]

process_architecture/process:   0%|          | 5/2000 [00:00<01:37, 20.42it/s, test=6.9%, test_loss=2.913, train=9.0%, train_loss=2.913]

process_architecture/process:   1%|          | 20/2000 [00:00<00:32, 60.48it/s, test=6.9%, test_loss=2.913, train=9.0%, train_loss=2.913]

process_architecture/process:   1%|          | 20/2000 [00:00<00:32, 60.48it/s, test=6.2%, test_loss=2.783, train=9.0%, train_loss=2.790]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:27, 72.16it/s, test=6.2%, test_loss=2.783, train=9.0%, train_loss=2.790]

process_architecture/process:   2%|▏         | 30/2000 [00:00<00:27, 72.16it/s, test=7.5%, test_loss=2.615, train=7.0%, train_loss=2.647]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:20, 95.35it/s, test=7.5%, test_loss=2.615, train=7.0%, train_loss=2.647]

process_architecture/process:   4%|▎         | 70/2000 [00:00<00:15, 122.89it/s, test=7.5%, test_loss=2.615, train=7.0%, train_loss=2.647]

process_architecture/process:   4%|▎         | 70/2000 [00:00<00:15, 122.89it/s, test=9.8%, test_loss=2.447, train=8.0%, train_loss=2.454]

process_architecture/process:   4%|▍         | 83/2000 [00:00<00:16, 118.42it/s, test=9.8%, test_loss=2.447, train=8.0%, train_loss=2.454]

process_architecture/process:   4%|▍         | 83/2000 [00:01<00:16, 118.42it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   5%|▌         | 100/2000 [00:01<00:15, 119.77it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   6%|▌         | 120/2000 [00:01<00:13, 139.76it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   7%|▋         | 140/2000 [00:01<00:12, 154.85it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   7%|▋         | 140/2000 [00:01<00:12, 154.85it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:   8%|▊         | 156/2000 [00:01<00:12, 142.26it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:   9%|▉         | 176/2000 [00:01<00:11, 156.22it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:  10%|▉         | 196/2000 [00:01<00:10, 166.93it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:  10%|▉         | 196/2000 [00:01<00:10, 166.93it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  11%|█         | 214/2000 [00:01<00:11, 150.89it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  12%|█▏        | 234/2000 [00:01<00:10, 161.94it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  12%|█▏        | 234/2000 [00:01<00:10, 161.94it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  13%|█▎        | 251/2000 [00:01<00:11, 148.03it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  14%|█▎        | 270/2000 [00:02<00:10, 158.82it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  14%|█▍        | 290/2000 [00:02<00:10, 168.46it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  14%|█▍        | 290/2000 [00:02<00:10, 168.46it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  15%|█▌        | 308/2000 [00:02<00:11, 153.49it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  16%|█▋        | 328/2000 [00:02<00:10, 164.76it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  17%|█▋        | 348/2000 [00:02<00:09, 173.47it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  17%|█▋        | 348/2000 [00:02<00:09, 173.47it/s, test=97.1%, test_loss=0.011, train=97.0%, train_loss=0.010]

process_architecture/process:  18%|█▊        | 366/2000 [00:02<00:10, 155.08it/s, test=97.1%, test_loss=0.011, train=97.0%, train_loss=0.010]

process_architecture/process:  19%|█▉        | 385/2000 [00:02<00:09, 163.99it/s, test=97.1%, test_loss=0.011, train=97.0%, train_loss=0.010]

process_architecture/process:  19%|█▉        | 385/2000 [00:02<00:09, 163.99it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  20%|██        | 402/2000 [00:02<00:10, 147.81it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  21%|██        | 422/2000 [00:03<00:09, 159.64it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  22%|██▏       | 442/2000 [00:03<00:09, 168.28it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  22%|██▏       | 442/2000 [00:03<00:09, 168.28it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  23%|██▎       | 460/2000 [00:03<00:10, 152.90it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  24%|██▍       | 480/2000 [00:03<00:09, 162.63it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  24%|██▍       | 480/2000 [00:03<00:09, 162.63it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  25%|██▌       | 500/2000 [00:03<00:09, 153.35it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  26%|██▌       | 521/2000 [00:03<00:08, 166.59it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 542/2000 [00:03<00:08, 176.93it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 542/2000 [00:03<00:08, 176.93it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  28%|██▊       | 561/2000 [00:03<00:08, 160.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  29%|██▉       | 582/2000 [00:03<00:08, 172.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  29%|██▉       | 582/2000 [00:04<00:08, 172.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  30%|███       | 600/2000 [00:04<00:08, 157.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  31%|███       | 621/2000 [00:04<00:08, 169.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 641/2000 [00:04<00:07, 176.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 641/2000 [00:04<00:07, 176.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  33%|███▎      | 660/2000 [00:04<00:08, 156.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 680/2000 [00:04<00:07, 167.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 680/2000 [00:04<00:07, 167.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▌      | 700/2000 [00:04<00:08, 153.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 719/2000 [00:04<00:07, 162.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 739/2000 [00:04<00:07, 170.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 739/2000 [00:05<00:07, 170.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 757/2000 [00:05<00:08, 152.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 777/2000 [00:05<00:07, 163.39it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 797/2000 [00:05<00:07, 171.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|███▉      | 797/2000 [00:05<00:07, 171.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 815/2000 [00:05<00:07, 155.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 835/2000 [00:05<00:06, 166.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 835/2000 [00:05<00:06, 166.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  43%|████▎     | 853/2000 [00:05<00:07, 148.60it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▎     | 873/2000 [00:05<00:07, 159.69it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 893/2000 [00:05<00:06, 169.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▍     | 893/2000 [00:05<00:06, 169.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 911/2000 [00:06<00:07, 153.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▋     | 930/2000 [00:06<00:06, 160.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 949/2000 [00:06<00:06, 168.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 949/2000 [00:06<00:06, 168.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 967/2000 [00:06<00:06, 151.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 987/2000 [00:06<00:06, 163.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 987/2000 [00:06<00:06, 163.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1004/2000 [00:06<00:06, 148.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1024/2000 [00:06<00:06, 160.49it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1044/2000 [00:06<00:05, 169.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1044/2000 [00:06<00:05, 169.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1062/2000 [00:06<00:06, 152.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1082/2000 [00:07<00:05, 164.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1082/2000 [00:07<00:05, 164.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1100/2000 [00:07<00:06, 148.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1120/2000 [00:07<00:05, 160.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1140/2000 [00:07<00:05, 170.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1140/2000 [00:07<00:05, 170.05it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1158/2000 [00:07<00:05, 154.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1178/2000 [00:07<00:04, 164.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1197/2000 [00:07<00:04, 171.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|█████▉    | 1197/2000 [00:07<00:04, 171.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1215/2000 [00:07<00:05, 154.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1235/2000 [00:08<00:04, 164.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1235/2000 [00:08<00:04, 164.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1253/2000 [00:08<00:04, 151.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▎   | 1273/2000 [00:08<00:04, 162.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1293/2000 [00:08<00:04, 171.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▍   | 1293/2000 [00:08<00:04, 171.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1311/2000 [00:08<00:04, 154.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1331/2000 [00:08<00:04, 165.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1331/2000 [00:08<00:04, 165.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1350/2000 [00:08<00:04, 150.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1370/2000 [00:08<00:03, 161.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|██████▉   | 1390/2000 [00:09<00:03, 169.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|██████▉   | 1390/2000 [00:09<00:03, 169.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1408/2000 [00:09<00:03, 154.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████▏  | 1428/2000 [00:09<00:03, 164.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1448/2000 [00:09<00:03, 171.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1448/2000 [00:09<00:03, 171.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1466/2000 [00:09<00:03, 154.82it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1486/2000 [00:09<00:03, 165.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1486/2000 [00:09<00:03, 165.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1504/2000 [00:09<00:03, 150.67it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1524/2000 [00:09<00:02, 161.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1544/2000 [00:09<00:02, 170.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1544/2000 [00:10<00:02, 170.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1562/2000 [00:10<00:02, 154.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1582/2000 [00:10<00:02, 165.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1582/2000 [00:10<00:02, 165.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1600/2000 [00:10<00:02, 151.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1620/2000 [00:10<00:02, 162.12it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1640/2000 [00:10<00:02, 170.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1640/2000 [00:10<00:02, 170.27it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1658/2000 [00:10<00:02, 153.24it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1677/2000 [00:10<00:01, 162.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1697/2000 [00:10<00:01, 170.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▍ | 1697/2000 [00:10<00:01, 170.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1715/2000 [00:11<00:01, 152.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1734/2000 [00:11<00:01, 160.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1734/2000 [00:11<00:01, 160.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1751/2000 [00:11<00:01, 142.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▊ | 1771/2000 [00:11<00:01, 154.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1790/2000 [00:11<00:01, 163.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1790/2000 [00:11<00:01, 163.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|█████████ | 1807/2000 [00:11<00:01, 147.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████▏| 1826/2000 [00:11<00:01, 158.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1845/2000 [00:11<00:00, 166.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1845/2000 [00:11<00:00, 166.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1863/2000 [00:12<00:00, 150.32it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1882/2000 [00:12<00:00, 160.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1882/2000 [00:12<00:00, 160.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▌| 1900/2000 [00:12<00:00, 147.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1919/2000 [00:12<00:00, 157.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1938/2000 [00:12<00:00, 164.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1938/2000 [00:12<00:00, 164.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1955/2000 [00:12<00:00, 145.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1975/2000 [00:12<00:00, 157.81it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1994/2000 [00:12<00:00, 164.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1994/2000 [00:12<00:00, 164.17it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 154.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.509, train=0.0%, train_loss=3.513]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=14.787, train=0.0%, train_loss=14.726]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.662, train=0.0%, train_loss=3.665]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:53, 37.18it/s, test=0.0%, test_loss=3.662, train=0.0%, train_loss=3.665]

outcome_architecture/outcome:   0%|          | 5/2000 [00:00<00:53, 37.18it/s, test=0.0%, test_loss=1.142, train=0.0%, train_loss=1.138]

outcome_architecture/outcome:   1%|          | 12/2000 [00:00<00:38, 52.13it/s, test=0.0%, test_loss=1.142, train=0.0%, train_loss=1.138]

outcome_architecture/outcome:   1%|          | 12/2000 [00:00<00:38, 52.13it/s, test=5.1%, test_loss=0.932, train=6.3%, train_loss=0.926]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:33, 59.57it/s, test=5.1%, test_loss=0.932, train=6.3%, train_loss=0.926]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:33, 59.57it/s, test=7.6%, test_loss=0.955, train=4.7%, train_loss=0.971]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:31, 61.98it/s, test=7.6%, test_loss=0.955, train=4.7%, train_loss=0.971]

outcome_architecture/outcome:   2%|▏         | 37/2000 [00:00<00:26, 74.09it/s, test=7.6%, test_loss=0.955, train=4.7%, train_loss=0.971]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:23, 82.23it/s, test=7.6%, test_loss=0.955, train=4.7%, train_loss=0.971]

outcome_architecture/outcome:   2%|▏         | 47/2000 [00:00<00:23, 82.23it/s, test=0.0%, test_loss=4.416, train=0.0%, train_loss=4.503]

outcome_architecture/outcome:   3%|▎         | 56/2000 [00:00<00:24, 77.79it/s, test=0.0%, test_loss=4.416, train=0.0%, train_loss=4.503]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:00<00:23, 82.15it/s, test=0.0%, test_loss=4.416, train=0.0%, train_loss=4.503]

outcome_architecture/outcome:   3%|▎         | 66/2000 [00:01<00:23, 82.15it/s, test=0.0%, test_loss=1.860, train=0.0%, train_loss=1.887]

outcome_architecture/outcome:   4%|▍         | 75/2000 [00:01<00:24, 78.12it/s, test=0.0%, test_loss=1.860, train=0.0%, train_loss=1.887]

outcome_architecture/outcome:   4%|▍         | 85/2000 [00:01<00:22, 83.57it/s, test=0.0%, test_loss=1.860, train=0.0%, train_loss=1.887]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 87.51it/s, test=0.0%, test_loss=1.860, train=0.0%, train_loss=1.887]

outcome_architecture/outcome:   5%|▍         | 95/2000 [00:01<00:21, 87.51it/s, test=2.0%, test_loss=0.990, train=2.0%, train_loss=1.041]

outcome_architecture/outcome:   5%|▌         | 104/2000 [00:01<00:23, 81.71it/s, test=2.0%, test_loss=0.990, train=2.0%, train_loss=1.041]

outcome_architecture/outcome:   6%|▌         | 113/2000 [00:01<00:22, 82.29it/s, test=2.0%, test_loss=0.990, train=2.0%, train_loss=1.041]

outcome_architecture/outcome:   6%|▌         | 123/2000 [00:01<00:21, 86.50it/s, test=2.0%, test_loss=0.990, train=2.0%, train_loss=1.041]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:20, 89.37it/s, test=2.0%, test_loss=0.990, train=2.0%, train_loss=1.041]

outcome_architecture/outcome:   7%|▋         | 143/2000 [00:01<00:20, 91.52it/s, test=2.0%, test_loss=0.990, train=2.0%, train_loss=1.041]

outcome_architecture/outcome:   7%|▋         | 143/2000 [00:01<00:20, 91.52it/s, test=11.3%, test_loss=0.899, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:   8%|▊         | 153/2000 [00:01<00:21, 84.96it/s, test=11.3%, test_loss=0.899, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:   8%|▊         | 163/2000 [00:02<00:20, 88.87it/s, test=11.3%, test_loss=0.899, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:   9%|▊         | 173/2000 [00:02<00:19, 91.83it/s, test=11.3%, test_loss=0.899, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:   9%|▉         | 183/2000 [00:02<00:19, 93.87it/s, test=11.3%, test_loss=0.899, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  10%|▉         | 193/2000 [00:02<00:19, 95.08it/s, test=11.3%, test_loss=0.899, train=11.0%, train_loss=0.916]

outcome_architecture/outcome:  10%|▉         | 193/2000 [00:02<00:19, 95.08it/s, test=11.9%, test_loss=0.894, train=11.7%, train_loss=0.909]

outcome_architecture/outcome:  10%|█         | 203/2000 [00:02<00:20, 87.01it/s, test=11.9%, test_loss=0.894, train=11.7%, train_loss=0.909]

outcome_architecture/outcome:  11%|█         | 213/2000 [00:02<00:19, 89.99it/s, test=11.9%, test_loss=0.894, train=11.7%, train_loss=0.909]

outcome_architecture/outcome:  11%|█         | 223/2000 [00:02<00:19, 92.07it/s, test=11.9%, test_loss=0.894, train=11.7%, train_loss=0.909]

outcome_architecture/outcome:  12%|█▏        | 233/2000 [00:02<00:18, 93.97it/s, test=11.9%, test_loss=0.894, train=11.7%, train_loss=0.909]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:18, 95.37it/s, test=11.9%, test_loss=0.894, train=11.7%, train_loss=0.909]

outcome_architecture/outcome:  12%|█▏        | 243/2000 [00:02<00:18, 95.37it/s, test=10.2%, test_loss=0.885, train=10.7%, train_loss=0.891]

outcome_architecture/outcome:  13%|█▎        | 253/2000 [00:03<00:20, 87.13it/s, test=10.2%, test_loss=0.885, train=10.7%, train_loss=0.891]

outcome_architecture/outcome:  13%|█▎        | 263/2000 [00:03<00:19, 89.84it/s, test=10.2%, test_loss=0.885, train=10.7%, train_loss=0.891]

outcome_architecture/outcome:  14%|█▎        | 273/2000 [00:03<00:18, 91.66it/s, test=10.2%, test_loss=0.885, train=10.7%, train_loss=0.891]

outcome_architecture/outcome:  14%|█▍        | 283/2000 [00:03<00:18, 93.10it/s, test=10.2%, test_loss=0.885, train=10.7%, train_loss=0.891]

outcome_architecture/outcome:  15%|█▍        | 293/2000 [00:03<00:18, 94.40it/s, test=10.2%, test_loss=0.885, train=10.7%, train_loss=0.891]

outcome_architecture/outcome:  15%|█▍        | 293/2000 [00:03<00:18, 94.40it/s, test=11.0%, test_loss=0.896, train=10.7%, train_loss=0.901]

outcome_architecture/outcome:  15%|█▌        | 303/2000 [00:03<00:19, 86.34it/s, test=11.0%, test_loss=0.896, train=10.7%, train_loss=0.901]

outcome_architecture/outcome:  16%|█▌        | 313/2000 [00:03<00:18, 89.61it/s, test=11.0%, test_loss=0.896, train=10.7%, train_loss=0.901]

outcome_architecture/outcome:  16%|█▌        | 323/2000 [00:03<00:18, 91.59it/s, test=11.0%, test_loss=0.896, train=10.7%, train_loss=0.901]

outcome_architecture/outcome:  17%|█▋        | 333/2000 [00:03<00:17, 92.73it/s, test=11.0%, test_loss=0.896, train=10.7%, train_loss=0.901]

outcome_architecture/outcome:  17%|█▋        | 343/2000 [00:03<00:17, 94.11it/s, test=11.0%, test_loss=0.896, train=10.7%, train_loss=0.901]

outcome_architecture/outcome:  17%|█▋        | 343/2000 [00:04<00:17, 94.11it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  18%|█▊        | 353/2000 [00:04<00:19, 86.53it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  18%|█▊        | 363/2000 [00:04<00:18, 89.38it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  19%|█▊        | 373/2000 [00:04<00:17, 91.34it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  19%|█▉        | 383/2000 [00:04<00:17, 92.92it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  20%|█▉        | 393/2000 [00:04<00:17, 94.46it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.909]

outcome_architecture/outcome:  20%|█▉        | 393/2000 [00:04<00:17, 94.46it/s, test=10.9%, test_loss=0.904, train=10.7%, train_loss=0.912]

outcome_architecture/outcome:  20%|██        | 403/2000 [00:04<00:18, 86.72it/s, test=10.9%, test_loss=0.904, train=10.7%, train_loss=0.912]

outcome_architecture/outcome:  21%|██        | 413/2000 [00:04<00:17, 89.76it/s, test=10.9%, test_loss=0.904, train=10.7%, train_loss=0.912]

outcome_architecture/outcome:  21%|██        | 423/2000 [00:04<00:17, 91.70it/s, test=10.9%, test_loss=0.904, train=10.7%, train_loss=0.912]

outcome_architecture/outcome:  22%|██▏       | 433/2000 [00:04<00:16, 93.64it/s, test=10.9%, test_loss=0.904, train=10.7%, train_loss=0.912]

outcome_architecture/outcome:  22%|██▏       | 443/2000 [00:05<00:16, 95.11it/s, test=10.9%, test_loss=0.904, train=10.7%, train_loss=0.912]

outcome_architecture/outcome:  22%|██▏       | 443/2000 [00:05<00:16, 95.11it/s, test=11.1%, test_loss=0.901, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  23%|██▎       | 453/2000 [00:05<00:17, 86.99it/s, test=11.1%, test_loss=0.901, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  23%|██▎       | 462/2000 [00:05<00:17, 87.35it/s, test=11.1%, test_loss=0.901, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  24%|██▎       | 472/2000 [00:05<00:16, 90.73it/s, test=11.1%, test_loss=0.901, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  24%|██▍       | 482/2000 [00:05<00:16, 93.08it/s, test=11.1%, test_loss=0.901, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  25%|██▍       | 492/2000 [00:05<00:16, 93.50it/s, test=11.1%, test_loss=0.901, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  25%|██▍       | 492/2000 [00:05<00:16, 93.50it/s, test=11.0%, test_loss=0.915, train=10.0%, train_loss=0.925]

outcome_architecture/outcome:  25%|██▌       | 502/2000 [00:05<00:17, 85.70it/s, test=11.0%, test_loss=0.915, train=10.0%, train_loss=0.925]

outcome_architecture/outcome:  26%|██▌       | 512/2000 [00:05<00:16, 88.95it/s, test=11.0%, test_loss=0.915, train=10.0%, train_loss=0.925]

outcome_architecture/outcome:  26%|██▌       | 522/2000 [00:05<00:16, 91.81it/s, test=11.0%, test_loss=0.915, train=10.0%, train_loss=0.925]

outcome_architecture/outcome:  27%|██▋       | 532/2000 [00:06<00:15, 93.85it/s, test=11.0%, test_loss=0.915, train=10.0%, train_loss=0.925]

outcome_architecture/outcome:  27%|██▋       | 542/2000 [00:06<00:15, 94.74it/s, test=11.0%, test_loss=0.915, train=10.0%, train_loss=0.925]

outcome_architecture/outcome:  27%|██▋       | 542/2000 [00:06<00:15, 94.74it/s, test=12.2%, test_loss=0.907, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  28%|██▊       | 552/2000 [00:06<00:16, 86.58it/s, test=12.2%, test_loss=0.907, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  28%|██▊       | 562/2000 [00:06<00:16, 89.38it/s, test=12.2%, test_loss=0.907, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  29%|██▊       | 572/2000 [00:06<00:15, 91.83it/s, test=12.2%, test_loss=0.907, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  29%|██▉       | 582/2000 [00:06<00:15, 93.83it/s, test=12.2%, test_loss=0.907, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  30%|██▉       | 592/2000 [00:06<00:14, 94.92it/s, test=12.2%, test_loss=0.907, train=11.0%, train_loss=0.898]

outcome_architecture/outcome:  30%|██▉       | 592/2000 [00:06<00:14, 94.92it/s, test=12.2%, test_loss=0.879, train=9.0%, train_loss=0.887]

outcome_architecture/outcome:  30%|███       | 602/2000 [00:06<00:16, 86.76it/s, test=12.2%, test_loss=0.879, train=9.0%, train_loss=0.887]

outcome_architecture/outcome:  31%|███       | 612/2000 [00:06<00:15, 89.37it/s, test=12.2%, test_loss=0.879, train=9.0%, train_loss=0.887]

outcome_architecture/outcome:  31%|███       | 622/2000 [00:07<00:14, 92.05it/s, test=12.2%, test_loss=0.879, train=9.0%, train_loss=0.887]

outcome_architecture/outcome:  32%|███▏      | 632/2000 [00:07<00:14, 93.63it/s, test=12.2%, test_loss=0.879, train=9.0%, train_loss=0.887]

outcome_architecture/outcome:  32%|███▏      | 642/2000 [00:07<00:14, 95.17it/s, test=12.2%, test_loss=0.879, train=9.0%, train_loss=0.887]

outcome_architecture/outcome:  32%|███▏      | 642/2000 [00:07<00:14, 95.17it/s, test=11.6%, test_loss=0.882, train=9.3%, train_loss=0.883]

outcome_architecture/outcome:  33%|███▎      | 652/2000 [00:07<00:15, 87.44it/s, test=11.6%, test_loss=0.882, train=9.3%, train_loss=0.883]

outcome_architecture/outcome:  33%|███▎      | 662/2000 [00:07<00:14, 90.67it/s, test=11.6%, test_loss=0.882, train=9.3%, train_loss=0.883]

outcome_architecture/outcome:  34%|███▎      | 672/2000 [00:07<00:14, 93.13it/s, test=11.6%, test_loss=0.882, train=9.3%, train_loss=0.883]

outcome_architecture/outcome:  34%|███▍      | 682/2000 [00:07<00:13, 94.81it/s, test=11.6%, test_loss=0.882, train=9.3%, train_loss=0.883]

outcome_architecture/outcome:  35%|███▍      | 692/2000 [00:07<00:13, 95.79it/s, test=11.6%, test_loss=0.882, train=9.3%, train_loss=0.883]

outcome_architecture/outcome:  35%|███▍      | 692/2000 [00:07<00:13, 95.79it/s, test=13.2%, test_loss=0.885, train=10.0%, train_loss=0.905]

outcome_architecture/outcome:  35%|███▌      | 702/2000 [00:07<00:14, 87.68it/s, test=13.2%, test_loss=0.885, train=10.0%, train_loss=0.905]

outcome_architecture/outcome:  36%|███▌      | 712/2000 [00:08<00:14, 90.81it/s, test=13.2%, test_loss=0.885, train=10.0%, train_loss=0.905]

outcome_architecture/outcome:  36%|███▌      | 722/2000 [00:08<00:13, 93.02it/s, test=13.2%, test_loss=0.885, train=10.0%, train_loss=0.905]

outcome_architecture/outcome:  37%|███▋      | 732/2000 [00:08<00:13, 94.55it/s, test=13.2%, test_loss=0.885, train=10.0%, train_loss=0.905]

outcome_architecture/outcome:  37%|███▋      | 742/2000 [00:08<00:13, 95.88it/s, test=13.2%, test_loss=0.885, train=10.0%, train_loss=0.905]

outcome_architecture/outcome:  37%|███▋      | 742/2000 [00:08<00:13, 95.88it/s, test=12.2%, test_loss=0.898, train=12.3%, train_loss=0.905]

outcome_architecture/outcome:  38%|███▊      | 752/2000 [00:08<00:14, 88.12it/s, test=12.2%, test_loss=0.898, train=12.3%, train_loss=0.905]

outcome_architecture/outcome:  38%|███▊      | 762/2000 [00:08<00:13, 90.75it/s, test=12.2%, test_loss=0.898, train=12.3%, train_loss=0.905]

outcome_architecture/outcome:  39%|███▊      | 772/2000 [00:08<00:13, 92.79it/s, test=12.2%, test_loss=0.898, train=12.3%, train_loss=0.905]

outcome_architecture/outcome:  39%|███▉      | 782/2000 [00:08<00:12, 94.23it/s, test=12.2%, test_loss=0.898, train=12.3%, train_loss=0.905]

outcome_architecture/outcome:  40%|███▉      | 792/2000 [00:08<00:12, 95.11it/s, test=12.2%, test_loss=0.898, train=12.3%, train_loss=0.905]

outcome_architecture/outcome:  40%|███▉      | 792/2000 [00:09<00:12, 95.11it/s, test=12.0%, test_loss=0.882, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  40%|████      | 802/2000 [00:09<00:13, 86.07it/s, test=12.0%, test_loss=0.882, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  41%|████      | 812/2000 [00:09<00:13, 87.86it/s, test=12.0%, test_loss=0.882, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  41%|████      | 822/2000 [00:09<00:13, 90.59it/s, test=12.0%, test_loss=0.882, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  42%|████▏     | 832/2000 [00:09<00:12, 92.87it/s, test=12.0%, test_loss=0.882, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  42%|████▏     | 842/2000 [00:09<00:12, 93.53it/s, test=12.0%, test_loss=0.882, train=11.0%, train_loss=0.888]

outcome_architecture/outcome:  42%|████▏     | 842/2000 [00:09<00:12, 93.53it/s, test=13.9%, test_loss=0.886, train=12.7%, train_loss=0.857]

outcome_architecture/outcome:  43%|████▎     | 852/2000 [00:09<00:13, 86.37it/s, test=13.9%, test_loss=0.886, train=12.7%, train_loss=0.857]

outcome_architecture/outcome:  43%|████▎     | 862/2000 [00:09<00:12, 89.49it/s, test=13.9%, test_loss=0.886, train=12.7%, train_loss=0.857]

outcome_architecture/outcome:  44%|████▎     | 872/2000 [00:09<00:12, 91.75it/s, test=13.9%, test_loss=0.886, train=12.7%, train_loss=0.857]

outcome_architecture/outcome:  44%|████▍     | 882/2000 [00:09<00:11, 94.06it/s, test=13.9%, test_loss=0.886, train=12.7%, train_loss=0.857]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:09<00:11, 94.54it/s, test=13.9%, test_loss=0.886, train=12.7%, train_loss=0.857]

outcome_architecture/outcome:  45%|████▍     | 892/2000 [00:10<00:11, 94.54it/s, test=15.3%, test_loss=0.874, train=10.7%, train_loss=0.871]

outcome_architecture/outcome:  45%|████▌     | 902/2000 [00:10<00:12, 86.98it/s, test=15.3%, test_loss=0.874, train=10.7%, train_loss=0.871]

outcome_architecture/outcome:  46%|████▌     | 912/2000 [00:10<00:12, 90.12it/s, test=15.3%, test_loss=0.874, train=10.7%, train_loss=0.871]

outcome_architecture/outcome:  46%|████▌     | 922/2000 [00:10<00:11, 92.53it/s, test=15.3%, test_loss=0.874, train=10.7%, train_loss=0.871]

outcome_architecture/outcome:  47%|████▋     | 932/2000 [00:10<00:11, 93.74it/s, test=15.3%, test_loss=0.874, train=10.7%, train_loss=0.871]

outcome_architecture/outcome:  47%|████▋     | 943/2000 [00:10<00:10, 97.43it/s, test=15.3%, test_loss=0.874, train=10.7%, train_loss=0.871]

outcome_architecture/outcome:  47%|████▋     | 943/2000 [00:10<00:10, 97.43it/s, test=15.4%, test_loss=0.862, train=14.0%, train_loss=0.870]

outcome_architecture/outcome:  48%|████▊     | 953/2000 [00:10<00:11, 90.45it/s, test=15.4%, test_loss=0.862, train=14.0%, train_loss=0.870]

outcome_architecture/outcome:  48%|████▊     | 964/2000 [00:10<00:10, 94.72it/s, test=15.4%, test_loss=0.862, train=14.0%, train_loss=0.870]

outcome_architecture/outcome:  49%|████▉     | 975/2000 [00:10<00:10, 98.45it/s, test=15.4%, test_loss=0.862, train=14.0%, train_loss=0.870]

outcome_architecture/outcome:  49%|████▉     | 986/2000 [00:10<00:10, 101.01it/s, test=15.4%, test_loss=0.862, train=14.0%, train_loss=0.870]

outcome_architecture/outcome:  50%|████▉     | 997/2000 [00:11<00:09, 102.82it/s, test=15.4%, test_loss=0.862, train=14.0%, train_loss=0.870]

outcome_architecture/outcome:  50%|████▉     | 997/2000 [00:11<00:09, 102.82it/s, test=15.7%, test_loss=0.868, train=13.0%, train_loss=0.879]

outcome_architecture/outcome:  50%|█████     | 1008/2000 [00:11<00:10, 94.41it/s, test=15.7%, test_loss=0.868, train=13.0%, train_loss=0.879]

outcome_architecture/outcome:  51%|█████     | 1019/2000 [00:11<00:10, 97.47it/s, test=15.7%, test_loss=0.868, train=13.0%, train_loss=0.879]

outcome_architecture/outcome:  52%|█████▏    | 1030/2000 [00:11<00:09, 99.90it/s, test=15.7%, test_loss=0.868, train=13.0%, train_loss=0.879]

outcome_architecture/outcome:  52%|█████▏    | 1041/2000 [00:11<00:09, 102.05it/s, test=15.7%, test_loss=0.868, train=13.0%, train_loss=0.879]

outcome_architecture/outcome:  52%|█████▏    | 1041/2000 [00:11<00:09, 102.05it/s, test=17.5%, test_loss=0.843, train=11.7%, train_loss=0.828]

outcome_architecture/outcome:  53%|█████▎    | 1052/2000 [00:11<00:10, 90.76it/s, test=17.5%, test_loss=0.843, train=11.7%, train_loss=0.828]

outcome_architecture/outcome:  53%|█████▎    | 1063/2000 [00:11<00:09, 95.06it/s, test=17.5%, test_loss=0.843, train=11.7%, train_loss=0.828]

outcome_architecture/outcome:  54%|█████▎    | 1074/2000 [00:11<00:09, 98.45it/s, test=17.5%, test_loss=0.843, train=11.7%, train_loss=0.828]

outcome_architecture/outcome:  54%|█████▍    | 1085/2000 [00:11<00:09, 99.85it/s, test=17.5%, test_loss=0.843, train=11.7%, train_loss=0.828]

outcome_architecture/outcome:  55%|█████▍    | 1096/2000 [00:12<00:08, 100.80it/s, test=17.5%, test_loss=0.843, train=11.7%, train_loss=0.828]

outcome_architecture/outcome:  55%|█████▍    | 1096/2000 [00:12<00:08, 100.80it/s, test=17.5%, test_loss=0.835, train=17.3%, train_loss=0.843]

outcome_architecture/outcome:  55%|█████▌    | 1107/2000 [00:12<00:09, 90.62it/s, test=17.5%, test_loss=0.835, train=17.3%, train_loss=0.843]

outcome_architecture/outcome:  56%|█████▌    | 1118/2000 [00:12<00:09, 94.10it/s, test=17.5%, test_loss=0.835, train=17.3%, train_loss=0.843]

outcome_architecture/outcome:  56%|█████▋    | 1129/2000 [00:12<00:08, 97.44it/s, test=17.5%, test_loss=0.835, train=17.3%, train_loss=0.843]

outcome_architecture/outcome:  57%|█████▋    | 1140/2000 [00:12<00:08, 100.01it/s, test=17.5%, test_loss=0.835, train=17.3%, train_loss=0.843]

outcome_architecture/outcome:  57%|█████▋    | 1140/2000 [00:12<00:08, 100.01it/s, test=16.2%, test_loss=0.820, train=15.7%, train_loss=0.835]

outcome_architecture/outcome:  58%|█████▊    | 1151/2000 [00:12<00:09, 92.64it/s, test=16.2%, test_loss=0.820, train=15.7%, train_loss=0.835]

outcome_architecture/outcome:  58%|█████▊    | 1162/2000 [00:12<00:08, 96.28it/s, test=16.2%, test_loss=0.820, train=15.7%, train_loss=0.835]

outcome_architecture/outcome:  59%|█████▊    | 1173/2000 [00:12<00:08, 98.81it/s, test=16.2%, test_loss=0.820, train=15.7%, train_loss=0.835]

outcome_architecture/outcome:  59%|█████▉    | 1184/2000 [00:13<00:08, 100.97it/s, test=16.2%, test_loss=0.820, train=15.7%, train_loss=0.835]

outcome_architecture/outcome:  60%|█████▉    | 1195/2000 [00:13<00:07, 102.50it/s, test=16.2%, test_loss=0.820, train=15.7%, train_loss=0.835]

outcome_architecture/outcome:  60%|█████▉    | 1195/2000 [00:13<00:07, 102.50it/s, test=17.5%, test_loss=0.822, train=16.0%, train_loss=0.825]

outcome_architecture/outcome:  60%|██████    | 1206/2000 [00:13<00:08, 93.96it/s, test=17.5%, test_loss=0.822, train=16.0%, train_loss=0.825]

outcome_architecture/outcome:  61%|██████    | 1217/2000 [00:13<00:08, 97.27it/s, test=17.5%, test_loss=0.822, train=16.0%, train_loss=0.825]

outcome_architecture/outcome:  61%|██████▏   | 1228/2000 [00:13<00:07, 99.78it/s, test=17.5%, test_loss=0.822, train=16.0%, train_loss=0.825]

outcome_architecture/outcome:  62%|██████▏   | 1239/2000 [00:13<00:07, 101.34it/s, test=17.5%, test_loss=0.822, train=16.0%, train_loss=0.825]

outcome_architecture/outcome:  62%|██████▏   | 1239/2000 [00:13<00:07, 101.34it/s, test=18.5%, test_loss=0.797, train=19.0%, train_loss=0.837]

outcome_architecture/outcome:  62%|██████▎   | 1250/2000 [00:13<00:08, 93.52it/s, test=18.5%, test_loss=0.797, train=19.0%, train_loss=0.837]

outcome_architecture/outcome:  63%|██████▎   | 1261/2000 [00:13<00:07, 97.06it/s, test=18.5%, test_loss=0.797, train=19.0%, train_loss=0.837]

outcome_architecture/outcome:  64%|██████▎   | 1272/2000 [00:13<00:07, 99.64it/s, test=18.5%, test_loss=0.797, train=19.0%, train_loss=0.837]

outcome_architecture/outcome:  64%|██████▍   | 1283/2000 [00:14<00:07, 101.57it/s, test=18.5%, test_loss=0.797, train=19.0%, train_loss=0.837]

outcome_architecture/outcome:  65%|██████▍   | 1294/2000 [00:14<00:06, 102.89it/s, test=18.5%, test_loss=0.797, train=19.0%, train_loss=0.837]

outcome_architecture/outcome:  65%|██████▍   | 1294/2000 [00:14<00:06, 102.89it/s, test=16.5%, test_loss=0.807, train=14.3%, train_loss=0.787]

outcome_architecture/outcome:  65%|██████▌   | 1305/2000 [00:14<00:07, 93.72it/s, test=16.5%, test_loss=0.807, train=14.3%, train_loss=0.787]

outcome_architecture/outcome:  66%|██████▌   | 1316/2000 [00:14<00:07, 96.86it/s, test=16.5%, test_loss=0.807, train=14.3%, train_loss=0.787]

outcome_architecture/outcome:  66%|██████▋   | 1327/2000 [00:14<00:06, 99.38it/s, test=16.5%, test_loss=0.807, train=14.3%, train_loss=0.787]

outcome_architecture/outcome:  67%|██████▋   | 1338/2000 [00:14<00:06, 101.37it/s, test=16.5%, test_loss=0.807, train=14.3%, train_loss=0.787]

outcome_architecture/outcome:  67%|██████▋   | 1349/2000 [00:14<00:06, 102.80it/s, test=16.5%, test_loss=0.807, train=14.3%, train_loss=0.787]

outcome_architecture/outcome:  67%|██████▋   | 1349/2000 [00:14<00:06, 102.80it/s, test=19.5%, test_loss=0.820, train=21.3%, train_loss=0.797]

outcome_architecture/outcome:  68%|██████▊   | 1360/2000 [00:14<00:06, 94.48it/s, test=19.5%, test_loss=0.820, train=21.3%, train_loss=0.797]

outcome_architecture/outcome:  69%|██████▊   | 1371/2000 [00:14<00:06, 97.69it/s, test=19.5%, test_loss=0.820, train=21.3%, train_loss=0.797]

outcome_architecture/outcome:  69%|██████▉   | 1382/2000 [00:15<00:06, 100.07it/s, test=19.5%, test_loss=0.820, train=21.3%, train_loss=0.797]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:15<00:05, 101.77it/s, test=19.5%, test_loss=0.820, train=21.3%, train_loss=0.797]

outcome_architecture/outcome:  70%|██████▉   | 1393/2000 [00:15<00:05, 101.77it/s, test=0.0%, test_loss=1623.148, train=0.0%, train_loss=1628.146]

outcome_architecture/outcome:  70%|███████   | 1404/2000 [00:15<00:06, 93.88it/s, test=0.0%, test_loss=1623.148, train=0.0%, train_loss=1628.146]

outcome_architecture/outcome:  71%|███████   | 1415/2000 [00:15<00:06, 97.39it/s, test=0.0%, test_loss=1623.148, train=0.0%, train_loss=1628.146]

outcome_architecture/outcome:  71%|███████▏  | 1426/2000 [00:15<00:05, 99.65it/s, test=0.0%, test_loss=1623.148, train=0.0%, train_loss=1628.146]

outcome_architecture/outcome:  72%|███████▏  | 1437/2000 [00:15<00:05, 101.72it/s, test=0.0%, test_loss=1623.148, train=0.0%, train_loss=1628.146]

outcome_architecture/outcome:  72%|███████▏  | 1448/2000 [00:15<00:05, 103.24it/s, test=0.0%, test_loss=1623.148, train=0.0%, train_loss=1628.146]

outcome_architecture/outcome:  72%|███████▏  | 1448/2000 [00:15<00:05, 103.24it/s, test=0.0%, test_loss=234121.922, train=0.0%, train_loss=245786.578]

outcome_architecture/outcome:  73%|███████▎  | 1459/2000 [00:15<00:05, 95.03it/s, test=0.0%, test_loss=234121.922, train=0.0%, train_loss=245786.578]

outcome_architecture/outcome:  74%|███████▎  | 1470/2000 [00:15<00:05, 98.47it/s, test=0.0%, test_loss=234121.922, train=0.0%, train_loss=245786.578]

outcome_architecture/outcome:  74%|███████▍  | 1481/2000 [00:16<00:05, 101.00it/s, test=0.0%, test_loss=234121.922, train=0.0%, train_loss=245786.578]

outcome_architecture/outcome:  75%|███████▍  | 1492/2000 [00:16<00:04, 102.97it/s, test=0.0%, test_loss=234121.922, train=0.0%, train_loss=245786.578]

outcome_architecture/outcome:  75%|███████▍  | 1492/2000 [00:16<00:04, 102.97it/s, test=0.1%, test_loss=7166645.500, train=0.0%, train_loss=6525024.500]

outcome_architecture/outcome:  75%|███████▌  | 1503/2000 [00:16<00:05, 94.85it/s, test=0.1%, test_loss=7166645.500, train=0.0%, train_loss=6525024.500]

outcome_architecture/outcome:  76%|███████▌  | 1514/2000 [00:16<00:04, 97.36it/s, test=0.1%, test_loss=7166645.500, train=0.0%, train_loss=6525024.500]

outcome_architecture/outcome:  76%|███████▌  | 1524/2000 [00:16<00:04, 97.43it/s, test=0.1%, test_loss=7166645.500, train=0.0%, train_loss=6525024.500]

outcome_architecture/outcome:  77%|███████▋  | 1534/2000 [00:16<00:04, 97.90it/s, test=0.1%, test_loss=7166645.500, train=0.0%, train_loss=6525024.500]

outcome_architecture/outcome:  77%|███████▋  | 1544/2000 [00:16<00:04, 98.43it/s, test=0.1%, test_loss=7166645.500, train=0.0%, train_loss=6525024.500]

outcome_architecture/outcome:  77%|███████▋  | 1544/2000 [00:16<00:04, 98.43it/s, test=0.0%, test_loss=186059584.000, train=0.0%, train_loss=149494336.000]

outcome_architecture/outcome:  78%|███████▊  | 1554/2000 [00:16<00:05, 88.95it/s, test=0.0%, test_loss=186059584.000, train=0.0%, train_loss=149494336.000]

outcome_architecture/outcome:  78%|███████▊  | 1565/2000 [00:16<00:04, 92.35it/s, test=0.0%, test_loss=186059584.000, train=0.0%, train_loss=149494336.000]

outcome_architecture/outcome:  79%|███████▉  | 1575/2000 [00:17<00:04, 94.00it/s, test=0.0%, test_loss=186059584.000, train=0.0%, train_loss=149494336.000]

outcome_architecture/outcome:  79%|███████▉  | 1586/2000 [00:17<00:04, 95.95it/s, test=0.0%, test_loss=186059584.000, train=0.0%, train_loss=149494336.000]

outcome_architecture/outcome:  80%|███████▉  | 1597/2000 [00:17<00:04, 97.43it/s, test=0.0%, test_loss=186059584.000, train=0.0%, train_loss=149494336.000]

outcome_architecture/outcome:  80%|███████▉  | 1597/2000 [00:17<00:04, 97.43it/s, test=0.2%, test_loss=10532755.000, train=0.3%, train_loss=7963809.500]

outcome_architecture/outcome:  80%|████████  | 1607/2000 [00:17<00:04, 89.06it/s, test=0.2%, test_loss=10532755.000, train=0.3%, train_loss=7963809.500]

outcome_architecture/outcome:  81%|████████  | 1617/2000 [00:17<00:04, 90.72it/s, test=0.2%, test_loss=10532755.000, train=0.3%, train_loss=7963809.500]

outcome_architecture/outcome:  81%|████████▏ | 1628/2000 [00:17<00:03, 95.37it/s, test=0.2%, test_loss=10532755.000, train=0.3%, train_loss=7963809.500]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:17<00:03, 98.58it/s, test=0.2%, test_loss=10532755.000, train=0.3%, train_loss=7963809.500]

outcome_architecture/outcome:  82%|████████▏ | 1639/2000 [00:17<00:03, 98.58it/s, test=0.2%, test_loss=4842887.500, train=0.7%, train_loss=3762864.250]

outcome_architecture/outcome:  82%|████████▎ | 1650/2000 [00:17<00:03, 91.96it/s, test=0.2%, test_loss=4842887.500, train=0.7%, train_loss=3762864.250]

outcome_architecture/outcome:  83%|████████▎ | 1661/2000 [00:17<00:03, 95.99it/s, test=0.2%, test_loss=4842887.500, train=0.7%, train_loss=3762864.250]

outcome_architecture/outcome:  84%|████████▎ | 1672/2000 [00:18<00:03, 98.19it/s, test=0.2%, test_loss=4842887.500, train=0.7%, train_loss=3762864.250]

outcome_architecture/outcome:  84%|████████▍ | 1683/2000 [00:18<00:03, 100.81it/s, test=0.2%, test_loss=4842887.500, train=0.7%, train_loss=3762864.250]

outcome_architecture/outcome:  85%|████████▍ | 1694/2000 [00:18<00:02, 102.32it/s, test=0.2%, test_loss=4842887.500, train=0.7%, train_loss=3762864.250]

outcome_architecture/outcome:  85%|████████▍ | 1694/2000 [00:18<00:02, 102.32it/s, test=0.1%, test_loss=4559391.500, train=0.3%, train_loss=3182652.000]

outcome_architecture/outcome:  85%|████████▌ | 1705/2000 [00:18<00:03, 94.25it/s, test=0.1%, test_loss=4559391.500, train=0.3%, train_loss=3182652.000]

outcome_architecture/outcome:  86%|████████▌ | 1716/2000 [00:18<00:02, 97.66it/s, test=0.1%, test_loss=4559391.500, train=0.3%, train_loss=3182652.000]

outcome_architecture/outcome:  86%|████████▋ | 1727/2000 [00:18<00:02, 100.31it/s, test=0.1%, test_loss=4559391.500, train=0.3%, train_loss=3182652.000]

outcome_architecture/outcome:  87%|████████▋ | 1738/2000 [00:18<00:02, 102.32it/s, test=0.1%, test_loss=4559391.500, train=0.3%, train_loss=3182652.000]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:18<00:02, 103.46it/s, test=0.1%, test_loss=4559391.500, train=0.3%, train_loss=3182652.000]

outcome_architecture/outcome:  87%|████████▋ | 1749/2000 [00:18<00:02, 103.46it/s, test=0.0%, test_loss=330279616.000, train=0.0%, train_loss=291386080.000]

outcome_architecture/outcome:  88%|████████▊ | 1760/2000 [00:18<00:02, 94.92it/s, test=0.0%, test_loss=330279616.000, train=0.0%, train_loss=291386080.000]

outcome_architecture/outcome:  89%|████████▊ | 1771/2000 [00:19<00:02, 98.20it/s, test=0.0%, test_loss=330279616.000, train=0.0%, train_loss=291386080.000]

outcome_architecture/outcome:  89%|████████▉ | 1782/2000 [00:19<00:02, 100.51it/s, test=0.0%, test_loss=330279616.000, train=0.0%, train_loss=291386080.000]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 102.33it/s, test=0.0%, test_loss=330279616.000, train=0.0%, train_loss=291386080.000]

outcome_architecture/outcome:  90%|████████▉ | 1793/2000 [00:19<00:02, 102.33it/s, test=0.0%, test_loss=129105720.000, train=0.0%, train_loss=186077584.000]

outcome_architecture/outcome:  90%|█████████ | 1804/2000 [00:19<00:02, 94.27it/s, test=0.0%, test_loss=129105720.000, train=0.0%, train_loss=186077584.000]

outcome_architecture/outcome:  91%|█████████ | 1815/2000 [00:19<00:01, 97.70it/s, test=0.0%, test_loss=129105720.000, train=0.0%, train_loss=186077584.000]

outcome_architecture/outcome:  91%|█████████▏| 1826/2000 [00:19<00:01, 100.32it/s, test=0.0%, test_loss=129105720.000, train=0.0%, train_loss=186077584.000]

outcome_architecture/outcome:  92%|█████████▏| 1837/2000 [00:19<00:01, 102.24it/s, test=0.0%, test_loss=129105720.000, train=0.0%, train_loss=186077584.000]

outcome_architecture/outcome:  92%|█████████▏| 1848/2000 [00:19<00:01, 103.49it/s, test=0.0%, test_loss=129105720.000, train=0.0%, train_loss=186077584.000]

outcome_architecture/outcome:  92%|█████████▏| 1848/2000 [00:19<00:01, 103.49it/s, test=0.0%, test_loss=38360772.000, train=0.0%, train_loss=31251010.000]

outcome_architecture/outcome:  93%|█████████▎| 1859/2000 [00:19<00:01, 94.93it/s, test=0.0%, test_loss=38360772.000, train=0.0%, train_loss=31251010.000]

outcome_architecture/outcome:  94%|█████████▎| 1870/2000 [00:20<00:01, 98.16it/s, test=0.0%, test_loss=38360772.000, train=0.0%, train_loss=31251010.000]

outcome_architecture/outcome:  94%|█████████▍| 1881/2000 [00:20<00:01, 100.55it/s, test=0.0%, test_loss=38360772.000, train=0.0%, train_loss=31251010.000]

outcome_architecture/outcome:  95%|█████████▍| 1892/2000 [00:20<00:01, 102.50it/s, test=0.0%, test_loss=38360772.000, train=0.0%, train_loss=31251010.000]

outcome_architecture/outcome:  95%|█████████▍| 1892/2000 [00:20<00:01, 102.50it/s, test=0.2%, test_loss=25383718.000, train=0.3%, train_loss=23062822.000]

outcome_architecture/outcome:  95%|█████████▌| 1903/2000 [00:20<00:01, 94.43it/s, test=0.2%, test_loss=25383718.000, train=0.3%, train_loss=23062822.000]

outcome_architecture/outcome:  96%|█████████▌| 1914/2000 [00:20<00:00, 97.78it/s, test=0.2%, test_loss=25383718.000, train=0.3%, train_loss=23062822.000]

outcome_architecture/outcome:  96%|█████████▋| 1925/2000 [00:20<00:00, 100.34it/s, test=0.2%, test_loss=25383718.000, train=0.3%, train_loss=23062822.000]

outcome_architecture/outcome:  97%|█████████▋| 1936/2000 [00:20<00:00, 102.22it/s, test=0.2%, test_loss=25383718.000, train=0.3%, train_loss=23062822.000]

outcome_architecture/outcome:  97%|█████████▋| 1947/2000 [00:20<00:00, 103.64it/s, test=0.2%, test_loss=25383718.000, train=0.3%, train_loss=23062822.000]

outcome_architecture/outcome:  97%|█████████▋| 1947/2000 [00:20<00:00, 103.64it/s, test=0.0%, test_loss=14000745.000, train=0.0%, train_loss=10399517.000]

outcome_architecture/outcome:  98%|█████████▊| 1958/2000 [00:20<00:00, 94.94it/s, test=0.0%, test_loss=14000745.000, train=0.0%, train_loss=10399517.000]

outcome_architecture/outcome:  98%|█████████▊| 1969/2000 [00:21<00:00, 98.13it/s, test=0.0%, test_loss=14000745.000, train=0.0%, train_loss=10399517.000]

outcome_architecture/outcome:  99%|█████████▉| 1980/2000 [00:21<00:00, 100.55it/s, test=0.0%, test_loss=14000745.000, train=0.0%, train_loss=10399517.000]

outcome_architecture/outcome: 100%|█████████▉| 1991/2000 [00:21<00:00, 102.26it/s, test=0.0%, test_loss=14000745.000, train=0.0%, train_loss=10399517.000]

outcome_architecture/outcome: 100%|█████████▉| 1991/2000 [00:21<00:00, 102.26it/s, test=0.2%, test_loss=1439574.500, train=0.0%, train_loss=1490673.375]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 93.69it/s, test=0.2%, test_loss=1439574.500, train=0.0%, train_loss=1490673.375]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,process,4.277046e+00,0.000000,0.000,0.0,4.277812e+00
1,1,process_architecture,process,4.261146e+00,0.040000,0.077,0.0,4.262105e+00
2,2,process_architecture,process,4.237757e+00,0.040000,0.077,0.0,4.238684e+00
3,5,process_architecture,process,3.954697e+00,0.000000,0.000,0.0,3.950308e+00
4,10,process_architecture,process,3.626287e+00,0.000000,0.000,0.0,3.606024e+00
...,...,...,...,...,...,...,...,...
91,1800,outcome_architecture,outcome,1.860776e+08,0.000000,0.000,0.0,1.291057e+08
92,1850,outcome_architecture,outcome,3.125101e+07,0.000000,0.000,0.0,3.836077e+07
93,1900,outcome_architecture,outcome,2.306282e+07,0.003333,0.002,0.0,2.538372e+07
94,1950,outcome_architecture,outcome,1.039952e+07,0.000000,0.000,0.0,1.400074e+07
95,2000,outcome_architecture,outcome,1.490673e+06,0.000000,0.002,0.0,1.439574e+06


## 7. Final behavioral comparison

The four displayed rows are:

- two fixed references,
- two trained models.

But only the latter two were optimized.

In [8]:

rows = []

for name, model, mode, trained in [
    ("Fixed PROCESS reference", process_reference, "process", False),
    ("Trained PROCESS architecture", trained_process, "process", True),
    ("Fixed OUTCOME reference", outcome_reference, "outcome", False),
    ("Trained OUTCOME architecture", trained_outcome, "outcome", True),
]:
    metrics = free_run_metrics(model, test_eval, tokenizer, mode)
    rows.append({
        "model": name,
        "optimized": trained,
        "mode": mode,
        "test_answer_accuracy": metrics["final_answer"],
        "test_exact_continuation": metrics["exact_continuation"],
    })

final_results = pd.DataFrame(rows)
final_results

,model,optimized,mode,test_answer_accuracy,test_exact_continuation
0,Fixed PROCESS reference,False,process,1.000,1.0
1,Trained PROCESS architecture,True,process,1.000,1.0
2,Fixed OUTCOME reference,False,outcome,1.000,1.0
3,Trained OUTCOME architecture,True,outcome,0.002,0.0

## 8. Learning curves

The first plot tracks free-running answer accuracy. The second plot tracks teacher-forced training and held-out test loss at the same checkpoints.

In [9]:

fig, ax = plt.subplots(figsize=(8, 4.5))

for (architecture, mode), frame in history.groupby(["architecture", "mode"]):
    ax.plot(
        frame["step"],
        frame["test_answer_accuracy"],
        marker="o",
        label=f"{architecture} / {mode}",
    )

ax.axhline(1.0, linestyle="--", label="constructive solution = 100%")
ax.axhline(1 / tokenizer.n_states, linestyle=":", label="chance")
ax.set_xlabel("optimization step")
ax.set_ylabel("free-running test answer accuracy")
ax.set_ylim(-0.02, 1.03)
ax.legend()
plt.show()

In [10]:
def plot_train_test_loss(history, *, steps=STEPS):
    required = {"architecture", "mode", "step", "train_loss", "test_loss"}
    missing = required.difference(history.columns)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"history is missing required columns: {missing_text}")

    fig, ax = plt.subplots(figsize=(9, 5))
    styles = {
        ("process_architecture", "process"): {
            "color": "#2ca02c",
            "label": "PROCESS architecture / process",
        },
        ("outcome_architecture", "outcome"): {
            "color": "#d62728",
            "label": "OUTCOME architecture / outcome",
        },
    }

    for key, frame in history.sort_values("step").groupby(["architecture", "mode"]):
        style = styles.get(key, {"color": None, "label": " / ".join(map(str, key))})
        ax.plot(
            frame["step"],
            frame["train_loss"],
            color=style["color"],
            linewidth=2.2,
            label=f"{style['label']} train",
        )
        ax.plot(
            frame["step"],
            frame["test_loss"],
            color=style["color"],
            linestyle="--",
            linewidth=2.2,
            label=f"{style['label']} test",
        )

    ax.set_xlabel("Iteration", fontsize=13)
    ax.set_ylabel("Teacher-forced loss", fontsize=13)
    ax.set_xlim(0, steps)
    ax.grid(True, alpha=0.35)
    ax.legend(frameon=True, fontsize=10)
    fig.tight_layout()
    return fig, ax

plot_train_test_loss(history)
plt.show()


## 9. Inspect one free-running example

No gold continuation is fed to the model during this evaluation.

In [11]:

example_prompt = torch.tensor(
    [tokenizer.prompt(example)],
    dtype=torch.long,
    device=DEVICE,
)

for name, model, mode in [
    ("Fixed PROCESS", process_reference, "process"),
    ("Trained PROCESS", trained_process, "process"),
    ("Fixed OUTCOME", outcome_reference, "outcome"),
    ("Trained OUTCOME", trained_outcome, "outcome"),
]:
    budget = 3 if mode == "outcome" else 2 * DEPTH + 3
    generated = generate(
        model,
        example_prompt,
        budget,
        tokenizer.eos,
    )
    continuation = generated[0, example_prompt.shape[1]:]
    print(f"\n{name}")
    print(tokenizer.decode(continuation))

Fixed PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Trained PROCESS
s02 S1011 c31 S1111 c31 S1011 t302 S1001 <COLON> S1001 <EOS>

Fixed OUTCOME
<COLON> S1001 <EOS>

Trained OUTCOME
S1000 S1000 <EOS>


## 10. How to interpret the result

There are four broad possibilities.

### Both trained models reach 100%

The two constructive solution classes are readily reachable from this initialization and optimizer.

### PROCESS reaches 100%, OUTCOME does not

Then

\[
\exists\theta^\star_{\rm O}:\operatorname{Err}(\theta^\star_{\rm O})=0
\]

but the tested terminal-supervision optimization trajectory does not discover it.

That is evidence for a **trainability / accessibility gap**, not an expressivity gap.

### OUTCOME reaches 100%, PROCESS does not

Then the existence of an explicit local process circuit does not by itself guarantee that ordinary trace training discovers it.

### Neither reaches 100%

Then constructive realizability and optimization reachability are substantially different for both architectures.

---

Do not infer an impossibility theorem from a failed run. Multiple seeds, learning-rate controls, and optimizer-stability diagnostics are needed before making a strong optimization claim.


# Optional appendix: full $2\times2$ architecture × supervision experiment

The primary notebook above trains exactly **two** models.

A separate, stronger control can cross:

\[
\{\text{PROCESS architecture},\text{OUTCOME architecture}\}
\times
\{\text{PROCESS supervision},\text{OUTCOME supervision}\}.
\]

That experiment trains **four** models and should be reported separately.

It requires the OUTCOME architecture to use the longer PROCESS position budget, so it is intentionally not the exact diagonal reachability experiment above.

In [12]:
RUN_OPTIONAL_2X2 = True

if RUN_OPTIONAL_2X2:
    from handcoded_utils import (
        build_random_trainable_outcome_architecture,
        build_random_trainable_process_architecture,
        run_architecture_experiment,
    )

    bases = {
        "process_architecture": build_random_trainable_process_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
        "outcome_architecture": build_random_trainable_outcome_architecture(
            tokenizer, DEPTH, seed=MODEL_SEED, device=DEVICE
        ),
    }

    models_2x2, history_2x2 = run_architecture_experiment(
        bases,
        training_data,
        batch_schedule,
        LR,
        CHECKPOINTS,
        train_eval,
        test_eval,
        tokenizer,
        circuit_prompts,
        test_loss_data=test_loss_data,
        loss_eval_size=LOSS_EVAL_SIZE,
    )

    display(history_2x2.drop(columns=["circuit_matrix"], errors="ignore"))
else:
    print("Skipping optional 2x2 experiment. Set RUN_OPTIONAL_2X2 = True to run it.")

architecture/mode:   0%|          | 0/4 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.218, train=0.0%, train_loss=4.218]

process_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.137, train=0.0%, train_loss=4.137]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:03, 10.90it/s, test=0.0%, test_loss=4.137, train=0.0%, train_loss=4.137]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:03, 10.90it/s, test=0.0%, test_loss=3.085, train=0.0%, train_loss=3.089]

process_architecture/outcome:   0%|          | 2/2000 [00:00<03:03, 10.90it/s, test=0.0%, test_loss=1.788, train=0.0%, train_loss=1.798]

process_architecture/outcome:   1%|          | 16/2000 [00:00<00:29, 66.90it/s, test=0.0%, test_loss=1.788, train=0.0%, train_loss=1.798]

process_architecture/outcome:   1%|          | 16/2000 [00:00<00:29, 66.90it/s, test=0.0%, test_loss=1.146, train=0.0%, train_loss=1.136]

process_architecture/outcome:   1%|          | 16/2000 [00:00<00:29, 66.90it/s, test=0.0%, test_loss=1.086, train=0.0%, train_loss=1.085]

process_architecture/outcome:   2%|▏         | 30/2000 [00:00<00:20, 94.68it/s, test=0.0%, test_loss=1.086, train=0.0%, train_loss=1.085]

process_architecture/outcome:   2%|▏         | 30/2000 [00:00<00:20, 94.68it/s, test=7.2%, test_loss=0.920, train=6.0%, train_loss=0.935]

process_architecture/outcome:   2%|▎         | 50/2000 [00:00<00:15, 125.26it/s, test=7.2%, test_loss=0.920, train=6.0%, train_loss=0.935]

process_architecture/outcome:   4%|▎         | 70/2000 [00:00<00:12, 149.01it/s, test=7.2%, test_loss=0.920, train=6.0%, train_loss=0.935]

process_architecture/outcome:   4%|▎         | 70/2000 [00:00<00:12, 149.01it/s, test=7.5%, test_loss=0.936, train=7.0%, train_loss=0.943]

process_architecture/outcome:   4%|▍         | 87/2000 [00:00<00:12, 153.86it/s, test=7.5%, test_loss=0.936, train=7.0%, train_loss=0.943]

process_architecture/outcome:   4%|▍         | 87/2000 [00:00<00:12, 153.86it/s, test=7.2%, test_loss=0.924, train=6.0%, train_loss=0.933]

process_architecture/outcome:   5%|▌         | 104/2000 [00:00<00:11, 158.16it/s, test=7.2%, test_loss=0.924, train=6.0%, train_loss=0.933]

process_architecture/outcome:   6%|▋         | 125/2000 [00:00<00:10, 171.77it/s, test=7.2%, test_loss=0.924, train=6.0%, train_loss=0.933]

process_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:10, 177.18it/s, test=7.2%, test_loss=0.924, train=6.0%, train_loss=0.933]

process_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:10, 177.18it/s, test=10.7%, test_loss=0.901, train=7.3%, train_loss=0.901]

process_architecture/outcome:   8%|▊         | 162/2000 [00:01<00:10, 173.08it/s, test=10.7%, test_loss=0.901, train=7.3%, train_loss=0.901]

process_architecture/outcome:   9%|▉         | 182/2000 [00:01<00:10, 180.09it/s, test=10.7%, test_loss=0.901, train=7.3%, train_loss=0.901]

process_architecture/outcome:   9%|▉         | 182/2000 [00:01<00:10, 180.09it/s, test=11.2%, test_loss=0.907, train=11.0%, train_loss=0.904]

process_architecture/outcome:  10%|█         | 201/2000 [00:01<00:10, 176.74it/s, test=11.2%, test_loss=0.907, train=11.0%, train_loss=0.904]

process_architecture/outcome:  11%|█         | 220/2000 [00:01<00:09, 179.39it/s, test=11.2%, test_loss=0.907, train=11.0%, train_loss=0.904]

process_architecture/outcome:  12%|█▏        | 240/2000 [00:01<00:09, 184.30it/s, test=11.2%, test_loss=0.907, train=11.0%, train_loss=0.904]

process_architecture/outcome:  12%|█▏        | 240/2000 [00:01<00:09, 184.30it/s, test=9.8%, test_loss=0.891, train=8.3%, train_loss=0.891]

process_architecture/outcome:  13%|█▎        | 259/2000 [00:01<00:09, 178.83it/s, test=9.8%, test_loss=0.891, train=8.3%, train_loss=0.891]

process_architecture/outcome:  14%|█▍        | 279/2000 [00:01<00:09, 184.02it/s, test=9.8%, test_loss=0.891, train=8.3%, train_loss=0.891]

process_architecture/outcome:  15%|█▍        | 299/2000 [00:01<00:09, 187.05it/s, test=9.8%, test_loss=0.891, train=8.3%, train_loss=0.891]

process_architecture/outcome:  15%|█▍        | 299/2000 [00:01<00:09, 187.05it/s, test=9.3%, test_loss=0.887, train=8.0%, train_loss=0.881]

process_architecture/outcome:  16%|█▌        | 318/2000 [00:01<00:09, 180.02it/s, test=9.3%, test_loss=0.887, train=8.0%, train_loss=0.881]

process_architecture/outcome:  17%|█▋        | 338/2000 [00:02<00:09, 183.62it/s, test=9.3%, test_loss=0.887, train=8.0%, train_loss=0.881]

process_architecture/outcome:  17%|█▋        | 338/2000 [00:02<00:09, 183.62it/s, test=12.1%, test_loss=0.877, train=12.0%, train_loss=0.889]

process_architecture/outcome:  18%|█▊        | 357/2000 [00:02<00:09, 177.05it/s, test=12.1%, test_loss=0.877, train=12.0%, train_loss=0.889]

process_architecture/outcome:  19%|█▉        | 377/2000 [00:02<00:08, 181.37it/s, test=12.1%, test_loss=0.877, train=12.0%, train_loss=0.889]

process_architecture/outcome:  20%|█▉        | 397/2000 [00:02<00:08, 184.41it/s, test=12.1%, test_loss=0.877, train=12.0%, train_loss=0.889]

process_architecture/outcome:  20%|█▉        | 397/2000 [00:02<00:08, 184.41it/s, test=12.0%, test_loss=0.881, train=12.7%, train_loss=0.892]

process_architecture/outcome:  21%|██        | 416/2000 [00:02<00:08, 177.95it/s, test=12.0%, test_loss=0.881, train=12.7%, train_loss=0.892]

process_architecture/outcome:  22%|██▏       | 436/2000 [00:02<00:08, 183.38it/s, test=12.0%, test_loss=0.881, train=12.7%, train_loss=0.892]

process_architecture/outcome:  22%|██▏       | 436/2000 [00:02<00:08, 183.38it/s, test=13.1%, test_loss=0.866, train=10.7%, train_loss=0.864]

process_architecture/outcome:  23%|██▎       | 455/2000 [00:02<00:08, 179.99it/s, test=13.1%, test_loss=0.866, train=10.7%, train_loss=0.864]

process_architecture/outcome:  24%|██▍       | 475/2000 [00:02<00:08, 184.82it/s, test=13.1%, test_loss=0.866, train=10.7%, train_loss=0.864]

process_architecture/outcome:  25%|██▍       | 494/2000 [00:02<00:08, 185.65it/s, test=13.1%, test_loss=0.866, train=10.7%, train_loss=0.864]

process_architecture/outcome:  25%|██▍       | 494/2000 [00:02<00:08, 185.65it/s, test=13.7%, test_loss=0.862, train=12.3%, train_loss=0.848]

process_architecture/outcome:  26%|██▌       | 513/2000 [00:03<00:08, 179.95it/s, test=13.7%, test_loss=0.862, train=12.3%, train_loss=0.848]

process_architecture/outcome:  27%|██▋       | 533/2000 [00:03<00:07, 185.06it/s, test=13.7%, test_loss=0.862, train=12.3%, train_loss=0.848]

process_architecture/outcome:  27%|██▋       | 533/2000 [00:03<00:07, 185.06it/s, test=13.3%, test_loss=0.862, train=14.3%, train_loss=0.823]

process_architecture/outcome:  28%|██▊       | 552/2000 [00:03<00:08, 179.64it/s, test=13.3%, test_loss=0.862, train=14.3%, train_loss=0.823]

process_architecture/outcome:  29%|██▊       | 573/2000 [00:03<00:07, 186.33it/s, test=13.3%, test_loss=0.862, train=14.3%, train_loss=0.823]

process_architecture/outcome:  30%|██▉       | 592/2000 [00:03<00:07, 186.09it/s, test=13.3%, test_loss=0.862, train=14.3%, train_loss=0.823]

process_architecture/outcome:  30%|██▉       | 592/2000 [00:03<00:07, 186.09it/s, test=15.8%, test_loss=0.862, train=13.3%, train_loss=0.840]

process_architecture/outcome:  31%|███       | 611/2000 [00:03<00:07, 179.08it/s, test=15.8%, test_loss=0.862, train=13.3%, train_loss=0.840]

process_architecture/outcome:  32%|███▏      | 631/2000 [00:03<00:07, 182.90it/s, test=15.8%, test_loss=0.862, train=13.3%, train_loss=0.840]

process_architecture/outcome:  32%|███▏      | 631/2000 [00:03<00:07, 182.90it/s, test=13.8%, test_loss=0.867, train=14.3%, train_loss=0.840]

process_architecture/outcome:  32%|███▎      | 650/2000 [00:03<00:07, 176.64it/s, test=13.8%, test_loss=0.867, train=14.3%, train_loss=0.840]

process_architecture/outcome:  33%|███▎      | 669/2000 [00:03<00:07, 180.16it/s, test=13.8%, test_loss=0.867, train=14.3%, train_loss=0.840]

process_architecture/outcome:  34%|███▍      | 689/2000 [00:04<00:07, 183.71it/s, test=13.8%, test_loss=0.867, train=14.3%, train_loss=0.840]

process_architecture/outcome:  34%|███▍      | 689/2000 [00:04<00:07, 183.71it/s, test=16.7%, test_loss=0.857, train=15.0%, train_loss=0.834]

process_architecture/outcome:  35%|███▌      | 708/2000 [00:04<00:07, 178.00it/s, test=16.7%, test_loss=0.857, train=15.0%, train_loss=0.834]

process_architecture/outcome:  36%|███▋      | 728/2000 [00:04<00:06, 183.96it/s, test=16.7%, test_loss=0.857, train=15.0%, train_loss=0.834]

process_architecture/outcome:  37%|███▋      | 748/2000 [00:04<00:06, 188.31it/s, test=16.7%, test_loss=0.857, train=15.0%, train_loss=0.834]

process_architecture/outcome:  37%|███▋      | 748/2000 [00:04<00:06, 188.31it/s, test=17.9%, test_loss=0.854, train=15.3%, train_loss=0.814]

process_architecture/outcome:  38%|███▊      | 767/2000 [00:04<00:06, 183.56it/s, test=17.9%, test_loss=0.854, train=15.3%, train_loss=0.814]

process_architecture/outcome:  39%|███▉      | 788/2000 [00:04<00:06, 189.95it/s, test=17.9%, test_loss=0.854, train=15.3%, train_loss=0.814]

process_architecture/outcome:  39%|███▉      | 788/2000 [00:04<00:06, 189.95it/s, test=17.9%, test_loss=0.836, train=17.3%, train_loss=0.813]

process_architecture/outcome:  40%|████      | 808/2000 [00:04<00:06, 185.15it/s, test=17.9%, test_loss=0.836, train=17.3%, train_loss=0.813]

process_architecture/outcome:  41%|████▏     | 829/2000 [00:04<00:06, 189.83it/s, test=17.9%, test_loss=0.836, train=17.3%, train_loss=0.813]

process_architecture/outcome:  41%|████▏     | 829/2000 [00:04<00:06, 189.83it/s, test=19.8%, test_loss=0.800, train=18.3%, train_loss=0.770]

process_architecture/outcome:  42%|████▎     | 850/2000 [00:04<00:06, 184.79it/s, test=19.8%, test_loss=0.800, train=18.3%, train_loss=0.770]

process_architecture/outcome:  44%|████▎     | 871/2000 [00:04<00:05, 189.93it/s, test=19.8%, test_loss=0.800, train=18.3%, train_loss=0.770]

process_architecture/outcome:  45%|████▍     | 892/2000 [00:05<00:05, 194.18it/s, test=19.8%, test_loss=0.800, train=18.3%, train_loss=0.770]

process_architecture/outcome:  45%|████▍     | 892/2000 [00:05<00:05, 194.18it/s, test=22.5%, test_loss=0.786, train=20.3%, train_loss=0.743]

process_architecture/outcome:  46%|████▌     | 912/2000 [00:05<00:05, 187.58it/s, test=22.5%, test_loss=0.786, train=20.3%, train_loss=0.743]

process_architecture/outcome:  47%|████▋     | 933/2000 [00:05<00:05, 191.37it/s, test=22.5%, test_loss=0.786, train=20.3%, train_loss=0.743]

process_architecture/outcome:  47%|████▋     | 933/2000 [00:05<00:05, 191.37it/s, test=23.2%, test_loss=0.745, train=21.0%, train_loss=0.697]

process_architecture/outcome:  48%|████▊     | 953/2000 [00:05<00:05, 184.79it/s, test=23.2%, test_loss=0.745, train=21.0%, train_loss=0.697]

process_architecture/outcome:  49%|████▊     | 973/2000 [00:05<00:05, 187.09it/s, test=23.2%, test_loss=0.745, train=21.0%, train_loss=0.697]

process_architecture/outcome:  50%|████▉     | 994/2000 [00:05<00:05, 192.45it/s, test=23.2%, test_loss=0.745, train=21.0%, train_loss=0.697]

process_architecture/outcome:  50%|████▉     | 994/2000 [00:05<00:05, 192.45it/s, test=22.8%, test_loss=0.744, train=23.7%, train_loss=0.700]

process_architecture/outcome:  51%|█████     | 1014/2000 [00:05<00:05, 185.47it/s, test=22.8%, test_loss=0.744, train=23.7%, train_loss=0.700]

process_architecture/outcome:  52%|█████▏    | 1034/2000 [00:05<00:05, 189.53it/s, test=22.8%, test_loss=0.744, train=23.7%, train_loss=0.700]

process_architecture/outcome:  52%|█████▏    | 1034/2000 [00:05<00:05, 189.53it/s, test=22.6%, test_loss=0.745, train=17.3%, train_loss=0.761]

process_architecture/outcome:  53%|█████▎    | 1054/2000 [00:05<00:05, 182.67it/s, test=22.6%, test_loss=0.745, train=17.3%, train_loss=0.761]

process_architecture/outcome:  54%|█████▍    | 1075/2000 [00:06<00:04, 188.74it/s, test=22.6%, test_loss=0.745, train=17.3%, train_loss=0.761]

process_architecture/outcome:  55%|█████▍    | 1096/2000 [00:06<00:04, 193.42it/s, test=22.6%, test_loss=0.745, train=17.3%, train_loss=0.761]

process_architecture/outcome:  55%|█████▍    | 1096/2000 [00:06<00:04, 193.42it/s, test=20.8%, test_loss=0.729, train=22.0%, train_loss=0.715]

process_architecture/outcome:  56%|█████▌    | 1116/2000 [00:06<00:04, 185.38it/s, test=20.8%, test_loss=0.729, train=22.0%, train_loss=0.715]

process_architecture/outcome:  57%|█████▋    | 1137/2000 [00:06<00:04, 189.95it/s, test=20.8%, test_loss=0.729, train=22.0%, train_loss=0.715]

process_architecture/outcome:  57%|█████▋    | 1137/2000 [00:06<00:04, 189.95it/s, test=21.8%, test_loss=0.705, train=22.3%, train_loss=0.719]

process_architecture/outcome:  58%|█████▊    | 1157/2000 [00:06<00:04, 184.53it/s, test=21.8%, test_loss=0.705, train=22.3%, train_loss=0.719]

process_architecture/outcome:  59%|█████▉    | 1178/2000 [00:06<00:04, 189.59it/s, test=21.8%, test_loss=0.705, train=22.3%, train_loss=0.719]

process_architecture/outcome:  60%|█████▉    | 1199/2000 [00:06<00:04, 193.92it/s, test=21.8%, test_loss=0.705, train=22.3%, train_loss=0.719]

process_architecture/outcome:  60%|█████▉    | 1199/2000 [00:06<00:04, 193.92it/s, test=21.8%, test_loss=0.765, train=23.3%, train_loss=0.699]

process_architecture/outcome:  61%|██████    | 1219/2000 [00:06<00:04, 187.38it/s, test=21.8%, test_loss=0.765, train=23.3%, train_loss=0.699]

process_architecture/outcome:  62%|██████▏   | 1240/2000 [00:06<00:03, 191.52it/s, test=21.8%, test_loss=0.765, train=23.3%, train_loss=0.699]

process_architecture/outcome:  62%|██████▏   | 1240/2000 [00:06<00:03, 191.52it/s, test=23.6%, test_loss=0.719, train=22.3%, train_loss=0.694]

process_architecture/outcome:  63%|██████▎   | 1260/2000 [00:07<00:03, 185.16it/s, test=23.6%, test_loss=0.719, train=22.3%, train_loss=0.694]

process_architecture/outcome:  64%|██████▍   | 1281/2000 [00:07<00:03, 191.24it/s, test=23.6%, test_loss=0.719, train=22.3%, train_loss=0.694]

process_architecture/outcome:  64%|██████▍   | 1281/2000 [00:07<00:03, 191.24it/s, test=26.0%, test_loss=0.708, train=28.3%, train_loss=0.674]

process_architecture/outcome:  65%|██████▌   | 1301/2000 [00:07<00:03, 185.29it/s, test=26.0%, test_loss=0.708, train=28.3%, train_loss=0.674]

process_architecture/outcome:  66%|██████▌   | 1322/2000 [00:07<00:03, 189.77it/s, test=26.0%, test_loss=0.708, train=28.3%, train_loss=0.674]

process_architecture/outcome:  67%|██████▋   | 1342/2000 [00:07<00:03, 192.14it/s, test=26.0%, test_loss=0.708, train=28.3%, train_loss=0.674]

process_architecture/outcome:  67%|██████▋   | 1342/2000 [00:07<00:03, 192.14it/s, test=27.7%, test_loss=0.706, train=30.0%, train_loss=0.618]

process_architecture/outcome:  68%|██████▊   | 1362/2000 [00:07<00:03, 186.05it/s, test=27.7%, test_loss=0.706, train=30.0%, train_loss=0.618]

process_architecture/outcome:  69%|██████▉   | 1383/2000 [00:07<00:03, 191.70it/s, test=27.7%, test_loss=0.706, train=30.0%, train_loss=0.618]

process_architecture/outcome:  69%|██████▉   | 1383/2000 [00:07<00:03, 191.70it/s, test=28.1%, test_loss=0.694, train=29.7%, train_loss=0.643]

process_architecture/outcome:  70%|███████   | 1403/2000 [00:07<00:03, 184.63it/s, test=28.1%, test_loss=0.694, train=29.7%, train_loss=0.643]

process_architecture/outcome:  71%|███████   | 1424/2000 [00:07<00:03, 189.40it/s, test=28.1%, test_loss=0.694, train=29.7%, train_loss=0.643]

process_architecture/outcome:  72%|███████▏  | 1445/2000 [00:08<00:02, 193.41it/s, test=28.1%, test_loss=0.694, train=29.7%, train_loss=0.643]

process_architecture/outcome:  72%|███████▏  | 1445/2000 [00:08<00:02, 193.41it/s, test=27.1%, test_loss=0.672, train=32.3%, train_loss=0.597]

process_architecture/outcome:  73%|███████▎  | 1465/2000 [00:08<00:02, 187.00it/s, test=27.1%, test_loss=0.672, train=32.3%, train_loss=0.597]

process_architecture/outcome:  74%|███████▍  | 1486/2000 [00:08<00:02, 192.12it/s, test=27.1%, test_loss=0.672, train=32.3%, train_loss=0.597]

process_architecture/outcome:  74%|███████▍  | 1486/2000 [00:08<00:02, 192.12it/s, test=28.8%, test_loss=0.683, train=31.0%, train_loss=0.585]

process_architecture/outcome:  75%|███████▌  | 1506/2000 [00:08<00:02, 185.14it/s, test=28.8%, test_loss=0.683, train=31.0%, train_loss=0.585]

process_architecture/outcome:  76%|███████▋  | 1526/2000 [00:08<00:02, 189.10it/s, test=28.8%, test_loss=0.683, train=31.0%, train_loss=0.585]

process_architecture/outcome:  77%|███████▋  | 1547/2000 [00:08<00:02, 193.01it/s, test=28.8%, test_loss=0.683, train=31.0%, train_loss=0.585]

process_architecture/outcome:  77%|███████▋  | 1547/2000 [00:08<00:02, 193.01it/s, test=29.2%, test_loss=0.679, train=31.7%, train_loss=0.618]

process_architecture/outcome:  78%|███████▊  | 1567/2000 [00:08<00:02, 186.28it/s, test=29.2%, test_loss=0.679, train=31.7%, train_loss=0.618]

process_architecture/outcome:  79%|███████▉  | 1588/2000 [00:08<00:02, 191.45it/s, test=29.2%, test_loss=0.679, train=31.7%, train_loss=0.618]

process_architecture/outcome:  79%|███████▉  | 1588/2000 [00:08<00:02, 191.45it/s, test=31.5%, test_loss=0.678, train=35.7%, train_loss=0.582]

process_architecture/outcome:  80%|████████  | 1608/2000 [00:08<00:02, 184.98it/s, test=31.5%, test_loss=0.678, train=35.7%, train_loss=0.582]

process_architecture/outcome:  81%|████████▏ | 1629/2000 [00:08<00:01, 189.79it/s, test=31.5%, test_loss=0.678, train=35.7%, train_loss=0.582]

process_architecture/outcome:  81%|████████▏ | 1629/2000 [00:09<00:01, 189.79it/s, test=29.9%, test_loss=0.723, train=31.3%, train_loss=0.630]

process_architecture/outcome:  82%|████████▎ | 1650/2000 [00:09<00:01, 185.01it/s, test=29.9%, test_loss=0.723, train=31.3%, train_loss=0.630]

process_architecture/outcome:  84%|████████▎ | 1671/2000 [00:09<00:01, 190.69it/s, test=29.9%, test_loss=0.723, train=31.3%, train_loss=0.630]

process_architecture/outcome:  85%|████████▍ | 1692/2000 [00:09<00:01, 193.84it/s, test=29.9%, test_loss=0.723, train=31.3%, train_loss=0.630]

process_architecture/outcome:  85%|████████▍ | 1692/2000 [00:09<00:01, 193.84it/s, test=31.5%, test_loss=0.629, train=37.7%, train_loss=0.537]

process_architecture/outcome:  86%|████████▌ | 1712/2000 [00:09<00:01, 186.86it/s, test=31.5%, test_loss=0.629, train=37.7%, train_loss=0.537]

process_architecture/outcome:  87%|████████▋ | 1732/2000 [00:09<00:01, 190.48it/s, test=31.5%, test_loss=0.629, train=37.7%, train_loss=0.537]

process_architecture/outcome:  87%|████████▋ | 1732/2000 [00:09<00:01, 190.48it/s, test=33.8%, test_loss=0.658, train=34.3%, train_loss=0.544]

process_architecture/outcome:  88%|████████▊ | 1752/2000 [00:09<00:01, 184.83it/s, test=33.8%, test_loss=0.658, train=34.3%, train_loss=0.544]

process_architecture/outcome:  89%|████████▊ | 1773/2000 [00:09<00:01, 190.60it/s, test=33.8%, test_loss=0.658, train=34.3%, train_loss=0.544]

process_architecture/outcome:  90%|████████▉ | 1793/2000 [00:09<00:01, 192.98it/s, test=33.8%, test_loss=0.658, train=34.3%, train_loss=0.544]

process_architecture/outcome:  90%|████████▉ | 1793/2000 [00:09<00:01, 192.98it/s, test=32.8%, test_loss=0.664, train=37.7%, train_loss=0.566]

process_architecture/outcome:  91%|█████████ | 1813/2000 [00:09<00:01, 186.36it/s, test=32.8%, test_loss=0.664, train=37.7%, train_loss=0.566]

process_architecture/outcome:  92%|█████████▏| 1834/2000 [00:10<00:00, 190.87it/s, test=32.8%, test_loss=0.664, train=37.7%, train_loss=0.566]

process_architecture/outcome:  92%|█████████▏| 1834/2000 [00:10<00:00, 190.87it/s, test=31.9%, test_loss=0.603, train=37.0%, train_loss=0.548]

process_architecture/outcome:  93%|█████████▎| 1854/2000 [00:10<00:00, 185.03it/s, test=31.9%, test_loss=0.603, train=37.0%, train_loss=0.548]

process_architecture/outcome:  94%|█████████▍| 1875/2000 [00:10<00:00, 190.85it/s, test=31.9%, test_loss=0.603, train=37.0%, train_loss=0.548]

process_architecture/outcome:  95%|█████████▍| 1895/2000 [00:10<00:00, 193.38it/s, test=31.9%, test_loss=0.603, train=37.0%, train_loss=0.548]

process_architecture/outcome:  95%|█████████▍| 1895/2000 [00:10<00:00, 193.38it/s, test=32.2%, test_loss=0.615, train=35.0%, train_loss=0.597]

process_architecture/outcome:  96%|█████████▌| 1915/2000 [00:10<00:00, 186.35it/s, test=32.2%, test_loss=0.615, train=35.0%, train_loss=0.597]

process_architecture/outcome:  97%|█████████▋| 1936/2000 [00:10<00:00, 191.13it/s, test=32.2%, test_loss=0.615, train=35.0%, train_loss=0.597]

process_architecture/outcome:  97%|█████████▋| 1936/2000 [00:10<00:00, 191.13it/s, test=32.0%, test_loss=0.647, train=33.3%, train_loss=0.554]

process_architecture/outcome:  98%|█████████▊| 1956/2000 [00:10<00:00, 184.93it/s, test=32.0%, test_loss=0.647, train=33.3%, train_loss=0.554]

process_architecture/outcome:  99%|█████████▉| 1977/2000 [00:10<00:00, 190.08it/s, test=32.0%, test_loss=0.647, train=33.3%, train_loss=0.554]

process_architecture/outcome: 100%|█████████▉| 1998/2000 [00:10<00:00, 193.23it/s, test=32.0%, test_loss=0.647, train=33.3%, train_loss=0.554]

process_architecture/outcome: 100%|█████████▉| 1998/2000 [00:10<00:00, 193.23it/s, test=30.9%, test_loss=0.662, train=36.0%, train_loss=0.533]

process_architecture/outcome: 100%|██████████| 2000/2000 [00:10<00:00, 182.42it/s, test=30.9%, test_loss=0.662, train=36.0%, train_loss=0.533]

architecture/mode:  25%|██▌       | 1/4 [00:10<00:32, 10.98s/it]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=7.7%, test_loss=4.262, train=4.0%, train_loss=4.261]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=7.7%, test_loss=4.239, train=4.0%, train_loss=4.238]

process_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.950, train=0.0%, train_loss=3.955]

process_architecture/process:   0%|          | 5/2000 [00:00<00:57, 34.63it/s, test=0.0%, test_loss=3.950, train=0.0%, train_loss=3.955]

process_architecture/process:   0%|          | 5/2000 [00:00<00:57, 34.63it/s, test=0.0%, test_loss=3.606, train=0.0%, train_loss=3.626]

process_architecture/process:   0%|          | 5/2000 [00:00<00:57, 34.63it/s, test=6.9%, test_loss=2.913, train=9.0%, train_loss=2.913]

process_architecture/process:   1%|          | 20/2000 [00:00<00:25, 76.42it/s, test=6.9%, test_loss=2.913, train=9.0%, train_loss=2.913]

process_architecture/process:   1%|          | 20/2000 [00:00<00:25, 76.42it/s, test=6.2%, test_loss=2.783, train=9.0%, train_loss=2.790]

process_architecture/process:   1%|▏         | 29/2000 [00:00<00:24, 81.28it/s, test=6.2%, test_loss=2.783, train=9.0%, train_loss=2.790]

process_architecture/process:   1%|▏         | 29/2000 [00:00<00:24, 81.28it/s, test=7.5%, test_loss=2.615, train=7.0%, train_loss=2.647]

process_architecture/process:   2%|▎         | 50/2000 [00:00<00:18, 104.81it/s, test=7.5%, test_loss=2.615, train=7.0%, train_loss=2.647]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:14, 133.90it/s, test=7.5%, test_loss=2.615, train=7.0%, train_loss=2.647]

process_architecture/process:   4%|▎         | 71/2000 [00:00<00:14, 133.90it/s, test=9.8%, test_loss=2.447, train=8.0%, train_loss=2.454]

process_architecture/process:   4%|▍         | 85/2000 [00:00<00:15, 127.22it/s, test=9.8%, test_loss=2.447, train=8.0%, train_loss=2.454]

process_architecture/process:   4%|▍         | 85/2000 [00:00<00:15, 127.22it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   5%|▌         | 100/2000 [00:00<00:15, 124.05it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   6%|▌         | 121/2000 [00:01<00:12, 145.51it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 161.71it/s, test=13.2%, test_loss=2.351, train=7.7%, train_loss=2.314]

process_architecture/process:   7%|▋         | 142/2000 [00:01<00:11, 161.71it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:   8%|▊         | 159/2000 [00:01<00:12, 148.66it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:   9%|▉         | 180/2000 [00:01<00:11, 164.24it/s, test=12.8%, test_loss=1.877, train=8.7%, train_loss=1.847]

process_architecture/process:   9%|▉         | 180/2000 [00:01<00:11, 164.24it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  10%|█         | 200/2000 [00:01<00:11, 151.65it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  11%|█         | 221/2000 [00:01<00:10, 164.69it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  12%|█▏        | 242/2000 [00:01<00:10, 174.83it/s, test=21.1%, test_loss=0.634, train=23.3%, train_loss=0.637]

process_architecture/process:  12%|█▏        | 242/2000 [00:01<00:10, 174.83it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  13%|█▎        | 261/2000 [00:01<00:10, 158.67it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  14%|█▍        | 282/2000 [00:01<00:10, 170.27it/s, test=69.5%, test_loss=0.105, train=69.0%, train_loss=0.102]

process_architecture/process:  14%|█▍        | 282/2000 [00:02<00:10, 170.27it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  15%|█▌        | 300/2000 [00:02<00:10, 154.95it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  16%|█▌        | 321/2000 [00:02<00:10, 167.64it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  17%|█▋        | 342/2000 [00:02<00:09, 177.53it/s, test=83.8%, test_loss=0.034, train=86.7%, train_loss=0.054]

process_architecture/process:  17%|█▋        | 342/2000 [00:02<00:09, 177.53it/s, test=97.1%, test_loss=0.011, train=97.0%, train_loss=0.010]

process_architecture/process:  18%|█▊        | 361/2000 [00:02<00:10, 159.29it/s, test=97.1%, test_loss=0.011, train=97.0%, train_loss=0.010]

process_architecture/process:  19%|█▉        | 382/2000 [00:02<00:09, 170.79it/s, test=97.1%, test_loss=0.011, train=97.0%, train_loss=0.010]

process_architecture/process:  19%|█▉        | 382/2000 [00:02<00:09, 170.79it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  20%|██        | 400/2000 [00:02<00:10, 155.57it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  21%|██        | 421/2000 [00:02<00:09, 168.60it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  22%|██▏       | 442/2000 [00:02<00:08, 177.91it/s, test=100.0%, test_loss=0.002, train=100.0%, train_loss=0.002]

process_architecture/process:  22%|██▏       | 442/2000 [00:03<00:08, 177.91it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  23%|██▎       | 461/2000 [00:03<00:09, 160.33it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  24%|██▍       | 482/2000 [00:03<00:08, 171.20it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  24%|██▍       | 482/2000 [00:03<00:08, 171.20it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  25%|██▌       | 500/2000 [00:03<00:09, 155.82it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  26%|██▌       | 521/2000 [00:03<00:08, 168.16it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 541/2000 [00:03<00:08, 176.38it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

process_architecture/process:  27%|██▋       | 541/2000 [00:03<00:08, 176.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  28%|██▊       | 560/2000 [00:03<00:09, 159.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  29%|██▉       | 581/2000 [00:03<00:08, 170.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  29%|██▉       | 581/2000 [00:03<00:08, 170.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  30%|███       | 600/2000 [00:03<00:08, 156.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  31%|███       | 620/2000 [00:04<00:08, 166.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 641/2000 [00:04<00:07, 175.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  32%|███▏      | 641/2000 [00:04<00:07, 175.94it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  33%|███▎      | 660/2000 [00:04<00:08, 158.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 681/2000 [00:04<00:07, 170.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  34%|███▍      | 681/2000 [00:04<00:07, 170.41it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  35%|███▌      | 700/2000 [00:04<00:08, 155.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  36%|███▌      | 720/2000 [00:04<00:07, 166.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 740/2000 [00:04<00:07, 175.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  37%|███▋      | 740/2000 [00:04<00:07, 175.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  38%|███▊      | 759/2000 [00:04<00:07, 158.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 780/2000 [00:04<00:07, 170.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  39%|███▉      | 780/2000 [00:05<00:07, 170.47it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  40%|████      | 800/2000 [00:05<00:07, 155.83it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  41%|████      | 820/2000 [00:05<00:07, 166.75it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 841/2000 [00:05<00:06, 176.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  42%|████▏     | 841/2000 [00:05<00:06, 176.71it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  43%|████▎     | 860/2000 [00:05<00:07, 159.36it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 880/2000 [00:05<00:06, 169.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  44%|████▍     | 880/2000 [00:05<00:06, 169.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  45%|████▌     | 900/2000 [00:05<00:07, 155.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  46%|████▌     | 921/2000 [00:05<00:06, 167.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 942/2000 [00:05<00:05, 177.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  47%|████▋     | 942/2000 [00:06<00:05, 177.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  48%|████▊     | 961/2000 [00:06<00:06, 159.66it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 982/2000 [00:06<00:05, 170.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  49%|████▉     | 982/2000 [00:06<00:05, 170.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  50%|█████     | 1000/2000 [00:06<00:06, 155.65it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  51%|█████     | 1021/2000 [00:06<00:05, 168.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1042/2000 [00:06<00:05, 178.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  52%|█████▏    | 1042/2000 [00:06<00:05, 178.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  53%|█████▎    | 1061/2000 [00:06<00:05, 160.34it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1082/2000 [00:06<00:05, 171.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  54%|█████▍    | 1082/2000 [00:06<00:05, 171.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  55%|█████▌    | 1100/2000 [00:06<00:05, 155.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  56%|█████▌    | 1121/2000 [00:07<00:05, 167.95it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1141/2000 [00:07<00:04, 176.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  57%|█████▋    | 1141/2000 [00:07<00:04, 176.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  58%|█████▊    | 1160/2000 [00:07<00:05, 158.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1181/2000 [00:07<00:04, 170.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  59%|█████▉    | 1181/2000 [00:07<00:04, 170.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  60%|██████    | 1200/2000 [00:07<00:05, 157.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  61%|██████    | 1220/2000 [00:07<00:04, 167.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1241/2000 [00:07<00:04, 177.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  62%|██████▏   | 1241/2000 [00:07<00:04, 177.52it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  63%|██████▎   | 1260/2000 [00:07<00:04, 160.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1282/2000 [00:07<00:04, 174.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  64%|██████▍   | 1282/2000 [00:08<00:04, 174.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  65%|██████▌   | 1301/2000 [00:08<00:04, 159.16it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  66%|██████▌   | 1322/2000 [00:08<00:03, 171.04it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1343/2000 [00:08<00:03, 180.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  67%|██████▋   | 1343/2000 [00:08<00:03, 180.53it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  68%|██████▊   | 1362/2000 [00:08<00:03, 162.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1383/2000 [00:08<00:03, 173.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  69%|██████▉   | 1383/2000 [00:08<00:03, 173.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  70%|███████   | 1401/2000 [00:08<00:03, 156.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  71%|███████   | 1422/2000 [00:08<00:03, 169.22it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1443/2000 [00:08<00:03, 179.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  72%|███████▏  | 1443/2000 [00:09<00:03, 179.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  73%|███████▎  | 1462/2000 [00:09<00:03, 161.51it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1483/2000 [00:09<00:02, 172.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  74%|███████▍  | 1483/2000 [00:09<00:02, 172.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  75%|███████▌  | 1501/2000 [00:09<00:03, 156.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  76%|███████▌  | 1522/2000 [00:09<00:02, 170.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1543/2000 [00:09<00:02, 179.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  77%|███████▋  | 1543/2000 [00:09<00:02, 179.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  78%|███████▊  | 1562/2000 [00:09<00:02, 161.11it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1582/2000 [00:09<00:02, 170.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  79%|███████▉  | 1582/2000 [00:09<00:02, 170.96it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  80%|████████  | 1600/2000 [00:09<00:02, 155.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  81%|████████  | 1621/2000 [00:10<00:02, 168.44it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1642/2000 [00:10<00:02, 177.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  82%|████████▏ | 1642/2000 [00:10<00:02, 177.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  83%|████████▎ | 1661/2000 [00:10<00:02, 159.81it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1682/2000 [00:10<00:01, 171.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  84%|████████▍ | 1682/2000 [00:10<00:01, 171.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  85%|████████▌ | 1700/2000 [00:10<00:01, 156.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  86%|████████▌ | 1720/2000 [00:10<00:01, 166.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1740/2000 [00:10<00:01, 173.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  87%|████████▋ | 1740/2000 [00:10<00:01, 173.87it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  88%|████████▊ | 1758/2000 [00:10<00:01, 155.77it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  89%|████████▉ | 1778/2000 [00:10<00:01, 166.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1799/2000 [00:11<00:01, 177.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  90%|████████▉ | 1799/2000 [00:11<00:01, 177.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  91%|█████████ | 1818/2000 [00:11<00:01, 159.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1838/2000 [00:11<00:00, 169.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  92%|█████████▏| 1838/2000 [00:11<00:00, 169.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  93%|█████████▎| 1856/2000 [00:11<00:00, 154.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  94%|█████████▍| 1877/2000 [00:11<00:00, 167.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1898/2000 [00:11<00:00, 176.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  95%|█████████▍| 1898/2000 [00:11<00:00, 176.31it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  96%|█████████▌| 1917/2000 [00:11<00:00, 158.86it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1938/2000 [00:11<00:00, 170.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  97%|█████████▋| 1938/2000 [00:12<00:00, 170.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  98%|█████████▊| 1956/2000 [00:12<00:00, 154.82it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process:  99%|█████████▉| 1977/2000 [00:12<00:00, 167.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1997/2000 [00:12<00:00, 175.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|█████████▉| 1997/2000 [00:12<00:00, 175.76it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

process_architecture/process: 100%|██████████| 2000/2000 [00:12<00:00, 162.07it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode:  50%|█████     | 2/4 [00:23<00:23, 11.81s/it]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=3.630, train=0.0%, train_loss=3.634]

outcome_architecture/outcome:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=11.926, train=0.0%, train_loss=11.908]

outcome_architecture/outcome:   0%|          | 3/2000 [00:00<01:08, 28.95it/s, test=0.0%, test_loss=11.926, train=0.0%, train_loss=11.908]

outcome_architecture/outcome:   0%|          | 3/2000 [00:00<01:08, 28.95it/s, test=0.0%, test_loss=3.592, train=0.0%, train_loss=3.593]

outcome_architecture/outcome:   0%|          | 3/2000 [00:00<01:08, 28.95it/s, test=0.0%, test_loss=1.687, train=0.0%, train_loss=1.703]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:42, 46.69it/s, test=0.0%, test_loss=1.687, train=0.0%, train_loss=1.703]

outcome_architecture/outcome:   0%|          | 10/2000 [00:00<00:42, 46.69it/s, test=6.4%, test_loss=0.956, train=5.0%, train_loss=0.969]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 61.20it/s, test=6.4%, test_loss=0.956, train=5.0%, train_loss=0.969]

outcome_architecture/outcome:   1%|          | 20/2000 [00:00<00:32, 61.20it/s, test=6.9%, test_loss=0.934, train=6.3%, train_loss=0.957]

outcome_architecture/outcome:   1%|▏         | 27/2000 [00:00<00:31, 63.45it/s, test=6.9%, test_loss=0.934, train=6.3%, train_loss=0.957]

outcome_architecture/outcome:   2%|▏         | 38/2000 [00:00<00:25, 77.89it/s, test=6.9%, test_loss=0.934, train=6.3%, train_loss=0.957]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:22, 87.10it/s, test=6.9%, test_loss=0.934, train=6.3%, train_loss=0.957]

outcome_architecture/outcome:   2%|▏         | 49/2000 [00:00<00:22, 87.10it/s, test=8.5%, test_loss=0.927, train=8.7%, train_loss=0.941]

outcome_architecture/outcome:   3%|▎         | 58/2000 [00:00<00:23, 82.67it/s, test=8.5%, test_loss=0.927, train=8.7%, train_loss=0.941]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 89.54it/s, test=8.5%, test_loss=0.927, train=8.7%, train_loss=0.941]

outcome_architecture/outcome:   3%|▎         | 69/2000 [00:00<00:21, 89.54it/s, test=9.4%, test_loss=0.937, train=9.7%, train_loss=0.954]

outcome_architecture/outcome:   4%|▍         | 79/2000 [00:01<00:22, 85.02it/s, test=9.4%, test_loss=0.937, train=9.7%, train_loss=0.954]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:21, 90.91it/s, test=9.4%, test_loss=0.937, train=9.7%, train_loss=0.954]

outcome_architecture/outcome:   4%|▍         | 90/2000 [00:01<00:21, 90.91it/s, test=0.4%, test_loss=44.051, train=0.3%, train_loss=42.468]

outcome_architecture/outcome:   5%|▌         | 100/2000 [00:01<00:22, 86.13it/s, test=0.4%, test_loss=44.051, train=0.3%, train_loss=42.468]

outcome_architecture/outcome:   6%|▌         | 111/2000 [00:01<00:20, 91.66it/s, test=0.4%, test_loss=44.051, train=0.3%, train_loss=42.468]

outcome_architecture/outcome:   6%|▌         | 122/2000 [00:01<00:19, 95.52it/s, test=0.4%, test_loss=44.051, train=0.3%, train_loss=42.468]

outcome_architecture/outcome:   7%|▋         | 133/2000 [00:01<00:18, 98.27it/s, test=0.4%, test_loss=44.051, train=0.3%, train_loss=42.468]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 100.27it/s, test=0.4%, test_loss=44.051, train=0.3%, train_loss=42.468]

outcome_architecture/outcome:   7%|▋         | 144/2000 [00:01<00:18, 100.27it/s, test=0.9%, test_loss=2.136, train=0.3%, train_loss=2.210]

outcome_architecture/outcome:   8%|▊         | 155/2000 [00:01<00:19, 92.71it/s, test=0.9%, test_loss=2.136, train=0.3%, train_loss=2.210]

outcome_architecture/outcome:   8%|▊         | 166/2000 [00:01<00:19, 95.84it/s, test=0.9%, test_loss=2.136, train=0.3%, train_loss=2.210]

outcome_architecture/outcome:   9%|▉         | 177/2000 [00:02<00:18, 98.67it/s, test=0.9%, test_loss=2.136, train=0.3%, train_loss=2.210]

outcome_architecture/outcome:   9%|▉         | 188/2000 [00:02<00:18, 100.46it/s, test=0.9%, test_loss=2.136, train=0.3%, train_loss=2.210]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 101.87it/s, test=0.9%, test_loss=2.136, train=0.3%, train_loss=2.210]

outcome_architecture/outcome:  10%|▉         | 199/2000 [00:02<00:17, 101.87it/s, test=1.1%, test_loss=1.315, train=0.7%, train_loss=1.250]

outcome_architecture/outcome:  10%|█         | 210/2000 [00:02<00:19, 93.28it/s, test=1.1%, test_loss=1.315, train=0.7%, train_loss=1.250]

outcome_architecture/outcome:  11%|█         | 220/2000 [00:02<00:18, 94.80it/s, test=1.1%, test_loss=1.315, train=0.7%, train_loss=1.250]

outcome_architecture/outcome:  12%|█▏        | 230/2000 [00:02<00:18, 96.02it/s, test=1.1%, test_loss=1.315, train=0.7%, train_loss=1.250]

outcome_architecture/outcome:  12%|█▏        | 240/2000 [00:02<00:18, 94.33it/s, test=1.1%, test_loss=1.315, train=0.7%, train_loss=1.250]

outcome_architecture/outcome:  12%|█▏        | 240/2000 [00:02<00:18, 94.33it/s, test=9.1%, test_loss=0.971, train=9.3%, train_loss=1.003]

outcome_architecture/outcome:  12%|█▎        | 250/2000 [00:02<00:21, 83.20it/s, test=9.1%, test_loss=0.971, train=9.3%, train_loss=1.003]

outcome_architecture/outcome:  13%|█▎        | 260/2000 [00:02<00:20, 86.95it/s, test=9.1%, test_loss=0.971, train=9.3%, train_loss=1.003]

outcome_architecture/outcome:  14%|█▎        | 270/2000 [00:03<00:19, 90.00it/s, test=9.1%, test_loss=0.971, train=9.3%, train_loss=1.003]

outcome_architecture/outcome:  14%|█▍        | 280/2000 [00:03<00:18, 92.42it/s, test=9.1%, test_loss=0.971, train=9.3%, train_loss=1.003]

outcome_architecture/outcome:  14%|█▍        | 290/2000 [00:03<00:18, 94.24it/s, test=9.1%, test_loss=0.971, train=9.3%, train_loss=1.003]

outcome_architecture/outcome:  14%|█▍        | 290/2000 [00:03<00:18, 94.24it/s, test=8.5%, test_loss=0.983, train=6.7%, train_loss=0.973]

outcome_architecture/outcome:  15%|█▌        | 300/2000 [00:03<00:19, 86.52it/s, test=8.5%, test_loss=0.983, train=6.7%, train_loss=0.973]

outcome_architecture/outcome:  16%|█▌        | 310/2000 [00:03<00:18, 89.54it/s, test=8.5%, test_loss=0.983, train=6.7%, train_loss=0.973]

outcome_architecture/outcome:  16%|█▌        | 320/2000 [00:03<00:18, 92.07it/s, test=8.5%, test_loss=0.983, train=6.7%, train_loss=0.973]

outcome_architecture/outcome:  16%|█▋        | 330/2000 [00:03<00:17, 93.85it/s, test=8.5%, test_loss=0.983, train=6.7%, train_loss=0.973]

outcome_architecture/outcome:  17%|█▋        | 340/2000 [00:03<00:17, 95.16it/s, test=8.5%, test_loss=0.983, train=6.7%, train_loss=0.973]

outcome_architecture/outcome:  17%|█▋        | 340/2000 [00:03<00:17, 95.16it/s, test=8.6%, test_loss=0.953, train=8.7%, train_loss=0.954]

outcome_architecture/outcome:  18%|█▊        | 350/2000 [00:03<00:18, 87.04it/s, test=8.6%, test_loss=0.953, train=8.7%, train_loss=0.954]

outcome_architecture/outcome:  18%|█▊        | 360/2000 [00:04<00:18, 88.32it/s, test=8.6%, test_loss=0.953, train=8.7%, train_loss=0.954]

outcome_architecture/outcome:  18%|█▊        | 370/2000 [00:04<00:17, 91.16it/s, test=8.6%, test_loss=0.953, train=8.7%, train_loss=0.954]

outcome_architecture/outcome:  19%|█▉        | 380/2000 [00:04<00:17, 93.48it/s, test=8.6%, test_loss=0.953, train=8.7%, train_loss=0.954]

outcome_architecture/outcome:  20%|█▉        | 390/2000 [00:04<00:16, 94.85it/s, test=8.6%, test_loss=0.953, train=8.7%, train_loss=0.954]

outcome_architecture/outcome:  20%|█▉        | 390/2000 [00:04<00:16, 94.85it/s, test=10.7%, test_loss=0.955, train=7.3%, train_loss=0.969]

outcome_architecture/outcome:  20%|██        | 400/2000 [00:04<00:18, 86.69it/s, test=10.7%, test_loss=0.955, train=7.3%, train_loss=0.969]

outcome_architecture/outcome:  20%|██        | 410/2000 [00:04<00:17, 89.52it/s, test=10.7%, test_loss=0.955, train=7.3%, train_loss=0.969]

outcome_architecture/outcome:  21%|██        | 420/2000 [00:04<00:17, 92.21it/s, test=10.7%, test_loss=0.955, train=7.3%, train_loss=0.969]

outcome_architecture/outcome:  22%|██▏       | 430/2000 [00:04<00:16, 94.41it/s, test=10.7%, test_loss=0.955, train=7.3%, train_loss=0.969]

outcome_architecture/outcome:  22%|██▏       | 440/2000 [00:04<00:16, 95.65it/s, test=10.7%, test_loss=0.955, train=7.3%, train_loss=0.969]

outcome_architecture/outcome:  22%|██▏       | 440/2000 [00:05<00:16, 95.65it/s, test=11.5%, test_loss=0.924, train=10.7%, train_loss=0.938]

outcome_architecture/outcome:  22%|██▎       | 450/2000 [00:05<00:17, 88.93it/s, test=11.5%, test_loss=0.924, train=10.7%, train_loss=0.938]

outcome_architecture/outcome:  23%|██▎       | 461/2000 [00:05<00:16, 93.90it/s, test=11.5%, test_loss=0.924, train=10.7%, train_loss=0.938]

outcome_architecture/outcome:  24%|██▎       | 472/2000 [00:05<00:15, 97.51it/s, test=11.5%, test_loss=0.924, train=10.7%, train_loss=0.938]

outcome_architecture/outcome:  24%|██▍       | 483/2000 [00:05<00:15, 100.11it/s, test=11.5%, test_loss=0.924, train=10.7%, train_loss=0.938]

outcome_architecture/outcome:  25%|██▍       | 494/2000 [00:05<00:14, 102.01it/s, test=11.5%, test_loss=0.924, train=10.7%, train_loss=0.938]

outcome_architecture/outcome:  25%|██▍       | 494/2000 [00:05<00:14, 102.01it/s, test=9.9%, test_loss=0.931, train=8.7%, train_loss=0.931]

outcome_architecture/outcome:  25%|██▌       | 505/2000 [00:05<00:15, 93.93it/s, test=9.9%, test_loss=0.931, train=8.7%, train_loss=0.931]

outcome_architecture/outcome:  26%|██▌       | 516/2000 [00:05<00:15, 97.25it/s, test=9.9%, test_loss=0.931, train=8.7%, train_loss=0.931]

outcome_architecture/outcome:  26%|██▋       | 527/2000 [00:05<00:14, 100.02it/s, test=9.9%, test_loss=0.931, train=8.7%, train_loss=0.931]

outcome_architecture/outcome:  27%|██▋       | 538/2000 [00:05<00:14, 101.93it/s, test=9.9%, test_loss=0.931, train=8.7%, train_loss=0.931]

outcome_architecture/outcome:  27%|██▋       | 549/2000 [00:05<00:14, 103.16it/s, test=9.9%, test_loss=0.931, train=8.7%, train_loss=0.931]

outcome_architecture/outcome:  27%|██▋       | 549/2000 [00:06<00:14, 103.16it/s, test=12.0%, test_loss=0.918, train=8.3%, train_loss=0.906]

outcome_architecture/outcome:  28%|██▊       | 560/2000 [00:06<00:15, 94.21it/s, test=12.0%, test_loss=0.918, train=8.3%, train_loss=0.906]

outcome_architecture/outcome:  29%|██▊       | 571/2000 [00:06<00:14, 97.48it/s, test=12.0%, test_loss=0.918, train=8.3%, train_loss=0.906]

outcome_architecture/outcome:  29%|██▉       | 582/2000 [00:06<00:14, 99.86it/s, test=12.0%, test_loss=0.918, train=8.3%, train_loss=0.906]

outcome_architecture/outcome:  30%|██▉       | 593/2000 [00:06<00:13, 101.40it/s, test=12.0%, test_loss=0.918, train=8.3%, train_loss=0.906]

outcome_architecture/outcome:  30%|██▉       | 593/2000 [00:06<00:13, 101.40it/s, test=11.7%, test_loss=0.921, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  30%|███       | 604/2000 [00:06<00:14, 93.09it/s, test=11.7%, test_loss=0.921, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  31%|███       | 615/2000 [00:06<00:14, 96.57it/s, test=11.7%, test_loss=0.921, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  31%|███▏      | 626/2000 [00:06<00:13, 99.17it/s, test=11.7%, test_loss=0.921, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  32%|███▏      | 637/2000 [00:06<00:13, 101.17it/s, test=11.7%, test_loss=0.921, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  32%|███▏      | 648/2000 [00:06<00:13, 102.32it/s, test=11.7%, test_loss=0.921, train=10.7%, train_loss=0.922]

outcome_architecture/outcome:  32%|███▏      | 648/2000 [00:07<00:13, 102.32it/s, test=11.9%, test_loss=0.917, train=7.0%, train_loss=0.921]

outcome_architecture/outcome:  33%|███▎      | 659/2000 [00:07<00:14, 93.58it/s, test=11.9%, test_loss=0.917, train=7.0%, train_loss=0.921]

outcome_architecture/outcome:  34%|███▎      | 670/2000 [00:07<00:13, 96.83it/s, test=11.9%, test_loss=0.917, train=7.0%, train_loss=0.921]

outcome_architecture/outcome:  34%|███▍      | 681/2000 [00:07<00:13, 99.32it/s, test=11.9%, test_loss=0.917, train=7.0%, train_loss=0.921]

outcome_architecture/outcome:  35%|███▍      | 692/2000 [00:07<00:12, 101.13it/s, test=11.9%, test_loss=0.917, train=7.0%, train_loss=0.921]

outcome_architecture/outcome:  35%|███▍      | 692/2000 [00:07<00:12, 101.13it/s, test=11.5%, test_loss=0.925, train=8.7%, train_loss=0.917]

outcome_architecture/outcome:  35%|███▌      | 703/2000 [00:07<00:13, 93.23it/s, test=11.5%, test_loss=0.925, train=8.7%, train_loss=0.917]

outcome_architecture/outcome:  36%|███▌      | 714/2000 [00:07<00:13, 96.65it/s, test=11.5%, test_loss=0.925, train=8.7%, train_loss=0.917]

outcome_architecture/outcome:  36%|███▋      | 725/2000 [00:07<00:12, 98.79it/s, test=11.5%, test_loss=0.925, train=8.7%, train_loss=0.917]

outcome_architecture/outcome:  37%|███▋      | 736/2000 [00:07<00:12, 99.99it/s, test=11.5%, test_loss=0.925, train=8.7%, train_loss=0.917]

outcome_architecture/outcome:  37%|███▋      | 747/2000 [00:08<00:12, 101.64it/s, test=11.5%, test_loss=0.925, train=8.7%, train_loss=0.917]

outcome_architecture/outcome:  37%|███▋      | 747/2000 [00:08<00:12, 101.64it/s, test=11.1%, test_loss=0.907, train=9.3%, train_loss=0.911]

outcome_architecture/outcome:  38%|███▊      | 758/2000 [00:08<00:13, 93.42it/s, test=11.1%, test_loss=0.907, train=9.3%, train_loss=0.911]

outcome_architecture/outcome:  38%|███▊      | 769/2000 [00:08<00:12, 96.81it/s, test=11.1%, test_loss=0.907, train=9.3%, train_loss=0.911]

outcome_architecture/outcome:  39%|███▉      | 780/2000 [00:08<00:12, 99.50it/s, test=11.1%, test_loss=0.907, train=9.3%, train_loss=0.911]

outcome_architecture/outcome:  40%|███▉      | 791/2000 [00:08<00:11, 101.34it/s, test=11.1%, test_loss=0.907, train=9.3%, train_loss=0.911]

outcome_architecture/outcome:  40%|███▉      | 791/2000 [00:08<00:11, 101.34it/s, test=11.7%, test_loss=0.904, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  40%|████      | 802/2000 [00:08<00:12, 93.40it/s, test=11.7%, test_loss=0.904, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  41%|████      | 813/2000 [00:08<00:12, 96.86it/s, test=11.7%, test_loss=0.904, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  41%|████      | 824/2000 [00:08<00:11, 99.37it/s, test=11.7%, test_loss=0.904, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  42%|████▏     | 835/2000 [00:08<00:11, 100.61it/s, test=11.7%, test_loss=0.904, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  42%|████▏     | 846/2000 [00:09<00:11, 101.92it/s, test=11.7%, test_loss=0.904, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  42%|████▏     | 846/2000 [00:09<00:11, 101.92it/s, test=10.1%, test_loss=0.925, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  43%|████▎     | 857/2000 [00:09<00:12, 93.27it/s, test=10.1%, test_loss=0.925, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  43%|████▎     | 868/2000 [00:09<00:11, 96.51it/s, test=10.1%, test_loss=0.925, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  44%|████▍     | 879/2000 [00:09<00:11, 98.83it/s, test=10.1%, test_loss=0.925, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  44%|████▍     | 890/2000 [00:09<00:11, 100.68it/s, test=10.1%, test_loss=0.925, train=10.3%, train_loss=0.929]

outcome_architecture/outcome:  44%|████▍     | 890/2000 [00:09<00:11, 100.68it/s, test=12.5%, test_loss=0.923, train=8.3%, train_loss=0.907]

outcome_architecture/outcome:  45%|████▌     | 901/2000 [00:09<00:11, 92.53it/s, test=12.5%, test_loss=0.923, train=8.3%, train_loss=0.907]

outcome_architecture/outcome:  46%|████▌     | 912/2000 [00:09<00:11, 95.87it/s, test=12.5%, test_loss=0.923, train=8.3%, train_loss=0.907]

outcome_architecture/outcome:  46%|████▌     | 923/2000 [00:09<00:10, 98.57it/s, test=12.5%, test_loss=0.923, train=8.3%, train_loss=0.907]

outcome_architecture/outcome:  47%|████▋     | 934/2000 [00:09<00:10, 100.38it/s, test=12.5%, test_loss=0.923, train=8.3%, train_loss=0.907]

outcome_architecture/outcome:  47%|████▋     | 945/2000 [00:10<00:10, 101.93it/s, test=12.5%, test_loss=0.923, train=8.3%, train_loss=0.907]

outcome_architecture/outcome:  47%|████▋     | 945/2000 [00:10<00:10, 101.93it/s, test=14.1%, test_loss=0.923, train=8.0%, train_loss=0.914]

outcome_architecture/outcome:  48%|████▊     | 956/2000 [00:10<00:11, 93.37it/s, test=14.1%, test_loss=0.923, train=8.0%, train_loss=0.914]

outcome_architecture/outcome:  48%|████▊     | 967/2000 [00:10<00:10, 96.58it/s, test=14.1%, test_loss=0.923, train=8.0%, train_loss=0.914]

outcome_architecture/outcome:  49%|████▉     | 978/2000 [00:10<00:10, 99.03it/s, test=14.1%, test_loss=0.923, train=8.0%, train_loss=0.914]

outcome_architecture/outcome:  49%|████▉     | 989/2000 [00:10<00:10, 100.57it/s, test=14.1%, test_loss=0.923, train=8.0%, train_loss=0.914]

outcome_architecture/outcome:  49%|████▉     | 989/2000 [00:10<00:10, 100.57it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.901]

outcome_architecture/outcome:  50%|█████     | 1000/2000 [00:10<00:10, 92.67it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.901]

outcome_architecture/outcome:  51%|█████     | 1011/2000 [00:10<00:10, 96.18it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.901]

outcome_architecture/outcome:  51%|█████     | 1022/2000 [00:10<00:09, 98.16it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.901]

outcome_architecture/outcome:  52%|█████▏    | 1033/2000 [00:10<00:09, 100.28it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.901]

outcome_architecture/outcome:  52%|█████▏    | 1044/2000 [00:11<00:09, 99.97it/s, test=12.4%, test_loss=0.902, train=10.3%, train_loss=0.901]

outcome_architecture/outcome:  52%|█████▏    | 1044/2000 [00:11<00:09, 99.97it/s, test=12.2%, test_loss=0.924, train=8.3%, train_loss=0.921]

outcome_architecture/outcome:  53%|█████▎    | 1055/2000 [00:11<00:10, 92.20it/s, test=12.2%, test_loss=0.924, train=8.3%, train_loss=0.921]

outcome_architecture/outcome:  53%|█████▎    | 1066/2000 [00:11<00:09, 96.06it/s, test=12.2%, test_loss=0.924, train=8.3%, train_loss=0.921]

outcome_architecture/outcome:  54%|█████▍    | 1077/2000 [00:11<00:09, 98.94it/s, test=12.2%, test_loss=0.924, train=8.3%, train_loss=0.921]

outcome_architecture/outcome:  54%|█████▍    | 1088/2000 [00:11<00:09, 100.92it/s, test=12.2%, test_loss=0.924, train=8.3%, train_loss=0.921]

outcome_architecture/outcome:  55%|█████▍    | 1099/2000 [00:11<00:08, 102.56it/s, test=12.2%, test_loss=0.924, train=8.3%, train_loss=0.921]

outcome_architecture/outcome:  55%|█████▍    | 1099/2000 [00:11<00:08, 102.56it/s, test=14.0%, test_loss=0.898, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  56%|█████▌    | 1110/2000 [00:11<00:09, 94.19it/s, test=14.0%, test_loss=0.898, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  56%|█████▌    | 1121/2000 [00:11<00:09, 97.60it/s, test=14.0%, test_loss=0.898, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  57%|█████▋    | 1132/2000 [00:11<00:08, 100.25it/s, test=14.0%, test_loss=0.898, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  57%|█████▋    | 1143/2000 [00:12<00:08, 102.07it/s, test=14.0%, test_loss=0.898, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  57%|█████▋    | 1143/2000 [00:12<00:08, 102.07it/s, test=13.1%, test_loss=0.897, train=8.0%, train_loss=0.911]

outcome_architecture/outcome:  58%|█████▊    | 1154/2000 [00:12<00:09, 92.29it/s, test=13.1%, test_loss=0.897, train=8.0%, train_loss=0.911]

outcome_architecture/outcome:  58%|█████▊    | 1165/2000 [00:12<00:08, 96.12it/s, test=13.1%, test_loss=0.897, train=8.0%, train_loss=0.911]

outcome_architecture/outcome:  59%|█████▉    | 1176/2000 [00:12<00:08, 99.12it/s, test=13.1%, test_loss=0.897, train=8.0%, train_loss=0.911]

outcome_architecture/outcome:  59%|█████▉    | 1187/2000 [00:12<00:08, 101.34it/s, test=13.1%, test_loss=0.897, train=8.0%, train_loss=0.911]

outcome_architecture/outcome:  60%|█████▉    | 1198/2000 [00:12<00:07, 100.28it/s, test=13.1%, test_loss=0.897, train=8.0%, train_loss=0.911]

outcome_architecture/outcome:  60%|█████▉    | 1198/2000 [00:12<00:07, 100.28it/s, test=13.5%, test_loss=0.902, train=9.0%, train_loss=0.899]

outcome_architecture/outcome:  60%|██████    | 1209/2000 [00:12<00:08, 92.67it/s, test=13.5%, test_loss=0.902, train=9.0%, train_loss=0.899]

outcome_architecture/outcome:  61%|██████    | 1220/2000 [00:12<00:08, 96.18it/s, test=13.5%, test_loss=0.902, train=9.0%, train_loss=0.899]

outcome_architecture/outcome:  62%|██████▏   | 1231/2000 [00:12<00:07, 98.99it/s, test=13.5%, test_loss=0.902, train=9.0%, train_loss=0.899]

outcome_architecture/outcome:  62%|██████▏   | 1242/2000 [00:13<00:07, 99.06it/s, test=13.5%, test_loss=0.902, train=9.0%, train_loss=0.899]

outcome_architecture/outcome:  62%|██████▏   | 1242/2000 [00:13<00:07, 99.06it/s, test=13.3%, test_loss=0.903, train=9.7%, train_loss=0.917]

outcome_architecture/outcome:  63%|██████▎   | 1253/2000 [00:13<00:08, 91.71it/s, test=13.3%, test_loss=0.903, train=9.7%, train_loss=0.917]

outcome_architecture/outcome:  63%|██████▎   | 1264/2000 [00:13<00:07, 95.42it/s, test=13.3%, test_loss=0.903, train=9.7%, train_loss=0.917]

outcome_architecture/outcome:  64%|██████▍   | 1275/2000 [00:13<00:07, 98.18it/s, test=13.3%, test_loss=0.903, train=9.7%, train_loss=0.917]

outcome_architecture/outcome:  64%|██████▍   | 1285/2000 [00:13<00:07, 97.41it/s, test=13.3%, test_loss=0.903, train=9.7%, train_loss=0.917]

outcome_architecture/outcome:  65%|██████▍   | 1296/2000 [00:13<00:07, 99.17it/s, test=13.3%, test_loss=0.903, train=9.7%, train_loss=0.917]

outcome_architecture/outcome:  65%|██████▍   | 1296/2000 [00:13<00:07, 99.17it/s, test=13.4%, test_loss=0.894, train=11.0%, train_loss=0.901]

outcome_architecture/outcome:  65%|██████▌   | 1306/2000 [00:13<00:07, 90.49it/s, test=13.4%, test_loss=0.894, train=11.0%, train_loss=0.901]

outcome_architecture/outcome:  66%|██████▌   | 1317/2000 [00:13<00:07, 94.36it/s, test=13.4%, test_loss=0.894, train=11.0%, train_loss=0.901]

outcome_architecture/outcome:  66%|██████▋   | 1328/2000 [00:13<00:06, 96.87it/s, test=13.4%, test_loss=0.894, train=11.0%, train_loss=0.901]

outcome_architecture/outcome:  67%|██████▋   | 1338/2000 [00:14<00:06, 96.80it/s, test=13.4%, test_loss=0.894, train=11.0%, train_loss=0.901]

outcome_architecture/outcome:  67%|██████▋   | 1348/2000 [00:14<00:06, 96.97it/s, test=13.4%, test_loss=0.894, train=11.0%, train_loss=0.901]

outcome_architecture/outcome:  67%|██████▋   | 1348/2000 [00:14<00:06, 96.97it/s, test=14.3%, test_loss=0.892, train=9.0%, train_loss=0.906]

outcome_architecture/outcome:  68%|██████▊   | 1358/2000 [00:14<00:07, 87.83it/s, test=14.3%, test_loss=0.892, train=9.0%, train_loss=0.906]

outcome_architecture/outcome:  68%|██████▊   | 1368/2000 [00:14<00:07, 89.99it/s, test=14.3%, test_loss=0.892, train=9.0%, train_loss=0.906]

outcome_architecture/outcome:  69%|██████▉   | 1378/2000 [00:14<00:06, 91.60it/s, test=14.3%, test_loss=0.892, train=9.0%, train_loss=0.906]

outcome_architecture/outcome:  69%|██████▉   | 1389/2000 [00:14<00:06, 95.34it/s, test=14.3%, test_loss=0.892, train=9.0%, train_loss=0.906]

outcome_architecture/outcome:  69%|██████▉   | 1389/2000 [00:14<00:06, 95.34it/s, test=12.3%, test_loss=0.902, train=8.7%, train_loss=0.916]

outcome_architecture/outcome:  70%|███████   | 1400/2000 [00:14<00:06, 89.10it/s, test=12.3%, test_loss=0.902, train=8.7%, train_loss=0.916]

outcome_architecture/outcome:  70%|███████   | 1410/2000 [00:14<00:06, 91.98it/s, test=12.3%, test_loss=0.902, train=8.7%, train_loss=0.916]

outcome_architecture/outcome:  71%|███████   | 1421/2000 [00:14<00:06, 95.81it/s, test=12.3%, test_loss=0.902, train=8.7%, train_loss=0.916]

outcome_architecture/outcome:  72%|███████▏  | 1432/2000 [00:15<00:05, 98.55it/s, test=12.3%, test_loss=0.902, train=8.7%, train_loss=0.916]

outcome_architecture/outcome:  72%|███████▏  | 1442/2000 [00:15<00:05, 98.89it/s, test=12.3%, test_loss=0.902, train=8.7%, train_loss=0.916]

outcome_architecture/outcome:  72%|███████▏  | 1442/2000 [00:15<00:05, 98.89it/s, test=13.1%, test_loss=0.915, train=13.0%, train_loss=0.908]

outcome_architecture/outcome:  73%|███████▎  | 1452/2000 [00:15<00:06, 90.98it/s, test=13.1%, test_loss=0.915, train=13.0%, train_loss=0.908]

outcome_architecture/outcome:  73%|███████▎  | 1463/2000 [00:15<00:05, 94.47it/s, test=13.1%, test_loss=0.915, train=13.0%, train_loss=0.908]

outcome_architecture/outcome:  74%|███████▎  | 1473/2000 [00:15<00:05, 95.71it/s, test=13.1%, test_loss=0.915, train=13.0%, train_loss=0.908]

outcome_architecture/outcome:  74%|███████▍  | 1484/2000 [00:15<00:05, 98.26it/s, test=13.1%, test_loss=0.915, train=13.0%, train_loss=0.908]

outcome_architecture/outcome:  75%|███████▍  | 1495/2000 [00:15<00:05, 100.23it/s, test=13.1%, test_loss=0.915, train=13.0%, train_loss=0.908]

outcome_architecture/outcome:  75%|███████▍  | 1495/2000 [00:15<00:05, 100.23it/s, test=13.5%, test_loss=0.883, train=10.0%, train_loss=0.891]

outcome_architecture/outcome:  75%|███████▌  | 1506/2000 [00:15<00:05, 91.27it/s, test=13.5%, test_loss=0.883, train=10.0%, train_loss=0.891]

outcome_architecture/outcome:  76%|███████▌  | 1517/2000 [00:15<00:05, 95.19it/s, test=13.5%, test_loss=0.883, train=10.0%, train_loss=0.891]

outcome_architecture/outcome:  76%|███████▋  | 1527/2000 [00:16<00:04, 96.44it/s, test=13.5%, test_loss=0.883, train=10.0%, train_loss=0.891]

outcome_architecture/outcome:  77%|███████▋  | 1538/2000 [00:16<00:04, 99.20it/s, test=13.5%, test_loss=0.883, train=10.0%, train_loss=0.891]

outcome_architecture/outcome:  77%|███████▋  | 1549/2000 [00:16<00:04, 100.23it/s, test=13.5%, test_loss=0.883, train=10.0%, train_loss=0.891]

outcome_architecture/outcome:  77%|███████▋  | 1549/2000 [00:16<00:04, 100.23it/s, test=13.6%, test_loss=0.904, train=8.7%, train_loss=0.885]

outcome_architecture/outcome:  78%|███████▊  | 1560/2000 [00:16<00:04, 90.97it/s, test=13.6%, test_loss=0.904, train=8.7%, train_loss=0.885]

outcome_architecture/outcome:  79%|███████▊  | 1571/2000 [00:16<00:04, 95.03it/s, test=13.6%, test_loss=0.904, train=8.7%, train_loss=0.885]

outcome_architecture/outcome:  79%|███████▉  | 1582/2000 [00:16<00:04, 98.11it/s, test=13.6%, test_loss=0.904, train=8.7%, train_loss=0.885]

outcome_architecture/outcome:  80%|███████▉  | 1592/2000 [00:16<00:04, 98.04it/s, test=13.6%, test_loss=0.904, train=8.7%, train_loss=0.885]

outcome_architecture/outcome:  80%|███████▉  | 1592/2000 [00:16<00:04, 98.04it/s, test=14.1%, test_loss=0.906, train=11.3%, train_loss=0.904]

outcome_architecture/outcome:  80%|████████  | 1602/2000 [00:16<00:04, 90.68it/s, test=14.1%, test_loss=0.906, train=11.3%, train_loss=0.904]

outcome_architecture/outcome:  81%|████████  | 1613/2000 [00:17<00:04, 94.80it/s, test=14.1%, test_loss=0.906, train=11.3%, train_loss=0.904]

outcome_architecture/outcome:  81%|████████  | 1623/2000 [00:17<00:03, 96.18it/s, test=14.1%, test_loss=0.906, train=11.3%, train_loss=0.904]

outcome_architecture/outcome:  82%|████████▏ | 1634/2000 [00:17<00:03, 98.81it/s, test=14.1%, test_loss=0.906, train=11.3%, train_loss=0.904]

outcome_architecture/outcome:  82%|████████▏ | 1645/2000 [00:17<00:03, 100.77it/s, test=14.1%, test_loss=0.906, train=11.3%, train_loss=0.904]

outcome_architecture/outcome:  82%|████████▏ | 1645/2000 [00:17<00:03, 100.77it/s, test=15.2%, test_loss=0.897, train=12.7%, train_loss=0.901]

outcome_architecture/outcome:  83%|████████▎ | 1656/2000 [00:17<00:03, 91.39it/s, test=15.2%, test_loss=0.897, train=12.7%, train_loss=0.901]

outcome_architecture/outcome:  83%|████████▎ | 1667/2000 [00:17<00:03, 95.29it/s, test=15.2%, test_loss=0.897, train=12.7%, train_loss=0.901]

outcome_architecture/outcome:  84%|████████▍ | 1678/2000 [00:17<00:03, 97.45it/s, test=15.2%, test_loss=0.897, train=12.7%, train_loss=0.901]

outcome_architecture/outcome:  84%|████████▍ | 1689/2000 [00:17<00:03, 98.84it/s, test=15.2%, test_loss=0.897, train=12.7%, train_loss=0.901]

outcome_architecture/outcome:  84%|████████▍ | 1689/2000 [00:17<00:03, 98.84it/s, test=13.5%, test_loss=0.886, train=11.7%, train_loss=0.913]

outcome_architecture/outcome:  85%|████████▌ | 1700/2000 [00:17<00:03, 91.61it/s, test=13.5%, test_loss=0.886, train=11.7%, train_loss=0.913]

outcome_architecture/outcome:  86%|████████▌ | 1710/2000 [00:18<00:03, 91.78it/s, test=13.5%, test_loss=0.886, train=11.7%, train_loss=0.913]

outcome_architecture/outcome:  86%|████████▌ | 1720/2000 [00:18<00:02, 93.56it/s, test=13.5%, test_loss=0.886, train=11.7%, train_loss=0.913]

outcome_architecture/outcome:  86%|████████▋ | 1730/2000 [00:18<00:02, 94.91it/s, test=13.5%, test_loss=0.886, train=11.7%, train_loss=0.913]

outcome_architecture/outcome:  87%|████████▋ | 1740/2000 [00:18<00:02, 94.44it/s, test=13.5%, test_loss=0.886, train=11.7%, train_loss=0.913]

outcome_architecture/outcome:  87%|████████▋ | 1740/2000 [00:18<00:02, 94.44it/s, test=13.0%, test_loss=0.877, train=11.0%, train_loss=0.890]

outcome_architecture/outcome:  88%|████████▊ | 1750/2000 [00:18<00:02, 86.59it/s, test=13.0%, test_loss=0.877, train=11.0%, train_loss=0.890]

outcome_architecture/outcome:  88%|████████▊ | 1760/2000 [00:18<00:02, 89.25it/s, test=13.0%, test_loss=0.877, train=11.0%, train_loss=0.890]

outcome_architecture/outcome:  88%|████████▊ | 1770/2000 [00:18<00:02, 90.08it/s, test=13.0%, test_loss=0.877, train=11.0%, train_loss=0.890]

outcome_architecture/outcome:  89%|████████▉ | 1780/2000 [00:18<00:02, 92.07it/s, test=13.0%, test_loss=0.877, train=11.0%, train_loss=0.890]

outcome_architecture/outcome:  90%|████████▉ | 1790/2000 [00:18<00:02, 93.42it/s, test=13.0%, test_loss=0.877, train=11.0%, train_loss=0.890]

outcome_architecture/outcome:  90%|████████▉ | 1790/2000 [00:19<00:02, 93.42it/s, test=13.0%, test_loss=0.894, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  90%|█████████ | 1800/2000 [00:19<00:02, 84.29it/s, test=13.0%, test_loss=0.894, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  90%|█████████ | 1810/2000 [00:19<00:02, 87.91it/s, test=13.0%, test_loss=0.894, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  91%|█████████ | 1820/2000 [00:19<00:01, 90.92it/s, test=13.0%, test_loss=0.894, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  92%|█████████▏| 1830/2000 [00:19<00:01, 91.95it/s, test=13.0%, test_loss=0.894, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  92%|█████████▏| 1840/2000 [00:19<00:01, 93.73it/s, test=13.0%, test_loss=0.894, train=10.7%, train_loss=0.904]

outcome_architecture/outcome:  92%|█████████▏| 1840/2000 [00:19<00:01, 93.73it/s, test=13.2%, test_loss=0.888, train=9.3%, train_loss=0.900]

outcome_architecture/outcome:  92%|█████████▎| 1850/2000 [00:19<00:01, 84.35it/s, test=13.2%, test_loss=0.888, train=9.3%, train_loss=0.900]

outcome_architecture/outcome:  93%|█████████▎| 1860/2000 [00:19<00:01, 87.57it/s, test=13.2%, test_loss=0.888, train=9.3%, train_loss=0.900]

outcome_architecture/outcome:  94%|█████████▎| 1870/2000 [00:19<00:01, 90.58it/s, test=13.2%, test_loss=0.888, train=9.3%, train_loss=0.900]

outcome_architecture/outcome:  94%|█████████▍| 1880/2000 [00:19<00:01, 92.75it/s, test=13.2%, test_loss=0.888, train=9.3%, train_loss=0.900]

outcome_architecture/outcome:  94%|█████████▍| 1890/2000 [00:20<00:01, 94.11it/s, test=13.2%, test_loss=0.888, train=9.3%, train_loss=0.900]

outcome_architecture/outcome:  94%|█████████▍| 1890/2000 [00:20<00:01, 94.11it/s, test=15.0%, test_loss=0.897, train=13.0%, train_loss=0.906]

outcome_architecture/outcome:  95%|█████████▌| 1900/2000 [00:20<00:01, 86.37it/s, test=15.0%, test_loss=0.897, train=13.0%, train_loss=0.906]

outcome_architecture/outcome:  96%|█████████▌| 1910/2000 [00:20<00:01, 89.71it/s, test=15.0%, test_loss=0.897, train=13.0%, train_loss=0.906]

outcome_architecture/outcome:  96%|█████████▌| 1920/2000 [00:20<00:00, 92.19it/s, test=15.0%, test_loss=0.897, train=13.0%, train_loss=0.906]

outcome_architecture/outcome:  96%|█████████▋| 1930/2000 [00:20<00:00, 93.64it/s, test=15.0%, test_loss=0.897, train=13.0%, train_loss=0.906]

outcome_architecture/outcome:  97%|█████████▋| 1940/2000 [00:20<00:00, 94.71it/s, test=15.0%, test_loss=0.897, train=13.0%, train_loss=0.906]

outcome_architecture/outcome:  97%|█████████▋| 1940/2000 [00:20<00:00, 94.71it/s, test=14.3%, test_loss=0.901, train=10.0%, train_loss=0.921]

outcome_architecture/outcome:  98%|█████████▊| 1950/2000 [00:20<00:00, 85.94it/s, test=14.3%, test_loss=0.901, train=10.0%, train_loss=0.921]

outcome_architecture/outcome:  98%|█████████▊| 1960/2000 [00:20<00:00, 88.37it/s, test=14.3%, test_loss=0.901, train=10.0%, train_loss=0.921]

outcome_architecture/outcome:  98%|█████████▊| 1970/2000 [00:20<00:00, 90.64it/s, test=14.3%, test_loss=0.901, train=10.0%, train_loss=0.921]

outcome_architecture/outcome:  99%|█████████▉| 1980/2000 [00:21<00:00, 92.05it/s, test=14.3%, test_loss=0.901, train=10.0%, train_loss=0.921]

outcome_architecture/outcome: 100%|█████████▉| 1991/2000 [00:21<00:00, 96.20it/s, test=14.3%, test_loss=0.901, train=10.0%, train_loss=0.921]

outcome_architecture/outcome: 100%|█████████▉| 1991/2000 [00:21<00:00, 96.20it/s, test=10.0%, test_loss=0.893, train=10.3%, train_loss=0.911]

outcome_architecture/outcome: 100%|██████████| 2000/2000 [00:21<00:00, 94.17it/s, test=10.0%, test_loss=0.893, train=10.3%, train_loss=0.911]

architecture/mode:  75%|███████▌  | 3/4 [00:44<00:16, 16.14s/it]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s]

outcome_architecture/process:   0%|          | 0/2000 [00:00<?, ?it/s, test=0.0%, test_loss=4.107, train=0.0%, train_loss=4.117]

outcome_architecture/process:   0%|          | 1/2000 [00:00<05:20,  6.23it/s, test=0.0%, test_loss=4.107, train=0.0%, train_loss=4.117]

outcome_architecture/process:   0%|          | 1/2000 [00:00<05:20,  6.23it/s, test=0.0%, test_loss=15.698, train=0.0%, train_loss=15.883]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:18,  6.27it/s, test=0.0%, test_loss=15.698, train=0.0%, train_loss=15.883]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:18,  6.27it/s, test=0.0%, test_loss=4.090, train=0.0%, train_loss=4.097]

outcome_architecture/process:   0%|          | 2/2000 [00:00<05:18,  6.27it/s, test=0.0%, test_loss=3.429, train=0.0%, train_loss=3.449]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:09, 28.48it/s, test=0.0%, test_loss=3.429, train=0.0%, train_loss=3.449]

outcome_architecture/process:   0%|          | 10/2000 [00:00<01:09, 28.48it/s, test=6.5%, test_loss=2.734, train=8.7%, train_loss=2.768]

outcome_architecture/process:   1%|          | 20/2000 [00:00<00:56, 35.11it/s, test=6.5%, test_loss=2.734, train=8.7%, train_loss=2.768]

outcome_architecture/process:   1%|          | 20/2000 [00:00<00:56, 35.11it/s, test=5.6%, test_loss=2.673, train=6.7%, train_loss=2.694]

outcome_architecture/process:   1%|▏         | 25/2000 [00:00<01:03, 31.02it/s, test=5.6%, test_loss=2.673, train=6.7%, train_loss=2.694]

outcome_architecture/process:   2%|▏         | 36/2000 [00:01<00:41, 47.31it/s, test=5.6%, test_loss=2.673, train=6.7%, train_loss=2.694]

outcome_architecture/process:   2%|▏         | 46/2000 [00:01<00:33, 59.14it/s, test=5.6%, test_loss=2.673, train=6.7%, train_loss=2.694]

outcome_architecture/process:   2%|▏         | 46/2000 [00:01<00:33, 59.14it/s, test=0.0%, test_loss=2.720, train=0.0%, train_loss=2.788]

outcome_architecture/process:   3%|▎         | 53/2000 [00:01<00:40, 48.18it/s, test=0.0%, test_loss=2.720, train=0.0%, train_loss=2.788]

outcome_architecture/process:   3%|▎         | 63/2000 [00:01<00:32, 59.01it/s, test=0.0%, test_loss=2.720, train=0.0%, train_loss=2.788]

outcome_architecture/process:   4%|▎         | 74/2000 [00:01<00:27, 70.31it/s, test=0.0%, test_loss=2.720, train=0.0%, train_loss=2.788]

outcome_architecture/process:   4%|▎         | 74/2000 [00:01<00:27, 70.31it/s, test=7.0%, test_loss=4.579, train=5.0%, train_loss=4.475]

outcome_architecture/process:   4%|▍         | 83/2000 [00:01<00:34, 56.28it/s, test=7.0%, test_loss=4.579, train=5.0%, train_loss=4.475]

outcome_architecture/process:   5%|▍         | 94/2000 [00:01<00:28, 67.01it/s, test=7.0%, test_loss=4.579, train=5.0%, train_loss=4.475]

outcome_architecture/process:   5%|▍         | 94/2000 [00:02<00:28, 67.01it/s, test=8.5%, test_loss=2.738, train=9.7%, train_loss=2.778]

outcome_architecture/process:   5%|▌         | 102/2000 [00:02<00:34, 54.45it/s, test=8.5%, test_loss=2.738, train=9.7%, train_loss=2.778]

outcome_architecture/process:   6%|▌         | 113/2000 [00:02<00:28, 65.25it/s, test=8.5%, test_loss=2.738, train=9.7%, train_loss=2.778]

outcome_architecture/process:   6%|▌         | 124/2000 [00:02<00:25, 74.55it/s, test=8.5%, test_loss=2.738, train=9.7%, train_loss=2.778]

outcome_architecture/process:   7%|▋         | 134/2000 [00:02<00:23, 79.93it/s, test=8.5%, test_loss=2.738, train=9.7%, train_loss=2.778]

outcome_architecture/process:   7%|▋         | 145/2000 [00:02<00:21, 86.85it/s, test=8.5%, test_loss=2.738, train=9.7%, train_loss=2.778]

outcome_architecture/process:   7%|▋         | 145/2000 [00:02<00:21, 86.85it/s, test=12.0%, test_loss=2.523, train=9.7%, train_loss=2.539]

outcome_architecture/process:   8%|▊         | 155/2000 [00:02<00:28, 65.56it/s, test=12.0%, test_loss=2.523, train=9.7%, train_loss=2.539]

outcome_architecture/process:   8%|▊         | 166/2000 [00:02<00:24, 74.36it/s, test=12.0%, test_loss=2.523, train=9.7%, train_loss=2.539]

outcome_architecture/process:   9%|▉         | 177/2000 [00:02<00:22, 81.85it/s, test=12.0%, test_loss=2.523, train=9.7%, train_loss=2.539]

outcome_architecture/process:   9%|▉         | 187/2000 [00:03<00:21, 85.60it/s, test=12.0%, test_loss=2.523, train=9.7%, train_loss=2.539]

outcome_architecture/process:  10%|▉         | 198/2000 [00:03<00:19, 91.20it/s, test=12.0%, test_loss=2.523, train=9.7%, train_loss=2.539]

outcome_architecture/process:  10%|▉         | 198/2000 [00:03<00:19, 91.20it/s, test=11.6%, test_loss=2.411, train=10.7%, train_loss=2.451]

outcome_architecture/process:  10%|█         | 208/2000 [00:03<00:26, 67.40it/s, test=11.6%, test_loss=2.411, train=10.7%, train_loss=2.451]

outcome_architecture/process:  11%|█         | 219/2000 [00:03<00:23, 75.88it/s, test=11.6%, test_loss=2.411, train=10.7%, train_loss=2.451]

outcome_architecture/process:  12%|█▏        | 230/2000 [00:03<00:21, 82.00it/s, test=11.6%, test_loss=2.411, train=10.7%, train_loss=2.451]

outcome_architecture/process:  12%|█▏        | 241/2000 [00:03<00:19, 88.09it/s, test=11.6%, test_loss=2.411, train=10.7%, train_loss=2.451]

outcome_architecture/process:  12%|█▏        | 241/2000 [00:03<00:19, 88.09it/s, test=9.0%, test_loss=2.602, train=8.7%, train_loss=2.553]

outcome_architecture/process:  13%|█▎        | 251/2000 [00:03<00:26, 65.79it/s, test=9.0%, test_loss=2.602, train=8.7%, train_loss=2.553]

outcome_architecture/process:  13%|█▎        | 262/2000 [00:04<00:23, 74.47it/s, test=9.0%, test_loss=2.602, train=8.7%, train_loss=2.553]

outcome_architecture/process:  14%|█▎        | 273/2000 [00:04<00:21, 81.72it/s, test=9.0%, test_loss=2.602, train=8.7%, train_loss=2.553]

outcome_architecture/process:  14%|█▍        | 283/2000 [00:04<00:19, 86.13it/s, test=9.0%, test_loss=2.602, train=8.7%, train_loss=2.553]

outcome_architecture/process:  15%|█▍        | 294/2000 [00:04<00:18, 91.16it/s, test=9.0%, test_loss=2.602, train=8.7%, train_loss=2.553]

outcome_architecture/process:  15%|█▍        | 294/2000 [00:04<00:18, 91.16it/s, test=12.9%, test_loss=2.290, train=12.7%, train_loss=2.338]

outcome_architecture/process:  15%|█▌        | 304/2000 [00:04<00:25, 66.51it/s, test=12.9%, test_loss=2.290, train=12.7%, train_loss=2.338]

outcome_architecture/process:  16%|█▌        | 315/2000 [00:04<00:22, 75.08it/s, test=12.9%, test_loss=2.290, train=12.7%, train_loss=2.338]

outcome_architecture/process:  16%|█▋        | 326/2000 [00:04<00:20, 82.35it/s, test=12.9%, test_loss=2.290, train=12.7%, train_loss=2.338]

outcome_architecture/process:  17%|█▋        | 336/2000 [00:04<00:19, 86.46it/s, test=12.9%, test_loss=2.290, train=12.7%, train_loss=2.338]

outcome_architecture/process:  17%|█▋        | 347/2000 [00:05<00:18, 90.25it/s, test=12.9%, test_loss=2.290, train=12.7%, train_loss=2.338]

outcome_architecture/process:  17%|█▋        | 347/2000 [00:05<00:18, 90.25it/s, test=13.5%, test_loss=2.058, train=11.3%, train_loss=2.075]

outcome_architecture/process:  18%|█▊        | 357/2000 [00:05<00:25, 65.49it/s, test=13.5%, test_loss=2.058, train=11.3%, train_loss=2.075]

outcome_architecture/process:  18%|█▊        | 367/2000 [00:05<00:22, 72.55it/s, test=13.5%, test_loss=2.058, train=11.3%, train_loss=2.075]

outcome_architecture/process:  19%|█▉        | 377/2000 [00:05<00:20, 77.52it/s, test=13.5%, test_loss=2.058, train=11.3%, train_loss=2.075]

outcome_architecture/process:  19%|█▉        | 387/2000 [00:05<00:19, 81.96it/s, test=13.5%, test_loss=2.058, train=11.3%, train_loss=2.075]

outcome_architecture/process:  20%|█▉        | 397/2000 [00:05<00:18, 86.17it/s, test=13.5%, test_loss=2.058, train=11.3%, train_loss=2.075]

outcome_architecture/process:  20%|█▉        | 397/2000 [00:05<00:18, 86.17it/s, test=13.1%, test_loss=1.900, train=10.7%, train_loss=1.903]

outcome_architecture/process:  20%|██        | 407/2000 [00:05<00:24, 63.78it/s, test=13.1%, test_loss=1.900, train=10.7%, train_loss=1.903]

outcome_architecture/process:  21%|██        | 417/2000 [00:06<00:22, 71.19it/s, test=13.1%, test_loss=1.900, train=10.7%, train_loss=1.903]

outcome_architecture/process:  21%|██▏       | 428/2000 [00:06<00:19, 78.66it/s, test=13.1%, test_loss=1.900, train=10.7%, train_loss=1.903]

outcome_architecture/process:  22%|██▏       | 439/2000 [00:06<00:18, 85.69it/s, test=13.1%, test_loss=1.900, train=10.7%, train_loss=1.903]

outcome_architecture/process:  22%|██▏       | 439/2000 [00:06<00:18, 85.69it/s, test=14.6%, test_loss=1.877, train=13.0%, train_loss=1.852]

outcome_architecture/process:  22%|██▎       | 450/2000 [00:06<00:23, 65.60it/s, test=14.6%, test_loss=1.877, train=13.0%, train_loss=1.852]

outcome_architecture/process:  23%|██▎       | 461/2000 [00:06<00:20, 73.93it/s, test=14.6%, test_loss=1.877, train=13.0%, train_loss=1.852]

outcome_architecture/process:  24%|██▎       | 472/2000 [00:06<00:18, 81.32it/s, test=14.6%, test_loss=1.877, train=13.0%, train_loss=1.852]

outcome_architecture/process:  24%|██▍       | 483/2000 [00:06<00:17, 87.30it/s, test=14.6%, test_loss=1.877, train=13.0%, train_loss=1.852]

outcome_architecture/process:  25%|██▍       | 494/2000 [00:06<00:16, 92.11it/s, test=14.6%, test_loss=1.877, train=13.0%, train_loss=1.852]

outcome_architecture/process:  25%|██▍       | 494/2000 [00:07<00:16, 92.11it/s, test=12.6%, test_loss=1.640, train=13.0%, train_loss=1.597]

outcome_architecture/process:  25%|██▌       | 504/2000 [00:07<00:21, 68.09it/s, test=12.6%, test_loss=1.640, train=13.0%, train_loss=1.597]

outcome_architecture/process:  26%|██▌       | 515/2000 [00:07<00:19, 76.37it/s, test=12.6%, test_loss=1.640, train=13.0%, train_loss=1.597]

outcome_architecture/process:  26%|██▋       | 526/2000 [00:07<00:17, 83.30it/s, test=12.6%, test_loss=1.640, train=13.0%, train_loss=1.597]

outcome_architecture/process:  27%|██▋       | 537/2000 [00:07<00:16, 88.98it/s, test=12.6%, test_loss=1.640, train=13.0%, train_loss=1.597]

outcome_architecture/process:  27%|██▋       | 548/2000 [00:07<00:15, 93.57it/s, test=12.6%, test_loss=1.640, train=13.0%, train_loss=1.597]

outcome_architecture/process:  27%|██▋       | 548/2000 [00:07<00:15, 93.57it/s, test=12.5%, test_loss=1.406, train=12.7%, train_loss=1.433]

outcome_architecture/process:  28%|██▊       | 558/2000 [00:07<00:20, 68.83it/s, test=12.5%, test_loss=1.406, train=12.7%, train_loss=1.433]

outcome_architecture/process:  28%|██▊       | 569/2000 [00:07<00:18, 77.10it/s, test=12.5%, test_loss=1.406, train=12.7%, train_loss=1.433]

outcome_architecture/process:  29%|██▉       | 580/2000 [00:08<00:16, 84.04it/s, test=12.5%, test_loss=1.406, train=12.7%, train_loss=1.433]

outcome_architecture/process:  30%|██▉       | 591/2000 [00:08<00:15, 89.59it/s, test=12.5%, test_loss=1.406, train=12.7%, train_loss=1.433]

outcome_architecture/process:  30%|██▉       | 591/2000 [00:08<00:15, 89.59it/s, test=11.5%, test_loss=1.563, train=8.7%, train_loss=1.531]

outcome_architecture/process:  30%|███       | 601/2000 [00:08<00:20, 67.22it/s, test=11.5%, test_loss=1.563, train=8.7%, train_loss=1.531]

outcome_architecture/process:  31%|███       | 612/2000 [00:08<00:18, 75.73it/s, test=11.5%, test_loss=1.563, train=8.7%, train_loss=1.531]

outcome_architecture/process:  31%|███       | 623/2000 [00:08<00:16, 82.84it/s, test=11.5%, test_loss=1.563, train=8.7%, train_loss=1.531]

outcome_architecture/process:  32%|███▏      | 634/2000 [00:08<00:15, 88.74it/s, test=11.5%, test_loss=1.563, train=8.7%, train_loss=1.531]

outcome_architecture/process:  32%|███▏      | 645/2000 [00:08<00:14, 93.25it/s, test=11.5%, test_loss=1.563, train=8.7%, train_loss=1.531]

outcome_architecture/process:  32%|███▏      | 645/2000 [00:09<00:14, 93.25it/s, test=19.7%, test_loss=0.679, train=24.0%, train_loss=0.730]

outcome_architecture/process:  33%|███▎      | 655/2000 [00:09<00:19, 68.71it/s, test=19.7%, test_loss=0.679, train=24.0%, train_loss=0.730]

outcome_architecture/process:  33%|███▎      | 666/2000 [00:09<00:17, 77.05it/s, test=19.7%, test_loss=0.679, train=24.0%, train_loss=0.730]

outcome_architecture/process:  34%|███▍      | 677/2000 [00:09<00:15, 83.98it/s, test=19.7%, test_loss=0.679, train=24.0%, train_loss=0.730]

outcome_architecture/process:  34%|███▍      | 688/2000 [00:09<00:14, 89.73it/s, test=19.7%, test_loss=0.679, train=24.0%, train_loss=0.730]

outcome_architecture/process:  35%|███▍      | 699/2000 [00:09<00:13, 94.28it/s, test=19.7%, test_loss=0.679, train=24.0%, train_loss=0.730]

outcome_architecture/process:  35%|███▍      | 699/2000 [00:09<00:13, 94.28it/s, test=17.8%, test_loss=1.056, train=16.7%, train_loss=1.096]

outcome_architecture/process:  36%|███▌      | 710/2000 [00:09<00:18, 69.66it/s, test=17.8%, test_loss=1.056, train=16.7%, train_loss=1.096]

outcome_architecture/process:  36%|███▌      | 721/2000 [00:09<00:16, 77.54it/s, test=17.8%, test_loss=1.056, train=16.7%, train_loss=1.096]

outcome_architecture/process:  37%|███▋      | 732/2000 [00:09<00:15, 84.26it/s, test=17.8%, test_loss=1.056, train=16.7%, train_loss=1.096]

outcome_architecture/process:  37%|███▋      | 743/2000 [00:10<00:14, 89.64it/s, test=17.8%, test_loss=1.056, train=16.7%, train_loss=1.096]

outcome_architecture/process:  37%|███▋      | 743/2000 [00:10<00:14, 89.64it/s, test=63.6%, test_loss=0.186, train=59.3%, train_loss=0.209]

outcome_architecture/process:  38%|███▊      | 753/2000 [00:10<00:18, 67.18it/s, test=63.6%, test_loss=0.186, train=59.3%, train_loss=0.209]

outcome_architecture/process:  38%|███▊      | 764/2000 [00:10<00:16, 75.56it/s, test=63.6%, test_loss=0.186, train=59.3%, train_loss=0.209]

outcome_architecture/process:  39%|███▉      | 775/2000 [00:10<00:14, 82.68it/s, test=63.6%, test_loss=0.186, train=59.3%, train_loss=0.209]

outcome_architecture/process:  39%|███▉      | 786/2000 [00:10<00:13, 88.43it/s, test=63.6%, test_loss=0.186, train=59.3%, train_loss=0.209]

outcome_architecture/process:  40%|███▉      | 797/2000 [00:10<00:12, 92.86it/s, test=63.6%, test_loss=0.186, train=59.3%, train_loss=0.209]

outcome_architecture/process:  40%|███▉      | 797/2000 [00:10<00:12, 92.86it/s, test=45.5%, test_loss=0.187, train=44.7%, train_loss=0.215]

outcome_architecture/process:  40%|████      | 807/2000 [00:10<00:17, 68.64it/s, test=45.5%, test_loss=0.187, train=44.7%, train_loss=0.215]

outcome_architecture/process:  41%|████      | 818/2000 [00:11<00:15, 76.94it/s, test=45.5%, test_loss=0.187, train=44.7%, train_loss=0.215]

outcome_architecture/process:  41%|████▏     | 829/2000 [00:11<00:13, 83.77it/s, test=45.5%, test_loss=0.187, train=44.7%, train_loss=0.215]

outcome_architecture/process:  42%|████▏     | 840/2000 [00:11<00:12, 89.39it/s, test=45.5%, test_loss=0.187, train=44.7%, train_loss=0.215]

outcome_architecture/process:  42%|████▏     | 840/2000 [00:11<00:12, 89.39it/s, test=77.6%, test_loss=0.082, train=78.0%, train_loss=0.077]

outcome_architecture/process:  42%|████▎     | 850/2000 [00:11<00:17, 67.21it/s, test=77.6%, test_loss=0.082, train=78.0%, train_loss=0.077]

outcome_architecture/process:  43%|████▎     | 861/2000 [00:11<00:15, 75.65it/s, test=77.6%, test_loss=0.082, train=78.0%, train_loss=0.077]

outcome_architecture/process:  44%|████▎     | 872/2000 [00:11<00:13, 82.87it/s, test=77.6%, test_loss=0.082, train=78.0%, train_loss=0.077]

outcome_architecture/process:  44%|████▍     | 883/2000 [00:11<00:12, 88.62it/s, test=77.6%, test_loss=0.082, train=78.0%, train_loss=0.077]

outcome_architecture/process:  45%|████▍     | 894/2000 [00:11<00:11, 93.12it/s, test=77.6%, test_loss=0.082, train=78.0%, train_loss=0.077]

outcome_architecture/process:  45%|████▍     | 894/2000 [00:12<00:11, 93.12it/s, test=93.5%, test_loss=0.017, train=92.7%, train_loss=0.016]

outcome_architecture/process:  45%|████▌     | 904/2000 [00:12<00:15, 68.74it/s, test=93.5%, test_loss=0.017, train=92.7%, train_loss=0.016]

outcome_architecture/process:  46%|████▌     | 915/2000 [00:12<00:14, 76.99it/s, test=93.5%, test_loss=0.017, train=92.7%, train_loss=0.016]

outcome_architecture/process:  46%|████▋     | 926/2000 [00:12<00:12, 83.91it/s, test=93.5%, test_loss=0.017, train=92.7%, train_loss=0.016]

outcome_architecture/process:  47%|████▋     | 937/2000 [00:12<00:11, 89.47it/s, test=93.5%, test_loss=0.017, train=92.7%, train_loss=0.016]

outcome_architecture/process:  47%|████▋     | 948/2000 [00:12<00:11, 93.84it/s, test=93.5%, test_loss=0.017, train=92.7%, train_loss=0.016]

outcome_architecture/process:  47%|████▋     | 948/2000 [00:12<00:11, 93.84it/s, test=96.0%, test_loss=0.016, train=95.0%, train_loss=0.017]

outcome_architecture/process:  48%|████▊     | 958/2000 [00:12<00:15, 69.11it/s, test=96.0%, test_loss=0.016, train=95.0%, train_loss=0.017]

outcome_architecture/process:  48%|████▊     | 969/2000 [00:12<00:13, 77.34it/s, test=96.0%, test_loss=0.016, train=95.0%, train_loss=0.017]

outcome_architecture/process:  49%|████▉     | 980/2000 [00:13<00:12, 84.16it/s, test=96.0%, test_loss=0.016, train=95.0%, train_loss=0.017]

outcome_architecture/process:  50%|████▉     | 991/2000 [00:13<00:11, 89.82it/s, test=96.0%, test_loss=0.016, train=95.0%, train_loss=0.017]

outcome_architecture/process:  50%|████▉     | 991/2000 [00:13<00:11, 89.82it/s, test=99.5%, test_loss=0.003, train=99.3%, train_loss=0.004]

outcome_architecture/process:  50%|█████     | 1001/2000 [00:13<00:14, 67.28it/s, test=99.5%, test_loss=0.003, train=99.3%, train_loss=0.004]

outcome_architecture/process:  51%|█████     | 1012/2000 [00:13<00:13, 75.77it/s, test=99.5%, test_loss=0.003, train=99.3%, train_loss=0.004]

outcome_architecture/process:  51%|█████     | 1023/2000 [00:13<00:11, 82.90it/s, test=99.5%, test_loss=0.003, train=99.3%, train_loss=0.004]

outcome_architecture/process:  52%|█████▏    | 1034/2000 [00:13<00:10, 88.77it/s, test=99.5%, test_loss=0.003, train=99.3%, train_loss=0.004]

outcome_architecture/process:  52%|█████▏    | 1045/2000 [00:13<00:10, 93.34it/s, test=99.5%, test_loss=0.003, train=99.3%, train_loss=0.004]

outcome_architecture/process:  52%|█████▏    | 1045/2000 [00:14<00:10, 93.34it/s, test=99.9%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  53%|█████▎    | 1055/2000 [00:14<00:13, 68.91it/s, test=99.9%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  53%|█████▎    | 1066/2000 [00:14<00:12, 77.25it/s, test=99.9%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  54%|█████▍    | 1077/2000 [00:14<00:10, 84.11it/s, test=99.9%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  54%|█████▍    | 1088/2000 [00:14<00:10, 89.65it/s, test=99.9%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  55%|█████▍    | 1099/2000 [00:14<00:09, 94.00it/s, test=99.9%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  55%|█████▍    | 1099/2000 [00:14<00:09, 94.00it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  56%|█████▌    | 1110/2000 [00:14<00:12, 68.85it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  56%|█████▌    | 1120/2000 [00:14<00:11, 75.46it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  57%|█████▋    | 1131/2000 [00:14<00:10, 81.89it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  57%|█████▋    | 1142/2000 [00:15<00:09, 87.41it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  57%|█████▋    | 1142/2000 [00:15<00:09, 87.41it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  58%|█████▊    | 1152/2000 [00:15<00:13, 63.03it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  58%|█████▊    | 1162/2000 [00:15<00:11, 70.29it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  59%|█████▊    | 1172/2000 [00:15<00:10, 76.29it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  59%|█████▉    | 1182/2000 [00:15<00:10, 80.60it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  60%|█████▉    | 1192/2000 [00:15<00:09, 83.59it/s, test=100.0%, test_loss=0.001, train=100.0%, train_loss=0.001]

outcome_architecture/process:  60%|█████▉    | 1192/2000 [00:15<00:09, 83.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  60%|██████    | 1202/2000 [00:16<00:12, 62.42it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  61%|██████    | 1212/2000 [00:16<00:11, 69.43it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  61%|██████    | 1222/2000 [00:16<00:10, 74.80it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  62%|██████▏   | 1232/2000 [00:16<00:09, 80.25it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  62%|██████▏   | 1242/2000 [00:16<00:08, 84.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  62%|██████▏   | 1242/2000 [00:16<00:08, 84.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  63%|██████▎   | 1252/2000 [00:16<00:11, 63.38it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  63%|██████▎   | 1262/2000 [00:16<00:10, 70.89it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  64%|██████▎   | 1272/2000 [00:16<00:09, 77.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  64%|██████▍   | 1282/2000 [00:16<00:08, 81.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  65%|██████▍   | 1292/2000 [00:17<00:08, 86.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  65%|██████▍   | 1292/2000 [00:17<00:08, 86.01it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  65%|██████▌   | 1302/2000 [00:17<00:10, 64.45it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  66%|██████▌   | 1313/2000 [00:17<00:09, 72.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  66%|██████▌   | 1324/2000 [00:17<00:08, 79.90it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  67%|██████▋   | 1335/2000 [00:17<00:07, 85.46it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  67%|██████▋   | 1346/2000 [00:17<00:07, 89.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  67%|██████▋   | 1346/2000 [00:17<00:07, 89.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  68%|██████▊   | 1356/2000 [00:18<00:09, 66.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  68%|██████▊   | 1367/2000 [00:18<00:08, 74.59it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  69%|██████▉   | 1378/2000 [00:18<00:07, 81.03it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  69%|██████▉   | 1389/2000 [00:18<00:07, 86.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  69%|██████▉   | 1389/2000 [00:18<00:07, 86.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  70%|███████   | 1400/2000 [00:18<00:09, 65.92it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  71%|███████   | 1411/2000 [00:18<00:07, 74.03it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  71%|███████   | 1422/2000 [00:18<00:07, 81.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  72%|███████▏  | 1433/2000 [00:18<00:06, 87.08it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  72%|███████▏  | 1444/2000 [00:19<00:06, 91.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  72%|███████▏  | 1444/2000 [00:19<00:06, 91.63it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  73%|███████▎  | 1454/2000 [00:19<00:08, 68.09it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  73%|███████▎  | 1465/2000 [00:19<00:07, 76.23it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  74%|███████▍  | 1476/2000 [00:19<00:06, 83.03it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  74%|███████▍  | 1487/2000 [00:19<00:05, 88.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  75%|███████▍  | 1498/2000 [00:19<00:05, 93.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  75%|███████▍  | 1498/2000 [00:19<00:05, 93.00it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  75%|███████▌  | 1508/2000 [00:19<00:07, 68.54it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  76%|███████▌  | 1519/2000 [00:20<00:06, 76.64it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  76%|███████▋  | 1530/2000 [00:20<00:05, 83.40it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  77%|███████▋  | 1541/2000 [00:20<00:05, 88.77it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  77%|███████▋  | 1541/2000 [00:20<00:05, 88.77it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  78%|███████▊  | 1551/2000 [00:20<00:06, 66.70it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  78%|███████▊  | 1562/2000 [00:20<00:05, 74.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  79%|███████▊  | 1573/2000 [00:20<00:05, 82.10it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  79%|███████▉  | 1584/2000 [00:20<00:04, 87.74it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  80%|███████▉  | 1595/2000 [00:20<00:04, 92.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  80%|███████▉  | 1595/2000 [00:21<00:04, 92.20it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  80%|████████  | 1605/2000 [00:21<00:05, 67.97it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  81%|████████  | 1616/2000 [00:21<00:05, 75.72it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  81%|████████▏ | 1627/2000 [00:21<00:04, 82.66it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  82%|████████▏ | 1638/2000 [00:21<00:04, 88.28it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  82%|████████▏ | 1649/2000 [00:21<00:03, 92.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  82%|████████▏ | 1649/2000 [00:21<00:03, 92.58it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  83%|████████▎ | 1659/2000 [00:21<00:05, 68.19it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  84%|████████▎ | 1670/2000 [00:21<00:04, 76.33it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  84%|████████▍ | 1681/2000 [00:22<00:03, 83.14it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  85%|████████▍ | 1692/2000 [00:22<00:03, 88.55it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  85%|████████▍ | 1692/2000 [00:22<00:03, 88.55it/s, test=99.8%, test_loss=0.000, train=99.7%, train_loss=0.000]

outcome_architecture/process:  85%|████████▌ | 1702/2000 [00:22<00:04, 66.36it/s, test=99.8%, test_loss=0.000, train=99.7%, train_loss=0.000]

outcome_architecture/process:  86%|████████▌ | 1713/2000 [00:22<00:03, 74.89it/s, test=99.8%, test_loss=0.000, train=99.7%, train_loss=0.000]

outcome_architecture/process:  86%|████████▌ | 1724/2000 [00:22<00:03, 82.01it/s, test=99.8%, test_loss=0.000, train=99.7%, train_loss=0.000]

outcome_architecture/process:  87%|████████▋ | 1735/2000 [00:22<00:03, 88.06it/s, test=99.8%, test_loss=0.000, train=99.7%, train_loss=0.000]

outcome_architecture/process:  87%|████████▋ | 1746/2000 [00:22<00:02, 92.62it/s, test=99.8%, test_loss=0.000, train=99.7%, train_loss=0.000]

outcome_architecture/process:  87%|████████▋ | 1746/2000 [00:22<00:02, 92.62it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  88%|████████▊ | 1756/2000 [00:23<00:03, 68.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  88%|████████▊ | 1767/2000 [00:23<00:03, 76.68it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  89%|████████▉ | 1778/2000 [00:23<00:02, 83.57it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  89%|████████▉ | 1789/2000 [00:23<00:02, 89.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  89%|████████▉ | 1789/2000 [00:23<00:02, 89.15it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  90%|█████████ | 1800/2000 [00:23<00:02, 67.79it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  91%|█████████ | 1811/2000 [00:23<00:02, 75.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  91%|█████████ | 1822/2000 [00:23<00:02, 83.06it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  92%|█████████▏| 1833/2000 [00:23<00:01, 88.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  92%|█████████▏| 1844/2000 [00:24<00:01, 93.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  92%|█████████▏| 1844/2000 [00:24<00:01, 93.35it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  93%|█████████▎| 1854/2000 [00:24<00:02, 68.88it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  93%|█████████▎| 1865/2000 [00:24<00:01, 76.98it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  94%|█████████▍| 1876/2000 [00:24<00:01, 83.84it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  94%|█████████▍| 1887/2000 [00:24<00:01, 89.37it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  95%|█████████▍| 1898/2000 [00:24<00:01, 93.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  95%|█████████▍| 1898/2000 [00:24<00:01, 93.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  95%|█████████▌| 1908/2000 [00:24<00:01, 68.78it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  96%|█████████▌| 1919/2000 [00:25<00:01, 76.99it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  96%|█████████▋| 1930/2000 [00:25<00:00, 83.81it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  97%|█████████▋| 1941/2000 [00:25<00:00, 89.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  97%|█████████▋| 1941/2000 [00:25<00:00, 89.48it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  98%|█████████▊| 1951/2000 [00:25<00:00, 67.13it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  98%|█████████▊| 1962/2000 [00:25<00:00, 75.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  99%|█████████▊| 1973/2000 [00:25<00:00, 82.85it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process:  99%|█████████▉| 1984/2000 [00:25<00:00, 88.77it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process: 100%|█████████▉| 1995/2000 [00:25<00:00, 93.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process: 100%|█████████▉| 1995/2000 [00:26<00:00, 93.30it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

outcome_architecture/process: 100%|██████████| 2000/2000 [00:26<00:00, 76.61it/s, test=100.0%, test_loss=0.000, train=100.0%, train_loss=0.000]

architecture/mode: 100%|██████████| 4/4 [01:10<00:00, 20.13s/it]

architecture/mode: 100%|██████████| 4/4 [01:10<00:00, 17.73s/it]

,step,architecture,mode,train_loss,train_answer_accuracy_sample,test_answer_accuracy,test_exact_continuation,test_loss
0,0,process_architecture,outcome,4.274016,0.0,0.0,0.0,4.273914
1,1,process_architecture,outcome,4.218189,0.0,0.0,0.0,4.218158
2,2,process_architecture,outcome,4.137219,0.0,0.0,0.0,4.137338
3,5,process_architecture,outcome,3.089416,0.0,0.0,0.0,3.085494
4,10,process_architecture,outcome,1.798246,0.0,0.0,0.0,1.788273
...,...,...,...,...,...,...,...,...
187,1800,outcome_architecture,process,0.000067,1.0,1.0,1.0,0.000082
188,1850,outcome_architecture,process,0.000061,1.0,1.0,1.0,0.000071
189,1900,outcome_architecture,process,0.000058,1.0,1.0,1.0,0.000055
190,1950,outcome_architecture,process,0.000050,1.0,1.0,1.0,0.000053
191,2000,outcome_architecture,process,0.000044,1.0,1.0,1.0,0.000051

In [13]:

import json as _json, numpy as _np, pandas as _pd
def _clean(df):
    df = df.drop(columns=["circuit_matrix"], errors="ignore").copy()
    return _json.loads(df.to_json(orient="records"))

_payload = {
    "model_seed": MODEL_SEED,
    "steps": STEPS,
    "final_results": _clean(final_results),
    "history": _clean(history),
}
try:
    _payload["history_2x2"] = _clean(history_2x2)
except NameError:
    _payload["history_2x2"] = None

with open(_OUT_JSON, "w") as _f:
    _json.dump(_payload, _f, indent=2)
print("WROTE", _OUT_JSON)

WROTE /home/hariguru/aayus/trace/results/reachability_seeds/seed_45.json